{{
    config(
        schema="cl_chilecompra_mercado_publico",
        alias="licitacion_item",
        materialized="table",
        partition_by={
            "field": "ano",
            "data_type": "int64",
            "range": {"start": 2007, "end": 2031, "interval": 1},
        },
        cluster_by=["mes"],
    )
}}


select
    safe_cast(ano as int64) ano,
    safe_cast(mes as int64) mes,
    safe_cast(codigo_licitacion as string) codigo_licitacion,
    safe_cast(codigo_item as string) codigo_item,
    safe_cast(id_licitacion as string) id_licitacion,
    safe_cast(url as string) url,
    safe_cast(nombre as string) nombre,
    safe_cast(descripcion as string) descripcion,
    safe_cast(tipo_adquisicion as string) tipo_adquisicion,
    safe_cast(codigo_estado as string) codigo_estado,
    safe_cast(estado as string) estado,
    safe_cast(codigo_estado_licitacion as string) codigo_estado_licitacion,
    safe_cast(codigo_organismo as string) codigo_organismo,
    safe_cast(nombre_organismo as string) nombre_organismo,
    safe_cast(sector as string) sector,
    safe_cast(rut_unidad_compra as string) rut_unidad_compra,
    safe_cast(codigo_unidad_compra as string) codigo_unidad_compra,
    safe_cast(nombre_unidad_compra as string) nombre_unidad_compra,
    safe_cast(direccion_unidad_compra as string) direccion_unidad_compra,
    safe_cast(comuna_unidad_compra as string) comuna_unidad_compra,
    safe_cast(region_unidad_compra as string) region_unidad_compra,
    safe_cast(indicador_informada as string) indicador_informada,
    safe_cast(codigo_tipo as string) codigo_tipo,
    safe_cast(sigla_tipo as string) sigla_tipo,
    safe_cast(tipo_convocatoria as string) tipo_convocatoria,
    safe_cast(codigo_moneda as string) codigo_moneda,
    safe_cast(moneda as string) moneda,
    safe_cast(moneda_oferta as string) moneda_oferta,
    safe_cast(cantidad_etapas as int64) cantidad_etapas,
    safe_cast(estado_etapas as string) estado_etapas,
    safe_cast(toma_razon as string) toma_razon,
    safe_cast(estado_publicidad_ofertas as string) estado_publicidad_ofertas,
    safe_cast(justificacion_publicidad as string) justificacion_publicidad,
    safe_cast(estado_cs as string) estado_cs,
    safe_cast(codigo_contrato as string) codigo_contrato,
    safe_cast(indicador_obras as string) indicador_obras,
    safe_cast(cantidad_reclamos as int64) cantidad_reclamos,
    safe_cast(fecha_creacion as date) fecha_creacion,
    safe_cast(fecha_publicacion as date) fecha_publicacion,
    safe_cast(fecha_cierre as date) fecha_cierre,
    safe_cast(fecha_inicio as date) fecha_inicio,
    safe_cast(fecha_final as date) fecha_final,
    safe_cast(fecha_pub_respuestas as date) fecha_pub_respuestas,
    safe_cast(fecha_acto_apertura_tecnica as date) fecha_acto_apertura_tecnica,
    safe_cast(fecha_acto_apertura_economica as date) fecha_acto_apertura_economica,
    safe_cast(fecha_adjudicacion as date) fecha_adjudicacion,
    safe_cast(fecha_estimada_adjudicacion as date) fecha_estimada_adjudicacion,
    safe_cast(fecha_soporte_fisico as date) fecha_soporte_fisico,
    safe_cast(fecha_tiempo_evaluacion as date) fecha_tiempo_evaluacion,
    safe_cast(unidad_tiempo_evaluacion as string) unidad_tiempo_evaluacion,
    safe_cast(fecha_estimada_firma as date) fecha_estimada_firma,
    safe_cast(fechas_usuario as string) fechas_usuario,
    safe_cast(fecha_visita_terreno as date) fecha_visita_terreno,
    safe_cast(direccion_visita as string) direccion_visita,
    safe_cast(fecha_entrega_antecedentes as date) fecha_entrega_antecedentes,
    safe_cast(direccion_entrega as string) direccion_entrega,
    safe_cast(estimacion as string) estimacion,
    safe_cast(fuente_financiamiento as string) fuente_financiamiento,
    safe_cast(visibilidad_monto as string) visibilidad_monto,
    safe_cast(monto_estimado as float64) monto_estimado,
    safe_cast(monto_estimado_adjudicado as float64) monto_estimado_adjudicado,
    safe_cast(justificacion_monto_estimado as string) justificacion_monto_estimado,
    safe_cast(tiempo as int64) tiempo,
    safe_cast(unidad_tiempo as string) unidad_tiempo,
    safe_cast(modalidad as string) modalidad,
    safe_cast(tipo_pago as string) tipo_pago,
    safe_cast(prohibicion_contratacion as string) prohibicion_contratacion,
    safe_cast(subcontratacion as string) subcontratacion,
    safe_cast(
        unidad_tiempo_duracion_contrato as string
    ) unidad_tiempo_duracion_contrato,
    safe_cast(tiempo_duracion_contrato as int64) tiempo_duracion_contrato,
    safe_cast(tipo_duracion_contrato as string) tipo_duracion_contrato,
    safe_cast(observacion_contrato as string) observacion_contrato,
    safe_cast(extension_plazo as string) extension_plazo,
    safe_cast(indicador_base_tipo as string) indicador_base_tipo,
    safe_cast(unidad_tiempo_contrato as string) unidad_tiempo_contrato,
    safe_cast(valor_tiempo_renovacion as int64) valor_tiempo_renovacion,
    safe_cast(periodo_tiempo_renovacion as string) periodo_tiempo_renovacion,
    safe_cast(indicador_renovable as string) indicador_renovable,
    safe_cast(tipo_aprobacion as string) tipo_aprobacion,
    safe_cast(numero_aprobacion as string) numero_aprobacion,
    safe_cast(fecha_aprobacion as date) fecha_aprobacion,
    safe_cast(cantidad_oferentes as int64) cantidad_oferentes,
    safe_cast(
        indicador_criterios_ambientales as string
    ) indicador_criterios_ambientales,
    safe_cast(
        descripcion_criterios_ambientales as string
    ) descripcion_criterios_ambientales,
    safe_cast(indicador_criterios_sociales as string) indicador_criterios_sociales,
    safe_cast(descripcion_criterios_sociales as string) descripcion_criterios_sociales,
    safe_cast(
        descripcion_criterios_sociales_2 as string
    ) descripcion_criterios_sociales_2,
    safe_cast(criterios_evaluacion as string) criterios_evaluacion,
    safe_cast(correlativo_item as string) correlativo_item,
    safe_cast(codigo_producto_onu as string) codigo_producto_onu,
    safe_cast(rubro_n1 as string) rubro_n1,
    safe_cast(rubro_n2 as string) rubro_n2,
    safe_cast(rubro_n3 as string) rubro_n3,
    safe_cast(nombre_producto_generico as string) nombre_producto_generico,
    safe_cast(nombre_linea as string) nombre_linea,
    safe_cast(descripcion_linea as string) descripcion_linea,
    safe_cast(unidad_medida as string) unidad_medida,
    safe_cast(cantidad as float64) cantidad
from
    {{ set_datalake_project("cl_chilecompra_mercado_publico_staging.licitacion_item") }}
    as t
