{{
    config(
        schema="us_dot_fars",
        alias="person",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 1975, "end": 2029, "interval": 1},
        },
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(state_id as string) state_id,
    safe_cast(case_number as string) case_number,
    safe_cast(vehicle_number as int64) vehicle_number,
    safe_cast(person_number as int64) person_number,
    safe_cast(age as int64) age,
    safe_cast(sex_code as string) sex_code,
    safe_cast(person_type_code as string) person_type_code,
    safe_cast(injury_severity_code as string) injury_severity_code,
    safe_cast(seating_position_code as string) seating_position_code,
    safe_cast(restraint_use_code as string) restraint_use_code,
    safe_cast(restraint_misuse_code as string) restraint_misuse_code,
    safe_cast(helmet_use_code as string) helmet_use_code,
    safe_cast(air_bag_code as string) air_bag_code,
    safe_cast(ejection_code as string) ejection_code,
    safe_cast(ejection_path_code as string) ejection_path_code,
    safe_cast(extrication_code as string) extrication_code,
    safe_cast(police_reported_alcohol_code as string) police_reported_alcohol_code,
    safe_cast(alcohol_test_status_code as string) alcohol_test_status_code,
    safe_cast(alcohol_test_type_code as string) alcohol_test_type_code,
    safe_cast(alcohol_test_result_code as string) alcohol_test_result_code,
    safe_cast(blood_alcohol_content as float64) blood_alcohol_content,
    safe_cast(drug_involvement_code as string) drug_involvement_code,
    safe_cast(drug_test_status_code as string) drug_test_status_code,
    safe_cast(transported_to_facility_code as string) transported_to_facility_code,
    safe_cast(died_at_scene_code as string) died_at_scene_code,
    safe_cast(death_date as date) death_date,
    safe_cast(death_hour as int64) death_hour,
    safe_cast(death_minute as int64) death_minute,
    safe_cast(survival_hours as int64) survival_hours,
    safe_cast(survival_minutes as int64) survival_minutes,
    safe_cast(work_injury_code as string) work_injury_code,
    safe_cast(race_code as string) race_code,
    safe_cast(hispanic_origin_code as string) hispanic_origin_code,
    safe_cast(non_motorist_location_code as string) non_motorist_location_code,
    safe_cast(striking_vehicle_number as string) striking_vehicle_number,
    safe_cast(body_type_code as string) body_type_code,
    safe_cast(make_code as string) make_code,
    safe_cast(model_year as int64) model_year,
    safe_cast(rollover_code as string) rollover_code,
    safe_cast(first_harmful_event_code as string) first_harmful_event_code,
    safe_cast(manner_of_collision_code as string) manner_of_collision_code,
    safe_cast(school_bus_related_code as string) school_bus_related_code
from {{ set_datalake_project("us_dot_fars_staging.person") }} as t
