{{
    config(
        schema="us_dot_fars",
        alias="person",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 1975, "end": 2029, "interval": 1},
        },
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(state_id as string) state_id,
    safe_cast(case_number as string) case_number,
    safe_cast(vehicle_number as int64) vehicle_number,
    safe_cast(person_number as int64) person_number,
    safe_cast(age as int64) age,
    safe_cast(sex_code as string) sex_code,
    safe_cast(person_type_code as string) person_type_code,
    safe_cast(injury_severity_code as string) injury_severity_code,
    safe_cast(seating_position_code as string) seating_position_code,
    safe_cast(restraint_use_code as string) restraint_use_code,
    safe_cast(restraint_misuse_code as string) restraint_misuse_code,
    safe_cast(helmet_use_code as string) helmet_use_code,
    safe_cast(air_bag_code as string) air_bag_code,
    safe_cast(ejection_code as string) ejection_code,
    safe_cast(ejection_path_code as string) ejection_path_code,
    safe_cast(extrication_code as string) extrication_code,
    safe_cast(police_reported_alcohol_code as string) police_reported_alcohol_code,
    safe_cast(alcohol_test_status_code as string) alcohol_test_status_code,
    safe_cast(alcohol_test_type_code as string) alcohol_test_type_code,
    safe_cast(alcohol_test_result_code as string) alcohol_test_result_code,
    safe_cast(blood_alcohol_content as float64) blood_alcohol_content,
    safe_cast(drug_involvement_code as string) drug_involvement_code,
    safe_cast(drug_test_status_code as string) drug_test_status_code,
    safe_cast(transported_to_facility_code as string) transported_to_facility_code,
    safe_cast(died_at_scene_code as string) died_at_scene_code,
    safe_cast(death_date as date) death_date,
    safe_cast(death_hour as int64) death_hour,
    safe_cast(death_minute as int64) death_minute,
    safe_cast(survival_hours as int64) survival_hours,
    safe_cast(survival_minutes as int64) survival_minutes,
    safe_cast(work_injury_code as string) work_injury_code,
    safe_cast(race_code as string) race_code,
    safe_cast(hispanic_origin_code as string) hispanic_origin_code,
    safe_cast(non_motorist_location_code as string) non_motorist_location_code,
    safe_cast(striking_vehicle_number as string) striking_vehicle_number,
    safe_cast(body_type_code as string) body_type_code,
    safe_cast(make_code as string) make_code,
    safe_cast(model_year as int64) model_year,
    safe_cast(rollover_code as string) rollover_code,
    safe_cast(first_harmful_event_code as string) first_harmful_event_code,
    safe_cast(manner_of_collision_code as string) manner_of_collision_code,
    safe_cast(school_bus_related_code as string) school_bus_related_code,
    safe_cast(county_id as string) county_id,
    safe_cast(month as int64) month,
    safe_cast(day as int64) day,
    safe_cast(hour as int64) hour,
    safe_cast(minute as int64) minute,
    safe_cast(vehicle_forms_count as int64) vehicle_forms_count,
    safe_cast(death_month as int64) death_month,
    safe_cast(death_day as int64) death_day,
    safe_cast(death_year as int64) death_year,
    safe_cast(death_time_code as string) death_time_code,
    safe_cast(alcohol_determination_method_code as string) alcohol_determination_method_code,
    safe_cast(drug_determination_method_code as string) drug_determination_method_code,
    safe_cast(drug_test_type_1_code as string) drug_test_type_1_code,
    safe_cast(drug_test_type_2_code as string) drug_test_type_2_code,
    safe_cast(drug_test_type_3_code as string) drug_test_type_3_code,
    safe_cast(drug_test_result_1_code as string) drug_test_result_1_code,
    safe_cast(drug_test_result_2_code as string) drug_test_result_2_code,
    safe_cast(drug_test_result_3_code as string) drug_test_result_3_code,
    safe_cast(toxicology_test_code as string) toxicology_test_code,
    safe_cast(person_related_factor_1_code as string) person_related_factor_1_code,
    safe_cast(person_related_factor_2_code as string) person_related_factor_2_code,
    safe_cast(person_related_factor_3_code as string) person_related_factor_3_code,
    safe_cast(helmet_misuse_code as string) helmet_misuse_code,
    safe_cast(non_motorist_device_type_code as string) non_motorist_device_type_code,
    safe_cast(non_motorist_device_motorization_code as string) non_motorist_device_motorization_code,
    safe_cast(striking_vehicle_number_legacy_code as string) striking_vehicle_number_legacy_code,
    safe_cast(death_certificate_number as string) death_certificate_number,
    safe_cast(roadway_function_class_person_code as string) roadway_function_class_person_code,
    safe_cast(rural_urban_person_code as string) rural_urban_person_code,
    safe_cast(functional_system_person_code as string) functional_system_person_code,
    safe_cast(initial_impact_point_code as string) initial_impact_point_code,
    safe_cast(most_damaged_area_code as string) most_damaged_area_code,
    safe_cast(vehicle_role_code as string) vehicle_role_code,
    safe_cast(fire_occurrence_code as string) fire_occurrence_code,
    safe_cast(emergency_use_code as string) emergency_use_code,
    safe_cast(special_use_code as string) special_use_code,
    safe_cast(tow_vehicle_code as string) tow_vehicle_code,
    safe_cast(make_model_code as string) make_model_code,
    safe_cast(gross_vehicle_weight_rating_from_code as string) gross_vehicle_weight_rating_from_code,
    safe_cast(gross_vehicle_weight_rating_to_code as string) gross_vehicle_weight_rating_to_code,
    safe_cast(final_stage_body_class_code as string) final_stage_body_class_code,
    safe_cast(vpic_make_code as string) vpic_make_code,
    safe_cast(vpic_model_code as string) vpic_model_code,
    safe_cast(vpic_body_class_code as string) vpic_body_class_code,
    safe_cast(vin_make as string) vin_make,
    safe_cast(vin_model as string) vin_model,
    safe_cast(vin_body_type as string) vin_body_type,
    safe_cast(vin_vehicle_type as string) vin_vehicle_type,
    safe_cast(vin_model_year_code as string) vin_model_year_code,
    safe_cast(vin_length as int64) vin_length,
    safe_cast(vin_curb_weight as int64) vin_curb_weight,
    safe_cast(wheelbase_short as int64) wheelbase_short,
    safe_cast(wheelbase_long as int64) wheelbase_long,
    safe_cast(motorcycle_engine_displacement as int64) motorcycle_engine_displacement,
    safe_cast(motorcycle_engine_cycles_code as string) motorcycle_engine_cycles_code,
    safe_cast(motorcycle_dry_weight as int64) motorcycle_dry_weight,
    safe_cast(engine_displacement_cubic_inch as int64) engine_displacement_cubic_inch,
    safe_cast(truck_shipping_weight as int64) truck_shipping_weight,
    safe_cast(truck_shipping_weight_variance_code as string) truck_shipping_weight_variance_code,
    safe_cast(truck_weight_rating_code as string) truck_weight_rating_code,
    safe_cast(truck_series as string) truck_series,
    safe_cast(wheels_and_drive_wheels_code as string) wheels_and_drive_wheels_code,
    safe_cast(carburetion as string) carburetion,
    safe_cast(cylinders as string) cylinders,
    safe_cast(fuel_code as string) fuel_code,
    safe_cast(original_tire_size as string) original_tire_size,
    safe_cast(truck_ton_rating as string) truck_ton_rating,
    safe_cast(truck_vin_restraint_type as string) truck_vin_restraint_type
from {{ set_datalake_project("us_dot_fars_staging.person") }} as t
