{{
    config(
        alias="respondent_cycle_1",
        schema="world_oecd_piaac",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 2012, "end": 2028, "interval": 1},
        },
        cluster_by=["country_id_iso_3"],
    )
}}


select
    safe_cast(year as int64) year,
    nullif(trim(safe_cast(cycle as string)), '') cycle,
    nullif(trim(safe_cast(round as string)), '') round,
    nullif(trim(safe_cast(country_id_iso_3 as string)), '') country_id_iso_3,
    nullif(trim(safe_cast(country_id_m49 as string)), '') country_id_m49,
    nullif(trim(safe_cast(country_entity_id as string)), '') country_entity_id,
    nullif(trim(safe_cast(respondent_id as string)), '') respondent_id,
    safe_cast(age_r as int64) age_r,
    nullif(trim(safe_cast(gender_r as string)), '') gender_r,
    nullif(trim(safe_cast(disp_cibq as string)), '') disp_cibq,
    nullif(trim(safe_cast(disp_main as string)), '') disp_main,
    nullif(trim(safe_cast(disp_mainwrc as string)), '') disp_mainwrc,
    nullif(trim(safe_cast(a_n01_t as string)), '') a_n01_t,
    nullif(trim(safe_cast(b_q01a as string)), '') b_q01a,
    nullif(trim(safe_cast(b_q01a_t as string)), '') b_q01a_t,
    nullif(trim(safe_cast(b_q01a3 as string)), '') b_q01a3,
    nullif(trim(safe_cast(b_q01a3_c as string)), '') b_q01a3_c,
    nullif(trim(safe_cast(b_q01b as string)), '') b_q01b,
    safe_cast(b_q01c1 as int64) b_q01c1,
    nullif(trim(safe_cast(b_q01c1_c as string)), '') b_q01c1_c,
    safe_cast(b_q01c1_t as int64) b_q01c1_t,
    safe_cast(b_q01c2 as int64) b_q01c2,
    nullif(trim(safe_cast(b_q01d as string)), '') b_q01d,
    safe_cast(b_d01d as int64) b_d01d,
    nullif(trim(safe_cast(b_d01d_c as string)), '') b_d01d_c,
    nullif(trim(safe_cast(b_q02a as string)), '') b_q02a,
    nullif(trim(safe_cast(b_q02a_t1 as string)), '') b_q02a_t1,
    nullif(trim(safe_cast(b_q02a_t2 as string)), '') b_q02a_t2,
    nullif(trim(safe_cast(b_q02b as string)), '') b_q02b,
    nullif(trim(safe_cast(b_q02b_c as string)), '') b_q02b_c,
    nullif(trim(safe_cast(b_q02c as string)), '') b_q02c,
    nullif(trim(safe_cast(b_q03a as string)), '') b_q03a,
    nullif(trim(safe_cast(b_q03b as string)), '') b_q03b,
    nullif(trim(safe_cast(b_q03b_c as string)), '') b_q03b_c,
    safe_cast(b_q03c1 as int64) b_q03c1,
    nullif(trim(safe_cast(b_q03c1_c as string)), '') b_q03c1_c,
    safe_cast(b_q03c2 as int64) b_q03c2,
    nullif(trim(safe_cast(b_q03d as string)), '') b_q03d,
    safe_cast(b_d03d as int64) b_d03d,
    nullif(trim(safe_cast(b_d03d_c as string)), '') b_d03d_c,
    nullif(trim(safe_cast(b_q04a as string)), '') b_q04a,
    safe_cast(b_q04b as int64) b_q04b,
    safe_cast(b_q04b_c as int64) b_q04b_c,
    nullif(trim(safe_cast(b_q05a as string)), '') b_q05a,
    nullif(trim(safe_cast(b_q05b as string)), '') b_q05b,
    nullif(trim(safe_cast(b_q05c as string)), '') b_q05c,
    nullif(trim(safe_cast(b_q05c_t as string)), '') b_q05c_t,
    nullif(trim(safe_cast(b_q10a as string)), '') b_q10a,
    nullif(trim(safe_cast(b_q10b as string)), '') b_q10b,
    nullif(trim(safe_cast(b_q10c as string)), '') b_q10c,
    nullif(trim(safe_cast(b_q11 as string)), '') b_q11,
    nullif(trim(safe_cast(b_q12a as string)), '') b_q12a,
    nullif(trim(safe_cast(b_q12a_t as string)), '') b_q12a_t,
    safe_cast(b_q12b as int64) b_q12b,
    nullif(trim(safe_cast(b_q12c as string)), '') b_q12c,
    safe_cast(b_q12d as int64) b_q12d,
    safe_cast(b_q12d_c as int64) b_q12d_c,
    nullif(trim(safe_cast(b_q12e as string)), '') b_q12e,
    safe_cast(b_q12f as int64) b_q12f,
    safe_cast(b_q12f_c as int64) b_q12f_c,
    nullif(trim(safe_cast(b_q12g as string)), '') b_q12g,
    safe_cast(b_q12h as int64) b_q12h,
    safe_cast(b_q12h_c as int64) b_q12h_c,
    nullif(trim(safe_cast(b_d12h as string)), '') b_d12h,
    nullif(trim(safe_cast(b_q13 as string)), '') b_q13,
    nullif(trim(safe_cast(b_q14a as string)), '') b_q14a,
    nullif(trim(safe_cast(b_q14b as string)), '') b_q14b,
    nullif(trim(safe_cast(b_q15a as string)), '') b_q15a,
    nullif(trim(safe_cast(b_q15b as string)), '') b_q15b,
    nullif(trim(safe_cast(b_q15c as string)), '') b_q15c,
    nullif(trim(safe_cast(b_q16 as string)), '') b_q16,
    nullif(trim(safe_cast(b_q17 as string)), '') b_q17,
    safe_cast(b_q18a as int64) b_q18a,
    safe_cast(b_q19a as int64) b_q19a,
    safe_cast(b_q20a as int64) b_q20a,
    nullif(trim(safe_cast(b_q20b as string)), '') b_q20b,
    nullif(trim(safe_cast(b_q26a as string)), '') b_q26a,
    nullif(trim(safe_cast(b_q26a_t as string)), '') b_q26a_t,
    nullif(trim(safe_cast(b_q26b as string)), '') b_q26b,
    nullif(trim(safe_cast(c_q01a as string)), '') c_q01a,
    nullif(trim(safe_cast(c_q01b as string)), '') c_q01b,
    nullif(trim(safe_cast(c_q01c as string)), '') c_q01c,
    nullif(trim(safe_cast(c_q02a as string)), '') c_q02a,
    nullif(trim(safe_cast(c_q02b as string)), '') c_q02b,
    nullif(trim(safe_cast(c_q02c as string)), '') c_q02c,
    nullif(trim(safe_cast(c_q03_01 as string)), '') c_q03_01,
    nullif(trim(safe_cast(c_q03_02 as string)), '') c_q03_02,
    nullif(trim(safe_cast(c_q03_03 as string)), '') c_q03_03,
    nullif(trim(safe_cast(c_q03_04 as string)), '') c_q03_04,
    nullif(trim(safe_cast(c_q03_05 as string)), '') c_q03_05,
    nullif(trim(safe_cast(c_q03_06 as string)), '') c_q03_06,
    nullif(trim(safe_cast(c_q03_07 as string)), '') c_q03_07,
    nullif(trim(safe_cast(c_q03_08 as string)), '') c_q03_08,
    nullif(trim(safe_cast(c_q03_09 as string)), '') c_q03_09,
    nullif(trim(safe_cast(c_q03_10 as string)), '') c_q03_10,
    safe_cast(c_s03 as int64) c_s03,
    nullif(trim(safe_cast(c_q04a as string)), '') c_q04a,
    nullif(trim(safe_cast(c_q04b as string)), '') c_q04b,
    nullif(trim(safe_cast(c_q04c as string)), '') c_q04c,
    nullif(trim(safe_cast(c_q04d as string)), '') c_q04d,
    nullif(trim(safe_cast(c_q04e as string)), '') c_q04e,
    nullif(trim(safe_cast(c_q04f as string)), '') c_q04f,
    nullif(trim(safe_cast(c_q04g as string)), '') c_q04g,
    nullif(trim(safe_cast(c_q04h as string)), '') c_q04h,
    nullif(trim(safe_cast(c_q04i as string)), '') c_q04i,
    nullif(trim(safe_cast(c_q04j as string)), '') c_q04j,
    nullif(trim(safe_cast(c_d04 as string)), '') c_d04,
    nullif(trim(safe_cast(c_q05 as string)), '') c_q05,
    nullif(trim(safe_cast(c_d05 as string)), '') c_d05,
    nullif(trim(safe_cast(c_q06 as string)), '') c_q06,
    nullif(trim(safe_cast(c_d06 as string)), '') c_d06,
    nullif(trim(safe_cast(c_q07 as string)), '') c_q07,
    nullif(trim(safe_cast(c_q07_t as string)), '') c_q07_t,
    nullif(trim(safe_cast(c_q08a as string)), '') c_q08a,
    nullif(trim(safe_cast(c_q08b as string)), '') c_q08b,
    safe_cast(c_q08c1 as int64) c_q08c1,
    nullif(trim(safe_cast(c_q08c1_c as string)), '') c_q08c1_c,
    safe_cast(c_q08c2 as int64) c_q08c2,
    nullif(trim(safe_cast(c_d08c as string)), '') c_d08c,
    safe_cast(c_q09 as int64) c_q09,
    safe_cast(c_q09_c as int64) c_q09_c,
    nullif(trim(safe_cast(c_d09 as string)), '') c_d09,
    nullif(trim(safe_cast(c_d09_t as string)), '') c_d09_t,
    safe_cast(c_q10a as int64) c_q10a,
    safe_cast(c_q10a_c as int64) c_q10a_c,
    nullif(trim(safe_cast(d_q03 as string)), '') d_q03,
    nullif(trim(safe_cast(d_q04 as string)), '') d_q04,
    nullif(trim(safe_cast(d_q04_t as string)), '') d_q04_t,
    nullif(trim(safe_cast(d_q04_t1 as string)), '') d_q04_t1,
    safe_cast(d_q05a1 as int64) d_q05a1,
    nullif(trim(safe_cast(d_q05a1_c as string)), '') d_q05a1_c,
    safe_cast(d_q05a2 as int64) d_q05a2,
    nullif(trim(safe_cast(d_q05a3 as string)), '') d_q05a3,
    safe_cast(d_q05b1 as int64) d_q05b1,
    nullif(trim(safe_cast(d_q05b1_c as string)), '') d_q05b1_c,
    safe_cast(d_q05b2 as int64) d_q05b2,
    nullif(trim(safe_cast(d_q05b3 as string)), '') d_q05b3,
    nullif(trim(safe_cast(d_q06a as string)), '') d_q06a,
    nullif(trim(safe_cast(d_q06b as string)), '') d_q06b,
    nullif(trim(safe_cast(d_q06c as string)), '') d_q06c,
    nullif(trim(safe_cast(d_q07a as string)), '') d_q07a,
    nullif(trim(safe_cast(d_q07b as string)), '') d_q07b,
    nullif(trim(safe_cast(d_q07b_c as string)), '') d_q07b_c,
    nullif(trim(safe_cast(d_q08a as string)), '') d_q08a,
    nullif(trim(safe_cast(d_q08b as string)), '') d_q08b,
    nullif(trim(safe_cast(d_q09 as string)), '') d_q09,
    safe_cast(d_q10 as int64) d_q10,
    safe_cast(d_q10_c as int64) d_q10_c,
    safe_cast(d_q10_t as int64) d_q10_t,
    nullif(trim(safe_cast(d_q10_t1 as string)), '') d_q10_t1,
    nullif(trim(safe_cast(d_q11a as string)), '') d_q11a,
    nullif(trim(safe_cast(d_q11b as string)), '') d_q11b,
    nullif(trim(safe_cast(d_q11c as string)), '') d_q11c,
    nullif(trim(safe_cast(d_q11d as string)), '') d_q11d,
    nullif(trim(safe_cast(d_q12a as string)), '') d_q12a,
    nullif(trim(safe_cast(d_q12b as string)), '') d_q12b,
    nullif(trim(safe_cast(d_q12c as string)), '') d_q12c,
    nullif(trim(safe_cast(d_q13a as string)), '') d_q13a,
    nullif(trim(safe_cast(d_q13b as string)), '') d_q13b,
    nullif(trim(safe_cast(d_q13c as string)), '') d_q13c,
    nullif(trim(safe_cast(d_q14 as string)), '') d_q14,
    nullif(trim(safe_cast(d_q16a as string)), '') d_q16a,
    safe_cast(d_s16a as float64) d_s16a,
    safe_cast(d_d16a as float64) d_d16a,
    safe_cast(d_q16b as float64) d_q16b,
    nullif(trim(safe_cast(d_q16b_t as string)), '') d_q16b_t,
    nullif(trim(safe_cast(d_q16c as string)), '') d_q16c,
    nullif(trim(safe_cast(d_q16d1 as string)), '') d_q16d1,
    nullif(trim(safe_cast(d_q16d2 as string)), '') d_q16d2,
    nullif(trim(safe_cast(d_q16d3 as string)), '') d_q16d3,
    nullif(trim(safe_cast(d_q16d4 as string)), '') d_q16d4,
    nullif(trim(safe_cast(d_q16d5 as string)), '') d_q16d5,
    nullif(trim(safe_cast(d_q16d6 as string)), '') d_q16d6,
    nullif(trim(safe_cast(d_q17a as string)), '') d_q17a,
    safe_cast(d_q17b as int64) d_q17b,
    nullif(trim(safe_cast(d_q17c as string)), '') d_q17c,
    nullif(trim(safe_cast(d_q17d as string)), '') d_q17d,
    safe_cast(d_q18a as int64) d_q18a,
    nullif(trim(safe_cast(d_q18a_t as string)), '') d_q18a_t,
    nullif(trim(safe_cast(d_q18b as string)), '') d_q18b,
    nullif(trim(safe_cast(d_q18c1 as string)), '') d_q18c1,
    nullif(trim(safe_cast(d_q18c2 as string)), '') d_q18c2,
    nullif(trim(safe_cast(e_q03 as string)), '') e_q03,
    nullif(trim(safe_cast(e_q04 as string)), '') e_q04,
    safe_cast(e_q05a1 as int64) e_q05a1,
    nullif(trim(safe_cast(e_q05a1_c as string)), '') e_q05a1_c,
    safe_cast(e_q05a2 as int64) e_q05a2,
    safe_cast(e_q05b1 as int64) e_q05b1,
    nullif(trim(safe_cast(e_q05b1_c as string)), '') e_q05b1_c,
    safe_cast(e_q05b2 as int64) e_q05b2,
    nullif(trim(safe_cast(e_q06 as string)), '') e_q06,
    nullif(trim(safe_cast(e_q07a as string)), '') e_q07a,
    nullif(trim(safe_cast(e_q07b as string)), '') e_q07b,
    nullif(trim(safe_cast(e_q08 as string)), '') e_q08,
    safe_cast(e_q09 as int64) e_q09,
    safe_cast(e_q09_c as int64) e_q09_c,
    nullif(trim(safe_cast(e_q10 as string)), '') e_q10,
    nullif(trim(safe_cast(f_q01b as string)), '') f_q01b,
    nullif(trim(safe_cast(f_q02a as string)), '') f_q02a,
    nullif(trim(safe_cast(f_q02b as string)), '') f_q02b,
    nullif(trim(safe_cast(f_q02c as string)), '') f_q02c,
    nullif(trim(safe_cast(f_q02d as string)), '') f_q02d,
    nullif(trim(safe_cast(f_q02e as string)), '') f_q02e,
    nullif(trim(safe_cast(f_q03a as string)), '') f_q03a,
    nullif(trim(safe_cast(f_q03b as string)), '') f_q03b,
    nullif(trim(safe_cast(f_q03c as string)), '') f_q03c,
    nullif(trim(safe_cast(f_q04a as string)), '') f_q04a,
    nullif(trim(safe_cast(f_q04b as string)), '') f_q04b,
    nullif(trim(safe_cast(f_q05a as string)), '') f_q05a,
    nullif(trim(safe_cast(f_q05b as string)), '') f_q05b,
    nullif(trim(safe_cast(f_q06b as string)), '') f_q06b,
    nullif(trim(safe_cast(f_q06c as string)), '') f_q06c,
    nullif(trim(safe_cast(f_q07a as string)), '') f_q07a,
    nullif(trim(safe_cast(f_q07b as string)), '') f_q07b,
    nullif(trim(safe_cast(g_q01a as string)), '') g_q01a,
    nullif(trim(safe_cast(g_q01a_t as string)), '') g_q01a_t,
    nullif(trim(safe_cast(g_q01a_t1 as string)), '') g_q01a_t1,
    nullif(trim(safe_cast(g_q01b as string)), '') g_q01b,
    nullif(trim(safe_cast(g_q01b_t as string)), '') g_q01b_t,
    nullif(trim(safe_cast(g_q01b_t1 as string)), '') g_q01b_t1,
    nullif(trim(safe_cast(g_q01c as string)), '') g_q01c,
    nullif(trim(safe_cast(g_q01c_t as string)), '') g_q01c_t,
    nullif(trim(safe_cast(g_q01c_t1 as string)), '') g_q01c_t1,
    nullif(trim(safe_cast(g_q01d as string)), '') g_q01d,
    nullif(trim(safe_cast(g_q01e as string)), '') g_q01e,
    nullif(trim(safe_cast(g_q01f as string)), '') g_q01f,
    nullif(trim(safe_cast(g_q01f_t as string)), '') g_q01f_t,
    nullif(trim(safe_cast(g_q01f_t1 as string)), '') g_q01f_t1,
    nullif(trim(safe_cast(g_q01g as string)), '') g_q01g,
    nullif(trim(safe_cast(g_q01g_t as string)), '') g_q01g_t,
    nullif(trim(safe_cast(g_q01g_t1 as string)), '') g_q01g_t1,
    nullif(trim(safe_cast(g_q01h as string)), '') g_q01h,
    nullif(trim(safe_cast(g_q01h_t as string)), '') g_q01h_t,
    nullif(trim(safe_cast(g_q01h_t1 as string)), '') g_q01h_t1,
    nullif(trim(safe_cast(g_q02a as string)), '') g_q02a,
    nullif(trim(safe_cast(g_q02b as string)), '') g_q02b,
    nullif(trim(safe_cast(g_q02c as string)), '') g_q02c,
    nullif(trim(safe_cast(g_q02d as string)), '') g_q02d,
    nullif(trim(safe_cast(g_q03b as string)), '') g_q03b,
    nullif(trim(safe_cast(g_q03c as string)), '') g_q03c,
    nullif(trim(safe_cast(g_q03d as string)), '') g_q03d,
    nullif(trim(safe_cast(g_q03f as string)), '') g_q03f,
    nullif(trim(safe_cast(g_q03g as string)), '') g_q03g,
    nullif(trim(safe_cast(g_q03h as string)), '') g_q03h,
    nullif(trim(safe_cast(g_q04 as string)), '') g_q04,
    nullif(trim(safe_cast(g_q04_t as string)), '') g_q04_t,
    nullif(trim(safe_cast(g_q05a as string)), '') g_q05a,
    nullif(trim(safe_cast(g_q05c as string)), '') g_q05c,
    nullif(trim(safe_cast(g_q05d as string)), '') g_q05d,
    nullif(trim(safe_cast(g_q05e as string)), '') g_q05e,
    nullif(trim(safe_cast(g_q05f as string)), '') g_q05f,
    nullif(trim(safe_cast(g_q05g as string)), '') g_q05g,
    nullif(trim(safe_cast(g_q05h as string)), '') g_q05h,
    nullif(trim(safe_cast(g_q06 as string)), '') g_q06,
    nullif(trim(safe_cast(g_q07 as string)), '') g_q07,
    nullif(trim(safe_cast(g_q08 as string)), '') g_q08,
    nullif(trim(safe_cast(h_q01a as string)), '') h_q01a,
    nullif(trim(safe_cast(h_q01b as string)), '') h_q01b,
    nullif(trim(safe_cast(h_q01b_t as string)), '') h_q01b_t,
    nullif(trim(safe_cast(h_q01c as string)), '') h_q01c,
    nullif(trim(safe_cast(h_q01c_t as string)), '') h_q01c_t,
    nullif(trim(safe_cast(h_q01d as string)), '') h_q01d,
    nullif(trim(safe_cast(h_q01e as string)), '') h_q01e,
    nullif(trim(safe_cast(h_q01e_t as string)), '') h_q01e_t,
    nullif(trim(safe_cast(h_q01f as string)), '') h_q01f,
    nullif(trim(safe_cast(h_q01g as string)), '') h_q01g,
    nullif(trim(safe_cast(h_q01h as string)), '') h_q01h,
    nullif(trim(safe_cast(h_q02a as string)), '') h_q02a,
    nullif(trim(safe_cast(h_q02b as string)), '') h_q02b,
    nullif(trim(safe_cast(h_q02c as string)), '') h_q02c,
    nullif(trim(safe_cast(h_q02d as string)), '') h_q02d,
    nullif(trim(safe_cast(h_q03b as string)), '') h_q03b,
    nullif(trim(safe_cast(h_q03c as string)), '') h_q03c,
    nullif(trim(safe_cast(h_q03d as string)), '') h_q03d,
    nullif(trim(safe_cast(h_q03f as string)), '') h_q03f,
    nullif(trim(safe_cast(h_q03g as string)), '') h_q03g,
    nullif(trim(safe_cast(h_q03h as string)), '') h_q03h,
    nullif(trim(safe_cast(h_q04a as string)), '') h_q04a,
    nullif(trim(safe_cast(h_q04b as string)), '') h_q04b,
    nullif(trim(safe_cast(h_q05a as string)), '') h_q05a,
    nullif(trim(safe_cast(h_q05c as string)), '') h_q05c,
    nullif(trim(safe_cast(h_q05d as string)), '') h_q05d,
    nullif(trim(safe_cast(h_q05e as string)), '') h_q05e,
    nullif(trim(safe_cast(h_q05f as string)), '') h_q05f,
    nullif(trim(safe_cast(h_q05g as string)), '') h_q05g,
    nullif(trim(safe_cast(h_q05h as string)), '') h_q05h,
    nullif(trim(safe_cast(i_q04b as string)), '') i_q04b,
    nullif(trim(safe_cast(i_q04d as string)), '') i_q04d,
    nullif(trim(safe_cast(i_q04h as string)), '') i_q04h,
    nullif(trim(safe_cast(i_q04j as string)), '') i_q04j,
    nullif(trim(safe_cast(i_q04l as string)), '') i_q04l,
    nullif(trim(safe_cast(i_q04m as string)), '') i_q04m,
    nullif(trim(safe_cast(i_q05f as string)), '') i_q05f,
    nullif(trim(safe_cast(i_q06a as string)), '') i_q06a,
    nullif(trim(safe_cast(i_q07a as string)), '') i_q07a,
    nullif(trim(safe_cast(i_q07b as string)), '') i_q07b,
    nullif(trim(safe_cast(i_q08 as string)), '') i_q08,
    nullif(trim(safe_cast(i_q08_t as string)), '') i_q08_t,
    safe_cast(j_q01 as int64) j_q01,
    safe_cast(j_q01_c as int64) j_q01_c,
    safe_cast(j_q01_t as int64) j_q01_t,
    nullif(trim(safe_cast(j_q01_t1 as string)), '') j_q01_t1,
    nullif(trim(safe_cast(j_q02a as string)), '') j_q02a,
    nullif(trim(safe_cast(j_q02c as string)), '') j_q02c,
    nullif(trim(safe_cast(j_q03a as string)), '') j_q03a,
    safe_cast(j_q03b as int64) j_q03b,
    safe_cast(j_q03b_c as int64) j_q03b_c,
    safe_cast(j_q03c as int64) j_q03c,
    nullif(trim(safe_cast(j_q03c_c as string)), '') j_q03c_c,
    safe_cast(j_q03d1 as int64) j_q03d1,
    nullif(trim(safe_cast(j_q03d1_c as string)), '') j_q03d1_c,
    safe_cast(j_q03d2 as int64) j_q03d2,
    nullif(trim(safe_cast(j_q03d2_c as string)), '') j_q03d2_c,
    nullif(trim(safe_cast(j_q04a as string)), '') j_q04a,
    nullif(trim(safe_cast(j_q04a_t as string)), '') j_q04a_t,
    safe_cast(j_q04c1 as int64) j_q04c1,
    nullif(trim(safe_cast(j_q04c1_c as string)), '') j_q04c1_c,
    safe_cast(j_q04c2 as int64) j_q04c2,
    safe_cast(j_q04c2_t as int64) j_q04c2_t,
    nullif(trim(safe_cast(j_q04c2_t1 as string)), '') j_q04c2_t1,
    nullif(trim(safe_cast(j_n05a2 as string)), '') j_n05a2,
    nullif(trim(safe_cast(j_q06a as string)), '') j_q06a,
    nullif(trim(safe_cast(j_q06a_t as string)), '') j_q06a_t,
    nullif(trim(safe_cast(j_q06b as string)), '') j_q06b,
    nullif(trim(safe_cast(j_q06b_t as string)), '') j_q06b_t,
    nullif(trim(safe_cast(j_q07a as string)), '') j_q07a,
    nullif(trim(safe_cast(j_q07a_t as string)), '') j_q07a_t,
    nullif(trim(safe_cast(j_q07b as string)), '') j_q07b,
    nullif(trim(safe_cast(j_q07b_t as string)), '') j_q07b_t,
    nullif(trim(safe_cast(j_q08 as string)), '') j_q08,
    nullif(trim(safe_cast(computerexperience as string)), '') computerexperience,
    nullif(trim(safe_cast(nativespeaker as string)), '') nativespeaker,
    nullif(trim(safe_cast(edlevel3 as string)), '') edlevel3,
    safe_cast(cba_core_stage1_score as float64) cba_core_stage1_score,
    safe_cast(cba_core_stage2_score as float64) cba_core_stage2_score,
    nullif(trim(safe_cast(corestage1_pass as string)), '') corestage1_pass,
    nullif(trim(safe_cast(corestage2_pass as string)), '') corestage2_pass,
    nullif(trim(safe_cast(random_cba_module1 as string)), '') random_cba_module1,
    nullif(trim(safe_cast(random_cba_module2 as string)), '') random_cba_module2,
    nullif(
        trim(safe_cast(random_cba_module1_stage1 as string)), ''
    ) random_cba_module1_stage1,
    nullif(
        trim(safe_cast(random_cba_module1_stage2 as string)), ''
    ) random_cba_module1_stage2,
    nullif(
        trim(safe_cast(random_cba_module2_stage1 as string)), ''
    ) random_cba_module2_stage1,
    nullif(
        trim(safe_cast(random_cba_module2_stage2 as string)), ''
    ) random_cba_module2_stage2,
    nullif(trim(safe_cast(cba_start as string)), '') cba_start,
    safe_cast(ppc_score as float64) ppc_score,
    nullif(trim(safe_cast(random_pp as string)), '') random_pp,
    safe_cast(prc_pv_q1 as int64) prc_pv_q1,
    safe_cast(prc_sp_q1 as int64) prc_sp_q1,
    safe_cast(prc_pf_q1 as int64) prc_pf_q1,
    safe_cast(prc_pf_q2 as int64) prc_pf_q2,
    safe_cast(prc_pf_q3 as int64) prc_pf_q3,
    nullif(trim(safe_cast(paper as string)), '') paper,
    nullif(trim(safe_cast(cbamod1 as string)), '') cbamod1,
    nullif(trim(safe_cast(cbamod2 as string)), '') cbamod2,
    nullif(trim(safe_cast(cbamod2alt as string)), '') cbamod2alt,
    nullif(trim(safe_cast(cbamod1stg1 as string)), '') cbamod1stg1,
    nullif(trim(safe_cast(cbamod2stg1 as string)), '') cbamod2stg1,
    nullif(trim(safe_cast(cbamod1stg2 as string)), '') cbamod1stg2,
    nullif(trim(safe_cast(cbamod2stg2 as string)), '') cbamod2stg2,
    nullif(trim(safe_cast(monthlyincpr as string)), '') monthlyincpr,
    nullif(trim(safe_cast(yearlyincpr as string)), '') yearlyincpr,
    nullif(trim(safe_cast(pbroute as string)), '') pbroute,
    nullif(trim(safe_cast(zz1a as string)), '') zz1a,
    nullif(trim(safe_cast(zz1b_01 as string)), '') zz1b_01,
    nullif(trim(safe_cast(zz1b_02 as string)), '') zz1b_02,
    nullif(trim(safe_cast(zz2 as string)), '') zz2,
    nullif(trim(safe_cast(zz3 as string)), '') zz3,
    nullif(trim(safe_cast(zz4_01 as string)), '') zz4_01,
    nullif(trim(safe_cast(zz4_02 as string)), '') zz4_02,
    nullif(trim(safe_cast(zz4_03 as string)), '') zz4_03,
    nullif(trim(safe_cast(zz4_04 as string)), '') zz4_04,
    nullif(trim(safe_cast(zz4_05 as string)), '') zz4_05,
    nullif(trim(safe_cast(zz4_06 as string)), '') zz4_06,
    nullif(trim(safe_cast(zz5 as string)), '') zz5,
    nullif(trim(safe_cast(zz6 as string)), '') zz6,
    nullif(trim(safe_cast(isced_hf as string)), '') isced_hf,
    nullif(trim(safe_cast(isced_hf_c as string)), '') isced_hf_c,
    nullif(trim(safe_cast(isco08_c as string)), '') isco08_c,
    nullif(trim(safe_cast(isco08_l as string)), '') isco08_l,
    nullif(trim(safe_cast(isic4_c as string)), '') isic4_c,
    nullif(trim(safe_cast(isic4_l as string)), '') isic4_l,
    nullif(trim(safe_cast(lng_l1 as string)), '') lng_l1,
    nullif(trim(safe_cast(lng_l2 as string)), '') lng_l2,
    nullif(trim(safe_cast(lng_home as string)), '') lng_home,
    nullif(trim(safe_cast(cnt_h as string)), '') cnt_h,
    nullif(trim(safe_cast(cnt_brth as string)), '') cnt_brth,
    nullif(trim(safe_cast(reg_tl2 as string)), '') reg_tl2,
    nullif(trim(safe_cast(lng_bq as string)), '') lng_bq,
    nullif(trim(safe_cast(lng_ci as string)), '') lng_ci,
    safe_cast(yrsqual as int64) yrsqual,
    safe_cast(yrsqual_t as int64) yrsqual_t,
    safe_cast(yrsget as int64) yrsget,
    nullif(trim(safe_cast(vet as string)), '') vet,
    nullif(trim(safe_cast(ctryqual as string)), '') ctryqual,
    nullif(trim(safe_cast(birthrgn as string)), '') birthrgn,
    nullif(trim(safe_cast(firlgrgn as string)), '') firlgrgn,
    nullif(trim(safe_cast(seclgrgn as string)), '') seclgrgn,
    nullif(trim(safe_cast(homlgrgn as string)), '') homlgrgn,
    nullif(trim(safe_cast(forbornlang as string)), '') forbornlang,
    nullif(trim(safe_cast(pared as string)), '') pared,
    nullif(trim(safe_cast(nativelang as string)), '') nativelang,
    nullif(trim(safe_cast(bornlang as string)), '') bornlang,
    nullif(trim(safe_cast(natbilang as string)), '') natbilang,
    nullif(trim(safe_cast(forbilang as string)), '') forbilang,
    nullif(trim(safe_cast(homlang as string)), '') homlang,
    nullif(trim(safe_cast(ctryrgn as string)), '') ctryrgn,
    nullif(trim(safe_cast(impar as string)), '') impar,
    nullif(trim(safe_cast(imgen as string)), '') imgen,
    safe_cast(imyrs as int64) imyrs,
    nullif(trim(safe_cast(imyrs_c as string)), '') imyrs_c,
    nullif(trim(safe_cast(imyrcat as string)), '') imyrcat,
    nullif(trim(safe_cast(ageg5lfs as string)), '') ageg5lfs,
    nullif(trim(safe_cast(ageg10lfs as string)), '') ageg10lfs,
    nullif(trim(safe_cast(ageg10lfs_t as string)), '') ageg10lfs_t,
    nullif(trim(safe_cast(edcat8 as string)), '') edcat8,
    nullif(trim(safe_cast(edcat7 as string)), '') edcat7,
    nullif(trim(safe_cast(edcat6 as string)), '') edcat6,
    nullif(trim(safe_cast(leaver1624 as string)), '') leaver1624,
    safe_cast(leavedu as int64) leavedu,
    nullif(trim(safe_cast(fe12 as string)), '') fe12,
    nullif(trim(safe_cast(aetpop as string)), '') aetpop,
    nullif(trim(safe_cast(faet12 as string)), '') faet12,
    nullif(trim(safe_cast(faet12jr as string)), '') faet12jr,
    nullif(trim(safe_cast(faet12njr as string)), '') faet12njr,
    nullif(trim(safe_cast(nfe12 as string)), '') nfe12,
    nullif(trim(safe_cast(nfe12jr as string)), '') nfe12jr,
    nullif(trim(safe_cast(nfe12njr as string)), '') nfe12njr,
    nullif(trim(safe_cast(fnfaet12 as string)), '') fnfaet12,
    nullif(trim(safe_cast(fnfe12jr as string)), '') fnfe12jr,
    nullif(trim(safe_cast(fnfaet12jr as string)), '') fnfaet12jr,
    nullif(trim(safe_cast(fnfaet12njr as string)), '') fnfaet12njr,
    nullif(trim(safe_cast(edwork as string)), '') edwork,
    nullif(trim(safe_cast(neet as string)), '') neet,
    safe_cast(nfehrsnjr as float64) nfehrsnjr,
    safe_cast(nfehrsjr as float64) nfehrsjr,
    safe_cast(nfehrs as int64) nfehrs,
    nullif(trim(safe_cast(nopaidworkever as string)), '') nopaidworkever,
    nullif(trim(safe_cast(paidwork12 as string)), '') paidwork12,
    nullif(trim(safe_cast(paidwork5 as string)), '') paidwork5,
    nullif(trim(safe_cast(iscoskil4 as string)), '') iscoskil4,
    nullif(trim(safe_cast(isic1l as string)), '') isic1l,
    nullif(trim(safe_cast(isic2l as string)), '') isic2l,
    nullif(trim(safe_cast(isic1c as string)), '') isic1c,
    nullif(trim(safe_cast(isic2c as string)), '') isic2c,
    nullif(trim(safe_cast(isco1c as string)), '') isco1c,
    nullif(trim(safe_cast(isco2c as string)), '') isco2c,
    nullif(trim(safe_cast(isco1l as string)), '') isco1l,
    nullif(trim(safe_cast(isco2l as string)), '') isco2l,
    safe_cast(earnhr as float64) earnhr,
    nullif(trim(safe_cast(earnhrdcl as string)), '') earnhrdcl,
    safe_cast(earnhrppp as float64) earnhrppp,
    safe_cast(earnhrbonus as float64) earnhrbonus,
    nullif(trim(safe_cast(earnhrbonusdcl as string)), '') earnhrbonusdcl,
    safe_cast(earnhrbonusppp as float64) earnhrbonusppp,
    safe_cast(earnmth as float64) earnmth,
    safe_cast(earnmthppp as float64) earnmthppp,
    safe_cast(earnmthselfppp as float64) earnmthselfppp,
    safe_cast(earnmthbonus as float64) earnmthbonus,
    safe_cast(earnmthall as float64) earnmthall,
    nullif(trim(safe_cast(earnmthalldcl as string)), '') earnmthalldcl,
    safe_cast(earnmthallppp as float64) earnmthallppp,
    safe_cast(earnmthbonusppp as float64) earnmthbonusppp,
    nullif(trim(safe_cast(earnflag as string)), '') earnflag,
    safe_cast(learnatwork as float64) learnatwork,
    nullif(trim(safe_cast(learnatwork_wle_ca as string)), '') learnatwork_wle_ca,
    safe_cast(readytolearn as float64) readytolearn,
    nullif(trim(safe_cast(readytolearn_wle_ca as string)), '') readytolearn_wle_ca,
    safe_cast(icthome as float64) icthome,
    nullif(trim(safe_cast(icthome_wle_ca as string)), '') icthome_wle_ca,
    safe_cast(ictwork as float64) ictwork,
    nullif(trim(safe_cast(ictwork_wle_ca as string)), '') ictwork_wle_ca,
    safe_cast(influence as float64) influence,
    nullif(trim(safe_cast(influence_wle_ca as string)), '') influence_wle_ca,
    safe_cast(numhome as float64) numhome,
    nullif(trim(safe_cast(numhome_wle_ca as string)), '') numhome_wle_ca,
    safe_cast(numwork as float64) numwork,
    nullif(trim(safe_cast(numwork_wle_ca as string)), '') numwork_wle_ca,
    safe_cast(planning as float64) planning,
    nullif(trim(safe_cast(planning_wle_ca as string)), '') planning_wle_ca,
    safe_cast(readhome as float64) readhome,
    nullif(trim(safe_cast(readhome_wle_ca as string)), '') readhome_wle_ca,
    safe_cast(readwork as float64) readwork,
    nullif(trim(safe_cast(readwork_wle_ca as string)), '') readwork_wle_ca,
    safe_cast(taskdisc as float64) taskdisc,
    nullif(trim(safe_cast(taskdisc_wle_ca as string)), '') taskdisc_wle_ca,
    safe_cast(writhome as float64) writhome,
    nullif(trim(safe_cast(writhome_wle_ca as string)), '') writhome_wle_ca,
    safe_cast(writwork as float64) writwork,
    nullif(trim(safe_cast(writwork_wle_ca as string)), '') writwork_wle_ca,
    nullif(trim(safe_cast(litstatus as string)), '') litstatus,
    safe_cast(pvlit1 as float64) pvlit1,
    safe_cast(pvlit2 as float64) pvlit2,
    safe_cast(pvlit3 as float64) pvlit3,
    safe_cast(pvlit4 as float64) pvlit4,
    safe_cast(pvlit5 as float64) pvlit5,
    safe_cast(pvlit6 as float64) pvlit6,
    safe_cast(pvlit7 as float64) pvlit7,
    safe_cast(pvlit8 as float64) pvlit8,
    safe_cast(pvlit9 as float64) pvlit9,
    safe_cast(pvlit10 as float64) pvlit10,
    nullif(trim(safe_cast(numstatus as string)), '') numstatus,
    safe_cast(pvnum1 as float64) pvnum1,
    safe_cast(pvnum2 as float64) pvnum2,
    safe_cast(pvnum3 as float64) pvnum3,
    safe_cast(pvnum4 as float64) pvnum4,
    safe_cast(pvnum5 as float64) pvnum5,
    safe_cast(pvnum6 as float64) pvnum6,
    safe_cast(pvnum7 as float64) pvnum7,
    safe_cast(pvnum8 as float64) pvnum8,
    safe_cast(pvnum9 as float64) pvnum9,
    safe_cast(pvnum10 as float64) pvnum10,
    nullif(trim(safe_cast(pslstatus as string)), '') pslstatus,
    safe_cast(pvpsl1 as float64) pvpsl1,
    safe_cast(pvpsl2 as float64) pvpsl2,
    safe_cast(pvpsl3 as float64) pvpsl3,
    safe_cast(pvpsl4 as float64) pvpsl4,
    safe_cast(pvpsl5 as float64) pvpsl5,
    safe_cast(pvpsl6 as float64) pvpsl6,
    safe_cast(pvpsl7 as float64) pvpsl7,
    safe_cast(pvpsl8 as float64) pvpsl8,
    safe_cast(pvpsl9 as float64) pvpsl9,
    safe_cast(pvpsl10 as float64) pvpsl10,
    safe_cast(prc_pv_scr as float64) prc_pv_scr,
    safe_cast(prc_sp_scr as float64) prc_sp_scr,
    safe_cast(prc_pc_scr as float64) prc_pc_scr,
    nullif(trim(safe_cast(vemethod as string)), '') vemethod,
    nullif(trim(safe_cast(vemethodn as string)), '') vemethodn,
    safe_cast(vefayfac as float64) vefayfac,
    nullif(trim(safe_cast(venreps as string)), '') venreps,
    nullif(trim(safe_cast(varstrat as string)), '') varstrat,
    nullif(trim(safe_cast(varunit as string)), '') varunit,
    safe_cast(spfwt0 as float64) spfwt0,
    safe_cast(spfwt1 as float64) spfwt1,
    safe_cast(spfwt2 as float64) spfwt2,
    safe_cast(spfwt3 as float64) spfwt3,
    safe_cast(spfwt4 as float64) spfwt4,
    safe_cast(spfwt5 as float64) spfwt5,
    safe_cast(spfwt6 as float64) spfwt6,
    safe_cast(spfwt7 as float64) spfwt7,
    safe_cast(spfwt8 as float64) spfwt8,
    safe_cast(spfwt9 as float64) spfwt9,
    safe_cast(spfwt10 as float64) spfwt10,
    safe_cast(spfwt11 as float64) spfwt11,
    safe_cast(spfwt12 as float64) spfwt12,
    safe_cast(spfwt13 as float64) spfwt13,
    safe_cast(spfwt14 as float64) spfwt14,
    safe_cast(spfwt15 as float64) spfwt15,
    safe_cast(spfwt16 as float64) spfwt16,
    safe_cast(spfwt17 as float64) spfwt17,
    safe_cast(spfwt18 as float64) spfwt18,
    safe_cast(spfwt19 as float64) spfwt19,
    safe_cast(spfwt20 as float64) spfwt20,
    safe_cast(spfwt21 as float64) spfwt21,
    safe_cast(spfwt22 as float64) spfwt22,
    safe_cast(spfwt23 as float64) spfwt23,
    safe_cast(spfwt24 as float64) spfwt24,
    safe_cast(spfwt25 as float64) spfwt25,
    safe_cast(spfwt26 as float64) spfwt26,
    safe_cast(spfwt27 as float64) spfwt27,
    safe_cast(spfwt28 as float64) spfwt28,
    safe_cast(spfwt29 as float64) spfwt29,
    safe_cast(spfwt30 as float64) spfwt30,
    safe_cast(spfwt31 as float64) spfwt31,
    safe_cast(spfwt32 as float64) spfwt32,
    safe_cast(spfwt33 as float64) spfwt33,
    safe_cast(spfwt34 as float64) spfwt34,
    safe_cast(spfwt35 as float64) spfwt35,
    safe_cast(spfwt36 as float64) spfwt36,
    safe_cast(spfwt37 as float64) spfwt37,
    safe_cast(spfwt38 as float64) spfwt38,
    safe_cast(spfwt39 as float64) spfwt39,
    safe_cast(spfwt40 as float64) spfwt40,
    safe_cast(spfwt41 as float64) spfwt41,
    safe_cast(spfwt42 as float64) spfwt42,
    safe_cast(spfwt43 as float64) spfwt43,
    safe_cast(spfwt44 as float64) spfwt44,
    safe_cast(spfwt45 as float64) spfwt45,
    safe_cast(spfwt46 as float64) spfwt46,
    safe_cast(spfwt47 as float64) spfwt47,
    safe_cast(spfwt48 as float64) spfwt48,
    safe_cast(spfwt49 as float64) spfwt49,
    safe_cast(spfwt50 as float64) spfwt50,
    safe_cast(spfwt51 as float64) spfwt51,
    safe_cast(spfwt52 as float64) spfwt52,
    safe_cast(spfwt53 as float64) spfwt53,
    safe_cast(spfwt54 as float64) spfwt54,
    safe_cast(spfwt55 as float64) spfwt55,
    safe_cast(spfwt56 as float64) spfwt56,
    safe_cast(spfwt57 as float64) spfwt57,
    safe_cast(spfwt58 as float64) spfwt58,
    safe_cast(spfwt59 as float64) spfwt59,
    safe_cast(spfwt60 as float64) spfwt60,
    safe_cast(spfwt61 as float64) spfwt61,
    safe_cast(spfwt62 as float64) spfwt62,
    safe_cast(spfwt63 as float64) spfwt63,
    safe_cast(spfwt64 as float64) spfwt64,
    safe_cast(spfwt65 as float64) spfwt65,
    safe_cast(spfwt66 as float64) spfwt66,
    safe_cast(spfwt67 as float64) spfwt67,
    safe_cast(spfwt68 as float64) spfwt68,
    safe_cast(spfwt69 as float64) spfwt69,
    safe_cast(spfwt70 as float64) spfwt70,
    safe_cast(spfwt71 as float64) spfwt71,
    safe_cast(spfwt72 as float64) spfwt72,
    safe_cast(spfwt73 as float64) spfwt73,
    safe_cast(spfwt74 as float64) spfwt74,
    safe_cast(spfwt75 as float64) spfwt75,
    safe_cast(spfwt76 as float64) spfwt76,
    safe_cast(spfwt77 as float64) spfwt77,
    safe_cast(spfwt78 as float64) spfwt78,
    safe_cast(spfwt79 as float64) spfwt79,
    safe_cast(spfwt80 as float64) spfwt80
from {{ set_datalake_project("world_oecd_piaac_staging.respondent_cycle_1") }} as t
