"""Gate B — republication-drift check (fix_plan/04).

Compares the header of every LOCAL input zip (the vintage the rebuild
will consume) against the OFFICIAL layout fetched from today's TSE by
``diagnostics run --tier 2 --force`` (remote HTTP-Range headers).

A family-year where the local header differs from today's official
layout means TSE republished that file since our download — parsing is
unaffected (read-by-header-name), but the data content may have been
revised, so the cell is flagged for an optional re-download decision.

Run from ``code/python/`` after the tier-2 refresh:

    TSE_DATA_DIR=/Users/rdahis/Downloads/dados_TSE uv run python gate_b_drift.py

Writes ``fix_plan/gate_b_drift.md``.
"""

from __future__ import annotations

import io
import json
import re
import zipfile
from pathlib import Path

from config import INPUT_DIR
from diagnostics.tier2_leiame import (
    FAMILIES,
    _header_columns,
    _member_ok,
    needed_pairs,
)

ARTIFACTS = Path(__file__).resolve().parent / "diagnostics" / "artifacts"
LAYOUTS = ARTIFACTS / "layouts"
OUT = Path(__file__).resolve().parent.parent / "fix_plan" / "gate_b_drift.md"

_DATA_EXT_RE = re.compile(r"\.(csv|txt)$", re.IGNORECASE)


def _local_zip_paths(family: str, ano: int) -> list[Path]:
    fam = FAMILIES[family]
    hits = []
    for tpl in fam.local_dirs:
        # zips sit next to where the extracted dir would be:
        # INPUT_DIR/<family_dir>/<name>.zip
        pattern = tpl.format(ano=ano, uf="*")
        parent = (INPUT_DIR / pattern).parent
        stem = Path(pattern).name
        if parent.is_dir():
            hits.extend(sorted(parent.glob(stem + ".zip")))
    return hits


def _zip_first_header(zp: Path, member_hint: str) -> list[str] | None:
    try:
        zf = zipfile.ZipFile(zp)
    except zipfile.BadZipFile:
        return None
    members = [
        m
        for m in zf.infolist()
        if _DATA_EXT_RE.search(m.filename)
        and _member_ok(m.filename, member_hint)
    ]
    if not members:
        return None
    member = min(members, key=lambda m: m.file_size)
    with zf.open(member) as fh:
        first = io.TextIOWrapper(fh, encoding="latin-1").readline()
    return _header_columns(first)


def main() -> None:
    rows = []
    for family, ano in needed_pairs("all"):
        layout_file = LAYOUTS / f"{family}_{ano}.json"
        if not layout_file.exists():
            rows.append((family, ano, "NO_REMOTE_LAYOUT", ""))
            continue
        official = json.loads(layout_file.read_text())
        if official.get("source", "").startswith("leiame"):
            rows.append((family, ano, "LEIAME_ONLY", ""))
            continue
        cols_official = [c.lower() for c in official["columns"]]
        fam = FAMILIES[family]
        zips = _local_zip_paths(family, ano)
        if not zips:
            rows.append((family, ano, "NO_LOCAL_ZIP", ""))
            continue
        local = None
        for zp in zips:
            local = _zip_first_header(zp, fam.member_hint)
            if local:
                break
        if not local:
            rows.append((family, ano, "NO_LOCAL_HEADER", ""))
            continue
        local = [c.lower() for c in local]
        if local == cols_official:
            rows.append((family, ano, "OK", ""))
        else:
            miss = [c for c in cols_official if c not in local]
            extra = [c for c in local if c not in cols_official]
            detail = (
                f"remote-only: {miss}; local-only: {extra}"
                if miss or extra
                else "same set, order differs"
            )
            rows.append((family, ano, "DRIFT", detail))

    counts: dict[str, int] = {}
    for _, _, st, _ in rows:
        counts[st] = counts.get(st, 0) + 1
    with open(OUT, "w") as fh:
        fh.write(
            "# Gate B — republication drift: local input zips vs today's "
            "TSE\n\nGenerated by `code/python/gate_b_drift.py`. DRIFT means "
            "TSE republished the file since our download vintage; parsing "
            "is header-based and unaffected, but data content may have "
            "been revised.\n\n"
        )
        fh.write(f"Summary: {counts}\n\n")
        fh.write("| family | ano | status | detail |\n|---|---|---|---|\n")
        for family, ano, st, detail in rows:
            if st == "OK":
                continue
            fh.write(f"| {family} | {ano} | {st} | {detail} |\n")
        fh.write(
            f"\n{counts.get('OK', 0)} family-years OK (identical header, "
            "omitted from the table).\n"
        )
    print("summary:", counts)
    print("written:", OUT)


if __name__ == "__main__":
    main()
