"""Single source of truth for the world_aiddata_gcdf architecture.

Generates the architecture CSV (BD schema) and, from the same spec, the column
order and type map consumed by clean.py and the dbt model. Columns are mapped to
the source workbook BY POSITION (first 126 columns of the ``GCDF_3.0`` sheet), so
minor punctuation differences in the source headers (curly vs. straight
apostrophes, hyphenation) never break the rename.

Dataset: AidData's Global Chinese Development Finance Dataset, Version 3.0.
One project/activity-level table (``projects``). English column names.
Descriptions in PT / EN / ES. Types follow arithmetic meaning:
INT64/FLOAT64 only for genuine quantities (each with a measurement unit where
one exists); every categorical/coded/flag field stays STRING. The categorical
fields store human-readable labels (e.g. Status="Completion", Flow Type="Loan"),
so no ``dicionario`` is required.
"""

import csv
import os

# ---------------------------------------------------------------------------
# Helpers for the repetitive field families (loan-type flags, agency name/type)
# ---------------------------------------------------------------------------


def loanflag(en_x, pt_x, es_x):
    return (
        f"Marker set to 'Yes' when the loan is {en_x}",
        f"Marcador definido como 'Sim' quando o empréstimo é {pt_x}",
        f"Marcador definido como 'Sí' cuando el préstamo es {es_x}",
    )


def ag_name(en_role, pt_role, es_role):
    return (
        f"Name of the {en_role}; pipe-delimited when multiple",
        f"Nome da(s) {pt_role}; separadas por barra vertical quando múltiplas",
        f"Nombre de la(s) {es_role}; separadas por barra vertical cuando son varias",
    )


def ag_type(en_role, pt_role, es_role):
    return (
        f"Type and country of origin of the {en_role}; pipe-delimited when multiple",
        f"Tipo e país de origem da(s) {pt_role}; separados por barra vertical quando múltiplos",
        f"Tipo y país de origen de la(s) {es_role}; separados por barra vertical cuando son varios",
    )


# ---------------------------------------------------------------------------
# Column spec, IN SOURCE ORDER (workbook columns 1..126).
# Fields: target, bigquery_type, measurement_unit, covered_by_dictionary(0/1),
#         directory_column, (desc_en, desc_pt, desc_es), observations
# ---------------------------------------------------------------------------
DIR_PAIS = "br_bd_diretorios_mundo.pais:sigla_iso3"

COLS = [
    dict(
        t="id_record",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Unique identification number AidData assigns to each project/activity record",
            "Número de identificação único atribuído pela AidData a cada registro de projeto/atividade",
            "Número de identificación único que AidData asigna a cada registro de proyecto/actividad",
        ),
    ),
    dict(
        t="recommended_for_aggregates",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Whether AidData recommends including the record in aggregate analyses (Yes/No)",
            "Se a AidData recomenda incluir o registro em análises agregadas (Sim/Não)",
            "Si AidData recomienda incluir el registro en análisis agregados (Sí/No)",
        ),
    ),
    dict(
        t="id_parent",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="Links related records into a common package",
        desc=(
            "Identifier of the linked package grouping related project/activity records",
            "Identificador do pacote que agrupa registros de projeto/atividade relacionados",
            "Identificador del paquete que agrupa registros de proyecto/actividad relacionados",
        ),
    ),
    dict(
        t="umbrella",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Whether the record is an umbrella agreement, excluded from aggregates (Yes/No)",
            "Se o registro é um acordo guarda-chuva, excluído dos agregados (Sim/Não)",
            "Si el registro es un acuerdo paraguas, excluido de los agregados (Sí/No)",
        ),
    ),
    dict(
        t="financier_country",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Country from which the official financial or in-kind transfer originated",
            "País de origem da transferência financeira ou em espécie oficial",
            "País del que se originó la transferencia financiera o en especie oficial",
        ),
    ),
    dict(
        t="recipient_name",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="Regional labels used when multiple countries",
        desc=(
            "Recipient country, or region when multiple recipient countries are involved",
            "País receptor, ou região quando envolve múltiplos países receptores",
            "País receptor, o región cuando participan varios países receptores",
        ),
    ),
    dict(
        t="country_iso3_code",
        ty="STRING",
        u="",
        d=0,
        dir=DIR_PAIS,
        obs="Blank for regional/multi-country records",
        desc=(
            "Recipient country ISO 3166-1 alpha-3 code",
            "Código ISO 3166-1 alfa-3 do país receptor",
            "Código ISO 3166-1 alfa-3 del país receptor",
        ),
    ),
    dict(
        t="recipient_region",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Geographical region of the recipient country",
            "Região geográfica do país receptor",
            "Región geográfica del país receptor",
        ),
    ),
    dict(
        t="year",
        ty="INT64",
        u="",
        d=0,
        dir="br_bd_diretorios_data_tempo.ano:ano",
        obs="Partition column; commitment year",
        desc=(
            "Year the official financial commitment was made (commitment year)",
            "Ano em que o compromisso financeiro oficial foi firmado (ano de compromisso)",
            "Año en que se realizó el compromiso financiero oficial (año de compromiso)",
        ),
    ),
    dict(
        t="implementation_start_year",
        ty="INT64",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Year the project/activity began implementation",
            "Ano em que o projeto/atividade iniciou a implementação",
            "Año en que el proyecto/actividad comenzó su implementación",
        ),
    ),
    dict(
        t="completion_year",
        ty="INT64",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Year the project/activity was completed",
            "Ano em que o projeto/atividade foi concluído",
            "Año en que el proyecto/actividad se completó",
        ),
    ),
    dict(
        t="title",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Short name or description of the project/activity",
            "Nome ou descrição breve do projeto/atividade",
            "Nombre o descripción breve del proyecto/actividad",
        ),
    ),
    dict(
        t="description",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Detailed narrative summary of the project/activity and its financing",
            "Resumo narrativo detalhado do projeto/atividade e de seu financiamento",
            "Resumen narrativo detallado del proyecto/actividad y su financiamiento",
        ),
    ),
    dict(
        t="staff_comments",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "AidData staff comments on coding assumptions, logic, and evidence",
            "Comentários da equipe da AidData sobre premissas, lógica e evidências de codificação",
            "Comentarios del personal de AidData sobre supuestos, lógica y evidencia de codificación",
        ),
    ),
    dict(
        t="status",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="Six categories: Pipeline: Pledge/Commitment, Implementation, Completion, Suspended, Cancelled",
        desc=(
            "Latest status of the project/activity",
            "Situação mais recente do projeto/atividade",
            "Estado más reciente del proyecto/actividad",
        ),
    ),
    dict(
        t="intent",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="Development, Commercial, Representational, Mixed, or Military",
        desc=(
            "Primary purpose of the project/activity",
            "Propósito principal do projeto/atividade",
            "Propósito principal del proyecto/actividad",
        ),
    ),
    dict(
        t="flow_type",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Type of financial or in-kind transfer supporting the project/activity",
            "Tipo de transferência financeira ou em espécie que apoia o projeto/atividade",
            "Tipo de transferencia financiera o en especie que apoya el proyecto/actividad",
        ),
    ),
    dict(
        t="flow_type_simplified",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="Grant, Loan, Debt Rescheduling, or Vague",
        desc=(
            "Simplified flow type grouping into four categories",
            "Tipo de fluxo simplificado agrupado em quatro categorias",
            "Tipo de flujo simplificado agrupado en cuatro categorías",
        ),
    ),
    dict(
        t="oecd_oda_concessionality_threshold",
        ty="FLOAT64",
        u="proportion",
        d=0,
        dir="",
        obs="Grant-element threshold applied to classify the loan as ODA",
        desc=(
            "OECD concessionality threshold applied to the loan for ODA classification",
            "Limiar de concessionalidade da OCDE aplicado ao empréstimo para classificação como AOD",
            "Umbral de concesionalidad de la OCDE aplicado al préstamo para clasificación como AOD",
        ),
    ),
    dict(
        t="flow_class",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="ODA-like, OOF-like, or Vague (Official Finance)",
        desc=(
            "OECD-DAC flow class: ODA-like, OOF-like, or Vague (Official Finance)",
            "Classe do fluxo OCDE-CAD: tipo AOD, tipo OOF ou Vago (Finanças Oficiais)",
            "Clase de flujo OCDE-CAD: tipo AOD, tipo OOF o Vago (Financiamiento Oficial)",
        ),
    ),
    dict(
        t="sector_code",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="OECD 3-digit sector code; label in sector_name",
        desc=(
            "OECD 3-digit sector code of the project/activity's primary sector",
            "Código setorial de 3 dígitos da OCDE do setor principal do projeto/atividade",
            "Código sectorial de 3 dígitos de la OCDE del sector principal del proyecto/actividad",
        ),
    ),
    dict(
        t="sector_name",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "OECD sector name of the project/activity's primary sector",
            "Nome setorial da OCDE do setor principal do projeto/atividade",
            "Nombre sectorial de la OCDE del sector principal del proyecto/actividad",
        ),
    ),
    dict(
        t="infrastructure",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=(
            "Marker set to 'Yes' when the project involves physical infrastructure",
            "Marcador definido como 'Sim' quando o projeto envolve infraestrutura física",
            "Marcador definido como 'Sí' cuando el proyecto implica infraestructura física",
        ),
    ),
    dict(
        t="covid",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=(
            "Marker set to 'Yes' when the project is part of China's COVID-19 response",
            "Marcador definido como 'Sim' quando o projeto integra a resposta da China à COVID-19",
            "Marcador definido como 'Sí' cuando el proyecto forma parte de la respuesta de China a la COVID-19",
        ),
    ),
    dict(
        t="funding_agencies",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=ag_name(
            "agency(ies) that issued the commitment or pledge",
            "agência(s) que emitiu(ram) o compromisso ou promessa",
            "agencia(s) que emitió(eron) el compromiso o promesa",
        ),
    ),
    dict(
        t="funding_agencies_type",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=ag_type(
            "funding agency(ies)",
            "agência(s) financiadora(s)",
            "agencia(s) financiadora(s)",
        ),
    ),
    dict(
        t="cofinanced",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Whether a separate agency co-financed the project/activity (Yes/No)",
            "Se uma agência distinta cofinanciou o projeto/atividade (Sim/Não)",
            "Si una agencia distinta cofinanció el proyecto/actividad (Sí/No)",
        ),
    ),
    dict(
        t="cofinancing_agencies",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=ag_name(
            "co-financing agency(ies)",
            "agência(s) cofinanciadora(s)",
            "agencia(s) cofinanciadora(s)",
        ),
    ),
    dict(
        t="cofinancing_agencies_type",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=ag_type(
            "co-financing agency(ies)",
            "agência(s) cofinanciadora(s)",
            "agencia(s) cofinanciadora(s)",
        ),
    ),
    dict(
        t="direct_receiving_agencies",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="Borrower/repayer for loans",
        desc=ag_name(
            "direct receiving agency(ies)",
            "agência(s) receptora(s) direta(s)",
            "agencia(s) receptora(s) directa(s)",
        ),
    ),
    dict(
        t="direct_receiving_agencies_type",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=ag_type(
            "direct receiving agency(ies)",
            "agência(s) receptora(s) direta(s)",
            "agencia(s) receptora(s) directa(s)",
        ),
    ),
    dict(
        t="indirect_receiving_agencies",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="On-lending recipients",
        desc=ag_name(
            "indirect receiving agency(ies) in on-lending arrangements",
            "agência(s) receptora(s) indireta(s) em arranjos de repasse",
            "agencia(s) receptora(s) indirecta(s) en arreglos de represtamo",
        ),
    ),
    dict(
        t="indirect_receiving_agencies_type",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=ag_type(
            "indirect receiving agency(ies)",
            "agência(s) receptora(s) indireta(s)",
            "agencia(s) receptora(s) indirecta(s)",
        ),
    ),
    dict(
        t="on_lending",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=(
            "Marker set to 'Yes' when the loan involves an on-lending arrangement",
            "Marcador definido como 'Sim' quando o empréstimo envolve arranjo de repasse",
            "Marcador definido como 'Sí' cuando el préstamo implica un arreglo de represtamo",
        ),
    ),
    dict(
        t="implementing_agencies",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=ag_name(
            "implementing agency(ies)",
            "agência(s) executora(s)",
            "agencia(s) ejecutora(s)",
        ),
    ),
    dict(
        t="implementing_agencies_type",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=ag_type(
            "implementing agency(ies)",
            "agência(s) executora(s)",
            "agencia(s) ejecutora(s)",
        ),
    ),
    dict(
        t="guarantee_provided",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Whether a third-party loan repayment guarantee was issued (Yes/No)",
            "Se foi emitida garantia de pagamento do empréstimo por terceiro (Sim/Não)",
            "Si se emitió una garantía de pago del préstamo por un tercero (Sí/No)",
        ),
    ),
    dict(
        t="guarantor",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=ag_name(
            "guarantor agency(ies)",
            "agência(s) garantidora(s)",
            "agencia(s) garante(s)",
        ),
    ),
    dict(
        t="guarantor_agency_type",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=ag_type(
            "guarantor agency(ies)",
            "agência(s) garantidora(s)",
            "agencia(s) garante(s)",
        ),
    ),
    dict(
        t="insurance_provided",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Whether a third party provided credit insurance on the loan (Yes/No)",
            "Se um terceiro forneceu seguro de crédito sobre o empréstimo (Sim/Não)",
            "Si un tercero proporcionó un seguro de crédito sobre el préstamo (Sí/No)",
        ),
    ),
    dict(
        t="insurance_provider",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=ag_name(
            "credit insurance provider(s)",
            "provedor(es) de seguro de crédito",
            "proveedor(es) de seguro de crédito",
        ),
    ),
    dict(
        t="insurance_provider_agency_type",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=ag_type(
            "credit insurance provider(s)",
            "provedor(es) de seguro de crédito",
            "proveedor(es) de seguro de crédito",
        ),
    ),
    dict(
        t="collateralized",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=(
            "Marker set to 'Yes' when the loan is collateralized or securitized",
            "Marcador definido como 'Sim' quando o empréstimo é garantido por colateral ou securitizado",
            "Marcador definido como 'Sí' cuando el préstamo está garantizado con colateral o securitizado",
        ),
    ),
    dict(
        t="collateral_provider",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=ag_name(
            "collateral provider(s)",
            "provedor(es) de colateral",
            "proveedor(es) de colateral",
        ),
    ),
    dict(
        t="collateral_provider_agency_type",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=ag_type(
            "collateral provider(s)",
            "provedor(es) de colateral",
            "proveedor(es) de colateral",
        ),
    ),
    dict(
        t="security_agent",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=ag_name(
            "security/collateral agent(s)",
            "agente(s) de garantia/colateral",
            "agente(s) de garantía/colateral",
        ),
    ),
    dict(
        t="security_agent_type",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=ag_type(
            "security/collateral agent(s)",
            "agente(s) de garantia/colateral",
            "agente(s) de garantía/colateral",
        ),
    ),
    dict(
        t="collateral",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Description of the collateral or security backing the loan",
            "Descrição do colateral ou garantia que respalda o empréstimo",
            "Descripción del colateral o garantía que respalda el préstamo",
        ),
    ),
    dict(
        t="amount_original_currency",
        ty="FLOAT64",
        u="",
        d=0,
        dir="",
        obs="Denominated in the currency given by original_currency",
        desc=(
            "Transaction amount in the original currency",
            "Valor da transação na moeda original",
            "Monto de la transacción en la moneda original",
        ),
    ),
    dict(
        t="original_currency",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="ISO currency code",
        desc=(
            "Currency in which the original amount is denominated",
            "Moeda em que o valor original está denominado",
            "Moneda en que está denominado el monto original",
        ),
    ),
    dict(
        t="amount_estimated",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=(
            "Marker set to 'Yes' when the transaction amount is an estimate",
            "Marcador definido como 'Sim' quando o valor da transação é uma estimativa",
            "Marcador definido como 'Sí' cuando el monto de la transacción es una estimación",
        ),
    ),
    dict(
        t="amount_constant_usd_2021",
        ty="FLOAT64",
        u="USD",
        d=0,
        dir="",
        obs="Constant 2021 US dollars",
        desc=(
            "Transaction amount in constant 2021 US dollars",
            "Valor da transação em dólares dos EUA constantes de 2021",
            "Monto de la transacción en dólares estadounidenses constantes de 2021",
        ),
    ),
    dict(
        t="amount_nominal_usd",
        ty="FLOAT64",
        u="USD",
        d=0,
        dir="",
        obs="Nominal US dollars",
        desc=(
            "Transaction amount in nominal US dollars",
            "Valor da transação em dólares dos EUA nominais",
            "Monto de la transacción en dólares estadounidenses nominales",
        ),
    ),
    dict(
        t="adjusted_amount_original_currency",
        ty="FLOAT64",
        u="",
        d=0,
        dir="",
        obs="Adjusted for double-counting; in original_currency",
        desc=(
            "Adjusted transaction amount in the original currency",
            "Valor ajustado da transação na moeda original",
            "Monto ajustado de la transacción en la moneda original",
        ),
    ),
    dict(
        t="adjusted_amount_constant_usd_2021",
        ty="FLOAT64",
        u="USD",
        d=0,
        dir="",
        obs="Adjusted for double-counting",
        desc=(
            "Adjusted transaction amount in constant 2021 US dollars",
            "Valor ajustado da transação em dólares dos EUA constantes de 2021",
            "Monto ajustado de la transacción en dólares estadounidenses constantes de 2021",
        ),
    ),
    dict(
        t="adjusted_amount_nominal_usd",
        ty="FLOAT64",
        u="USD",
        d=0,
        dir="",
        obs="Adjusted for double-counting",
        desc=(
            "Adjusted transaction amount in nominal US dollars",
            "Valor ajustado da transação em dólares dos EUA nominais",
            "Monto ajustado de la transacción en dólares estadounidenses nominales",
        ),
    ),
    dict(
        t="financial_distress",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=(
            "Marker set to 'Yes' when the loan shows signs of financial distress",
            "Marcador definido como 'Sim' quando o empréstimo apresenta sinais de estresse financeiro",
            "Marcador definido como 'Sí' cuando el préstamo muestra señales de estrés financiero",
        ),
    ),
    dict(
        t="commitment_date",
        ty="DATE",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Date the official financial commitment was made",
            "Data em que o compromisso financeiro oficial foi firmado",
            "Fecha en que se realizó el compromiso financiero oficial",
        ),
    ),
    dict(
        t="commitment_date_estimated",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Whether the commitment date is an estimate (Yes/No)",
            "Se a data de compromisso é uma estimativa (Sim/Não)",
            "Si la fecha de compromiso es una estimación (Sí/No)",
        ),
    ),
    dict(
        t="planned_implementation_start_date",
        ty="DATE",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Planned date for the start of project/activity implementation",
            "Data planejada para o início da implementação do projeto/atividade",
            "Fecha planificada para el inicio de la implementación del proyecto/actividad",
        ),
    ),
    dict(
        t="actual_implementation_start_date",
        ty="DATE",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Actual date the project/activity began implementation",
            "Data efetiva em que o projeto/atividade iniciou a implementação",
            "Fecha real en que el proyecto/actividad comenzó su implementación",
        ),
    ),
    dict(
        t="actual_implementation_start_date_estimated",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=(
            "Marker set to 'Yes' when the actual implementation start date is an estimate",
            "Marcador definido como 'Sim' quando a data efetiva de início da implementação é uma estimativa",
            "Marcador definido como 'Sí' cuando la fecha real de inicio de implementación es una estimación",
        ),
    ),
    dict(
        t="deviation_planned_implementation_start_date",
        ty="INT64",
        u="day",
        d=0,
        dir="",
        obs="Actual minus planned, in days",
        desc=(
            "Deviation of actual from planned implementation start, in days",
            "Desvio do início de implementação efetivo em relação ao planejado, em dias",
            "Desviación del inicio de implementación real respecto al planificado, en días",
        ),
    ),
    dict(
        t="planned_completion_date",
        ty="DATE",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Planned date for project/activity completion",
            "Data planejada para a conclusão do projeto/atividade",
            "Fecha planificada para la finalización del proyecto/actividad",
        ),
    ),
    dict(
        t="actual_completion_date",
        ty="DATE",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Actual date the project/activity was completed",
            "Data efetiva em que o projeto/atividade foi concluído",
            "Fecha real en que el proyecto/actividad se completó",
        ),
    ),
    dict(
        t="actual_completion_date_estimated",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=(
            "Marker set to 'Yes' when the actual completion date is an estimate",
            "Marcador definido como 'Sim' quando a data efetiva de conclusão é uma estimativa",
            "Marcador definido como 'Sí' cuando la fecha real de finalización es una estimación",
        ),
    ),
    dict(
        t="deviation_planned_completion_date",
        ty="INT64",
        u="day",
        d=0,
        dir="",
        obs="Actual minus planned, in days",
        desc=(
            "Deviation of actual from planned completion, in days",
            "Desvio da conclusão efetiva em relação à planejada, em dias",
            "Desviación de la finalización real respecto a la planificada, en días",
        ),
    ),
    dict(
        t="maturity",
        ty="FLOAT64",
        u="year",
        d=0,
        dir="",
        obs="",
        desc=(
            "Loan maturity, in years",
            "Prazo de vencimento do empréstimo, em anos",
            "Plazo de vencimiento del préstamo, en años",
        ),
    ),
    dict(
        t="interest_rate",
        ty="FLOAT64",
        u="percent",
        d=0,
        dir="",
        obs="",
        desc=(
            "Loan interest rate, in percent",
            "Taxa de juros do empréstimo, em porcentagem",
            "Tasa de interés del préstamo, en porcentaje",
        ),
    ),
    dict(
        t="grace_period",
        ty="FLOAT64",
        u="year",
        d=0,
        dir="",
        obs="",
        desc=(
            "Loan grace period, in years",
            "Período de carência do empréstimo, em anos",
            "Período de gracia del préstamo, en años",
        ),
    ),
    dict(
        t="management_fee",
        ty="FLOAT64",
        u="percent",
        d=0,
        dir="",
        obs="",
        desc=(
            "Loan management fee, in percent",
            "Taxa de administração do empréstimo, em porcentagem",
            "Comisión de gestión del préstamo, en porcentaje",
        ),
    ),
    dict(
        t="commitment_fee",
        ty="FLOAT64",
        u="percent",
        d=0,
        dir="",
        obs="",
        desc=(
            "Loan commitment fee, in percent",
            "Taxa de compromisso do empréstimo, em porcentagem",
            "Comisión de compromiso del préstamo, en porcentaje",
        ),
    ),
    dict(
        t="insurance_fee_percent",
        ty="FLOAT64",
        u="percent",
        d=0,
        dir="",
        obs="",
        desc=(
            "Credit insurance fee, in percent",
            "Taxa de seguro de crédito, em porcentagem",
            "Comisión de seguro de crédito, en porcentaje",
        ),
    ),
    dict(
        t="insurance_fee_nominal_usd",
        ty="FLOAT64",
        u="USD",
        d=0,
        dir="",
        obs="",
        desc=(
            "Credit insurance fee, in nominal US dollars",
            "Taxa de seguro de crédito, em dólares dos EUA nominais",
            "Comisión de seguro de crédito, en dólares estadounidenses nominales",
        ),
    ),
    dict(
        t="default_interest_rate",
        ty="FLOAT64",
        u="percent",
        d=0,
        dir="",
        obs="",
        desc=(
            "Default (penalty) interest rate, in percent",
            "Taxa de juros de mora (penalidade), em porcentagem",
            "Tasa de interés de mora (penalización), en porcentaje",
        ),
    ),
    dict(
        t="first_loan_repayment_date",
        ty="DATE",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Date of the first scheduled loan repayment",
            "Data do primeiro pagamento programado do empréstimo",
            "Fecha del primer pago programado del préstamo",
        ),
    ),
    dict(
        t="last_loan_repayment_date",
        ty="DATE",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Date of the last scheduled loan repayment",
            "Data do último pagamento programado do empréstimo",
            "Fecha del último pago programado del préstamo",
        ),
    ),
    dict(
        t="grant_element_oecd_cash_flow",
        ty="FLOAT64",
        u="percent",
        d=0,
        dir="",
        obs="",
        desc=(
            "Grant element under the OECD cash-flow methodology, in percent",
            "Elemento de doação pela metodologia de fluxo de caixa da OCDE, em porcentagem",
            "Elemento de donación bajo la metodología de flujo de caja de la OCDE, en porcentaje",
        ),
    ),
    dict(
        t="grant_element_oecd_grant_equiv",
        ty="FLOAT64",
        u="percent",
        d=0,
        dir="",
        obs="",
        desc=(
            "Grant element under the OECD grant-equivalent methodology, in percent",
            "Elemento de doação pela metodologia de equivalente-doação da OCDE, em porcentagem",
            "Elemento de donación bajo la metodología de equivalente-donación de la OCDE, en porcentaje",
        ),
    ),
    dict(
        t="grant_element_imf",
        ty="FLOAT64",
        u="percent",
        d=0,
        dir="",
        obs="",
        desc=(
            "Grant element under the IMF methodology, in percent",
            "Elemento de doação pela metodologia do FMI, em porcentagem",
            "Elemento de donación bajo la metodología del FMI, en porcentaje",
        ),
    ),
    dict(
        t="number_of_lenders",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="Categorical: Bilateral Loan or Syndicated Loan",
        desc=(
            "Lender structure of the loan (bilateral or syndicated)",
            "Estrutura de credores do empréstimo (bilateral ou sindicalizado)",
            "Estructura de prestamistas del préstamo (bilateral o sindicado)",
        ),
    ),
    dict(
        t="export_buyers_credit",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=loanflag(
            "an export buyer's credit",
            "um crédito ao comprador de exportação",
            "un crédito al comprador de exportación",
        ),
    ),
    dict(
        t="suppliers_credit",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=loanflag(
            "a supplier's or export seller's credit",
            "um crédito ao fornecedor ou vendedor de exportação",
            "un crédito al proveedor o vendedor de exportación",
        ),
    ),
    dict(
        t="interest_free_loan",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=loanflag("interest-free", "sem juros", "sin intereses"),
    ),
    dict(
        t="refinancing",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=loanflag(
            "a refinancing", "um refinanciamento", "un refinanciamiento"
        ),
    ),
    dict(
        t="investment_project_loan",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=loanflag(
            "an investment project loan",
            "um empréstimo para projeto de investimento",
            "un préstamo para proyecto de inversión",
        ),
    ),
    dict(
        t="mergers_acquisitions",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=loanflag(
            "for a merger or acquisition",
            "para uma fusão ou aquisição",
            "para una fusión o adquisición",
        ),
    ),
    dict(
        t="working_capital",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=loanflag(
            "for working capital",
            "para capital de giro",
            "para capital de trabajo",
        ),
    ),
    dict(
        t="epcf",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="Engineering-Procurement-Construction-Financing; 'Yes' when applicable",
        desc=loanflag(
            "an EPC+Financing (EPCF) loan",
            "um empréstimo EPC+Financiamento (EPCF)",
            "un préstamo EPC+Financiamiento (EPCF)",
        ),
    ),
    dict(
        t="lease",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=loanflag(
            "a lease",
            "um arrendamento (leasing)",
            "un arrendamiento (leasing)",
        ),
    ),
    dict(
        t="fxsl_bop",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="Foreign-exchange swap line / balance-of-payments; 'Yes' when applicable",
        desc=loanflag(
            "a foreign-exchange swap line or balance-of-payments loan",
            "uma linha de swap cambial ou empréstimo de balanço de pagamentos",
            "una línea de swap cambiario o préstamo de balanza de pagos",
        ),
    ),
    dict(
        t="cc_irs",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="Cross-currency interest-rate swap; 'Yes' when applicable",
        desc=loanflag(
            "a cross-currency interest-rate swap",
            "um swap de taxa de juros entre moedas",
            "un swap de tasa de interés entre monedas",
        ),
    ),
    dict(
        t="rcf",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="Revolving credit facility; 'Yes' when applicable",
        desc=loanflag(
            "a revolving credit facility",
            "uma linha de crédito rotativo",
            "una línea de crédito rotativo",
        ),
    ),
    dict(
        t="gcl",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="Government concessional loan; 'Yes' when applicable",
        desc=loanflag(
            "a government concessional loan",
            "um empréstimo concessional governamental",
            "un préstamo concesional gubernamental",
        ),
    ),
    dict(
        t="pbc",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="Preferential buyer's credit; 'Yes' when applicable",
        desc=loanflag(
            "a preferential buyer's credit",
            "um crédito preferencial ao comprador",
            "un crédito preferencial al comprador",
        ),
    ),
    dict(
        t="pxf_commodity_prepayment",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=loanflag(
            "a pre-export finance or commodity prepayment",
            "um financiamento pré-exportação ou pré-pagamento de commodities",
            "un financiamiento pre-exportación o prepago de materias primas",
        ),
    ),
    dict(
        t="inter_bank_loan",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=loanflag(
            "an inter-bank loan",
            "um empréstimo interbancário",
            "un préstamo interbancario",
        ),
    ),
    dict(
        t="overseas_project_contracting_loan",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=loanflag(
            "an overseas project contracting loan",
            "um empréstimo para contratação de projeto no exterior",
            "un préstamo para contratación de proyecto en el exterior",
        ),
    ),
    dict(
        t="dpa",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="Deferred payment agreement; 'Yes' when applicable",
        desc=loanflag(
            "a deferred payment agreement",
            "um acordo de pagamento diferido",
            "un acuerdo de pago diferido",
        ),
    ),
    dict(
        t="project_finance",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=loanflag(
            "a project finance arrangement",
            "um arranjo de project finance",
            "un arreglo de project finance",
        ),
    ),
    dict(
        t="involving_multilateral",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=(
            "Marker set to 'Yes' when a multilateral institution is involved",
            "Marcador definido como 'Sim' quando há envolvimento de instituição multilateral",
            "Marcador definido como 'Sí' cuando participa una institución multilateral",
        ),
    ),
    dict(
        t="non_chinese_financier",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Whether a non-Chinese financier is involved (Yes/No)",
            "Se há envolvimento de financiador não chinês (Sim/Não)",
            "Si participa un financiador no chino (Sí/No)",
        ),
    ),
    dict(
        t="short_term",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=loanflag(
            "short-term (maturity under one year)",
            "de curto prazo (vencimento inferior a um ano)",
            "de corto plazo (vencimiento inferior a un año)",
        ),
    ),
    dict(
        t="rescue",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=loanflag(
            "an emergency rescue loan",
            "um empréstimo de resgate emergencial",
            "un préstamo de rescate de emergencia",
        ),
    ),
    dict(
        t="jv_spv_host_government_ownership",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Host government ownership level of the project JV/SPV",
            "Nível de propriedade do governo anfitrião na JV/SPE do projeto",
            "Nivel de propiedad del gobierno anfitrión en la JV/SPV del proyecto",
        ),
    ),
    dict(
        t="jv_spv_chinese_government_ownership",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Chinese government ownership level of the project JV/SPV",
            "Nível de propriedade do governo chinês na JV/SPE do projeto",
            "Nivel de propiedad del gobierno chino en la JV/SPV del proyecto",
        ),
    ),
    dict(
        t="level_public_liability",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Level of public liability attached to the debt",
            "Nível de responsabilidade pública associado à dívida",
            "Nivel de responsabilidad pública asociado a la deuda",
        ),
    ),
    dict(
        t="total_source_count",
        ty="INT64",
        u="",
        d=0,
        dir="",
        obs="Count of sources",
        desc=(
            "Total number of sources supporting the record",
            "Número total de fontes que sustentam o registro",
            "Número total de fuentes que respaldan el registro",
        ),
    ),
    dict(
        t="official_source_count",
        ty="INT64",
        u="",
        d=0,
        dir="",
        obs="Count of official sources",
        desc=(
            "Number of official sources supporting the record",
            "Número de fontes oficiais que sustentam o registro",
            "Número de fuentes oficiales que respaldan el registro",
        ),
    ),
    dict(
        t="source_urls",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="Pipe-delimited",
        desc=(
            "URLs of the sources supporting the record",
            "URLs das fontes que sustentam o registro",
            "URLs de las fuentes que respaldan el registro",
        ),
    ),
    dict(
        t="source_titles",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="Pipe-delimited",
        desc=(
            "Titles of the sources supporting the record",
            "Títulos das fontes que sustentam o registro",
            "Títulos de las fuentes que respaldan el registro",
        ),
    ),
    dict(
        t="source_publishers",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="Pipe-delimited",
        desc=(
            "Publishers of the sources supporting the record",
            "Editores das fontes que sustentam o registro",
            "Editores de las fuentes que respaldan el registro",
        ),
    ),
    dict(
        t="source_resource_types",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="Pipe-delimited",
        desc=(
            "Resource types of the sources supporting the record",
            "Tipos de recurso das fontes que sustentam o registro",
            "Tipos de recurso de las fuentes que respaldan el registro",
        ),
    ),
    dict(
        t="contact_name",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="Public officials named in public sources",
        desc=(
            "Name of the contact person associated with the project/activity",
            "Nome da pessoa de contato associada ao projeto/atividade",
            "Nombre de la persona de contacto asociada al proyecto/actividad",
        ),
    ),
    dict(
        t="contact_position",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Position of the contact person associated with the project/activity",
            "Cargo da pessoa de contato associada ao projeto/atividade",
            "Cargo de la persona de contacto asociada al proyecto/actividad",
        ),
    ),
    dict(
        t="oda_eligible_recipient",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Whether the recipient country is ODA-eligible (Yes/No)",
            "Se o país receptor é elegível para AOD (Sim/Não)",
            "Si el país receptor es elegible para AOD (Sí/No)",
        ),
    ),
    dict(
        t="oecd_oda_income_group",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "OECD-DAC income group of the recipient country",
            "Grupo de renda OCDE-CAD do país receptor",
            "Grupo de ingresos OCDE-CAD del país receptor",
        ),
    ),
    dict(
        t="location_narrative",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Narrative description of the project/activity location",
            "Descrição narrativa da localização do projeto/atividade",
            "Descripción narrativa de la ubicación del proyecto/actividad",
        ),
    ),
    dict(
        t="geographic_precision_available",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="Precise, Admin Level, or Within 5km",
        desc=(
            "Best geographic precision available for the project/activity",
            "Melhor precisão geográfica disponível para o projeto/atividade",
            "Mejor precisión geográfica disponible para el proyecto/actividad",
        ),
    ),
    dict(
        t="adm1_level_available",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Whether ADM1-level location data are available (Yes/No)",
            "Se há dados de localização em nível ADM1 disponíveis (Sim/Não)",
            "Si hay datos de ubicación a nivel ADM1 disponibles (Sí/No)",
        ),
    ),
    dict(
        t="adm2_level_available",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="",
        desc=(
            "Whether ADM2-level location data are available (Yes/No)",
            "Se há dados de localização em nível ADM2 disponíveis (Sim/Não)",
            "Si hay datos de ubicación a nivel ADM2 disponibles (Sí/No)",
        ),
    ),
    dict(
        t="geospatial_feature_available",
        ty="STRING",
        u="",
        d=0,
        dir="",
        obs="'Yes' when applicable, otherwise blank",
        desc=(
            "Marker set to 'Yes' when a geospatial feature is available",
            "Marcador definido como 'Sim' quando há feição geoespacial disponível",
            "Marcador definido como 'Sí' cuando hay un elemento geoespacial disponible",
        ),
    ),
    dict(
        t="source_quality_score",
        ty="INT64",
        u="",
        d=0,
        dir="",
        obs="Ordinal score from 1 (lowest) to 5 (highest)",
        desc=(
            "AidData source-quality score, from 1 to 5",
            "Pontuação de qualidade das fontes da AidData, de 1 a 5",
            "Puntuación de calidad de las fuentes de AidData, de 1 a 5",
        ),
    ),
    dict(
        t="data_completeness_score",
        ty="INT64",
        u="",
        d=0,
        dir="",
        obs="Ordinal score from 1 (lowest) to 5 (highest)",
        desc=(
            "AidData data-completeness score, from 1 to 5",
            "Pontuação de completude dos dados da AidData, de 1 a 5",
            "Puntuación de completitud de los datos de AidData, de 1 a 5",
        ),
    ),
    dict(
        t="implementation_detail_score",
        ty="INT64",
        u="",
        d=0,
        dir="",
        obs="Ordinal score from 1 (lowest) to 5 (highest)",
        desc=(
            "AidData implementation-detail score, from 1 to 5",
            "Pontuação de detalhamento da implementação da AidData, de 1 a 5",
            "Puntuación de detalle de implementación de AidData, de 1 a 5",
        ),
    ),
    dict(
        t="loan_detail_score",
        ty="INT64",
        u="",
        d=0,
        dir="",
        obs="Ordinal score from 1 (lowest) to 5 (highest)",
        desc=(
            "AidData loan-detail score, from 1 to 5",
            "Pontuação de detalhamento do empréstimo da AidData, de 1 a 5",
            "Puntuación de detalle del préstamo de AidData, de 1 a 5",
        ),
    ),
]

# Output order: partition + geography + identifiers first, then source order.
LEAD = [
    "year",
    "country_iso3_code",
    "recipient_name",
    "recipient_region",
    "financier_country",
    "id_record",
    "id_parent",
]
_by_name = {c["t"]: c for c in COLS}
OUTPUT_ORDER = LEAD + [c["t"] for c in COLS if c["t"] not in LEAD]

TEMPORAL_TABLE = "2000(1)2021"


def rows():
    for name in OUTPUT_ORDER:
        c = _by_name[name]
        en, pt, es = c["desc"]
        yield dict(
            name=name,
            bigquery_type=c["ty"],
            description=pt,  # sheet `description` column is Portuguese
            description_en=en,
            description_es=es,
            temporal_coverage="" if name != "year" else TEMPORAL_TABLE,
            covered_by_dictionary="yes" if c["d"] else "no",
            directory_column=c["dir"],
            measurement_unit=c["u"],
            has_sensitive_data="no",
            observations=c["obs"],
            original_name="",  # filled from the workbook by clean.py/position
        )


HEADERS = [
    "name",
    "bigquery_type",
    "description",
    "description_en",
    "description_es",
    "temporal_coverage",
    "covered_by_dictionary",
    "directory_column",
    "measurement_unit",
    "has_sensitive_data",
    "observations",
    "original_name",
]

if __name__ == "__main__":
    assert len(COLS) == 126, f"expected 126 source columns, got {len(COLS)}"
    names = [c["t"] for c in COLS]
    assert len(set(names)) == 126, "duplicate target names"
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "world_aiddata_gcdf__projects.csv")
    with open(out, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=HEADERS)
        w.writeheader()
        for r in rows():
            w.writerow(r)
    print(f"wrote {out} ({len(OUTPUT_ORDER)} columns)")
