{{
    config(
        schema="cl_ine_censo",
        alias="persona",
        materialized="table",
        partition_by={
            "field": "ano",
            "data_type": "int64",
            "range": {"start": 2024, "end": 2029, "interval": 1},
        },
        cluster_by=["id_comuna"],
    )
}}


select
    safe_cast(ano as int64) ano,
    lpad(safe_cast(id_region as string), 2, '0') id_region,
    safe_cast(id_provincia as string) id_provincia,
    safe_cast(id_comuna as string) id_comuna,
    safe_cast(id_vivienda as string) id_vivienda,
    safe_cast(id_hogar as string) id_hogar,
    safe_cast(id_persona as string) id_persona,
    safe_cast(comuna_bajo_umbral as string) comuna_bajo_umbral,
    safe_cast(area as string) area,
    safe_cast(tipo_operativo as string) tipo_operativo,
    safe_cast(sexo as string) sexo,
    safe_cast(edad as int64) edad,
    safe_cast(edad_quinquenal as string) edad_quinquenal,
    safe_cast(parentesco as string) parentesco,
    safe_cast(p23_est_civil as string) p23_est_civil,
    safe_cast(p24_lug_resid5 as string) p24_lug_resid5,
    safe_cast(p24_lug_resid5_esp as string) p24_lug_resid5_esp,
    safe_cast(p25_lug_nacimiento as string) p25_lug_nacimiento,
    safe_cast(p25_lug_nacimiento_rec as string) p25_lug_nacimiento_rec,
    safe_cast(p25_lug_nacimiento_esp as string) p25_lug_nacimiento_esp,
    safe_cast(p26_llegada_periodo as string) p26_llegada_periodo,
    safe_cast(p27_nacionalidad as string) p27_nacionalidad,
    safe_cast(p27_nacionalidad_esp as string) p27_nacionalidad_esp,
    safe_cast(p27_nacionalidad_rec as string) p27_nacionalidad_rec,
    safe_cast(p28_autoid_pueblo as string) p28_autoid_pueblo,
    safe_cast(p28_pueblo_pert as string) p28_pueblo_pert,
    safe_cast(p29_afrodescendencia_rec as string) p29_afrodescendencia_rec,
    safe_cast(p29_afrodescendencia as string) p29_afrodescendencia,
    safe_cast(p30_lengua_indigena as string) p30_lengua_indigena,
    safe_cast(p30_lengua_indigena_rec as string) p30_lengua_indigena_rec,
    safe_cast(p31_religion as string) p31_religion,
    safe_cast(p31_religion_rec as string) p31_religion_rec,
    safe_cast(p32a_dificultad_ver as string) p32a_dificultad_ver,
    safe_cast(p32b_dificultad_oir as string) p32b_dificultad_oir,
    safe_cast(p32c_dificultad_mover as string) p32c_dificultad_mover,
    safe_cast(p32d_dificultad_cogni as string) p32d_dificultad_cogni,
    safe_cast(p32e_dificultad_cuidado as string) p32e_dificultad_cuidado,
    safe_cast(p32f_dificultad_comunic as string) p32f_dificultad_comunic,
    safe_cast(discapacidad as string) discapacidad,
    safe_cast(p33_edu_asiste as string) p33_edu_asiste,
    safe_cast(asistencia_parv as string) asistencia_parv,
    safe_cast(asistencia_basica as string) asistencia_basica,
    safe_cast(asistencia_media as string) asistencia_media,
    safe_cast(asistencia_superior as string) asistencia_superior,
    safe_cast(p37_alfabet as string) p37_alfabet,
    safe_cast(escolaridad as int64) escolaridad,
    safe_cast(cine11 as string) cine11,
    safe_cast(sit_fuerza_trabajo as string) sit_fuerza_trabajo,
    safe_cast(p40_cise_rec as string) p40_cise_rec,
    safe_cast(depend_econ_deficit_hab as string) depend_econ_deficit_hab,
    safe_cast(cod_ciuo as string) cod_ciuo,
    safe_cast(cod_caenes as string) cod_caenes,
    safe_cast(p44_lug_trab as string) p44_lug_trab,
    safe_cast(p44_lug_trab_esp as string) p44_lug_trab_esp,
    safe_cast(p45_medio_transporte as string) p45_medio_transporte,
    safe_cast(p46a_tot_hijs_nac as int64) p46a_tot_hijs_nac,
    safe_cast(p46b_hijas_nac as int64) p46b_hijas_nac,
    safe_cast(p46c_hijos_nac as int64) p46c_hijos_nac,
    safe_cast(p47a_tot_hijs_sobrev as int64) p47a_tot_hijs_sobrev,
    safe_cast(p47b_hijas_sobrev as int64) p47b_hijas_sobrev,
    safe_cast(p47c_hijos_sobrev as int64) p47c_hijos_sobrev,
    safe_cast(p48_anio_nac_uh as int64) p48_anio_nac_uh,
    safe_cast(p48_mes_nac_uh as int64) p48_mes_nac_uh,
    safe_cast(div_genero as string) div_genero
from {{ set_datalake_project("cl_ine_censo_staging.persona") }} as t
