{{
    config(
        schema="us_dol_oflc",
        alias="perm",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 2008, "end": 2031, "interval": 1},
        },
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(case_number as string) case_number,
    safe_cast(case_status as string) case_status,
    safe_cast(received_date as date) received_date,
    safe_cast(decision_date as date) decision_date,
    safe_cast(employer_name as string) employer_name,
    safe_cast(employer_trade_name as string) employer_trade_name,
    safe_cast(employer_address as string) employer_address,
    safe_cast(employer_city as string) employer_city,
    safe_cast(employer_state as string) employer_state,
    safe_cast(employer_postal_code as string) employer_postal_code,
    safe_cast(employer_country as string) employer_country,
    safe_cast(naics_id as string) naics_id,
    safe_cast(job_title as string) job_title,
    safe_cast(soc_id as string) soc_id,
    safe_cast(soc_title as string) soc_title,
    safe_cast(full_time_position as string) full_time_position,
    safe_cast(wage_offered_from as float64) wage_offered_from,
    safe_cast(wage_offered_to as float64) wage_offered_to,
    safe_cast(wage_unit_of_pay as string) wage_unit_of_pay,
    safe_cast(wage_offered_from_annual as float64) wage_offered_from_annual,
    safe_cast(wage_offered_to_annual as float64) wage_offered_to_annual,
    safe_cast(prevailing_wage as float64) prevailing_wage,
    safe_cast(prevailing_wage_unit_of_pay as string) prevailing_wage_unit_of_pay,
    safe_cast(prevailing_wage_annual as float64) prevailing_wage_annual,
    safe_cast(prevailing_wage_level as string) prevailing_wage_level,
    safe_cast(prevailing_wage_source as string) prevailing_wage_source,
    safe_cast(prevailing_wage_tracking_number as string) prevailing_wage_tracking_number,
    safe_cast(worksite_address as string) worksite_address,
    safe_cast(worksite_city as string) worksite_city,
    safe_cast(worksite_county as string) worksite_county,
    safe_cast(worksite_state as string) worksite_state,
    safe_cast(worksite_postal_code as string) worksite_postal_code,
    safe_cast(attorney_law_firm_name as string) attorney_law_firm_name,
    safe_cast(agent_representing_employer as string) agent_representing_employer,
    safe_cast(application_type as string) application_type,
    safe_cast(refile as string) refile,
    safe_cast(schedule_a_sheepherder as string) schedule_a_sheepherder,
    safe_cast(us_economic_sector as string) us_economic_sector,
    safe_cast(employer_num_employees as int64) employer_num_employees,
    safe_cast(employer_year_commenced_business as int64) employer_year_commenced_business,
    safe_cast(prevailing_wage_determination_date as date) prevailing_wage_determination_date,
    safe_cast(prevailing_wage_expiration_date as date) prevailing_wage_expiration_date,
    safe_cast(minimum_education as string) minimum_education,
    safe_cast(major_field_of_study as string) major_field_of_study,
    safe_cast(required_experience as string) required_experience,
    safe_cast(required_experience_months as int64) required_experience_months,
    safe_cast(country_of_citizenship as string) country_of_citizenship,
    safe_cast(foreign_worker_birth_country as string) foreign_worker_birth_country,
    safe_cast(class_of_admission as string) class_of_admission,
    safe_cast(foreign_worker_education as string) foreign_worker_education,
    safe_cast(is_multiple_worksites as string) is_multiple_worksites,
    safe_cast(source_file as string) source_file
from {{ set_datalake_project("us_dol_oflc_staging.perm") }} as t
