{{
    config(
        schema="us_dol_oflc",
        alias="lca",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 2008, "end": 2031, "interval": 1},
        },
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(case_number as string) case_number,
    safe_cast(case_status as string) case_status,
    safe_cast(visa_class as string) visa_class,
    safe_cast(received_date as date) received_date,
    safe_cast(decision_date as date) decision_date,
    safe_cast(employment_begin_date as date) employment_begin_date,
    safe_cast(employment_end_date as date) employment_end_date,
    safe_cast(employer_name as string) employer_name,
    safe_cast(employer_trade_name as string) employer_trade_name,
    safe_cast(employer_address as string) employer_address,
    safe_cast(employer_city as string) employer_city,
    safe_cast(employer_state as string) employer_state,
    safe_cast(employer_postal_code as string) employer_postal_code,
    safe_cast(employer_country as string) employer_country,
    safe_cast(naics_id as string) naics_id,
    safe_cast(job_title as string) job_title,
    safe_cast(soc_id as string) soc_id,
    safe_cast(soc_title as string) soc_title,
    safe_cast(full_time_position as string) full_time_position,
    safe_cast(wage_offered_from as float64) wage_offered_from,
    safe_cast(wage_offered_to as float64) wage_offered_to,
    safe_cast(wage_unit_of_pay as string) wage_unit_of_pay,
    safe_cast(wage_offered_from_annual as float64) wage_offered_from_annual,
    safe_cast(wage_offered_to_annual as float64) wage_offered_to_annual,
    safe_cast(prevailing_wage as float64) prevailing_wage,
    safe_cast(prevailing_wage_unit_of_pay as string) prevailing_wage_unit_of_pay,
    safe_cast(prevailing_wage_annual as float64) prevailing_wage_annual,
    safe_cast(prevailing_wage_level as string) prevailing_wage_level,
    safe_cast(prevailing_wage_source as string) prevailing_wage_source,
    safe_cast(prevailing_wage_source_year as string) prevailing_wage_source_year,
    safe_cast(prevailing_wage_tracking_number as string) prevailing_wage_tracking_number,
    safe_cast(worksite_address as string) worksite_address,
    safe_cast(worksite_city as string) worksite_city,
    safe_cast(worksite_county as string) worksite_county,
    safe_cast(worksite_state as string) worksite_state,
    safe_cast(worksite_postal_code as string) worksite_postal_code,
    safe_cast(attorney_law_firm_name as string) attorney_law_firm_name,
    safe_cast(agent_representing_employer as string) agent_representing_employer,
    safe_cast(original_certification_date as date) original_certification_date,
    safe_cast(total_workers as int64) total_workers,
    safe_cast(new_employment as int64) new_employment,
    safe_cast(continued_employment as int64) continued_employment,
    safe_cast(change_previous_employment as int64) change_previous_employment,
    safe_cast(new_concurrent_employment as int64) new_concurrent_employment,
    safe_cast(change_employer as int64) change_employer,
    safe_cast(amended_petition as int64) amended_petition,
    safe_cast(worksite_workers as int64) worksite_workers,
    safe_cast(total_worksite_locations as int64) total_worksite_locations,
    safe_cast(secondary_entity as string) secondary_entity,
    safe_cast(secondary_entity_business_name as string) secondary_entity_business_name,
    safe_cast(h1b_dependent as string) h1b_dependent,
    safe_cast(willful_violator as string) willful_violator,
    safe_cast(support_h1b as string) support_h1b,
    safe_cast(statutory_basis as string) statutory_basis,
    safe_cast(withdrawn as string) withdrawn,
    safe_cast(source_file as string) source_file
from {{ set_datalake_project("us_dol_oflc_staging.lca") }} as t
