{{
    config(
        schema="us_dol_oflc",
        alias="h2b",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 2008, "end": 2031, "interval": 1},
        },
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(case_number as string) case_number,
    safe_cast(case_status as string) case_status,
    safe_cast(visa_class as string) visa_class,
    safe_cast(received_date as date) received_date,
    safe_cast(decision_date as date) decision_date,
    safe_cast(employment_begin_date as date) employment_begin_date,
    safe_cast(employment_end_date as date) employment_end_date,
    safe_cast(employer_name as string) employer_name,
    safe_cast(employer_trade_name as string) employer_trade_name,
    safe_cast(employer_address as string) employer_address,
    safe_cast(employer_city as string) employer_city,
    safe_cast(employer_state as string) employer_state,
    safe_cast(employer_postal_code as string) employer_postal_code,
    safe_cast(employer_country as string) employer_country,
    safe_cast(naics_id as string) naics_id,
    safe_cast(job_title as string) job_title,
    safe_cast(soc_id as string) soc_id,
    safe_cast(soc_title as string) soc_title,
    safe_cast(full_time_position as string) full_time_position,
    safe_cast(wage_offered_from as float64) wage_offered_from,
    safe_cast(wage_offered_to as float64) wage_offered_to,
    safe_cast(wage_unit_of_pay as string) wage_unit_of_pay,
    safe_cast(wage_offered_from_annual as float64) wage_offered_from_annual,
    safe_cast(wage_offered_to_annual as float64) wage_offered_to_annual,
    safe_cast(prevailing_wage as float64) prevailing_wage,
    safe_cast(prevailing_wage_unit_of_pay as string) prevailing_wage_unit_of_pay,
    safe_cast(prevailing_wage_annual as float64) prevailing_wage_annual,
    safe_cast(prevailing_wage_tracking_number as string) prevailing_wage_tracking_number,
    safe_cast(worksite_address as string) worksite_address,
    safe_cast(worksite_city as string) worksite_city,
    safe_cast(worksite_county as string) worksite_county,
    safe_cast(worksite_state as string) worksite_state,
    safe_cast(worksite_postal_code as string) worksite_postal_code,
    safe_cast(attorney_law_firm_name as string) attorney_law_firm_name,
    safe_cast(agent_representing_employer as string) agent_representing_employer,
    safe_cast(application_type as string) application_type,
    safe_cast(certification_begin_date as date) certification_begin_date,
    safe_cast(certification_end_date as date) certification_end_date,
    safe_cast(requested_begin_date as date) requested_begin_date,
    safe_cast(requested_end_date as date) requested_end_date,
    safe_cast(nature_of_temporary_need as string) nature_of_temporary_need,
    safe_cast(cap_exempt as string) cap_exempt,
    safe_cast(type_of_employer as string) type_of_employer,
    safe_cast(job_order_number as string) job_order_number,
    safe_cast(job_order_submit_date as date) job_order_submit_date,
    safe_cast(swa_state as string) swa_state,
    safe_cast(workers_requested as int64) workers_requested,
    safe_cast(workers_certified as int64) workers_certified,
    safe_cast(anticipated_number_of_hours as float64) anticipated_number_of_hours,
    safe_cast(overtime_rate_from as float64) overtime_rate_from,
    safe_cast(overtime_rate_to as float64) overtime_rate_to,
    safe_cast(msa_name as string) msa_name,
    safe_cast(education_level as string) education_level,
    safe_cast(work_experience_months as int64) work_experience_months,
    safe_cast(source_file as string) source_file
from {{ set_datalake_project("us_dol_oflc_staging.h2b") }} as t
