{{
    config(
        schema="us_dol_oflc",
        alias="h2a",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 2008, "end": 2031, "interval": 1},
        },
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(case_number as string) case_number,
    safe_cast(case_status as string) case_status,
    safe_cast(visa_class as string) visa_class,
    safe_cast(received_date as date) received_date,
    safe_cast(decision_date as date) decision_date,
    safe_cast(employment_begin_date as date) employment_begin_date,
    safe_cast(employment_end_date as date) employment_end_date,
    safe_cast(employer_name as string) employer_name,
    safe_cast(employer_trade_name as string) employer_trade_name,
    safe_cast(employer_address as string) employer_address,
    safe_cast(employer_city as string) employer_city,
    safe_cast(employer_state as string) employer_state,
    safe_cast(employer_postal_code as string) employer_postal_code,
    safe_cast(employer_country as string) employer_country,
    safe_cast(naics_id as string) naics_id,
    safe_cast(job_title as string) job_title,
    safe_cast(soc_id as string) soc_id,
    safe_cast(soc_title as string) soc_title,
    safe_cast(full_time_position as string) full_time_position,
    safe_cast(wage_offered_from as float64) wage_offered_from,
    safe_cast(wage_unit_of_pay as string) wage_unit_of_pay,
    safe_cast(wage_offered_from_annual as float64) wage_offered_from_annual,
    safe_cast(worksite_address as string) worksite_address,
    safe_cast(worksite_city as string) worksite_city,
    safe_cast(worksite_county as string) worksite_county,
    safe_cast(worksite_state as string) worksite_state,
    safe_cast(worksite_postal_code as string) worksite_postal_code,
    safe_cast(attorney_law_firm_name as string) attorney_law_firm_name,
    safe_cast(agent_representing_employer as string) agent_representing_employer,
    safe_cast(certification_begin_date as date) certification_begin_date,
    safe_cast(certification_end_date as date) certification_end_date,
    safe_cast(requested_begin_date as date) requested_begin_date,
    safe_cast(requested_end_date as date) requested_end_date,
    safe_cast(type_of_employer_application as string) type_of_employer_application,
    safe_cast(h2a_labor_contractor as string) h2a_labor_contractor,
    safe_cast(nature_of_temporary_need as string) nature_of_temporary_need,
    safe_cast(emergency_filing as string) emergency_filing,
    safe_cast(primary_crop as string) primary_crop,
    safe_cast(job_order_number as string) job_order_number,
    safe_cast(swa_name as string) swa_name,
    safe_cast(workers_requested as int64) workers_requested,
    safe_cast(workers_certified as int64) workers_certified,
    safe_cast(anticipated_number_of_hours as float64) anticipated_number_of_hours,
    safe_cast(piece_rate_offer as float64) piece_rate_offer,
    safe_cast(piece_rate_unit as string) piece_rate_unit,
    safe_cast(overtime_rate_from as float64) overtime_rate_from,
    safe_cast(overtime_rate_to as float64) overtime_rate_to,
    safe_cast(frequency_of_pay as string) frequency_of_pay,
    safe_cast(education_level as string) education_level,
    safe_cast(work_experience_months as int64) work_experience_months,
    safe_cast(housing_city as string) housing_city,
    safe_cast(housing_state as string) housing_state,
    safe_cast(housing_type as string) housing_type,
    safe_cast(housing_total_occupancy as int64) housing_total_occupancy,
    safe_cast(meals_provided as string) meals_provided,
    safe_cast(total_worksite_records as int64) total_worksite_records,
    safe_cast(source_file as string) source_file
from {{ set_datalake_project("us_dol_oflc_staging.h2a") }} as t
