"""SDMX component -> Data Basis column name, type and trilingual description.

The OECD serves structure metadata in English and French only, so every Portuguese
and Spanish string here is written by hand. There are 66 distinct components across
the 15 cubes and they are heavily reused, which is why translating them properly is
cheap — unlike the codelists underneath them (thousands of codes), whose labels go
to the ``dicionario`` table untranslated, as the source publishes them.

Column names are English because the data and its metadata are English
(.claude/rules/data-basis-style.md). Every dimension is a code resolved by the
``dicionario`` table, so all of them are STRING with ``covered_by_dictionary=yes``;
numeric-looking ones (``unit_multiplier``, ``decimals``) are codelist-backed and
categorical, not quantities, per the type-by-arithmetic-meaning rule.
"""

# name, bigquery_type, description pt/en/es, covered_by_dictionary
# Ordered roughly by how widely each component is used across the cubes.
CONCEPTS = {
    # --- identity and grain -------------------------------------------------
    "REF_AREA": (
        "reference_area",
        "STRING",
        True,
        "Área de referência da observação: país, entidade subnacional ou agregado",
        "Reference area of the observation: country, subnational entity or aggregate",
        "Área de referencia de la observación: país, entidad subnacional o agregado",
    ),
    "TIME_PERIOD": (
        "year",
        "INT64",
        False,
        "Ano de referência da observação",
        "Reference year of the observation",
        "Año de referencia de la observación",
    ),
    "MEASURE": (
        "measure",
        "STRING",
        True,
        "Grandeza medida pela observação",
        "Quantity the observation measures",
        "Magnitud que mide la observación",
    ),
    "UNIT_MEASURE": (
        "unit_measure",
        "STRING",
        True,
        "Unidade em que a observação está expressa",
        "Unit in which the observation is expressed",
        "Unidad en que se expresa la observación",
    ),
    "OBS_VALUE": (
        "obs_value",
        "FLOAT64",
        False,
        "Valor da observação",
        "Value of the observation",
        "Valor de la observación",
    ),
    # --- education dimensions ----------------------------------------------
    "EDUCATION_LEV": (
        "education_level",
        "STRING",
        True,
        "Nível de ensino segundo a CINE 2011 (ISCED 2011)",
        "Level of education under ISCED 2011",
        "Nivel de enseñanza según la CINE 2011 (ISCED 2011)",
    ),
    "ATTAINMENT_LEV": (
        "attainment_level",
        "STRING",
        True,
        "Nível de escolaridade concluído pela pessoa",
        "Highest level of education the person completed",
        "Nivel de escolaridad completado por la persona",
    ),
    "EDUCATION_FIELD": (
        "education_field",
        "STRING",
        True,
        "Área de formação segundo a CINE-F 2013",
        "Field of education under ISCED-F 2013",
        "Ámbito de formación según la CINE-F 2013",
    ),
    "EDUCATION_TYPE": (
        "education_type",
        "STRING",
        True,
        "Tipo de ensino, distinguindo educação formal inicial e de adultos",
        "Type of education, separating formal initial and adult programmes",
        "Tipo de enseñanza, distinguiendo educación formal inicial y de adultos",
    ),
    "EDU_STATUS": (
        "education_status",
        "STRING",
        True,
        "Situação da pessoa quanto à participação em educação ou formação",
        "Whether the person is in education or training",
        "Situación de la persona respecto a su participación en educación o formación",
    ),
    "INST_TYPE_EDU": (
        "education_institution_type",
        "STRING",
        True,
        "Natureza da instituição de ensino: pública, privada dependente ou independente do governo",
        "Nature of the educational institution: public, government-dependent private or independent private",
        "Naturaleza de la institución educativa: pública, privada dependiente o independiente del gobierno",
    ),
    "INSTITUTION_TYPE": (
        "institution_type",
        "STRING",
        True,
        "Tipo de instituição declarado no inquérito TALIS",
        "Type of institution as reported in the TALIS survey",
        "Tipo de institución declarado en la encuesta TALIS",
    ),
    "GRADE": (
        "grade",
        "STRING",
        True,
        "Série ou ano de estudo dentro do nível de ensino",
        "Grade or year of study within the level of education",
        "Grado o año de estudio dentro del nivel de enseñanza",
    ),
    "INTENSITY": (
        "intensity",
        "STRING",
        True,
        "Regime de dedicação do estudante: tempo integral ou parcial",
        "Student's mode of attendance: full-time or part-time",
        "Régimen de dedicación del estudiante: tiempo completo o parcial",
    ),
    "SUBJ_TYPE": (
        "subject",
        "STRING",
        True,
        "Disciplina ou área do currículo a que se refere o tempo de instrução",
        "Curriculum subject the instruction time refers to",
        "Asignatura o área del currículo a que se refiere el tiempo de instrucción",
    ),
    "MOBILITY": (
        "mobility",
        "STRING",
        True,
        "Condição de mobilidade internacional do estudante",
        "International mobility status of the student",
        "Condición de movilidad internacional del estudiante",
    ),
    "ORIGIN": (
        "origin_area",
        "STRING",
        True,
        "País ou região de origem do estudante móvel",
        "Country or region of origin of the mobile student",
        "País o región de origen del estudiante móvil",
    ),
    "DESTINATION": (
        "destination_area",
        "STRING",
        True,
        "País ou região de destino do estudante móvel",
        "Country or region of destination of the mobile student",
        "País o región de destino del estudiante móvil",
    ),
    # --- people -------------------------------------------------------------
    "SEX": (
        "sex",
        "STRING",
        True,
        "Sexo da população de referência",
        "Sex of the reference population",
        "Sexo de la población de referencia",
    ),
    "AGE": (
        "age",
        "STRING",
        True,
        "Idade ou faixa etária da população de referência",
        "Age or age band of the reference population",
        "Edad o grupo de edad de la población de referencia",
    ),
    "PERS_TYPE": (
        "personnel_type",
        "STRING",
        True,
        "Categoria do pessoal escolar: docentes, direção ou auxiliares",
        "Category of school personnel: teachers, school heads or aides",
        "Categoría del personal escolar: docentes, dirección o auxiliares",
    ),
    "PERS_QUAL_LEV": (
        "personnel_qualification_level",
        "STRING",
        True,
        "Nível de qualificação do pessoal, usado para comparar salários",
        "Qualification level of the personnel, used to compare salaries",
        "Nivel de cualificación del personal, usado para comparar salarios",
    ),
    "PERS_EXP_LEV": (
        "personnel_experience_level",
        "STRING",
        True,
        "Tempo de experiência do pessoal, usado para comparar salários",
        "Experience level of the personnel, used to compare salaries",
        "Tiempo de experiencia del personal, usado para comparar salarios",
    ),
    "TEACHER_PROFILE": (
        "teacher_profile",
        "STRING",
        True,
        "Perfil do docente segundo o recorte usado no TALIS",
        "Teacher profile under the breakdown used in TALIS",
        "Perfil del docente según el desglose usado en TALIS",
    ),
    "STUDENTS_CHARACTERISTICS": (
        "students_characteristics",
        "STRING",
        True,
        "Característica do corpo discente da escola no TALIS",
        "Characteristic of the school's student body in TALIS",
        "Característica del alumnado de la escuela en TALIS",
    ),
    "BIRTH_PLACE": (
        "birth_place",
        "STRING",
        True,
        "Local de nascimento, distinguindo nativos de imigrantes",
        "Place of birth, separating native-born from foreign-born",
        "Lugar de nacimiento, distinguiendo nativos de inmigrantes",
    ),
    "MIGRATION_AGE": (
        "migration_age",
        "STRING",
        True,
        "Idade em que a pessoa imigrou",
        "Age at which the person migrated",
        "Edad a la que la persona migró",
    ),
    # --- labour market ------------------------------------------------------
    "LABOUR_FORCE_STATUS": (
        "labour_force_status",
        "STRING",
        True,
        "Condição da pessoa perante a força de trabalho",
        "Person's status with respect to the labour force",
        "Condición de la persona respecto a la fuerza de trabajo",
    ),
    "DURATION_UNEMP": (
        "unemployment_duration",
        "STRING",
        True,
        "Tempo decorrido de desemprego",
        "Length of time spent unemployed",
        "Tiempo transcurrido de desempleo",
    ),
    "WORK_TIME_ARNGMNT": (
        "work_time_arrangement",
        "STRING",
        True,
        "Regime de jornada de trabalho: tempo integral ou parcial",
        "Working time arrangement: full-time or part-time",
        "Régimen de jornada laboral: tiempo completo o parcial",
    ),
    "INCOME": (
        "income",
        "STRING",
        True,
        "Faixa de rendimento relativa à mediana",
        "Earnings band relative to the median",
        "Tramo de ingresos relativo a la mediana",
    ),
    # --- finance ------------------------------------------------------------
    "EXP_SOURCE": (
        "financing_source",
        "STRING",
        True,
        "Origem dos recursos aplicados em educação",
        "Source of the funds spent on education",
        "Origen de los recursos destinados a educación",
    ),
    "EXP_DESTINATION": (
        "expenditure_destination",
        "STRING",
        True,
        "Destino da despesa em educação",
        "Destination of the education expenditure",
        "Destino del gasto en educación",
    ),
    "EXPENDITURE_TYPE": (
        "expenditure_type",
        "STRING",
        True,
        "Natureza da despesa: corrente, de capital ou por rubrica",
        "Nature of the expenditure: current, capital or by line item",
        "Naturaleza del gasto: corriente, de capital o por rubro",
    ),
    "URBANISATION": (
        "urbanisation_degree",
        "STRING",
        True,
        "Grau de urbanização da localidade da escola",
        "Degree of urbanisation of the school's locality",
        "Grado de urbanización de la localidad de la escuela",
    ),
    # --- observation metadata ----------------------------------------------
    "FREQ": (
        "frequency",
        "STRING",
        True,
        "Periodicidade da série",
        "Frequency of the series",
        "Periodicidad de la serie",
    ),
    "STATISTICAL_OPERATION": (
        "statistical_operation",
        "STRING",
        True,
        "Operação estatística aplicada ao valor, por exemplo média ou mediana",
        "Statistical operation applied to the value, such as mean or median",
        "Operación estadística aplicada al valor, por ejemplo media o mediana",
    ),
    "PRICE_BASE": (
        "price_base",
        "STRING",
        True,
        "Base de preços do valor monetário: corrente ou constante",
        "Price base of the monetary value: current or constant",
        "Base de precios del valor monetario: corriente o constante",
    ),
    "BASE_PER": (
        "base_period",
        "STRING",
        False,
        "Ano-base usado quando o valor está a preços constantes",
        "Base year used when the value is at constant prices",
        "Año base usado cuando el valor está a precios constantes",
    ),
    "CURRENCY": (
        "currency",
        "STRING",
        True,
        "Moeda em que o valor monetário está expresso",
        "Currency the monetary value is expressed in",
        "Moneda en que se expresa el valor monetario",
    ),
    "UNIT_MULT": (
        "unit_multiplier",
        "STRING",
        True,
        "Potência de dez pela qual o valor deve ser multiplicado",
        "Power of ten the value must be multiplied by",
        "Potencia de diez por la que debe multiplicarse el valor",
    ),
    "DECIMALS": (
        "decimals",
        "STRING",
        True,
        "Número de casas decimais com que a fonte publica o valor",
        "Number of decimal places the source publishes the value with",
        "Número de decimales con que la fuente publica el valor",
    ),
    "OBS_STATUS": (
        "obs_status",
        "STRING",
        True,
        "Situação da observação, incluindo o motivo de ausência do valor",
        "Status of the observation, including why a value is absent",
        "Situación de la observación, incluido el motivo de ausencia del valor",
    ),
    "OBS_STATUS_2": (
        "obs_status_2",
        "STRING",
        True,
        "Segunda marcação de situação da observação, quando a fonte registra mais de uma",
        "Second observation status flag, where the source records more than one",
        "Segunda marca de situación de la observación, cuando la fuente registra más de una",
    ),
    "OBS_STATUS_3": (
        "obs_status_3",
        "STRING",
        True,
        "Terceira marcação de situação da observação, quando a fonte registra mais de uma",
        "Third observation status flag, where the source records more than one",
        "Tercera marca de situación de la observación, cuando la fuente registra más de una",
    ),
    "CONF_STATUS": (
        "confidentiality_status",
        "STRING",
        True,
        "Situação de confidencialidade da observação",
        "Confidentiality status of the observation",
        "Situación de confidencialidad de la observación",
    ),
    "COMMENT_OBS": (
        "obs_comment",
        "STRING",
        False,
        "Nota de rodapé da fonte sobre a observação",
        "Source footnote about the observation",
        "Nota al pie de la fuente sobre la observación",
    ),
    "TRANSFORMATION": (
        "transformation",
        "STRING",
        True,
        "Transformação aplicada ao valor em relação à série de origem",
        "Transformation applied to the value relative to the source series",
        "Transformación aplicada al valor respecto a la serie de origen",
    ),
    # --- reference periods and reporting ------------------------------------
    "REF_PERIOD": (
        "reference_period",
        "STRING",
        False,
        "Período de referência declarado pela fonte para a observação",
        "Reference period the source declares for the observation",
        "Período de referencia declarado por la fuente para la observación",
    ),
    "REF_YEAR_AGES": (
        "reference_date_ages",
        "STRING",
        False,
        "Data de referência usada para apurar as idades",
        "Reference date used to determine ages",
        "Fecha de referencia usada para determinar las edades",
    ),
    "REPYEARSTART": (
        "reporting_year_start",
        "STRING",
        False,
        "Início do ano de referência do país, quando não coincide com o ano civil",
        "Start of the country's reporting year, where it differs from the calendar year",
        "Inicio del año de referencia del país, cuando no coincide con el año civil",
    ),
    "REPYEAREND": (
        "reporting_year_end",
        "STRING",
        False,
        "Fim do ano de referência do país, quando não coincide com o ano civil",
        "End of the country's reporting year, where it differs from the calendar year",
        "Fin del año de referencia del país, cuando no coincide con el año civil",
    ),
    "TIME_PER_COLLECT": (
        "time_period_collection",
        "STRING",
        True,
        "Momento do período a que a coleta se refere",
        "Point in the period the collection refers to",
        "Momento del período al que se refiere la recolección",
    ),
    "ORIGIN_CRITERION": (
        "origin_criterion",
        "STRING",
        True,
        "Critério usado para classificar a origem do estudante móvel",
        "Criterion used to classify the mobile student's origin",
        "Criterio usado para clasificar el origen del estudiante móvil",
    ),
    "LAST_UPDATE": (
        "last_update",
        "STRING",
        False,
        "Data em que a fonte atualizou a observação",
        "Date the source last updated the observation",
        "Fecha en que la fuente actualizó la observación",
    ),
    "LAST_MODIFIED": (
        "last_modified",
        "STRING",
        False,
        "Data em que a fonte modificou a observação",
        "Date the source last modified the observation",
        "Fecha en que la fuente modificó la observación",
    ),
    "COUNTRY": (
        "country_note",
        "STRING",
        False,
        "País a que a nota da fonte se refere",
        "Country the source note refers to",
        "País al que se refiere la nota de la fuente",
    ),
    "SOURCE_DATA": (
        "data_source",
        "STRING",
        False,
        "Fonte primária de onde a OCDE obteve a observação",
        "Primary source the OECD obtained the observation from",
        "Fuente primaria de donde la OCDE obtuvo la observación",
    ),
    # --- questionnaire provenance -------------------------------------------
    "QUESTIONNAIRE": (
        "questionnaire",
        "STRING",
        True,
        "Questionário do qual a observação foi extraída",
        "Questionnaire the observation was drawn from",
        "Cuestionario del que se extrajo la observación",
    ),
    "Q_SHEET": (
        "questionnaire_sheet",
        "STRING",
        True,
        "Aba do questionário de origem da observação",
        "Sheet of the source questionnaire the observation comes from",
        "Pestaña del cuestionario de origen de la observación",
    ),
    "Q_SHEET_ROW_ID": (
        "questionnaire_row_id",
        "STRING",
        False,
        "Identificador da linha na aba do questionário de origem",
        "Row identifier within the source questionnaire sheet",
        "Identificador de la fila en la pestaña del cuestionario de origen",
    ),
    "ATTRIBUTE_TALIS": (
        "talis_question",
        "STRING",
        False,
        "Pergunta do TALIS e resposta a que a observação corresponde",
        "TALIS question and response the observation corresponds to",
        "Pregunta del TALIS y respuesta a la que corresponde la observación",
    ),
    # --- derived ratio components (FIN_ANNEX) -------------------------------
    "NUMERATOR_CATEGORY": (
        "numerator_category",
        "STRING",
        True,
        "Categoria que compõe o numerador do indicador",
        "Category making up the indicator's numerator",
        "Categoría que compone el numerador del indicador",
    ),
    "NUMERATOR_VALUE": (
        "numerator_value",
        "STRING",
        False,
        "Valor do numerador do indicador",
        "Value of the indicator's numerator",
        "Valor del numerador del indicador",
    ),
    "DENOMINATOR_CATEGORY": (
        "denominator_category",
        "STRING",
        True,
        "Categoria que compõe o denominador do indicador",
        "Category making up the indicator's denominator",
        "Categoría que compone el denominador del indicador",
    ),
    "DENOMINATOR_VALUE": (
        "denominator_value",
        "STRING",
        False,
        "Valor do denominador do indicador",
        "Value of the indicator's denominator",
        "Valor del denominador del indicador",
    ),
}
