{{ config(alias="microdados", schema="br_cnpq_bolsas") }}

select
    safe_cast(ano as int64) ano,
    safe_cast(processo as string) processo,
    safe_cast(data_inicio_processo as date) data_inicio_processo,
    safe_cast(data_fim_processo as date) data_fim_processo,
    safe_cast(beneficiario as string) beneficiario,
    safe_cast(titulo_projeto as string) titulo_projeto,
    safe_cast(palavra_chave as string) palavra_chave,
    safe_cast(linha_fomento as string) linha_fomento,
    safe_cast(modalidade as string) modalidade,
    safe_cast(categoria_nivel as string) categoria_nivel,
    safe_cast(chamada as string) chamada,
    safe_cast(programa_cnpq as string) programa_cnpq,
    safe_cast(grande_area_conhecimento as string) grande_area_conhecimento,
    safe_cast(area_conhecimento as string) area_conhecimento,
    safe_cast(subarea_conhecimento as string) subarea_conhecimento,
    safe_cast(pais_origem as string) pais_origem,
    safe_cast(sigla_uf_origem as string) sigla_uf_origem,
    safe_cast(instituicao_origem as string) instituicao_origem,
    safe_cast(pais_destino as string) pais_destino,
    safe_cast(sigla_uf_destino as string) sigla_uf_destino,
    safe_cast(municipio_destino as string) municipio_destino,
    safe_cast(sigla_instituicao_destino as string) sigla_instituicao_destino,
    safe_cast(sigla_instituicao_macro as string) sigla_instituicao_macro,
    safe_cast(instituicao_destino as string) instituicao_destino,
    safe_cast(plano_interno as string) plano_interno,
    safe_cast(unidade_orcamentaria as string) unidade_orcamentaria,
    safe_cast(fonte_recurso as string) fonte_recurso,
    safe_cast(natureza_despesa as string) natureza_despesa,
    safe_cast(programa_ppa as string) programa_ppa,
    safe_cast(acao_ppa as string) acao_ppa,
    safe_cast(valor as float64) valor
from {{ set_datalake_project("br_cnpq_bolsas_staging.microdados") }} as t
