---
default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: basedosdados-dev
      dataset: dbt
      location: US
      threads: 2
      keyfile: "{{ env_var('BD_SERVICE_ACCOUNT_DEV', '/credentials-dev/dev.json') }}"
    prod:
      type: bigquery
      method: service-account
      project: basedosdados
      dataset: dbt
      location: US
      threads: 2
      keyfile: "{{ env_var('BD_SERVICE_ACCOUNT_DEV', '/credentials-prod/prod.json') }}"
    data-api:
      type: bigquery
      method: service-account
      project: basedosdados-data-api
      dataset: dbt
      location: US
      threads: 2
      keyfile: "{{ env_var('BD_SERVICE_ACCOUNT_DEV', '/credentials-prod/prod.json') }}"
elementary:
  outputs:
    default:
      type: bigquery
      project: basedosdados
      dataset: elementary
      method: service-account
      keyfile: /tmp/bigquery_keyfile.json
      threads: 2
