---
default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: basedosdados-dev
      dataset: dbt
      location: US
      threads: 2
      keyfile: "{{ env_var('BD_DBT_SERVICE_ACCOUNT_DEV') }}"
    prod:
      type: bigquery
      method: service-account
      project: basedosdados
      dataset: dbt
      location: US
      threads: 2
      keyfile: "{{ env_var('BD_DBT_SERVICE_ACCOUNT_PROD') }}"
elementary:
  outputs:
    default:
      type: bigquery
      project: basedosdados
      dataset: elementary
      method: service-account
      keyfile: /tmp/bigquery_keyfile.json
      threads: 2
