---
default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: basedosdados-dev
      dataset: dbt
      location: US
      threads: 2
      keyfile: "{{ env_var('BD_SERVICE_ACCOUNT_DEV', '/credentials-dev/dev.json') }}"
    prod:
      type: bigquery
      method: service-account
      project: basedosdados
      dataset: dbt
      location: US
      threads: 2
      keyfile: "{{ env_var('BD_SERVICE_ACCOUNT_DEV', '/credentials-prod/prod.json') }}"
elementary:
  target: dev
  outputs:
    dev:
      type: bigquery
      project: basedosdados-dev
      dataset: elementary
      method: service-account
      keyfile: /home/luizavbo/.basedosdados/credentials/staging.json
      threads: 2
