{{
    config(
        schema="us_stanford_dime",
        alias="contribution",
        materialized="table",
        partition_by={
            "field": "cycle",
            "data_type": "int64",
            "range": {"start": 1980, "end": 2030, "interval": 1},
        },
    )
}}


select
    safe_cast(cycle as int64) cycle,
    safe_cast(transaction_id as string) transaction_id,
    safe_cast(contributor_id as string) contributor_id,
    safe_cast(recipient_id as string) recipient_id,
    safe_cast(efec_transaction_id_original as string) efec_transaction_id_original,
    safe_cast(efec_committee_id_original as string) efec_committee_id_original,
    safe_cast(back_reference_transaction_id as string) back_reference_transaction_id,
    date(safe_cast(date as datetime)) date,
    safe_cast(amount as float64) amount,
    safe_cast(transaction_type as string) transaction_type,
    safe_cast(election_type as string) election_type,
    safe_cast(seat as string) seat,
    safe_cast(contributor_name as string) contributor_name,
    safe_cast(contributor_last_name as string) contributor_last_name,
    safe_cast(contributor_first_name as string) contributor_first_name,
    safe_cast(contributor_middle_name as string) contributor_middle_name,
    safe_cast(contributor_suffix as string) contributor_suffix,
    safe_cast(contributor_title as string) contributor_title,
    safe_cast(contributor_full_first_name as string) contributor_full_first_name,
    safe_cast(contributor_type as string) contributor_type,
    safe_cast(contributor_gender as string) contributor_gender,
    safe_cast(contributor_address as string) contributor_address,
    safe_cast(contributor_city as string) contributor_city,
    safe_cast(contributor_state as string) contributor_state,
    safe_cast(contributor_zipcode as string) contributor_zipcode,
    safe_cast(contributor_district as string) contributor_district,
    safe_cast(census_tract_id as string) census_tract_id,
    safe_cast(latitude as float64) latitude,
    safe_cast(longitude as float64) longitude,
    safe_cast(gis_confidence as float64) gis_confidence,
    safe_cast(contributor_occupation as string) contributor_occupation,
    safe_cast(contributor_employer as string) contributor_employer,
    safe_cast(occupation_standardized as string) occupation_standardized,
    safe_cast(is_corporation as string) is_corporation,
    safe_cast(recipient_name as string) recipient_name,
    safe_cast(recipient_party as string) recipient_party,
    safe_cast(recipient_type as string) recipient_type,
    safe_cast(recipient_state as string) recipient_state,
    safe_cast(contributor_cfscore as float64) contributor_cfscore,
    safe_cast(candidate_cfscore as float64) candidate_cfscore,
    safe_cast(excluded_from_scaling as string) excluded_from_scaling,
    safe_cast(efec_memo as string) efec_memo,
    safe_cast(efec_memo2 as string) efec_memo2,
    safe_cast(efec_organization_original as string) efec_organization_original,
    safe_cast(efec_form_type as string) efec_form_type
from {{ set_datalake_project("us_stanford_dime_staging.contribution") }} as t
