---
version: 2
models:
  - name: example__my_first_dbt_model
    description: A starter dbt model
    columns:
      - description: The primary key for this table
        name: id
        tests: [unique, not_null]
  - name: example__my_second_dbt_model
    description: A starter dbt model
    columns:
      - description: The primary key for this table
        name: id
        tests: [unique, not_null]
