{{
    config(
        schema="us_ed_ipeds",
        alias="om",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 2015, "end": 2030, "interval": 1},
        },
        cluster_by=["unitid"],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(unitid as int64) unitid,
    safe_cast(omchrt as int64) omchrt,
    safe_cast(xomrchrt as string) xomrchrt,
    safe_cast(omrchrt as float64) omrchrt,
    safe_cast(xomexcls as string) xomexcls,
    safe_cast(omexcls as float64) omexcls,
    safe_cast(xomachrt as string) xomachrt,
    safe_cast(omachrt as float64) omachrt,
    safe_cast(xomcert4 as string) xomcert4,
    safe_cast(omcert4 as float64) omcert4,
    safe_cast(xomassc4 as string) xomassc4,
    safe_cast(omassc4 as float64) omassc4,
    safe_cast(xombach4 as string) xombach4,
    safe_cast(ombach4 as float64) ombach4,
    safe_cast(xomawdn4 as string) xomawdn4,
    safe_cast(omawdn4 as float64) omawdn4,
    safe_cast(xomawdp4 as string) xomawdp4,
    safe_cast(omawdp4 as float64) omawdp4,
    safe_cast(xomcert6 as string) xomcert6,
    safe_cast(omcert6 as float64) omcert6,
    safe_cast(xomassc6 as string) xomassc6,
    safe_cast(omassc6 as float64) omassc6,
    safe_cast(xombach6 as string) xombach6,
    safe_cast(ombach6 as float64) ombach6,
    safe_cast(xomawdn6 as string) xomawdn6,
    safe_cast(omawdn6 as int64) omawdn6,
    safe_cast(xomawdp6 as string) xomawdp6,
    safe_cast(omawdp6 as float64) omawdp6,
    safe_cast(xomcert8 as string) xomcert8,
    safe_cast(omcert8 as float64) omcert8,
    safe_cast(xomassc8 as string) xomassc8,
    safe_cast(omassc8 as float64) omassc8,
    safe_cast(xombach8 as string) xombach8,
    safe_cast(ombach8 as float64) ombach8,
    safe_cast(xomawdn8 as string) xomawdn8,
    safe_cast(omawdn8 as int64) omawdn8,
    safe_cast(xomenryi as string) xomenryi,
    safe_cast(omenryi as int64) omenryi,
    safe_cast(xomenrai as string) xomenrai,
    safe_cast(omenrai as int64) omenrai,
    safe_cast(xomenrun as string) xomenrun,
    safe_cast(omenrun as int64) omenrun,
    safe_cast(xomnoawd as string) xomnoawd,
    safe_cast(omnoawd as int64) omnoawd,
    safe_cast(xomawdp8 as string) xomawdp8,
    safe_cast(omawdp8 as float64) omawdp8,
    safe_cast(xomenrtp as string) xomenrtp,
    safe_cast(omenrtp as float64) omenrtp,
    safe_cast(xomenryp as string) xomenryp,
    safe_cast(omenryp as float64) omenryp,
    safe_cast(xomenrap as string) xomenrap,
    safe_cast(omenrap as float64) omenrap,
    safe_cast(xomenrup as string) xomenrup,
    safe_cast(omenrup as float64) omenrup,
    safe_cast(xomrcht6 as string) xomrcht6,
    safe_cast(omrcht6 as float64) omrcht6,
    safe_cast(xomexcl6 as string) xomexcl6,
    safe_cast(omexcl6 as float64) omexcl6,
    safe_cast(xomacht6 as string) xomacht6,
    safe_cast(omacht6 as float64) omacht6,
    safe_cast(xomexcl8 as string) xomexcl8,
    safe_cast(omexcl8 as float64) omexcl8,
    safe_cast(xomacht8 as string) xomacht8,
    safe_cast(omacht8 as float64) omacht8,
    safe_cast(xomrcht8 as string) xomrcht8,
    safe_cast(omrcht8 as float64) omrcht8,
    safe_cast(omflag as float64) omflag
from {{ set_datalake_project("us_ed_ipeds_staging.om") }} as t
