{{
    config(
        schema="us_ed_ipeds",
        alias="c_a",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 2000, "end": 2030, "interval": 1},
        },
        cluster_by=["unitid"],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(unitid as int64) unitid,
    safe_cast(cipcode as float64) cipcode,
    safe_cast(major_number as float64) major_number,
    safe_cast(award_level as int64) award_level,
    safe_cast(xctotalt as string) xctotalt,
    safe_cast(ctotalt as float64) ctotalt,
    safe_cast(xctotalm as string) xctotalm,
    safe_cast(ctotalm as float64) ctotalm,
    safe_cast(xctotalw as string) xctotalw,
    safe_cast(ctotalw as float64) ctotalw,
    safe_cast(xcaiant as string) xcaiant,
    safe_cast(caiant as float64) caiant,
    safe_cast(xcaianm as string) xcaianm,
    safe_cast(caianm as float64) caianm,
    safe_cast(xcaianw as string) xcaianw,
    safe_cast(caianw as float64) caianw,
    safe_cast(xcasiat as string) xcasiat,
    safe_cast(casiat as float64) casiat,
    safe_cast(xcasiam as string) xcasiam,
    safe_cast(casiam as float64) casiam,
    safe_cast(xcasiaw as string) xcasiaw,
    safe_cast(casiaw as float64) casiaw,
    safe_cast(xcbkaat as string) xcbkaat,
    safe_cast(cbkaat as float64) cbkaat,
    safe_cast(xcbkaam as string) xcbkaam,
    safe_cast(cbkaam as float64) cbkaam,
    safe_cast(xcbkaaw as string) xcbkaaw,
    safe_cast(cbkaaw as float64) cbkaaw,
    safe_cast(xchispt as string) xchispt,
    safe_cast(chispt as float64) chispt,
    safe_cast(xchispm as string) xchispm,
    safe_cast(chispm as float64) chispm,
    safe_cast(xchispw as string) xchispw,
    safe_cast(chispw as float64) chispw,
    safe_cast(xcnhpit as string) xcnhpit,
    safe_cast(cnhpit as float64) cnhpit,
    safe_cast(xcnhpim as string) xcnhpim,
    safe_cast(cnhpim as float64) cnhpim,
    safe_cast(xcnhpiw as string) xcnhpiw,
    safe_cast(cnhpiw as float64) cnhpiw,
    safe_cast(xcwhitt as string) xcwhitt,
    safe_cast(cwhitt as float64) cwhitt,
    safe_cast(xcwhitm as string) xcwhitm,
    safe_cast(cwhitm as float64) cwhitm,
    safe_cast(xcwhitw as string) xcwhitw,
    safe_cast(cwhitw as float64) cwhitw,
    safe_cast(xc2mort as string) xc2mort,
    safe_cast(c2mort as float64) c2mort,
    safe_cast(xc2morm as string) xc2morm,
    safe_cast(c2morm as float64) c2morm,
    safe_cast(xc2morw as string) xc2morw,
    safe_cast(c2morw as float64) c2morw,
    safe_cast(xcunknt as string) xcunknt,
    safe_cast(cunknt as float64) cunknt,
    safe_cast(xcunknm as string) xcunknm,
    safe_cast(cunknm as float64) cunknm,
    safe_cast(xcunknw as string) xcunknw,
    safe_cast(cunknw as float64) cunknw,
    safe_cast(xcnralt as string) xcnralt,
    safe_cast(cnralt as float64) cnralt,
    safe_cast(xcnralm as string) xcnralm,
    safe_cast(cnralm as float64) cnralm,
    safe_cast(xcnralw as string) xcnralw,
    safe_cast(cnralw as float64) cnralw,
    safe_cast(cdistedp as float64) cdistedp,
    safe_cast(xcrace03 as string) xcrace03,
    safe_cast(crace03 as float64) crace03,
    safe_cast(xcrace04 as string) xcrace04,
    safe_cast(crace04 as float64) crace04,
    safe_cast(xcrace05 as string) xcrace05,
    safe_cast(crace05 as float64) crace05,
    safe_cast(xcrace06 as string) xcrace06,
    safe_cast(crace06 as float64) crace06,
    safe_cast(xcrace07 as string) xcrace07,
    safe_cast(crace07 as float64) crace07,
    safe_cast(xcrace08 as string) xcrace08,
    safe_cast(crace08 as float64) crace08,
    safe_cast(xcrace09 as string) xcrace09,
    safe_cast(crace09 as float64) crace09,
    safe_cast(xcrace10 as string) xcrace10,
    safe_cast(crace10 as float64) crace10,
    safe_cast(xcrace11 as string) xcrace11,
    safe_cast(crace11 as float64) crace11,
    safe_cast(xcrace12 as string) xcrace12,
    safe_cast(crace12 as float64) crace12,
    safe_cast(xcrace18 as string) xcrace18,
    safe_cast(crace18 as float64) crace18,
    safe_cast(xcrace19 as string) xcrace19,
    safe_cast(crace19 as float64) crace19,
    safe_cast(xcrace20 as string) xcrace20,
    safe_cast(crace20 as float64) crace20,
    safe_cast(xcrace21 as string) xcrace21,
    safe_cast(crace21 as float64) crace21,
    safe_cast(xcrace22 as string) xcrace22,
    safe_cast(crace22 as float64) crace22,
    safe_cast(xdvcait as string) xdvcait,
    safe_cast(dvcait as float64) dvcait,
    safe_cast(xdvcaim as string) xdvcaim,
    safe_cast(dvcaim as float64) dvcaim,
    safe_cast(xdvcaiw as string) xdvcaiw,
    safe_cast(dvcaiw as float64) dvcaiw,
    safe_cast(xdvcapt as string) xdvcapt,
    safe_cast(dvcapt as float64) dvcapt,
    safe_cast(xdvcapm as string) xdvcapm,
    safe_cast(dvcapm as float64) dvcapm,
    safe_cast(xdvcapw as string) xdvcapw,
    safe_cast(dvcapw as float64) dvcapw,
    safe_cast(xdvcbkt as string) xdvcbkt,
    safe_cast(dvcbkt as float64) dvcbkt,
    safe_cast(xdvcbkm as string) xdvcbkm,
    safe_cast(dvcbkm as float64) dvcbkm,
    safe_cast(xdvcbkw as string) xdvcbkw,
    safe_cast(dvcbkw as float64) dvcbkw,
    safe_cast(xdvchst as string) xdvchst,
    safe_cast(dvchst as float64) dvchst,
    safe_cast(xdvchsm as string) xdvchsm,
    safe_cast(dvchsm as float64) dvchsm,
    safe_cast(xdvchsw as string) xdvchsw,
    safe_cast(dvchsw as float64) dvchsw,
    safe_cast(xdvcwht as string) xdvcwht,
    safe_cast(dvcwht as float64) dvcwht,
    safe_cast(xdvcwhm as string) xdvcwhm,
    safe_cast(dvcwhm as float64) dvcwhm,
    safe_cast(xdvcwhw as string) xdvcwhw,
    safe_cast(dvcwhw as float64) dvcwhw,
    safe_cast(xcrace01 as string) xcrace01,
    safe_cast(crace01 as float64) crace01,
    safe_cast(xcrace02 as string) xcrace02,
    safe_cast(crace02 as float64) crace02,
    safe_cast(xcrace13 as string) xcrace13,
    safe_cast(crace13 as float64) crace13,
    safe_cast(xcrace14 as string) xcrace14,
    safe_cast(crace14 as float64) crace14,
    safe_cast(xcrace15 as string) xcrace15,
    safe_cast(crace15 as float64) crace15,
    safe_cast(xcrace16 as string) xcrace16,
    safe_cast(crace16 as float64) crace16,
    safe_cast(xcrace17 as string) xcrace17,
    safe_cast(crace17 as float64) crace17,
    safe_cast(xcrace23 as string) xcrace23,
    safe_cast(crace23 as float64) crace23,
    safe_cast(xcrace24 as string) xcrace24,
    safe_cast(crace24 as float64) crace24
from
    {{ set_datalake_project("us_ed_ipeds_staging.c_a") }} as t
    -- rematerialize us_ed_ipeds (table-approve re-trigger)
