{{
    config(
        schema="us_ed_ipeds",
        alias="effy",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 2002, "end": 2030, "interval": 1},
        },
        cluster_by=["unitid"],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(unitid as int64) unitid,
    safe_cast(effyalev as float64) effyalev,
    safe_cast(effylev as int64) effylev,
    safe_cast(lstudy as int64) lstudy,
    safe_cast(xeytotlt as string) xeytotlt,
    safe_cast(efytotlt as float64) efytotlt,
    safe_cast(xeytotlm as string) xeytotlm,
    safe_cast(efytotlm as float64) efytotlm,
    safe_cast(xeytotlw as string) xeytotlw,
    safe_cast(efytotlw as float64) efytotlw,
    safe_cast(xefyaiat as string) xefyaiat,
    safe_cast(efyaiant as float64) efyaiant,
    safe_cast(xefyaiam as string) xefyaiam,
    safe_cast(efyaianm as float64) efyaianm,
    safe_cast(xefyaiaw as string) xefyaiaw,
    safe_cast(efyaianw as float64) efyaianw,
    safe_cast(xefyasit as string) xefyasit,
    safe_cast(efyasiat as float64) efyasiat,
    safe_cast(xefyasim as string) xefyasim,
    safe_cast(efyasiam as float64) efyasiam,
    safe_cast(xefyasiw as string) xefyasiw,
    safe_cast(efyasiaw as float64) efyasiaw,
    safe_cast(xefybkat as string) xefybkat,
    safe_cast(efybkaat as float64) efybkaat,
    safe_cast(xefybkam as string) xefybkam,
    safe_cast(efybkaam as float64) efybkaam,
    safe_cast(xefybkaw as string) xefybkaw,
    safe_cast(efybkaaw as float64) efybkaaw,
    safe_cast(xefyhist as string) xefyhist,
    safe_cast(efyhispt as float64) efyhispt,
    safe_cast(xefyhism as string) xefyhism,
    safe_cast(efyhispm as float64) efyhispm,
    safe_cast(xefyhisw as string) xefyhisw,
    safe_cast(efyhispw as float64) efyhispw,
    safe_cast(xefynhpt as string) xefynhpt,
    safe_cast(efynhpit as float64) efynhpit,
    safe_cast(xefynhpm as string) xefynhpm,
    safe_cast(efynhpim as float64) efynhpim,
    safe_cast(xefynhpw as string) xefynhpw,
    safe_cast(efynhpiw as float64) efynhpiw,
    safe_cast(xefywhit as string) xefywhit,
    safe_cast(efywhitt as float64) efywhitt,
    safe_cast(xefywhim as string) xefywhim,
    safe_cast(efywhitm as float64) efywhitm,
    safe_cast(xefywhiw as string) xefywhiw,
    safe_cast(efywhitw as float64) efywhitw,
    safe_cast(xefy2mot as string) xefy2mot,
    safe_cast(efy2mort as float64) efy2mort,
    safe_cast(xefy2mom as string) xefy2mom,
    safe_cast(efy2morm as float64) efy2morm,
    safe_cast(xefy2mow as string) xefy2mow,
    safe_cast(efy2morw as float64) efy2morw,
    safe_cast(xeyunknt as string) xeyunknt,
    safe_cast(efyunknt as float64) efyunknt,
    safe_cast(xeyunknm as string) xeyunknm,
    safe_cast(efyunknm as float64) efyunknm,
    safe_cast(xeyunknw as string) xeyunknw,
    safe_cast(efyunknw as float64) efyunknw,
    safe_cast(xeynralt as string) xeynralt,
    safe_cast(efynralt as float64) efynralt,
    safe_cast(xeynralm as string) xeynralm,
    safe_cast(efynralm as float64) efynralm,
    safe_cast(xeynralw as string) xeynralw,
    safe_cast(efynralw as float64) efynralw,
    safe_cast(xefyguun as string) xefyguun,
    safe_cast(efyguun as string) efyguun,
    safe_cast(xefyguan as string) xefyguan,
    safe_cast(efyguan as string) efyguan,
    safe_cast(xefyguto as string) xefyguto,
    safe_cast(efygutot as string) efygutot,
    safe_cast(xefygukn as string) xefygukn,
    safe_cast(efygukn as string) efygukn,
    safe_cast(xfyrac03 as string) xfyrac03,
    safe_cast(fyrace03 as float64) fyrace03,
    safe_cast(xfyrac04 as string) xfyrac04,
    safe_cast(fyrace04 as float64) fyrace04,
    safe_cast(xfyrac05 as string) xfyrac05,
    safe_cast(fyrace05 as float64) fyrace05,
    safe_cast(xfyrac06 as string) xfyrac06,
    safe_cast(fyrace06 as float64) fyrace06,
    safe_cast(xfyrac07 as string) xfyrac07,
    safe_cast(fyrace07 as float64) fyrace07,
    safe_cast(xfyrac08 as string) xfyrac08,
    safe_cast(fyrace08 as float64) fyrace08,
    safe_cast(xfyrac09 as string) xfyrac09,
    safe_cast(fyrace09 as float64) fyrace09,
    safe_cast(xfyrac10 as string) xfyrac10,
    safe_cast(fyrace10 as float64) fyrace10,
    safe_cast(xfyrac11 as string) xfyrac11,
    safe_cast(fyrace11 as float64) fyrace11,
    safe_cast(xfyrac12 as string) xfyrac12,
    safe_cast(fyrace12 as float64) fyrace12,
    safe_cast(xfyrac18 as string) xfyrac18,
    safe_cast(fyrace18 as float64) fyrace18,
    safe_cast(xfyrac19 as string) xfyrac19,
    safe_cast(fyrace19 as float64) fyrace19,
    safe_cast(xfyrac20 as string) xfyrac20,
    safe_cast(fyrace20 as float64) fyrace20,
    safe_cast(xfyrac21 as string) xfyrac21,
    safe_cast(fyrace21 as float64) fyrace21,
    safe_cast(xfyrac22 as string) xfyrac22,
    safe_cast(fyrace22 as float64) fyrace22,
    safe_cast(xdveyait as string) xdveyait,
    safe_cast(dveyait as float64) dveyait,
    safe_cast(xdveyaim as string) xdveyaim,
    safe_cast(dveyaim as float64) dveyaim,
    safe_cast(xdveyaiw as string) xdveyaiw,
    safe_cast(dveyaiw as float64) dveyaiw,
    safe_cast(xdveyapt as string) xdveyapt,
    safe_cast(dveyapt as float64) dveyapt,
    safe_cast(xdveyapm as string) xdveyapm,
    safe_cast(dveyapm as float64) dveyapm,
    safe_cast(xdveyapw as string) xdveyapw,
    safe_cast(dveyapw as float64) dveyapw,
    safe_cast(xdveybkt as string) xdveybkt,
    safe_cast(dveybkt as float64) dveybkt,
    safe_cast(xdveybkm as string) xdveybkm,
    safe_cast(dveybkm as float64) dveybkm,
    safe_cast(xdveybkw as string) xdveybkw,
    safe_cast(dveybkw as float64) dveybkw,
    safe_cast(xdveyhst as string) xdveyhst,
    safe_cast(dveyhst as float64) dveyhst,
    safe_cast(xdveyhsm as string) xdveyhsm,
    safe_cast(dveyhsm as float64) dveyhsm,
    safe_cast(xdveyhsw as string) xdveyhsw,
    safe_cast(dveyhsw as float64) dveyhsw,
    safe_cast(xdveywht as string) xdveywht,
    safe_cast(dveywht as float64) dveywht,
    safe_cast(xdveywhm as string) xdveywhm,
    safe_cast(dveywhm as float64) dveywhm,
    safe_cast(xdveywhw as string) xdveywhw,
    safe_cast(dveywhw as float64) dveywhw,
    safe_cast(xfyrac01 as string) xfyrac01,
    safe_cast(fyrace01 as float64) fyrace01,
    safe_cast(xfyrac02 as string) xfyrac02,
    safe_cast(fyrace02 as float64) fyrace02,
    safe_cast(xfyrac13 as string) xfyrac13,
    safe_cast(fyrace13 as float64) fyrace13,
    safe_cast(xfyrac14 as string) xfyrac14,
    safe_cast(fyrace14 as float64) fyrace14,
    safe_cast(xfyrac15 as string) xfyrac15,
    safe_cast(fyrace15 as float64) fyrace15,
    safe_cast(xfyrac16 as string) xfyrac16,
    safe_cast(fyrace16 as float64) fyrace16,
    safe_cast(xfyrac17 as string) xfyrac17,
    safe_cast(fyrace17 as float64) fyrace17,
    safe_cast(xfyrac23 as string) xfyrac23,
    safe_cast(fyrace23 as float64) fyrace23,
    safe_cast(xfyrac24 as string) xfyrac24,
    safe_cast(fyrace24 as float64) fyrace24
from
    {{ set_datalake_project("us_ed_ipeds_staging.effy") }} as t
    -- rematerialize us_ed_ipeds (table-approve re-trigger)
