{{
    config(
        schema="us_ed_ipeds",
        alias="ef_d",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 2000, "end": 2030, "interval": 1},
        },
        cluster_by=["unitid"],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(unitid as int64) unitid,
    safe_cast(xgrcohrt as string) xgrcohrt,
    safe_cast(grcohrt as float64) grcohrt,
    safe_cast(xugenter as string) xugenter,
    safe_cast(ugentern as float64) ugentern,
    safe_cast(xpgrcohr as string) xpgrcohr,
    safe_cast(pgrcohrt as float64) pgrcohrt,
    safe_cast(xrrftct as string) xrrftct,
    safe_cast(rrftct as float64) rrftct,
    safe_cast(xrrftex as string) xrrftex,
    safe_cast(rrftex as float64) rrftex,
    safe_cast(xrrftin as string) xrrftin,
    safe_cast(rrftin as float64) rrftin,
    safe_cast(xrrftcta as string) xrrftcta,
    safe_cast(rrftcta as float64) rrftcta,
    safe_cast(xret_nmf as string) xret_nmf,
    safe_cast(ret_nmf as float64) ret_nmf,
    safe_cast(xret_pcf as string) xret_pcf,
    safe_cast(ret_pcf as float64) ret_pcf,
    safe_cast(xrrptct as string) xrrptct,
    safe_cast(rrptct as float64) rrptct,
    safe_cast(xrrptex as string) xrrptex,
    safe_cast(rrptex as float64) rrptex,
    safe_cast(xrrptin as string) xrrptin,
    safe_cast(rrptin as float64) rrptin,
    safe_cast(xrrptcta as string) xrrptcta,
    safe_cast(rrptcta as float64) rrptcta,
    safe_cast(xret_nmp as string) xret_nmp,
    safe_cast(ret_nmp as float64) ret_nmp,
    safe_cast(xret_pcp as string) xret_pcp,
    safe_cast(ret_pcp as float64) ret_pcp,
    safe_cast(xstufacr as string) xstufacr,
    safe_cast(stufacr as float64) stufacr,
    safe_cast(fyrpyear as float64) fyrpyear,
    safe_cast(xtostucu as string) xtostucu,
    safe_cast(tostucu as float64) tostucu,
    safe_cast(xtostucg as string) xtostucg,
    safe_cast(tostucg as float64) tostucg,
    safe_cast(xtostucp as string) xtostucp,
    safe_cast(tostucp as float64) tostucp,
    safe_cast(xcdactua as string) xcdactua,
    safe_cast(cdactua as float64) cdactua,
    safe_cast(xcnactua as string) xcnactua,
    safe_cast(cnactua as float64) cnactua,
    safe_cast(xcdactga as string) xcdactga,
    safe_cast(cdactga as float64) cdactga
from
    {{ set_datalake_project("us_ed_ipeds_staging.ef_d") }} as t
    -- rematerialize us_ed_ipeds (table-approve re-trigger)
