{{
    config(
        schema="us_ed_ipeds",
        alias="ic_py",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 2000, "end": 2030, "interval": 1},
        },
        cluster_by=["unitid"],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(unitid as int64) unitid,
    safe_cast(prgmofr as int64) prgmofr,
    safe_cast(cipcode1 as float64) cipcode1,
    safe_cast(xciptui1 as string) xciptui1,
    safe_cast(ciptuit1 as string) ciptuit1,
    safe_cast(xcipsup1 as string) xcipsup1,
    safe_cast(cipsupp1 as string) cipsupp1,
    safe_cast(xciplgt1 as string) xciplgt1,
    safe_cast(ciplgth1 as float64) ciplgth1,
    safe_cast(prgmsr1 as float64) prgmsr1,
    safe_cast(xmthcmp1 as string) xmthcmp1,
    safe_cast(mthcmp1 as float64) mthcmp1,
    safe_cast(xwkcmp1 as string) xwkcmp1,
    safe_cast(wkcmp1 as float64) wkcmp1,
    safe_cast(xlnayhr1 as string) xlnayhr1,
    safe_cast(lnayhr1 as float64) lnayhr1,
    safe_cast(xlnaywk1 as string) xlnaywk1,
    safe_cast(lnaywk1 as float64) lnaywk1,
    safe_cast(xchg1py0 as string) xchg1py0,
    safe_cast(chg1py0 as float64) chg1py0,
    safe_cast(xchg1py1 as string) xchg1py1,
    safe_cast(chg1py1 as float64) chg1py1,
    safe_cast(xchg1py2 as string) xchg1py2,
    safe_cast(chg1py2 as float64) chg1py2,
    safe_cast(xchg1py3 as string) xchg1py3,
    safe_cast(chg1py3 as float64) chg1py3,
    safe_cast(xchg4py0 as string) xchg4py0,
    safe_cast(chg4py0 as float64) chg4py0,
    safe_cast(xchg4py1 as string) xchg4py1,
    safe_cast(chg4py1 as float64) chg4py1,
    safe_cast(xchg4py2 as string) xchg4py2,
    safe_cast(chg4py2 as float64) chg4py2,
    safe_cast(xchg4py3 as string) xchg4py3,
    safe_cast(chg4py3 as float64) chg4py3,
    safe_cast(xchg5py0 as string) xchg5py0,
    safe_cast(chg5py0 as string) chg5py0,
    safe_cast(xchg5py1 as string) xchg5py1,
    safe_cast(chg5py1 as string) chg5py1,
    safe_cast(xchg5py2 as string) xchg5py2,
    safe_cast(chg5py2 as string) chg5py2,
    safe_cast(xchg5py3 as string) xchg5py3,
    safe_cast(chg5py3 as string) chg5py3,
    safe_cast(xchg6py0 as string) xchg6py0,
    safe_cast(chg6py0 as string) chg6py0,
    safe_cast(xchg6py1 as string) xchg6py1,
    safe_cast(chg6py1 as string) chg6py1,
    safe_cast(xchg6py2 as string) xchg6py2,
    safe_cast(chg6py2 as string) chg6py2,
    safe_cast(xchg6py3 as string) xchg6py3,
    safe_cast(chg6py3 as string) chg6py3,
    safe_cast(xchg7py0 as string) xchg7py0,
    safe_cast(chg7py0 as float64) chg7py0,
    safe_cast(xchg7py1 as string) xchg7py1,
    safe_cast(chg7py1 as float64) chg7py1,
    safe_cast(xchg7py2 as string) xchg7py2,
    safe_cast(chg7py2 as float64) chg7py2,
    safe_cast(xchg7py3 as string) xchg7py3,
    safe_cast(chg7py3 as float64) chg7py3,
    safe_cast(xchg8py0 as string) xchg8py0,
    safe_cast(chg8py0 as float64) chg8py0,
    safe_cast(xchg8py1 as string) xchg8py1,
    safe_cast(chg8py1 as float64) chg8py1,
    safe_cast(xchg8py2 as string) xchg8py2,
    safe_cast(chg8py2 as float64) chg8py2,
    safe_cast(xchg8py3 as string) xchg8py3,
    safe_cast(chg8py3 as float64) chg8py3,
    safe_cast(xchg9py0 as string) xchg9py0,
    safe_cast(chg9py0 as float64) chg9py0,
    safe_cast(xchg9py1 as string) xchg9py1,
    safe_cast(chg9py1 as float64) chg9py1,
    safe_cast(xchg9py2 as string) xchg9py2,
    safe_cast(chg9py2 as float64) chg9py2,
    safe_cast(xchg9py3 as string) xchg9py3,
    safe_cast(chg9py3 as float64) chg9py3,
    safe_cast(cipcode2 as float64) cipcode2,
    safe_cast(xciptui2 as string) xciptui2,
    safe_cast(ciptuit2 as float64) ciptuit2,
    safe_cast(xcipsup2 as string) xcipsup2,
    safe_cast(cipsupp2 as float64) cipsupp2,
    safe_cast(xciplgt2 as string) xciplgt2,
    safe_cast(ciplgth2 as float64) ciplgth2,
    safe_cast(prgmsr2 as float64) prgmsr2,
    safe_cast(xmthcmp2 as string) xmthcmp2,
    safe_cast(mthcmp2 as float64) mthcmp2,
    safe_cast(cipcode3 as float64) cipcode3,
    safe_cast(xciptui3 as string) xciptui3,
    safe_cast(ciptuit3 as float64) ciptuit3,
    safe_cast(xcipsup3 as string) xcipsup3,
    safe_cast(cipsupp3 as float64) cipsupp3,
    safe_cast(xciplgt3 as string) xciplgt3,
    safe_cast(ciplgth3 as float64) ciplgth3,
    safe_cast(prgmsr3 as float64) prgmsr3,
    safe_cast(xmthcmp3 as string) xmthcmp3,
    safe_cast(mthcmp3 as float64) mthcmp3,
    safe_cast(cipcode4 as float64) cipcode4,
    safe_cast(xciptui4 as string) xciptui4,
    safe_cast(ciptuit4 as string) ciptuit4,
    safe_cast(xcipsup4 as string) xcipsup4,
    safe_cast(cipsupp4 as string) cipsupp4,
    safe_cast(xciplgt4 as string) xciplgt4,
    safe_cast(ciplgth4 as string) ciplgth4,
    safe_cast(prgmsr4 as float64) prgmsr4,
    safe_cast(xmthcmp4 as string) xmthcmp4,
    safe_cast(mthcmp4 as string) mthcmp4,
    safe_cast(cipcode5 as float64) cipcode5,
    safe_cast(xciptui5 as string) xciptui5,
    safe_cast(ciptuit5 as string) ciptuit5,
    safe_cast(xcipsup5 as string) xcipsup5,
    safe_cast(cipsupp5 as string) cipsupp5,
    safe_cast(xciplgt5 as string) xciplgt5,
    safe_cast(ciplgth5 as string) ciplgth5,
    safe_cast(prgmsr5 as float64) prgmsr5,
    safe_cast(xmthcmp5 as string) xmthcmp5,
    safe_cast(mthcmp5 as string) mthcmp5,
    safe_cast(cipcode6 as float64) cipcode6,
    safe_cast(xciptui6 as string) xciptui6,
    safe_cast(ciptuit6 as string) ciptuit6,
    safe_cast(xcipsup6 as string) xcipsup6,
    safe_cast(cipsupp6 as string) cipsupp6,
    safe_cast(xciplgt6 as string) xciplgt6,
    safe_cast(ciplgth6 as string) ciplgth6,
    safe_cast(prgmsr6 as float64) prgmsr6,
    safe_cast(xmthcmp6 as string) xmthcmp6,
    safe_cast(mthcmp6 as string) mthcmp6,
    safe_cast(xcmp1py0 as string) xcmp1py0,
    safe_cast(cmp1py0 as string) cmp1py0,
    safe_cast(xcmp1py1 as string) xcmp1py1,
    safe_cast(cmp1py1 as string) cmp1py1,
    safe_cast(xcmp1py2 as string) xcmp1py2,
    safe_cast(cmp1py2 as string) cmp1py2,
    safe_cast(xcmp1py3 as string) xcmp1py3,
    safe_cast(cmp1py3 as string) cmp1py3,
    safe_cast(pg300 as float64) pg300
from
    {{ set_datalake_project("us_ed_ipeds_staging.ic_py") }} as t
    -- rematerialize us_ed_ipeds (table-approve re-trigger)
