{{
    config(
        schema="us_ed_ipeds",
        alias="adm",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 2014, "end": 2030, "interval": 1},
        },
        cluster_by=["unitid"],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(unitid as int64) unitid,
    safe_cast(admcon1 as int64) admcon1,
    safe_cast(admcon2 as int64) admcon2,
    safe_cast(admcon3 as int64) admcon3,
    safe_cast(admcon4 as int64) admcon4,
    safe_cast(admcon5 as int64) admcon5,
    safe_cast(admcon6 as int64) admcon6,
    safe_cast(admcon7 as int64) admcon7,
    safe_cast(admcon8 as int64) admcon8,
    safe_cast(admcon9 as int64) admcon9,
    safe_cast(admcon10 as float64) admcon10,
    safe_cast(admcon11 as float64) admcon11,
    safe_cast(admcon12 as float64) admcon12,
    safe_cast(xapplcn as string) xapplcn,
    safe_cast(applicants_total as int64) applicants_total,
    safe_cast(xapplcnm as string) xapplcnm,
    safe_cast(applicants_men as float64) applicants_men,
    safe_cast(xapplcnw as string) xapplcnw,
    safe_cast(applicants_women as float64) applicants_women,
    safe_cast(xapplcnan as string) xapplcnan,
    safe_cast(applcnan as float64) applcnan,
    safe_cast(xapplcnun as string) xapplcnun,
    safe_cast(applcnun as float64) applcnun,
    safe_cast(xadmssn as string) xadmssn,
    safe_cast(admissions_total as float64) admissions_total,
    safe_cast(xadmssnm as string) xadmssnm,
    safe_cast(admissions_men as float64) admissions_men,
    safe_cast(xadmssnw as string) xadmssnw,
    safe_cast(admissions_women as float64) admissions_women,
    safe_cast(xadmssnan as string) xadmssnan,
    safe_cast(admssnan as float64) admssnan,
    safe_cast(xadmssnun as string) xadmssnun,
    safe_cast(admssnun as float64) admssnun,
    safe_cast(xenrlt as string) xenrlt,
    safe_cast(enrolled_total as float64) enrolled_total,
    safe_cast(xenrlm as string) xenrlm,
    safe_cast(enrolled_men as float64) enrolled_men,
    safe_cast(xenrlw as string) xenrlw,
    safe_cast(enrolled_women as float64) enrolled_women,
    safe_cast(xenrlan as string) xenrlan,
    safe_cast(enrlan as float64) enrlan,
    safe_cast(xenrlun as string) xenrlun,
    safe_cast(enrlun as float64) enrlun,
    safe_cast(xenrlft as string) xenrlft,
    safe_cast(enrlft as float64) enrlft,
    safe_cast(xenrlftm as string) xenrlftm,
    safe_cast(enrlftm as float64) enrlftm,
    safe_cast(xenrlftw as string) xenrlftw,
    safe_cast(enrlftw as float64) enrlftw,
    safe_cast(xenrlftan as string) xenrlftan,
    safe_cast(enrlftan as float64) enrlftan,
    safe_cast(xenrlftun as string) xenrlftun,
    safe_cast(enrlftun as float64) enrlftun,
    safe_cast(xenrlpt as string) xenrlpt,
    safe_cast(enrlpt as float64) enrlpt,
    safe_cast(xenrlptm as string) xenrlptm,
    safe_cast(enrlptm as float64) enrlptm,
    safe_cast(xenrlptw as string) xenrlptw,
    safe_cast(enrlptw as float64) enrlptw,
    safe_cast(xenrlptan as string) xenrlptan,
    safe_cast(enrlptan as float64) enrlptan,
    safe_cast(xenrlptun as string) xenrlptun,
    safe_cast(enrlptun as float64) enrlptun,
    safe_cast(xsatnum as string) xsatnum,
    safe_cast(satnum as float64) satnum,
    safe_cast(xsatpct as string) xsatpct,
    safe_cast(satpct as float64) satpct,
    safe_cast(xactnum as string) xactnum,
    safe_cast(actnum as float64) actnum,
    safe_cast(xactpct as string) xactpct,
    safe_cast(actpct as float64) actpct,
    safe_cast(xsatvr25 as string) xsatvr25,
    safe_cast(sat_verbal_25th as float64) sat_verbal_25th,
    safe_cast(xsatvr50 as string) xsatvr50,
    safe_cast(satvr50 as float64) satvr50,
    safe_cast(xsatvr75 as string) xsatvr75,
    safe_cast(sat_verbal_75th as float64) sat_verbal_75th,
    safe_cast(xsatmt25 as string) xsatmt25,
    safe_cast(sat_math_25th as float64) sat_math_25th,
    safe_cast(xsatmt50 as string) xsatmt50,
    safe_cast(satmt50 as float64) satmt50,
    safe_cast(xsatmt75 as string) xsatmt75,
    safe_cast(sat_math_75th as float64) sat_math_75th,
    safe_cast(xactcm25 as string) xactcm25,
    safe_cast(act_composite_25th as float64) act_composite_25th,
    safe_cast(xactcm50 as string) xactcm50,
    safe_cast(actcm50 as float64) actcm50,
    safe_cast(xactcm75 as string) xactcm75,
    safe_cast(act_composite_75th as float64) act_composite_75th,
    safe_cast(xacten25 as string) xacten25,
    safe_cast(act_english_25th as float64) act_english_25th,
    safe_cast(xacten50 as string) xacten50,
    safe_cast(acten50 as float64) acten50,
    safe_cast(xacten75 as string) xacten75,
    safe_cast(act_english_75th as float64) act_english_75th,
    safe_cast(xactmt25 as string) xactmt25,
    safe_cast(act_math_25th as float64) act_math_25th,
    safe_cast(xactmt50 as string) xactmt50,
    safe_cast(actmt50 as float64) actmt50,
    safe_cast(xactmt75 as string) xactmt75,
    safe_cast(act_math_75th as float64) act_math_75th,
    safe_cast(xsatwr25 as string) xsatwr25,
    safe_cast(sat_writing_25th as float64) sat_writing_25th,
    safe_cast(xsatwr75 as string) xsatwr75,
    safe_cast(sat_writing_75th as float64) sat_writing_75th,
    safe_cast(xactwr25 as string) xactwr25,
    safe_cast(act_writing_25th as float64) act_writing_25th,
    safe_cast(xactwr75 as string) xactwr75,
    safe_cast(act_writing_75th as float64) act_writing_75th
from {{ set_datalake_project("us_ed_ipeds_staging.adm") }} as t
