{{
    config(
        schema="us_ed_ipeds",
        alias="al",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 2014, "end": 2030, "interval": 1},
        },
        cluster_by=["unitid"],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(unitid as int64) unitid,
    safe_cast(lexp100k as float64) lexp100k,
    safe_cast(lcolelyn as int64) lcolelyn,
    safe_cast(xlpbooks as string) xlpbooks,
    safe_cast(lpbooks as float64) lpbooks,
    safe_cast(xlebooks as string) xlebooks,
    safe_cast(lebooks as int64) lebooks,
    safe_cast(xledatab as string) xledatab,
    safe_cast(ledatab as int64) ledatab,
    safe_cast(xlpmedia as string) xlpmedia,
    safe_cast(lpmedia as float64) lpmedia,
    safe_cast(xlemedia as string) xlemedia,
    safe_cast(lemedia as int64) lemedia,
    safe_cast(xlpseria as string) xlpseria,
    safe_cast(lpseria as float64) lpseria,
    safe_cast(xleseria as string) xleseria,
    safe_cast(leseria as float64) leseria,
    safe_cast(xlpcollc as string) xlpcollc,
    safe_cast(lpcllct as float64) lpcllct,
    safe_cast(xlecollc as string) xlecollc,
    safe_cast(lecllct as int64) lecllct,
    safe_cast(xltcllct as string) xltcllct,
    safe_cast(ltcllct as float64) ltcllct,
    safe_cast(xlpcrclt as string) xlpcrclt,
    safe_cast(lpcrclt as float64) lpcrclt,
    safe_cast(xlecrclt as string) xlecrclt,
    safe_cast(lecrclt as int64) lecrclt,
    safe_cast(xltcrclt as string) xltcrclt,
    safe_cast(ltcrclt as float64) ltcrclt,
    safe_cast(lilldyn as float64) lilldyn,
    safe_cast(xlilldpr as string) xlilldpr,
    safe_cast(lilldpr as float64) lilldpr,
    safe_cast(xlilldrc as string) xlilldrc,
    safe_cast(lilldrc as float64) lilldrc,
    safe_cast(lilsyn as float64) lilsyn,
    safe_cast(xlstotal as string) xlstotal,
    safe_cast(lstotal as float64) lstotal,
    safe_cast(xlslibrn as string) xlslibrn,
    safe_cast(lslibrn as float64) lslibrn,
    safe_cast(xlsoprof as string) xlsoprof,
    safe_cast(lsoprof as float64) lsoprof,
    safe_cast(xlsopaid as string) xlsopaid,
    safe_cast(lsopaid as float64) lsopaid,
    safe_cast(xlsstast as string) xlsstast,
    safe_cast(lsstast as float64) lsstast,
    safe_cast(xlbranch as string) xlbranch,
    safe_cast(lbranch as float64) lbranch,
    safe_cast(xsalwag as string) xsalwag,
    safe_cast(lsalwag as float64) lsalwag,
    safe_cast(lfrngbyn as int64) lfrngbyn,
    safe_cast(xlfrngbn as string) xlfrngbn,
    safe_cast(lfrngbn as float64) lfrngbn,
    safe_cast(xlexmsbb as string) xlexmsbb,
    safe_cast(lexmsbb as float64) lexmsbb,
    safe_cast(xlexmscs as string) xlexmscs,
    safe_cast(lexmscs as float64) lexmscs,
    safe_cast(xlexmsot as string) xlexmsot,
    safe_cast(lexmsot as float64) lexmsot,
    safe_cast(xlexmstl as string) xlexmstl,
    safe_cast(lexmstl as float64) lexmstl,
    safe_cast(xlexomps as string) xlexomps,
    safe_cast(lexomps as float64) lexomps,
    safe_cast(xlexomot as string) xlexomot,
    safe_cast(lexomot as float64) lexomot,
    safe_cast(xlexomtl as string) xlexomtl,
    safe_cast(lexomtl as float64) lexomtl,
    safe_cast(xlexptot as string) xlexptot,
    safe_cast(lexptot as float64) lexptot,
    safe_cast(lswmsom as float64) lswmsom,
    safe_cast(lsuppvrs as float64) lsuppvrs
from {{ set_datalake_project("us_ed_ipeds_staging.al") }} as t
