{{
    config(
        schema="us_ed_ipeds",
        alias="sal_is",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 2012, "end": 2030, "interval": 1},
        },
        cluster_by=["unitid"],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(unitid as int64) unitid,
    safe_cast(arank as int64) arank,
    safe_cast(xsainstt as string) xsainstt,
    safe_cast(sainstt as float64) sainstt,
    safe_cast(xsainstm as string) xsainstm,
    safe_cast(sainstm as float64) sainstm,
    safe_cast(xsainstw as string) xsainstw,
    safe_cast(sainstw as float64) sainstw,
    safe_cast(xsa_9mct as string) xsa_9mct,
    safe_cast(sa_9mct as float64) sa_9mct,
    safe_cast(xsa_9mcm as string) xsa_9mcm,
    safe_cast(sa_9mcm as float64) sa_9mcm,
    safe_cast(xsa_9mcw as string) xsa_9mcw,
    safe_cast(sa_9mcw as float64) sa_9mcw,
    safe_cast(xsatotlt as string) xsatotlt,
    safe_cast(satotlt as int64) satotlt,
    safe_cast(xsatotlm as string) xsatotlm,
    safe_cast(satotlm as int64) satotlm,
    safe_cast(xsatotlw as string) xsatotlw,
    safe_cast(satotlw as int64) satotlw,
    safe_cast(xsa09mct as string) xsa09mct,
    safe_cast(sa09mct as float64) sa09mct,
    safe_cast(xsa09mcm as string) xsa09mcm,
    safe_cast(sa09mcm as float64) sa09mcm,
    safe_cast(xsa09mcw as string) xsa09mcw,
    safe_cast(sa09mcw as float64) sa09mcw,
    safe_cast(xsa10mct as string) xsa10mct,
    safe_cast(sa10mct as float64) sa10mct,
    safe_cast(xsa10mcm as string) xsa10mcm,
    safe_cast(sa10mcm as float64) sa10mcm,
    safe_cast(xsa10mcw as string) xsa10mcw,
    safe_cast(sa10mcw as float64) sa10mcw,
    safe_cast(xsa11mct as string) xsa11mct,
    safe_cast(sa11mct as float64) sa11mct,
    safe_cast(xsa11mcm as string) xsa11mcm,
    safe_cast(sa11mcm as float64) sa11mcm,
    safe_cast(xsa11mcw as string) xsa11mcw,
    safe_cast(sa11mcw as float64) sa11mcw,
    safe_cast(xsa12mct as string) xsa12mct,
    safe_cast(sa12mct as float64) sa12mct,
    safe_cast(xsa12mcm as string) xsa12mcm,
    safe_cast(sa12mcm as float64) sa12mcm,
    safe_cast(xsa12mcw as string) xsa12mcw,
    safe_cast(sa12mcw as float64) sa12mcw,
    safe_cast(xsaoutlt as string) xsaoutlt,
    safe_cast(saoutlt as int64) saoutlt,
    safe_cast(xsaoutlm as string) xsaoutlm,
    safe_cast(saoutlm as int64) saoutlm,
    safe_cast(xsaoutlw as string) xsaoutlw,
    safe_cast(saoutlw as int64) saoutlw,
    safe_cast(xsa09mot as string) xsa09mot,
    safe_cast(sa09mot as float64) sa09mot,
    safe_cast(xsa09mom as string) xsa09mom,
    safe_cast(sa09mom as float64) sa09mom,
    safe_cast(xsa09mow as string) xsa09mow,
    safe_cast(sa09mow as float64) sa09mow,
    safe_cast(xsa10mot as string) xsa10mot,
    safe_cast(sa10mot as float64) sa10mot,
    safe_cast(xsa10mom as string) xsa10mom,
    safe_cast(sa10mom as float64) sa10mom,
    safe_cast(xsa10mow as string) xsa10mow,
    safe_cast(sa10mow as float64) sa10mow,
    safe_cast(xsa11mot as string) xsa11mot,
    safe_cast(sa11mot as float64) sa11mot,
    safe_cast(xsa11mom as string) xsa11mom,
    safe_cast(sa11mom as float64) sa11mom,
    safe_cast(xsa11mow as string) xsa11mow,
    safe_cast(sa11mow as float64) sa11mow,
    safe_cast(xsa12mot as string) xsa12mot,
    safe_cast(sa12mot as float64) sa12mot,
    safe_cast(xsa12mom as string) xsa12mom,
    safe_cast(sa12mom as float64) sa12mom,
    safe_cast(xsa12mow as string) xsa12mow,
    safe_cast(sa12mow as float64) sa12mow,
    safe_cast(xsaeq9ot as string) xsaeq9ot,
    safe_cast(saeq9ot as float64) saeq9ot,
    safe_cast(xsaeq9om as string) xsaeq9om,
    safe_cast(saeq9om as float64) saeq9om,
    safe_cast(xsaeq9ow as string) xsaeq9ow,
    safe_cast(saeq9ow as float64) saeq9ow,
    safe_cast(xsaeq9at as string) xsaeq9at,
    safe_cast(saeq9at as float64) saeq9at,
    safe_cast(xsaeq9am as string) xsaeq9am,
    safe_cast(saeq9am as float64) saeq9am,
    safe_cast(xsaeq9aw as string) xsaeq9aw,
    safe_cast(saeq9aw as float64) saeq9aw,
    safe_cast(xsa09mat as string) xsa09mat,
    safe_cast(sa09mat as float64) sa09mat,
    safe_cast(xsa09mam as string) xsa09mam,
    safe_cast(sa09mam as float64) sa09mam,
    safe_cast(xsa09maw as string) xsa09maw,
    safe_cast(sa09maw as float64) sa09maw,
    safe_cast(xsa10mat as string) xsa10mat,
    safe_cast(sa10mat as float64) sa10mat,
    safe_cast(xsa10mam as string) xsa10mam,
    safe_cast(sa10mam as float64) sa10mam,
    safe_cast(xsa10maw as string) xsa10maw,
    safe_cast(sa10maw as float64) sa10maw,
    safe_cast(xsa11mat as string) xsa11mat,
    safe_cast(sa11mat as float64) sa11mat,
    safe_cast(xsa11mam as string) xsa11mam,
    safe_cast(sa11mam as float64) sa11mam,
    safe_cast(xsa11maw as string) xsa11maw,
    safe_cast(sa11maw as float64) sa11maw,
    safe_cast(xsa12mat as string) xsa12mat,
    safe_cast(sa12mat as float64) sa12mat,
    safe_cast(xsa12mam as string) xsa12mam,
    safe_cast(sa12mam as float64) sa12mam,
    safe_cast(xsa12maw as string) xsa12maw,
    safe_cast(sa12maw as float64) sa12maw,
    safe_cast(xsamntht as string) xsamntht,
    safe_cast(samntht as float64) samntht,
    safe_cast(xsamnthm as string) xsamnthm,
    safe_cast(samnthm as float64) samnthm,
    safe_cast(xsamnthw as string) xsamnthw,
    safe_cast(samnthw as float64) samnthw,
    safe_cast(xsaavmnt as string) xsaavmnt,
    safe_cast(saavmnt as float64) saavmnt,
    safe_cast(xsaavmnm as string) xsaavmnm,
    safe_cast(saavmnm as float64) saavmnm,
    safe_cast(xsaavmnw as string) xsaavmnw,
    safe_cast(saavmnw as float64) saavmnw
from {{ set_datalake_project("us_ed_ipeds_staging.sal_is") }} as t
