{{
    config(
        schema="us_ed_ipeds",
        alias="ef_a",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 2000, "end": 2030, "interval": 1},
        },
        cluster_by=["unitid"],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(unitid as int64) unitid,
    safe_cast(efalevel as float64) efalevel,
    safe_cast(line as int64) line,
    safe_cast(section as int64) section,
    safe_cast(lstudy as int64) lstudy,
    safe_cast(xeftotlt as string) xeftotlt,
    safe_cast(eftotlt as float64) eftotlt,
    safe_cast(xeftotlm as string) xeftotlm,
    safe_cast(eftotlm as float64) eftotlm,
    safe_cast(xeftotlw as string) xeftotlw,
    safe_cast(eftotlw as float64) eftotlw,
    safe_cast(xefaiant as string) xefaiant,
    safe_cast(efaiant as float64) efaiant,
    safe_cast(xefaianm as string) xefaianm,
    safe_cast(efaianm as float64) efaianm,
    safe_cast(xefaianw as string) xefaianw,
    safe_cast(efaianw as float64) efaianw,
    safe_cast(xefasiat as string) xefasiat,
    safe_cast(efasiat as float64) efasiat,
    safe_cast(xefasiam as string) xefasiam,
    safe_cast(efasiam as float64) efasiam,
    safe_cast(xefasiaw as string) xefasiaw,
    safe_cast(efasiaw as float64) efasiaw,
    safe_cast(xefbkaat as string) xefbkaat,
    safe_cast(efbkaat as float64) efbkaat,
    safe_cast(xefbkaam as string) xefbkaam,
    safe_cast(efbkaam as float64) efbkaam,
    safe_cast(xefbkaaw as string) xefbkaaw,
    safe_cast(efbkaaw as float64) efbkaaw,
    safe_cast(xefhispt as string) xefhispt,
    safe_cast(efhispt as float64) efhispt,
    safe_cast(xefhispm as string) xefhispm,
    safe_cast(efhispm as float64) efhispm,
    safe_cast(xefhispw as string) xefhispw,
    safe_cast(efhispw as float64) efhispw,
    safe_cast(xefnhpit as string) xefnhpit,
    safe_cast(efnhpit as float64) efnhpit,
    safe_cast(xefnhpim as string) xefnhpim,
    safe_cast(efnhpim as float64) efnhpim,
    safe_cast(xefnhpiw as string) xefnhpiw,
    safe_cast(efnhpiw as float64) efnhpiw,
    safe_cast(xefwhitt as string) xefwhitt,
    safe_cast(efwhitt as float64) efwhitt,
    safe_cast(xefwhitm as string) xefwhitm,
    safe_cast(efwhitm as float64) efwhitm,
    safe_cast(xefwhitw as string) xefwhitw,
    safe_cast(efwhitw as float64) efwhitw,
    safe_cast(xef2mort as string) xef2mort,
    safe_cast(ef2mort as float64) ef2mort,
    safe_cast(xef2morm as string) xef2morm,
    safe_cast(ef2morm as float64) ef2morm,
    safe_cast(xef2morw as string) xef2morw,
    safe_cast(ef2morw as float64) ef2morw,
    safe_cast(xefunknt as string) xefunknt,
    safe_cast(efunknt as float64) efunknt,
    safe_cast(xefunknm as string) xefunknm,
    safe_cast(efunknm as float64) efunknm,
    safe_cast(xefunknw as string) xefunknw,
    safe_cast(efunknw as float64) efunknw,
    safe_cast(xefnralt as string) xefnralt,
    safe_cast(efnralt as float64) efnralt,
    safe_cast(xefnralm as string) xefnralm,
    safe_cast(efnralm as float64) efnralm,
    safe_cast(xefnralw as string) xefnralw,
    safe_cast(efnralw as float64) efnralw,
    safe_cast(xefgndrun as string) xefgndrun,
    safe_cast(efgndrun as float64) efgndrun,
    safe_cast(xefgndran as string) xefgndran,
    safe_cast(efgndran as float64) efgndran,
    safe_cast(xefgndrua as string) xefgndrua,
    safe_cast(efgndrua as float64) efgndrua,
    safe_cast(xefgndrkn as string) xefgndrkn,
    safe_cast(efgndrkn as float64) efgndrkn,
    safe_cast(xefgndru as string) xefgndru,
    safe_cast(xefgndra as string) xefgndra,
    safe_cast(xefgndrk as string) xefgndrk,
    safe_cast(xdvefait as string) xdvefait,
    safe_cast(dvefait as float64) dvefait,
    safe_cast(xdvefaim as string) xdvefaim,
    safe_cast(dvefaim as float64) dvefaim,
    safe_cast(xdvefaiw as string) xdvefaiw,
    safe_cast(dvefaiw as float64) dvefaiw,
    safe_cast(xdvefapt as string) xdvefapt,
    safe_cast(dvefapt as float64) dvefapt,
    safe_cast(xdvefapm as string) xdvefapm,
    safe_cast(dvefapm as float64) dvefapm,
    safe_cast(xdvefapw as string) xdvefapw,
    safe_cast(dvefapw as float64) dvefapw,
    safe_cast(xdvefbkt as string) xdvefbkt,
    safe_cast(dvefbkt as float64) dvefbkt,
    safe_cast(xdvefbkm as string) xdvefbkm,
    safe_cast(dvefbkm as float64) dvefbkm,
    safe_cast(xdvefbkw as string) xdvefbkw,
    safe_cast(dvefbkw as float64) dvefbkw,
    safe_cast(xdvefhst as string) xdvefhst,
    safe_cast(dvefhst as float64) dvefhst,
    safe_cast(xdvefhsm as string) xdvefhsm,
    safe_cast(dvefhsm as float64) dvefhsm,
    safe_cast(xdvefhsw as string) xdvefhsw,
    safe_cast(dvefhsw as float64) dvefhsw,
    safe_cast(xdvefwht as string) xdvefwht,
    safe_cast(dvefwht as float64) dvefwht,
    safe_cast(xdvefwhm as string) xdvefwhm,
    safe_cast(dvefwhm as float64) dvefwhm,
    safe_cast(xdvefwhw as string) xdvefwhw,
    safe_cast(dvefwhw as float64) dvefwhw,
    safe_cast(xefrac19 as string) xefrac19,
    safe_cast(efrace19 as float64) efrace19,
    safe_cast(xefrac05 as string) xefrac05,
    safe_cast(efrace05 as float64) efrace05,
    safe_cast(xefrac06 as string) xefrac06,
    safe_cast(efrace06 as float64) efrace06,
    safe_cast(xefrac20 as string) xefrac20,
    safe_cast(efrace20 as float64) efrace20,
    safe_cast(xefrac07 as string) xefrac07,
    safe_cast(efrace07 as float64) efrace07,
    safe_cast(xefrac08 as string) xefrac08,
    safe_cast(efrace08 as float64) efrace08,
    safe_cast(xefrac18 as string) xefrac18,
    safe_cast(efrace18 as float64) efrace18,
    safe_cast(xefrac03 as string) xefrac03,
    safe_cast(efrace03 as float64) efrace03,
    safe_cast(xefrac04 as string) xefrac04,
    safe_cast(efrace04 as float64) efrace04,
    safe_cast(xefrac21 as string) xefrac21,
    safe_cast(efrace21 as float64) efrace21,
    safe_cast(xefrac09 as string) xefrac09,
    safe_cast(efrace09 as float64) efrace09,
    safe_cast(xefrac10 as string) xefrac10,
    safe_cast(efrace10 as float64) efrace10,
    safe_cast(xefrac22 as string) xefrac22,
    safe_cast(efrace22 as float64) efrace22,
    safe_cast(xefrac11 as string) xefrac11,
    safe_cast(efrace11 as float64) efrace11,
    safe_cast(xefrac12 as string) xefrac12,
    safe_cast(efrace12 as float64) efrace12,
    safe_cast(xefrac01 as string) xefrac01,
    safe_cast(efrace01 as float64) efrace01,
    safe_cast(xefrac02 as string) xefrac02,
    safe_cast(efrace02 as float64) efrace02,
    safe_cast(xefrac13 as string) xefrac13,
    safe_cast(efrace13 as float64) efrace13,
    safe_cast(xefrac14 as string) xefrac14,
    safe_cast(efrace14 as float64) efrace14,
    safe_cast(xefrac15 as string) xefrac15,
    safe_cast(efrace15 as float64) efrace15,
    safe_cast(xefrac16 as string) xefrac16,
    safe_cast(efrace16 as float64) efrace16,
    safe_cast(xefrac17 as string) xefrac17,
    safe_cast(efrace17 as float64) efrace17,
    safe_cast(xefrac23 as string) xefrac23,
    safe_cast(efrace23 as float64) efrace23,
    safe_cast(xefrac24 as string) xefrac24,
    safe_cast(efrace24 as float64) efrace24
from {{ set_datalake_project("us_ed_ipeds_staging.ef_a") }} as t
