{{
    config(
        schema="us_ed_ipeds",
        alias="gr",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 1997, "end": 2030, "interval": 1},
        },
        cluster_by=["unitid"],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(unitid as int64) unitid,
    safe_cast(grtype as float64) grtype,
    safe_cast(chrtstat as float64) chrtstat,
    safe_cast(section as int64) section,
    safe_cast(cohort as int64) cohort,
    safe_cast(line as float64) line,
    safe_cast(xgrtotlt as string) xgrtotlt,
    safe_cast(grtotlt as float64) grtotlt,
    safe_cast(xgrtotlm as string) xgrtotlm,
    safe_cast(grtotlm as float64) grtotlm,
    safe_cast(xgrtotlw as string) xgrtotlw,
    safe_cast(grtotlw as float64) grtotlw,
    safe_cast(xgraiant as string) xgraiant,
    safe_cast(graiant as float64) graiant,
    safe_cast(xgraianm as string) xgraianm,
    safe_cast(graianm as float64) graianm,
    safe_cast(xgraianw as string) xgraianw,
    safe_cast(graianw as float64) graianw,
    safe_cast(xgrasiat as string) xgrasiat,
    safe_cast(grasiat as float64) grasiat,
    safe_cast(xgrasiam as string) xgrasiam,
    safe_cast(grasiam as float64) grasiam,
    safe_cast(xgrasiaw as string) xgrasiaw,
    safe_cast(grasiaw as float64) grasiaw,
    safe_cast(xgrbkaat as string) xgrbkaat,
    safe_cast(grbkaat as float64) grbkaat,
    safe_cast(xgrbkaam as string) xgrbkaam,
    safe_cast(grbkaam as float64) grbkaam,
    safe_cast(xgrbkaaw as string) xgrbkaaw,
    safe_cast(grbkaaw as float64) grbkaaw,
    safe_cast(xgrhispt as string) xgrhispt,
    safe_cast(grhispt as float64) grhispt,
    safe_cast(xgrhispm as string) xgrhispm,
    safe_cast(grhispm as float64) grhispm,
    safe_cast(xgrhispw as string) xgrhispw,
    safe_cast(grhispw as float64) grhispw,
    safe_cast(xgrnhpit as string) xgrnhpit,
    safe_cast(grnhpit as float64) grnhpit,
    safe_cast(xgrnhpim as string) xgrnhpim,
    safe_cast(grnhpim as float64) grnhpim,
    safe_cast(xgrnhpiw as string) xgrnhpiw,
    safe_cast(grnhpiw as float64) grnhpiw,
    safe_cast(xgrwhitt as string) xgrwhitt,
    safe_cast(grwhitt as float64) grwhitt,
    safe_cast(xgrwhitm as string) xgrwhitm,
    safe_cast(grwhitm as float64) grwhitm,
    safe_cast(xgrwhitw as string) xgrwhitw,
    safe_cast(grwhitw as float64) grwhitw,
    safe_cast(xgr2mort as string) xgr2mort,
    safe_cast(gr2mort as float64) gr2mort,
    safe_cast(xgr2morm as string) xgr2morm,
    safe_cast(gr2morm as float64) gr2morm,
    safe_cast(xgr2morw as string) xgr2morw,
    safe_cast(gr2morw as float64) gr2morw,
    safe_cast(xgrunknt as string) xgrunknt,
    safe_cast(grunknt as float64) grunknt,
    safe_cast(xgrunknm as string) xgrunknm,
    safe_cast(grunknm as float64) grunknm,
    safe_cast(xgrunknw as string) xgrunknw,
    safe_cast(grunknw as float64) grunknw,
    safe_cast(xgrnralt as string) xgrnralt,
    safe_cast(grnralt as float64) grnralt,
    safe_cast(xgrnralm as string) xgrnralm,
    safe_cast(grnralm as float64) grnralm,
    safe_cast(xgrnralw as string) xgrnralw,
    safe_cast(grnralw as float64) grnralw,
    safe_cast(xgrrac03 as string) xgrrac03,
    safe_cast(grrace03 as float64) grrace03,
    safe_cast(xgrrac04 as string) xgrrac04,
    safe_cast(grrace04 as float64) grrace04,
    safe_cast(xgrrac05 as string) xgrrac05,
    safe_cast(grrace05 as float64) grrace05,
    safe_cast(xgrrac06 as string) xgrrac06,
    safe_cast(grrace06 as float64) grrace06,
    safe_cast(xgrrac07 as string) xgrrac07,
    safe_cast(grrace07 as float64) grrace07,
    safe_cast(xgrrac08 as string) xgrrac08,
    safe_cast(grrace08 as float64) grrace08,
    safe_cast(xgrrac09 as string) xgrrac09,
    safe_cast(grrace09 as float64) grrace09,
    safe_cast(xgrrac10 as string) xgrrac10,
    safe_cast(grrace10 as float64) grrace10,
    safe_cast(xgrrac11 as string) xgrrac11,
    safe_cast(grrace11 as float64) grrace11,
    safe_cast(xgrrac12 as string) xgrrac12,
    safe_cast(grrace12 as float64) grrace12,
    safe_cast(xgrrac18 as string) xgrrac18,
    safe_cast(grrace18 as float64) grrace18,
    safe_cast(xgrrac19 as string) xgrrac19,
    safe_cast(grrace19 as float64) grrace19,
    safe_cast(xgrrac20 as string) xgrrac20,
    safe_cast(grrace20 as float64) grrace20,
    safe_cast(xgrrac21 as string) xgrrac21,
    safe_cast(grrace21 as float64) grrace21,
    safe_cast(xgrrac22 as string) xgrrac22,
    safe_cast(grrace22 as float64) grrace22,
    safe_cast(xdvgrait as string) xdvgrait,
    safe_cast(dvgrait as float64) dvgrait,
    safe_cast(xdvgraim as string) xdvgraim,
    safe_cast(dvgraim as float64) dvgraim,
    safe_cast(xdvgraiw as string) xdvgraiw,
    safe_cast(dvgraiw as float64) dvgraiw,
    safe_cast(xdvgrapt as string) xdvgrapt,
    safe_cast(dvgrapt as float64) dvgrapt,
    safe_cast(xdvgrapm as string) xdvgrapm,
    safe_cast(dvgrapm as float64) dvgrapm,
    safe_cast(xdvgrapw as string) xdvgrapw,
    safe_cast(dvgrapw as float64) dvgrapw,
    safe_cast(xdvgrbkt as string) xdvgrbkt,
    safe_cast(dvgrbkt as float64) dvgrbkt,
    safe_cast(xdvgrbkm as string) xdvgrbkm,
    safe_cast(dvgrbkm as float64) dvgrbkm,
    safe_cast(xdvgrbkw as string) xdvgrbkw,
    safe_cast(dvgrbkw as float64) dvgrbkw,
    safe_cast(xdvgrhst as string) xdvgrhst,
    safe_cast(dvgrhst as float64) dvgrhst,
    safe_cast(xdvgrhsm as string) xdvgrhsm,
    safe_cast(dvgrhsm as float64) dvgrhsm,
    safe_cast(xdvgrhsw as string) xdvgrhsw,
    safe_cast(dvgrhsw as float64) dvgrhsw,
    safe_cast(xdvgrwht as string) xdvgrwht,
    safe_cast(dvgrwht as float64) dvgrwht,
    safe_cast(xdvgrwhm as string) xdvgrwhm,
    safe_cast(dvgrwhm as float64) dvgrwhm,
    safe_cast(xdvgrwhw as string) xdvgrwhw,
    safe_cast(dvgrwhw as float64) dvgrwhw,
    safe_cast(xgrrac01 as string) xgrrac01,
    safe_cast(grrace01 as float64) grrace01,
    safe_cast(xgrrac02 as string) xgrrac02,
    safe_cast(grrace02 as float64) grrace02,
    safe_cast(xgrrac13 as string) xgrrac13,
    safe_cast(grrace13 as float64) grrace13,
    safe_cast(xgrrac14 as string) xgrrac14,
    safe_cast(grrace14 as float64) grrace14,
    safe_cast(xgrrac15 as string) xgrrac15,
    safe_cast(grrace15 as float64) grrace15,
    safe_cast(xgrrac16 as string) xgrrac16,
    safe_cast(grrace16 as float64) grrace16,
    safe_cast(xgrrac17 as string) xgrrac17,
    safe_cast(grrace17 as float64) grrace17,
    safe_cast(xgrrac23 as string) xgrrac23,
    safe_cast(grrace23 as float64) grrace23,
    safe_cast(xgrrac24 as string) xgrrac24,
    safe_cast(grrace24 as float64) grrace24
from
    {{ set_datalake_project("us_ed_ipeds_staging.gr") }} as t
    -- rematerialize us_ed_ipeds (table-approve re-trigger)
