{{
    config(
        schema="us_bls_atus",
        alias="cps",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 2003, "end": 2029, "interval": 1},
        },
        cluster_by=["tucaseid"],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(tucaseid as string) tucaseid,
    safe_cast(tulineno as string) tulineno,
    safe_cast(gediv as string) gediv,
    safe_cast(gemetsta as string) gemetsta,
    safe_cast(gepseucl as string) gepseucl,
    safe_cast(gepseust as string) gepseust,
    safe_cast(gereg as string) gereg,
    lpad(safe_cast(gestfips as string), 2, '0') gestfips,
    safe_cast(gtcbsa as string) gtcbsa,
    safe_cast(gtco as string) gtco,
    safe_cast(gtmetsta as string) gtmetsta,
    safe_cast(hefaminc as string) hefaminc,
    safe_cast(hehousut as string) hehousut,
    safe_cast(hephoneo as string) hephoneo,
    safe_cast(hetelavl as string) hetelavl,
    safe_cast(hetelhhd as string) hetelhhd,
    safe_cast(hetenure as string) hetenure,
    safe_cast(hrhhid as string) hrhhid,
    safe_cast(hrhhid2 as string) hrhhid2,
    safe_cast(hrhtype as string) hrhtype,
    safe_cast(hrintsta as string) hrintsta,
    safe_cast(hrlonglk as string) hrlonglk,
    safe_cast(hrmis as string) hrmis,
    safe_cast(hrmonth as int64) hrmonth,
    safe_cast(hrnumhou as int64) hrnumhou,
    safe_cast(hrsample as string) hrsample,
    safe_cast(hrsersuf as string) hrsersuf,
    safe_cast(hryear4 as int64) hryear4,
    safe_cast(hubus as string) hubus,
    safe_cast(hubusl1 as string) hubusl1,
    safe_cast(hubusl2 as string) hubusl2,
    safe_cast(hubusl3 as string) hubusl3,
    safe_cast(hubusl4 as string) hubusl4,
    safe_cast(hufaminc as string) hufaminc,
    safe_cast(hufinal as string) hufinal,
    safe_cast(huhhnum as string) huhhnum,
    safe_cast(huinttyp as string) huinttyp,
    safe_cast(huprscnt as int64) huprscnt,
    safe_cast(hurespli as string) hurespli,
    safe_cast(huspnish as string) huspnish,
    safe_cast(hxfaminc as string) hxfaminc,
    safe_cast(peabspdo as string) peabspdo,
    safe_cast(peabsrsn as string) peabsrsn,
    safe_cast(peafever as string) peafever,
    safe_cast(peafnow as string) peafnow,
    safe_cast(peafwhen as string) peafwhen,
    safe_cast(peafwhn1 as string) peafwhn1,
    safe_cast(peafwhn2 as string) peafwhn2,
    safe_cast(peafwhn3 as string) peafwhn3,
    safe_cast(peafwhn4 as string) peafwhn4,
    safe_cast(pecert1 as string) pecert1,
    safe_cast(pecert2 as string) pecert2,
    safe_cast(pecert3 as string) pecert3,
    safe_cast(pecohab as string) pecohab,
    safe_cast(pecyc as string) pecyc,
    safe_cast(pedadtyp as string) pedadtyp,
    safe_cast(pedipged as string) pedipged,
    safe_cast(pedisdrs as string) pedisdrs,
    safe_cast(pedisear as string) pedisear,
    safe_cast(pediseye as string) pediseye,
    safe_cast(pedisout as string) pedisout,
    safe_cast(pedisphy as string) pedisphy,
    safe_cast(pedisrem as string) pedisrem,
    safe_cast(pedw4wk as string) pedw4wk,
    safe_cast(pedwavl as string) pedwavl,
    safe_cast(pedwavr as string) pedwavr,
    safe_cast(pedwlko as string) pedwlko,
    safe_cast(pedwlkwk as string) pedwlkwk,
    safe_cast(pedwrsn as string) pedwrsn,
    safe_cast(pedwwk as string) pedwwk,
    safe_cast(pedwwnto as string) pedwwnto,
    safe_cast(peeduca as string) peeduca,
    safe_cast(peern as int64) peern,
    safe_cast(peerncov as string) peerncov,
    safe_cast(peernh1o as float64) peernh1o,
    safe_cast(peernh2 as int64) peernh2,
    safe_cast(peernhro as int64) peernhro,
    safe_cast(peernhry as string) peernhry,
    safe_cast(peernlab as string) peernlab,
    safe_cast(peernper as string) peernper,
    safe_cast(peernrt as string) peernrt,
    safe_cast(peernuot as string) peernuot,
    safe_cast(peernwkp as int64) peernwkp,
    safe_cast(pefntvty as string) pefntvty,
    safe_cast(pegr6cor as string) pegr6cor,
    safe_cast(pegrprof as string) pegrprof,
    safe_cast(pehgcomp as string) pehgcomp,
    safe_cast(pehract1 as int64) pehract1,
    safe_cast(pehract2 as int64) pehract2,
    safe_cast(pehractt as int64) pehractt,
    safe_cast(pehravl as string) pehravl,
    safe_cast(pehrftpt as string) pehrftpt,
    safe_cast(pehrrsn1 as string) pehrrsn1,
    safe_cast(pehrrsn2 as string) pehrrsn2,
    safe_cast(pehrrsn3 as string) pehrrsn3,
    safe_cast(pehrusl1 as int64) pehrusl1,
    safe_cast(pehrusl2 as int64) pehrusl2,
    safe_cast(pehruslt as int64) pehruslt,
    safe_cast(pehrwant as string) pehrwant,
    safe_cast(pehspnon as string) pehspnon,
    safe_cast(peio1cow as string) peio1cow,
    case
        when regexp_contains(safe_cast(peio1icd as string), r'^[0-9]+$')
        then lpad(safe_cast(peio1icd as string), 4, '0')
        else safe_cast(peio1icd as string)
    end peio1icd,
    case
        when regexp_contains(safe_cast(peio1ocd as string), r'^[0-9]+$')
        then lpad(safe_cast(peio1ocd as string), 4, '0')
        else safe_cast(peio1ocd as string)
    end peio1ocd,
    safe_cast(peio2cow as string) peio2cow,
    case
        when regexp_contains(safe_cast(peio2icd as string), r'^[0-9]+$')
        then lpad(safe_cast(peio2icd as string), 4, '0')
        else safe_cast(peio2icd as string)
    end peio2icd,
    case
        when regexp_contains(safe_cast(peio2ocd as string), r'^[0-9]+$')
        then lpad(safe_cast(peio2ocd as string), 4, '0')
        else safe_cast(peio2ocd as string)
    end peio2ocd,
    safe_cast(pejhrsn as string) pejhrsn,
    safe_cast(pejhwant as string) pejhwant,
    safe_cast(pejhwko as string) pejhwko,
    safe_cast(pelayavl as string) pelayavl,
    safe_cast(pelaydur as int64) pelaydur,
    safe_cast(pelayfto as string) pelayfto,
    safe_cast(pelaylk as string) pelaylk,
    safe_cast(pelkavl as string) pelkavl,
    safe_cast(pelkdur as int64) pelkdur,
    safe_cast(pelkfto as string) pelkfto,
    safe_cast(pelkll1o as string) pelkll1o,
    safe_cast(pelkll2o as string) pelkll2o,
    safe_cast(pelklwo as string) pelklwo,
    safe_cast(pelkm1 as string) pelkm1,
    safe_cast(pelndad as string) pelndad,
    safe_cast(pelnmom as string) pelnmom,
    safe_cast(pemaritl as string) pemaritl,
    safe_cast(pemjnum as string) pemjnum,
    safe_cast(pemjot as string) pemjot,
    safe_cast(pemlr as string) pemlr,
    safe_cast(pemntvty as string) pemntvty,
    safe_cast(pemomtyp as string) pemomtyp,
    safe_cast(pems123 as string) pems123,
    safe_cast(penatvty as string) penatvty,
    safe_cast(penlfact as string) penlfact,
    safe_cast(penlfjh as string) penlfjh,
    safe_cast(penlfret as string) penlfret,
    safe_cast(peparent as string) peparent,
    safe_cast(pepdemp1 as string) pepdemp1,
    safe_cast(pepdemp2 as string) pepdemp2,
    safe_cast(peret1 as string) peret1,
    safe_cast(perrp as string) perrp,
    safe_cast(peschenr as string) peschenr,
    safe_cast(peschft as string) peschft,
    safe_cast(peschlvl as string) peschlvl,
    safe_cast(pesex as string) pesex,
    safe_cast(pespouse as string) pespouse,
    safe_cast(prabsrea as string) prabsrea,
    safe_cast(pragna as string) pragna,
    safe_cast(prcitshp as string) prcitshp,
    safe_cast(prcivlf as string) prcivlf,
    safe_cast(prcow1 as string) prcow1,
    safe_cast(prcow2 as string) prcow2,
    safe_cast(prcowpg as string) prcowpg,
    safe_cast(prdasian as string) prdasian,
    safe_cast(prdisc as string) prdisc,
    safe_cast(prdisflg as string) prdisflg,
    safe_cast(prdtcow1 as string) prdtcow1,
    safe_cast(prdtcow2 as string) prdtcow2,
    safe_cast(prdthsp as string) prdthsp,
    safe_cast(prdtind1 as string) prdtind1,
    safe_cast(prdtind2 as string) prdtind2,
    safe_cast(prdtocc1 as string) prdtocc1,
    safe_cast(prdtocc2 as string) prdtocc2,
    safe_cast(premp as string) premp,
    safe_cast(premphrs as string) premphrs,
    safe_cast(prempnot as string) prempnot,
    safe_cast(prerelg as string) prerelg,
    safe_cast(prernhly as float64) prernhly,
    safe_cast(prernwa as int64) prernwa,
    safe_cast(prexplf as string) prexplf,
    safe_cast(prfamnum as string) prfamnum,
    safe_cast(prfamrel as string) prfamrel,
    safe_cast(prfamtyp as string) prfamtyp,
    safe_cast(prftlf as string) prftlf,
    safe_cast(prhernal as string) prhernal,
    safe_cast(prhrusl as string) prhrusl,
    safe_cast(primind1 as string) primind1,
    safe_cast(primind2 as string) primind2,
    safe_cast(prinuyer as string) prinuyer,
    safe_cast(prioelg as string) prioelg,
    safe_cast(prjobsea as string) prjobsea,
    safe_cast(prmarsta as string) prmarsta,
    safe_cast(prmjind1 as string) prmjind1,
    safe_cast(prmjind2 as string) prmjind2,
    safe_cast(prmjocc1 as string) prmjocc1,
    safe_cast(prmjocc2 as string) prmjocc2,
    safe_cast(prmjocgr as string) prmjocgr,
    safe_cast(prnagpws as string) prnagpws,
    safe_cast(prnagws as string) prnagws,
    safe_cast(prnlfsch as string) prnlfsch,
    safe_cast(prnmchld as int64) prnmchld,
    safe_cast(prpertyp as string) prpertyp,
    safe_cast(prpthrs as string) prpthrs,
    safe_cast(prptrea as string) prptrea,
    safe_cast(prsjmj as string) prsjmj,
    safe_cast(prtage as int64) prtage,
    safe_cast(prunedur as int64) prunedur,
    safe_cast(pruntype as string) pruntype,
    safe_cast(prwernal as string) prwernal,
    safe_cast(prwksch as string) prwksch,
    safe_cast(prwkstat as string) prwkstat,
    safe_cast(prwntjob as string) prwntjob,
    safe_cast(ptdtrace as string) ptdtrace,
    safe_cast(pthr as string) pthr,
    safe_cast(ptnmemp1 as int64) ptnmemp1,
    safe_cast(ptnmemp2 as int64) ptnmemp2,
    safe_cast(ptot as string) ptot,
    safe_cast(ptwk as string) ptwk,
    safe_cast(puabsot as string) puabsot,
    safe_cast(puafever as string) puafever,
    safe_cast(pubus1 as string) pubus1,
    safe_cast(pubus2ot as string) pubus2ot,
    safe_cast(pudis as string) pudis,
    safe_cast(pudis1 as string) pudis1,
    safe_cast(pudis2 as string) pudis2,
    safe_cast(puhroff1 as string) puhroff1,
    safe_cast(puhroff2 as int64) puhroff2,
    safe_cast(puhrot1 as string) puhrot1,
    safe_cast(puhrot2 as int64) puhrot2,
    safe_cast(pujhdp1o as string) pujhdp1o,
    safe_cast(pulay as string) pulay,
    safe_cast(pulay6m as string) pulay6m,
    safe_cast(pulayavr as string) pulayavr,
    safe_cast(pulaydt as string) pulaydt,
    safe_cast(pulineno as string) pulineno,
    safe_cast(pulk as string) pulk,
    safe_cast(pulkavr as string) pulkavr,
    safe_cast(pulkdk1 as string) pulkdk1,
    safe_cast(pulkdk2 as string) pulkdk2,
    safe_cast(pulkdk3 as string) pulkdk3,
    safe_cast(pulkdk4 as string) pulkdk4,
    safe_cast(pulkm2 as string) pulkm2,
    safe_cast(pulkm3 as string) pulkm3,
    safe_cast(pulkm4 as string) pulkm4,
    safe_cast(pulkm5 as string) pulkm5,
    safe_cast(pulkm6 as string) pulkm6,
    safe_cast(pulkps1 as string) pulkps1,
    safe_cast(pulkps2 as string) pulkps2,
    safe_cast(pulkps3 as string) pulkps3,
    safe_cast(pulkps4 as string) pulkps4,
    safe_cast(pupelig as string) pupelig,
    safe_cast(puretot as string) puretot,
    safe_cast(puslfprx as string) puslfprx,
    safe_cast(puwk as string) puwk,
    safe_cast(tratusr as string) tratusr,
    safe_cast(tubwgt as float64) tubwgt,
    safe_cast(ptcovid1 as string) ptcovid1,
    safe_cast(ptcovid2 as string) ptcovid2,
    safe_cast(ptcovid3 as string) ptcovid3,
    safe_cast(ptcovid4 as string) ptcovid4,
    safe_cast(ptcovid5w as string) ptcovid5w,
    safe_cast(pepar1 as string) pepar1,
    safe_cast(pepar2 as string) pepar2,
    safe_cast(pepar1typ as string) pepar1typ,
    safe_cast(pepar2typ as string) pepar2typ,
    safe_cast(prernmin as string) prernmin,
    safe_cast(ptcovr1 as string) ptcovr1,
    safe_cast(ptcovr2 as int64) ptcovr2,
    safe_cast(ptcovr3 as string) ptcovr3,
    safe_cast(ptcovr4 as string) ptcovr4,
    safe_cast(pxcovr1 as string) pxcovr1,
    safe_cast(pxcovr2 as string) pxcovr2,
    safe_cast(pxcovr3 as string) pxcovr3,
    safe_cast(pxcovr4 as string) pxcovr4,
    safe_cast(pttlwk as string) pttlwk,
    safe_cast(pttlwkhr as int64) pttlwkhr,
    safe_cast(pxtlwk as string) pxtlwk,
    safe_cast(pxtlwkhr as string) pxtlwkhr
from {{ set_datalake_project("us_bls_atus_staging.cps") }} as t
