{{
    config(
        schema="us_bls_atus",
        alias="respondent",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 2003, "end": 2029, "interval": 1},
        },
        cluster_by=["tucaseid"],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(tucaseid as string) tucaseid,
    safe_cast(tulineno as string) tulineno,
    safe_cast(tespuhrs as float64) tespuhrs,
    safe_cast(trdtind1 as string) trdtind1,
    safe_cast(trdtocc1 as string) trdtocc1,
    safe_cast(trernhly as float64) trernhly,
    safe_cast(trernupd as string) trernupd,
    safe_cast(trhernal as string) trhernal,
    safe_cast(trhhchild as string) trhhchild,
    safe_cast(trimind1 as string) trimind1,
    safe_cast(trmjind1 as string) trmjind1,
    safe_cast(trmjocc1 as string) trmjocc1,
    safe_cast(trmjocgr as string) trmjocgr,
    safe_cast(trnhhchild as string) trnhhchild,
    safe_cast(trnumhou as int64) trnumhou,
    safe_cast(trohhchild as string) trohhchild,
    safe_cast(trtalone as int64) trtalone,
    safe_cast(trtcc as int64) trtcc,
    safe_cast(trthhfamily as int64) trthhfamily,
    safe_cast(trtnochild as int64) trtnochild,
    safe_cast(trtnohh as int64) trtnohh,
    safe_cast(trto as int64) trto,
    safe_cast(trtohh as int64) trtohh,
    safe_cast(trtohhchild as int64) trtohhchild,
    safe_cast(trtonhh as int64) trtonhh,
    safe_cast(trtonhhchild as int64) trtonhhchild,
    safe_cast(trtsponly as int64) trtsponly,
    safe_cast(trtspouse as int64) trtspouse,
    safe_cast(trtunmpart as int64) trtunmpart,
    safe_cast(trwernal as string) trwernal,
    safe_cast(tthr as string) tthr,
    safe_cast(ttot as string) ttot,
    safe_cast(ttwk as string) ttwk,
    safe_cast(tuabsot as string) tuabsot,
    safe_cast(teabsrsn as string) teabsrsn,
    safe_cast(teern as int64) teern,
    safe_cast(teernh1o as float64) teernh1o,
    safe_cast(teernh2 as int64) teernh2,
    safe_cast(teernhro as float64) teernhro,
    safe_cast(teernhry as string) teernhry,
    safe_cast(teernper as string) teernper,
    safe_cast(teernrt as string) teernrt,
    safe_cast(teernuot as string) teernuot,
    safe_cast(teernwkp as int64) teernwkp,
    safe_cast(tehrftpt as string) tehrftpt,
    safe_cast(tehrusl1 as int64) tehrusl1,
    safe_cast(tehrusl2 as int64) tehrusl2,
    safe_cast(teio1cow as string) teio1cow,
    case
        when regexp_contains(safe_cast(teio1icd as string), r'^[0-9]+$')
        then lpad(safe_cast(teio1icd as string), 4, '0')
        else safe_cast(teio1icd as string)
    end teio1icd,
    case
        when regexp_contains(safe_cast(teio1ocd as string), r'^[0-9]+$')
        then lpad(safe_cast(teio1ocd as string), 4, '0')
        else safe_cast(teio1ocd as string)
    end teio1ocd,
    safe_cast(telayavl as string) telayavl,
    safe_cast(telaylk as string) telaylk,
    safe_cast(telkavl as string) telkavl,
    safe_cast(telkm1 as string) telkm1,
    safe_cast(teret1 as string) teret1,
    safe_cast(teschft as string) teschft,
    safe_cast(tubus as string) tubus,
    safe_cast(tubus1 as string) tubus1,
    safe_cast(tubus2ot as string) tubus2ot,
    safe_cast(tubusl1 as string) tubusl1,
    safe_cast(tubusl2 as string) tubusl2,
    safe_cast(tubusl3 as string) tubusl3,
    safe_cast(tubusl4 as string) tubusl4,
    safe_cast(tucc2 as string) tucc2,
    safe_cast(tucc4 as string) tucc4,
    safe_cast(tufwk as string) tufwk,
    safe_cast(tuio1mfg as string) tuio1mfg,
    safe_cast(tuiodp1 as string) tuiodp1,
    safe_cast(tuiodp2 as string) tuiodp2,
    safe_cast(tuiodp3 as string) tuiodp3,
    safe_cast(tulay as string) tulay,
    safe_cast(tulay6m as string) tulay6m,
    safe_cast(tulayavr as string) tulayavr,
    safe_cast(tulaydt as string) tulaydt,
    safe_cast(tulk as string) tulk,
    safe_cast(tulkavr as string) tulkavr,
    safe_cast(tulkdk1 as string) tulkdk1,
    safe_cast(tulkdk2 as string) tulkdk2,
    safe_cast(tulkdk3 as string) tulkdk3,
    safe_cast(tulkdk4 as string) tulkdk4,
    safe_cast(tulkm2 as string) tulkm2,
    safe_cast(tulkm3 as string) tulkm3,
    safe_cast(tulkm4 as string) tulkm4,
    safe_cast(tulkm5 as string) tulkm5,
    safe_cast(tulkm6 as string) tulkm6,
    safe_cast(tulkps1 as string) tulkps1,
    safe_cast(tulkps2 as string) tulkps2,
    safe_cast(tulkps3 as string) tulkps3,
    safe_cast(tulkps4 as string) tulkps4,
    safe_cast(tumonth as int64) tumonth,
    safe_cast(trtccc as int64) trtccc,
    safe_cast(trtcctot as int64) trtcctot,
    safe_cast(trtchild as int64) trtchild,
    safe_cast(trtcoc as int64) trtcoc,
    safe_cast(trtfamily as int64) trtfamily,
    safe_cast(trtfriend as int64) trtfriend,
    safe_cast(trthh as int64) trthh,
    safe_cast(tudis2 as string) tudis2,
    safe_cast(turetot as string) turetot,
    safe_cast(tuspabs as string) tuspabs,
    safe_cast(tuspusft as string) tuspusft,
    safe_cast(tuspwk as string) tuspwk,
    safe_cast(tremodr as string) tremodr,
    safe_cast(tucc9 as string) tucc9,
    safe_cast(tudiarydate as string) tudiarydate,
    safe_cast(tudis as string) tudis,
    safe_cast(tudis1 as string) tudis1,
    safe_cast(trchildnum as int64) trchildnum,
    safe_cast(tudiaryday as string) tudiaryday,
    safe_cast(trernwa as int64) trernwa,
    safe_cast(trholiday as string) trholiday,
    safe_cast(trspftpt as string) trspftpt,
    safe_cast(trsppres as string) trsppres,
    safe_cast(trdpftpt as string) trdpftpt,
    safe_cast(tufnwgtp as float64) tufnwgtp,
    safe_cast(tespempnot as string) tespempnot,
    safe_cast(teschlvl as string) teschlvl,
    safe_cast(teschenr as string) teschenr,
    safe_cast(temjot as string) temjot,
    safe_cast(telfs as string) telfs,
    safe_cast(tehruslt as int64) tehruslt,
    safe_cast(tryhhchild as int64) tryhhchild,
    safe_cast(trwbmodr as string) trwbmodr,
    safe_cast(trtalone_wk as int64) trtalone_wk,
    safe_cast(trtccc_wk as int64) trtccc_wk,
    safe_cast(trlvmodr as string) trlvmodr,
    safe_cast(trtec as int64) trtec,
    safe_cast(tuecytd as string) tuecytd,
    safe_cast(tuelder as string) tuelder,
    safe_cast(tuelfreq as string) tuelfreq,
    safe_cast(tuelnum as int64) tuelnum,
    safe_cast(tu20fwgt as float64) tu20fwgt
from {{ set_datalake_project("us_bls_atus_staging.respondent") }} as t
