columns_order = [
    "ano",
    "sigla_uf",
    "CVLI Crimes violentos letais intencionais",
    "Feminicídios",
    "Homicídio doloso - N° ocorrências",
    "Homicídio doloso - N° vítimas",
    "Latrocínio",
    "Lesão corporal seguida de morte",
    "Mortes a esclarecer",
    "Mortes decorrentes de intervenções de Policiais Civis em serviço",
    "Mortes decorrentes de intervenções de Policiais Civis fora de serviço",
    "Mortes decorrentes de intervenções de Policiais Militares em serviço",
    "Mortes decorrentes de intervenções de Policiais Militares fora de serviço",
    "Mortes decorrentes de intervenções policiais - Total (Policiais civis e militares em serviço e fora)",
    "Mortes Violentas Intencionais",
    "Policiais Civis mortos em confronto em serviço",
    "Policiais Civis mortos em confronto ou por lesão não natural fora de serviço",
    "Policiais Militares mortos em confronto em serviço",
    "Policiais Militares mortos em confronto ou por lesão não natural fora de serviço",
    "Suicídio",
    "Estupro (incluindo Estupro de Vulnerável)",
    "Tentativa de estupro",
    "Furto de veículo",
    "Roubo a instituição financeira",
    "Roubo de carga",
    "Roubo de veículo",
    "Roubo e furto de veículos",
    "Armas de fogo apreendidas",
    "Registros de pessoas desaparecidas",
    "População do sistema penitenciário",
    "Despesas empenhadas na Função Segurança Pública",
]

real_columns = [
    "ano",
    "sigla_uf",
    "quantidade_cvli",
    "quantidade_feminicidio",
    "quantidade_ocorrencia_homicidio_doloso",
    "quantidade_vitima_homicidio_doloso",
    "quantidade_latrocinio",
    "quantidade_lesao_corporal_seguida_de_morte",
    "quantidade_morte_a_esclarecer",
    "quantidade_morte_intervencao_policial_civil_servico",
    "quantidade_morte_intervencao_policial_civil_fora_servico",
    "quantidade_morte_intervencao_policial_militar_servico",
    "quantidade_morte_intervencao_policial_militar_fora_servico",
    "quantidade_morte_violenta_intencional",
    "quantidade_policial_civil_morto_confronto_servico",
    "quantidade_policial_civil_morto_confronto_fora_servico",
    "quantidade_policial_militar_morto_confronto_servico",
    "quantidade_policial_militar_morto_confronto_fora_servico",
    "quantidade_suicidio",
    "quantidade_estupro",
    "quantidade_tentativa_estupro",
    "quantidade_furto_veiculo",
    "quantidade_roubo_instituicao_financeira",
    "quantidade_roubo_carga",
    "quantidade_roubo_de_veiculo",
    "quantidade_arma_fogo_apreendida",
    "quantidade_registro_pessoa_desaparecida",
    "quantidade_populacao_sistema_penitenciario",
    "despesa_empenhada_seguranca_publica",
]
