{{
    config(
        schema="us_nih_reporter",
        alias="project",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 1985, "end": 2031, "interval": 1},
        },
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(application_id as string) application_id,
    safe_cast(full_project_num as string) full_project_num,
    safe_cast(core_project_num as string) core_project_num,
    safe_cast(subproject_id as string) subproject_id,
    safe_cast(application_type as string) application_type,
    safe_cast(activity as string) activity,
    safe_cast(administering_ic as string) administering_ic,
    safe_cast(serial_number as string) serial_number,
    safe_cast(suffix as string) suffix,
    safe_cast(support_year as int64) support_year,
    safe_cast(assistance_listing_number as string) assistance_listing_number,
    safe_cast(opportunity_number as string) opportunity_number,
    safe_cast(study_section as string) study_section,
    safe_cast(org_ipf_id as string) org_ipf_id,
    safe_cast(org_duns as string) org_duns,
    safe_cast(pi_ids as string) pi_ids,
    safe_cast(project_title as string) project_title,
    safe_cast(ic_name as string) ic_name,
    safe_cast(funding_mechanism as string) funding_mechanism,
    safe_cast(funding_ics as string) funding_ics,
    safe_cast(arra_funded as string) arra_funded,
    safe_cast(study_section_name as string) study_section_name,
    safe_cast(program_officer_name as string) program_officer_name,
    safe_cast(pi_names as string) pi_names,
    safe_cast(org_name as string) org_name,
    safe_cast(org_dept as string) org_dept,
    safe_cast(ed_inst_type as string) ed_inst_type,
    safe_cast(org_city as string) org_city,
    safe_cast(org_state as string) org_state,
    safe_cast(org_zipcode as string) org_zipcode,
    safe_cast(org_district as string) org_district,
    safe_cast(org_country as string) org_country,
    safe_cast(org_fips as string) org_fips,
    safe_cast(project_start as date) project_start,
    safe_cast(project_end as date) project_end,
    safe_cast(budget_start as date) budget_start,
    safe_cast(budget_end as date) budget_end,
    safe_cast(award_notice_date as date) award_notice_date,
    safe_cast(nih_spending_cats as string) nih_spending_cats,
    safe_cast(project_terms as string) project_terms,
    safe_cast(public_health_relevance as string) public_health_relevance,
    safe_cast(direct_cost as float64) direct_cost,
    safe_cast(indirect_cost as float64) indirect_cost,
    safe_cast(total_cost as float64) total_cost,
    safe_cast(total_cost_subproject as float64) total_cost_subproject
from {{ set_datalake_project("us_nih_reporter_staging.project") }} as t
