{{
    config(
        schema="in_tcpd_elections",
        alias="assembly_elections",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 1961, "end": 2028, "interval": 1},
        },
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(month as string) month,
    safe_cast(state_acronym as string) state_acronym,
    safe_cast(assembly_number as string) assembly_number,
    safe_cast(constituency_number as string) constituency_number,
    safe_cast(constituency_name as string) constituency_name,
    safe_cast(constituency_type as string) constituency_type,
    safe_cast(sub_region as string) sub_region,
    safe_cast(district_name as string) district_name,
    safe_cast(poll_type as string) poll_type,
    safe_cast(delimitation_id as string) delimitation_id,
    safe_cast(position as string) position,
    safe_cast(candidate_id as string) candidate_id,
    safe_cast(candidate_name as string) candidate_name,
    safe_cast(candidate_sex as string) candidate_sex,
    safe_cast(candidate_type as string) candidate_type,
    safe_cast(candidate_age as int64) candidate_age,
    safe_cast(party as string) party,
    safe_cast(party_id as string) party_id,
    safe_cast(party_type as string) party_type,
    safe_cast(votes as int64) votes,
    safe_cast(valid_votes as int64) valid_votes,
    safe_cast(voters as int64) voters,
    safe_cast(candidates as int64) candidates,
    safe_cast(turnout_percentage as float64) turnout_percentage,
    safe_cast(vote_share_percentage as float64) vote_share_percentage,
    safe_cast(margin_votes as int64) margin_votes,
    safe_cast(margin_percentage as float64) margin_percentage,
    safe_cast(enop as float64) enop,
    safe_cast(deposit_lost as bool) deposit_lost,
    safe_cast(incumbent as bool) incumbent,
    safe_cast(recontest as bool) recontest,
    safe_cast(last_poll as bool) last_poll,
    safe_cast(contested as int64) contested,
    safe_cast(terms as int64) terms,
    safe_cast(turncoat as bool) turncoat,
    safe_cast(same_constituency as bool) same_constituency,
    safe_cast(same_party as bool) same_party,
    safe_cast(last_party as string) last_party,
    safe_cast(last_party_id as string) last_party_id,
    safe_cast(last_constituency_name as string) last_constituency_name,
    safe_cast(education_level as string) education_level,
    safe_cast(profession_main_category as string) profession_main_category,
    safe_cast(profession_main_type as string) profession_main_type,
    safe_cast(profession_secondary_category as string) profession_secondary_category,
    safe_cast(profession_secondary_type as string) profession_secondary_type
from {{ set_datalake_project("in_tcpd_elections_staging.assembly_elections") }} as t
