{{
    config(
        schema="us_ed_college_scorecard",
        alias="institution",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 1996, "end": 2030, "interval": 1},
        },
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(unitid as string) unitid,
    safe_cast(opeid8 as string) opeid8,
    safe_cast(opeid6 as string) opeid6,
    safe_cast(federal_school_code as string) federal_school_code,
    safe_cast(institution_name as string) institution_name,
    safe_cast(institution_alias as string) institution_alias,
    safe_cast(institution_url as string) institution_url,
    safe_cast(net_price_calculator_url as string) net_price_calculator_url,
    safe_cast(address as string) address,
    safe_cast(city as string) city,
    safe_cast(state_abbreviation as string) state_abbreviation,
    safe_cast(zip_code as string) zip_code,
    safe_cast(state_fips as string) state_fips,
    safe_cast(region as string) region,
    safe_cast(locale as string) locale,
    safe_cast(locale_degree_urbanization as string) locale_degree_urbanization,
    safe_cast(latitude as float64) latitude,
    safe_cast(longitude as float64) longitude,
    safe_cast(control as string) control,
    safe_cast(control_peps as string) control_peps,
    safe_cast(ownership_peps as string) ownership_peps,
    safe_cast(scorecard_sector as string) scorecard_sector,
    safe_cast(institution_level as string) institution_level,
    safe_cast(predominant_degree as string) predominant_degree,
    safe_cast(predominant_degree_recoded as string) predominant_degree_recoded,
    safe_cast(highest_degree as string) highest_degree,
    safe_cast(main_campus as string) main_campus,
    safe_cast(branch_campuses as int64) branch_campuses,
    safe_cast(carnegie_basic as string) carnegie_basic,
    safe_cast(carnegie_undergraduate_profile as string) carnegie_undergraduate_profile,
    safe_cast(carnegie_size_setting as string) carnegie_size_setting,
    safe_cast(online_only as string) online_only,
    safe_cast(currently_operating as string) currently_operating,
    safe_cast(open_admissions_policy as string) open_admissions_policy,
    safe_cast(religious_affiliation as string) religious_affiliation,
    safe_cast(men_only as string) men_only,
    safe_cast(women_only as string) women_only,
    safe_cast(historically_black as string) historically_black,
    safe_cast(predominantly_black as string) predominantly_black,
    safe_cast(alaska_native_hawaiian_serving as string) alaska_native_hawaiian_serving,
    safe_cast(tribal_college as string) tribal_college,
    safe_cast(asian_pacific_islander_serving as string) asian_pacific_islander_serving,
    safe_cast(hispanic_serving as string) hispanic_serving,
    safe_cast(native_american_non_tribal as string) native_american_non_tribal,
    safe_cast(accreditor_name as string) accreditor_name,
    safe_cast(accreditor_code as string) accreditor_code,
    safe_cast(title_iv_eligibility_type as string) title_iv_eligibility_type,
    safe_cast(title_iv_approval_date as date) title_iv_approval_date,
    safe_cast(heightened_cash_monitoring as string) heightened_cash_monitoring,
    safe_cast(dol_provider as string) dol_provider,
    safe_cast(undergraduate_enrollment as int64) undergraduate_enrollment,
    safe_cast(undergraduate_enrollment_all as int64) undergraduate_enrollment_all,
    safe_cast(tuition_revenue_per_fte as int64) tuition_revenue_per_fte,
    safe_cast(
        instructional_expenditure_per_fte as int64
    ) instructional_expenditure_per_fte,
    safe_cast(average_faculty_salary as int64) average_faculty_salary,
    safe_cast(full_time_faculty_rate as float64) full_time_faculty_rate,
    safe_cast(endowment_begin as int64) endowment_begin,
    safe_cast(endowment_end as int64) endowment_end,
    safe_cast(admission_rate as float64) admission_rate,
    safe_cast(admission_rate_all_campuses as float64) admission_rate_all_campuses,
    safe_cast(admission_rate_suppressed as float64) admission_rate_suppressed,
    safe_cast(test_score_requirement as string) test_score_requirement,
    safe_cast(sat_average as float64) sat_average,
    safe_cast(sat_average_all_campuses as float64) sat_average_all_campuses,
    safe_cast(sat_reading_p25 as string) sat_reading_p25,
    safe_cast(sat_reading_p50 as string) sat_reading_p50,
    safe_cast(sat_reading_p75 as string) sat_reading_p75,
    safe_cast(sat_reading_midpoint as string) sat_reading_midpoint,
    safe_cast(sat_math_p25 as string) sat_math_p25,
    safe_cast(sat_math_p50 as string) sat_math_p50,
    safe_cast(sat_math_p75 as string) sat_math_p75,
    safe_cast(sat_math_midpoint as string) sat_math_midpoint,
    safe_cast(sat_writing_p25 as string) sat_writing_p25,
    safe_cast(sat_writing_p75 as string) sat_writing_p75,
    safe_cast(sat_writing_midpoint as string) sat_writing_midpoint,
    safe_cast(act_composite_p25 as string) act_composite_p25,
    safe_cast(act_composite_p50 as string) act_composite_p50,
    safe_cast(act_composite_p75 as string) act_composite_p75,
    safe_cast(act_composite_midpoint as string) act_composite_midpoint,
    safe_cast(act_english_p25 as string) act_english_p25,
    safe_cast(act_english_p50 as string) act_english_p50,
    safe_cast(act_english_p75 as string) act_english_p75,
    safe_cast(act_english_midpoint as string) act_english_midpoint,
    safe_cast(act_math_p25 as string) act_math_p25,
    safe_cast(act_math_p50 as string) act_math_p50,
    safe_cast(act_math_p75 as string) act_math_p75,
    safe_cast(act_math_midpoint as string) act_math_midpoint,
    safe_cast(act_writing_p25 as string) act_writing_p25,
    safe_cast(act_writing_p75 as string) act_writing_p75,
    safe_cast(act_writing_midpoint as string) act_writing_midpoint
from {{ set_datalake_project("us_ed_college_scorecard_staging.institution") }} as t
