{{
    config(
        schema="us_ed_college_scorecard",
        alias="field_of_study",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 2015, "end": 2027, "interval": 1},
        },
        cluster_by=['cip_code'],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(unitid as string) unitid,
    safe_cast(opeid6 as string) opeid6,
    safe_cast(institution_name as string) institution_name,
    safe_cast(control as string) control,
    safe_cast(main_campus as string) main_campus,
    safe_cast(cip_code as string) cip_code,
    safe_cast(cip_description as string) cip_description,
    safe_cast(credential_level as string) credential_level,
    safe_cast(credential_description as string) credential_description,
    safe_cast(ipedscount1 as int64) ipedscount1,
    safe_cast(ipedscount2 as int64) ipedscount2,
    safe_cast(debt_all_stgp_any_n as int64) debt_all_stgp_any_n,
    safe_cast(debt_all_stgp_any_mean as float64) debt_all_stgp_any_mean,
    safe_cast(debt_all_stgp_any_mdn as float64) debt_all_stgp_any_mdn,
    safe_cast(debt_all_stgp_eval_n as int64) debt_all_stgp_eval_n,
    safe_cast(debt_all_stgp_eval_mean as float64) debt_all_stgp_eval_mean,
    safe_cast(debt_all_stgp_eval_mdn as float64) debt_all_stgp_eval_mdn,
    safe_cast(debt_all_pp_any_n as int64) debt_all_pp_any_n,
    safe_cast(debt_all_pp_any_mean as float64) debt_all_pp_any_mean,
    safe_cast(debt_all_pp_any_mdn as float64) debt_all_pp_any_mdn,
    safe_cast(debt_all_pp_eval_n as int64) debt_all_pp_eval_n,
    safe_cast(debt_all_pp_eval_mean as float64) debt_all_pp_eval_mean,
    safe_cast(debt_all_pp_eval_mdn as float64) debt_all_pp_eval_mdn,
    safe_cast(debt_male_stgp_any_n as int64) debt_male_stgp_any_n,
    safe_cast(debt_male_stgp_any_mean as float64) debt_male_stgp_any_mean,
    safe_cast(debt_male_stgp_any_mdn as float64) debt_male_stgp_any_mdn,
    safe_cast(debt_male_stgp_eval_n as int64) debt_male_stgp_eval_n,
    safe_cast(debt_male_stgp_eval_mean as float64) debt_male_stgp_eval_mean,
    safe_cast(debt_male_stgp_eval_mdn as float64) debt_male_stgp_eval_mdn,
    safe_cast(debt_male_pp_any_n as int64) debt_male_pp_any_n,
    safe_cast(debt_male_pp_any_mean as float64) debt_male_pp_any_mean,
    safe_cast(debt_male_pp_any_mdn as float64) debt_male_pp_any_mdn,
    safe_cast(debt_male_pp_eval_n as int64) debt_male_pp_eval_n,
    safe_cast(debt_male_pp_eval_mean as float64) debt_male_pp_eval_mean,
    safe_cast(debt_male_pp_eval_mdn as float64) debt_male_pp_eval_mdn,
    safe_cast(debt_notmale_stgp_any_n as int64) debt_notmale_stgp_any_n,
    safe_cast(debt_notmale_stgp_any_mean as float64) debt_notmale_stgp_any_mean,
    safe_cast(debt_notmale_stgp_any_mdn as float64) debt_notmale_stgp_any_mdn,
    safe_cast(debt_notmale_stgp_eval_n as int64) debt_notmale_stgp_eval_n,
    safe_cast(debt_notmale_stgp_eval_mean as float64) debt_notmale_stgp_eval_mean,
    safe_cast(debt_notmale_stgp_eval_mdn as float64) debt_notmale_stgp_eval_mdn,
    safe_cast(debt_notmale_pp_any_n as int64) debt_notmale_pp_any_n,
    safe_cast(debt_notmale_pp_any_mean as float64) debt_notmale_pp_any_mean,
    safe_cast(debt_notmale_pp_any_mdn as float64) debt_notmale_pp_any_mdn,
    safe_cast(debt_notmale_pp_eval_n as int64) debt_notmale_pp_eval_n,
    safe_cast(debt_notmale_pp_eval_mean as float64) debt_notmale_pp_eval_mean,
    safe_cast(debt_notmale_pp_eval_mdn as float64) debt_notmale_pp_eval_mdn,
    safe_cast(debt_pell_stgp_any_n as int64) debt_pell_stgp_any_n,
    safe_cast(debt_pell_stgp_any_mean as float64) debt_pell_stgp_any_mean,
    safe_cast(debt_pell_stgp_any_mdn as float64) debt_pell_stgp_any_mdn,
    safe_cast(debt_pell_stgp_eval_n as int64) debt_pell_stgp_eval_n,
    safe_cast(debt_pell_stgp_eval_mean as float64) debt_pell_stgp_eval_mean,
    safe_cast(debt_pell_stgp_eval_mdn as float64) debt_pell_stgp_eval_mdn,
    safe_cast(debt_pell_pp_any_n as int64) debt_pell_pp_any_n,
    safe_cast(debt_pell_pp_any_mean as float64) debt_pell_pp_any_mean,
    safe_cast(debt_pell_pp_any_mdn as float64) debt_pell_pp_any_mdn,
    safe_cast(debt_pell_pp_eval_n as int64) debt_pell_pp_eval_n,
    safe_cast(debt_pell_pp_eval_mean as float64) debt_pell_pp_eval_mean,
    safe_cast(debt_pell_pp_eval_mdn as float64) debt_pell_pp_eval_mdn,
    safe_cast(debt_nopell_stgp_any_n as int64) debt_nopell_stgp_any_n,
    safe_cast(debt_nopell_stgp_any_mean as float64) debt_nopell_stgp_any_mean,
    safe_cast(debt_nopell_stgp_any_mdn as float64) debt_nopell_stgp_any_mdn,
    safe_cast(debt_nopell_stgp_eval_n as int64) debt_nopell_stgp_eval_n,
    safe_cast(debt_nopell_stgp_eval_mean as float64) debt_nopell_stgp_eval_mean,
    safe_cast(debt_nopell_stgp_eval_mdn as float64) debt_nopell_stgp_eval_mdn,
    safe_cast(debt_nopell_pp_any_n as int64) debt_nopell_pp_any_n,
    safe_cast(debt_nopell_pp_any_mean as float64) debt_nopell_pp_any_mean,
    safe_cast(debt_nopell_pp_any_mdn as float64) debt_nopell_pp_any_mdn,
    safe_cast(debt_nopell_pp_eval_n as int64) debt_nopell_pp_eval_n,
    safe_cast(debt_nopell_pp_eval_mean as float64) debt_nopell_pp_eval_mean,
    safe_cast(debt_nopell_pp_eval_mdn as float64) debt_nopell_pp_eval_mdn,
    safe_cast(debt_all_pp_any_mdn10yrpay as float64) debt_all_pp_any_mdn10yrpay,
    safe_cast(debt_all_pp_eval_mdn10yrpay as float64) debt_all_pp_eval_mdn10yrpay,
    safe_cast(debt_all_stgp_any_mdn10yrpay as float64) debt_all_stgp_any_mdn10yrpay,
    safe_cast(debt_all_stgp_eval_mdn10yrpay as float64) debt_all_stgp_eval_mdn10yrpay,
    safe_cast(earn_count_nwne_hi_1yr as int64) earn_count_nwne_hi_1yr,
    safe_cast(earn_cntover150_hi_1yr as int64) earn_cntover150_hi_1yr,
    safe_cast(earn_count_wne_hi_1yr as int64) earn_count_wne_hi_1yr,
    safe_cast(earn_mdn_hi_1yr as float64) earn_mdn_hi_1yr,
    safe_cast(earn_count_nwne_hi_2yr as int64) earn_count_nwne_hi_2yr,
    safe_cast(earn_cntover150_hi_2yr as int64) earn_cntover150_hi_2yr,
    safe_cast(earn_count_wne_hi_2yr as int64) earn_count_wne_hi_2yr,
    safe_cast(earn_mdn_hi_2yr as float64) earn_mdn_hi_2yr,
    safe_cast(bbrr2_fed_comp_n as int64) bbrr2_fed_comp_n,
    safe_cast(bbrr2_fed_comp_dflt as string) bbrr2_fed_comp_dflt,
    safe_cast(bbrr2_fed_comp_dlnq as string) bbrr2_fed_comp_dlnq,
    safe_cast(bbrr2_fed_comp_fbr as string) bbrr2_fed_comp_fbr,
    safe_cast(bbrr2_fed_comp_dfr as string) bbrr2_fed_comp_dfr,
    safe_cast(bbrr2_fed_comp_noprog as string) bbrr2_fed_comp_noprog,
    safe_cast(bbrr2_fed_comp_makeprog as string) bbrr2_fed_comp_makeprog,
    safe_cast(bbrr2_fed_comp_paidinfull as string) bbrr2_fed_comp_paidinfull,
    safe_cast(bbrr2_fed_comp_discharge as string) bbrr2_fed_comp_discharge,
    safe_cast(bbrr3_fed_comp_n as int64) bbrr3_fed_comp_n,
    safe_cast(bbrr3_fed_comp_dflt as string) bbrr3_fed_comp_dflt,
    safe_cast(bbrr3_fed_comp_dlnq as string) bbrr3_fed_comp_dlnq,
    safe_cast(bbrr3_fed_comp_fbr as string) bbrr3_fed_comp_fbr,
    safe_cast(bbrr3_fed_comp_dfr as string) bbrr3_fed_comp_dfr,
    safe_cast(bbrr3_fed_comp_noprog as string) bbrr3_fed_comp_noprog,
    safe_cast(bbrr3_fed_comp_makeprog as string) bbrr3_fed_comp_makeprog,
    safe_cast(bbrr3_fed_comp_paidinfull as string) bbrr3_fed_comp_paidinfull,
    safe_cast(bbrr3_fed_comp_discharge as string) bbrr3_fed_comp_discharge,
    safe_cast(earn_count_pell_wne_1yr as int64) earn_count_pell_wne_1yr,
    safe_cast(earn_pell_wne_mdn_1yr as float64) earn_pell_wne_mdn_1yr,
    safe_cast(earn_count_nopell_wne_1yr as int64) earn_count_nopell_wne_1yr,
    safe_cast(earn_nopell_wne_mdn_1yr as float64) earn_nopell_wne_mdn_1yr,
    safe_cast(earn_count_male_wne_1yr as int64) earn_count_male_wne_1yr,
    safe_cast(earn_male_wne_mdn_1yr as float64) earn_male_wne_mdn_1yr,
    safe_cast(earn_count_nomale_wne_1yr as int64) earn_count_nomale_wne_1yr,
    safe_cast(earn_nomale_wne_mdn_1yr as float64) earn_nomale_wne_mdn_1yr,
    safe_cast(earn_count_ne_3yr as int64) earn_count_ne_3yr,
    safe_cast(earn_ne_mdn_3yr as float64) earn_ne_mdn_3yr,
    safe_cast(earn_count_wne_3yr as int64) earn_count_wne_3yr,
    safe_cast(earn_cntover150_3yr as int64) earn_cntover150_3yr,
    safe_cast(earn_count_pell_ne_3yr as int64) earn_count_pell_ne_3yr,
    safe_cast(earn_pell_ne_mdn_3yr as float64) earn_pell_ne_mdn_3yr,
    safe_cast(earn_count_nopell_ne_3yr as int64) earn_count_nopell_ne_3yr,
    safe_cast(earn_nopell_ne_mdn_3yr as float64) earn_nopell_ne_mdn_3yr,
    safe_cast(earn_count_male_ne_3yr as int64) earn_count_male_ne_3yr,
    safe_cast(earn_male_ne_mdn_3yr as float64) earn_male_ne_mdn_3yr,
    safe_cast(earn_count_nomale_ne_3yr as int64) earn_count_nomale_ne_3yr,
    safe_cast(earn_nomale_ne_mdn_3yr as float64) earn_nomale_ne_mdn_3yr,
    safe_cast(earn_count_nwne_1yr as int64) earn_count_nwne_1yr,
    safe_cast(earn_count_wne_1yr as int64) earn_count_wne_1yr,
    safe_cast(earn_mdn_1yr as float64) earn_mdn_1yr,
    safe_cast(earn_gt_threshold_1yr as int64) earn_gt_threshold_1yr,
    safe_cast(earn_count_high_cred_1yr as int64) earn_count_high_cred_1yr,
    safe_cast(earn_in_state_1yr as int64) earn_in_state_1yr,
    safe_cast(earn_count_nwne_4yr as int64) earn_count_nwne_4yr,
    safe_cast(earn_count_wne_4yr as int64) earn_count_wne_4yr,
    safe_cast(earn_mdn_4yr as float64) earn_mdn_4yr,
    safe_cast(earn_gt_threshold_4yr as int64) earn_gt_threshold_4yr,
    safe_cast(earn_count_pell_wne_4yr as int64) earn_count_pell_wne_4yr,
    safe_cast(earn_pell_wne_mdn_4yr as float64) earn_pell_wne_mdn_4yr,
    safe_cast(earn_count_nopell_wne_4yr as int64) earn_count_nopell_wne_4yr,
    safe_cast(earn_nopell_wne_mdn_4yr as float64) earn_nopell_wne_mdn_4yr,
    safe_cast(earn_count_male_wne_4yr as int64) earn_count_male_wne_4yr,
    safe_cast(earn_male_wne_mdn_4yr as float64) earn_male_wne_mdn_4yr,
    safe_cast(earn_count_nomale_wne_4yr as int64) earn_count_nomale_wne_4yr,
    safe_cast(earn_nomale_wne_mdn_4yr as float64) earn_nomale_wne_mdn_4yr,
    safe_cast(earn_count_high_cred_4yr as int64) earn_count_high_cred_4yr,
    safe_cast(earn_in_state_4yr as int64) earn_in_state_4yr,
    safe_cast(bbrr1_fed_comp_n as int64) bbrr1_fed_comp_n,
    safe_cast(bbrr1_fed_comp_dflt as string) bbrr1_fed_comp_dflt,
    safe_cast(bbrr1_fed_comp_dlnq as string) bbrr1_fed_comp_dlnq,
    safe_cast(bbrr1_fed_comp_fbr as string) bbrr1_fed_comp_fbr,
    safe_cast(bbrr1_fed_comp_dfr as string) bbrr1_fed_comp_dfr,
    safe_cast(bbrr1_fed_comp_noprog as string) bbrr1_fed_comp_noprog,
    safe_cast(bbrr1_fed_comp_makeprog as string) bbrr1_fed_comp_makeprog,
    safe_cast(bbrr1_fed_comp_paidinfull as string) bbrr1_fed_comp_paidinfull,
    safe_cast(bbrr1_fed_comp_discharge as string) bbrr1_fed_comp_discharge,
    safe_cast(bbrr4_fed_comp_n as int64) bbrr4_fed_comp_n,
    safe_cast(bbrr4_fed_comp_dflt as string) bbrr4_fed_comp_dflt,
    safe_cast(bbrr4_fed_comp_dlnq as string) bbrr4_fed_comp_dlnq,
    safe_cast(bbrr4_fed_comp_fbr as string) bbrr4_fed_comp_fbr,
    safe_cast(bbrr4_fed_comp_dfr as string) bbrr4_fed_comp_dfr,
    safe_cast(bbrr4_fed_comp_noprog as string) bbrr4_fed_comp_noprog,
    safe_cast(bbrr4_fed_comp_makeprog as string) bbrr4_fed_comp_makeprog,
    safe_cast(bbrr4_fed_comp_paidinfull as string) bbrr4_fed_comp_paidinfull,
    safe_cast(bbrr4_fed_comp_discharge as string) bbrr4_fed_comp_discharge,
    safe_cast(distance_education as string) distance_education,
    safe_cast(earn_count_nwne_5yr as int64) earn_count_nwne_5yr,
    safe_cast(earn_count_wne_5yr as int64) earn_count_wne_5yr,
    safe_cast(earn_mdn_5yr as float64) earn_mdn_5yr,
    safe_cast(earn_gt_threshold_5yr as int64) earn_gt_threshold_5yr,
    safe_cast(earn_count_pell_wne_5yr as int64) earn_count_pell_wne_5yr,
    safe_cast(earn_pell_wne_mdn_5yr as float64) earn_pell_wne_mdn_5yr,
    safe_cast(earn_count_nopell_wne_5yr as int64) earn_count_nopell_wne_5yr,
    safe_cast(earn_nopell_wne_mdn_5yr as float64) earn_nopell_wne_mdn_5yr,
    safe_cast(earn_count_male_wne_5yr as int64) earn_count_male_wne_5yr,
    safe_cast(earn_male_wne_mdn_5yr as float64) earn_male_wne_mdn_5yr,
    safe_cast(earn_count_nomale_wne_5yr as int64) earn_count_nomale_wne_5yr,
    safe_cast(earn_nomale_wne_mdn_5yr as float64) earn_nomale_wne_mdn_5yr,
    safe_cast(earn_count_high_cred_5yr as int64) earn_count_high_cred_5yr,
    safe_cast(earn_in_state_5yr as int64) earn_in_state_5yr,
    safe_cast(earn_count_wne_4yr_nat as int64) earn_count_wne_4yr_nat,
    safe_cast(earn_mdn_4yr_nat as float64) earn_mdn_4yr_nat,
    safe_cast(earn_p25_4yr_nat as float64) earn_p25_4yr_nat,
    safe_cast(earn_p75_4yr_nat as float64) earn_p75_4yr_nat
from
    {{ set_datalake_project("us_ed_college_scorecard_staging.field_of_study") }}
    as t
