---
version: 2
models:
  - name: br_denatran_frota__municipio_tipo
    description: Frota de veículos por município e tipo
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [ano, mes, id_municipio, tipo_veiculo]
          config:
            where: __most_recent_year_month__
      - not_null_proportion_multiple_columns:
          at_least: 0.05
          config:
            # where: __most_recent_year_month__
    columns:
      - name: ano
        description: Ano
        tests:
          - relationships:
              to: ref('br_bd_diretorios_data_tempo__data')
              field: ano
              config:
                where: __most_recent_year_month__
      - name: mes
        description: Mês
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__municipio')
              field: id_municipio
              config:
                where: __most_recent_year_month__
      - name: sigla_uf
        description: Sigla da Unidade da Federação
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__uf')
              field: sigla
              config:
                where: __most_recent_year_month__
      - name: tipo_veiculo
        description: Tipo de veículo
      - name: quantidade
        description: Quantidade de veículos
  - name: br_denatran_frota__uf_tipo
    description: Frota de veículos por Unidade da Federação (UF) e tipo
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [ano, mes, sigla_uf, tipo_veiculo]
          config:
            where: __most_recent_year_month__
      - not_null_proportion_multiple_columns:
          at_least: 0.05
          config:
            # where: __most_recent_year_month__
    columns:
      - name: ano
        description: Ano
      - name: mes
        description: Mês
      - name: sigla_uf
        description: Sigla da Unidade da Federação
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__uf')
              field: sigla
              config:
                where: __most_recent_year_month__
      - name: tipo_veiculo
        description: Tipo de veículo
      - name: quantidade
        description: Quantidade de veículos
