-- Generated by models/world_noaa_ghcn/code/gen_dbt.py from
-- code/architecture/dicionario.csv. Edit the generator, not this file.
{{
    config(
        schema="world_noaa_ghcn",
        alias="dicionario",
        materialized="table",
    )
}}


select
    safe_cast(id_tabela as string) id_tabela,
    safe_cast(nome_coluna as string) nome_coluna,
    safe_cast(chave as string) chave,
    safe_cast(cobertura_temporal as string) cobertura_temporal,
    safe_cast(valor as string) valor
from {{ set_datalake_project("world_noaa_ghcn_staging.dicionario") }} as t
