-- Generated by models/world_noaa_ghcn/code/gen_dbt.py from
-- code/architecture/station.csv. Edit the generator, not this file.
{{
    config(
        schema="world_noaa_ghcn",
        alias="station",
        materialized="table",
    )
}}


select
    safe_cast(station_id as string) station_id,
    safe_cast(country_code as string) country_code,
    safe_cast(country_name as string) country_name,
    safe_cast(network_code as string) network_code,
    safe_cast(state_code as string) state_code,
    safe_cast(state_name as string) state_name,
    safe_cast(station_name as string) station_name,
    safe_cast(latitude as float64) latitude,
    safe_cast(longitude as float64) longitude,
    safe_cast(elevation as float64) elevation,
    safe_cast(gsn_flag as string) gsn_flag,
    safe_cast(hcn_crn_flag as string) hcn_crn_flag,
    safe_cast(wmo_id as string) wmo_id
from {{ set_datalake_project("world_noaa_ghcn_staging.station") }} as t
