-- Generated by models/world_noaa_ghcn/code/gen_dbt.py from
-- code/architecture/observation.csv. Edit the generator, not this file.
{{
    config(
        schema="world_noaa_ghcn",
        alias="observation",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 1763, "end": 2031, "interval": 1},
        },
        cluster_by=["station_id", "element"],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(station_id as string) station_id,
    safe_cast(date as date) date,
    safe_cast(element as string) element,
    safe_cast(value as float64) value,
    safe_cast(measurement_unit as string) measurement_unit,
    safe_cast(measurement_flag as string) measurement_flag,
    safe_cast(quality_flag as string) quality_flag,
    safe_cast(source_flag as string) source_flag,
    safe_cast(observation_time as string) observation_time
from {{ set_datalake_project("world_noaa_ghcn_staging.observation") }} as t
