-- Generated by models/world_noaa_ghcn/code/gen_dbt.py from
-- code/architecture/station_element_inventory.csv. Edit the generator, not this file.
{{
    config(
        schema="world_noaa_ghcn",
        alias="station_element_inventory",
        materialized="table",
    )
}}


select
    safe_cast(station_id as string) station_id,
    safe_cast(element as string) element,
    safe_cast(first_year as int64) first_year,
    safe_cast(last_year as int64) last_year
from
    {{ set_datalake_project("world_noaa_ghcn_staging.station_element_inventory") }} as t
