"""sinpatinhas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lpK3G-uhSByQqoWuaSRUbhD7V2z9MlS1
"""

# pip install cacimbao

import basedosdados as bd
import cacimbao  # type: ignore
import polars as pl

dados = cacimbao.download_dataset("sinpatinhas")

dados = dados.rename(
    {
        "corpelagem": "cor_pelagem",
        "no_municipio": "nome",
        "datacadastro": "data_cadastro",
        "uf": "sigla_uf",
    }
)

billing_id = "basedosdados-dev"

query = """
  SELECT
    dados.id_municipio as id_municipio,
    dados.nome as nome,
    dados.sigla_uf as sigla_uf
FROM `basedosdados.br_bd_diretorios_brasil.municipio` AS dados
"""

municipios = bd.read_sql(query=query, billing_project_id=billing_id)

municipios_pl = pl.from_pandas(municipios)

dados = dados.join(
    municipios_pl.select(["id_municipio", "nome", "sigla_uf"]),
    on=["nome", "sigla_uf"],
    how="inner",
)

dados = dados.with_columns(
    pl.int_range(1, dados.height + 1).shuffle().alias("id_animal")
).select(
    "data_cadastro",
    "id_animal",
    "id_municipio",
    "especie",
    "idade",
    "sexo",
    "cor_pelagem",
)

dados.write_parquet("output/data.parquet")
