"""Architecture tables for us_stanford_dime (DIME v4.0).

The architecture is the single source of truth for column names, types,
descriptions and ordering. Cleaning, dbt models and backend metadata are all
generated from it.

Column order follows the Data Basis style manual: partition columns first,
then identifiers, then descriptive columns. Names are English because the
data and its documentation are English (see .claude/rules/data-basis-style.md),
and identifiers take the ``_id`` suffix rather than the Portuguese ``id_``
prefix.

Types follow arithmetic meaning, not source storage: a column is INT64/FLOAT64
only when summing or averaging it is meaningful and it has a real measurement
unit. Coded values (party codes, transaction codes, 0/1 flags) are STRING and
carry ``covered_by_dictionary = yes`` when the ``dicionario`` table defines
their labels.

Run ``python architecture.py`` to (re)write the CSVs under ``architecture/``.
"""

from __future__ import annotations

import csv
from pathlib import Path

ARCH_DIR = Path(__file__).resolve().parent / "architecture"

HEADER = [
    "name",
    "bigquery_type",
    "description",
    "temporal_coverage",
    "covered_by_dictionary",
    "directory_column",
    "measurement_unit",
    "has_sensitive_data",
    "observations",
    "original_name",
]

# Column tuple: (name, type, description, dict, directory, unit, sensitive,
#                observations, original_name)
Col = tuple[str, str, str, str, str, str, str, str, str]

YEAR_DIR = "br_bd_diretorios_data_tempo.ano:ano"

# --------------------------------------------------------------------------
# contribution — one row per itemized contribution record
# --------------------------------------------------------------------------

CONTRIBUTION: list[Col] = [
    # partition
    (
        "cycle",
        "INT64",
        "Two-year election cycle during which the contribution was recorded",
        "",
        "no",
        YEAR_DIR,
        "year",
        "no",
        "Partition column. Cycles are even years; the 1980 cycle covers 1979-1980",
        "cycle",
    ),
    # identifiers
    (
        "transaction_id",
        "STRING",
        "Unique identifier of the contribution record, assigned by DIME",
        "",
        "no",
        "",
        "",
        "no",
        "Primary key within a cycle",
        "transaction.id",
    ),
    (
        "contributor_id",
        "STRING",
        "Unique identifier of the contributor, assigned by DIME entity resolution",
        "",
        "no",
        "",
        "",
        "no",
        "Stable across election cycles and levels of government; joins to the contributor table",
        "bonica.cid",
    ),
    (
        "recipient_id",
        "STRING",
        "Unique identifier of the recipient candidate or committee, assigned by DIME",
        "",
        "no",
        "",
        "",
        "no",
        "Stable across cycles, offices and levels of government; joins to the recipient table",
        "bonica.rid",
    ),
    (
        "efec_transaction_id_original",
        "STRING",
        "Original transaction identifier from the FEC electronic filing",
        "",
        "no",
        "",
        "",
        "no",
        "Empty for state and local records",
        "efec.transaction.id.orig",
    ),
    (
        "efec_committee_id_original",
        "STRING",
        "Original committee identifier from the FEC electronic filing",
        "",
        "no",
        "",
        "",
        "no",
        "Empty for state and local records",
        "efec.comid.orig",
    ),
    (
        "back_reference_transaction_id",
        "STRING",
        "Identifier of an earlier record in the database that this record repeats",
        "",
        "no",
        "",
        "",
        "no",
        "Points at transaction_id; use it to drop duplicate entries",
        "bk.ref.transaction.id",
    ),
    # descriptive
    (
        "date",
        "DATE",
        "Date on which the contribution was transacted",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "date",
    ),
    (
        "amount",
        "FLOAT64",
        "Dollar amount of the contribution",
        "",
        "no",
        "",
        "USD",
        "no",
        "Nominal dollars, not adjusted for inflation. Negative values occur on refunds and corrections",
        "amount",
    ),
    (
        "transaction_type",
        "STRING",
        "FEC code for the type of transaction",
        "",
        "yes",
        "",
        "",
        "no",
        "Non-FEC codes 15S, 15L, 15PD, PF and PFR are assigned by DIME for state and local records",
        "transaction.type",
    ),
    (
        "election_type",
        "STRING",
        "Type of election the contribution was made for",
        "",
        "yes",
        "",
        "",
        "no",
        "",
        "election.type",
    ),
    (
        "seat",
        "STRING",
        "Elected office sought by the recipient",
        "",
        "no",
        "",
        "",
        "no",
        "Readable labels of the form level:office, for example federal:house or state:lower. Offices prefixed 'local:' are not standardized, so the value space is open-ended (139 distinct values observed)",
        "seat",
    ),
    (
        "contributor_name",
        "STRING",
        "Full name of the contributor, cleaned and standardized by DIME",
        "",
        "no",
        "",
        "",
        "yes",
        "Last name first; suffix and title removed",
        "contributor.name",
    ),
    (
        "contributor_last_name",
        "STRING",
        "Last name of the contributor",
        "",
        "no",
        "",
        "",
        "yes",
        "Empty for committees and organizations",
        "contributor.lname",
    ),
    (
        "contributor_first_name",
        "STRING",
        "First name of the contributor",
        "",
        "no",
        "",
        "",
        "yes",
        "Empty for committees and organizations",
        "contributor.fname",
    ),
    (
        "contributor_middle_name",
        "STRING",
        "Middle name or initial of the contributor",
        "",
        "no",
        "",
        "",
        "yes",
        "",
        "contributor.mname",
    ),
    (
        "contributor_suffix",
        "STRING",
        "Name suffix of the contributor",
        "",
        "no",
        "",
        "",
        "yes",
        "For example Jr., Sr., III",
        "contributor.suffix",
    ),
    (
        "contributor_title",
        "STRING",
        "Title of the contributor",
        "",
        "no",
        "",
        "",
        "yes",
        "For example Mr., Mrs., Dr., Esq.",
        "contributor.title",
    ),
    (
        "contributor_full_first_name",
        "STRING",
        "First name, middle name, suffix and title of the contributor concatenated",
        "",
        "no",
        "",
        "",
        "yes",
        "",
        "contributor.ffname",
    ),
    (
        "contributor_type",
        "STRING",
        "Whether the contributor is an individual or an organization",
        "",
        "yes",
        "",
        "",
        "no",
        "",
        "contributor.type",
    ),
    (
        "contributor_gender",
        "STRING",
        "Gender of the contributor",
        "",
        "yes",
        "",
        "",
        "yes",
        "Imputed by DIME from first-name gender ratios reported by the U.S. Census and from gendered titles; not self-reported",
        "contributor.gender",
    ),
    (
        "contributor_address",
        "STRING",
        "Street address reported by the contributor",
        "",
        "no",
        "",
        "",
        "yes",
        "",
        "contributor.address",
    ),
    (
        "contributor_city",
        "STRING",
        "City reported by the contributor",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "contributor.city",
    ),
    (
        "contributor_state",
        "STRING",
        "Two-letter state abbreviation reported by the contributor",
        "",
        "no",
        "",
        "",
        "no",
        "Includes territories and foreign codes, so it is not restricted to the 50 states plus DC and is not linked to the state directory",
        "contributor.state",
    ),
    (
        "contributor_zipcode",
        "STRING",
        "ZIP code reported by the contributor",
        "",
        "no",
        "",
        "",
        "no",
        "Five or nine digits depending on the filing",
        "contributor.zipcode",
    ),
    (
        "contributor_district",
        "STRING",
        "Congressional district the contributor's geocode falls in",
        "",
        "no",
        "",
        "",
        "no",
        "Two-letter state abbreviation followed by the district number. District boundaries are those in force for the cycle, so the code is not comparable across redistricting cycles",
        "contributor.district",
    ),
    (
        "census_tract_id",
        "STRING",
        "Census tract the contributor's geocode falls in",
        "",
        "no",
        "",
        "",
        "no",
        "Eleven-digit GEOID. Tract vintage follows the decennial boundaries in force for the cycle, so it is not linked to a single-vintage census tract directory",
        "censustract",
    ),
    (
        "latitude",
        "FLOAT64",
        "Latitude of the contributor's geocoded address",
        "",
        "no",
        "",
        "degree",
        "yes",
        "Geocoded with the Pelias geocoder; consistent per contributor_id across records with varying address completeness",
        "latitude",
    ),
    (
        "longitude",
        "FLOAT64",
        "Longitude of the contributor's geocoded address",
        "",
        "no",
        "",
        "degree",
        "yes",
        "Geocoded with the Pelias geocoder",
        "longitude",
    ),
    (
        "gis_confidence",
        "FLOAT64",
        "Confidence in the accuracy of the geocoded coordinates, from 0 to 1",
        "",
        "no",
        "",
        "index",
        "no",
        "",
        "gis.confidence",
    ),
    (
        "contributor_occupation",
        "STRING",
        "Occupation reported by the contributor",
        "",
        "no",
        "",
        "",
        "no",
        "Cleaned and standardized by DIME",
        "contributor.occupation",
    ),
    (
        "contributor_employer",
        "STRING",
        "Employer reported by the contributor",
        "",
        "no",
        "",
        "",
        "no",
        "Cleaned and standardized by DIME",
        "contributor.employer",
    ),
    (
        "occupation_standardized",
        "STRING",
        "Industry category the reported occupation was mapped to",
        "",
        "no",
        "",
        "",
        "no",
        "Assigned by DIME; populated for a minority of records",
        "occ.standardized",
    ),
    (
        "is_corporation",
        "STRING",
        "Whether the contributing committee is a corporation or trade organization",
        "",
        "no",
        "",
        "",
        "no",
        "Applies to committees only; these donors are excluded from the CFscore estimation",
        "is.corp",
    ),
    (
        "recipient_name",
        "STRING",
        "Name of the recipient candidate or committee",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "recipient.name",
    ),
    (
        "recipient_party",
        "STRING",
        "Party of the recipient",
        "",
        "yes",
        "",
        "",
        "no",
        "Match against the recipient table for more detailed party codings",
        "recipient.party",
    ),
    (
        "recipient_type",
        "STRING",
        "Whether the recipient is a candidate or a committee",
        "",
        "yes",
        "",
        "",
        "no",
        "",
        "recipient.type",
    ),
    (
        "recipient_state",
        "STRING",
        "Two-letter state abbreviation of the recipient",
        "",
        "no",
        "",
        "",
        "no",
        "Not linked to the state directory because it includes non-state codes",
        "recipient.state",
    ),
    (
        "contributor_cfscore",
        "FLOAT64",
        "Common-space CFscore of the contributor",
        "",
        "no",
        "",
        "score_point",
        "no",
        "Ideal point estimated from the contributor's giving; negative is liberal, positive is conservative. Repeated on every record of the same contributor",
        "contributor.cfscore",
    ),
    (
        "candidate_cfscore",
        "FLOAT64",
        "Common-space CFscore of the recipient",
        "",
        "no",
        "",
        "score_point",
        "no",
        "Ideal point estimated from the donations the recipient received; negative is liberal, positive is conservative",
        "candidate.cfscore",
    ),
    (
        "excluded_from_scaling",
        "STRING",
        "Whether the record was excluded from the CFscore estimation",
        "",
        "yes",
        "",
        "",
        "no",
        "Stored as 0 or 1 in the source",
        "excluded.from.scaling",
    ),
    (
        "efec_memo",
        "STRING",
        "Memo field from the FEC electronic filing",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "efec.memo",
    ),
    (
        "efec_memo2",
        "STRING",
        "Auxiliary memo field from the FEC electronic filing",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "efec.memo2",
    ),
    (
        "efec_organization_original",
        "STRING",
        "Original recipient name from the FEC electronic filing",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "efec.org.orig",
    ),
    (
        "efec_form_type",
        "STRING",
        "Form type of the FEC electronic filing the record came from",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "efec.form.type",
    ),
]

# --------------------------------------------------------------------------
# recipient — one row per candidate or committee per election cycle
# --------------------------------------------------------------------------

RECIPIENT: list[Col] = [
    # partition
    (
        "cycle",
        "INT64",
        "Two-year election cycle the entry refers to",
        "",
        "no",
        YEAR_DIR,
        "year",
        "no",
        "Partition column",
        "cycle",
    ),
    # identifiers
    (
        "recipient_id",
        "STRING",
        "Unique identifier of the candidate or committee, assigned by DIME",
        "",
        "no",
        "",
        "",
        "no",
        "Stable across cycles, offices and levels of government; joins to the contribution table",
        "bonica.rid",
    ),
    (
        "contributor_id",
        "STRING",
        "Identifier of the same person in the contributor database",
        "",
        "no",
        "",
        "",
        "no",
        "Links a candidate to their own personal contributions. Partially populated: a missing value does not mean the candidate made no contributions",
        "bonica.cid",
    ),
    (
        "election",
        "STRING",
        "Election cycle prefixed by the two-letter state code",
        "",
        "no",
        "",
        "",
        "no",
        "Federal candidates take 'fd' as the state code, for example fd1980",
        "election",
    ),
    (
        "icpsr_id",
        "STRING",
        "Adjusted ICPSR legislator identifier with the election cycle appended",
        "",
        "no",
        "",
        "",
        "no",
        "Row identifier. Candidates who never served in Congress get identifiers derived from their FEC, NIMSP or state agency candidate identifier",
        "ICPSR",
    ),
    (
        "icpsr2_id",
        "STRING",
        "Adjusted ICPSR legislator identifier without the cycle suffix",
        "",
        "no",
        "",
        "",
        "no",
        "Party switchers are assigned a new value after switching",
        "ICPSR2",
    ),
    (
        "candidate_id",
        "STRING",
        "Candidate identifier assigned by the FEC or the state reporting agency",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "Cand.ID",
    ),
    (
        "fec_committee_id",
        "STRING",
        "Committee identifier assigned by the FEC or the state reporting agency",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "FEC.ID",
    ),
    (
        "nimsp_id",
        "STRING",
        "Candidate identifier assigned by CRP/NIMSP",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "NID",
    ),
    (
        "icpsr_id_before_switch",
        "STRING",
        "ICPSR identifier held before switching parties",
        "",
        "no",
        "",
        "",
        "no",
        "Populated for party switchers only",
        "before.switch.ICPSR",
    ),
    (
        "icpsr_id_after_switch",
        "STRING",
        "ICPSR identifier held after switching parties",
        "",
        "no",
        "",
        "",
        "no",
        "Populated for party switchers only",
        "after.switch.ICPSR",
    ),
    # descriptive
    (
        "fec_year",
        "INT64",
        "Year of the election the campaign targets, as listed by the FEC",
        "",
        "no",
        YEAR_DIR,
        "year",
        "no",
        "Can be later than the cycle, as for senators fundraising during their first four years in office",
        "fecyear",
    ),
    (
        "name",
        "STRING",
        "Name of the candidate or committee",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "name",
    ),
    (
        "last_name",
        "STRING",
        "Last name of the candidate",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "lname",
    ),
    (
        "first_name",
        "STRING",
        "First name of the candidate",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "fname",
    ),
    (
        "middle_name",
        "STRING",
        "Middle name of the candidate",
        "",
        "no",
        "",
        "",
        "no",
        "The source codebook mislabels this field as the first name",
        "mname",
    ),
    (
        "full_first_name",
        "STRING",
        "First name, middle name, suffix and title of the candidate concatenated",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "ffname",
    ),
    (
        "title",
        "STRING",
        "Title of the candidate",
        "",
        "no",
        "",
        "",
        "no",
        "For example Mr., Mrs., Dr., Esq.",
        "title",
    ),
    (
        "suffix",
        "STRING",
        "Name suffix of the candidate",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "suffix",
    ),
    (
        "candidate_gender",
        "STRING",
        "Gender of the candidate",
        "",
        "yes",
        "",
        "",
        "no",
        "Imputed for all candidates except those who served in Congress. Four rows carry the value with literal quote marks, an escaping artefact left in the source",
        "cand.gender",
    ),
    (
        "party",
        "STRING",
        "Party of the candidate or committee",
        "",
        "yes",
        "",
        "",
        "no",
        "",
        "party",
    ),
    (
        "party_original",
        "STRING",
        "Party held before a party switch",
        "",
        "yes",
        "",
        "",
        "no",
        "Populated for party switchers only",
        "party.orig",
    ),
    (
        "state",
        "STRING",
        "Two-letter state abbreviation of the candidate or committee",
        "",
        "no",
        "",
        "",
        "no",
        "Not linked to the state directory because it includes non-state codes",
        "state",
    ),
    (
        "seat",
        "STRING",
        "Office sought by the candidate",
        "",
        "no",
        "",
        "",
        "no",
        "Committees are listed as federal:committee or state:committee",
        "seat",
    ),
    (
        "district",
        "STRING",
        "District code of the seat sought",
        "",
        "no",
        "",
        "",
        "no",
        "Two-letter state code followed by the district number; Senate candidates take 'S' followed by the year the seat is up",
        "district",
    ),
    (
        "district_cycle",
        "STRING",
        "District and cycle the candidate contested",
        "",
        "no",
        "",
        "",
        "no",
        "For example 1980_MS_S",
        "distcyc",
    ),
    (
        "incumbency_status",
        "STRING",
        "Incumbency status of the candidate",
        "",
        "yes",
        "",
        "",
        "no",
        "",
        "ico.status",
    ),
    (
        "recipient_cfscore",
        "FLOAT64",
        "Common-space CFscore of the recipient",
        "",
        "no",
        "",
        "score_point",
        "no",
        "Ideal point estimated from donations received; negative is liberal, positive is conservative. Constant across cycles for a recipient",
        "recipient.cfscore",
    ),
    (
        "recipient_cfscore_dynamic",
        "FLOAT64",
        "Cycle-specific CFscore of the recipient",
        "",
        "no",
        "",
        "score_point",
        "no",
        "Re-estimated each cycle holding contributor scores constant",
        "recipient.cfscore.dyn",
    ),
    (
        "contributor_cfscore",
        "FLOAT64",
        "CFscore of the recipient estimated from their own personal donations",
        "",
        "no",
        "",
        "score_point",
        "no",
        "",
        "contributor.cfscore",
    ),
    (
        "dw_dime",
        "FLOAT64",
        "DW-DIME score of the recipient",
        "",
        "no",
        "",
        "score_point",
        "no",
        "Roll-call score inferred from contributions by supervised machine learning (Bonica 2018)",
        "dwdime",
    ),
    (
        "composite_score",
        "FLOAT64",
        "Composite ideological score of the recipient",
        "",
        "no",
        "",
        "score_point",
        "no",
        "Combines contributions, roll-call votes and other sources by multiple overimputation; new in version 4.0",
        "composite.score",
    ),
    (
        "dw_nominate_1",
        "FLOAT64",
        "First-dimension common-space DW-NOMINATE score",
        "",
        "no",
        "",
        "score_point",
        "no",
        "From voteview.com, based on a joint scaling of the 1st to 117th Congresses",
        "dwnom1",
    ),
    (
        "dw_nominate_2",
        "FLOAT64",
        "Second-dimension common-space DW-NOMINATE score",
        "",
        "no",
        "",
        "score_point",
        "no",
        "From voteview.com",
        "dwnom2",
    ),
    (
        "dw_nominate_1_period",
        "FLOAT64",
        "First-dimension Nokken-Poole period-specific DW-NOMINATE score",
        "",
        "no",
        "",
        "score_point",
        "no",
        "From voteview.com. House and Senate are scaled separately, so the two chambers are not directly comparable",
        "ps.dwnom1",
    ),
    (
        "dw_nominate_2_period",
        "FLOAT64",
        "Second-dimension Nokken-Poole period-specific DW-NOMINATE score",
        "",
        "no",
        "",
        "score_point",
        "no",
        "From voteview.com",
        "ps.dwnom2",
    ),
    (
        "irt_cfscore",
        "FLOAT64",
        "Ideal point of the recipient from an IRT count model applied to PAC data",
        "",
        "no",
        "",
        "score_point",
        "no",
        "See Bonica (2013)",
        "irt.cfscore",
    ),
    (
        "number_of_givers",
        "INT64",
        "Number of distinct donors who gave to the recipient during the cycle",
        "",
        "no",
        "",
        "person",
        "no",
        "",
        "num.givers",
    ),
    (
        "number_of_givers_total",
        "INT64",
        "Number of distinct donors who gave to the recipient over their whole career",
        "",
        "no",
        "",
        "person",
        "no",
        "",
        "num.givers.total",
    ),
    (
        "total_receipts",
        "FLOAT64",
        "Total contributions raised during the cycle",
        "",
        "no",
        "",
        "USD",
        "no",
        "Nominal dollars",
        "total.receipts",
    ),
    (
        "total_disbursements",
        "FLOAT64",
        "Total campaign disbursements during the cycle",
        "",
        "no",
        "",
        "USD",
        "no",
        "Nominal dollars",
        "total.disbursements",
    ),
    (
        "total_individual_contributions",
        "FLOAT64",
        "Total itemized contributions from individuals raised during the cycle",
        "",
        "no",
        "",
        "USD",
        "no",
        "Nominal dollars",
        "total.indiv.contribs",
    ),
    (
        "total_unitemized",
        "FLOAT64",
        "Total unitemized contributions from individuals raised during the cycle",
        "",
        "no",
        "",
        "USD",
        "no",
        "Nominal dollars",
        "total.unitemized",
    ),
    (
        "total_pac_contributions",
        "FLOAT64",
        "Total raised from PACs and other committees during the cycle",
        "",
        "no",
        "",
        "USD",
        "no",
        "Nominal dollars",
        "total.pac.contribs",
    ),
    (
        "total_party_contributions",
        "FLOAT64",
        "Total raised from party committees during the cycle",
        "",
        "no",
        "",
        "USD",
        "no",
        "Nominal dollars",
        "total.party.contribs",
    ),
    (
        "total_contributions_from_candidate",
        "FLOAT64",
        "Total raised from the candidate's own contributions during the cycle",
        "",
        "no",
        "",
        "USD",
        "no",
        "Nominal dollars",
        "total.contribs.from.candidate",
    ),
    (
        "independent_expenditure_support",
        "FLOAT64",
        "Total independent expenditures made to support the candidate",
        "",
        "no",
        "",
        "USD",
        "no",
        "Nominal dollars",
        "ind.exp.support",
    ),
    (
        "independent_expenditure_oppose",
        "FLOAT64",
        "Total independent expenditures made to oppose the candidate",
        "",
        "no",
        "",
        "USD",
        "no",
        "Nominal dollars",
        "ind.exp.oppose",
    ),
    (
        "primary_vote_share",
        "FLOAT64",
        "Vote share won in the primary election, as reported by the FEC",
        "",
        "no",
        "",
        "percent",
        "no",
        "Coded for federal congressional candidates only",
        "prim.vote.pct",
    ),
    (
        "primary_winner",
        "STRING",
        "Outcome of the primary election",
        "",
        "yes",
        "",
        "",
        "no",
        "Coded for federal congressional candidates only",
        "pwinner",
    ),
    (
        "general_vote_share",
        "FLOAT64",
        "Vote share won in the general election, as reported by the FEC",
        "",
        "no",
        "",
        "percent",
        "no",
        "",
        "gen.vote.pct",
    ),
    (
        "general_winner",
        "STRING",
        "Outcome of the general election",
        "",
        "yes",
        "",
        "",
        "no",
        "Federal outcomes come from the FEC, state outcomes from NIMSP",
        "gwinner",
    ),
    (
        "special_election_status",
        "STRING",
        "Outcome of the special election, as coded by the FEC",
        "",
        "yes",
        "",
        "",
        "no",
        "The source uses '?' for an unrecorded outcome, which is kept rather than nulled",
        "s.elec.stat",
    ),
    (
        "runoff_election_status",
        "STRING",
        "Outcome of the run-off election, as coded by the FEC",
        "",
        "yes",
        "",
        "",
        "no",
        "The source uses '?' for an unrecorded outcome, which is kept rather than nulled",
        "r.elec.stat",
    ),
    (
        "district_presidential_vote_share",
        "FLOAT64",
        "Two-party vote share won by the Democratic presidential nominee in the district",
        "",
        "no",
        "",
        "percent",
        "no",
        "Measured at the most recent or concurrent presidential election",
        "district.pres.vs",
    ),
    (
        "fec_candidate_status",
        "STRING",
        "Status of the candidate's campaign as assigned by the FEC",
        "",
        "yes",
        "",
        "",
        "no",
        "",
        "fec.cand.status",
    ),
    (
        "recipient_type",
        "STRING",
        "Whether the recipient is a candidate or a committee",
        "",
        "yes",
        "",
        "",
        "no",
        "",
        "recipient.type",
    ),
    (
        "interest_group_category",
        "STRING",
        "FEC interest group category of the committee",
        "",
        "yes",
        "",
        "",
        "no",
        "",
        "igcat",
    ),
    (
        "committee_type",
        "STRING",
        "FEC code for the type of committee",
        "",
        "yes",
        "",
        "",
        "no",
        "",
        "comtype",
    ),
    (
        "included_in_scaling",
        "STRING",
        "Whether the recipient met the requirements for inclusion in the CFscore estimation",
        "",
        "yes",
        "",
        "",
        "no",
        "Stored as 0 or 1 in the source. Recipients with value 0 are absent from the smaller dime_recipients file",
        "included_in_scaling",
    ),
    (
        "nimsp_party",
        "STRING",
        "Party name assigned by NIMSP",
        "",
        "no",
        "",
        "",
        "no",
        "Spelled-out party names, not codes, and not normalized at source: DEMOCRATIC and DEMOCRAT both occur",
        "nimsp.party",
    ),
    (
        "nimsp_incumbency_status",
        "STRING",
        "Incumbency status assigned by NIMSP",
        "",
        "yes",
        "",
        "",
        "no",
        "",
        "nimsp.candidate.ICO.code",
    ),
    (
        "nimsp_district",
        "STRING",
        "District number assigned by NIMSP",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "nimsp.district",
    ),
    (
        "nimsp_office",
        "STRING",
        "State office sought, as coded by NIMSP",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "nimsp.office",
    ),
    (
        "nimsp_candidate_status",
        "STRING",
        "Election outcome as recorded by NIMSP",
        "",
        "no",
        "",
        "",
        "no",
        "Readable phrases, not normalized at source: both 'Lost - General Election' and 'Lost-General' occur",
        "nimsp.candidate.status",
    ),
]

# --------------------------------------------------------------------------
# contributor — one row per donor
# --------------------------------------------------------------------------

CONTRIBUTOR: list[Col] = [
    (
        "contributor_id",
        "STRING",
        "Unique identifier of the contributor, assigned by DIME entity resolution",
        "",
        "no",
        "",
        "",
        "no",
        "Joins to the contribution and contributor_cycle tables",
        "bonica.cid",
    ),
    (
        "contributor_type",
        "STRING",
        "Whether the contributor is an individual or an organization",
        "",
        "yes",
        "",
        "",
        "no",
        "",
        "contributor.type",
    ),
    (
        "contributor_gender",
        "STRING",
        "Gender of the contributor",
        "",
        "yes",
        "",
        "",
        "yes",
        "Imputed by DIME from first-name gender ratios and gendered titles; not self-reported",
        "contributor.gender",
    ),
    (
        "is_corporation",
        "STRING",
        "Whether the contributor is a corporation or trade organization",
        "",
        "no",
        "",
        "",
        "no",
        "Applies to committees only; these donors are excluded from the CFscore estimation",
        "is.corp",
    ),
    (
        "contributor_cfscore",
        "FLOAT64",
        "Common-space CFscore of the contributor",
        "",
        "no",
        "",
        "score_point",
        "no",
        "Negative is liberal, positive is conservative. Donors who gave to a single recipient are assigned that recipient's ideal point",
        "contributor.cfscore",
    ),
    (
        "is_projected",
        "STRING",
        "Whether the contributor was projected onto the space rather than estimated within it",
        "",
        "yes",
        "",
        "",
        "no",
        "Stored as 0 or 1 in the source. Value 1 covers corporate and trade-affiliated committees and donors who gave to a single recipient, whose scores are less reliable",
        "is.projected",
    ),
    (
        "number_distinct_recipients",
        "INT64",
        "Number of distinct recipients in the scaling that received contributions from the donor",
        "",
        "no",
        "",
        "unit",
        "no",
        "The number of observations behind the ideal point. Eight or more distinct recipients is typically enough for a reliable estimate",
        "num.distinct",
    ),
    (
        "first_cycle_active",
        "INT64",
        "First election cycle in which the donor was recorded as active",
        "",
        "no",
        YEAR_DIR,
        "year",
        "no",
        "",
        "first_cycle_active",
    ),
    (
        "last_cycle_active",
        "INT64",
        "Last election cycle in which the donor was recorded as active",
        "",
        "no",
        YEAR_DIR,
        "year",
        "no",
        "",
        "last_cycle_active",
    ),
    (
        "most_recent_name",
        "STRING",
        "Name reported by the contributor on their most recent record",
        "",
        "no",
        "",
        "",
        "yes",
        "",
        "most.recent.contributor.name",
    ),
    (
        "most_recent_address",
        "STRING",
        "Street address reported by the contributor on their most recent record",
        "",
        "no",
        "",
        "",
        "yes",
        "",
        "most.recent.contributor.address",
    ),
    (
        "most_recent_city",
        "STRING",
        "City reported by the contributor on their most recent record",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "most.recent.contributor.city",
    ),
    (
        "most_recent_state",
        "STRING",
        "Two-letter state abbreviation reported on the most recent record",
        "",
        "no",
        "",
        "",
        "no",
        "Includes territories and foreign codes, so it is not linked to the state directory",
        "most.recent.contributor.state",
    ),
    (
        "most_recent_zipcode",
        "STRING",
        "ZIP code reported by the contributor on their most recent record",
        "",
        "no",
        "",
        "",
        "no",
        "Five or nine digits depending on the filing",
        "most.recent.contributor.zipcode",
    ),
    (
        "most_recent_latitude",
        "FLOAT64",
        "Latitude geocoded from the most recent record",
        "",
        "no",
        "",
        "degree",
        "yes",
        "",
        "most.recent.contributor.latitude",
    ),
    (
        "most_recent_longitude",
        "FLOAT64",
        "Longitude geocoded from the most recent record",
        "",
        "no",
        "",
        "degree",
        "yes",
        "",
        "most.recent.contributor.longitude",
    ),
    (
        "most_recent_occupation",
        "STRING",
        "Occupation reported by the contributor on their most recent record",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "most.recent.contributor.occupation",
    ),
    (
        "most_recent_employer",
        "STRING",
        "Employer reported by the contributor on their most recent record",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "most.recent.contributor.employer",
    ),
    (
        "most_recent_transaction_id",
        "STRING",
        "Identifier of the contributor's most recent contribution record",
        "",
        "no",
        "",
        "",
        "no",
        "Joins to transaction_id in the contribution table",
        "most.recent.transaction.id",
    ),
    (
        "most_recent_transaction_date",
        "DATE",
        "Date of the contributor's most recent contribution record",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "most.recent.transaction.date",
    ),
]

# --------------------------------------------------------------------------
# contributor_cycle — one row per donor per cycle in which they gave
# --------------------------------------------------------------------------

CONTRIBUTOR_CYCLE: list[Col] = [
    (
        "cycle",
        "INT64",
        "Two-year election cycle the amount refers to",
        "",
        "no",
        YEAR_DIR,
        "year",
        "no",
        "Partition column",
        "amount.<cycle>",
    ),
    (
        "contributor_id",
        "STRING",
        "Unique identifier of the contributor, assigned by DIME entity resolution",
        "",
        "no",
        "",
        "",
        "no",
        "Joins to the contributor and contribution tables",
        "bonica.cid",
    ),
    (
        "amount",
        "FLOAT64",
        "Total amount contributed by the donor during the cycle",
        "",
        "no",
        "",
        "USD",
        "no",
        "Nominal dollars. Reshaped from the amount.<cycle> columns of the source contributor file; cycles in which the donor gave nothing are not stored as rows",
        "amount.<cycle>",
    ),
]

# --------------------------------------------------------------------------
# dicionario — code to label mapping for the coded columns above
# --------------------------------------------------------------------------

DICIONARIO: list[Col] = [
    (
        "id_tabela",
        "STRING",
        "Slug of the us_stanford_dime table the dictionary entry describes",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "id_tabela",
    ),
    (
        "nome_coluna",
        "STRING",
        "Name of the column the dictionary entry describes",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "nome_coluna",
    ),
    (
        "chave",
        "STRING",
        "Code stored in the column",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "chave",
    ),
    (
        "cobertura_temporal",
        "STRING",
        "Temporal coverage of the dictionary entry",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "cobertura_temporal",
    ),
    (
        "valor",
        "STRING",
        "Label the code stands for",
        "",
        "no",
        "",
        "",
        "no",
        "",
        "valor",
    ),
]

TABLES: dict[str, list[Col]] = {
    "contribution": CONTRIBUTION,
    "recipient": RECIPIENT,
    "contributor": CONTRIBUTOR,
    "contributor_cycle": CONTRIBUTOR_CYCLE,
    "dicionario": DICIONARIO,
}


# Source CSV header -> architecture column name, per table. Built from the
# original_name field so the cleaning step never restates the mapping.
def rename_map(table: str) -> dict[str, str]:
    """Return ``{source column: architecture column}`` for one table."""
    return {c[9]: c[0] for c in TABLES[table] if c[9] and "<" not in c[9]}


def column_names(table: str) -> list[str]:
    """Return the architecture column order for one table."""
    return [c[0] for c in TABLES[table]]


def column_types(table: str) -> dict[str, str]:
    """Return ``{column: bigquery_type}`` for one table."""
    return {c[0]: c[1] for c in TABLES[table]}


def write_all() -> None:
    """Write one architecture CSV per table."""
    ARCH_DIR.mkdir(parents=True, exist_ok=True)
    for table, cols in TABLES.items():
        path = ARCH_DIR / f"{table}.csv"
        with path.open("w", newline="", encoding="utf-8") as fh:
            w = csv.writer(fh)
            w.writerow(HEADER)
            for c in cols:
                w.writerow(c)
        print(f"wrote {path.name} ({len(cols)} columns)")


if __name__ == "__main__":
    write_all()
