"""The remaining FARS source columns, beyond the analytic core in gen_architecture.

Every column of accident.csv, vehicle.csv and person.csv is modelled. Names and
descriptions come from NHTSA's own Data Element List in the FARS Analytical
User's Manual, 1975-2024, so a column is called what the publisher calls it.

Two source variables collapse into one column only where the manual gives them
the same data element name AND their year spans are disjoint - that is a rename
across eras (TOWAWAY -> TOWED, VEH_CF1 -> VEH_SC1). Same name with overlapping
spans means genuinely parallel fields (WEATHER1/WEATHER2, CF1/CF2/CF3,
GVWR_FROM/GVWR_TO) and they stay separate.

The `<VAR>NAME` label columns the CSVs carry from 2015 are deliberately NOT
modelled: they are the label half of a code the dicionario already documents,
per year range, for every year rather than only for 2015 on.
"""

FULL = "1975(1)2024"

DIR_YEAR = "diretorios_data_tempo.ano:ano"
DIR_MONTH = "diretorios_data_tempo.mes:mes"
DIR_STATE = "diretorios_us.state:id_state"
DIR_COUNTY = "diretorios_us.county:id_county"

# A note repeated on every coded column: the code set is not stable over the
# 50-year span, so the dictionary is keyed by year range as well as by code.
ERA = (
    "Coluna codificada; o conjunto de códigos mudou ao longo do tempo, portanto "
    "consulte a tabela dicionario pelo par (código, cobertura_temporal)",
    "Coded column; the code set changed over time, so read it against the "
    "dicionario table on the (code, temporal coverage) pair",
    "Columna codificada; el conjunto de códigos cambió con el tiempo, por lo que "
    "debe leerse en la tabla dicionario por el par (código, cobertura temporal)",
)


IDENT = (
    "Identificador de texto livre; não é coluna categórica e portanto não é coberta pelo dicionário",
    "Free-text identifier; not a categorical column and so not covered by the dictionary",
    "Identificador de texto libre; no es una columna categórica y por lo tanto no está cubierta por el diccionario",
)
VINCH = (
    "Caractere isolado do VIN, publicado pela fonte em coluna própria",
    "Single character of the VIN, published by the source in its own column",
    "Carácter aislado del VIN, publicado por la fuente en una columna propia",
)
VINDEC = (
    "Campo derivado da decodificação do VIN pela NHTSA; descontinuado após 2012",
    "Field derived from NHTSA's decoding of the VIN; discontinued after 2012",
    "Campo derivado de la decodificación del VIN por la NHTSA; descontinuado después de 2012",
)
REPEAT = (
    "Atributo do acidente ou do veículo repetido no arquivo de pessoas pela fonte",
    "Crash- or vehicle-level attribute repeated on the person file by the source",
    "Atributo del accidente o del vehículo repetido en el archivo de personas por la fuente",
)


def extras(c):
    """Return (crash, vehicle, person) extra column specs."""

    # Identifier-like fields carry a <VAR>NAME companion that merely echoes the
    # value, so they are not dictionary material: declaring them would push tens
    # of thousands of ZIP codes and carrier ids into the dicionario.
    crash = [
        c(
            "crash_related_factor_1_code",
            "STRING",
            "CF1",
            "Primeiro fator relacionado ao acidente registrado no laudo",
            "First crash-level related factor recorded in the case material",
            "Primer factor relacionado con el accidente registrado en el informe",
            "1975(1)2019",
            dic=True,
            obs=ERA,
        ),
        c(
            "crash_related_factor_2_code",
            "STRING",
            "CF2",
            "Segundo fator relacionado ao acidente registrado no laudo",
            "Second crash-level related factor recorded in the case material",
            "Segundo factor relacionado con el accidente registrado en el informe",
            "1975(1)2019",
            dic=True,
            obs=ERA,
        ),
        c(
            "crash_related_factor_3_code",
            "STRING",
            "CF3",
            "Terceiro fator relacionado ao acidente registrado no laudo",
            "Third crash-level related factor recorded in the case material",
            "Tercer factor relacionado con el accidente registrado en el informe",
            "1975(1)2019",
            dic=True,
            obs=ERA,
        ),
        c(
            "federal_highway_code",
            "STRING",
            "FED_AID|TA_1_CL",
            "Classificação da via quanto ao financiamento federal",
            "Classification of the roadway for federal aid purposes",
            "Clasificación de la vía en cuanto al financiamiento federal",
            "1975(1)1993",
            dic=True,
            obs=(
                "Publicada como TA_1_CL até 1981 e como FED_AID de 1982 a 1993; não foi inicializada antes de 1978, de modo que não há dados nesses anos",
                "Published as TA_1_CL through 1981 and as FED_AID from 1982 to 1993; it was not initialised before 1978, so no data exists for those years",
                "Publicada como TA_1_CL hasta 1981 y como FED_AID de 1982 a 1993; no fue inicializada antes de 1978, por lo que no hay datos en esos años",
            ),
        ),
        c(
            "land_use_code",
            "STRING",
            "LAND_USE",
            "Uso do solo no local do acidente",
            "Land use at the crash location",
            "Uso del suelo en el lugar del accidente",
            "1975(1)1986",
            dic=True,
            obs=ERA,
        ),
        c(
            "roadway_surface_type_code",
            "STRING",
            "PAVE_TYP",
            "Tipo de pavimento da via no local do acidente",
            "Type of roadway surface at the crash location",
            "Tipo de pavimento de la vía en el lugar del accidente",
            "1975(1)2009",
            dic=True,
            obs=(
                "Registrada no nível do acidente até 2009; a partir de 2010 passou a ser registrada por veículo, na tabela vehicle",
                "Recorded at crash level through 2009; from 2010 it is recorded per vehicle, in the vehicle table",
                "Registrada a nivel del accidente hasta 2009; desde 2010 pasó a registrarse por vehículo, en la tabla vehicle",
            ),
        ),
        c(
            "trafficway_id_2",
            "STRING",
            "TWAY_ID2",
            "Identificação da segunda via, quando o acidente ocorreu em um cruzamento",
            "Identifier of the second trafficway, when the crash occurred at an intersection",
            "Identificación de la segunda vía, cuando el accidente ocurrió en un cruce",
            "2004(1)2024",
        ),
        c(
            "vehicles_in_transport_count",
            "INT64",
            "VEHICLES",
            "Número de veículos em circulação envolvidos no acidente",
            "Number of vehicles in transport involved in the crash",
            "Número de vehículos en circulación involucrados en el accidente",
            "1975(1)1981",
            unit="vehicle",
            obs=(
                "Contagem publicada apenas até 1981; vehicle_forms_count cobre todo o período",
                "Count published only through 1981; vehicle_forms_count covers the whole period",
                "Conteo publicado solo hasta 1981; vehicle_forms_count cubre todo el período",
            ),
        ),
        c(
            "atmospheric_condition_1_code",
            "STRING",
            "WEATHER1",
            "Primeira condição atmosférica registrada no momento do acidente",
            "First atmospheric condition recorded at the time of the crash",
            "Primera condición atmosférica registrada en el momento del accidente",
            "2007(1)2019",
            dic=True,
            obs=(
                "Entre 2007 e 2019 a fonte permitia registrar duas condições atmosféricas simultâneas, além da coluna weather_code",
                "Between 2007 and 2019 the source allowed two simultaneous atmospheric conditions to be recorded, alongside the weather_code column",
                "Entre 2007 y 2019 la fuente permitía registrar dos condiciones atmosféricas simultáneas, además de la columna weather_code",
            ),
        ),
        c(
            "atmospheric_condition_2_code",
            "STRING",
            "WEATHER2",
            "Segunda condição atmosférica registrada no momento do acidente",
            "Second atmospheric condition recorded at the time of the crash",
            "Segunda condición atmosférica registrada en el momento del accidente",
            "2007(1)2019",
            dic=True,
            obs=(
                "Preenchida apenas quando duas condições atmosféricas foram registradas simultaneamente",
                "Populated only where two atmospheric conditions were recorded at once",
                "Registrada solo cuando se anotaron dos condiciones atmosféricas simultáneas",
            ),
        ),
    ]

    person = [
        c(
            "county_id",
            "STRING",
            "COUNTY",
            "Código FIPS de cinco posições do condado onde ocorreu o acidente",
            "Five-digit FIPS code of the county where the crash occurred",
            "Código FIPS de cinco posiciones del condado donde ocurrió el accidente",
            FULL,
            dirc=DIR_COUNTY,
            obs=(
                "Construído como estado (2 dígitos) + condado (3 dígitos); nulo quando o código de condado é 0 ou 997-999",
                "Built as state (2 digits) + county (3 digits); null where the county code is 0 or 997-999",
                "Construido como estado (2 dígitos) + condado (3 dígitos); nulo cuando el código de condado es 0 o 997-999",
            ),
        ),
        c(
            "month",
            "INT64",
            "MONTH",
            "Mês-calendário do acidente",
            "Calendar month of the crash",
            "Mes calendario del accidente",
            FULL,
            dirc=DIR_MONTH,
            unit="month",
            obs=REPEAT,
        ),
        c(
            "day",
            "INT64",
            "DAY",
            "Dia do mês em que ocorreu o acidente",
            "Day of the month on which the crash occurred",
            "Día del mes en que ocurrió el accidente",
            FULL,
            unit="day",
            obs=REPEAT,
        ),
        c(
            "hour",
            "INT64",
            "HOUR",
            "Hora do acidente, no relógio de 24 horas",
            "Hour of the crash, on the 24-hour clock",
            "Hora del accidente, en el reloj de 24 horas",
            FULL,
            unit="hour",
            obs=REPEAT,
        ),
        c(
            "minute",
            "INT64",
            "MINUTE",
            "Minuto do acidente",
            "Minute of the crash",
            "Minuto del accidente",
            FULL,
            unit="minute",
            obs=REPEAT,
        ),
        c(
            "vehicle_forms_count",
            "INT64",
            "VE_FORMS",
            "Número de veículos em movimento envolvidos no acidente",
            "Number of vehicles in transport involved in the crash",
            "Número de vehículos en movimiento involucrados en el accidente",
            FULL,
            unit="vehicle",
            obs=REPEAT,
        ),
        c(
            "death_month",
            "INT64",
            "DEATH_MO",
            "Mês do óbito",
            "Month of death",
            "Mes del fallecimiento",
            FULL,
            unit="month",
            obs=(
                "Componente bruto de death_date; código de não aplicável convertido em nulo para sobreviventes",
                "Raw component of death_date; the not-applicable code is converted to null for survivors",
                "Componente bruto de death_date; el código de no aplicable se convierte en nulo para sobrevivientes",
            ),
        ),
        c(
            "death_day",
            "INT64",
            "DEATH_DA",
            "Dia do óbito",
            "Day of death",
            "Día del fallecimiento",
            FULL,
            unit="day",
            obs=(
                "Componente bruto de death_date",
                "Raw component of death_date",
                "Componente bruto de death_date",
            ),
        ),
        c(
            "death_year",
            "INT64",
            "DEATH_YR",
            "Ano do óbito",
            "Year of death",
            "Año del fallecimiento",
            FULL,
            unit="year",
            obs=(
                "Componente bruto de death_date",
                "Raw component of death_date",
                "Componente bruto de death_date",
            ),
        ),
        c(
            "death_time_code",
            "STRING",
            "DEATH_TM",
            "Hora do óbito no formato HHMM, como publicado pela fonte",
            "Time of death in HHMM form, as published by the source",
            "Hora del fallecimiento en formato HHMM, tal como la publica la fuente",
            FULL,
            dic=True,
            obs=(
                "Mantida como código porque a forma HHMM não admite aritmética; death_hour e death_minute trazem os componentes",
                "Kept as a code because the HHMM form does not admit arithmetic; death_hour and death_minute carry the components",
                "Mantenida como código porque la forma HHMM no admite aritmética; death_hour y death_minute traen los componentes",
            ),
        ),
        c(
            "alcohol_determination_method_code",
            "STRING",
            "ALC_DET",
            "Método pelo qual a polícia determinou o envolvimento com álcool",
            "Method by which police determined alcohol involvement",
            "Método por el cual la policía determinó el involucramiento con alcohol",
            "1987(1)2021",
            dic=True,
            obs=ERA,
        ),
        c(
            "drug_determination_method_code",
            "STRING",
            "DRUG_DET",
            "Método pelo qual a polícia determinou o envolvimento com drogas",
            "Method by which police determined drug involvement",
            "Método por el cual la policía determinó el involucramiento con drogas",
            "1991(1)2021",
            dic=True,
            obs=ERA,
        ),
        c(
            "drug_test_type_1_code",
            "STRING",
            "DRUGTST1|DRUGTEST",
            "Tipo do primeiro teste toxicológico realizado",
            "Type of the first drug test administered",
            "Tipo de la primera prueba toxicológica realizada",
            "1991(1)2017",
            dic=True,
            obs=ERA,
        ),
        c(
            "drug_test_type_2_code",
            "STRING",
            "DRUGTST2",
            "Tipo do segundo teste toxicológico realizado",
            "Type of the second drug test administered",
            "Tipo de la segunda prueba toxicológica realizada",
            "1993(1)2017",
            dic=True,
            obs=ERA,
        ),
        c(
            "drug_test_type_3_code",
            "STRING",
            "DRUGTST3",
            "Tipo do terceiro teste toxicológico realizado",
            "Type of the third drug test administered",
            "Tipo de la tercera prueba toxicológica realizada",
            "1993(1)2017",
            dic=True,
            obs=ERA,
        ),
        c(
            "drug_test_result_1_code",
            "STRING",
            "DRUGRES1|DRUG_RES",
            "Resultado do primeiro teste toxicológico",
            "Result of the first drug test",
            "Resultado de la primera prueba toxicológica",
            "1991(1)2017",
            dic=True,
            obs=ERA,
        ),
        c(
            "drug_test_result_2_code",
            "STRING",
            "DRUGRES2",
            "Resultado do segundo teste toxicológico",
            "Result of the second drug test",
            "Resultado de la segunda prueba toxicológica",
            "1993(1)2017",
            dic=True,
            obs=ERA,
        ),
        c(
            "drug_test_result_3_code",
            "STRING",
            "DRUGRES3",
            "Resultado do terceiro teste toxicológico",
            "Result of the third drug test",
            "Resultado de la tercera prueba toxicológica",
            "1993(1)2017",
            dic=True,
            obs=ERA,
        ),
        c(
            "toxicology_test_code",
            "STRING",
            "TOXCLGY",
            "Realização de exame toxicológico, no registro anterior a 1991",
            "Whether a toxicology test was performed, in the pre-1991 record",
            "Realización de examen toxicológico, en el registro anterior a 1991",
            "1987(1)1990",
            dic=True,
            obs=ERA,
        ),
        c(
            "person_related_factor_1_code",
            "STRING",
            "P_SF1|P_CF1",
            "Primeiro fator relacionado à pessoa registrado no laudo",
            "First person-level related factor recorded in the case material",
            "Primer factor relacionado con la persona registrado en el informe",
            "1975(1)2019",
            dic=True,
            obs=(
                "Publicada como P_CF1 até 2009 e como P_SF1 de 2010 a 2019",
                "Published as P_CF1 through 2009 and as P_SF1 from 2010 to 2019",
                "Publicada como P_CF1 hasta 2009 y como P_SF1 de 2010 a 2019",
            ),
        ),
        c(
            "person_related_factor_2_code",
            "STRING",
            "P_SF2|P_CF2",
            "Segundo fator relacionado à pessoa registrado no laudo",
            "Second person-level related factor recorded in the case material",
            "Segundo factor relacionado con la persona registrado en el informe",
            "1975(1)2019",
            dic=True,
            obs=ERA,
        ),
        c(
            "person_related_factor_3_code",
            "STRING",
            "P_SF3|P_CF3",
            "Terceiro fator relacionado à pessoa registrado no laudo",
            "Third person-level related factor recorded in the case material",
            "Tercer factor relacionado con la persona registrado en el informe",
            "1975(1)2019",
            dic=True,
            obs=ERA,
        ),
        c(
            "helmet_misuse_code",
            "STRING",
            "HELM_MIS",
            "Indicação de uso incorreto do capacete",
            "Indication that the helmet was misused",
            "Indicación de uso incorrecto del casco",
            "2019(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "non_motorist_device_type_code",
            "STRING",
            "DEVTYPE",
            "Tipo de dispositivo usado pelo não ocupante",
            "Type of device used by the non-motorist",
            "Tipo de dispositivo usado por el no ocupante",
            "2022(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "non_motorist_device_motorization_code",
            "STRING",
            "DEVMOTOR",
            "Indica se o dispositivo do não ocupante era motorizado",
            "Whether the non-motorist's device was motorised",
            "Indica si el dispositivo del no ocupante era motorizado",
            "2022(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "striking_vehicle_number_legacy_code",
            "STRING",
            "N_MOT_NO",
            "Número do veículo que atingiu o não ocupante, na numeração anterior a 2011",
            "Number of the vehicle that struck the non-motorist, in the pre-2011 numbering",
            "Número del vehículo que impactó al no ocupante, en la numeración anterior a 2011",
            "1982(1)2010",
            dic=True,
            obs=(
                "Antecessora de striking_vehicle_number; mantida em coluna própria porque as duas convivem em 2011",
                "Predecessor of striking_vehicle_number; kept as its own column because the two coexist in 2011",
                "Antecesora de striking_vehicle_number; mantenida en columna propia porque ambas coexisten en 2011",
            ),
        ),
        c(
            "death_certificate_number",
            "STRING",
            "CERT_NO",
            "Número do atestado de óbito atribuído pelo estado",
            "Death certificate number assigned by the state",
            "Número del certificado de defunción asignado por el estado",
            "1991(1)2014",
            obs=IDENT,
        ),
        c(
            "roadway_function_class_person_code",
            "STRING",
            "ROAD_FNC",
            "Classe funcional da via, repetida no arquivo de pessoas",
            "Functional class of the roadway, repeated on the person file",
            "Clase funcional de la vía, repetida en el archivo de personas",
            "1975(1)2014",
            dic=True,
            obs=REPEAT,
        ),
        c(
            "rural_urban_person_code",
            "STRING",
            "RUR_URB",
            "Classificação rural ou urbana, repetida no arquivo de pessoas",
            "Rural or urban classification, repeated on the person file",
            "Clasificación rural o urbana, repetida en el archivo de personas",
            "2015(1)2024",
            dic=True,
            obs=REPEAT,
        ),
        c(
            "functional_system_person_code",
            "STRING",
            "FUNC_SYS",
            "Sistema funcional da via, repetido no arquivo de pessoas",
            "Functional system of the roadway, repeated on the person file",
            "Sistema funcional de la vía, repetido en el archivo de personas",
            "2015(1)2024",
            dic=True,
            obs=REPEAT,
        ),
        c(
            "initial_impact_point_code",
            "STRING",
            "IMPACT1",
            "Ponto de impacto inicial no veículo em que a pessoa estava",
            "Initial point of impact on the vehicle the person was in",
            "Punto de impacto inicial en el vehículo en que estaba la persona",
            FULL,
            dic=True,
            obs=REPEAT,
        ),
        c(
            "most_damaged_area_code",
            "STRING",
            "IMPACT2",
            "Área mais danificada do veículo em que a pessoa estava",
            "Most damaged area of the vehicle the person was in",
            "Área más dañada del vehículo en que estaba la persona",
            "1975(1)2011",
            dic=True,
            obs=REPEAT,
        ),
        c(
            "vehicle_role_code",
            "STRING",
            "IMPACTS",
            "Papel do veículo na colisão",
            "Role of the vehicle in the collision",
            "Papel del vehículo en la colisión",
            "1975(1)2009",
            dic=True,
            obs=REPEAT,
        ),
        c(
            "fire_occurrence_code",
            "STRING",
            "FIRE_EXP",
            "Ocorrência de incêndio no veículo em que a pessoa estava",
            "Whether fire occurred in the vehicle the person was in",
            "Ocurrencia de incendio en el vehículo en que estaba la persona",
            FULL,
            dic=True,
            obs=REPEAT,
        ),
        c(
            "emergency_use_code",
            "STRING",
            "EMER_USE",
            "Indica se o veículo estava em atendimento de emergência",
            "Whether the vehicle was responding to an emergency",
            "Indica si el vehículo estaba en atención de emergencia",
            FULL,
            dic=True,
            obs=REPEAT,
        ),
        c(
            "special_use_code",
            "STRING",
            "SPEC_USE",
            "Uso especial do veículo em que a pessoa estava",
            "Special use of the vehicle the person was in",
            "Uso especial del vehículo en que estaba la persona",
            FULL,
            dic=True,
            obs=REPEAT,
        ),
        c(
            "tow_vehicle_code",
            "STRING",
            "TOW_VEH",
            "Indica se o veículo rebocava reboque ou semirreboque",
            "Whether the vehicle was pulling a trailer or semitrailer",
            "Indica si el vehículo remolcaba un remolque o semirremolque",
            FULL,
            dic=True,
            obs=REPEAT,
        ),
        c(
            "make_model_code",
            "STRING",
            "MAK_MOD",
            "Combinação codificada de marca e modelo do veículo",
            "Coded combination of the vehicle's make and model",
            "Combinación codificada de marca y modelo del vehículo",
            FULL,
            dic=True,
            obs=REPEAT,
        ),
        c(
            "gross_vehicle_weight_rating_from_code",
            "STRING",
            "GVWR_FROM",
            "Limite inferior da faixa de peso bruto total do veículo",
            "Lower bound of the vehicle's gross vehicle weight rating band",
            "Límite inferior de la banda de peso bruto total del vehículo",
            "2020(1)2024",
            dic=True,
            obs=REPEAT,
        ),
        c(
            "gross_vehicle_weight_rating_to_code",
            "STRING",
            "GVWR_TO",
            "Limite superior da faixa de peso bruto total do veículo",
            "Upper bound of the vehicle's gross vehicle weight rating band",
            "Límite superior de la banda de peso bruto total del vehículo",
            "2020(1)2024",
            dic=True,
            obs=REPEAT,
        ),
        c(
            "final_stage_body_class_code",
            "STRING",
            "ICFINALBODY",
            "Classe de carroceria do estágio final de fabricação",
            "Body class of the final stage of manufacture",
            "Clase de carrocería de la etapa final de fabricación",
            "2020(1)2024",
            dic=True,
            obs=REPEAT,
        ),
        c(
            "vpic_make_code",
            "STRING",
            "VPICMAKE",
            "Marca do veículo segundo a decodificação vPIC da NHTSA",
            "Make of the vehicle under NHTSA's vPIC decoding",
            "Marca del vehículo según la decodificación vPIC de la NHTSA",
            "2020(1)2024",
            dic=True,
            obs=REPEAT,
        ),
        c(
            "vpic_model_code",
            "STRING",
            "VPICMODEL",
            "Modelo do veículo segundo a decodificação vPIC da NHTSA",
            "Model of the vehicle under NHTSA's vPIC decoding",
            "Modelo del vehículo según la decodificación vPIC de la NHTSA",
            "2020(1)2024",
            dic=True,
            obs=REPEAT,
        ),
        c(
            "vpic_body_class_code",
            "STRING",
            "VPICBODYCLASS",
            "Classe de carroceria segundo a decodificação vPIC da NHTSA",
            "Body class under NHTSA's vPIC decoding",
            "Clase de carrocería según la decodificación vPIC de la NHTSA",
            "2020(1)2024",
            dic=True,
            obs=REPEAT,
        ),
        c(
            "vin_make",
            "STRING",
            "VINMAKE",
            "Marca decodificada do VIN",
            "Make decoded from the VIN",
            "Marca decodificada del VIN",
            "2010(1)2012",
            obs=VINDEC,
        ),
        c(
            "vin_model",
            "STRING",
            "VINA_MOD",
            "Modelo decodificado do VIN",
            "Model decoded from the VIN",
            "Modelo decodificado del VIN",
            "1975(1)2012",
            obs=VINDEC,
        ),
        c(
            "vin_body_type",
            "STRING",
            "VIN_BT",
            "Tipo de carroceria decodificado do VIN",
            "Body type decoded from the VIN",
            "Tipo de carrocería decodificado del VIN",
            "1982(1)2012",
            obs=VINDEC,
        ),
        c(
            "vin_vehicle_type",
            "STRING",
            "VINTYPE",
            "Tipo de veículo decodificado do VIN",
            "Vehicle type decoded from the VIN",
            "Tipo de vehículo decodificado del VIN",
            "2010(1)2012",
            obs=VINDEC,
        ),
        c(
            "vin_model_year_code",
            "STRING",
            "VINMODYR",
            "Ano-modelo do VIN, no código de posição 10 usado pela fonte",
            "Model year from the VIN, in the position-10 code the source publishes",
            "Año-modelo del VIN, en el código de posición 10 que publica la fuente",
            "2010(1)2012",
            dic=True,
            obs=(
                "Mantida como código: a fonte publica o caractere de posição 10 do VIN, não um ano de quatro dígitos, e lê-lo como número produziria anos entre 0 e 99",
                "Kept as a code: the source publishes VIN position 10 rather than a four-digit year, and reading it as a number would produce years between 0 and 99",
                "Mantenida como código: la fuente publica el carácter de posición 10 del VIN, no un año de cuatro dígitos, y leerlo como número produciría años entre 0 y 99",
            ),
        ),
        c(
            "vin_length",
            "INT64",
            "VIN_LNGT",
            "Número de caracteres do VIN publicado",
            "Number of characters in the published VIN",
            "Número de caracteres del VIN publicado",
            "2010(1)2012",
            unit="character",
            obs=VINDEC,
        ),
        c(
            "vin_curb_weight",
            "INT64",
            "VIN_WGT",
            "Peso em ordem de marcha decodificado do VIN, em libras",
            "Curb weight decoded from the VIN, in pounds",
            "Peso en orden de marcha decodificado del VIN, en libras",
            "1975(1)2012",
            unit="pound",
            obs=VINDEC,
        ),
        c(
            "wheelbase_short",
            "INT64",
            "WHLBS_SH",
            "Menor entre-eixos decodificado do VIN, em polegadas",
            "Shortest wheelbase decoded from the VIN, in inches",
            "Distancia entre ejes más corta decodificada del VIN, en pulgadas",
            "1975(1)2012",
            unit="inch",
            obs=VINDEC,
        ),
        c(
            "wheelbase_long",
            "INT64",
            "WHLBS_LG",
            "Maior entre-eixos decodificado do VIN, em polegadas",
            "Longest wheelbase decoded from the VIN, in inches",
            "Distancia entre ejes más larga decodificada del VIN, en pulgadas",
            "1975(1)2012",
            unit="inch",
            obs=VINDEC,
        ),
        c(
            "motorcycle_engine_displacement",
            "INT64",
            "MCYCL_DS",
            "Cilindrada do motor da motocicleta, em centímetros cúbicos",
            "Engine displacement of the motorcycle, in cubic centimetres",
            "Cilindrada del motor de la motocicleta, en centímetros cúbicos",
            "1975(1)2012",
            unit="militre",
            obs=VINDEC,
        ),
        c(
            "motorcycle_engine_cycles_code",
            "STRING",
            "MCYCL_CY",
            "Número de tempos do motor da motocicleta",
            "Number of engine cycles of the motorcycle",
            "Número de tiempos del motor de la motocicleta",
            "2011(1)2012",
            dic=True,
            obs=VINDEC,
        ),
        c(
            "motorcycle_dry_weight",
            "INT64",
            "MCYCL_WT",
            "Peso a seco da motocicleta, em libras",
            "Dry weight of the motorcycle, in pounds",
            "Peso en seco de la motocicleta, en libras",
            "2011(1)2012",
            unit="pound",
            obs=VINDEC,
        ),
        c(
            "engine_displacement_cubic_inch",
            "INT64",
            "DISPLACE",
            "Cilindrada do motor, em polegadas cúbicas",
            "Engine displacement, in cubic inches",
            "Cilindrada del motor, en pulgadas cúbicas",
            "2011(1)2012",
            unit="inch3",
            obs=VINDEC,
        ),
        c(
            "truck_shipping_weight",
            "INT64",
            "TRK_WT",
            "Peso de embarque do caminhão, em libras",
            "Shipping weight of the truck, in pounds",
            "Peso de embarque del camión, en libras",
            "2011(1)2012",
            unit="pound",
            obs=VINDEC,
        ),
        c(
            "truck_shipping_weight_variance_code",
            "STRING",
            "TRKWTVAR",
            "Faixa de variação do peso de embarque do caminhão",
            "Variance band of the truck's shipping weight",
            "Banda de variación del peso de embarque del camión",
            "2011(1)2012",
            dic=True,
            obs=VINDEC,
        ),
        c(
            "truck_weight_rating_code",
            "STRING",
            "WGTCD_TR",
            "Classe de peso do caminhão decodificada do VIN",
            "Truck weight rating decoded from the VIN",
            "Clase de peso del camión decodificada del VIN",
            "1975(1)2012",
            dic=True,
            obs=VINDEC,
        ),
        c(
            "truck_series",
            "STRING",
            "SER_TR",
            "Série do caminhão decodificada do VIN",
            "Truck series decoded from the VIN",
            "Serie del camión decodificada del VIN",
            "1975(1)2012",
            obs=VINDEC,
        ),
        c(
            "wheels_and_drive_wheels_code",
            "STRING",
            "WHLDRWHL",
            "Número de rodas e de rodas motrizes, em código combinado",
            "Number of wheels and drive wheels, as a combined code",
            "Número de ruedas y de ruedas motrices, en código combinado",
            "2011(1)2012",
            dic=True,
            obs=VINDEC,
        ),
        c(
            "carburetion",
            "STRING",
            "CARBUR",
            "Sistema de alimentação de combustível decodificado do VIN",
            "Fuel delivery system decoded from the VIN",
            "Sistema de alimentación de combustible decodificado del VIN",
            "2011(1)2012",
            obs=VINDEC,
        ),
        c(
            "cylinders",
            "STRING",
            "CYLINDER",
            "Número de cilindros do motor decodificado do VIN",
            "Number of engine cylinders decoded from the VIN",
            "Número de cilindros del motor decodificado del VIN",
            "2011(1)2012",
            obs=VINDEC,
        ),
        c(
            "fuel_code",
            "STRING",
            "FUELCODE",
            "Tipo de combustível decodificado do VIN",
            "Fuel type decoded from the VIN",
            "Tipo de combustible decodificado del VIN",
            "2010(1)2012",
            obs=VINDEC,
        ),
        c(
            "original_tire_size",
            "STRING",
            "TIRE_SZE",
            "Medida original dos pneus decodificada do VIN",
            "Original tire size decoded from the VIN",
            "Medida original de los neumáticos decodificada del VIN",
            "2011(1)2012",
            obs=VINDEC,
        ),
        c(
            "truck_ton_rating",
            "STRING",
            "TON_RAT",
            "Capacidade nominal do caminhão em toneladas, decodificada do VIN",
            "Nominal tonnage rating of the truck, decoded from the VIN",
            "Capacidad nominal del camión en toneladas, decodificada del VIN",
            "2011(1)2012",
            obs=VINDEC,
        ),
        c(
            "truck_vin_restraint_type",
            "STRING",
            "VIN_REST",
            "Tipo de retenção do caminhão decodificado do VIN",
            "Truck restraint type decoded from the VIN",
            "Tipo de retención del camión decodificado del VIN",
            "2011(1)2012",
            obs=VINDEC,
        ),
    ]

    vehicle = [
        c(
            "month",
            "INT64",
            "MONTH",
            "Mês-calendário do acidente",
            "Calendar month of the crash",
            "Mes calendario del accidente",
            "1994(1)2024",
            dirc=DIR_MONTH,
            unit="month",
            obs=REPEAT,
        ),
        c(
            "day",
            "INT64",
            "DAY",
            "Dia do mês em que ocorreu o acidente",
            "Day of the month on which the crash occurred",
            "Día del mes en que ocurrió el accidente",
            "2009(1)2024",
            unit="day",
            obs=REPEAT,
        ),
        c(
            "hour",
            "INT64",
            "HOUR",
            "Hora do acidente, no relógio de 24 horas",
            "Hour of the crash, on the 24-hour clock",
            "Hora del accidente, en el reloj de 24 horas",
            "2009(1)2024",
            unit="hour",
            obs=REPEAT,
        ),
        c(
            "minute",
            "INT64",
            "MINUTE",
            "Minuto do acidente",
            "Minute of the crash",
            "Minuto del accidente",
            "2009(1)2024",
            unit="minute",
            obs=REPEAT,
        ),
        c(
            "vehicle_forms_count",
            "INT64",
            "VE_FORMS",
            "Número de veículos em movimento envolvidos no acidente",
            "Number of vehicles in transport involved in the crash",
            "Número de vehículos en movimiento involucrados en el accidente",
            FULL,
            unit="vehicle",
            obs=REPEAT,
        ),
        c(
            "first_harmful_event_code",
            "STRING",
            "HARM_EV",
            "Primeiro evento lesivo do acidente",
            "First harmful event of the crash",
            "Primer evento lesivo del accidente",
            FULL,
            dic=True,
            obs=REPEAT,
        ),
        c(
            "manner_of_collision_code",
            "STRING",
            "MAN_COLL",
            "Posição relativa dos veículos no primeiro impacto",
            "Orientation of the vehicles in the first collision",
            "Posición relativa de los vehículos en el primer impacto",
            FULL,
            dic=True,
            obs=REPEAT,
        ),
        c(
            "most_damaged_area_code",
            "STRING",
            "IMPACT2",
            "Área mais danificada do veículo",
            "Most damaged area of the vehicle",
            "Área más dañada del vehículo",
            "1975(1)2011",
            dic=True,
            obs=ERA,
        ),
        c(
            "vehicle_role_code",
            "STRING",
            "IMPACTS",
            "Papel do veículo na colisão",
            "Role of the vehicle in the collision",
            "Papel del vehículo en la colisión",
            "1975(1)2009",
            dic=True,
            obs=ERA,
        ),
        c(
            "vehicle_towed_code",
            "STRING",
            "TOWED|TOWAWAY",
            "Indica se o veículo foi rebocado do local",
            "Whether the vehicle was towed from the scene",
            "Indica si el vehículo fue remolcado del lugar",
            FULL,
            dic=True,
            obs=(
                "Publicada como TOWAWAY até 2008 e como TOWED a partir de 2009",
                "Published as TOWAWAY through 2008 and as TOWED from 2009",
                "Publicada como TOWAWAY hasta 2008 y como TOWED desde 2009",
            ),
        ),
        c(
            "rollover_location_code",
            "STRING",
            "ROLINLOC",
            "Local em que ocorreu o capotamento",
            "Location at which the rollover occurred",
            "Lugar en que ocurrió el vuelco",
            "2009(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "underride_override_code",
            "STRING",
            "UNDERIDE",
            "Ocorrência de submersão ou sobreposição entre veículos",
            "Whether underride or override occurred between vehicles",
            "Ocurrencia de submarinado o sobremontado entre vehículos",
            "1994(1)2020",
            dic=True,
            obs=(
                "Substituída em 2021 por vehicle_underride_override_code, com conjunto de códigos distinto",
                "Replaced in 2021 by vehicle_underride_override_code, with a distinct code set",
                "Sustituida en 2021 por vehicle_underride_override_code, con un conjunto de códigos distinto",
            ),
        ),
        c(
            "vehicle_underride_override_code",
            "STRING",
            "UNDEROVERRIDE",
            "Ocorrência de submersão ou sobreposição, na codificação a partir de 2021",
            "Whether underride or override occurred, in the coding used from 2021",
            "Ocurrencia de submarinado o sobremontado, en la codificación desde 2021",
            "2021(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "vehicle_maneuver_code",
            "STRING",
            "VEH_MAN",
            "Manobra do veículo imediatamente antes do acidente",
            "Manoeuvre of the vehicle immediately before the crash",
            "Maniobra del vehículo inmediatamente antes del accidente",
            "1982(1)2009",
            dic=True,
            obs=ERA,
        ),
        c(
            "crash_avoidance_maneuver_code",
            "STRING",
            "AVOID",
            "Manobra realizada para tentar evitar a colisão",
            "Manoeuvre attempted to avoid the collision",
            "Maniobra realizada para intentar evitar la colisión",
            "1991(1)2009",
            dic=True,
            obs=ERA,
        ),
        c(
            "crash_type_configuration_code",
            "STRING",
            "ACC_CONFIG",
            "Configuração do tipo de acidente",
            "Configuration of the crash type",
            "Configuración del tipo de accidente",
            "2023(1)2023",
            dic=True,
            obs=(
                "Publicada apenas em 2023",
                "Published in 2023 only",
                "Publicada solo en 2023",
            ),
        ),
        c(
            "pre_event_movement_code",
            "STRING",
            "P_CRASH1",
            "Movimento do veículo antes do reconhecimento do evento crítico",
            "Movement of the vehicle prior to recognition of the critical event",
            "Movimiento del vehículo antes del reconocimiento del evento crítico",
            "2010(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "attempted_avoidance_maneuver_code",
            "STRING",
            "P_CRASH3",
            "Manobra de evasão tentada antes do impacto",
            "Avoidance manoeuvre attempted before impact",
            "Maniobra de evasión intentada antes del impacto",
            "2010(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "pre_impact_stability_code",
            "STRING",
            "PCRASH4",
            "Estabilidade do veículo imediatamente antes do impacto",
            "Stability of the vehicle immediately before impact",
            "Estabilidad del vehículo inmediatamente antes del impacto",
            "2010(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "pre_impact_location_code",
            "STRING",
            "PCRASH5",
            "Posição do veículo na via imediatamente antes do impacto",
            "Location of the vehicle on the roadway immediately before impact",
            "Posición del vehículo en la vía inmediatamente antes del impacto",
            "2010(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "vehicle_roadway_surface_type_code",
            "STRING",
            "VPAVETYP",
            "Tipo de pavimento da via, registrado por veículo",
            "Type of roadway surface, recorded per vehicle",
            "Tipo de pavimento de la vía, registrado por vehículo",
            "2010(1)2024",
            dic=True,
            obs=(
                "Sucessora, no nível do veículo, de roadway_surface_type_code da tabela crash",
                "Vehicle-level successor to roadway_surface_type_code in the crash table",
                "Sucesora, a nivel del vehículo, de roadway_surface_type_code de la tabla crash",
            ),
        ),
        c(
            "driver_vision_obscured_1_code",
            "STRING",
            "D_VISION1",
            "Primeiro obstáculo à visão do condutor",
            "First obstruction to the driver's vision",
            "Primer obstáculo a la visión del conductor",
            "2009(1)2009",
            dic=True,
            obs=(
                "Publicada apenas em 2009",
                "Published in 2009 only",
                "Publicada solo en 2009",
            ),
        ),
        c(
            "driver_vision_obscured_2_code",
            "STRING",
            "D_VISION2",
            "Segundo obstáculo à visão do condutor",
            "Second obstruction to the driver's vision",
            "Segundo obstáculo a la visión del conductor",
            "2009(1)2009",
            dic=True,
            obs=(
                "Publicada apenas em 2009",
                "Published in 2009 only",
                "Publicada solo en 2009",
            ),
        ),
        c(
            "driver_vision_obscured_3_code",
            "STRING",
            "D_VISION3",
            "Terceiro obstáculo à visão do condutor",
            "Third obstruction to the driver's vision",
            "Tercer obstáculo a la visión del conductor",
            "2009(1)2009",
            dic=True,
            obs=(
                "Publicada apenas em 2009",
                "Published in 2009 only",
                "Publicada solo en 2009",
            ),
        ),
        c(
            "driver_training_code",
            "STRING",
            "DR_TRAIN",
            "Formação do condutor em curso de direção",
            "Driver's formal driver training",
            "Formación del conductor en curso de conducción",
            "1975(1)1986",
            dic=True,
            obs=ERA,
        ),
        c(
            "driver_zip_code",
            "STRING",
            "DR_ZIP",
            "Código postal de residência do condutor",
            "ZIP code of the driver's residence",
            "Código postal de residencia del conductor",
            "1987(1)2024",
            obs=IDENT,
        ),
        c(
            "license_type_code",
            "STRING",
            "L_TYPE",
            "Categoria da habilitação não comercial do condutor",
            "Class of the driver's non-commercial licence",
            "Categoría de la licencia no comercial del conductor",
            "2004(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "license_endorsement_compliance_code",
            "STRING",
            "L_ENDORS",
            "Conformidade com as autorizações da habilitação comercial",
            "Compliance with commercial licence endorsements",
            "Conformidad con las autorizaciones de la licencia comercial",
            "1991(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "license_restriction_compliance_code",
            "STRING",
            "L_RESTRI",
            "Conformidade com as restrições da habilitação",
            "Compliance with the restrictions on the licence",
            "Conformidad con las restricciones de la licencia",
            FULL,
            dic=True,
            obs=ERA,
        ),
        c(
            "license_vehicle_class_compliance_code",
            "STRING",
            "L_CL_VEH",
            "Conformidade da habilitação com a categoria do veículo, no registro anterior a 1987",
            "Compliance of the licence with the vehicle class, in the pre-1987 record",
            "Conformidad de la licencia con la categoría del vehículo, en el registro anterior a 1987",
            "1982(1)1986",
            dic=True,
            obs=ERA,
        ),
        c(
            "previous_suspensions_bac_count_code",
            "STRING",
            "PREV_SUS2",
            "Suspensões anteriores por alcoolemia acima do limite, fora dos casos de menoridade",
            "Previous administrative per se suspensions for BAC, excluding underage cases",
            "Suspensiones anteriores por alcoholemia sobre el límite, fuera de los casos de minoría de edad",
            "2018(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "previous_other_suspensions_code",
            "STRING",
            "PREV_SUS3",
            "Outras suspensões ou cassações anteriores registradas",
            "Other previous recorded suspensions or revocations",
            "Otras suspensiones o revocaciones anteriores registradas",
            "2018(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "first_record_month",
            "INT64",
            "FIRST_MO",
            "Mês do registro mais antigo de acidente, suspensão ou condenação do condutor",
            "Month of the driver's oldest crash, suspension or conviction record",
            "Mes del registro más antiguo de accidente, suspensión o condena del conductor",
            FULL,
            unit="month",
        ),
        c(
            "first_record_year",
            "INT64",
            "FIRST_YR",
            "Ano do registro mais antigo de acidente, suspensão ou condenação do condutor",
            "Year of the driver's oldest crash, suspension or conviction record",
            "Año del registro más antiguo de accidente, suspensión o condena del conductor",
            FULL,
            unit="year",
        ),
        c(
            "last_record_month",
            "INT64",
            "LAST_MO",
            "Mês do registro mais recente de acidente, suspensão ou condenação do condutor",
            "Month of the driver's most recent crash, suspension or conviction record",
            "Mes del registro más reciente de accidente, suspensión o condena del conductor",
            FULL,
            unit="month",
        ),
        c(
            "last_record_year",
            "INT64",
            "LAST_YR",
            "Ano do registro mais recente de acidente, suspensão ou condenação do condutor",
            "Year of the driver's most recent crash, suspension or conviction record",
            "Año del registro más reciente de accidente, suspensión o condena del conductor",
            FULL,
            unit="year",
        ),
        c(
            "violation_charged_1_code",
            "STRING",
            "VIOLCHG1|VIOL_CHG",
            "Primeira infração imputada ao condutor neste acidente",
            "First violation charged to the driver in this crash",
            "Primera infracción imputada al conductor en este accidente",
            "1975(1)2009",
            dic=True,
            obs=(
                "Publicada como VIOL_CHG até 1996 e como VIOLCHG1 de 1997 a 2009",
                "Published as VIOL_CHG through 1996 and as VIOLCHG1 from 1997 to 2009",
                "Publicada como VIOL_CHG hasta 1996 y como VIOLCHG1 de 1997 a 2009",
            ),
        ),
        c(
            "violation_charged_2_code",
            "STRING",
            "VIOLCHG2",
            "Segunda infração imputada ao condutor neste acidente",
            "Second violation charged to the driver in this crash",
            "Segunda infracción imputada al conductor en este accidente",
            "1997(1)2009",
            dic=True,
            obs=ERA,
        ),
        c(
            "violation_charged_3_code",
            "STRING",
            "VIOLCHG3",
            "Terceira infração imputada ao condutor neste acidente",
            "Third violation charged to the driver in this crash",
            "Tercera infracción imputada al conductor en este accidente",
            "1997(1)2009",
            dic=True,
            obs=ERA,
        ),
        c(
            "driver_related_factor_1_code",
            "STRING",
            "DR_SF1|DR_CF1",
            "Primeiro fator relacionado ao condutor registrado no laudo",
            "First driver-level related factor recorded in the case material",
            "Primer factor relacionado con el conductor registrado en el informe",
            "1975(1)2019",
            dic=True,
            obs=(
                "Publicada como DR_CF1 até 2009 e como DR_SF1 de 2010 a 2019",
                "Published as DR_CF1 through 2009 and as DR_SF1 from 2010 to 2019",
                "Publicada como DR_CF1 hasta 2009 y como DR_SF1 de 2010 a 2019",
            ),
        ),
        c(
            "driver_related_factor_2_code",
            "STRING",
            "DR_SF2|DR_CF2",
            "Segundo fator relacionado ao condutor registrado no laudo",
            "Second driver-level related factor recorded in the case material",
            "Segundo factor relacionado con el conductor registrado en el informe",
            "1975(1)2019",
            dic=True,
            obs=ERA,
        ),
        c(
            "driver_related_factor_3_code",
            "STRING",
            "DR_SF3|DR_CF3",
            "Terceiro fator relacionado ao condutor registrado no laudo",
            "Third driver-level related factor recorded in the case material",
            "Tercer factor relacionado con el conductor registrado en el informe",
            "1975(1)2019",
            dic=True,
            obs=ERA,
        ),
        c(
            "driver_related_factor_4_code",
            "STRING",
            "DR_SF4|DR_CF4",
            "Quarto fator relacionado ao condutor registrado no laudo",
            "Fourth driver-level related factor recorded in the case material",
            "Cuarto factor relacionado con el conductor registrado en el informe",
            "1997(1)2019",
            dic=True,
            obs=ERA,
        ),
        c(
            "vehicle_related_factor_1_code",
            "STRING",
            "VEH_SC1|VEH_CF1",
            "Primeiro fator relacionado ao veículo registrado no laudo",
            "First vehicle-level related factor recorded in the case material",
            "Primer factor relacionado con el vehículo registrado en el informe",
            "1975(1)2019",
            dic=True,
            obs=(
                "Publicada como VEH_CF1 até 2009 e como VEH_SC1 de 2010 a 2019",
                "Published as VEH_CF1 through 2009 and as VEH_SC1 from 2010 to 2019",
                "Publicada como VEH_CF1 hasta 2009 y como VEH_SC1 de 2010 a 2019",
            ),
        ),
        c(
            "vehicle_related_factor_2_code",
            "STRING",
            "VEH_SC2|VEH_CF2",
            "Segundo fator relacionado ao veículo registrado no laudo",
            "Second vehicle-level related factor recorded in the case material",
            "Segundo factor relacionado con el vehículo registrado en el informe",
            "1975(1)2019",
            dic=True,
            obs=ERA,
        ),
        c(
            "sequence_of_events_1_code",
            "STRING",
            "SEQ1",
            "Primeiro evento da sequência de eventos do veículo",
            "First event in the vehicle's sequence of events",
            "Primer evento de la secuencia de eventos del vehículo",
            "2004(1)2009",
            dic=True,
            obs=(
                "A sequência de eventos passou a ser publicada em arquivo próprio a partir de 2010",
                "The sequence of events moved to a file of its own from 2010",
                "La secuencia de eventos pasó a publicarse en un archivo propio desde 2010",
            ),
        ),
        c(
            "sequence_of_events_2_code",
            "STRING",
            "SEQ2",
            "Segundo evento da sequência de eventos do veículo",
            "Second event in the vehicle's sequence of events",
            "Segundo evento de la secuencia de eventos del vehículo",
            "2004(1)2009",
            dic=True,
            obs=ERA,
        ),
        c(
            "sequence_of_events_3_code",
            "STRING",
            "SEQ3",
            "Terceiro evento da sequência de eventos do veículo",
            "Third event in the vehicle's sequence of events",
            "Tercer evento de la secuencia de eventos del vehículo",
            "2004(1)2009",
            dic=True,
            obs=ERA,
        ),
        c(
            "sequence_of_events_4_code",
            "STRING",
            "SEQ4",
            "Quarto evento da sequência de eventos do veículo",
            "Fourth event in the vehicle's sequence of events",
            "Cuarto evento de la secuencia de eventos del vehículo",
            "2004(1)2009",
            dic=True,
            obs=ERA,
        ),
        c(
            "sequence_of_events_5_code",
            "STRING",
            "SEQ5",
            "Quinto evento da sequência de eventos do veículo",
            "Fifth event in the vehicle's sequence of events",
            "Quinto evento de la secuencia de eventos del vehículo",
            "2004(1)2009",
            dic=True,
            obs=ERA,
        ),
        c(
            "sequence_of_events_6_code",
            "STRING",
            "SEQ6",
            "Sexto evento da sequência de eventos do veículo",
            "Sixth event in the vehicle's sequence of events",
            "Sexto evento de la secuencia de eventos del vehículo",
            "2004(1)2009",
            dic=True,
            obs=ERA,
        ),
        c(
            "axles_code",
            "STRING",
            "AXLES",
            "Número de eixos do veículo de carga",
            "Number of axles on the cargo vehicle",
            "Número de ejes del vehículo de carga",
            "1991(1)2007",
            dic=True,
            obs=ERA,
        ),
        c(
            "hazardous_material_placard_code",
            "STRING",
            "HAZ_PLAC",
            "Presença de placa de identificação de carga perigosa",
            "Whether a hazardous material placard was displayed",
            "Presencia de placa de identificación de carga peligrosa",
            "2007(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "hazardous_material_id",
            "STRING",
            "HAZ_ID",
            "Número de identificação da carga perigosa transportada",
            "Identification number of the hazardous material carried",
            "Número de identificación de la carga peligrosa transportada",
            "2007(1)2024",
            obs=IDENT,
        ),
        c(
            "hazardous_material_class_number",
            "STRING",
            "HAZ_CNO",
            "Número da classe de risco da carga perigosa",
            "Hazard class number of the hazardous material",
            "Número de la clase de riesgo de la carga peligrosa",
            "2007(1)2024",
            obs=IDENT,
        ),
        c(
            "hazardous_material_release_code",
            "STRING",
            "HAZ_REL",
            "Ocorrência de vazamento da carga perigosa do compartimento de carga",
            "Whether hazardous material was released from the cargo compartment",
            "Ocurrencia de fuga de la carga peligrosa del compartimento de carga",
            "2007(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "motor_carrier_id",
            "STRING",
            "MCARR_ID",
            "Número de identificação da transportadora",
            "Motor carrier identification number",
            "Número de identificación del transportista",
            "1998(1)2024",
            obs=IDENT,
        ),
        c(
            "motor_carrier_id_issuing_authority_code",
            "STRING",
            "MCARR_I1",
            "Autoridade emissora do número de identificação da transportadora",
            "Authority that issued the motor carrier identification number",
            "Autoridad emisora del número de identificación del transportista",
            "2007(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "motor_carrier_id_number",
            "STRING",
            "MCARR_I2",
            "Parte numérica do identificador da transportadora",
            "Numeric part of the motor carrier identifier",
            "Parte numérica del identificador del transportista",
            "2007(1)2024",
            obs=IDENT,
        ),
        c(
            "trailer_1_vin",
            "STRING",
            "TRLR1VIN",
            "VIN do primeiro reboque",
            "VIN of the first trailer",
            "VIN del primer remolque",
            "2016(1)2024",
            obs=IDENT,
        ),
        c(
            "trailer_2_vin",
            "STRING",
            "TRLR2VIN",
            "VIN do segundo reboque",
            "VIN of the second trailer",
            "VIN del segundo remolque",
            "2016(1)2024",
            obs=IDENT,
        ),
        c(
            "trailer_3_vin",
            "STRING",
            "TRLR3VIN",
            "VIN do terceiro reboque",
            "VIN of the third trailer",
            "VIN del tercer remolque",
            "2016(1)2024",
            obs=IDENT,
        ),
        c(
            "trailer_1_gross_weight_rating_code",
            "STRING",
            "TRLR1GVWR",
            "Faixa de peso bruto total do primeiro reboque",
            "Gross vehicle weight rating band of the first trailer",
            "Banda de peso bruto total del primer remolque",
            "2020(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "trailer_2_gross_weight_rating_code",
            "STRING",
            "TRLR2GVWR",
            "Faixa de peso bruto total do segundo reboque",
            "Gross vehicle weight rating band of the second trailer",
            "Banda de peso bruto total del segundo remolque",
            "2020(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "trailer_3_gross_weight_rating_code",
            "STRING",
            "TRLR3GVWR",
            "Faixa de peso bruto total do terceiro reboque",
            "Gross vehicle weight rating band of the third trailer",
            "Banda de peso bruto total del tercer remolque",
            "2020(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "gross_vehicle_weight_rating_from_code",
            "STRING",
            "GVWR_FROM",
            "Limite inferior da faixa de peso bruto total da unidade tratora",
            "Lower bound of the power unit's gross vehicle weight rating band",
            "Límite inferior de la banda de peso bruto total de la unidad tractora",
            "2020(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "gross_vehicle_weight_rating_to_code",
            "STRING",
            "GVWR_TO",
            "Limite superior da faixa de peso bruto total da unidade tratora",
            "Upper bound of the power unit's gross vehicle weight rating band",
            "Límite superior de la banda de peso bruto total de la unidad tractora",
            "2020(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "final_stage_body_class_code",
            "STRING",
            "ICFINALBODY",
            "Classe de carroceria do estágio final de fabricação",
            "Body class of the final stage of manufacture",
            "Clase de carrocería de la etapa final de fabricación",
            "2020(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "vpic_make_code",
            "STRING",
            "VPICMAKE",
            "Marca do veículo segundo a decodificação vPIC da NHTSA",
            "Make of the vehicle under NHTSA's vPIC decoding",
            "Marca del vehículo según la decodificación vPIC de la NHTSA",
            "2020(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "vpic_model_code",
            "STRING",
            "VPICMODEL",
            "Modelo do veículo segundo a decodificação vPIC da NHTSA",
            "Model of the vehicle under NHTSA's vPIC decoding",
            "Modelo del vehículo según la decodificación vPIC de la NHTSA",
            "2020(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "vpic_body_class_code",
            "STRING",
            "VPICBODYCLASS",
            "Classe de carroceria segundo a decodificação vPIC da NHTSA",
            "Body class under NHTSA's vPIC decoding",
            "Clase de carrocería según la decodificación vPIC de la NHTSA",
            "2020(1)2024",
            dic=True,
            obs=ERA,
        ),
        c(
            "motorcycle_type_code",
            "STRING",
            "MCYCL_TY",
            "Tipo de motocicleta",
            "Type of motorcycle",
            "Tipo de motocicleta",
            "1975(1)1981",
            obs=VINDEC,
        ),
        c(
            "truck_chassis_type_code",
            "STRING",
            "CHAS_TR",
            "Tipo de chassi do caminhão decodificado do VIN",
            "Truck chassis type decoded from the VIN",
            "Tipo de chasis del camión decodificado del VIN",
            "1975(1)1981",
            dic=True,
            obs=VINDEC,
        ),
        c(
            "truck_field_code",
            "STRING",
            "FLDCD_TR",
            "Código de campo do caminhão decodificado do VIN",
            "Truck field code decoded from the VIN",
            "Código de campo del camión decodificado del VIN",
            "1975(1)2009",
            obs=VINDEC,
        ),
        c(
            "vin_make",
            "STRING",
            "VINMAKE",
            "Marca decodificada do VIN",
            "Make decoded from the VIN",
            "Marca decodificada del VIN",
            "2010(1)2012",
            obs=VINDEC,
        ),
        c(
            "vin_model",
            "STRING",
            "VINA_MOD",
            "Modelo decodificado do VIN",
            "Model decoded from the VIN",
            "Modelo decodificado del VIN",
            "1975(1)2012",
            obs=VINDEC,
        ),
        c(
            "vin_body_type",
            "STRING",
            "VIN_BT",
            "Tipo de carroceria decodificado do VIN",
            "Body type decoded from the VIN",
            "Tipo de carrocería decodificado del VIN",
            "1982(1)2012",
            obs=VINDEC,
        ),
        c(
            "vin_vehicle_type",
            "STRING",
            "VINTYPE",
            "Tipo de veículo decodificado do VIN",
            "Vehicle type decoded from the VIN",
            "Tipo de vehículo decodificado del VIN",
            "2010(1)2012",
            obs=VINDEC,
        ),
        c(
            "vin_model_year_code",
            "STRING",
            "VINMODYR",
            "Ano-modelo do VIN, no código de posição 10 usado pela fonte",
            "Model year from the VIN, in the position-10 code the source publishes",
            "Año-modelo del VIN, en el código de posición 10 que publica la fuente",
            "2010(1)2012",
            dic=True,
            obs=(
                "Mantida como código: a fonte publica o caractere de posição 10 do VIN, não um ano de quatro dígitos, e lê-lo como número produziria anos entre 0 e 99",
                "Kept as a code: the source publishes VIN position 10 rather than a four-digit year, and reading it as a number would produce years between 0 and 99",
                "Mantenida como código: la fuente publica el carácter de posición 10 del VIN, no un año de cuatro dígitos, y leerlo como número produciría años entre 0 y 99",
            ),
        ),
        c(
            "vin_length",
            "INT64",
            "VIN_LNGT",
            "Número de caracteres do VIN publicado",
            "Number of characters in the published VIN",
            "Número de caracteres del VIN publicado",
            "1975(1)2012",
            unit="character",
            obs=VINDEC,
        ),
        c(
            "vin_curb_weight",
            "INT64",
            "VIN_WGT",
            "Peso em ordem de marcha decodificado do VIN, em libras",
            "Curb weight decoded from the VIN, in pounds",
            "Peso en orden de marcha decodificado del VIN, en libras",
            "1975(1)2012",
            unit="pound",
            obs=VINDEC,
        ),
        c(
            "wheelbase_short",
            "INT64",
            "WHLBS_SH",
            "Menor entre-eixos decodificado do VIN, em polegadas",
            "Shortest wheelbase decoded from the VIN, in inches",
            "Distancia entre ejes más corta decodificada del VIN, en pulgadas",
            "1975(1)2012",
            unit="inch",
            obs=VINDEC,
        ),
        c(
            "wheelbase_long",
            "INT64",
            "WHLBS_LG",
            "Maior entre-eixos decodificado do VIN, em polegadas",
            "Longest wheelbase decoded from the VIN, in inches",
            "Distancia entre ejes más larga decodificada del VIN, en pulgadas",
            "1975(1)2012",
            unit="inch",
            obs=VINDEC,
        ),
        c(
            "motorcycle_engine_displacement",
            "INT64",
            "MCYCL_DS",
            "Cilindrada do motor da motocicleta, em centímetros cúbicos",
            "Engine displacement of the motorcycle, in cubic centimetres",
            "Cilindrada del motor de la motocicleta, en centímetros cúbicos",
            "1975(1)2012",
            unit="militre",
            obs=VINDEC,
        ),
        c(
            "motorcycle_engine_cycles_code",
            "STRING",
            "MCYCL_CY",
            "Número de tempos do motor da motocicleta",
            "Number of engine cycles of the motorcycle",
            "Número de tiempos del motor de la motocicleta",
            "2011(1)2012",
            dic=True,
            obs=VINDEC,
        ),
        c(
            "motorcycle_dry_weight",
            "INT64",
            "MCYCL_WT",
            "Peso a seco da motocicleta, em libras",
            "Dry weight of the motorcycle, in pounds",
            "Peso en seco de la motocicleta, en libras",
            "2011(1)2012",
            unit="pound",
            obs=VINDEC,
        ),
        c(
            "engine_displacement_cubic_inch",
            "INT64",
            "DISPLACE",
            "Cilindrada do motor, em polegadas cúbicas",
            "Engine displacement, in cubic inches",
            "Cilindrada del motor, en pulgadas cúbicas",
            "2011(1)2012",
            unit="inch3",
            obs=VINDEC,
        ),
        c(
            "truck_shipping_weight",
            "INT64",
            "TRK_WT",
            "Peso de embarque do caminhão, em libras",
            "Shipping weight of the truck, in pounds",
            "Peso de embarque del camión, en libras",
            "2011(1)2012",
            unit="pound",
            obs=VINDEC,
        ),
        c(
            "truck_shipping_weight_variance_code",
            "STRING",
            "TRKWTVAR",
            "Faixa de variação do peso de embarque do caminhão",
            "Variance band of the truck's shipping weight",
            "Banda de variación del peso de embarque del camión",
            "2011(1)2012",
            dic=True,
            obs=VINDEC,
        ),
        c(
            "truck_weight_rating_code",
            "STRING",
            "WGTCD_TR",
            "Classe de peso do caminhão decodificada do VIN",
            "Truck weight rating decoded from the VIN",
            "Clase de peso del camión decodificada del VIN",
            "1975(1)2012",
            dic=True,
            obs=VINDEC,
        ),
        c(
            "truck_series",
            "STRING",
            "SER_TR",
            "Série do caminhão decodificada do VIN",
            "Truck series decoded from the VIN",
            "Serie del camión decodificada del VIN",
            "1975(1)2012",
            obs=VINDEC,
        ),
        c(
            "wheels_and_drive_wheels_code",
            "STRING",
            "WHLDRWHL",
            "Número de rodas e de rodas motrizes, em código combinado",
            "Number of wheels and drive wheels, as a combined code",
            "Número de ruedas y de ruedas motrices, en código combinado",
            "2011(1)2012",
            dic=True,
            obs=VINDEC,
        ),
        c(
            "carburetion",
            "STRING",
            "CARBUR",
            "Sistema de alimentação de combustível decodificado do VIN",
            "Fuel delivery system decoded from the VIN",
            "Sistema de alimentación de combustible decodificado del VIN",
            "2011(1)2012",
            obs=VINDEC,
        ),
        c(
            "cylinders",
            "STRING",
            "CYLINDER",
            "Número de cilindros do motor decodificado do VIN",
            "Number of engine cylinders decoded from the VIN",
            "Número de cilindros del motor decodificado del VIN",
            "2011(1)2012",
            obs=VINDEC,
        ),
        c(
            "fuel_code",
            "STRING",
            "FUELCODE",
            "Tipo de combustível decodificado do VIN",
            "Fuel type decoded from the VIN",
            "Tipo de combustible decodificado del VIN",
            "2010(1)2012",
            obs=VINDEC,
        ),
        c(
            "original_tire_size",
            "STRING",
            "TIRE_SZE",
            "Medida original dos pneus decodificada do VIN",
            "Original tire size decoded from the VIN",
            "Medida original de los neumáticos decodificada del VIN",
            "2011(1)2012",
            obs=VINDEC,
        ),
        c(
            "truck_ton_rating",
            "STRING",
            "TON_RAT",
            "Capacidade nominal do caminhão em toneladas, decodificada do VIN",
            "Nominal tonnage rating of the truck, decoded from the VIN",
            "Capacidad nominal del camión en toneladas, decodificada del VIN",
            "2011(1)2012",
            obs=VINDEC,
        ),
        c(
            "truck_vin_restraint_type",
            "STRING",
            "VIN_REST",
            "Tipo de retenção do caminhão decodificado do VIN",
            "Truck restraint type decoded from the VIN",
            "Tipo de retención del camión decodificado del VIN",
            "2011(1)2012",
            obs=VINDEC,
        ),
    ] + [
        c(
            f"vin_character_{i}",
            "STRING",
            f"VIN_{i}",
            f"Caractere {i} do número de identificação do veículo",
            f"Character {i} of the vehicle identification number",
            f"Carácter {i} del número de identificación del vehículo",
            "1975(1)2024" if i <= 10 else "1994(1)2024",
            obs=VINCH,
        )
        for i in range(1, 13)
    ]

    return crash, vehicle, person
