"""Write the architecture CSVs for us_dot_fars.

The CSVs under ``architecture/`` are the single source of truth for column names,
order, types, descriptions and the raw -> clean mapping. The cleaning transform,
the dbt models and the backend metadata payloads are all generated from them, so
the four cannot describe different schemas.

``original_name`` holds a ``|``-separated list of source aliases, newest first.
FARS renamed variables repeatedly over 50 years (TEST_RES -> ALC_RES,
C_M_ZONE -> WRK_ZONE, REL_JUNC -> RELJCT2); the transform takes the first alias
present in that year's header. A column whose concept was genuinely restructured
rather than renamed keeps its own entry with its own temporal coverage, because
merging incompatible code sets under one name would be a correctness bug.

Run: uv run python models/us_dot_fars/code/gen_architecture.py
"""

import csv
from pathlib import Path

ARCH = Path(__file__).resolve().parent / "architecture"

FIELDS = [
    "name",
    "bigquery_type",
    "description_pt",
    "description_en",
    "description_es",
    "temporal_coverage",
    "covered_by_dictionary",
    "directory_column",
    "measurement_unit",
    "has_sensitive_data",
    "observations_pt",
    "observations_en",
    "observations_es",
    "original_name",
]

FULL = "1975(1)2024"


def c(
    name,
    t,
    orig,
    pt,
    en,
    es,
    cov="",
    dic=False,
    dirc="",
    unit="",
    sens=False,
    obs=("", "", ""),
):
    return {
        "name": name,
        "bigquery_type": t,
        "description_pt": pt,
        "description_en": en,
        "description_es": es,
        "temporal_coverage": cov,
        "covered_by_dictionary": "yes" if dic else "no",
        "directory_column": dirc,
        "measurement_unit": unit,
        "has_sensitive_data": "yes" if sens else "no",
        "observations_pt": obs[0],
        "observations_en": obs[1],
        "observations_es": obs[2],
        "original_name": orig,
    }


DIR_YEAR = "diretorios_data_tempo.ano:ano"
DIR_MONTH = "diretorios_data_tempo.mes:mes"
DIR_STATE = "diretorios_us.state:id_state"
DIR_COUNTY = "diretorios_us.county:id_county"

# A note repeated on every coded column: the code set is not stable over the
# 50-year span, so the dictionary is keyed by year range as well as by code.
ERA = (
    "Coluna codificada; o conjunto de códigos mudou ao longo do tempo, portanto "
    "consulte a tabela dicionario pelo par (código, cobertura_temporal)",
    "Coded column; the code set changed over time, so read it against the "
    "dicionario table on the (code, temporal coverage) pair",
    "Columna codificada; el conjunto de códigos cambió con el tiempo, por lo que "
    "debe leerse en la tabla dicionario por el par (código, cobertura temporal)",
)

CRASH = [
    c(
        "year",
        "INT64",
        "YEAR",
        "Ano-calendário do acidente",
        "Calendar year of the crash",
        "Año calendario del accidente",
        FULL,
        dirc=DIR_YEAR,
        unit="year",
        obs=(
            "Coluna de particionamento",
            "Partition column",
            "Columna de particionamiento",
        ),
    ),
    c(
        "state_id",
        "STRING",
        "STATE",
        "Código FIPS de duas posições do estado onde ocorreu o acidente",
        "Two-digit FIPS code of the state where the crash occurred",
        "Código FIPS de dos posiciones del estado donde ocurrió el accidente",
        FULL,
        dirc=DIR_STATE,
        obs=(
            "O arquivo nacional cobre os 50 estados e o Distrito de Columbia; Porto Rico e demais territórios são publicados separadamente e não estão incluídos",
            "The national file covers the 50 states and the District of Columbia; Puerto Rico and the other territories are published separately and are not included",
            "El archivo nacional cubre los 50 estados y el Distrito de Columbia; Puerto Rico y los demás territorios se publican por separado y no están incluidos",
        ),
    ),
    c(
        "county_id",
        "STRING",
        "COUNTY",
        "Código FIPS de cinco posições do condado onde ocorreu o acidente",
        "Five-digit FIPS code of the county where the crash occurred",
        "Código FIPS de cinco posiciones del condado donde ocurrió el accidente",
        FULL,
        dirc=DIR_COUNTY,
        obs=(
            "Construído como estado (2 dígitos) + condado (3 dígitos); nulo quando o código de condado é 0 (não aplicável) ou 997-999 (desconhecido)",
            "Built as state (2 digits) + county (3 digits); null where the county code is 0 (not applicable) or 997-999 (unknown)",
            "Construido como estado (2 dígitos) + condado (3 dígitos); nulo cuando el código de condado es 0 (no aplicable) o 997-999 (desconocido)",
        ),
    ),
    c(
        "case_number",
        "STRING",
        "ST_CASE",
        "Número do caso atribuído pelo estado, único dentro do par estado-ano",
        "Case number assigned by the state, unique within the state-year pair",
        "Número de caso asignado por el estado, único dentro del par estado-año",
        FULL,
        obs=(
            "Chave primária lógica da tabela junto com year e state_id, e chave de ligação com vehicle e person",
            "Logical primary key of the table together with year and state_id, and the join key to vehicle and person",
            "Clave primaria lógica de la tabla junto con year y state_id, y clave de unión con vehicle y person",
        ),
    ),
    c(
        "city_code",
        "STRING",
        "CITY",
        "Código NHTSA do município ou cidade onde ocorreu o acidente",
        "NHTSA code of the city or municipality where the crash occurred",
        "Código NHTSA de la ciudad o municipio donde ocurrió el accidente",
        FULL,
        dic=True,
        obs=(
            "Codificação própria da NHTSA, que não corresponde ao código FIPS de place; 0 indica área não incorporada",
            "NHTSA's own coding, which does not correspond to the FIPS place code; 0 marks an unincorporated area",
            "Codificación propia de la NHTSA, que no corresponde al código FIPS de place; 0 indica área no incorporada",
        ),
    ),
    c(
        "date",
        "DATE",
        "",
        "Data do acidente",
        "Date of the crash",
        "Fecha del accidente",
        FULL,
        obs=(
            "Derivada de year, month e day; nula quando mês ou dia trazem código de desconhecido",
            "Derived from year, month and day; null where month or day carry an unknown code",
            "Derivada de year, month y day; nula cuando mes o día traen código de desconocido",
        ),
    ),
    c(
        "month",
        "INT64",
        "MONTH",
        "Mês-calendário do acidente",
        "Calendar month of the crash",
        "Mes calendario del accidente",
        FULL,
        dirc=DIR_MONTH,
        unit="month",
    ),
    c(
        "day",
        "INT64",
        "DAY",
        "Dia do mês em que ocorreu o acidente",
        "Day of the month on which the crash occurred",
        "Día del mes en que ocurrió el accidente",
        FULL,
        unit="day",
    ),
    c(
        "day_of_week_code",
        "STRING",
        "DAY_WEEK",
        "Dia da semana em que ocorreu o acidente",
        "Day of the week on which the crash occurred",
        "Día de la semana en que ocurrió el accidente",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "hour",
        "INT64",
        "HOUR",
        "Hora do acidente, no relógio de 24 horas",
        "Hour of the crash, on the 24-hour clock",
        "Hora del accidente, en el reloj de 24 horas",
        FULL,
        unit="hour",
    ),
    c(
        "minute",
        "INT64",
        "MINUTE",
        "Minuto do acidente",
        "Minute of the crash",
        "Minuto del accidente",
        FULL,
        unit="minute",
    ),
    c(
        "latitude",
        "FLOAT64",
        "LATITUDE|latitude",
        "Latitude do local do acidente, em graus decimais",
        "Latitude of the crash location, in decimal degrees",
        "Latitud del lugar del accidente, en grados decimales",
        "1999(1)2024",
        unit="degree",
        obs=(
            "Publicada a partir de 1999, mas de qualidade irregular antes de aproximadamente 2001, quando o georreferenciamento passou a ser exigido de todos os estados; valores de preenchimento (77.7777, 88.8888, 99.9999) foram convertidos em nulo",
            "Published from 1999 on, but of uneven quality before roughly 2001, when georeferencing became required of every state; filler values (77.7777, 88.8888, 99.9999) were converted to null",
            "Publicada desde 1999, pero de calidad irregular antes de aproximadamente 2001, cuando el georreferenciamiento pasó a exigirse a todos los estados; los valores de relleno (77.7777, 88.8888, 99.9999) se convirtieron en nulo",
        ),
    ),
    c(
        "longitude",
        "FLOAT64",
        "LONGITUD|longitud",
        "Longitude do local do acidente, em graus decimais",
        "Longitude of the crash location, in decimal degrees",
        "Longitud del lugar del accidente, en grados decimales",
        "1999(1)2024",
        unit="degree",
        obs=(
            "Mesmas ressalvas de qualidade e de valores de preenchimento descritas em latitude",
            "Same quality and filler-value caveats described under latitude",
            "Mismas advertencias de calidad y de valores de relleno descritas en latitude",
        ),
    ),
    c(
        "trafficway_id",
        "STRING",
        "TWAY_ID",
        "Identificação da via em que ocorreu o acidente, conforme registrada pelo estado",
        "Identifier of the trafficway on which the crash occurred, as recorded by the state",
        "Identificación de la vía en que ocurrió el accidente, según registro del estado",
        "1982(1)2024",
    ),
    c(
        "milepoint",
        "FLOAT64",
        "MILEPT",
        "Marco quilométrico, em milhas, do ponto do acidente na via",
        "Milepost, in miles, of the crash point along the trafficway",
        "Hito, en millas, del punto del accidente en la vía",
        "1982(1)2024",
        unit="mile",
    ),
    c(
        "route_signing_code",
        "STRING",
        "ROUTE",
        "Tipo de sinalização da via (interestadual, rodovia federal, estadual, via local)",
        "Route signing of the trafficway (interstate, US highway, state highway, local road)",
        "Tipo de señalización de la vía (interestatal, carretera federal, estatal, vía local)",
        "1987(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "land_use_code",
        "STRING",
        "RUR_URB",
        "Classificação rural ou urbana do local do acidente",
        "Rural or urban classification of the crash location",
        "Clasificación rural o urbana del lugar del accidente",
        "2015(1)2024",
        dic=True,
        obs=(
            "Publicada como variável própria a partir de 2015; até 2014 a informação rural/urbana estava embutida em road_function_class_code",
            "Published as its own variable from 2015; through 2014 the rural/urban split was embedded in road_function_class_code",
            "Publicada como variable propia desde 2015; hasta 2014 la información rural/urbana estaba incorporada en road_function_class_code",
        ),
    ),
    c(
        "road_function_class_code",
        "STRING",
        "ROAD_FNC",
        "Classe funcional da via, combinando o corte rural/urbano e a função da via",
        "Functional class of the roadway, combining the rural/urban split and the road's function",
        "Clase funcional de la vía, combinando el corte rural/urbano y la función de la vía",
        "1975(1)2014",
        dic=True,
        obs=(
            "Descontinuada após 2014 e substituída pelo par functional_system_code e land_use_code, cujos códigos não são comparáveis aos desta coluna",
            "Discontinued after 2014 and replaced by the pair functional_system_code and land_use_code, whose codes are not comparable to this column's",
            "Descontinuada después de 2014 y sustituida por el par functional_system_code y land_use_code, cuyos códigos no son comparables con los de esta columna",
        ),
    ),
    c(
        "functional_system_code",
        "STRING",
        "FUNC_SYS",
        "Sistema funcional da via segundo a classificação da Federal Highway Administration",
        "Functional system of the roadway under the Federal Highway Administration classification",
        "Sistema funcional de la vía según la clasificación de la Federal Highway Administration",
        "2015(1)2024",
        dic=True,
        obs=(
            "Sucessora parcial de road_function_class_code a partir de 2015; os conjuntos de códigos são distintos e não devem ser somados entre as duas eras",
            "Partial successor to road_function_class_code from 2015; the code sets are distinct and must not be pooled across the two eras",
            "Sucesora parcial de road_function_class_code desde 2015; los conjuntos de códigos son distintos y no deben sumarse entre las dos eras",
        ),
    ),
    c(
        "road_owner_code",
        "STRING",
        "RD_OWNER",
        "Entidade proprietária da via",
        "Entity that owns the roadway",
        "Entidad propietaria de la vía",
        "2015(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "national_highway_system_code",
        "STRING",
        "NHS",
        "Indica se o acidente ocorreu em via do National Highway System",
        "Whether the crash occurred on a National Highway System route",
        "Indica si el accidente ocurrió en una vía del National Highway System",
        "1994(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "special_jurisdiction_code",
        "STRING",
        "SP_JUR",
        "Jurisdição especial sobre o local do acidente, quando não é a via pública comum",
        "Special jurisdiction over the crash location, where it is not an ordinary public road",
        "Jurisdicción especial sobre el lugar del accidente, cuando no es la vía pública común",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "first_harmful_event_code",
        "STRING",
        "HARM_EV",
        "Primeiro evento lesivo do acidente, isto é, o primeiro impacto que produziu dano ou lesão",
        "First harmful event of the crash, that is, the first impact that produced damage or injury",
        "Primer evento lesivo del accidente, es decir, el primer impacto que produjo daño o lesión",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "manner_of_collision_code",
        "STRING",
        "MAN_COLL",
        "Posição relativa dos veículos no primeiro impacto entre veículos em movimento",
        "Orientation of the vehicles in the first collision between vehicles in transport",
        "Posición relativa de los vehículos en el primer impacto entre vehículos en movimiento",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "relation_to_junction_code",
        "STRING",
        "RELJCT2|REL_JUNC",
        "Relação do local do acidente com um entroncamento",
        "Relation of the crash location to a junction",
        "Relación del lugar del accidente con un entronque",
        FULL,
        dic=True,
        obs=(
            "Publicada como REL_JUNC até 2009 e como RELJCT2 a partir de 2010; a redefinição dos códigos em 1991 e em 2010 está registrada na tabela dicionario",
            "Published as REL_JUNC through 2009 and as RELJCT2 from 2010; the 1991 and 2010 code redefinitions are recorded in the dicionario table",
            "Publicada como REL_JUNC hasta 2009 y como RELJCT2 desde 2010; la redefinición de los códigos en 1991 y en 2010 está registrada en la tabla dicionario",
        ),
    ),
    c(
        "within_interchange_code",
        "STRING",
        "RELJCT1",
        "Indica se o acidente ocorreu dentro da área de um trevo ou entroncamento em desnível",
        "Whether the crash occurred within an interchange area",
        "Indica si el accidente ocurrió dentro del área de un intercambiador",
        "2010(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "intersection_type_code",
        "STRING",
        "TYP_INT",
        "Configuração geométrica do cruzamento onde ocorreu o acidente",
        "Geometric configuration of the intersection where the crash occurred",
        "Configuración geométrica del cruce donde ocurrió el accidente",
        "2010(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "relation_to_roadway_code",
        "STRING",
        "REL_ROAD",
        "Posição do acidente em relação à pista de rolamento",
        "Location of the crash relative to the roadway",
        "Posición del accidente en relación con la calzada",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "work_zone_code",
        "STRING",
        "WRK_ZONE|C_M_ZONE",
        "Indica se o acidente ocorreu em zona de obras e de que tipo",
        "Whether the crash occurred in a work zone, and of what type",
        "Indica si el accidente ocurrió en zona de obras y de qué tipo",
        FULL,
        dic=True,
        obs=(
            "Publicada como C_M_ZONE até 2008 e como WRK_ZONE a partir de 2009, com conjuntos de códigos distintos em cada era",
            "Published as C_M_ZONE through 2008 and as WRK_ZONE from 2009, with distinct code sets in each era",
            "Publicada como C_M_ZONE hasta 2008 y como WRK_ZONE desde 2009, con conjuntos de códigos distintos en cada era",
        ),
    ),
    c(
        "light_condition_code",
        "STRING",
        "LGT_COND",
        "Condição de iluminação no momento do acidente",
        "Light condition at the time of the crash",
        "Condición de iluminación en el momento del accidente",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "weather_code",
        "STRING",
        "WEATHER",
        "Condição atmosférica predominante no momento do acidente",
        "Prevailing atmospheric condition at the time of the crash",
        "Condición atmosférica predominante en el momento del accidente",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "school_bus_related_code",
        "STRING",
        "SCH_BUS",
        "Indica se um ônibus escolar esteve envolvido no acidente",
        "Whether a school bus was involved in the crash",
        "Indica si un autobús escolar estuvo involucrado en el accidente",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "rail_crossing_id",
        "STRING",
        "RAIL",
        "Identificador do cruzamento ferroviário onde ocorreu o acidente",
        "Identifier of the rail grade crossing where the crash occurred",
        "Identificador del cruce ferroviario donde ocurrió el accidente",
        FULL,
        obs=(
            "Número de inventário do cruzamento atribuído pela Federal Railroad Administration; 0000000 indica acidente fora de cruzamento ferroviário",
            "Grade crossing inventory number assigned by the Federal Railroad Administration; 0000000 marks a crash away from a rail crossing",
            "Número de inventario del cruce asignado por la Federal Railroad Administration; 0000000 indica accidente fuera de cruce ferroviario",
        ),
    ),
    c(
        "hit_and_run_code",
        "STRING",
        "HIT_RUN",
        "Indica se houve evasão do local por algum veículo envolvido",
        "Whether any vehicle involved left the scene",
        "Indica si hubo huida del lugar por algún vehículo involucrado",
        "1975(1)2008",
        dic=True,
        obs=(
            "Registrada no nível do acidente até 2008; a partir de 2009 passou a ser registrada por veículo, na tabela vehicle",
            "Recorded at crash level through 2008; from 2009 it is recorded per vehicle, in the vehicle table",
            "Registrada a nivel del accidente hasta 2008; desde 2009 pasó a registrarse por vehículo, en la tabla vehicle",
        ),
    ),
    c(
        "number_of_lanes_code",
        "STRING",
        "NO_LANES",
        "Número de faixas de rolamento da via, em faixas codificadas",
        "Number of travel lanes on the trafficway, in coded bands",
        "Número de carriles de la vía, en bandas codificadas",
        "1975(1)2009",
        dic=True,
        obs=(
            "Registrada no nível do acidente até 2009; a partir de 2010 passou a ser registrada por veículo, na tabela vehicle",
            "Recorded at crash level through 2009; from 2010 it is recorded per vehicle, in the vehicle table",
            "Registrada a nivel del accidente hasta 2009; desde 2010 pasó a registrarse por vehículo, en la tabla vehicle",
        ),
    ),
    c(
        "speed_limit",
        "INT64",
        "SP_LIMIT",
        "Velocidade máxima regulamentada da via, em milhas por hora",
        "Posted speed limit of the trafficway, in miles per hour",
        "Velocidad máxima reglamentada de la vía, en millas por hora",
        "1975(1)2009",
        unit="mile_per_hour",
        obs=(
            "Códigos de não aplicável e desconhecido (0, 98, 99) foram convertidos em nulo; a partir de 2010 a informação passou a ser registrada por veículo",
            "Not-applicable and unknown codes (0, 98, 99) were converted to null; from 2010 the information is recorded per vehicle",
            "Los códigos de no aplicable y desconocido (0, 98, 99) se convirtieron en nulo; desde 2010 la información pasó a registrarse por vehículo",
        ),
    ),
    c(
        "roadway_alignment_code",
        "STRING",
        "ALIGNMNT",
        "Alinhamento horizontal da via no local do acidente",
        "Horizontal alignment of the roadway at the crash location",
        "Alineación horizontal de la vía en el lugar del accidente",
        "1975(1)2009",
        dic=True,
        obs=ERA,
    ),
    c(
        "roadway_profile_code",
        "STRING",
        "PROFILE",
        "Perfil vertical da via no local do acidente",
        "Vertical profile of the roadway at the crash location",
        "Perfil vertical de la vía en el lugar del accidente",
        "1975(1)2009",
        dic=True,
        obs=ERA,
    ),
    c(
        "surface_condition_code",
        "STRING",
        "SUR_COND",
        "Condição do pavimento no local do acidente",
        "Condition of the road surface at the crash location",
        "Condición del pavimento en el lugar del accidente",
        "1975(1)2009",
        dic=True,
        obs=ERA,
    ),
    c(
        "traffic_control_code",
        "STRING",
        "TRA_CONT",
        "Dispositivo de controle de tráfego presente no local do acidente",
        "Traffic control device present at the crash location",
        "Dispositivo de control de tráfico presente en el lugar del accidente",
        "1975(1)2009",
        dic=True,
        obs=ERA,
    ),
    c(
        "traffic_control_functioning_code",
        "STRING",
        "T_CONT_F",
        "Indica se o dispositivo de controle de tráfego estava em funcionamento",
        "Whether the traffic control device was functioning",
        "Indica si el dispositivo de control de tráfico estaba en funcionamiento",
        "1982(1)2009",
        dic=True,
        obs=ERA,
    ),
    c(
        "trafficway_flow_code",
        "STRING",
        "TRAF_FLO|TWAY_FLO|ROAD_FLO",
        "Sentido de circulação da via e presença de separação física entre os fluxos",
        "Direction of travel on the trafficway and whether the flows are physically divided",
        "Sentido de circulación de la vía y presencia de separación física entre los flujos",
        "1975(1)2009",
        dic=True,
        obs=(
            "Publicada como ROAD_FLO (1975-1981), TWAY_FLO (1982-1986) e TRAF_FLO (1987-2009)",
            "Published as ROAD_FLO (1975-1981), TWAY_FLO (1982-1986) and TRAF_FLO (1987-2009)",
            "Publicada como ROAD_FLO (1975-1981), TWAY_FLO (1982-1986) y TRAF_FLO (1987-2009)",
        ),
    ),
    c(
        "vehicle_forms_count",
        "INT64",
        "VE_FORMS",
        "Número de veículos em movimento envolvidos no acidente",
        "Number of vehicles in transport involved in the crash",
        "Número de vehículos en movimiento involucrados en el accidente",
        FULL,
        unit="vehicle",
    ),
    c(
        "vehicles_total_count",
        "INT64",
        "VE_TOTAL",
        "Número total de veículos envolvidos, incluindo os estacionados",
        "Total number of vehicles involved, including parked ones",
        "Número total de vehículos involucrados, incluidos los estacionados",
        "2005(1)2024",
        unit="vehicle",
    ),
    c(
        "parked_vehicles_count",
        "INT64",
        "PVH_INVL",
        "Número de veículos estacionados ou fora de circulação envolvidos no acidente",
        "Number of parked or out-of-transport vehicles involved in the crash",
        "Número de vehículos estacionados o fuera de circulación involucrados en el accidente",
        "2011(1)2024",
        unit="vehicle",
    ),
    c(
        "persons_count",
        "INT64",
        "PERSONS",
        "Número de pessoas em veículos em movimento envolvidas no acidente",
        "Number of people in vehicles in transport involved in the crash",
        "Número de personas en vehículos en movimiento involucradas en el accidente",
        FULL,
        unit="person",
    ),
    c(
        "persons_in_motor_vehicles_count",
        "INT64",
        "PERMVIT",
        "Número de ocupantes de veículos automotores em movimento",
        "Number of occupants of motor vehicles in transport",
        "Número de ocupantes de vehículos automotores en movimiento",
        "2011(1)2024",
        unit="person",
    ),
    c(
        "persons_outside_motor_vehicles_count",
        "INT64",
        "PERNOTMVIT",
        "Número de pessoas envolvidas que não estavam em veículo automotor em movimento",
        "Number of people involved who were not in a motor vehicle in transport",
        "Número de personas involucradas que no estaban en un vehículo automotor en movimiento",
        "2011(1)2024",
        unit="person",
    ),
    c(
        "pedestrians_count",
        "INT64",
        "PEDS",
        "Número de pedestres e outros não ocupantes envolvidos no acidente",
        "Number of pedestrians and other non-occupants involved in the crash",
        "Número de peatones y otros no ocupantes involucrados en el accidente",
        "1991(1)2024",
        unit="person",
    ),
    c(
        "fatalities_count",
        "INT64",
        "FATALS",
        "Número de mortes decorrentes do acidente",
        "Number of fatalities resulting from the crash",
        "Número de muertes derivadas del accidente",
        FULL,
        unit="person",
        obs=(
            "Uma morte entra no FARS quando ocorre em até 30 dias após o acidente; esta é a contagem que define a inclusão do acidente no censo",
            "A death enters FARS when it occurs within 30 days of the crash; this count is what qualifies the crash for the census",
            "Una muerte entra en FARS cuando ocurre dentro de los 30 días posteriores al accidente; este conteo es el que define la inclusión del accidente en el censo",
        ),
    ),
    c(
        "drunk_drivers_count",
        "INT64",
        "DRUNK_DR",
        "Número de condutores envolvidos com álcool no organismo segundo a imputação da NHTSA",
        "Number of drivers involved with alcohol in their system under NHTSA's imputation",
        "Número de conductores involucrados con alcohol en el organismo según la imputación de la NHTSA",
        "1975(1)2020",
        unit="person",
        obs=(
            "Descontinuada no arquivo nacional após 2020",
            "Discontinued in the national file after 2020",
            "Descontinuada en el archivo nacional después de 2020",
        ),
    ),
    c(
        "notification_hour",
        "INT64",
        "NOT_HOUR",
        "Hora em que os serviços de emergência foram notificados",
        "Hour at which emergency medical services were notified",
        "Hora en que los servicios de emergencia fueron notificados",
        FULL,
        unit="hour",
    ),
    c(
        "notification_minute",
        "INT64",
        "NOT_MIN",
        "Minuto em que os serviços de emergência foram notificados",
        "Minute at which emergency medical services were notified",
        "Minuto en que los servicios de emergencia fueron notificados",
        FULL,
        unit="minute",
    ),
    c(
        "arrival_hour",
        "INT64",
        "ARR_HOUR",
        "Hora de chegada dos serviços de emergência ao local",
        "Hour at which emergency medical services arrived on scene",
        "Hora de llegada de los servicios de emergencia al lugar",
        FULL,
        unit="hour",
    ),
    c(
        "arrival_minute",
        "INT64",
        "ARR_MIN",
        "Minuto de chegada dos serviços de emergência ao local",
        "Minute at which emergency medical services arrived on scene",
        "Minuto de llegada de los servicios de emergencia al lugar",
        FULL,
        unit="minute",
    ),
    c(
        "hospital_arrival_hour",
        "INT64",
        "HOSP_HR",
        "Hora de chegada do primeiro ferido ao hospital",
        "Hour at which the first injured person arrived at hospital",
        "Hora de llegada del primer herido al hospital",
        "1987(1)2024",
        unit="hour",
    ),
    c(
        "hospital_arrival_minute",
        "INT64",
        "HOSP_MN",
        "Minuto de chegada do primeiro ferido ao hospital",
        "Minute at which the first injured person arrived at hospital",
        "Minuto de llegada del primer herido al hospital",
        "1987(1)2024",
        unit="minute",
    ),
]

VEHICLE = [
    c(
        "year",
        "INT64",
        "",
        "Ano-calendário do acidente",
        "Calendar year of the crash",
        "Año calendario del accidente",
        FULL,
        dirc=DIR_YEAR,
        unit="year",
        obs=(
            "Coluna de particionamento; derivada do arquivo anual de origem, pois vehicle.csv não traz a coluna de ano em todos os anos",
            "Partition column; taken from the source annual file, because vehicle.csv does not carry a year column in every year",
            "Columna de particionamiento; derivada del archivo anual de origen, pues vehicle.csv no trae la columna de año en todos los años",
        ),
    ),
    c(
        "state_id",
        "STRING",
        "STATE",
        "Código FIPS de duas posições do estado onde ocorreu o acidente",
        "Two-digit FIPS code of the state where the crash occurred",
        "Código FIPS de dos posiciones del estado donde ocurrió el accidente",
        FULL,
        dirc=DIR_STATE,
    ),
    c(
        "case_number",
        "STRING",
        "ST_CASE",
        "Número do caso atribuído pelo estado, único dentro do par estado-ano",
        "Case number assigned by the state, unique within the state-year pair",
        "Número de caso asignado por el estado, único dentro del par estado-año",
        FULL,
        obs=(
            "Chave de ligação com a tabela crash",
            "Join key to the crash table",
            "Clave de unión con la tabla crash",
        ),
    ),
    c(
        "vehicle_number",
        "INT64",
        "VEH_NO",
        "Número sequencial do veículo dentro do acidente",
        "Sequential number of the vehicle within the crash",
        "Número secuencial del vehículo dentro del accidente",
        FULL,
        unit="vehicle",
        obs=(
            "Compõe a chave primária lógica da tabela com year, state_id e case_number",
            "Together with year, state_id and case_number forms the logical primary key of the table",
            "Junto con year, state_id y case_number forma la clave primaria lógica de la tabla",
        ),
    ),
    c(
        "unit_type_code",
        "STRING",
        "UNITTYPE",
        "Tipo de unidade: veículo em movimento, estacionado ou fora de circulação",
        "Type of unit: vehicle in transport, parked, or out of transport",
        "Tipo de unidad: vehículo en movimiento, estacionado o fuera de circulación",
        "2005(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "occupants_count",
        "INT64",
        "NUMOCCS|OCUPANTS",
        "Número de ocupantes do veículo",
        "Number of occupants of the vehicle",
        "Número de ocupantes del vehículo",
        FULL,
        unit="person",
        obs=(
            "Códigos de desconhecido (99 até 2009, 99 e 999 a partir de 2010) foram convertidos em nulo",
            "Unknown codes (99 through 2009; 99 and 999 from 2010) were converted to null",
            "Los códigos de desconocido (99 hasta 2009; 99 y 999 desde 2010) se convirtieron en nulo",
        ),
    ),
    c(
        "hit_and_run_code",
        "STRING",
        "HIT_RUN",
        "Indica se o veículo evadiu-se do local do acidente",
        "Whether the vehicle left the scene of the crash",
        "Indica si el vehículo huyó del lugar del accidente",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "registration_state_code",
        "STRING",
        "REG_STAT",
        "Estado de emplacamento do veículo",
        "State in which the vehicle is registered",
        "Estado de matriculación del vehículo",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "owner_code",
        "STRING",
        "OWNER",
        "Condição de propriedade do veículo",
        "Ownership status of the vehicle",
        "Condición de propiedad del vehículo",
        "1991(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "make_code",
        "STRING",
        "MAKE",
        "Marca do veículo",
        "Make of the vehicle",
        "Marca del vehículo",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "model_code",
        "STRING",
        "MODEL",
        "Modelo do veículo, codificado dentro da marca",
        "Model of the vehicle, coded within the make",
        "Modelo del vehículo, codificado dentro de la marca",
        FULL,
        obs=(
            "Não coberto pelo dicionário porque a fonte não publica um conjunto de rótulos para este campo isoladamente: o código de modelo só é interpretável em conjunto com make_code, e a combinação rotulada está em make_model_code",
            "Not covered by the dictionary because the source publishes no label set for this field on its own: the model code is interpretable only together with make_code, and the labelled combination is in make_model_code",
            "No cubierto por el diccionario porque la fuente no publica un conjunto de etiquetas para este campo por separado: el código de modelo solo es interpretable junto con make_code, y la combinación etiquetada está en make_model_code",
        ),
    ),
    c(
        "make_model_code",
        "STRING",
        "MAK_MOD",
        "Combinação codificada de marca e modelo do veículo",
        "Coded combination of the vehicle's make and model",
        "Combinación codificada de marca y modelo del vehículo",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "body_type_code",
        "STRING",
        "BODY_TYP",
        "Tipo de carroceria do veículo",
        "Body type of the vehicle",
        "Tipo de carrocería del vehículo",
        FULL,
        dic=True,
        obs=(
            "Conjunto de códigos revisado onze vezes entre 1975 e 2024; a comparação entre eras exige a tabela dicionario",
            "The code set was revised eleven times between 1975 and 2024; comparing across eras requires the dicionario table",
            "El conjunto de códigos fue revisado once veces entre 1975 y 2024; la comparación entre eras exige la tabla dicionario",
        ),
    ),
    c(
        "model_year",
        "INT64",
        "MOD_YEAR",
        "Ano-modelo do veículo",
        "Model year of the vehicle",
        "Año-modelo del vehículo",
        FULL,
        unit="year",
        obs=(
            "Códigos de desconhecido e não reportado (0, 9998, 9999 e, nas eras antigas, 99) foram convertidos em nulo",
            "Unknown and not-reported codes (0, 9998, 9999 and, in the older eras, 99) were converted to null",
            "Los códigos de desconocido y no reportado (0, 9998, 9999 y, en las eras antiguas, 99) se convirtieron en nulo",
        ),
    ),
    c(
        "vehicle_identification_number",
        "STRING",
        "VIN",
        "Número de identificação do veículo (VIN), conforme publicado pela NHTSA",
        "Vehicle identification number (VIN), as published by NHTSA",
        "Número de identificación del vehículo (VIN), según lo publica la NHTSA",
        FULL,
        obs=(
            "Publicado integralmente pela NHTSA no arquivo de uso público; identifica o veículo, não o condutor",
            "Published in full by NHTSA in the public use file; it identifies the vehicle, not the driver",
            "Publicado íntegramente por la NHTSA en el archivo de uso público; identifica al vehículo, no al conductor",
        ),
    ),
    c(
        "tow_vehicle_code",
        "STRING",
        "TOW_VEH",
        "Indica se o veículo rebocava reboque ou semirreboque",
        "Whether the vehicle was pulling a trailer or semitrailer",
        "Indica si el vehículo remolcaba un remolque o semirremolque",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "jackknife_code",
        "STRING",
        "J_KNIFE",
        "Indica ocorrência de tesouramento (jackknife) em veículo articulado",
        "Whether an articulated vehicle jackknifed",
        "Indica si un vehículo articulado sufrió tijereteo (jackknife)",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "gross_vehicle_weight_rating_code",
        "STRING",
        "GVWR",
        "Faixa de peso bruto total combinado do veículo",
        "Band of the vehicle's gross vehicle weight rating",
        "Banda de peso bruto total del vehículo",
        "2000(1)2019",
        dic=True,
        obs=ERA,
    ),
    c(
        "vehicle_configuration_code",
        "STRING",
        "V_CONFIG",
        "Configuração do veículo de carga",
        "Configuration of the cargo vehicle",
        "Configuración del vehículo de carga",
        "1991(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "cargo_body_type_code",
        "STRING",
        "CARGO_BT",
        "Tipo de carroceria de carga",
        "Cargo body type",
        "Tipo de carrocería de carga",
        "1991(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "hazardous_material_involvement_code",
        "STRING",
        "HAZ_INV|HAZ_CARG",
        "Indica envolvimento de carga perigosa",
        "Whether hazardous cargo was involved",
        "Indica involucramiento de carga peligrosa",
        "1982(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "bus_use_code",
        "STRING",
        "BUS_USE",
        "Uso do veículo como ônibus e sua finalidade",
        "Use of the vehicle as a bus, and for what purpose",
        "Uso del vehículo como autobús y su finalidad",
        "2000(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "special_use_code",
        "STRING",
        "SPEC_USE",
        "Uso especial do veículo (táxi, polícia, ambulância, escolar)",
        "Special use of the vehicle (taxi, police, ambulance, school)",
        "Uso especial del vehículo (taxi, policía, ambulancia, escolar)",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "emergency_use_code",
        "STRING",
        "EMER_USE",
        "Indica se o veículo estava em atendimento de emergência",
        "Whether the vehicle was responding to an emergency",
        "Indica si el vehículo estaba en atención de emergencia",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "travel_speed",
        "INT64",
        "TRAV_SP",
        "Velocidade estimada do veículo antes do acidente, em milhas por hora",
        "Estimated travel speed of the vehicle before the crash, in miles per hour",
        "Velocidad estimada del vehículo antes del accidente, en millas por hora",
        FULL,
        unit="mile_per_hour",
        obs=(
            "Códigos de desconhecido e não reportado foram convertidos em nulo; a faixa de sentinelas mudou de 97-99 para 997-999 em 2010, e tratá-los como velocidade produziria valores impossíveis",
            "Unknown and not-reported codes were converted to null; the sentinel band moved from 97-99 to 997-999 in 2010, and reading them as a speed would produce impossible values",
            "Los códigos de desconocido y no reportado se convirtieron en nulo; la banda de centinelas cambió de 97-99 a 997-999 en 2010, y tratarlos como velocidad produciría valores imposibles",
        ),
    ),
    c(
        "rollover_code",
        "STRING",
        "ROLLOVER",
        "Ocorrência e tipo de capotamento",
        "Occurrence and type of rollover",
        "Ocurrencia y tipo de vuelco",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "initial_impact_point_code",
        "STRING",
        "IMPACT1",
        "Ponto de impacto inicial no veículo, em posições de relógio",
        "Initial point of impact on the vehicle, in clock positions",
        "Punto de impacto inicial en el vehículo, en posiciones de reloj",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "extent_of_damage_code",
        "STRING",
        "DEFORMED",
        "Extensão dos danos ao veículo",
        "Extent of damage to the vehicle",
        "Extensión de los daños al vehículo",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "most_harmful_event_code",
        "STRING",
        "M_HARM",
        "Evento que produziu o dano mais grave a este veículo",
        "Event that produced the most severe damage to this vehicle",
        "Evento que produjo el daño más grave a este vehículo",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "fire_occurrence_code",
        "STRING",
        "FIRE_EXP",
        "Indica ocorrência de incêndio no veículo",
        "Whether fire occurred in the vehicle",
        "Indica ocurrencia de incendio en el vehículo",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "deaths_count",
        "INT64",
        "DEATHS",
        "Número de mortes de ocupantes deste veículo",
        "Number of deaths among occupants of this vehicle",
        "Número de muertes de ocupantes de este vehículo",
        FULL,
        unit="person",
    ),
    c(
        "driver_present_code",
        "STRING",
        "DR_PRES",
        "Indica se havia condutor no veículo",
        "Whether a driver was present in the vehicle",
        "Indica si había conductor en el vehículo",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "driver_drinking_code",
        "STRING",
        "DR_DRINK",
        "Envolvimento do condutor com álcool segundo o relato policial",
        "Police-reported alcohol involvement of the driver",
        "Involucramiento del conductor con alcohol según el informe policial",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "driver_license_state_code",
        "STRING",
        "L_STATE",
        "Estado emissor da habilitação do condutor",
        "State that issued the driver's licence",
        "Estado emisor de la licencia del conductor",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "driver_license_status_code",
        "STRING",
        "L_STATUS",
        "Situação da habilitação do condutor no momento do acidente",
        "Status of the driver's licence at the time of the crash",
        "Situación de la licencia del conductor en el momento del accidente",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "driver_license_compliance_code",
        "STRING",
        "L_COMPL",
        "Conformidade da habilitação com a categoria do veículo conduzido",
        "Compliance of the licence with the class of vehicle being driven",
        "Conformidad de la licencia con la categoría del vehículo conducido",
        "1987(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "commercial_license_status_code",
        "STRING",
        "CDL_STAT",
        "Situação da habilitação comercial do condutor",
        "Status of the driver's commercial licence",
        "Situación de la licencia comercial del conductor",
        "1991(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "driver_height",
        "INT64",
        "DR_HGT",
        "Altura declarada do condutor, em polegadas",
        "Reported height of the driver, in inches",
        "Estatura declarada del conductor, en pulgadas",
        "1998(1)2024",
        unit="inch",
        obs=(
            "Códigos de desconhecido e não reportado (998, 999) foram convertidos em nulo",
            "Unknown and not-reported codes (998, 999) were converted to null",
            "Los códigos de desconocido y no reportado (998, 999) se convirtieron en nulo",
        ),
    ),
    c(
        "driver_weight",
        "INT64",
        "DR_WGT",
        "Peso declarado do condutor, em libras",
        "Reported weight of the driver, in pounds",
        "Peso declarado del conductor, en libras",
        "1998(1)2024",
        unit="pound",
        obs=(
            "Códigos de desconhecido e não reportado (997, 998, 999) foram convertidos em nulo",
            "Unknown and not-reported codes (997, 998, 999) were converted to null",
            "Los códigos de desconocido y no reportado (997, 998, 999) se convirtieron en nulo",
        ),
    ),
    c(
        "previous_crashes_count",
        "INT64",
        "PREV_ACC",
        "Número de acidentes anteriores no histórico do condutor",
        "Number of previous crashes in the driver's record",
        "Número de accidentes anteriores en el historial del conductor",
        FULL,
        unit="crash",
        obs=(
            "Códigos de desconhecido e não aplicável (98, 99, 998, 999) foram convertidos em nulo",
            "Unknown and not-applicable codes (98, 99, 998, 999) were converted to null",
            "Los códigos de desconocido y no aplicable (98, 99, 998, 999) se convirtieron en nulo",
        ),
    ),
    c(
        "previous_suspensions_count",
        "INT64",
        "PREV_SUS|PREV_SUS1",
        "Número de suspensões ou cassações anteriores da habilitação",
        "Number of previous licence suspensions or revocations",
        "Número de suspensiones o revocaciones anteriores de la licencia",
        FULL,
        unit="occurrence",
        obs=(
            "Publicada como PREV_SUS até 2017 e como PREV_SUS1 a partir de 2018, quando o campo foi desdobrado em três",
            "Published as PREV_SUS through 2017 and as PREV_SUS1 from 2018, when the field was split into three",
            "Publicada como PREV_SUS hasta 2017 y como PREV_SUS1 desde 2018, cuando el campo fue desdoblado en tres",
        ),
    ),
    c(
        "previous_dwi_convictions_count",
        "INT64",
        "PREV_DWI",
        "Número de condenações anteriores por dirigir sob influência",
        "Number of previous convictions for driving while intoxicated",
        "Número de condenas anteriores por conducir bajo influencia",
        FULL,
        unit="occurrence",
    ),
    c(
        "previous_speeding_convictions_count",
        "INT64",
        "PREV_SPD",
        "Número de condenações anteriores por excesso de velocidade",
        "Number of previous convictions for speeding",
        "Número de condenas anteriores por exceso de velocidad",
        FULL,
        unit="occurrence",
    ),
    c(
        "previous_other_convictions_count",
        "INT64",
        "PREV_OTH",
        "Número de outras condenações anteriores de trânsito",
        "Number of other previous traffic convictions",
        "Número de otras condenas anteriores de tránsito",
        FULL,
        unit="occurrence",
    ),
    c(
        "speeding_related_code",
        "STRING",
        "SPEEDREL",
        "Indica se a velocidade contribuiu para o acidente",
        "Whether speed contributed to the crash",
        "Indica si la velocidad contribuyó al accidente",
        "2009(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "trafficway_description_code",
        "STRING",
        "VTRAFWAY",
        "Sentido de circulação e separação da via, registrados por veículo",
        "Direction of travel and division of the trafficway, recorded per vehicle",
        "Sentido de circulación y separación de la vía, registrados por vehículo",
        "2010(1)2024",
        dic=True,
        obs=(
            "Sucessora, no nível do veículo, de trafficway_flow_code da tabela crash",
            "Vehicle-level successor to trafficway_flow_code in the crash table",
            "Sucesora, a nivel del vehículo, de trafficway_flow_code de la tabla crash",
        ),
    ),
    c(
        "vehicle_number_of_lanes_code",
        "STRING",
        "VNUM_LAN",
        "Número de faixas de rolamento, registrado por veículo",
        "Number of travel lanes, recorded per vehicle",
        "Número de carriles, registrado por vehículo",
        "2010(1)2024",
        dic=True,
        obs=(
            "Sucessora, no nível do veículo, de number_of_lanes_code da tabela crash",
            "Vehicle-level successor to number_of_lanes_code in the crash table",
            "Sucesora, a nivel del vehículo, de number_of_lanes_code de la tabla crash",
        ),
    ),
    c(
        "vehicle_speed_limit",
        "INT64",
        "VSPD_LIM",
        "Velocidade máxima regulamentada da via, registrada por veículo, em milhas por hora",
        "Posted speed limit of the trafficway, recorded per vehicle, in miles per hour",
        "Velocidad máxima reglamentada de la vía, registrada por vehículo, en millas por hora",
        "2010(1)2024",
        unit="mile_per_hour",
        obs=(
            "Sucessora, no nível do veículo, de speed_limit da tabela crash; códigos de não aplicável e desconhecido foram convertidos em nulo",
            "Vehicle-level successor to speed_limit in the crash table; not-applicable and unknown codes were converted to null",
            "Sucesora, a nivel del vehículo, de speed_limit de la tabla crash; los códigos de no aplicable y desconocido se convirtieron en nulo",
        ),
    ),
    c(
        "vehicle_roadway_alignment_code",
        "STRING",
        "VALIGN",
        "Alinhamento horizontal da via, registrado por veículo",
        "Horizontal alignment of the roadway, recorded per vehicle",
        "Alineación horizontal de la vía, registrada por vehículo",
        "2010(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "vehicle_roadway_profile_code",
        "STRING",
        "VPROFILE",
        "Perfil vertical da via, registrado por veículo",
        "Vertical profile of the roadway, recorded per vehicle",
        "Perfil vertical de la vía, registrado por vehículo",
        "2010(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "vehicle_surface_condition_code",
        "STRING",
        "VSURCOND",
        "Condição do pavimento, registrada por veículo",
        "Road surface condition, recorded per vehicle",
        "Condición del pavimento, registrada por vehículo",
        "2010(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "vehicle_traffic_control_code",
        "STRING",
        "VTRAFCON",
        "Dispositivo de controle de tráfego, registrado por veículo",
        "Traffic control device, recorded per vehicle",
        "Dispositivo de control de tráfico, registrado por vehículo",
        "2010(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "vehicle_traffic_control_functioning_code",
        "STRING",
        "VTCONT_F",
        "Funcionamento do dispositivo de controle de tráfego, registrado por veículo",
        "Whether the traffic control device was functioning, recorded per vehicle",
        "Funcionamiento del dispositivo de control de tráfico, registrado por vehículo",
        "2010(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "crash_type_code",
        "STRING",
        "ACC_TYPE",
        "Tipo de acidente segundo a tipologia pré-colisão da NHTSA",
        "Crash type under NHTSA's pre-crash typology",
        "Tipo de accidente según la tipología precolisión de la NHTSA",
        "2010(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "driver_maneuver_code",
        "STRING",
        "P_CRASH2",
        "Manobra crítica que precedeu o acidente",
        "Critical event that preceded the crash",
        "Maniobra crítica que precedió al accidente",
        "2010(1)2024",
        dic=True,
        obs=ERA,
    ),
]

PERSON = [
    c(
        "year",
        "INT64",
        "",
        "Ano-calendário do acidente",
        "Calendar year of the crash",
        "Año calendario del accidente",
        FULL,
        dirc=DIR_YEAR,
        unit="year",
        obs=(
            "Coluna de particionamento; derivada do arquivo anual de origem",
            "Partition column; taken from the source annual file",
            "Columna de particionamiento; derivada del archivo anual de origen",
        ),
    ),
    c(
        "state_id",
        "STRING",
        "STATE",
        "Código FIPS de duas posições do estado onde ocorreu o acidente",
        "Two-digit FIPS code of the state where the crash occurred",
        "Código FIPS de dos posiciones del estado donde ocurrió el accidente",
        FULL,
        dirc=DIR_STATE,
    ),
    c(
        "case_number",
        "STRING",
        "ST_CASE",
        "Número do caso atribuído pelo estado, único dentro do par estado-ano",
        "Case number assigned by the state, unique within the state-year pair",
        "Número de caso asignado por el estado, único dentro del par estado-año",
        FULL,
        obs=(
            "Chave de ligação com as tabelas crash e vehicle",
            "Join key to the crash and vehicle tables",
            "Clave de unión con las tablas crash y vehicle",
        ),
    ),
    c(
        "vehicle_number",
        "INT64",
        "VEH_NO",
        "Número do veículo em que a pessoa estava; 0 identifica quem não estava em veículo automotor",
        "Number of the vehicle the person was in; 0 identifies someone not in a motor vehicle",
        "Número del vehículo en que estaba la persona; 0 identifica a quien no estaba en un vehículo automotor",
        FULL,
        unit="vehicle",
        obs=(
            "Pedestres, ciclistas e demais não ocupantes recebem vehicle_number igual a 0 e não têm correspondência na tabela vehicle",
            "Pedestrians, cyclists and other non-occupants take vehicle_number 0 and have no counterpart row in the vehicle table",
            "Peatones, ciclistas y demás no ocupantes reciben vehicle_number igual a 0 y no tienen correspondencia en la tabla vehicle",
        ),
    ),
    c(
        "person_number",
        "INT64",
        "PER_NO",
        "Número sequencial da pessoa dentro do veículo ou do acidente",
        "Sequential number of the person within the vehicle or the crash",
        "Número secuencial de la persona dentro del vehículo o del accidente",
        FULL,
        unit="person",
        obs=(
            "Compõe a chave primária lógica da tabela com year, state_id, case_number e vehicle_number",
            "Together with year, state_id, case_number and vehicle_number forms the logical primary key of the table",
            "Junto con year, state_id, case_number y vehicle_number forma la clave primaria lógica de la tabla",
        ),
    ),
    c(
        "age",
        "INT64",
        "AGE",
        "Idade da pessoa em anos completos no momento do acidente",
        "Age of the person in completed years at the time of the crash",
        "Edad de la persona en años cumplidos en el momento del accidente",
        FULL,
        unit="year",
        obs=(
            "Códigos de desconhecido e não reportado foram convertidos em nulo; a sentinela mudou de 99 para o par 998/999 em 2009, de modo que uma leitura numérica ingênua registraria idades de 99 ou 999 anos",
            "Unknown and not-reported codes were converted to null; the sentinel moved from 99 to the pair 998/999 in 2009, so a naive numeric read would record ages of 99 or 999 years",
            "Los códigos de desconocido y no reportado se convirtieron en nulo; el centinela cambió de 99 al par 998/999 en 2009, de modo que una lectura numérica ingenua registraría edades de 99 o 999 años",
        ),
    ),
    c(
        "sex_code",
        "STRING",
        "SEX",
        "Sexo da pessoa",
        "Sex of the person",
        "Sexo de la persona",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "person_type_code",
        "STRING",
        "PER_TYP",
        "Tipo de pessoa: condutor, passageiro, pedestre, ciclista ou outro não ocupante",
        "Type of person: driver, passenger, pedestrian, cyclist or other non-occupant",
        "Tipo de persona: conductor, pasajero, peatón, ciclista u otro no ocupante",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "injury_severity_code",
        "STRING",
        "INJ_SEV",
        "Gravidade da lesão sofrida pela pessoa",
        "Severity of the injury sustained by the person",
        "Gravedad de la lesión sufrida por la persona",
        FULL,
        dic=True,
        obs=(
            "A escala foi revisada seis vezes entre 1975 e 2024, incluindo a adoção da escala KABCO em 2010; comparações entre eras exigem a tabela dicionario",
            "The scale was revised six times between 1975 and 2024, including the move to the KABCO scale in 2010; comparisons across eras require the dicionario table",
            "La escala fue revisada seis veces entre 1975 y 2024, incluida la adopción de la escala KABCO en 2010; las comparaciones entre eras exigen la tabla dicionario",
        ),
    ),
    c(
        "seating_position_code",
        "STRING",
        "SEAT_POS",
        "Posição ocupada pela pessoa no veículo",
        "Seating position occupied by the person in the vehicle",
        "Posición ocupada por la persona en el vehículo",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "restraint_use_code",
        "STRING",
        "REST_USE|MAN_REST",
        "Uso de dispositivo de retenção pela pessoa",
        "Restraint use by the person",
        "Uso de dispositivo de retención por la persona",
        FULL,
        dic=True,
        obs=(
            "Publicada como MAN_REST até 1990 e como REST_USE a partir de 1991; o conjunto de códigos foi revisado cinco vezes desde então",
            "Published as MAN_REST through 1990 and as REST_USE from 1991; the code set has been revised five times since",
            "Publicada como MAN_REST hasta 1990 y como REST_USE desde 1991; el conjunto de códigos fue revisado cinco veces desde entonces",
        ),
    ),
    c(
        "restraint_misuse_code",
        "STRING",
        "REST_MIS",
        "Indica uso incorreto do dispositivo de retenção",
        "Whether the restraint was used incorrectly",
        "Indica uso incorrecto del dispositivo de retención",
        "2010(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "helmet_use_code",
        "STRING",
        "HELM_USE",
        "Uso de capacete por ocupante de motocicleta ou ciclista",
        "Helmet use by a motorcyclist or cyclist",
        "Uso de casco por ocupante de motocicleta o ciclista",
        "2019(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "air_bag_code",
        "STRING",
        "AIR_BAG|AUT_REST",
        "Presença e acionamento de airbag na posição ocupada",
        "Presence and deployment of an air bag at the occupied position",
        "Presencia y activación de airbag en la posición ocupada",
        FULL,
        dic=True,
        obs=(
            "Publicada como AUT_REST (retenção automática) até 1990 e como AIR_BAG a partir de 1991, com conjuntos de códigos distintos",
            "Published as AUT_REST (automatic restraint) through 1990 and as AIR_BAG from 1991, with distinct code sets",
            "Publicada como AUT_REST (retención automática) hasta 1990 y como AIR_BAG desde 1991, con conjuntos de códigos distintos",
        ),
    ),
    c(
        "ejection_code",
        "STRING",
        "EJECTION",
        "Grau de ejeção da pessoa do veículo",
        "Extent to which the person was ejected from the vehicle",
        "Grado de eyección de la persona del vehículo",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "ejection_path_code",
        "STRING",
        "EJ_PATH",
        "Abertura pela qual a pessoa foi ejetada",
        "Opening through which the person was ejected",
        "Abertura por la cual la persona fue eyectada",
        "1991(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "extrication_code",
        "STRING",
        "EXTRICAT",
        "Indica se foi necessário desencarcerar a pessoa",
        "Whether the person had to be extricated",
        "Indica si fue necesario desencarcelar a la persona",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "police_reported_alcohol_code",
        "STRING",
        "DRINKING",
        "Envolvimento com álcool segundo o relato policial",
        "Police-reported alcohol involvement",
        "Involucramiento con alcohol según el informe policial",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "alcohol_test_status_code",
        "STRING",
        "ALC_STATUS",
        "Situação do teste de alcoolemia",
        "Status of the alcohol test",
        "Situación de la prueba de alcoholemia",
        "2009(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "alcohol_test_type_code",
        "STRING",
        "ATST_TYP",
        "Tipo de teste de alcoolemia aplicado",
        "Type of alcohol test administered",
        "Tipo de prueba de alcoholemia aplicada",
        "1998(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "alcohol_test_result_code",
        "STRING",
        "ALC_RES|TEST_RES",
        "Resultado do teste de alcoolemia, no código original da fonte",
        "Result of the alcohol test, in the source's original code",
        "Resultado de la prueba de alcoholemia, en el código original de la fuente",
        FULL,
        dic=True,
        obs=(
            "Mantida como código para preservar as sentinelas de teste recusado, não realizado e resultado desconhecido; o valor numérico interpretado está em blood_alcohol_content",
            "Kept as a code so the test-refused, test-not-given and result-unknown sentinels are preserved; the interpreted numeric value is in blood_alcohol_content",
            "Mantenida como código para preservar los centinelas de prueba rechazada, no realizada y resultado desconocido; el valor numérico interpretado está en blood_alcohol_content",
        ),
    ),
    c(
        "blood_alcohol_content",
        "FLOAT64",
        "",
        "Concentração de álcool no sangue, em gramas por decilitro",
        "Blood alcohol concentration, in grams per decilitre",
        "Concentración de alcohol en sangre, en gramos por decilitro",
        FULL,
        unit="gram_per_deciliter",
        obs=(
            "Derivada de alcohol_test_result_code harmonizando a mudança de escala da fonte: até 2014 o código traz a concentração multiplicada por 100 e as sentinelas ocupam 95-99; a partir de 2015 traz a concentração multiplicada por 1000 e as sentinelas ocupam 995-999. Somente códigos dentro da faixa válida de cada era foram convertidos; todos os demais são nulos",
            "Derived from alcohol_test_result_code by harmonising the source's scale change: through 2014 the code carries the concentration multiplied by 100 with sentinels at 95-99; from 2015 it carries the concentration multiplied by 1000 with sentinels at 995-999. Only codes inside each era's valid band were converted; every other code is null",
            "Derivada de alcohol_test_result_code armonizando el cambio de escala de la fuente: hasta 2014 el código trae la concentración multiplicada por 100 y los centinelas ocupan 95-99; desde 2015 trae la concentración multiplicada por 1000 y los centinelas ocupan 995-999. Solo se convirtieron los códigos dentro de la banda válida de cada era; todos los demás son nulos",
        ),
    ),
    c(
        "drug_involvement_code",
        "STRING",
        "DRUGS",
        "Envolvimento com drogas segundo o relato policial",
        "Police-reported drug involvement",
        "Involucramiento con drogas según el informe policial",
        "1991(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "drug_test_status_code",
        "STRING",
        "DSTATUS",
        "Situação do teste toxicológico",
        "Status of the drug test",
        "Situación de la prueba toxicológica",
        "2009(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "transported_to_facility_code",
        "STRING",
        "HOSPITAL",
        "Meio de transporte da pessoa até unidade de saúde",
        "Means by which the person was transported to a medical facility",
        "Medio de transporte de la persona hasta una unidad de salud",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "died_at_scene_code",
        "STRING",
        "DOA",
        "Indica se a pessoa chegou morta ou morreu no local",
        "Whether the person was dead on arrival or died at the scene",
        "Indica si la persona llegó muerta o murió en el lugar",
        "2001(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "death_date",
        "DATE",
        "",
        "Data do óbito",
        "Date of death",
        "Fecha del fallecimiento",
        FULL,
        obs=(
            "Derivada de DEATH_MO, DEATH_DA e DEATH_YR; nula para sobreviventes e quando qualquer componente traz código de desconhecido",
            "Derived from DEATH_MO, DEATH_DA and DEATH_YR; null for survivors and where any component carries an unknown code",
            "Derivada de DEATH_MO, DEATH_DA y DEATH_YR; nula para sobrevivientes y cuando cualquier componente trae código de desconocido",
        ),
    ),
    c(
        "death_hour",
        "INT64",
        "DEATH_HR",
        "Hora do óbito, no relógio de 24 horas",
        "Hour of death, on the 24-hour clock",
        "Hora del fallecimiento, en el reloj de 24 horas",
        FULL,
        unit="hour",
    ),
    c(
        "death_minute",
        "INT64",
        "DEATH_MN",
        "Minuto do óbito",
        "Minute of death",
        "Minuto del fallecimiento",
        FULL,
        unit="minute",
    ),
    c(
        "survival_hours",
        "INT64",
        "LAG_HRS",
        "Horas decorridas entre o acidente e o óbito",
        "Hours elapsed between the crash and death",
        "Horas transcurridas entre el accidente y el fallecimiento",
        FULL,
        unit="hour",
        obs=(
            "Somada a survival_minutes dá o intervalo até o óbito; o FARS só inclui mortes ocorridas em até 30 dias após o acidente",
            "Together with survival_minutes gives the interval to death; FARS only includes deaths occurring within 30 days of the crash",
            "Sumada a survival_minutes da el intervalo hasta el fallecimiento; el FARS solo incluye muertes ocurridas dentro de los 30 días posteriores al accidente",
        ),
    ),
    c(
        "survival_minutes",
        "INT64",
        "LAG_MINS",
        "Minutos decorridos, além das horas, entre o acidente e o óbito",
        "Minutes elapsed, beyond the hours, between the crash and death",
        "Minutos transcurridos, además de las horas, entre el accidente y el fallecimiento",
        FULL,
        unit="minute",
    ),
    c(
        "work_injury_code",
        "STRING",
        "WORK_INJ",
        "Indica se a lesão ocorreu no exercício do trabalho",
        "Whether the injury occurred in the course of work",
        "Indica si la lesión ocurrió en el ejercicio del trabajo",
        "1987(1)2024",
        dic=True,
        obs=ERA,
    ),
    c(
        "race_code",
        "STRING",
        "RACE",
        "Raça da pessoa falecida, conforme o atestado de óbito",
        "Race of the deceased person, as recorded on the death certificate",
        "Raza de la persona fallecida, según el certificado de defunción",
        "1999(1)2018",
        dic=True,
        obs=(
            "Preenchida apenas para pessoas falecidas, a partir do atestado de óbito; descontinuada no arquivo person após 2018, quando passou a ser publicada em arquivo próprio",
            "Populated only for deceased people, from the death certificate; discontinued in the person file after 2018, when it moved to a file of its own",
            "Registrada solo para personas fallecidas, a partir del certificado de defunción; descontinuada en el archivo person después de 2018, cuando pasó a publicarse en un archivo propio",
        ),
    ),
    c(
        "hispanic_origin_code",
        "STRING",
        "HISPANIC",
        "Origem hispânica da pessoa falecida, conforme o atestado de óbito",
        "Hispanic origin of the deceased person, as recorded on the death certificate",
        "Origen hispano de la persona fallecida, según el certificado de defunción",
        "1999(1)2024",
        dic=True,
        obs=(
            "Preenchida apenas para pessoas falecidas, a partir do atestado de óbito",
            "Populated only for deceased people, from the death certificate",
            "Registrada solo para personas fallecidas, a partir del certificado de defunción",
        ),
    ),
    c(
        "non_motorist_location_code",
        "STRING",
        "LOCATION",
        "Posição do não ocupante na via no momento do acidente",
        "Location of the non-occupant on the roadway at the time of the crash",
        "Posición del no ocupante en la vía en el momento del accidente",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "striking_vehicle_number",
        "STRING",
        "STR_VEH",
        "Número do veículo que atingiu o não ocupante",
        "Number of the vehicle that struck the non-occupant",
        "Número del vehículo que impactó al no ocupante",
        "2011(1)2024",
        obs=(
            "Referencia vehicle_number dentro do mesmo acidente; 0 indica que nenhum veículo atingiu a pessoa. Não é uma coluna categórica e portanto não é coberta pelo dicionário",
            "References vehicle_number within the same crash; 0 means no vehicle struck the person. It is not a categorical column and so is not covered by the dictionary",
            "Referencia vehicle_number dentro del mismo accidente; 0 indica que ningún vehículo impactó a la persona. No es una columna categórica y por lo tanto no está cubierta por el diccionario",
        ),
    ),
    c(
        "body_type_code",
        "STRING",
        "BODY_TYP",
        "Tipo de carroceria do veículo em que a pessoa estava",
        "Body type of the vehicle the person was in",
        "Tipo de carrocería del vehículo en que estaba la persona",
        FULL,
        dic=True,
        obs=(
            "Repetida da tabela vehicle para permitir análise no nível da pessoa sem junção",
            "Repeated from the vehicle table so person-level analysis needs no join",
            "Repetida de la tabla vehicle para permitir análisis a nivel de la persona sin unión",
        ),
    ),
    c(
        "make_code",
        "STRING",
        "MAKE",
        "Marca do veículo em que a pessoa estava",
        "Make of the vehicle the person was in",
        "Marca del vehículo en que estaba la persona",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "model_year",
        "INT64",
        "MOD_YEAR",
        "Ano-modelo do veículo em que a pessoa estava",
        "Model year of the vehicle the person was in",
        "Año-modelo del vehículo en que estaba la persona",
        FULL,
        unit="year",
        obs=(
            "Códigos de desconhecido e não reportado foram convertidos em nulo",
            "Unknown and not-reported codes were converted to null",
            "Los códigos de desconocido y no reportado se convirtieron en nulo",
        ),
    ),
    c(
        "rollover_code",
        "STRING",
        "ROLLOVER",
        "Ocorrência e tipo de capotamento do veículo em que a pessoa estava",
        "Occurrence and type of rollover of the vehicle the person was in",
        "Ocurrencia y tipo de vuelco del vehículo en que estaba la persona",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "first_harmful_event_code",
        "STRING",
        "HARM_EV",
        "Primeiro evento lesivo do acidente",
        "First harmful event of the crash",
        "Primer evento lesivo del accidente",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "manner_of_collision_code",
        "STRING",
        "MAN_COLL",
        "Posição relativa dos veículos no primeiro impacto",
        "Orientation of the vehicles in the first collision",
        "Posición relativa de los vehículos en el primer impacto",
        FULL,
        dic=True,
        obs=ERA,
    ),
    c(
        "school_bus_related_code",
        "STRING",
        "SCH_BUS",
        "Indica se um ônibus escolar esteve envolvido no acidente",
        "Whether a school bus was involved in the crash",
        "Indica si un autobús escolar estuvo involucrado en el accidente",
        FULL,
        dic=True,
        obs=ERA,
    ),
]

DICIONARIO = [
    c(
        "id_tabela",
        "STRING",
        "",
        "Nome da tabela a que a coluna codificada pertence",
        "Name of the table the coded column belongs to",
        "Nombre de la tabla a la que pertenece la columna codificada",
    ),
    c(
        "nome_coluna",
        "STRING",
        "",
        "Nome da coluna codificada",
        "Name of the coded column",
        "Nombre de la columna codificada",
    ),
    c(
        "chave",
        "STRING",
        "",
        "Valor armazenado na coluna",
        "Value stored in the column",
        "Valor almacenado en la columna",
    ),
    c(
        "cobertura_temporal",
        "STRING",
        "",
        "Anos em que o par código-significado vigorou, na notação início(intervalo)fim",
        "Years over which the code-meaning pair was in force, in start(interval)end notation",
        "Años en que rigió el par código-significado, en la notación inicio(intervalo)fin",
    ),
    c(
        "valor",
        "STRING",
        "",
        "Significado do valor armazenado",
        "Meaning of the stored value",
        "Significado del valor almacenado",
    ),
]

TABLES = {
    "crash": CRASH,
    "vehicle": VEHICLE,
    "person": PERSON,
    "dicionario": DICIONARIO,
}


def main() -> None:
    ARCH.mkdir(parents=True, exist_ok=True)
    for table, cols in TABLES.items():
        names = [c["name"] for c in cols]
        assert len(names) == len(set(names)), (
            f"{table}: duplicate column names"
        )
        for col in cols:
            if col["bigquery_type"] in ("INT64", "FLOAT64"):
                assert col["measurement_unit"], (
                    f"{table}.{col['name']}: numeric column without a measurement unit"
                )
            for lang in ("pt", "en", "es"):
                d = col[f"description_{lang}"]
                assert d and d[0].isupper(), (
                    f"{table}.{col['name']}: description_{lang} must start uppercase"
                )
                assert not d.endswith("."), (
                    f"{table}.{col['name']}: description_{lang} must not end with a period"
                )
        path = ARCH / f"sheet_{table}.csv"
        # lineterminator is explicit: csv defaults to \r\n, which the
        # mixed-line-ending pre-commit hook then rewrites on every regeneration.
        with open(path, "w", encoding="utf-8", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=FIELDS, lineterminator="\n")
            w.writeheader()
            w.writerows(cols)
        print(f"wrote {path.name}: {len(cols)} columns")


if __name__ == "__main__":
    main()
