{{
    config(
        schema="us_ed_nces_ccd",
        alias="district_finance",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 1989, "end": 2026, "interval": 1},
        },
        cluster_by=["state_id", "agency_id"],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(agency_id as string) agency_id,
    safe_cast(state_id as string) state_id,
    safe_cast(census_id as string) census_id,
    safe_cast(enrollment_fall_responsible as int64) enrollment_fall_responsible,
    safe_cast(enrollment_fall_school as int64) enrollment_fall_school,
    safe_cast(rev_total as float64) rev_total,
    safe_cast(rev_fed_total as float64) rev_fed_total,
    safe_cast(rev_fed_state_title_i as float64) rev_fed_state_title_i,
    safe_cast(rev_fed_state_idea as float64) rev_fed_state_idea,
    safe_cast(rev_fed_state_vocational as float64) rev_fed_state_vocational,
    safe_cast(rev_fed_state_eff_instruction as float64) rev_fed_state_eff_instruction,
    safe_cast(rev_fed_state_supp_ed as float64) rev_fed_state_supp_ed,
    safe_cast(rev_fed_state_supp_21st_lc as float64) rev_fed_state_supp_21st_lc,
    safe_cast(rev_fed_state_rural_lowinc_sch as float64) rev_fed_state_rural_lowinc_sch,
    safe_cast(rev_fed_state_bilingual_ed as float64) rev_fed_state_bilingual_ed,
    safe_cast(rev_fed_state_other as float64) rev_fed_state_other,
    safe_cast(rev_fed_child_nutrition_act as float64) rev_fed_child_nutrition_act,
    safe_cast(rev_fed_nonspec as float64) rev_fed_nonspec,
    safe_cast(rev_fed_direct_impact_aid as float64) rev_fed_direct_impact_aid,
    safe_cast(rev_fed_direct_indian_ed as float64) rev_fed_direct_indian_ed,
    safe_cast(
        rev_fed_direct_rural_achievement as float64
    ) rev_fed_direct_rural_achievement,
    safe_cast(rev_fed_direct_other as float64) rev_fed_direct_other,
    safe_cast(rev_state_total as float64) rev_state_total,
    safe_cast(rev_state_gen_formula_assist as float64) rev_state_gen_formula_assist,
    safe_cast(rev_state_staff_improve as float64) rev_state_staff_improve,
    safe_cast(rev_state_special_ed as float64) rev_state_special_ed,
    safe_cast(rev_state_compens_basic_ed as float64) rev_state_compens_basic_ed,
    safe_cast(rev_state_bilingual_ed as float64) rev_state_bilingual_ed,
    safe_cast(rev_state_gifted_talented as float64) rev_state_gifted_talented,
    safe_cast(rev_state_vocational_ed as float64) rev_state_vocational_ed,
    safe_cast(rev_state_sch_lunch as float64) rev_state_sch_lunch,
    safe_cast(rev_state_outlay_capital_debt as float64) rev_state_outlay_capital_debt,
    safe_cast(rev_state_transportation as float64) rev_state_transportation,
    safe_cast(rev_state_oth_prog as float64) rev_state_oth_prog,
    safe_cast(rev_state_nonspec as float64) rev_state_nonspec,
    safe_cast(rev_state_employee_benefits as float64) rev_state_employee_benefits,
    safe_cast(
        rev_state_not_employee_benefits as float64
    ) rev_state_not_employee_benefits,
    safe_cast(rev_local_total as float64) rev_local_total,
    safe_cast(rev_local_parent_govt as float64) rev_local_parent_govt,
    safe_cast(rev_local_prop_tax as float64) rev_local_prop_tax,
    safe_cast(rev_local_sales_tax as float64) rev_local_sales_tax,
    safe_cast(rev_local_utility_tax as float64) rev_local_utility_tax,
    safe_cast(rev_local_income_tax as float64) rev_local_income_tax,
    safe_cast(rev_local_other_tax as float64) rev_local_other_tax,
    safe_cast(rev_local_other_sch_systems as float64) rev_local_other_sch_systems,
    safe_cast(rev_local_cities_counties as float64) rev_local_cities_counties,
    safe_cast(rev_local_tuition_fees as float64) rev_local_tuition_fees,
    safe_cast(rev_local_transportation_fees as float64) rev_local_transportation_fees,
    safe_cast(rev_local_sch_lunch as float64) rev_local_sch_lunch,
    safe_cast(rev_local_textbook_sales_rents as float64) rev_local_textbook_sales_rents,
    safe_cast(rev_local_dist_activ_receipts as float64) rev_local_dist_activ_receipts,
    safe_cast(rev_local_student_fees_nonspec as float64) rev_local_student_fees_nonspec,
    safe_cast(rev_local_oth_sales_serv as float64) rev_local_oth_sales_serv,
    safe_cast(rev_local_rents_royalties as float64) rev_local_rents_royalties,
    safe_cast(rev_local_property_sale as float64) rev_local_property_sale,
    safe_cast(rev_local_interest_earnings as float64) rev_local_interest_earnings,
    safe_cast(rev_local_fines_forfeits as float64) rev_local_fines_forfeits,
    safe_cast(rev_local_private_contrib as float64) rev_local_private_contrib,
    safe_cast(rev_local_misc as float64) rev_local_misc,
    safe_cast(rev_nces as float64) rev_nces,
    safe_cast(exp_total as float64) exp_total,
    safe_cast(exp_current_elsec_total as float64) exp_current_elsec_total,
    safe_cast(exp_current_instruction_total as float64) exp_current_instruction_total,
    safe_cast(exp_instruction as float64) exp_instruction,
    safe_cast(payments_private_schools as float64) payments_private_schools,
    safe_cast(payments_charter_schools as float64) payments_charter_schools,
    safe_cast(exp_current_supp_serve_total as float64) exp_current_supp_serve_total,
    safe_cast(exp_current_pupils as float64) exp_current_pupils,
    safe_cast(exp_current_instruc_staff as float64) exp_current_instruc_staff,
    safe_cast(exp_current_general_admin as float64) exp_current_general_admin,
    safe_cast(exp_current_sch_admin as float64) exp_current_sch_admin,
    safe_cast(exp_current_operation_plant as float64) exp_current_operation_plant,
    safe_cast(exp_current_student_transport as float64) exp_current_student_transport,
    safe_cast(exp_current_bco as float64) exp_current_bco,
    safe_cast(exp_current_supp_serv_nonspec as float64) exp_current_supp_serv_nonspec,
    safe_cast(exp_current_other as float64) exp_current_other,
    safe_cast(exp_current_food_serv as float64) exp_current_food_serv,
    safe_cast(exp_current_enterprise as float64) exp_current_enterprise,
    safe_cast(exp_current_other_elsec as float64) exp_current_other_elsec,
    safe_cast(exp_nonelsec as float64) exp_nonelsec,
    safe_cast(exp_nonelsec_community_serv as float64) exp_nonelsec_community_serv,
    safe_cast(exp_nonelsec_adult_education as float64) exp_nonelsec_adult_education,
    safe_cast(exp_nonelsec_other as float64) exp_nonelsec_other,
    safe_cast(outlay_capital_total as float64) outlay_capital_total,
    safe_cast(outlay_capital_construction as float64) outlay_capital_construction,
    safe_cast(outlay_capital_land_structures as float64) outlay_capital_land_structures,
    safe_cast(outlay_capital_instruc_equip as float64) outlay_capital_instruc_equip,
    safe_cast(outlay_capital_other_equip as float64) outlay_capital_other_equip,
    safe_cast(outlay_capital_nonspec_equip as float64) outlay_capital_nonspec_equip,
    safe_cast(payments_state_govt as float64) payments_state_govt,
    safe_cast(payments_local_govt as float64) payments_local_govt,
    safe_cast(payments_other_sch_system as float64) payments_other_sch_system,
    safe_cast(debt_interest as float64) debt_interest,
    safe_cast(salaries_total as float64) salaries_total,
    safe_cast(salaries_instruction as float64) salaries_instruction,
    safe_cast(salaries_teachers_regular_prog as float64) salaries_teachers_regular_prog,
    safe_cast(salaries_teachers_sped as float64) salaries_teachers_sped,
    safe_cast(salaries_teachers_vocational as float64) salaries_teachers_vocational,
    safe_cast(salaries_teachers_other_ed as float64) salaries_teachers_other_ed,
    safe_cast(salaries_supp_pupils as float64) salaries_supp_pupils,
    safe_cast(salaries_supp_instruc_staff as float64) salaries_supp_instruc_staff,
    safe_cast(salaries_supp_general_admin as float64) salaries_supp_general_admin,
    safe_cast(salaries_supp_sch_admin as float64) salaries_supp_sch_admin,
    safe_cast(salaries_supp_operation_plant as float64) salaries_supp_operation_plant,
    safe_cast(salaries_supp_stud_transport as float64) salaries_supp_stud_transport,
    safe_cast(salaries_supp_bco as float64) salaries_supp_bco,
    safe_cast(salaries_food_service as float64) salaries_food_service,
    safe_cast(benefits_employee_total as float64) benefits_employee_total,
    safe_cast(benefits_employee_instruction as float64) benefits_employee_instruction,
    safe_cast(benefits_supp_pupils as float64) benefits_supp_pupils,
    safe_cast(benefits_supp_instruc_staff as float64) benefits_supp_instruc_staff,
    safe_cast(benefits_supp_general_admin as float64) benefits_supp_general_admin,
    safe_cast(benefits_supp_sch_admin as float64) benefits_supp_sch_admin,
    safe_cast(benefits_supp_operation_plant as float64) benefits_supp_operation_plant,
    safe_cast(benefits_supp_stud_transport as float64) benefits_supp_stud_transport,
    safe_cast(benefits_supp_bco as float64) benefits_supp_bco,
    safe_cast(benefits_food_service as float64) benefits_food_service,
    safe_cast(benefits_enterprise_operations as float64) benefits_enterprise_operations,
    safe_cast(exp_textbooks as float64) exp_textbooks,
    safe_cast(debt_longterm_outstand_beg_fy as float64) debt_longterm_outstand_beg_fy,
    safe_cast(debt_longterm_issued_fy as float64) debt_longterm_issued_fy,
    safe_cast(debt_longterm_retired_fy as float64) debt_longterm_retired_fy,
    safe_cast(debt_longterm_outstand_end_fy as float64) debt_longterm_outstand_end_fy,
    safe_cast(debt_shortterm_outstand_beg_fy as float64) debt_shortterm_outstand_beg_fy,
    safe_cast(debt_shortterm_outstand_end_fy as float64) debt_shortterm_outstand_end_fy,
    safe_cast(assets_sinking_fund as float64) assets_sinking_fund,
    safe_cast(assets_bond_fund as float64) assets_bond_fund,
    safe_cast(assets_other as float64) assets_other,
    safe_cast(exp_utilities_energy as float64) exp_utilities_energy,
    safe_cast(exp_tech_supplies_services as float64) exp_tech_supplies_services,
    safe_cast(exp_tech_equipment as float64) exp_tech_equipment,
    safe_cast(exp_current_state_local_funds as float64) exp_current_state_local_funds,
    safe_cast(exp_current_federal_funds as float64) exp_current_federal_funds,
    safe_cast(exp_current_resa as float64) exp_current_resa,
    safe_cast(exp_sped_current as float64) exp_sped_current,
    safe_cast(exp_sped_instruction as float64) exp_sped_instruction,
    safe_cast(
        exp_sped_pupil_support_services as float64
    ) exp_sped_pupil_support_services,
    safe_cast(
        exp_sped_staff_support_services as float64
    ) exp_sped_staff_support_services,
    safe_cast(
        exp_sped_trans_support_services as float64
    ) exp_sped_trans_support_services,
    safe_cast(rev_cares_act_relief_esser as float64) rev_cares_act_relief_esser,
    safe_cast(rev_cares_act_relief_geer as float64) rev_cares_act_relief_geer,
    safe_cast(rev_cares_act_relief_esf_rem as float64) rev_cares_act_relief_esf_rem,
    safe_cast(rev_cares_act_relief_esf_rwp as float64) rev_cares_act_relief_esf_rwp,
    safe_cast(rev_cares_act_relief_serv as float64) rev_cares_act_relief_serv,
    safe_cast(rev_cares_act_relief_crf as float64) rev_cares_act_relief_crf,
    safe_cast(exp_cares_act_current as float64) exp_cares_act_current,
    safe_cast(exp_cares_act_instruction as float64) exp_cares_act_instruction,
    safe_cast(exp_cares_act_support_services as float64) exp_cares_act_support_services,
    safe_cast(exp_cares_act_outlay as float64) exp_cares_act_outlay,
    safe_cast(exp_cares_act_tech_service as float64) exp_cares_act_tech_service,
    safe_cast(exp_cares_act_tech_equipment as float64) exp_cares_act_tech_equipment,
    safe_cast(rev_crrsa_esser_ii as float64) rev_crrsa_esser_ii,
    safe_cast(rev_arp_esser as float64) rev_arp_esser,
    safe_cast(rev_crrsa_geer_ii as float64) rev_crrsa_geer_ii,
    safe_cast(rev_state_local_recovery_funds as float64) rev_state_local_recovery_funds,
    safe_cast(exp_cares_act_tech_plant as float64) exp_cares_act_tech_plant,
    safe_cast(exp_cares_act_food as float64) exp_cares_act_food,
    safe_cast(rev_fed_state_math_sci_teach as float64) rev_fed_state_math_sci_teach,
    safe_cast(rev_fed_state_drug_free as float64) rev_fed_state_drug_free,
    safe_cast(rev_fed_arra as float64) rev_fed_arra,
    safe_cast(exp_current_arra as float64) exp_current_arra,
    safe_cast(outlay_capital_arra as float64) outlay_capital_arra
from {{ set_datalake_project("us_ed_nces_ccd_staging.district_finance") }} as t
