{{
    config(
        schema="us_ed_nces_ccd",
        alias="school_district",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 1986, "end": 2030, "interval": 1},
        },
        cluster_by=["state_id", "agency_id"],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(agency_id as string) agency_id,
    safe_cast(state_id as string) state_id,
    safe_cast(county_id as string) county_id,
    safe_cast(agency_id_state as string) agency_id_state,
    safe_cast(agency_name as string) agency_name,
    safe_cast(county_name as string) county_name,
    safe_cast(cbsa_id as string) cbsa_id,
    safe_cast(cbsa_type as string) cbsa_type,
    safe_cast(csa_id as string) csa_id,
    safe_cast(cmsa_id as string) cmsa_id,
    safe_cast(necta_id as string) necta_id,
    safe_cast(congressional_district_id as string) congressional_district_id,
    safe_cast(state_leg_district_lower as string) state_leg_district_lower,
    safe_cast(state_leg_district_upper as string) state_leg_district_upper,
    safe_cast(supervisory_union_number as string) supervisory_union_number,
    safe_cast(street_location as string) street_location,
    safe_cast(city_location as string) city_location,
    safe_cast(state_location as string) state_location,
    safe_cast(zip_location as string) zip_location,
    safe_cast(zip4_location as string) zip4_location,
    safe_cast(street_mailing as string) street_mailing,
    safe_cast(city_mailing as string) city_mailing,
    safe_cast(state_mailing as string) state_mailing,
    safe_cast(zip_mailing as string) zip_mailing,
    safe_cast(zip4_mailing as string) zip4_mailing,
    safe_cast(phone as string) phone,
    safe_cast(latitude as float64) latitude,
    safe_cast(longitude as float64) longitude,
    safe_cast(urban_centric_locale as string) urban_centric_locale,
    safe_cast(agency_type as string) agency_type,
    safe_cast(agency_level as string) agency_level,
    safe_cast(agency_charter_indicator as string) agency_charter_indicator,
    safe_cast(boundary_change_indicator as string) boundary_change_indicator,
    safe_cast(bureau_indian_education as string) bureau_indian_education,
    safe_cast(lowest_grade_offered as string) lowest_grade_offered,
    safe_cast(highest_grade_offered as string) highest_grade_offered,
    safe_cast(number_of_schools as int64) number_of_schools,
    safe_cast(enrollment as int64) enrollment,
    safe_cast(spec_ed_students as int64) spec_ed_students,
    safe_cast(english_language_learners as int64) english_language_learners,
    safe_cast(migrant_students as int64) migrant_students
from {{ set_datalake_project("us_ed_nces_ccd_staging.school_district") }} as t
