{{
    config(
        schema="us_ed_nces_ccd",
        alias="school",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 1986, "end": 2030, "interval": 1},
        },
        cluster_by=["state_id", "school_id"],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(school_id as string) school_id,
    safe_cast(agency_id as string) agency_id,
    safe_cast(state_id as string) state_id,
    safe_cast(county_id as string) county_id,
    safe_cast(school_id_local as string) school_id_local,
    safe_cast(school_id_state as string) school_id_state,
    safe_cast(agency_id_state as string) agency_id_state,
    safe_cast(school_name as string) school_name,
    safe_cast(agency_name as string) agency_name,
    safe_cast(cbsa_id as string) cbsa_id,
    safe_cast(csa_id as string) csa_id,
    safe_cast(congressional_district_id as string) congressional_district_id,
    safe_cast(state_leg_district_lower as string) state_leg_district_lower,
    safe_cast(state_leg_district_upper as string) state_leg_district_upper,
    safe_cast(street_location as string) street_location,
    safe_cast(city_location as string) city_location,
    safe_cast(state_location as string) state_location,
    safe_cast(zip_location as string) zip_location,
    safe_cast(street_mailing as string) street_mailing,
    safe_cast(city_mailing as string) city_mailing,
    safe_cast(state_mailing as string) state_mailing,
    safe_cast(zip_mailing as string) zip_mailing,
    safe_cast(phone as string) phone,
    safe_cast(latitude as float64) latitude,
    safe_cast(longitude as float64) longitude,
    safe_cast(urban_centric_locale as string) urban_centric_locale,
    safe_cast(school_level as string) school_level,
    safe_cast(school_type as string) school_type,
    safe_cast(school_status as string) school_status,
    safe_cast(lowest_grade_offered as string) lowest_grade_offered,
    safe_cast(highest_grade_offered as string) highest_grade_offered,
    safe_cast(bureau_indian_education as string) bureau_indian_education,
    safe_cast(title_i_status as string) title_i_status,
    safe_cast(title_i_eligible as string) title_i_eligible,
    safe_cast(title_i_schoolwide as string) title_i_schoolwide,
    safe_cast(charter as string) charter,
    safe_cast(magnet as string) magnet,
    safe_cast(shared_time as string) shared_time,
    safe_cast(virtual as string) virtual,
    safe_cast(elem_cedp as string) elem_cedp,
    safe_cast(middle_cedp as string) middle_cedp,
    safe_cast(high_cedp as string) high_cedp,
    safe_cast(ungrade_cedp as string) ungrade_cedp,
    safe_cast(lunch_program as string) lunch_program,
    safe_cast(teachers_fte as float64) teachers_fte,
    safe_cast(enrollment as int64) enrollment,
    safe_cast(free_lunch as int64) free_lunch,
    safe_cast(reduced_price_lunch as int64) reduced_price_lunch,
    safe_cast(free_or_reduced_price_lunch as int64) free_or_reduced_price_lunch,
    safe_cast(direct_certification as int64) direct_certification
from {{ set_datalake_project("us_ed_nces_ccd_staging.school") }} as t
