"""Regenerate the auto-generated sections of code/DIAGNOSIS.md.

The status matrix and findings sections between the
``<!-- diagnostics:begin -->`` / ``<!-- diagnostics:end -->`` markers are
rewritten from ``artifacts/findings.json``; everything else in the doc is
hand-written and preserved.
"""

from __future__ import annotations

import json
from collections import defaultdict
from datetime import date
from pathlib import Path

ARTIFACTS = Path(__file__).resolve().parent / "artifacts"
FINDINGS_PATH = ARTIFACTS / "findings.json"
DIAGNOSIS_MD = (
    Path(__file__).resolve().parent.parent.parent / "DIAGNOSIS.md"
)  # code/DIAGNOSIS.md

BEGIN = "<!-- diagnostics:begin -->"
END = "<!-- diagnostics:end -->"

_SEV_RANK = {"OK": 0, "NO_LAYOUT": 1, "WARN": 2, "FAIL": 3}
_SEV_CELL = {"OK": "✓", "NO_LAYOUT": "·", "WARN": "⚠", "FAIL": "✗"}


def _load() -> list[dict]:
    return json.loads(FINDINGS_PATH.read_text())


def _matrix(findings: list[dict]) -> str:
    cell: dict[tuple[str, int], str] = {}
    years: set[int] = set()
    tables: set[str] = set()
    for f in findings:
        key = (f["table"], f["ano"])
        years.add(f["ano"])
        tables.add(f["table"])
        prev = cell.get(key, "OK")
        if _SEV_RANK[f["severity"]] >= _SEV_RANK.get(prev, 0):
            cell[key] = f["severity"]

    hist = sorted(y for y in years if y < 1994)
    modern = sorted(y for y in years if y >= 1994)
    lines = []
    for label, cols in (("1945-1990", hist), ("1994-2024", modern)):
        if not cols:
            continue
        sub_tables = sorted(
            t for t in tables if any((t, y) in cell for y in cols)
        )
        lines.append(f"#### {label}\n")
        lines.append(
            "| table | " + " | ".join(str(y)[2:] for y in cols) + " |"
        )
        lines.append("|---" * (len(cols) + 1) + "|")
        for t in sub_tables:
            row = [_SEV_CELL.get(cell.get((t, y), ""), " ") for y in cols]
            lines.append(f"| `{t}` | " + " | ".join(row) + " |")
        lines.append("")
    lines.append(
        "Legend: ✓ OK · ⚠ WARN (low-confidence layout) · ✗ FAIL · `·` no official layout acquired\n"
    )
    return "\n".join(lines)


def _findings_section(findings: list[dict]) -> str:
    interesting = [f for f in findings if f["severity"] in ("FAIL", "WARN")]
    if not interesting:
        return "No FAIL or WARN findings. All mapping sites match the official TSE layouts.\n"
    grouped: dict[tuple, list[dict]] = defaultdict(list)
    for f in interesting:
        grouped[
            (
                f["severity"],
                f["table"],
                f["module"],
                f["function"],
                f["lineno"],
                f["kind"],
            )
        ].append(f)

    lines = []
    for (sev, table, module, function, lineno, kind), group in sorted(
        grouped.items(), key=lambda kv: (-_SEV_RANK[kv[0][0]], kv[0][1])
    ):
        anos = sorted({g["ano"] for g in group})
        lines.append(f"#### {sev}: `{table}` — {kind}\n")
        lines.append(f"- block: `{module}::{function}` line {lineno}")
        lines.append(f"- years: {', '.join(map(str, anos))}")
        lines.append(
            f"- layout source: {group[0].get('layout_source') or 'n/a'}"
        )
        detail_seen = set()
        rows = []
        for g in group:
            for d in g["details"]:
                key = json.dumps(d, sort_keys=True)
                if key in detail_seen:
                    continue
                detail_seen.add(key)
                rows.append((g["ano"], d))
        if rows:
            lines.append("")
            lines.append(
                "| ano | raw col | code maps to | official variable |"
            )
            lines.append("|---|---|---|---|")
            for ano, d in rows[:25]:
                if "tse" in d:
                    lines.append(
                        f"| {ano} | `{d['v']}` | `{d['bd']}` | `{d['tse']}` |"
                    )
                elif "key" in d:
                    lines.append(
                        f"| {ano} | `{d['key']}` | `{d['bd']}` | *(absent)* |"
                    )
                else:
                    lines.append(f"| {ano} | | | `{d}` |")
            if len(rows) > 25:
                lines.append(f"| … | | | +{len(rows) - 25} more |")
        lines.append("")
    return "\n".join(lines)


def render() -> str:
    findings = _load()
    n_fail = sum(1 for f in findings if f["severity"] == "FAIL")
    n_warn = sum(1 for f in findings if f["severity"] == "WARN")
    n_ok = sum(1 for f in findings if f["severity"] == "OK")
    n_nl = sum(1 for f in findings if f["severity"] == "NO_LAYOUT")
    parts = [
        BEGIN,
        f"\n*Auto-generated by `python -m diagnostics report` on {date.today()}.*\n",
        f"**Summary:** {n_ok} OK · {n_warn} WARN · {n_fail} FAIL · {n_nl} without official layout "
        f"(site x year checks).\n",
        "### Status matrix\n",
        _matrix(findings),
        "### Findings\n",
        _findings_section(findings),
        END,
    ]
    return "\n".join(parts)


def update_diagnosis_md():
    content = DIAGNOSIS_MD.read_text()
    start = content.index(BEGIN)
    end = content.index(END) + len(END)
    DIAGNOSIS_MD.write_text(content[:start] + render() + content[end:])
    print(f"updated {DIAGNOSIS_MD}")


if __name__ == "__main__":
    update_diagnosis_md()
