---
name: ✨ feat
description: Nova funcionalidade no código do repositório
title: '[feat] '
labels: [feat]
body:
  - type: textarea
    id: descricao
    attributes:
      label: Descrição da funcionalidade
      description: O que essa funcionalidade deve fazer e qual problema resolve.
    validations:
      required: true
  - type: textarea
    id: motivacao
    attributes:
      label: Motivação e benefício
      description: Como isso contribui para a equipe ou para os usuários da BD?
    validations:
      required: true
  - type: textarea
    id: proposta
    attributes:
      label: Proposta de solução
      description: Abordagem sugerida (opcional). Inclua dependências externas se
        houver.
