---
name: 🛠️ pipeline
description: Solicitação para criação ou atualização de pipeline de dados
title: '[pipeline] <dataset_id>.<table_id>'
labels: [pipeline]
body:
  - type: input
    attributes:
      label: 📂 Dataset e Tabela
      description: Nome do dataset e da tabela-alvo no formato `<dataset_id>.<table_id>`
      placeholder: 'ex: `educacao_basica.matriculas_anuais`'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📋 Descrição do Pipeline
      description: Explique o objetivo e escopo da pipeline.
      placeholder: 'Ex: Esta pipeline extrai dados da API X, transforma e carrega
        na tabela Y...'
    validations:
      required: true
  - type: dropdown
    attributes:
      label: ⚙️ Tipo de Pipeline
      description: Selecione o tipo de processo implementado.
      options: [ELT, ETL, Híbrida (Detalhe o motivo no campo abaixo)]
    validations:
      required: false
  - type: textarea
    attributes:
      label: 🔄 Justificativa para Pipeline Híbrida
      description: Se selecionou "Híbrida", explique o motivo da escolha e como as
        etapas se dividem.
      placeholder: 'Ex: Extração inclui transformação parcial por limitação da fonte...'
    validations:
      required: false
  - type: textarea
    attributes:
      label: 📦 Stack Utilizada
      description: Detalhe as tecnologias e ferramentas utilizadas na pipeline.
      value: |
        - Extração: `<API / FTP / Web scraping / outro>`
        - Transformação: `<Pandas / dbt / SQL / outro>`
    validations:
      required: false
  - type: textarea
    attributes:
      label: 📜 Configuração e Agendamento
      description: Detalhes sobre como a pipeline será configurada e executada.
      value: |
        - Frequência: `<diária / semanal / mensal / outra>`
        - Horário de execução: `<HH:MM>`
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: ✅ Checklist da Pipeline
      options:
        - label: Variáveis de ambiente configuradas
        - label: Código implementado e testado localmente
        - label: Subida do código para o repositório
        - label: Código implementado e testado na Cloud
        - label: Documentação no PR
        - label: Código revisado por outro membro da equipe
    validations:
      required: false
