---
name: 📊 data
description: Solicitação para adicionar nova base, conjunto ou tabela à BD
title: '[data] '
labels: [data]
body:
  - type: input
    id: dataset_id
    attributes:
      label: dataset_id
      description: Nome do conjunto de dados (slug).
      placeholder: br_ibge_censo_agropecuario
    validations:
      required: true
  - type: input
    id: table_ids
    attributes:
      label: table_id(s)
      description: Nome da(s) tabela(s) a serem criadas.
    validations:
      required: true
  - type: textarea
    id: fonte
    attributes:
      label: Fonte original
      value: |
        - Endereço: <url>
        - Tem API? <sim/não>
        - É grátis? <sim/não>
        - Cobertura espacial: <area.slug>
        - Cobertura temporal: <YYYY-MM-DD a YYYY-MM-DD>
        - Frequência de atualização: <year/semester/quarter/month/day/hour>
        - Nível de observação: <entidade representada por linha>
    validations:
      required: true
  - type: textarea
    id: raspagem
    attributes:
      label: Notas de raspagem
      value: |-
        - Dificuldade: <baixa/média/alta>
        - Existe código semi-pronto? <sim/não>
        - Volume/frequência exigem cuidado especial? <não / alta_frequencia / alto_volume>
