{{
    config(
        schema="fr_meteofrance",
        alias="synop",
        materialized="table",
        partition_by={
            "field": "annee",
            "data_type": "int64",
            "range": {"start": 1996, "end": 2031, "interval": 1},
        },
        cluster_by=["indicatif_omm"],
    )
}}


select
    safe_cast(annee as int64) annee,
    safe_cast(mois as int64) mois,
    safe_cast(date as date) date,
    safe_cast(heure as time) heure,
    safe_cast(indicatif_omm as string) indicatif_omm,
    safe_cast(date_heure_traitement as datetime) date_heure_traitement,
    safe_cast(date_heure_insertion as datetime) date_heure_insertion,
    safe_cast(pression_mer as int64) pression_mer,
    safe_cast(variation_pression_3h as int64) variation_pression_3h,
    safe_cast(type_tendance_barometrique as string) type_tendance_barometrique,
    safe_cast(direction_vent_moyen as int64) direction_vent_moyen,
    safe_cast(vitesse_vent_moyen as float64) vitesse_vent_moyen,
    safe_cast(temperature as float64) temperature,
    safe_cast(point_rosee as float64) point_rosee,
    safe_cast(humidite as int64) humidite,
    safe_cast(visibilite_horizontale as float64) visibilite_horizontale,
    safe_cast(temps_present as string) temps_present,
    safe_cast(temps_passe_1 as string) temps_passe_1,
    safe_cast(temps_passe_2 as string) temps_passe_2,
    safe_cast(nebulosite_totale as float64) nebulosite_totale,
    safe_cast(nebulosite_etage_inferieur as int64) nebulosite_etage_inferieur,
    safe_cast(hauteur_base_nuages_inferieurs as int64) hauteur_base_nuages_inferieurs,
    safe_cast(type_nuages_etage_inferieur as string) type_nuages_etage_inferieur,
    safe_cast(type_nuages_etage_moyen as string) type_nuages_etage_moyen,
    safe_cast(type_nuages_etage_superieur as string) type_nuages_etage_superieur,
    safe_cast(pression_station as int64) pression_station,
    safe_cast(niveau_barometrique as int64) niveau_barometrique,
    safe_cast(geopotentiel as int64) geopotentiel,
    safe_cast(variation_pression_24h as int64) variation_pression_24h,
    safe_cast(temperature_minimale_12h as float64) temperature_minimale_12h,
    safe_cast(temperature_minimale_24h as float64) temperature_minimale_24h,
    safe_cast(temperature_maximale_12h as float64) temperature_maximale_12h,
    safe_cast(temperature_maximale_24h as float64) temperature_maximale_24h,
    safe_cast(temperature_minimale_sol_12h as float64) temperature_minimale_sol_12h,
    safe_cast(methode_mesure_tw as string) methode_mesure_tw,
    safe_cast(
        temperature_thermometre_mouille as float64
    ) temperature_thermometre_mouille,
    safe_cast(rafale_10min as float64) rafale_10min,
    safe_cast(rafale_periode as float64) rafale_periode,
    safe_cast(periode_mesure_rafale as float64) periode_mesure_rafale,
    safe_cast(etat_sol as string) etat_sol,
    safe_cast(hauteur_neige as float64) hauteur_neige,
    safe_cast(hauteur_neige_fraiche as float64) hauteur_neige_fraiche,
    safe_cast(periode_mesure_neige_fraiche as float64) periode_mesure_neige_fraiche,
    safe_cast(precipitation_1h as float64) precipitation_1h,
    safe_cast(precipitation_3h as float64) precipitation_3h,
    safe_cast(precipitation_6h as float64) precipitation_6h,
    safe_cast(precipitation_12h as float64) precipitation_12h,
    safe_cast(precipitation_24h as float64) precipitation_24h,
    safe_cast(phenomene_special_1 as string) phenomene_special_1,
    safe_cast(phenomene_special_2 as string) phenomene_special_2,
    safe_cast(phenomene_special_3 as string) phenomene_special_3,
    safe_cast(phenomene_special_4 as string) phenomene_special_4,
    safe_cast(nebulosite_couche_1 as int64) nebulosite_couche_1,
    safe_cast(type_nuage_1 as string) type_nuage_1,
    safe_cast(hauteur_base_nuage_1 as int64) hauteur_base_nuage_1,
    safe_cast(nebulosite_couche_2 as int64) nebulosite_couche_2,
    safe_cast(type_nuage_2 as string) type_nuage_2,
    safe_cast(hauteur_base_nuage_2 as int64) hauteur_base_nuage_2,
    safe_cast(nebulosite_couche_3 as int64) nebulosite_couche_3,
    safe_cast(type_nuage_3 as string) type_nuage_3,
    safe_cast(hauteur_base_nuage_3 as int64) hauteur_base_nuage_3,
    safe_cast(nebulosite_couche_4 as int64) nebulosite_couche_4,
    safe_cast(type_nuage_4 as string) type_nuage_4,
    safe_cast(hauteur_base_nuage_4 as int64) hauteur_base_nuage_4
from {{ set_datalake_project("fr_meteofrance_staging.synop") }} as t
