{{
    config(
        schema="us_fdic_bankfind",
        alias="institution",
        materialized="table",
    )
}}


select
    safe_cast(extraction_date as date) extraction_date,
    safe_cast(cert as string) cert,
    safe_cast(name as string) name,
    safe_cast(rssd_id as string) rssd_id,
    safe_cast(uninum as string) uninum,
    safe_cast(lei as string) lei,
    safe_cast(occ_charter_number as string) occ_charter_number,
    safe_cast(ots_docket_number as string) ots_docket_number,
    safe_cast(previous_name as string) previous_name,
    safe_cast(holding_company_rssd_id as string) holding_company_rssd_id,
    safe_cast(holding_company_name as string) holding_company_name,
    safe_cast(holding_company_city as string) holding_company_city,
    safe_cast(holding_company_state as string) holding_company_state,
    safe_cast(holding_company_type as string) holding_company_type,
    safe_cast(parent_cert as string) parent_cert,
    safe_cast(ultimate_cert as string) ultimate_cert,
    safe_cast(successor_cert as string) successor_cert,
    safe_cast(institution_class as string) institution_class,
    safe_cast(class_code as string) class_code,
    safe_cast(chartering_agency as string) chartering_agency,
    safe_cast(primary_regulator as string) primary_regulator,
    safe_cast(secondary_regulator as string) secondary_regulator,
    safe_cast(is_state_chartered as string) is_state_chartered,
    safe_cast(is_federally_chartered as string) is_federally_chartered,
    safe_cast(specialization_group as string) specialization_group,
    safe_cast(ownership_type as string) ownership_type,
    safe_cast(is_subchapter_s as string) is_subchapter_s,
    safe_cast(is_community_bank as string) is_community_bank,
    safe_cast(minority_status as string) minority_status,
    safe_cast(trust_powers as string) trust_powers,
    safe_cast(is_agricultural_lender as string) is_agricultural_lender,
    safe_cast(is_credit_card_institution as string) is_credit_card_institution,
    safe_cast(is_insured_foreign_branch as string) is_insured_foreign_branch,
    safe_cast(files_call_report_31 as string) files_call_report_31,
    safe_cast(is_fdic_insured as string) is_fdic_insured,
    safe_cast(primary_insurance_fund as string) primary_insurance_fund,
    safe_cast(insurance_date as date) insurance_date,
    safe_cast(insurance_end_date as date) insurance_end_date,
    safe_cast(is_insured_commercial_bank as string) is_insured_commercial_bank,
    safe_cast(is_insured_savings_institution as string) is_insured_savings_institution,
    safe_cast(is_active as string) is_active,
    safe_cast(established_date as date) established_date,
    safe_cast(end_date as date) end_date,
    safe_cast(last_structure_change_date as date) last_structure_change_date,
    safe_cast(
        last_structure_change_process_date as date
    ) last_structure_change_process_date,
    safe_cast(structure_change_code as string) structure_change_code,
    safe_cast(is_in_conservatorship as string) is_in_conservatorship,
    safe_cast(is_de_novo as string) is_de_novo,
    safe_cast(last_update_date as date) last_update_date,
    safe_cast(address as string) address,
    safe_cast(city as string) city,
    safe_cast(county as string) county,
    safe_cast(state_abbreviation as string) state_abbreviation,
    safe_cast(state_name as string) state_name,
    safe_cast(county_id as string) county_id,
    safe_cast(zip_code as string) zip_code,
    safe_cast(latitude as float64) latitude,
    safe_cast(longitude as float64) longitude,
    safe_cast(cbsa_id as string) cbsa_id,
    safe_cast(cbsa_name as string) cbsa_name,
    safe_cast(csa_id as string) csa_id,
    safe_cast(csa_name as string) csa_name,
    safe_cast(fdic_region as string) fdic_region,
    safe_cast(fdic_supervisory_region as string) fdic_supervisory_region,
    safe_cast(federal_reserve_district as string) federal_reserve_district,
    safe_cast(occ_district as string) occ_district,
    safe_cast(website as string) website,
    safe_cast(financial_report_date as date) financial_report_date,
    safe_cast(total_assets as float64) total_assets,
    safe_cast(total_deposits as float64) total_deposits,
    safe_cast(domestic_deposits as float64) domestic_deposits,
    safe_cast(equity_capital as float64) equity_capital,
    safe_cast(net_income as float64) net_income,
    safe_cast(return_on_assets as float64) return_on_assets,
    safe_cast(return_on_equity as float64) return_on_equity,
    safe_cast(domestic_offices as float64) domestic_offices,
    safe_cast(foreign_offices as float64) foreign_offices
from {{ set_datalake_project("us_fdic_bankfind_staging.institution") }} as t
