{{
    config(
        schema="us_census_cps",
        alias="basic_monthly",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 1994, "end": 2024, "interval": 1},
        },
    )
}}


select
    safe_cast(t.year as int64) year,
    safe_cast(t.month as int64) month,
    d.id_state id_state,
    case
        when safe_cast(t.fipscounty as int64) > 0
        then
            concat(
                d.id_state,
                lpad(cast(safe_cast(t.fipscounty as int64) as string), 3, '0')
            )
    end id_county,
    safe_cast(t.minsamp as string) minsamp,
    safe_cast(t.hhid as string) hhid,
    safe_cast(t.hhid2 as string) hhid2,
    safe_cast(t.hrsample as string) hrsample,
    safe_cast(t.hrsersuf as string) hrsersuf,
    safe_cast(t.hhnum as string) hhnum,
    safe_cast(t.hrlonglk as string) hrlonglk,
    safe_cast(t.lineno as string) lineno,
    safe_cast(t.fnlwgt as float64) fnlwgt,
    safe_cast(t.orgwgt as float64) orgwgt,
    safe_cast(t.lonwgt as float64) lonwgt,
    safe_cast(t.famwgt as float64) famwgt,
    safe_cast(t.age as int64) age,
    safe_cast(t.female as string) female,
    safe_cast(t.wbho as string) wbho,
    safe_cast(t.wbhao as string) wbhao,
    safe_cast(t.wbhom as string) wbhom,
    safe_cast(t.wbhaom as string) wbhaom,
    safe_cast(t.racehpia as string) racehpia,
    safe_cast(t.racehpi as string) racehpi,
    safe_cast(t.racea as string) racea,
    safe_cast(t.forborn as string) forborn,
    safe_cast(t.citizen as string) citizen,
    safe_cast(t.prcitshp as string) prcitshp,
    safe_cast(t.arrived as string) arrived,
    safe_cast(t.prinusyr as string) prinusyr,
    safe_cast(t.penatvty as string) penatvty,
    safe_cast(t.pemntvty as string) pemntvty,
    safe_cast(t.pefntvty as string) pefntvty,
    safe_cast(t.vet as string) vet,
    safe_cast(t.married as string) married,
    safe_cast(t.marstat as string) marstat,
    safe_cast(t.ownchild as int64) ownchild,
    safe_cast(t.ch02 as string) ch02,
    safe_cast(t.ch05 as string) ch05,
    safe_cast(t.ch35 as string) ch35,
    safe_cast(t.ch613 as string) ch613,
    safe_cast(t.ch1417 as string) ch1417,
    safe_cast(t.famrel84 as string) famrel84,
    safe_cast(t.famrel94 as string) famrel94,
    safe_cast(t.famrel as string) famrel,
    safe_cast(t.refper as string) refper,
    safe_cast(t.faminc as string) faminc,
    safe_cast(t.lfstat as string) lfstat,
    safe_cast(t.empl as string) empl,
    safe_cast(t.unem as string) unem,
    safe_cast(t.nilf as string) nilf,
    safe_cast(t.selfemp as string) selfemp,
    safe_cast(t.selfinc as string) selfinc,
    safe_cast(t.pubsect as string) pubsect,
    safe_cast(t.pubfed as string) pubfed,
    safe_cast(t.pubst as string) pubst,
    safe_cast(t.publoc as string) publoc,
    safe_cast(t.cow1 as string) cow1,
    safe_cast(t.cow2 as string) cow2,
    safe_cast(t.unemdur as int64) unemdur,
    safe_cast(t.jobloser as string) jobloser,
    safe_cast(t.jobleaver as string) jobleaver,
    safe_cast(t.entrant as string) entrant,
    safe_cast(t.unmem as string) unmem,
    safe_cast(t.uncov as string) uncov,
    safe_cast(t.`union` as string) `union`,
    safe_cast(t.cert as string) cert,
    safe_cast(t.certgov as string) certgov,
    safe_cast(t.schenrl as string) schenrl,
    safe_cast(t.schhs as string) schhs,
    safe_cast(t.schcol as string) schcol,
    safe_cast(t.schft as string) schft,
    safe_cast(t.schpt as string) schpt,
    safe_cast(t.multjob as string) multjob,
    safe_cast(t.multjobn as int64) multjobn,
    safe_cast(t.pdemp1 as string) pdemp1,
    safe_cast(t.pdemp2 as string) pdemp2,
    safe_cast(t.nmemp1 as int64) nmemp1,
    safe_cast(t.nmemp2 as int64) nmemp2,
    safe_cast(t.state as string) state,
    safe_cast(t.metro as string) metro,
    safe_cast(t.centcity as string) centcity,
    safe_cast(t.suburb as string) suburb,
    safe_cast(t.rural as string) rural,
    safe_cast(t.cmsacode05 as string) cmsacode05,
    safe_cast(t.cmsacode14 as string) cmsacode14,
    safe_cast(t.fipscounty as string) fipscounty,
    safe_cast(t.principalcty as string) principalcty,
    safe_cast(t.smsastat05 as string) smsastat05,
    safe_cast(t.smsastat14 as string) smsastat14,
    safe_cast(t.cbsasz as string) cbsasz,
    safe_cast(t.nyc as string) nyc,
    safe_cast(t.la as string) la,
    safe_cast(t.educ as string) educ,
    safe_cast(t.educ92 as string) educ92,
    safe_cast(t.ind_nber as string) ind_nber,
    safe_cast(t.ind_2d as string) ind_2d,
    safe_cast(t.ind70 as string) ind70,
    safe_cast(t.ind80 as string) ind80,
    safe_cast(t.ind03 as string) ind03,
    safe_cast(t.ind09 as string) ind09,
    safe_cast(t.ind12 as string) ind12,
    safe_cast(t.ind14 as string) ind14,
    safe_cast(t.ind_m03 as string) ind_m03,
    safe_cast(t.agric as string) agric,
    safe_cast(t.manuf as string) manuf,
    safe_cast(t.servs as string) servs,
    safe_cast(t.docc70 as string) docc70,
    safe_cast(t.docc80 as string) docc80,
    safe_cast(t.docc03 as string) docc03,
    safe_cast(t.occ70 as string) occ70,
    safe_cast(t.occ80 as string) occ80,
    safe_cast(t.occ03 as string) occ03,
    safe_cast(t.occ11 as string) occ11,
    safe_cast(t.occ12 as string) occ12,
    safe_cast(t.occ_m03 as string) occ_m03,
    safe_cast(t.manag83 as string) manag83,
    safe_cast(t.manag03 as string) manag03,
    safe_cast(t.hourslwa as int64) hourslwa,
    safe_cast(t.hourslw as int64) hourslw,
    safe_cast(t.hourslwm as int64) hourslwm,
    safe_cast(t.reason79 as string) reason79,
    safe_cast(t.reason94 as string) reason94,
    safe_cast(t.absent79 as string) absent79,
    safe_cast(t.absent94 as string) absent94,
    safe_cast(t.abpaid as string) abpaid,
    safe_cast(t.uhours as int64) uhours,
    safe_cast(t.uhourse as int64) uhourse,
    safe_cast(t.why3579 as string) why3579,
    safe_cast(t.why3594 as string) why3594,
    safe_cast(t.ptecon as string) ptecon,
    safe_cast(t.unempt as string) unempt,
    safe_cast(t.prhrusl as int64) prhrusl,
    safe_cast(t.hrsvary as string) hrsvary,
    safe_cast(t.pehrusl1 as int64) pehrusl1,
    safe_cast(t.pehrusl2 as int64) pehrusl2,
    safe_cast(t.pehruslt as int64) pehruslt,
    safe_cast(t.peernhro as int64) peernhro,
    safe_cast(t.imphrs as int64) imphrs,
    safe_cast(t.hrsimptd as string) hrsimptd,
    safe_cast(t.uhoursi as int64) uhoursi,
    safe_cast(t.blsimpt as string) blsimpt,
    safe_cast(t.tc as string) tc
from {{ set_datalake_project("us_census_cps_staging.basic_monthly") }} as t
left join
    `basedosdados.br_bd_diretorios_us.state` as d
    on safe_cast(t.state as string) = d.id_census
