-- Generated by models/us_census_cbp/code/gen_dbt.py from code/sheet_<table>.tsv.
-- Edit the generator and re-run it; hand edits here are overwritten.
{{
    config(
        schema="us_census_cbp",
        alias="dicionario",
        materialized="table",
    )
}}


select
    safe_cast(id_tabela as string) id_tabela,
    safe_cast(nome_coluna as string) nome_coluna,
    safe_cast(chave as string) chave,
    safe_cast(cobertura_temporal as string) cobertura_temporal,
    safe_cast(valor as string) valor
from {{ set_datalake_project("us_census_cbp_staging.dicionario") }} as t
