-- Generated by models/us_census_cbp/code/gen_dbt.py from code/sheet_<table>.tsv.
-- Edit the generator and re-run it; hand edits here are overwritten.
{{
    config(
        schema="us_census_cbp",
        alias="state",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 1998, "end": 2028, "interval": 1},
        },
        cluster_by=["naics"],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(id_state as string) id_state,
    safe_cast(naics as string) naics,
    safe_cast(naics_version as string) naics_version,
    safe_cast(lfo as string) lfo,
    safe_cast(establishments as int64) establishments,
    safe_cast(employment as int64) employment,
    safe_cast(employment_flag as string) employment_flag,
    safe_cast(employment_noise_flag as string) employment_noise_flag,
    safe_cast(payroll_first_quarter as int64) payroll_first_quarter,
    safe_cast(
        payroll_first_quarter_noise_flag as string
    ) payroll_first_quarter_noise_flag,
    safe_cast(payroll_annual as int64) payroll_annual,
    safe_cast(payroll_annual_noise_flag as string) payroll_annual_noise_flag,
    safe_cast(establishments_1_4 as int64) establishments_1_4,
    safe_cast(employment_1_4 as int64) employment_1_4,
    safe_cast(employment_1_4_flag as string) employment_1_4_flag,
    safe_cast(employment_1_4_noise_flag as string) employment_1_4_noise_flag,
    safe_cast(payroll_first_quarter_1_4 as int64) payroll_first_quarter_1_4,
    safe_cast(
        payroll_first_quarter_1_4_noise_flag as string
    ) payroll_first_quarter_1_4_noise_flag,
    safe_cast(payroll_annual_1_4 as int64) payroll_annual_1_4,
    safe_cast(payroll_annual_1_4_noise_flag as string) payroll_annual_1_4_noise_flag,
    safe_cast(establishments_5_9 as int64) establishments_5_9,
    safe_cast(employment_5_9 as int64) employment_5_9,
    safe_cast(employment_5_9_flag as string) employment_5_9_flag,
    safe_cast(employment_5_9_noise_flag as string) employment_5_9_noise_flag,
    safe_cast(payroll_first_quarter_5_9 as int64) payroll_first_quarter_5_9,
    safe_cast(
        payroll_first_quarter_5_9_noise_flag as string
    ) payroll_first_quarter_5_9_noise_flag,
    safe_cast(payroll_annual_5_9 as int64) payroll_annual_5_9,
    safe_cast(payroll_annual_5_9_noise_flag as string) payroll_annual_5_9_noise_flag,
    safe_cast(establishments_10_19 as int64) establishments_10_19,
    safe_cast(employment_10_19 as int64) employment_10_19,
    safe_cast(employment_10_19_flag as string) employment_10_19_flag,
    safe_cast(employment_10_19_noise_flag as string) employment_10_19_noise_flag,
    safe_cast(payroll_first_quarter_10_19 as int64) payroll_first_quarter_10_19,
    safe_cast(
        payroll_first_quarter_10_19_noise_flag as string
    ) payroll_first_quarter_10_19_noise_flag,
    safe_cast(payroll_annual_10_19 as int64) payroll_annual_10_19,
    safe_cast(
        payroll_annual_10_19_noise_flag as string
    ) payroll_annual_10_19_noise_flag,
    safe_cast(establishments_20_49 as int64) establishments_20_49,
    safe_cast(employment_20_49 as int64) employment_20_49,
    safe_cast(employment_20_49_flag as string) employment_20_49_flag,
    safe_cast(employment_20_49_noise_flag as string) employment_20_49_noise_flag,
    safe_cast(payroll_first_quarter_20_49 as int64) payroll_first_quarter_20_49,
    safe_cast(
        payroll_first_quarter_20_49_noise_flag as string
    ) payroll_first_quarter_20_49_noise_flag,
    safe_cast(payroll_annual_20_49 as int64) payroll_annual_20_49,
    safe_cast(
        payroll_annual_20_49_noise_flag as string
    ) payroll_annual_20_49_noise_flag,
    safe_cast(establishments_50_99 as int64) establishments_50_99,
    safe_cast(employment_50_99 as int64) employment_50_99,
    safe_cast(employment_50_99_flag as string) employment_50_99_flag,
    safe_cast(employment_50_99_noise_flag as string) employment_50_99_noise_flag,
    safe_cast(payroll_first_quarter_50_99 as int64) payroll_first_quarter_50_99,
    safe_cast(
        payroll_first_quarter_50_99_noise_flag as string
    ) payroll_first_quarter_50_99_noise_flag,
    safe_cast(payroll_annual_50_99 as int64) payroll_annual_50_99,
    safe_cast(
        payroll_annual_50_99_noise_flag as string
    ) payroll_annual_50_99_noise_flag,
    safe_cast(establishments_100_249 as int64) establishments_100_249,
    safe_cast(employment_100_249 as int64) employment_100_249,
    safe_cast(employment_100_249_flag as string) employment_100_249_flag,
    safe_cast(employment_100_249_noise_flag as string) employment_100_249_noise_flag,
    safe_cast(payroll_first_quarter_100_249 as int64) payroll_first_quarter_100_249,
    safe_cast(
        payroll_first_quarter_100_249_noise_flag as string
    ) payroll_first_quarter_100_249_noise_flag,
    safe_cast(payroll_annual_100_249 as int64) payroll_annual_100_249,
    safe_cast(
        payroll_annual_100_249_noise_flag as string
    ) payroll_annual_100_249_noise_flag,
    safe_cast(establishments_250_499 as int64) establishments_250_499,
    safe_cast(employment_250_499 as int64) employment_250_499,
    safe_cast(employment_250_499_flag as string) employment_250_499_flag,
    safe_cast(employment_250_499_noise_flag as string) employment_250_499_noise_flag,
    safe_cast(payroll_first_quarter_250_499 as int64) payroll_first_quarter_250_499,
    safe_cast(
        payroll_first_quarter_250_499_noise_flag as string
    ) payroll_first_quarter_250_499_noise_flag,
    safe_cast(payroll_annual_250_499 as int64) payroll_annual_250_499,
    safe_cast(
        payroll_annual_250_499_noise_flag as string
    ) payroll_annual_250_499_noise_flag,
    safe_cast(establishments_500_999 as int64) establishments_500_999,
    safe_cast(employment_500_999 as int64) employment_500_999,
    safe_cast(employment_500_999_flag as string) employment_500_999_flag,
    safe_cast(employment_500_999_noise_flag as string) employment_500_999_noise_flag,
    safe_cast(payroll_first_quarter_500_999 as int64) payroll_first_quarter_500_999,
    safe_cast(
        payroll_first_quarter_500_999_noise_flag as string
    ) payroll_first_quarter_500_999_noise_flag,
    safe_cast(payroll_annual_500_999 as int64) payroll_annual_500_999,
    safe_cast(
        payroll_annual_500_999_noise_flag as string
    ) payroll_annual_500_999_noise_flag,
    safe_cast(establishments_1000 as int64) establishments_1000,
    safe_cast(employment_1000 as int64) employment_1000,
    safe_cast(employment_1000_flag as string) employment_1000_flag,
    safe_cast(employment_1000_noise_flag as string) employment_1000_noise_flag,
    safe_cast(payroll_first_quarter_1000 as int64) payroll_first_quarter_1000,
    safe_cast(
        payroll_first_quarter_1000_noise_flag as string
    ) payroll_first_quarter_1000_noise_flag,
    safe_cast(payroll_annual_1000 as int64) payroll_annual_1000,
    safe_cast(payroll_annual_1000_noise_flag as string) payroll_annual_1000_noise_flag
from {{ set_datalake_project("us_census_cbp_staging.state") }} as t
