"""Master schema spec for us_harvard_cbdb (China Biographical Database).

Single source of truth for BOTH the architecture CSVs and the cleaning code.
Each column is a dict:
    src   : source column in the CBDB SQLite (None = derived)
    name  : English BD column name (snake_case)
    type  : BigQuery type (STRING / INT64 / FLOAT64)
    unit  : measurement_unit (only for real quantities)
    dict  : 'yes'/'no' covered_by_dictionary
    ref   : sibling reference table (for a dbt relationships test), '' if none
    pk    : part of the table's logical key (uniqueness test + OL linking)
    nz    : numeric-null rule -- 'year' (<=0 -> NULL), 'count' (-9999 -> NULL),
            'coord' (0 -> NULL), '' none
    pt/en/es : trilingual description (no trailing period)

CBDB is CC BY-NC-SA 4.0 (NonCommercial, ShareAlike). Onboarded free-tier only.
"""


# ---- Convenience builders -------------------------------------------------
def C(  # noqa: N802 - short builder name kept for a compact, readable spec
    src, name, type, pt, en, es, unit="", dict="no", ref="", pk=False, nz=""
):
    return dict_(
        src=src,
        name=name,
        type=type,
        unit=unit,
        dict=dict,
        ref=ref,
        pk=pk,
        nz=nz,
        pt=pt,
        en=en,
        es=es,
    )


def dict_(**k):
    return k


# Shared column fragments reused across tables --------------------------------
def col_notes(src="c_notes"):
    return C(
        src,
        "notes",
        "STRING",
        "Notas textuais livres sobre o registro, conforme o CBDB",
        "Free-text notes on the record, as recorded in CBDB",
        "Notas de texto libre sobre el registro, según el CBDB",
    )


def col_source(src="c_source"):
    return C(
        src,
        "source_id",
        "STRING",
        "Identificador da fonte histórica que documenta o registro",
        "Identifier of the historical source documenting the record",
        "Identificador de la fuente histórica que documenta el registro",
    )


def col_pages(src="c_pages"):
    return C(
        src,
        "source_pages",
        "STRING",
        "Páginas ou localização na fonte histórica citada",
        "Pages or location within the cited historical source",
        "Páginas o ubicación dentro de la fuente histórica citada",
    )


def col_year(src, name, pt, en, es):
    return C(src, name, "INT64", pt, en, es, unit="year", nz="year")


# =============================================================================
TABLES = {}

# ---------------------------------------------------------------- person -----
TABLES["person"] = dict(
    source="BIOG_MAIN",
    name_en="Person",
    name_pt="Pessoa",
    name_es="Persona",
    desc_pt="Tabela mestra de pessoas do CBDB: um registro por indivíduo histórico, com nomes em pinyin e chinês, sexo, dinastia, anos de nascimento e morte e local de origem.",
    desc_en="CBDB person master table: one record per historical individual, with pinyin and Chinese names, sex, dynasty, birth and death years, and place of origin.",
    desc_es="Tabla maestra de personas del CBDB: un registro por individuo histórico, con nombres en pinyin y chino, sexo, dinastía, años de nacimiento y muerte y lugar de origen.",
    ol="person",
    columns=[
        C(
            "c_personid",
            "person_id",
            "STRING",
            "Identificador único da pessoa no CBDB",
            "Unique person identifier in CBDB",
            "Identificador único de la persona en el CBDB",
            pk=True,
        ),
        C(
            "c_name",
            "name_pinyin",
            "STRING",
            "Nome completo em pinyin (romanização Hanyu Pinyin)",
            "Full name in pinyin (Hanyu Pinyin romanization)",
            "Nombre completo en pinyin (romanización Hanyu Pinyin)",
        ),
        C(
            "c_name_chn",
            "name_chinese",
            "STRING",
            "Nome completo em caracteres chineses",
            "Full name in Chinese characters",
            "Nombre completo en caracteres chinos",
        ),
        C(
            "c_surname",
            "surname_pinyin",
            "STRING",
            "Sobrenome em pinyin",
            "Surname in pinyin",
            "Apellido en pinyin",
        ),
        C(
            "c_surname_chn",
            "surname_chinese",
            "STRING",
            "Sobrenome em caracteres chineses",
            "Surname in Chinese characters",
            "Apellido en caracteres chinos",
        ),
        C(
            "c_mingzi",
            "given_name_pinyin",
            "STRING",
            "Nome próprio em pinyin",
            "Given name in pinyin",
            "Nombre de pila en pinyin",
        ),
        C(
            "c_mingzi_chn",
            "given_name_chinese",
            "STRING",
            "Nome próprio em caracteres chineses",
            "Given name in Chinese characters",
            "Nombre de pila en caracteres chinos",
        ),
        C(
            "c_female",
            "sex",
            "STRING",
            "Sexo da pessoa (código: 0 masculino, 1 feminino)",
            "Sex of the person (code: 0 male, 1 female)",
            "Sexo de la persona (código: 0 masculino, 1 femenino)",
            dict="yes",
        ),
        C(
            "c_dy",
            "dynasty_code",
            "STRING",
            "Código da dinastia associada à pessoa",
            "Code of the dynasty associated with the person",
            "Código de la dinastía asociada a la persona",
            dict="yes",
        ),
        col_year(
            "c_birthyear",
            "birth_year",
            "Ano de nascimento (calendário ocidental)",
            "Birth year (Western calendar)",
            "Año de nacimiento (calendario occidental)",
        ),
        col_year(
            "c_deathyear",
            "death_year",
            "Ano de morte (calendário ocidental)",
            "Death year (Western calendar)",
            "Año de muerte (calendario occidental)",
        ),
        C(
            "c_death_age",
            "death_age",
            "INT64",
            "Idade ao morrer, em anos (contagem chinesa sui)",
            "Age at death, in years (Chinese sui reckoning)",
            "Edad al morir, en años (cómputo chino sui)",
            unit="year",
            nz="year",
        ),
        col_year(
            "c_index_year",
            "index_year",
            "Ano representativo usado para ordenar a pessoa no tempo",
            "Representative year used to place the person in time",
            "Año representativo usado para ubicar a la persona en el tiempo",
        ),
        C(
            "c_index_year_type_code",
            "index_year_type_code",
            "STRING",
            "Código do tipo de ano-índice (como o ano representativo foi derivado)",
            "Code for the index-year type (how the representative year was derived)",
            "Código del tipo de año índice (cómo se derivó el año representativo)",
            dict="yes",
        ),
        col_year(
            "c_fl_earliest_year",
            "flourished_earliest_year",
            "Primeiro ano de atividade documentada (floruit)",
            "Earliest documented year of activity (floruit)",
            "Primer año documentado de actividad (floruit)",
        ),
        col_year(
            "c_fl_latest_year",
            "flourished_latest_year",
            "Último ano de atividade documentada (floruit)",
            "Latest documented year of activity (floruit)",
            "Último año documentado de actividad (floruit)",
        ),
        C(
            "c_ethnicity_code",
            "ethnicity_code",
            "STRING",
            "Código de etnia ou tribo da pessoa",
            "Code of the person's ethnicity or tribe",
            "Código de etnia o tribu de la persona",
            dict="yes",
        ),
        C(
            "c_household_status_code",
            "household_status_code",
            "STRING",
            "Código do status de registro domiciliar da pessoa",
            "Code of the person's household registration status",
            "Código del estatus de registro domiciliario de la persona",
            dict="yes",
        ),
        C(
            "c_choronym_code",
            "choronym_code",
            "STRING",
            "Código do coronímio (nome do clã por local ancestral)",
            "Code of the choronym (clan name by ancestral place)",
            "Código del corónimo (nombre de clan por lugar ancestral)",
            dict="yes",
        ),
        C(
            "c_index_addr_id",
            "index_address_code",
            "STRING",
            "Código do local básico de origem da pessoa",
            "Code of the person's basic place of origin",
            "Código del lugar básico de origen de la persona",
            ref="address_code",
        ),
        col_notes(),
    ],
)

# --------------------------------------------------------------- kinship -----
TABLES["kinship"] = dict(
    source="KIN_DATA",
    name_en="Kinship",
    name_pt="Parentesco",
    name_es="Parentesco",
    desc_pt="Relações de parentesco entre pessoas: cada registro liga uma pessoa a um parente por meio de um código de relação de parentesco.",
    desc_en="Kinship relations between persons: each record links a person to a kin by a kinship-relation code.",
    desc_es="Relaciones de parentesco entre personas: cada registro vincula a una persona con un pariente mediante un código de relación de parentesco.",
    ol="person",
    columns=[
        C(
            "c_personid",
            "person_id",
            "STRING",
            "Identificador da pessoa focal",
            "Identifier of the focal person",
            "Identificador de la persona focal",
            ref="__person",
            pk=True,
        ),
        C(
            "c_kin_id",
            "kin_person_id",
            "STRING",
            "Identificador da pessoa aparentada",
            "Identifier of the related (kin) person",
            "Identificador de la persona emparentada",
            ref="__person",
            pk=True,
        ),
        C(
            "c_kin_code",
            "kinship_code",
            "STRING",
            "Código do tipo de relação de parentesco",
            "Code of the kinship-relation type",
            "Código del tipo de relación de parentesco",
            ref="kinship_code",
            pk=True,
        ),
        col_source(),
        col_pages(),
        col_notes(),
    ],
)

# -------------------------------------------------------- office_posting -----
TABLES["office_posting"] = dict(
    source="POSTED_TO_OFFICE_DATA",
    name_en="Office posting",
    name_pt="Nomeação a cargo",
    name_es="Nombramiento a cargo",
    desc_pt="Nomeações a cargos oficiais: cada registro liga uma pessoa a um cargo do governo imperial, com anos de início e fim e tipo de nomeação.",
    desc_en="Appointments to official office: each record links a person to an imperial government office, with start and end years and appointment type.",
    desc_es="Nombramientos a cargos oficiales: cada registro vincula a una persona con un cargo del gobierno imperial, con años de inicio y fin y tipo de nombramiento.",
    ol="person",
    columns=[
        C(
            "c_personid",
            "person_id",
            "STRING",
            "Identificador da pessoa nomeada",
            "Identifier of the appointed person",
            "Identificador de la persona nombrada",
            ref="__person",
        ),
        C(
            "c_office_id",
            "office_code",
            "STRING",
            "Código do cargo ocupado",
            "Code of the office held",
            "Código del cargo ocupado",
            ref="office_code",
            pk=True,
        ),
        C(
            "c_posting_id",
            "posting_id",
            "STRING",
            "Identificador da nomeação (posting)",
            "Identifier of the posting",
            "Identificador del nombramiento (posting)",
            pk=True,
        ),
        C(
            "c_sequence",
            "sequence",
            "STRING",
            "Número de ordem da nomeação na carreira da pessoa",
            "Sequence number of the posting within the person's career",
            "Número de orden del nombramiento en la carrera de la persona",
        ),
        col_year(
            "c_firstyear",
            "first_year",
            "Primeiro ano no cargo (calendário ocidental)",
            "First year in office (Western calendar)",
            "Primer año en el cargo (calendario occidental)",
        ),
        col_year(
            "c_lastyear",
            "last_year",
            "Último ano no cargo (calendário ocidental)",
            "Last year in office (Western calendar)",
            "Último año en el cargo (calendario occidental)",
        ),
        C(
            "c_appt_code",
            "appointment_code",
            "STRING",
            "Código do tipo de nomeação (como o cargo foi assumido)",
            "Code of the appointment type (how the office was taken up)",
            "Código del tipo de nombramiento (cómo se asumió el cargo)",
            dict="yes",
        ),
        C(
            "c_assume_office_code",
            "assume_office_code",
            "STRING",
            "Código indicando se a pessoa efetivamente assumiu o cargo",
            "Code indicating whether the person actually assumed the office",
            "Código que indica si la persona asumió efectivamente el cargo",
            dict="yes",
        ),
        C(
            "c_dy",
            "dynasty_code",
            "STRING",
            "Código da dinastia da nomeação",
            "Code of the dynasty of the posting",
            "Código de la dinastía del nombramiento",
            dict="yes",
        ),
        col_source(),
        col_pages(),
        col_notes(),
    ],
)

# ----------------------------------------------------------- association -----
TABLES["association"] = dict(
    source="ASSOC_DATA",
    name_en="Association",
    name_pt="Associação",
    name_es="Asociación",
    desc_pt="Conexões sociais não familiares entre pessoas (mestres, alunos, colegas, patronos): cada registro liga duas pessoas por um tipo de associação, com anos e local.",
    desc_en="Non-kin social connections between persons (teachers, students, colleagues, patrons): each record links two persons by an association type, with years and place.",
    desc_es="Conexiones sociales no familiares entre personas (maestros, alumnos, colegas, patronos): cada registro vincula a dos personas por un tipo de asociación, con años y lugar.",
    ol="person",
    columns=[
        C(
            "c_personid",
            "person_id",
            "STRING",
            "Identificador da pessoa focal",
            "Identifier of the focal person",
            "Identificador de la persona focal",
            ref="__person",
            pk=True,
        ),
        C(
            "c_assoc_id",
            "assoc_person_id",
            "STRING",
            "Identificador da pessoa associada",
            "Identifier of the associated person",
            "Identificador de la persona asociada",
            ref="__person",
            pk=True,
        ),
        C(
            "c_assoc_code",
            "association_code",
            "STRING",
            "Código do tipo de associação",
            "Code of the association type",
            "Código del tipo de asociación",
            ref="association_code",
            pk=True,
        ),
        C(
            "c_kin_code",
            "kinship_code",
            "STRING",
            "Código de parentesco pelo qual a pessoa focal se liga à associação",
            "Kinship code by which the focal person connects to the association",
            "Código de parentesco por el que la persona focal se vincula a la asociación",
            ref="kinship_code",
            pk=True,
        ),
        C(
            "c_kin_id",
            "kin_person_id",
            "STRING",
            "Parente da pessoa focal envolvido na associação",
            "Kin of the focal person involved in the association",
            "Pariente de la persona focal involucrado en la asociación",
            ref="__person",
            pk=True,
        ),
        C(
            "c_assoc_kin_code",
            "assoc_kinship_code",
            "STRING",
            "Código de parentesco pelo qual a pessoa associada se liga à associação",
            "Kinship code by which the associated person connects to the association",
            "Código de parentesco por el que la persona asociada se vincula a la asociación",
            ref="kinship_code",
            pk=True,
        ),
        C(
            "c_assoc_kin_id",
            "assoc_kin_person_id",
            "STRING",
            "Parente da pessoa associada envolvido na associação",
            "Kin of the associated person involved in the association",
            "Pariente de la persona asociada involucrado en la asociación",
            ref="__person",
            pk=True,
        ),
        col_year(
            "c_assoc_first_year",
            "first_year",
            "Primeiro ano da associação (calendário ocidental)",
            "First year of the association (Western calendar)",
            "Primer año de la asociación (calendario occidental)",
        ),
        col_year(
            "c_assoc_last_year",
            "last_year",
            "Último ano da associação (calendário ocidental)",
            "Last year of the association (Western calendar)",
            "Último año de la asociación (calendario occidental)",
        ),
        C(
            "c_addr_id",
            "address_code",
            "STRING",
            "Código do local onde a associação ocorreu",
            "Code of the place where the association occurred",
            "Código del lugar donde ocurrió la asociación",
            ref="address_code",
        ),
        C(
            "c_text_title",
            "text_title",
            "STRING",
            "Título do texto que documenta a associação, quando aplicável",
            "Title of the text documenting the association, where applicable",
            "Título del texto que documenta la asociación, cuando corresponde",
            pk=True,
        ),
        col_source(),
        col_pages(),
        col_notes(),
    ],
)

# --------------------------------------------------------------- address -----
TABLES["address"] = dict(
    source="BIOG_ADDR_DATA",
    name_en="Address",
    name_pt="Endereço",
    name_es="Dirección",
    desc_pt="Vínculos entre pessoas e lugares (residência, local de origem, sepultamento): cada registro liga uma pessoa a um lugar por um tipo de endereço, com anos.",
    desc_en="Person-to-place links (residence, place of origin, burial): each record links a person to a place by an address type, with years.",
    desc_es="Vínculos entre personas y lugares (residencia, lugar de origen, sepultura): cada registro vincula a una persona con un lugar por un tipo de dirección, con años.",
    ol="person",
    columns=[
        C(
            "c_personid",
            "person_id",
            "STRING",
            "Identificador da pessoa",
            "Identifier of the person",
            "Identificador de la persona",
            ref="__person",
            pk=True,
        ),
        C(
            "c_addr_id",
            "address_code",
            "STRING",
            "Código do lugar",
            "Code of the place",
            "Código del lugar",
            ref="address_code",
            pk=True,
        ),
        C(
            "c_addr_type",
            "address_type_code",
            "STRING",
            "Código do tipo de vínculo com o lugar (residência, origem, sepultamento)",
            "Code of the place-link type (residence, origin, burial)",
            "Código del tipo de vínculo con el lugar (residencia, origen, sepultura)",
            dict="yes",
            pk=True,
        ),
        C(
            "c_sequence",
            "sequence",
            "STRING",
            "Número de ordem do vínculo com o lugar para a pessoa",
            "Sequence number of the place link for the person",
            "Número de orden del vínculo con el lugar para la persona",
            pk=True,
        ),
        col_year(
            "c_firstyear",
            "first_year",
            "Primeiro ano do vínculo com o lugar",
            "First year of the place link",
            "Primer año del vínculo con el lugar",
        ),
        col_year(
            "c_lastyear",
            "last_year",
            "Último ano do vínculo com o lugar",
            "Last year of the place link",
            "Último año del vínculo con el lugar",
        ),
        C(
            "c_natal",
            "is_natal",
            "STRING",
            "Indica se o endereço se refere à família natal de uma mulher (código)",
            "Indicates whether the address refers to a woman's natal family (code)",
            "Indica si la dirección se refiere a la familia natal de una mujer (código)",
        ),
        col_source(),
        col_pages(),
        col_notes(),
    ],
)

# ===================== REFERENCE / CODE TABLES ===============================

# ----------------------------------------------------------- office_code -----
TABLES["office_code"] = dict(
    source="OFFICE_CODES",
    name_en="Office code",
    name_pt="Código de cargo",
    name_es="Código de cargo",
    desc_pt="Vocabulário de cargos oficiais do governo imperial chinês, com nomes em pinyin, chinês e tradução em inglês, por dinastia.",
    desc_en="Vocabulary of official offices of the Chinese imperial government, with pinyin, Chinese, and English names, by dynasty.",
    desc_es="Vocabulario de cargos oficiales del gobierno imperial chino, con nombres en pinyin, chino y traducción al inglés, por dinastía.",
    ol=None,
    columns=[
        C(
            "c_office_id",
            "office_code",
            "STRING",
            "Código único do cargo",
            "Unique office code",
            "Código único del cargo",
            pk=True,
        ),
        C(
            "c_dy",
            "dynasty_code",
            "STRING",
            "Código da dinastia à qual o cargo pertence",
            "Code of the dynasty to which the office belongs",
            "Código de la dinastía a la que pertenece el cargo",
            dict="yes",
        ),
        C(
            "c_office_pinyin",
            "name_pinyin",
            "STRING",
            "Nome do cargo em pinyin",
            "Office name in pinyin",
            "Nombre del cargo en pinyin",
        ),
        C(
            "c_office_chn",
            "name_chinese",
            "STRING",
            "Nome do cargo em caracteres chineses",
            "Office name in Chinese characters",
            "Nombre del cargo en caracteres chinos",
        ),
        C(
            "c_office_pinyin_alt",
            "name_pinyin_alt",
            "STRING",
            "Nome alternativo do cargo em pinyin",
            "Alternative office name in pinyin",
            "Nombre alternativo del cargo en pinyin",
        ),
        C(
            "c_office_chn_alt",
            "name_chinese_alt",
            "STRING",
            "Nome alternativo do cargo em caracteres chineses",
            "Alternative office name in Chinese characters",
            "Nombre alternativo del cargo en caracteres chinos",
        ),
        C(
            "c_office_trans",
            "name_english",
            "STRING",
            "Tradução do nome do cargo em inglês",
            "English translation of the office name",
            "Traducción al inglés del nombre del cargo",
        ),
        C(
            "c_office_trans_alt",
            "name_english_alt",
            "STRING",
            "Tradução alternativa do nome do cargo em inglês",
            "Alternative English translation of the office name",
            "Traducción alternativa al inglés del nombre del cargo",
        ),
        col_notes(),
    ],
)

# ---------------------------------------------------------- address_code -----
TABLES["address_code"] = dict(
    source="ADDR_CODES",
    name_en="Address code",
    name_pt="Código de lugar",
    name_es="Código de lugar",
    desc_pt="Gazetteer de lugares históricos referidos no CBDB, com nomes em pinyin e chinês, tipo administrativo e coordenadas geográficas.",
    desc_en="Gazetteer of historical places referenced in CBDB, with pinyin and Chinese names, administrative type, and geographic coordinates.",
    desc_es="Gaceteer de lugares históricos referidos en el CBDB, con nombres en pinyin y chino, tipo administrativo y coordenadas geográficas.",
    ol=None,
    columns=[
        C(
            "c_addr_id",
            "address_code",
            "STRING",
            "Código único do lugar",
            "Unique place code",
            "Código único del lugar",
            pk=True,
        ),
        C(
            "c_name",
            "name_pinyin",
            "STRING",
            "Nome do lugar em pinyin",
            "Place name in pinyin",
            "Nombre del lugar en pinyin",
        ),
        C(
            "c_name_chn",
            "name_chinese",
            "STRING",
            "Nome do lugar em caracteres chineses",
            "Place name in Chinese characters",
            "Nombre del lugar en caracteres chinos",
        ),
        col_year(
            "c_firstyear",
            "first_year",
            "Primeiro ano de existência da unidade administrativa",
            "First year the administrative unit existed",
            "Primer año de existencia de la unidad administrativa",
        ),
        col_year(
            "c_lastyear",
            "last_year",
            "Último ano de existência da unidade administrativa",
            "Last year the administrative unit existed",
            "Último año de existencia de la unidad administrativa",
        ),
        C(
            "c_admin_type",
            "admin_type",
            "STRING",
            "Tipo administrativo do lugar (texto)",
            "Administrative type of the place (text)",
            "Tipo administrativo del lugar (texto)",
        ),
        C(
            "c_admin_cat_code",
            "admin_category_code",
            "STRING",
            "Código da categoria administrativa do lugar",
            "Code of the administrative category of the place",
            "Código de la categoría administrativa del lugar",
            dict="yes",
        ),
        C(
            "x_coord",
            "longitude",
            "FLOAT64",
            "Longitude do lugar em graus decimais",
            "Longitude of the place in decimal degrees",
            "Longitud del lugar en grados decimales",
            unit="degree",
            nz="coord",
        ),
        C(
            "y_coord",
            "latitude",
            "FLOAT64",
            "Latitude do lugar em graus decimais",
            "Latitude of the place in decimal degrees",
            "Latitud del lugar en grados decimales",
            unit="degree",
            nz="coord",
        ),
        C(
            "CHGIS_PT_ID",
            "chgis_point_id",
            "STRING",
            "Identificador do ponto correspondente no CHGIS (China Historical GIS)",
            "Identifier of the matching point in CHGIS (China Historical GIS)",
            "Identificador del punto correspondiente en CHGIS (China Historical GIS)",
        ),
        C(
            "c_alt_names",
            "alt_names",
            "STRING",
            "Nomes alternativos do lugar",
            "Alternative names of the place",
            "Nombres alternativos del lugar",
        ),
        col_notes(),
    ],
)

# ---------------------------------------------------------- kinship_code -----
TABLES["kinship_code"] = dict(
    source="KINSHIP_CODES",
    name_en="Kinship code",
    name_pt="Código de parentesco",
    name_es="Código de parentesco",
    desc_pt="Vocabulário de tipos de relação de parentesco, com o termo em chinês e inglês e a distância genealógica em gerações e passos.",
    desc_en="Vocabulary of kinship-relation types, with the Chinese and English term and the genealogical distance in generations and steps.",
    desc_es="Vocabulario de tipos de relación de parentesco, con el término en chino e inglés y la distancia genealógica en generaciones y pasos.",
    ol=None,
    columns=[
        C(
            "c_kincode",
            "kinship_code",
            "STRING",
            "Código único do tipo de parentesco",
            "Unique kinship-type code",
            "Código único del tipo de parentesco",
            pk=True,
        ),
        C(
            "c_kinrel_chn",
            "relation_chinese",
            "STRING",
            "Termo de parentesco em caracteres chineses",
            "Kinship term in Chinese characters",
            "Término de parentesco en caracteres chinos",
        ),
        C(
            "c_kinrel",
            "relation_english",
            "STRING",
            "Termo de parentesco em inglês (abreviado)",
            "Kinship term in English (abbreviated)",
            "Término de parentesco en inglés (abreviado)",
        ),
        C(
            "c_kinrel_alt",
            "relation_english_alt",
            "STRING",
            "Termo de parentesco alternativo em inglês",
            "Alternative kinship term in English",
            "Término de parentesco alternativo en inglés",
        ),
        C(
            "c_kinrel_simplified",
            "relation_simplified",
            "STRING",
            "Termo de parentesco simplificado",
            "Simplified kinship term",
            "Término de parentesco simplificado",
        ),
        C(
            "c_kin_pair1",
            "reciprocal_code_1",
            "STRING",
            "Código da relação recíproca primária",
            "Code of the primary reciprocal relation",
            "Código de la relación recíproca primaria",
            ref="kinship_code",
        ),
        C(
            "c_kin_pair2",
            "reciprocal_code_2",
            "STRING",
            "Código da relação recíproca secundária",
            "Code of the secondary reciprocal relation",
            "Código de la relación recíproca secundaria",
            ref="kinship_code",
        ),
        C(
            "c_upstep",
            "generations_up",
            "INT64",
            "Número de gerações acima da pessoa focal",
            "Number of generations above the focal person",
            "Número de generaciones por encima de la persona focal",
            unit="generation",
            nz="count",
        ),
        C(
            "c_dwnstep",
            "generations_down",
            "INT64",
            "Número de gerações abaixo da pessoa focal",
            "Number of generations below the focal person",
            "Número de generaciones por debajo de la persona focal",
            unit="generation",
            nz="count",
        ),
        C(
            "c_marstep",
            "marriage_steps",
            "INT64",
            "Número de passos de casamento na relação",
            "Number of marriage steps in the relation",
            "Número de pasos de matrimonio en la relación",
            unit="step",
            nz="count",
        ),
        C(
            "c_colstep",
            "collateral_steps",
            "INT64",
            "Número de passos colaterais na relação",
            "Number of collateral steps in the relation",
            "Número de pasos colaterales en la relación",
            unit="step",
            nz="count",
        ),
    ],
)

# ------------------------------------------------------- association_code -----
TABLES["association_code"] = dict(
    source="ASSOC_CODES",
    name_en="Association code",
    name_pt="Código de associação",
    name_es="Código de asociación",
    desc_pt="Vocabulário de tipos de conexão social não familiar, com descrição em inglês e chinês e o tipo de papel.",
    desc_en="Vocabulary of non-kin social-connection types, with English and Chinese description and role type.",
    desc_es="Vocabulario de tipos de conexión social no familiar, con descripción en inglés y chino y el tipo de rol.",
    ol=None,
    columns=[
        C(
            "c_assoc_code",
            "association_code",
            "STRING",
            "Código único do tipo de associação",
            "Unique association-type code",
            "Código único del tipo de asociación",
            pk=True,
        ),
        C(
            "c_assoc_desc",
            "description_english",
            "STRING",
            "Descrição do tipo de associação em inglês",
            "Description of the association type in English",
            "Descripción del tipo de asociación en inglés",
        ),
        C(
            "c_assoc_desc_chn",
            "description_chinese",
            "STRING",
            "Descrição do tipo de associação em caracteres chineses",
            "Description of the association type in Chinese characters",
            "Descripción del tipo de asociación en caracteres chinos",
        ),
        C(
            "c_assoc_role_type",
            "role_type",
            "STRING",
            "Tipo de papel da associação",
            "Role type of the association",
            "Tipo de rol de la asociación",
        ),
        C(
            "c_assoc_pair",
            "reciprocal_code",
            "STRING",
            "Código da associação recíproca",
            "Code of the reciprocal association",
            "Código de la asociación recíproca",
            ref="association_code",
        ),
        C(
            "c_example",
            "example",
            "STRING",
            "Exemplo ilustrativo do tipo de associação",
            "Illustrative example of the association type",
            "Ejemplo ilustrativo del tipo de asociación",
        ),
    ],
)

# ------------------------------------------------------------ dicionario -----
# Standard BD dictionary. Populated by clean.py from the small CBDB code tables.
TABLES["dicionario"] = dict(
    source=None,
    name_en="Dictionary",
    name_pt="Dicionário",
    name_es="Diccionario",
    desc_pt="Dicionário que traduz os valores codificados das colunas cobertas por dicionário nas demais tabelas do conjunto.",
    desc_en="Dictionary translating the coded values of dictionary-covered columns in the other tables of this dataset.",
    desc_es="Diccionario que traduce los valores codificados de las columnas cubiertas por diccionario en las demás tablas del conjunto.",
    ol=None,
    columns=[
        C(
            None,
            "id_tabela",
            "STRING",
            "Nome da tabela à qual a coluna codificada pertence",
            "Name of the table to which the coded column belongs",
            "Nombre de la tabla a la que pertenece la columna codificada",
        ),
        C(
            None,
            "nome_coluna",
            "STRING",
            "Nome da coluna codificada",
            "Name of the coded column",
            "Nombre de la columna codificada",
        ),
        C(
            None,
            "chave",
            "STRING",
            "Valor codificado (chave)",
            "Coded value (key)",
            "Valor codificado (clave)",
        ),
        C(
            None,
            "cobertura_temporal",
            "STRING",
            "Cobertura temporal à qual a chave se aplica",
            "Temporal coverage to which the key applies",
            "Cobertura temporal a la que se aplica la clave",
        ),
        C(
            None,
            "valor",
            "STRING",
            "Rótulo legível correspondente à chave",
            "Human-readable label corresponding to the key",
            "Etiqueta legible correspondiente a la clave",
        ),
    ],
)

# Order in which tables are presented / uploaded
TABLE_ORDER = [
    "person",
    "kinship",
    "office_posting",
    "association",
    "address",
    "office_code",
    "address_code",
    "kinship_code",
    "association_code",
    "dicionario",
]

# Dicionario sources: (source_table, key_col, label_col_en, label_col_chn,
#                      [ (target_table, target_col) ... ])
DICT_SOURCES = [
    (
        "DYNASTIES",
        "c_dy",
        "c_dynasty",
        "c_dynasty_chn",
        [
            ("person", "dynasty_code"),
            ("office_posting", "dynasty_code"),
            ("office_code", "dynasty_code"),
        ],
    ),
    (
        "BIOG_ADDR_CODES",
        "c_addr_type",
        "c_addr_desc",
        "c_addr_desc_chn",
        [("address", "address_type_code")],
    ),
    (
        "APPOINTMENT_CODES",
        "c_appt_code",
        "c_appt_desc",
        "c_appt_desc_chn",
        [("office_posting", "appointment_code")],
    ),
    (
        "ASSUME_OFFICE_CODES",
        "c_assume_office_code",
        "c_assume_office_desc",
        "c_assume_office_desc_chn",
        [("office_posting", "assume_office_code")],
    ),
    (
        "ETHNICITY_TRIBE_CODES",
        "c_ethnicity_code",
        "c_name",
        "c_name_chn",
        [("person", "ethnicity_code")],
    ),
    (
        "HOUSEHOLD_STATUS_CODES",
        "c_household_status_code",
        "c_household_status_desc",
        "c_household_status_desc_chn",
        [("person", "household_status_code")],
    ),
    (
        "CHORONYM_CODES",
        "c_choronym_code",
        "c_choronym_desc",
        "c_choronym_chn",
        [("person", "choronym_code")],
    ),
    (
        "ADMIN_CAT_CODES",
        "c_admin_cat_code",
        "c_admin_cat_trans",
        "c_admin_cat_hz",
        [("address_code", "admin_category_code")],
    ),
    (
        "INDEXYEAR_TYPE_CODES",
        "c_index_year_type_code",
        "c_index_year_type_desc",
        "c_index_year_type_hz",
        [("person", "index_year_type_code")],
    ),
    # sex is a literal 0/1, handled specially in clean.py
]
