---
version: 2
models:
  - name: br_ibge_populacao__brasil
    description: População residente no Brasil
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [ano]
      - not_null_proportion_multiple_columns:
          at_least: 0.05
    columns:
      - name: ano
        description: Ano
        tests:
          - relationships:
              to: ref('br_bd_diretorios_data_tempo__ano')
              field: ano
      - name: populacao
        description: População residente
  - name: br_ibge_populacao__uf
    description: População residente por Unidade da Federação
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [ano, sigla_uf]
      - not_null_proportion_multiple_columns:
          at_least: 0.05
    columns:
      - name: ano
        description: Ano
        tests:
          - relationships:
              to: ref('br_bd_diretorios_data_tempo__ano')
              field: ano
      - name: sigla_uf
        description: Sigla da Unidade da Federação
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__uf')
              field: sigla
      - name: populacao
        description: População residente
  - name: br_ibge_populacao__municipio
    description: População residente por município
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [ano, id_municipio]
      - not_null_proportion_multiple_columns:
          at_least: 0.05
    columns:
      - name: ano
        description: Ano
        tests:
          - relationships:
              to: ref('br_bd_diretorios_data_tempo__ano')
              field: ano
      - name: sigla_uf
        description: Sigla da Unidade da Federação
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__uf')
              field: sigla
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__municipio')
              field: id_municipio
      - name: populacao
        description: População residente