"""
Single source of truth for br_senado_dados_abertos T1 architecture.

Drives (a) dbt SQL generation, (b) dbt schema.yml (PT descriptions), and
(c) backend column registration (PT/EN/ES). Column order here is the table's
column order.

Each column: (name, type, pt, en, es[, opts])
  type: "str" | "int" | "date" | "datetime"
  opts: dict with any of:
    part=True         partition column (INT64 ano)
    notnull=True      add dbt not_null test (partition / key columns)
    dir="ds.tbl:col"  directory_column FK
    dict=True         covered_by_dictionary
    unit="voto"       measurement_unit (numeric only)
"""

DIR_UF = "br_bd_diretorios_brasil.uf:sigla_uf"
DIR_ANO = "br_bd_diretorios_data_tempo.ano:ano"

TABLES: dict[str, dict] = {}


def _t(
    slug,
    name_pt,
    name_en,
    name_es,
    desc_pt,
    desc_en,
    desc_es,
    cols,
    unique,
    partition=None,
    ol=None,
):
    TABLES[slug] = {
        "name_pt": name_pt,
        "name_en": name_en,
        "name_es": name_es,
        "desc_pt": desc_pt,
        "desc_en": desc_en,
        "desc_es": desc_es,
        "cols": cols,
        "unique": unique,
        "partition": partition,
        "ol": ol or [],
    }


# ============================================================ senador
_t(
    "senador",
    "Senadores",
    "Senators",
    "Senadores",
    "Identificação dos senadores e senadoras que exerceram mandato no Senado Federal, a partir das legislaturas registradas no serviço de dados abertos.",
    "Identification of senators who held office in the Federal Senate, from the legislatures recorded in the open data service.",
    "Identificación de los senadores que ejercieron mandato en el Senado Federal, a partir de las legislaturas registradas en el servicio de datos abiertos.",
    [
        (
            "id_senador",
            "str",
            "Código identificador do parlamentar no Senado Federal",
            "Senator identifier code in the Federal Senate",
            "Código identificador del parlamentario en el Senado Federal",
            {"notnull": True},
        ),
        (
            "nome",
            "str",
            "Nome parlamentar",
            "Parliamentary name",
            "Nombre parlamentario",
        ),
        (
            "nome_completo",
            "str",
            "Nome civil completo",
            "Full civil name",
            "Nombre civil completo",
        ),
        (
            "sexo",
            "str",
            "Sexo do parlamentar",
            "Senator's sex",
            "Sexo del parlamentario",
        ),
        (
            "forma_tratamento",
            "str",
            "Forma de tratamento",
            "Form of address",
            "Forma de tratamiento",
        ),
        (
            "sigla_partido",
            "str",
            "Sigla do partido informado no registro do parlamentar",
            "Party abbreviation reported in the senator's record",
            "Sigla del partido informada en el registro del parlamentario",
        ),
        (
            "sigla_uf",
            "str",
            "Sigla da unidade da federação de mandato",
            "Federative unit abbreviation of the mandate",
            "Sigla de la unidad federativa del mandato",
            {"dir": DIR_UF},
        ),
        (
            "email",
            "str",
            "Endereço de e-mail do gabinete",
            "Office email address",
            "Dirección de correo electrónico del despacho",
        ),
        (
            "url_foto",
            "str",
            "URL da foto oficial do parlamentar",
            "URL of the senator's official photo",
            "URL de la foto oficial del parlamentario",
        ),
        (
            "url_pagina",
            "str",
            "URL da página do parlamentar no portal do Senado",
            "URL of the senator's page on the Senate portal",
            "URL de la página del parlamentario en el portal del Senado",
        ),
        (
            "url_pagina_particular",
            "str",
            "URL da página pessoal do parlamentar",
            "URL of the senator's personal page",
            "URL de la página personal del parlamentario",
        ),
        (
            "id_publico_legislatura_atual",
            "str",
            "Código público do parlamentar na legislatura atual",
            "Public code of the senator in the current legislature",
            "Código público del parlamentario en la legislatura actual",
        ),
    ],
    unique=["id_senador"],
    ol=["id_senador"],
)

# ============================================================ votacao
_t(
    "votacao",
    "Votações",
    "Votes",
    "Votaciones",
    "Votações nominais em processos legislativos no Plenário do Senado Federal e do Congresso Nacional, com uma linha por votação e os totais de votos apurados.",
    "Roll-call votes on legislative processes in the plenary of the Federal Senate and National Congress, one row per vote with the tallied vote totals.",
    "Votaciones nominales en procesos legislativos en el Plenario del Senado Federal y del Congreso Nacional, con una fila por votación y los totales de votos computados.",
    [
        (
            "ano",
            "int",
            "Ano da sessão em que ocorreu a votação",
            "Year of the session in which the vote took place",
            "Año de la sesión en que ocurrió la votación",
            {"part": True, "notnull": True, "dir": DIR_ANO},
        ),
        (
            "id_votacao",
            "str",
            "Código identificador da votação (sessão de votação)",
            "Vote identifier code (voting session)",
            "Código identificador de la votación (sesión de votación)",
            {"notnull": True},
        ),
        (
            "data_sessao",
            "date",
            "Data da sessão em que ocorreu a votação",
            "Date of the session in which the vote took place",
            "Fecha de la sesión en que ocurrió la votación",
        ),
        (
            "casa",
            "str",
            "Casa legislativa da sessão (SF, CN)",
            "Legislative house of the session (SF, CN)",
            "Cámara legislativa de la sesión (SF, CN)",
        ),
        (
            "id_processo",
            "str",
            "Código identificador do processo legislativo votado",
            "Identifier code of the legislative process voted",
            "Código identificador del proceso legislativo votado",
        ),
        (
            "codigo_materia",
            "str",
            "Código legado da matéria no sistema MATE",
            "Legacy code of the matter in the MATE system",
            "Código heredado de la materia en el sistema MATE",
        ),
        (
            "identificacao_materia",
            "str",
            "Identificação da matéria votada (sigla, número e ano)",
            "Identification of the voted matter (abbreviation, number and year)",
            "Identificación de la materia votada (sigla, número y año)",
        ),
        (
            "sigla_materia",
            "str",
            "Sigla do tipo da matéria votada",
            "Abbreviation of the voted matter type",
            "Sigla del tipo de la materia votada",
        ),
        (
            "numero_materia",
            "str",
            "Número da matéria votada",
            "Number of the voted matter",
            "Número de la materia votada",
        ),
        (
            "ano_materia",
            "int",
            "Ano da matéria votada",
            "Year of the voted matter",
            "Año de la materia votada",
        ),
        (
            "id_sessao",
            "str",
            "Código identificador da sessão",
            "Session identifier code",
            "Código identificador de la sesión",
        ),
        (
            "id_sessao_legislativa",
            "str",
            "Código identificador da sessão legislativa",
            "Legislative session identifier code",
            "Código identificador de la sesión legislativa",
        ),
        (
            "numero_sessao",
            "str",
            "Número da sessão",
            "Session number",
            "Número de la sesión",
        ),
        (
            "sequencial_sessao",
            "str",
            "Número sequencial da sessão",
            "Session sequence number",
            "Número secuencial de la sesión",
        ),
        (
            "sequencial_votacao",
            "str",
            "Número sequencial da votação na sessão",
            "Vote sequence number within the session",
            "Número secuencial de la votación en la sesión",
        ),
        (
            "sigla_tipo_sessao",
            "str",
            "Sigla do tipo de sessão",
            "Session type abbreviation",
            "Sigla del tipo de sesión",
        ),
        (
            "descricao_votacao",
            "str",
            "Descrição do objeto da votação",
            "Description of the vote's subject",
            "Descripción del objeto de la votación",
        ),
        (
            "ementa",
            "str",
            "Ementa da matéria votada",
            "Summary of the voted matter",
            "Resumen de la materia votada",
        ),
        (
            "resultado_votacao",
            "str",
            "Sigla do resultado da votação",
            "Vote result abbreviation",
            "Sigla del resultado de la votación",
            {"dict": True},
        ),
        (
            "votacao_secreta",
            "str",
            "Indica se a votação foi secreta (S/N)",
            "Indicates whether the vote was secret (S/N)",
            "Indica si la votación fue secreta (S/N)",
            {"dict": True},
        ),
        (
            "data_apresentacao",
            "date",
            "Data de apresentação da matéria votada",
            "Presentation date of the voted matter",
            "Fecha de presentación de la materia votada",
        ),
        (
            "sigla_colegiado",
            "str",
            "Sigla do colegiado em que ocorreu a votação",
            "Abbreviation of the collegiate body where the vote took place",
            "Sigla del colegiado en que ocurrió la votación",
        ),
        (
            "nome_colegiado",
            "str",
            "Nome do colegiado em que ocorreu a votação",
            "Name of the collegiate body where the vote took place",
            "Nombre del colegiado en que ocurrió la votación",
        ),
        (
            "voto_sim",
            "int",
            "Quantidade de votos Sim",
            "Number of Yes votes",
            "Cantidad de votos Sí",
            {"unit": "voto"},
        ),
        (
            "voto_nao",
            "int",
            "Quantidade de votos Não",
            "Number of No votes",
            "Cantidad de votos No",
            {"unit": "voto"},
        ),
        (
            "voto_abstencao",
            "int",
            "Quantidade de abstenções",
            "Number of abstentions",
            "Cantidad de abstenciones",
            {"unit": "voto"},
        ),
        (
            "voto_outro",
            "int",
            "Quantidade de outros registros de voto",
            "Number of other vote records",
            "Cantidad de otros registros de voto",
            {"unit": "voto"},
        ),
    ],
    unique=["id_votacao"],
    partition="ano",
    ol=["ano", "id_votacao"],
)

# ============================================================ votacao_parlamentar
_t(
    "votacao_parlamentar",
    "Votos dos Parlamentares",
    "Senators' Votes",
    "Votos de los Parlamentarios",
    "Voto individual de cada parlamentar em cada votação nominal, com uma linha por par votação-parlamentar.",
    "Individual vote of each senator in each roll-call vote, one row per vote-senator pair.",
    "Voto individual de cada parlamentario en cada votación nominal, con una fila por par votación-parlamentario.",
    [
        (
            "ano",
            "int",
            "Ano da sessão em que ocorreu a votação",
            "Year of the session in which the vote took place",
            "Año de la sesión en que ocurrió la votación",
            {"part": True, "notnull": True, "dir": DIR_ANO},
        ),
        (
            "id_votacao",
            "str",
            "Código identificador da votação",
            "Vote identifier code",
            "Código identificador de la votación",
            {"notnull": True},
        ),
        (
            "data_sessao",
            "date",
            "Data da sessão em que ocorreu a votação",
            "Date of the session in which the vote took place",
            "Fecha de la sesión en que ocurrió la votación",
        ),
        (
            "id_senador",
            "str",
            "Código identificador do parlamentar votante",
            "Identifier code of the voting senator",
            "Código identificador del parlamentario votante",
            {"notnull": True},
        ),
        (
            "nome",
            "str",
            "Nome do parlamentar votante",
            "Name of the voting senator",
            "Nombre del parlamentario votante",
        ),
        (
            "sexo",
            "str",
            "Sexo do parlamentar votante",
            "Sex of the voting senator",
            "Sexo del parlamentario votante",
        ),
        (
            "sigla_partido",
            "str",
            "Sigla do partido do parlamentar na votação",
            "Party abbreviation of the senator at the vote",
            "Sigla del partido del parlamentario en la votación",
        ),
        (
            "sigla_uf",
            "str",
            "Sigla da unidade da federação do parlamentar",
            "Federative unit abbreviation of the senator",
            "Sigla de la unidad federativa del parlamentario",
            {"dir": DIR_UF},
        ),
        (
            "voto",
            "str",
            "Sigla do voto do parlamentar",
            "Abbreviation of the senator's vote",
            "Sigla del voto del parlamentario",
            {"dict": True},
        ),
        (
            "descricao_voto",
            "str",
            "Descrição do voto do parlamentar",
            "Description of the senator's vote",
            "Descripción del voto del parlamentario",
        ),
    ],
    unique=["id_votacao", "id_senador"],
    partition="ano",
    ol=["ano", "id_votacao", "id_senador"],
)

# ============================================================ votacao_orientacao_bancada
_t(
    "votacao_orientacao_bancada",
    "Orientação de Bancada",
    "Party Whip Orientation",
    "Orientación de Bancada",
    "Orientação de voto das lideranças e bancadas para as votações nominais das sessões plenárias, com uma linha por par votação-bancada.",
    "Voting orientation of leaderships and party benches for roll-call votes in plenary sessions, one row per vote-bench pair.",
    "Orientación de voto de los liderazgos y bancadas para las votaciones nominales de las sesiones plenarias, con una fila por par votación-bancada.",
    [
        (
            "ano",
            "int",
            "Ano da votação",
            "Year of the vote",
            "Año de la votación",
            {"part": True, "notnull": True, "dir": DIR_ANO},
        ),
        (
            "id_votacao_sve",
            "str",
            "Código identificador da votação no sistema SVE",
            "Vote identifier code in the SVE system",
            "Código identificador de la votación en el sistema SVE",
            {"notnull": True},
        ),
        (
            "sequencial_votacao",
            "str",
            "Número sequencial da votação na sessão",
            "Vote sequence number within the session",
            "Número secuencial de la votación en la sesión",
        ),
        (
            "data_votacao",
            "date",
            "Data de início da votação",
            "Vote start date",
            "Fecha de inicio de la votación",
        ),
        (
            "sigla_materia",
            "str",
            "Sigla do tipo da matéria votada",
            "Abbreviation of the voted matter type",
            "Sigla del tipo de la materia votada",
        ),
        (
            "numero_materia",
            "str",
            "Número da matéria votada",
            "Number of the voted matter",
            "Número de la materia votada",
        ),
        (
            "ano_materia",
            "int",
            "Ano da matéria votada",
            "Year of the voted matter",
            "Año de la materia votada",
        ),
        (
            "bancada",
            "str",
            "Bancada ou liderança que emitiu a orientação",
            "Party bench or leadership that issued the orientation",
            "Bancada o liderazgo que emitió la orientación",
            {"notnull": True},
        ),
        (
            "orientacao",
            "str",
            "Orientação de voto emitida pela bancada",
            "Voting orientation issued by the bench",
            "Orientación de voto emitida por la bancada",
            {"dict": True},
        ),
        (
            "data_hora_orientacao",
            "datetime",
            "Data e hora do registro da orientação",
            "Date and time the orientation was recorded",
            "Fecha y hora del registro de la orientación",
        ),
    ],
    unique=["id_votacao_sve", "bancada"],
    partition="ano",
    ol=["ano", "id_votacao_sve", "bancada"],
)

# ============================================================ processo
_t(
    "processo",
    "Processos Legislativos",
    "Legislative Processes",
    "Procesos Legislativos",
    "Processos legislativos (projetos, requerimentos, medidas e demais matérias) apresentados no Senado Federal e no Congresso Nacional, com uma linha por processo.",
    "Legislative processes (bills, requests, measures and other matters) presented in the Federal Senate and National Congress, one row per process.",
    "Procesos legislativos (proyectos, requerimientos, medidas y demás materias) presentados en el Senado Federal y en el Congreso Nacional, con una fila por proceso.",
    [
        (
            "ano",
            "int",
            "Ano de identificação do processo legislativo",
            "Year of identification of the legislative process",
            "Año de identificación del proceso legislativo",
            {"part": True, "notnull": True, "dir": DIR_ANO},
        ),
        (
            "id_processo",
            "str",
            "Código identificador do processo legislativo",
            "Legislative process identifier code",
            "Código identificador del proceso legislativo",
            {"notnull": True},
        ),
        (
            "codigo_materia",
            "str",
            "Código legado da matéria no sistema MATE",
            "Legacy code of the matter in the MATE system",
            "Código heredado de la materia en el sistema MATE",
        ),
        (
            "identificacao",
            "str",
            "Identificação do processo (sigla, número e ano)",
            "Process identification (abbreviation, number and year)",
            "Identificación del proceso (sigla, número y año)",
        ),
        (
            "sigla",
            "str",
            "Sigla do tipo de documento do processo",
            "Abbreviation of the process document type",
            "Sigla del tipo de documento del proceso",
        ),
        (
            "numero",
            "str",
            "Número do processo",
            "Process number",
            "Número del proceso",
        ),
        (
            "autoria",
            "str",
            "Autoria do processo legislativo",
            "Authorship of the legislative process",
            "Autoría del proceso legislativo",
        ),
        (
            "ementa",
            "str",
            "Ementa do processo legislativo",
            "Summary of the legislative process",
            "Resumen del proceso legislativo",
        ),
        (
            "objetivo",
            "str",
            "Objetivo do documento no processo (iniciadora, acessória)",
            "Objective of the document in the process (initiating, accessory)",
            "Objetivo del documento en el proceso (iniciadora, accesoria)",
        ),
        (
            "tipo_documento",
            "str",
            "Tipo do documento iniciador do processo",
            "Type of the process initiating document",
            "Tipo del documento iniciador del proceso",
        ),
        (
            "tipo_conteudo",
            "str",
            "Tipo de conteúdo informacional do documento",
            "Type of informational content of the document",
            "Tipo de contenido informacional del documento",
        ),
        (
            "situacao_atual",
            "str",
            "Situação atual do processo legislativo",
            "Current status of the legislative process",
            "Situación actual del proceso legislativo",
        ),
        (
            "sigla_tipo_deliberacao",
            "str",
            "Sigla do tipo da última deliberação",
            "Abbreviation of the last deliberation type",
            "Sigla del tipo de la última deliberación",
        ),
        (
            "ente_identificador",
            "str",
            "Ente ou colegiado identificador do processo",
            "Entity or collegiate body identifying the process",
            "Ente o colegiado identificador del proceso",
        ),
        (
            "casa_identificadora",
            "str",
            "Casa legislativa identificadora do processo",
            "Legislative house identifying the process",
            "Cámara legislativa identificadora del proceso",
        ),
        (
            "norma_gerada",
            "str",
            "Norma jurídica gerada pelo processo",
            "Legal norm generated by the process",
            "Norma jurídica generada por el proceso",
        ),
        (
            "apelido",
            "str",
            "Apelido pelo qual o processo é conhecido",
            "Nickname by which the process is known",
            "Apodo por el que se conoce el proceso",
        ),
        (
            "tramitando",
            "str",
            "Indica se o processo está tramitando (Sim/Não)",
            "Indicates whether the process is under way (Yes/No)",
            "Indica si el proceso está en trámite (Sí/No)",
            {"dict": True},
        ),
        (
            "data_apresentacao",
            "date",
            "Data de apresentação do processo",
            "Presentation date of the process",
            "Fecha de presentación del proceso",
        ),
        (
            "data_deliberacao",
            "date",
            "Data da última deliberação do processo",
            "Date of the last deliberation of the process",
            "Fecha de la última deliberación del proceso",
        ),
        (
            "data_situacao_atual",
            "date",
            "Data da situação atual do processo",
            "Date of the current status of the process",
            "Fecha de la situación actual del proceso",
        ),
        (
            "data_ultima_atualizacao",
            "datetime",
            "Data e hora da última atualização do registro",
            "Date and time of the record's last update",
            "Fecha y hora de la última actualización del registro",
        ),
        (
            "ultima_informacao_atualizada",
            "str",
            "Tipo da última informação atualizada",
            "Type of the last updated information",
            "Tipo de la última información actualizada",
        ),
        (
            "url_documento",
            "str",
            "URL do documento do processo",
            "URL of the process document",
            "URL del documento del proceso",
        ),
    ],
    unique=["id_processo"],
    partition="ano",
    ol=["ano", "id_processo"],
)

# ============================================================ partido
_t(
    "partido",
    "Partidos Políticos",
    "Political Parties",
    "Partidos Políticos",
    "Partidos políticos em atividade e extintos registrados no Senado Federal, com datas de criação e extinção.",
    "Active and extinct political parties recorded in the Federal Senate, with creation and dissolution dates.",
    "Partidos políticos en actividad y extintos registrados en el Senado Federal, con fechas de creación y extinción.",
    [
        (
            "id_partido",
            "str",
            "Código identificador do partido político",
            "Political party identifier code",
            "Código identificador del partido político",
            {"notnull": True},
        ),
        (
            "sigla_partido",
            "str",
            "Sigla do partido político",
            "Political party abbreviation",
            "Sigla del partido político",
        ),
        (
            "nome_partido",
            "str",
            "Nome do partido político",
            "Political party name",
            "Nombre del partido político",
        ),
        (
            "data_criacao",
            "date",
            "Data de criação do partido",
            "Party creation date",
            "Fecha de creación del partido",
        ),
        (
            "data_extincao",
            "date",
            "Data de extinção do partido",
            "Party dissolution date",
            "Fecha de extinción del partido",
        ),
    ],
    unique=["id_partido"],
    ol=["id_partido"],
)

# ============================================================ bloco
_t(
    "bloco",
    "Blocos Parlamentares",
    "Parliamentary Blocs",
    "Bloques Parlamentarios",
    "Blocos parlamentares constituídos no Senado Federal, com datas de criação e extinção.",
    "Parliamentary blocs formed in the Federal Senate, with creation and dissolution dates.",
    "Bloques parlamentarios constituidos en el Senado Federal, con fechas de creación y extinción.",
    [
        (
            "id_bloco",
            "str",
            "Código identificador do bloco parlamentar",
            "Parliamentary bloc identifier code",
            "Código identificador del bloque parlamentario",
            {"notnull": True},
        ),
        (
            "nome_bloco",
            "str",
            "Nome do bloco parlamentar",
            "Parliamentary bloc name",
            "Nombre del bloque parlamentario",
        ),
        (
            "nome_apelido",
            "str",
            "Apelido do bloco parlamentar",
            "Nickname of the parliamentary bloc",
            "Apodo del bloque parlamentario",
        ),
        (
            "data_criacao",
            "date",
            "Data de criação do bloco",
            "Bloc creation date",
            "Fecha de creación del bloque",
        ),
        (
            "data_extincao",
            "date",
            "Data de extinção do bloco",
            "Bloc dissolution date",
            "Fecha de extinción del bloque",
        ),
    ],
    unique=["id_bloco"],
    ol=["id_bloco"],
)

# ============================================================ lideranca
_t(
    "lideranca",
    "Lideranças",
    "Leaderships",
    "Liderazgos",
    "Cargos de liderança exercidos por parlamentares no Senado Federal, no Congresso Nacional e na Câmara, com uma linha por designação.",
    "Leadership positions held by parliamentarians in the Federal Senate, National Congress and Chamber, one row per designation.",
    "Cargos de liderazgo ejercidos por parlamentarios en el Senado Federal, en el Congreso Nacional y en la Cámara, con una fila por designación.",
    [
        (
            "id_lideranca",
            "str",
            "Código identificador da liderança",
            "Leadership identifier code",
            "Código identificador del liderazgo",
            {"notnull": True},
        ),
        (
            "casa",
            "str",
            "Casa legislativa da liderança (SF, CN, CD)",
            "Legislative house of the leadership (SF, CN, CD)",
            "Cámara legislativa del liderazgo (SF, CN, CD)",
        ),
        (
            "id_senador",
            "str",
            "Código identificador do parlamentar",
            "Senator identifier code",
            "Código identificador del parlamentario",
        ),
        (
            "nome_parlamentar",
            "str",
            "Nome do parlamentar",
            "Senator's name",
            "Nombre del parlamentario",
        ),
        (
            "sigla_tipo_lideranca",
            "str",
            "Sigla do tipo de liderança",
            "Leadership type abbreviation",
            "Sigla del tipo de liderazgo",
        ),
        (
            "descricao_tipo_lideranca",
            "str",
            "Descrição do tipo de liderança",
            "Description of the leadership type",
            "Descripción del tipo de liderazgo",
        ),
        (
            "sigla_tipo_unidade_lideranca",
            "str",
            "Sigla do tipo de unidade da liderança",
            "Abbreviation of the leadership unit type",
            "Sigla del tipo de unidad del liderazgo",
        ),
        (
            "descricao_tipo_unidade_lideranca",
            "str",
            "Descrição do tipo de unidade da liderança",
            "Description of the leadership unit type",
            "Descripción del tipo de unidad del liderazgo",
        ),
        (
            "id_partido_filiacao",
            "str",
            "Código do partido de filiação do parlamentar",
            "Code of the senator's party affiliation",
            "Código del partido de afiliación del parlamentario",
        ),
        (
            "sigla_partido_filiacao",
            "str",
            "Sigla do partido de filiação do parlamentar",
            "Abbreviation of the senator's party affiliation",
            "Sigla del partido de afiliación del parlamentario",
        ),
        (
            "nome_partido_filiacao",
            "str",
            "Nome do partido de filiação do parlamentar",
            "Name of the senator's party affiliation",
            "Nombre del partido de afiliación del parlamentario",
        ),
        (
            "id_bloco",
            "str",
            "Código do bloco parlamentar da liderança",
            "Code of the leadership's parliamentary bloc",
            "Código del bloque parlamentario del liderazgo",
        ),
        (
            "sigla_bloco",
            "str",
            "Sigla do bloco parlamentar da liderança",
            "Abbreviation of the leadership's parliamentary bloc",
            "Sigla del bloque parlamentario del liderazgo",
        ),
        (
            "nome_bloco",
            "str",
            "Nome do bloco parlamentar da liderança",
            "Name of the leadership's parliamentary bloc",
            "Nombre del bloque parlamentario del liderazgo",
        ),
        (
            "numero_ordem_vice_lider",
            "str",
            "Número de ordem do vice-líder",
            "Order number of the deputy leader",
            "Número de orden del vicelíder",
        ),
        (
            "data_designacao",
            "date",
            "Data de designação da liderança",
            "Date the leadership was designated",
            "Fecha de designación del liderazgo",
        ),
    ],
    unique=["id_lideranca"],
    ol=["id_lideranca"],
)

# ============================================================ comissao
_t(
    "comissao",
    "Comissões",
    "Committees",
    "Comisiones",
    "Colegiados em atividade no Senado Federal e no Congresso Nacional, incluindo comissões, conselhos e demais órgãos, com uma linha por colegiado.",
    "Active collegiate bodies in the Federal Senate and National Congress, including committees, councils and other bodies, one row per body.",
    "Colegiados en actividad en el Senado Federal y en el Congreso Nacional, incluyendo comisiones, consejos y demás órganos, con una fila por colegiado.",
    [
        (
            "id_comissao",
            "str",
            "Código identificador do colegiado",
            "Collegiate body identifier code",
            "Código identificador del colegiado",
            {"notnull": True},
        ),
        (
            "sigla_comissao",
            "str",
            "Sigla do colegiado",
            "Collegiate body abbreviation",
            "Sigla del colegiado",
        ),
        (
            "nome_comissao",
            "str",
            "Nome do colegiado",
            "Collegiate body name",
            "Nombre del colegiado",
        ),
        (
            "sigla_casa",
            "str",
            "Sigla da casa legislativa do colegiado",
            "Legislative house abbreviation of the body",
            "Sigla de la cámara legislativa del colegiado",
        ),
        (
            "id_tipo_colegiado",
            "str",
            "Código do tipo de colegiado",
            "Collegiate body type code",
            "Código del tipo de colegiado",
        ),
        (
            "sigla_tipo_colegiado",
            "str",
            "Sigla do tipo de colegiado",
            "Collegiate body type abbreviation",
            "Sigla del tipo de colegiado",
        ),
        (
            "descricao_tipo_colegiado",
            "str",
            "Descrição do tipo de colegiado",
            "Description of the collegiate body type",
            "Descripción del tipo de colegiado",
        ),
        (
            "publica",
            "str",
            "Indica se o colegiado é público (S/N)",
            "Indicates whether the body is public (S/N)",
            "Indica si el colegiado es público (S/N)",
            {"dict": True},
        ),
        (
            "data_inicio",
            "date",
            "Data de início de atividade do colegiado",
            "Start date of the body's activity",
            "Fecha de inicio de actividad del colegiado",
        ),
    ],
    unique=["id_comissao"],
    ol=["id_comissao"],
)

# ============================================================ mesa
_t(
    "mesa",
    "Mesa Diretora",
    "Directing Board",
    "Mesa Directiva",
    "Composição atual da Mesa Diretora do Senado Federal, com uma linha por cargo ocupado.",
    "Current composition of the Directing Board of the Federal Senate, one row per occupied position.",
    "Composición actual de la Mesa Directiva del Senado Federal, con una fila por cargo ocupado.",
    [
        (
            "id_colegiado",
            "str",
            "Código identificador do colegiado da Mesa",
            "Identifier code of the board's collegiate body",
            "Código identificador del colegiado de la Mesa",
            {"notnull": True},
        ),
        (
            "sigla_colegiado",
            "str",
            "Sigla do colegiado da Mesa",
            "Abbreviation of the board's collegiate body",
            "Sigla del colegiado de la Mesa",
        ),
        (
            "nome_colegiado",
            "str",
            "Nome do colegiado da Mesa",
            "Name of the board's collegiate body",
            "Nombre del colegiado de la Mesa",
        ),
        (
            "cargo",
            "str",
            "Cargo ocupado na Mesa Diretora",
            "Position held on the Directing Board",
            "Cargo ocupado en la Mesa Directiva",
            {"notnull": True},
        ),
        (
            "id_senador",
            "str",
            "Código identificador do parlamentar",
            "Senator identifier code",
            "Código identificador del parlamentario",
        ),
        (
            "nome_parlamentar",
            "str",
            "Nome do parlamentar",
            "Senator's name",
            "Nombre del parlamentario",
        ),
        (
            "bancada",
            "str",
            "Bancada do parlamentar (partido e UF)",
            "Senator's bench (party and federative unit)",
            "Bancada del parlamentario (partido y unidad federativa)",
        ),
        (
            "ordem",
            "str",
            "Número de ordem do cargo na Mesa",
            "Order number of the position on the board",
            "Número de orden del cargo en la Mesa",
        ),
        (
            "origem",
            "str",
            "Origem da ocupação do cargo",
            "Origin of the position occupancy",
            "Origen de la ocupación del cargo",
        ),
    ],
    unique=["id_colegiado", "cargo"],
    ol=["id_colegiado"],
)
