"""
Single source of truth for br_senado_dados_abertos T1 architecture.

Drives (a) dbt SQL generation, (b) dbt schema.yml (PT descriptions), and
(c) backend column registration (PT/EN/ES). Column order here is the table's
column order.

Each column: (name, type, pt, en, es[, opts])
  type: "str" | "int" | "date" | "datetime"
  opts: dict with any of:
    part=True         partition column (INT64 ano)
    notnull=True      add dbt not_null test (partition / key columns)
    dir="ds.tbl:col"  directory_column FK
    dict=True         covered_by_dictionary
    unit="voto"       measurement_unit (numeric only)
"""

DIR_UF = "br_bd_diretorios_brasil.uf:sigla_uf"
DIR_ANO = "br_bd_diretorios_data_tempo.ano:ano"

TABLES: dict[str, dict] = {}


def _t(
    slug,
    name_pt,
    name_en,
    name_es,
    desc_pt,
    desc_en,
    desc_es,
    cols,
    unique,
    partition=None,
    ol=None,
):
    TABLES[slug] = {
        "name_pt": name_pt,
        "name_en": name_en,
        "name_es": name_es,
        "desc_pt": desc_pt,
        "desc_en": desc_en,
        "desc_es": desc_es,
        "cols": cols,
        "unique": unique,
        "partition": partition,
        "ol": ol or [],
    }


# ============================================================ senador
_t(
    "senador",
    "Senadores",
    "Senators",
    "Senadores",
    "Identificação dos senadores e senadoras que exerceram mandato no Senado Federal, a partir das legislaturas registradas no serviço de dados abertos.",
    "Identification of senators who held office in the Federal Senate, from the legislatures recorded in the open data service.",
    "Identificación de los senadores que ejercieron mandato en el Senado Federal, a partir de las legislaturas registradas en el servicio de datos abiertos.",
    [
        (
            "id_senador",
            "str",
            "Código identificador do parlamentar no Senado Federal",
            "Senator identifier code in the Federal Senate",
            "Código identificador del parlamentario en el Senado Federal",
            {"notnull": True},
        ),
        (
            "nome",
            "str",
            "Nome parlamentar",
            "Parliamentary name",
            "Nombre parlamentario",
        ),
        (
            "nome_completo",
            "str",
            "Nome civil completo",
            "Full civil name",
            "Nombre civil completo",
        ),
        (
            "sexo",
            "str",
            "Sexo do parlamentar",
            "Senator's sex",
            "Sexo del parlamentario",
        ),
        (
            "forma_tratamento",
            "str",
            "Forma de tratamento",
            "Form of address",
            "Forma de tratamiento",
        ),
        (
            "sigla_partido",
            "str",
            "Sigla do partido informado no registro do parlamentar",
            "Party abbreviation reported in the senator's record",
            "Sigla del partido informada en el registro del parlamentario",
        ),
        (
            "sigla_uf",
            "str",
            "Sigla da unidade da federação de mandato",
            "Federative unit abbreviation of the mandate",
            "Sigla de la unidad federativa del mandato",
            {"dir": DIR_UF},
        ),
        (
            "email",
            "str",
            "Endereço de e-mail do gabinete",
            "Office email address",
            "Dirección de correo electrónico del despacho",
        ),
        (
            "url_foto",
            "str",
            "URL da foto oficial do parlamentar",
            "URL of the senator's official photo",
            "URL de la foto oficial del parlamentario",
        ),
        (
            "url_pagina",
            "str",
            "URL da página do parlamentar no portal do Senado",
            "URL of the senator's page on the Senate portal",
            "URL de la página del parlamentario en el portal del Senado",
        ),
        (
            "url_pagina_particular",
            "str",
            "URL da página pessoal do parlamentar",
            "URL of the senator's personal page",
            "URL de la página personal del parlamentario",
        ),
        (
            "id_publico_legislatura_atual",
            "str",
            "Código público do parlamentar na legislatura atual",
            "Public code of the senator in the current legislature",
            "Código público del parlamentario en la legislatura actual",
        ),
    ],
    unique=["id_senador"],
    ol=["id_senador"],
)

# ============================================================ votacao
_t(
    "votacao",
    "Votações",
    "Votes",
    "Votaciones",
    "Votações nominais em processos legislativos no Plenário do Senado Federal e do Congresso Nacional, com uma linha por votação e os totais de votos apurados.",
    "Roll-call votes on legislative processes in the plenary of the Federal Senate and National Congress, one row per vote with the tallied vote totals.",
    "Votaciones nominales en procesos legislativos en el Plenario del Senado Federal y del Congreso Nacional, con una fila por votación y los totales de votos computados.",
    [
        (
            "ano",
            "int",
            "Ano da sessão em que ocorreu a votação",
            "Year of the session in which the vote took place",
            "Año de la sesión en que ocurrió la votación",
            {"part": True, "notnull": True, "dir": DIR_ANO},
        ),
        (
            "id_votacao",
            "str",
            "Código identificador da votação (sessão de votação)",
            "Vote identifier code (voting session)",
            "Código identificador de la votación (sesión de votación)",
            {"notnull": True},
        ),
        (
            "data_sessao",
            "date",
            "Data da sessão em que ocorreu a votação",
            "Date of the session in which the vote took place",
            "Fecha de la sesión en que ocurrió la votación",
        ),
        (
            "casa",
            "str",
            "Casa legislativa da sessão (SF, CN)",
            "Legislative house of the session (SF, CN)",
            "Cámara legislativa de la sesión (SF, CN)",
        ),
        (
            "id_processo",
            "str",
            "Código identificador do processo legislativo votado",
            "Identifier code of the legislative process voted",
            "Código identificador del proceso legislativo votado",
        ),
        (
            "codigo_materia",
            "str",
            "Código legado da matéria no sistema MATE",
            "Legacy code of the matter in the MATE system",
            "Código heredado de la materia en el sistema MATE",
        ),
        (
            "identificacao_materia",
            "str",
            "Identificação da matéria votada (sigla, número e ano)",
            "Identification of the voted matter (abbreviation, number and year)",
            "Identificación de la materia votada (sigla, número y año)",
        ),
        (
            "sigla_materia",
            "str",
            "Sigla do tipo da matéria votada",
            "Abbreviation of the voted matter type",
            "Sigla del tipo de la materia votada",
        ),
        (
            "numero_materia",
            "str",
            "Número da matéria votada",
            "Number of the voted matter",
            "Número de la materia votada",
        ),
        (
            "ano_materia",
            "int",
            "Ano da matéria votada",
            "Year of the voted matter",
            "Año de la materia votada",
        ),
        (
            "id_sessao",
            "str",
            "Código identificador da sessão",
            "Session identifier code",
            "Código identificador de la sesión",
        ),
        (
            "id_sessao_legislativa",
            "str",
            "Código identificador da sessão legislativa",
            "Legislative session identifier code",
            "Código identificador de la sesión legislativa",
        ),
        (
            "numero_sessao",
            "str",
            "Número da sessão",
            "Session number",
            "Número de la sesión",
        ),
        (
            "sequencial_sessao",
            "str",
            "Número sequencial da sessão",
            "Session sequence number",
            "Número secuencial de la sesión",
        ),
        (
            "sequencial",
            "str",
            "Número sequencial da votação na sessão",
            "Vote sequence number within the session",
            "Número secuencial de la votación en la sesión",
            {"src": "sequencial_votacao"},
        ),
        (
            "sigla_tipo_sessao",
            "str",
            "Sigla do tipo de sessão",
            "Session type abbreviation",
            "Sigla del tipo de sesión",
        ),
        (
            "descricao",
            "str",
            "Descrição do objeto da votação",
            "Description of the vote's subject",
            "Descripción del objeto de la votación",
            {"src": "descricao_votacao"},
        ),
        (
            "ementa",
            "str",
            "Ementa da matéria votada",
            "Summary of the voted matter",
            "Resumen de la materia votada",
        ),
        (
            "resultado",
            "str",
            "Sigla do resultado da votação",
            "Vote result abbreviation",
            "Sigla del resultado de la votación",
            {"dict": True, "src": "resultado_votacao"},
        ),
        (
            "votacao_secreta",
            "str",
            "Indica se a votação foi secreta (S/N)",
            "Indicates whether the vote was secret (S/N)",
            "Indica si la votación fue secreta (S/N)",
            {"dict": True},
        ),
        (
            "data_apresentacao",
            "date",
            "Data de apresentação da matéria votada",
            "Presentation date of the voted matter",
            "Fecha de presentación de la materia votada",
        ),
        (
            "sigla_colegiado",
            "str",
            "Sigla do colegiado em que ocorreu a votação",
            "Abbreviation of the collegiate body where the vote took place",
            "Sigla del colegiado en que ocurrió la votación",
        ),
        (
            "nome_colegiado",
            "str",
            "Nome do colegiado em que ocorreu a votação",
            "Name of the collegiate body where the vote took place",
            "Nombre del colegiado en que ocurrió la votación",
        ),
        (
            "voto_sim",
            "int",
            "Quantidade de votos Sim",
            "Number of Yes votes",
            "Cantidad de votos Sí",
            {"unit": "voto"},
        ),
        (
            "voto_nao",
            "int",
            "Quantidade de votos Não",
            "Number of No votes",
            "Cantidad de votos No",
            {"unit": "voto"},
        ),
        (
            "voto_abstencao",
            "int",
            "Quantidade de abstenções",
            "Number of abstentions",
            "Cantidad de abstenciones",
            {"unit": "voto"},
        ),
        (
            "voto_outro",
            "int",
            "Quantidade de outros registros de voto",
            "Number of other vote records",
            "Cantidad de otros registros de voto",
            {"unit": "voto"},
        ),
    ],
    unique=["id_votacao"],
    partition="ano",
    ol=["ano", "id_votacao"],
)

# ============================================================ votacao_parlamentar
_t(
    "votacao_parlamentar",
    "Votos dos Parlamentares",
    "Senators' Votes",
    "Votos de los Parlamentarios",
    "Voto individual de cada parlamentar em cada votação nominal, com uma linha por par votação-parlamentar.",
    "Individual vote of each senator in each roll-call vote, one row per vote-senator pair.",
    "Voto individual de cada parlamentario en cada votación nominal, con una fila por par votación-parlamentario.",
    [
        (
            "ano",
            "int",
            "Ano da sessão em que ocorreu a votação",
            "Year of the session in which the vote took place",
            "Año de la sesión en que ocurrió la votación",
            {"part": True, "notnull": True, "dir": DIR_ANO},
        ),
        (
            "id_votacao",
            "str",
            "Código identificador da votação",
            "Vote identifier code",
            "Código identificador de la votación",
            {"notnull": True},
        ),
        (
            "data_sessao",
            "date",
            "Data da sessão em que ocorreu a votação",
            "Date of the session in which the vote took place",
            "Fecha de la sesión en que ocurrió la votación",
        ),
        (
            "id_senador",
            "str",
            "Código identificador do parlamentar votante",
            "Identifier code of the voting senator",
            "Código identificador del parlamentario votante",
            {"notnull": True},
        ),
        (
            "sigla_partido",
            "str",
            "Sigla do partido do parlamentar na votação",
            "Party abbreviation of the senator at the vote",
            "Sigla del partido del parlamentario en la votación",
        ),
        (
            "sigla_uf",
            "str",
            "Sigla da unidade da federação do parlamentar",
            "Federative unit abbreviation of the senator",
            "Sigla de la unidad federativa del parlamentario",
            {"dir": DIR_UF},
        ),
        (
            "voto",
            "str",
            "Sigla do voto do parlamentar",
            "Abbreviation of the senator's vote",
            "Sigla del voto del parlamentario",
            {"dict": True},
        ),
        (
            "descricao_voto",
            "str",
            "Descrição do voto do parlamentar",
            "Description of the senator's vote",
            "Descripción del voto del parlamentario",
        ),
    ],
    unique=["id_votacao", "id_senador"],
    partition="ano",
    ol=["ano", "id_votacao", "id_senador"],
)

# ============================================================ votacao_orientacao_bancada
_t(
    "votacao_orientacao_bancada",
    "Orientação de Bancada",
    "Party Whip Orientation",
    "Orientación de Bancada",
    "Orientação de voto das lideranças e bancadas para as votações nominais das sessões plenárias, com uma linha por par votação-bancada.",
    "Voting orientation of leaderships and party benches for roll-call votes in plenary sessions, one row per vote-bench pair.",
    "Orientación de voto de los liderazgos y bancadas para las votaciones nominales de las sesiones plenarias, con una fila por par votación-bancada.",
    [
        (
            "ano",
            "int",
            "Ano da votação",
            "Year of the vote",
            "Año de la votación",
            {"part": True, "notnull": True, "dir": DIR_ANO},
        ),
        (
            "id_votacao_sve",
            "str",
            "Código identificador da votação no sistema SVE",
            "Vote identifier code in the SVE system",
            "Código identificador de la votación en el sistema SVE",
            {"notnull": True},
        ),
        (
            "sequencial_votacao",
            "str",
            "Número sequencial da votação na sessão",
            "Vote sequence number within the session",
            "Número secuencial de la votación en la sesión",
        ),
        (
            "data_votacao",
            "date",
            "Data de início da votação",
            "Vote start date",
            "Fecha de inicio de la votación",
        ),
        (
            "sigla_materia",
            "str",
            "Sigla do tipo da matéria votada",
            "Abbreviation of the voted matter type",
            "Sigla del tipo de la materia votada",
        ),
        (
            "numero_materia",
            "str",
            "Número da matéria votada",
            "Number of the voted matter",
            "Número de la materia votada",
        ),
        (
            "ano_materia",
            "int",
            "Ano da matéria votada",
            "Year of the voted matter",
            "Año de la materia votada",
        ),
        (
            "bancada",
            "str",
            "Bancada ou liderança que emitiu a orientação",
            "Party bench or leadership that issued the orientation",
            "Bancada o liderazgo que emitió la orientación",
            {"notnull": True},
        ),
        (
            "orientacao",
            "str",
            "Orientação de voto emitida pela bancada",
            "Voting orientation issued by the bench",
            "Orientación de voto emitida por la bancada",
            {"dict": True},
        ),
        (
            "data_hora_orientacao",
            "datetime",
            "Data e hora do registro da orientação",
            "Date and time the orientation was recorded",
            "Fecha y hora del registro de la orientación",
        ),
    ],
    unique=["id_votacao_sve", "bancada"],
    partition="ano",
    ol=["ano", "id_votacao_sve", "bancada"],
)

# ============================================================ processo
_t(
    "processo",
    "Processos Legislativos",
    "Legislative Processes",
    "Procesos Legislativos",
    "Processos legislativos (projetos, requerimentos, medidas e demais matérias) apresentados no Senado Federal e no Congresso Nacional, com uma linha por processo.",
    "Legislative processes (bills, requests, measures and other matters) presented in the Federal Senate and National Congress, one row per process.",
    "Procesos legislativos (proyectos, requerimientos, medidas y demás materias) presentados en el Senado Federal y en el Congreso Nacional, con una fila por proceso.",
    [
        (
            "ano",
            "int",
            "Ano de identificação do processo legislativo",
            "Year of identification of the legislative process",
            "Año de identificación del proceso legislativo",
            {"part": True, "notnull": True, "dir": DIR_ANO},
        ),
        (
            "id_processo",
            "str",
            "Código identificador do processo legislativo",
            "Legislative process identifier code",
            "Código identificador del proceso legislativo",
            {"notnull": True},
        ),
        (
            "codigo_materia",
            "str",
            "Código legado da matéria no sistema MATE",
            "Legacy code of the matter in the MATE system",
            "Código heredado de la materia en el sistema MATE",
        ),
        (
            "identificacao",
            "str",
            "Identificação do processo (sigla, número e ano)",
            "Process identification (abbreviation, number and year)",
            "Identificación del proceso (sigla, número y año)",
        ),
        (
            "sigla",
            "str",
            "Sigla do tipo de documento do processo",
            "Abbreviation of the process document type",
            "Sigla del tipo de documento del proceso",
        ),
        (
            "numero",
            "str",
            "Número do processo",
            "Process number",
            "Número del proceso",
        ),
        (
            "autoria",
            "str",
            "Autoria do processo legislativo",
            "Authorship of the legislative process",
            "Autoría del proceso legislativo",
        ),
        (
            "ementa",
            "str",
            "Ementa do processo legislativo",
            "Summary of the legislative process",
            "Resumen del proceso legislativo",
        ),
        (
            "objetivo",
            "str",
            "Objetivo do documento no processo (iniciadora, acessória)",
            "Objective of the document in the process (initiating, accessory)",
            "Objetivo del documento en el proceso (iniciadora, accesoria)",
        ),
        (
            "tipo_documento",
            "str",
            "Tipo do documento iniciador do processo",
            "Type of the process initiating document",
            "Tipo del documento iniciador del proceso",
        ),
        (
            "tipo_conteudo",
            "str",
            "Tipo de conteúdo informacional do documento",
            "Type of informational content of the document",
            "Tipo de contenido informacional del documento",
        ),
        (
            "situacao_atual",
            "str",
            "Situação atual do processo legislativo",
            "Current status of the legislative process",
            "Situación actual del proceso legislativo",
        ),
        (
            "sigla_tipo_deliberacao",
            "str",
            "Sigla do tipo da última deliberação",
            "Abbreviation of the last deliberation type",
            "Sigla del tipo de la última deliberación",
        ),
        (
            "ente_identificador",
            "str",
            "Ente ou colegiado identificador do processo",
            "Entity or collegiate body identifying the process",
            "Ente o colegiado identificador del proceso",
        ),
        (
            "casa_identificadora",
            "str",
            "Casa legislativa identificadora do processo",
            "Legislative house identifying the process",
            "Cámara legislativa identificadora del proceso",
        ),
        (
            "norma_gerada",
            "str",
            "Norma jurídica gerada pelo processo",
            "Legal norm generated by the process",
            "Norma jurídica generada por el proceso",
        ),
        (
            "apelido",
            "str",
            "Apelido pelo qual o processo é conhecido",
            "Nickname by which the process is known",
            "Apodo por el que se conoce el proceso",
        ),
        (
            "tramitando",
            "str",
            "Indica se o processo está tramitando (Sim/Não)",
            "Indicates whether the process is under way (Yes/No)",
            "Indica si el proceso está en trámite (Sí/No)",
            {"dict": True},
        ),
        (
            "data_apresentacao",
            "date",
            "Data de apresentação do processo",
            "Presentation date of the process",
            "Fecha de presentación del proceso",
        ),
        (
            "data_deliberacao",
            "date",
            "Data da última deliberação do processo",
            "Date of the last deliberation of the process",
            "Fecha de la última deliberación del proceso",
        ),
        (
            "data_situacao_atual",
            "date",
            "Data da situação atual do processo",
            "Date of the current status of the process",
            "Fecha de la situación actual del proceso",
        ),
        (
            "data_ultima_atualizacao",
            "datetime",
            "Data e hora da última atualização do registro",
            "Date and time of the record's last update",
            "Fecha y hora de la última actualización del registro",
        ),
        (
            "ultima_informacao_atualizada",
            "str",
            "Tipo da última informação atualizada",
            "Type of the last updated information",
            "Tipo de la última información actualizada",
        ),
        (
            "url_documento",
            "str",
            "URL do documento do processo",
            "URL of the process document",
            "URL del documento del proceso",
        ),
    ],
    unique=["id_processo"],
    partition="ano",
    ol=["ano", "id_processo"],
)

# ============================================================ partido
_t(
    "partido",
    "Partidos Políticos",
    "Political Parties",
    "Partidos Políticos",
    "Partidos políticos em atividade e extintos registrados no Senado Federal, com datas de criação e extinção.",
    "Active and extinct political parties recorded in the Federal Senate, with creation and dissolution dates.",
    "Partidos políticos en actividad y extintos registrados en el Senado Federal, con fechas de creación y extinción.",
    [
        (
            "id_partido",
            "str",
            "Código identificador do partido político",
            "Political party identifier code",
            "Código identificador del partido político",
            {"notnull": True},
        ),
        (
            "sigla",
            "str",
            "Sigla do partido político",
            "Political party abbreviation",
            "Sigla del partido político",
            {"src": "sigla_partido"},
        ),
        (
            "nome",
            "str",
            "Nome do partido político",
            "Political party name",
            "Nombre del partido político",
            {"src": "nome_partido"},
        ),
        (
            "data_criacao",
            "date",
            "Data de criação do partido",
            "Party creation date",
            "Fecha de creación del partido",
        ),
        (
            "data_extincao",
            "date",
            "Data de extinção do partido",
            "Party dissolution date",
            "Fecha de extinción del partido",
        ),
    ],
    unique=["id_partido"],
    ol=["id_partido"],
)

# ============================================================ bloco
_t(
    "bloco",
    "Blocos Parlamentares",
    "Parliamentary Blocs",
    "Bloques Parlamentarios",
    "Blocos parlamentares constituídos no Senado Federal, com datas de criação e extinção.",
    "Parliamentary blocs formed in the Federal Senate, with creation and dissolution dates.",
    "Bloques parlamentarios constituidos en el Senado Federal, con fechas de creación y extinción.",
    [
        (
            "id_bloco",
            "str",
            "Código identificador do bloco parlamentar",
            "Parliamentary bloc identifier code",
            "Código identificador del bloque parlamentario",
            {"notnull": True},
        ),
        (
            "nome",
            "str",
            "Nome do bloco parlamentar",
            "Parliamentary bloc name",
            "Nombre del bloque parlamentario",
            {"src": "nome_bloco"},
        ),
        (
            "nome_apelido",
            "str",
            "Apelido do bloco parlamentar",
            "Nickname of the parliamentary bloc",
            "Apodo del bloque parlamentario",
        ),
        (
            "data_criacao",
            "date",
            "Data de criação do bloco",
            "Bloc creation date",
            "Fecha de creación del bloque",
        ),
        (
            "data_extincao",
            "date",
            "Data de extinção do bloco",
            "Bloc dissolution date",
            "Fecha de extinción del bloque",
        ),
    ],
    unique=["id_bloco"],
    ol=["id_bloco"],
)

# ============================================================ lideranca
_t(
    "lideranca",
    "Lideranças",
    "Leaderships",
    "Liderazgos",
    "Cargos de liderança exercidos por parlamentares no Senado Federal, no Congresso Nacional e na Câmara, com uma linha por designação.",
    "Leadership positions held by parliamentarians in the Federal Senate, National Congress and Chamber, one row per designation.",
    "Cargos de liderazgo ejercidos por parlamentarios en el Senado Federal, en el Congreso Nacional y en la Cámara, con una fila por designación.",
    [
        (
            "id_lideranca",
            "str",
            "Código identificador da liderança",
            "Leadership identifier code",
            "Código identificador del liderazgo",
            {"notnull": True},
        ),
        (
            "casa",
            "str",
            "Casa legislativa da liderança (SF, CN, CD)",
            "Legislative house of the leadership (SF, CN, CD)",
            "Cámara legislativa del liderazgo (SF, CN, CD)",
        ),
        (
            "id_senador",
            "str",
            "Código identificador do parlamentar",
            "Senator identifier code",
            "Código identificador del parlamentario",
        ),
        (
            "nome_parlamentar",
            "str",
            "Nome do parlamentar",
            "Senator's name",
            "Nombre del parlamentario",
        ),
        (
            "sigla_tipo_lideranca",
            "str",
            "Sigla do tipo de liderança",
            "Leadership type abbreviation",
            "Sigla del tipo de liderazgo",
        ),
        (
            "descricao_tipo_lideranca",
            "str",
            "Descrição do tipo de liderança",
            "Description of the leadership type",
            "Descripción del tipo de liderazgo",
        ),
        (
            "sigla_tipo_unidade_lideranca",
            "str",
            "Sigla do tipo de unidade da liderança",
            "Abbreviation of the leadership unit type",
            "Sigla del tipo de unidad del liderazgo",
        ),
        (
            "descricao_tipo_unidade_lideranca",
            "str",
            "Descrição do tipo de unidade da liderança",
            "Description of the leadership unit type",
            "Descripción del tipo de unidad del liderazgo",
        ),
        (
            "id_partido_filiacao",
            "str",
            "Código do partido de filiação do parlamentar",
            "Code of the senator's party affiliation",
            "Código del partido de afiliación del parlamentario",
        ),
        (
            "sigla_partido_filiacao",
            "str",
            "Sigla do partido de filiação do parlamentar",
            "Abbreviation of the senator's party affiliation",
            "Sigla del partido de afiliación del parlamentario",
        ),
        (
            "nome_partido_filiacao",
            "str",
            "Nome do partido de filiação do parlamentar",
            "Name of the senator's party affiliation",
            "Nombre del partido de afiliación del parlamentario",
        ),
        (
            "id_bloco",
            "str",
            "Código do bloco parlamentar da liderança",
            "Code of the leadership's parliamentary bloc",
            "Código del bloque parlamentario del liderazgo",
        ),
        (
            "sigla_bloco",
            "str",
            "Sigla do bloco parlamentar da liderança",
            "Abbreviation of the leadership's parliamentary bloc",
            "Sigla del bloque parlamentario del liderazgo",
        ),
        (
            "nome_bloco",
            "str",
            "Nome do bloco parlamentar da liderança",
            "Name of the leadership's parliamentary bloc",
            "Nombre del bloque parlamentario del liderazgo",
        ),
        (
            "numero_ordem_vice_lider",
            "str",
            "Número de ordem do vice-líder",
            "Order number of the deputy leader",
            "Número de orden del vicelíder",
        ),
        (
            "data_designacao",
            "date",
            "Data de designação da liderança",
            "Date the leadership was designated",
            "Fecha de designación del liderazgo",
        ),
    ],
    unique=["id_lideranca"],
    ol=["id_lideranca"],
)

# ============================================================ comissao
_t(
    "comissao",
    "Comissões",
    "Committees",
    "Comisiones",
    "Colegiados em atividade no Senado Federal e no Congresso Nacional, incluindo comissões, conselhos e demais órgãos, com uma linha por colegiado.",
    "Active collegiate bodies in the Federal Senate and National Congress, including committees, councils and other bodies, one row per body.",
    "Colegiados en actividad en el Senado Federal y en el Congreso Nacional, incluyendo comisiones, consejos y demás órganos, con una fila por colegiado.",
    [
        (
            "id_comissao",
            "str",
            "Código identificador do colegiado",
            "Collegiate body identifier code",
            "Código identificador del colegiado",
            {"notnull": True},
        ),
        (
            "sigla",
            "str",
            "Sigla do colegiado",
            "Collegiate body abbreviation",
            "Sigla del colegiado",
            {"src": "sigla_comissao"},
        ),
        (
            "nome",
            "str",
            "Nome do colegiado",
            "Collegiate body name",
            "Nombre del colegiado",
            {"src": "nome_comissao"},
        ),
        (
            "sigla_casa",
            "str",
            "Sigla da casa legislativa do colegiado",
            "Legislative house abbreviation of the body",
            "Sigla de la cámara legislativa del colegiado",
        ),
        (
            "id_tipo_colegiado",
            "str",
            "Código do tipo de colegiado",
            "Collegiate body type code",
            "Código del tipo de colegiado",
        ),
        (
            "sigla_tipo_colegiado",
            "str",
            "Sigla do tipo de colegiado",
            "Collegiate body type abbreviation",
            "Sigla del tipo de colegiado",
        ),
        (
            "descricao_tipo_colegiado",
            "str",
            "Descrição do tipo de colegiado",
            "Description of the collegiate body type",
            "Descripción del tipo de colegiado",
        ),
        (
            "publica",
            "str",
            "Indica se o colegiado é público (S/N)",
            "Indicates whether the body is public (S/N)",
            "Indica si el colegiado es público (S/N)",
            {"dict": True},
        ),
        (
            "data_inicio",
            "date",
            "Data de início de atividade do colegiado",
            "Start date of the body's activity",
            "Fecha de inicio de actividad del colegiado",
        ),
    ],
    unique=["id_comissao"],
    ol=["id_comissao"],
)

# ============================================================ mesa
_t(
    "mesa",
    "Mesa Diretora",
    "Directing Board",
    "Mesa Directiva",
    "Composição atual da Mesa Diretora do Senado Federal, com uma linha por cargo ocupado.",
    "Current composition of the Directing Board of the Federal Senate, one row per occupied position.",
    "Composición actual de la Mesa Directiva del Senado Federal, con una fila por cargo ocupado.",
    [
        (
            "id_colegiado",
            "str",
            "Código identificador do colegiado da Mesa",
            "Identifier code of the board's collegiate body",
            "Código identificador del colegiado de la Mesa",
            {"notnull": True},
        ),
        (
            "sigla_colegiado",
            "str",
            "Sigla do colegiado da Mesa",
            "Abbreviation of the board's collegiate body",
            "Sigla del colegiado de la Mesa",
        ),
        (
            "nome_colegiado",
            "str",
            "Nome do colegiado da Mesa",
            "Name of the board's collegiate body",
            "Nombre del colegiado de la Mesa",
        ),
        (
            "cargo",
            "str",
            "Cargo ocupado na Mesa Diretora",
            "Position held on the Directing Board",
            "Cargo ocupado en la Mesa Directiva",
            {"notnull": True},
        ),
        (
            "id_senador",
            "str",
            "Código identificador do parlamentar",
            "Senator identifier code",
            "Código identificador del parlamentario",
        ),
        (
            "nome_parlamentar",
            "str",
            "Nome do parlamentar",
            "Senator's name",
            "Nombre del parlamentario",
        ),
        (
            "bancada",
            "str",
            "Bancada do parlamentar (partido e UF)",
            "Senator's bench (party and federative unit)",
            "Bancada del parlamentario (partido y unidad federativa)",
        ),
        (
            "ordem",
            "str",
            "Número de ordem do cargo na Mesa",
            "Order number of the position on the board",
            "Número de orden del cargo en la Mesa",
        ),
        (
            "origem",
            "str",
            "Origem da ocupação do cargo",
            "Origin of the position occupancy",
            "Origen de la ocupación del cargo",
        ),
    ],
    unique=["id_colegiado", "cargo"],
    ol=["id_colegiado"],
)

# ============================================================ senador_mandato
_t(
    "senador_mandato",
    "Mandatos dos Senadores",
    "Senators' Mandates",
    "Mandatos de los Senadores",
    "Mandatos exercidos por cada senador no Senado Federal, com a unidade da federação, a condição de titular ou suplente e as legislaturas cobertas pelo mandato, com uma linha por mandato.",
    "Mandates held by each senator in the Federal Senate, with the federative unit, the titular or substitute status and the legislatures covered by the mandate, one row per mandate.",
    "Mandatos ejercidos por cada senador en el Senado Federal, con la unidad federativa, la condición de titular o suplente y las legislaturas cubiertas por el mandato, con una fila por mandato.",
    [
        (
            "id_senador",
            "str",
            "Código identificador do parlamentar no Senado Federal",
            "Senator identifier code in the Federal Senate",
            "Código identificador del parlamentario en el Senado Federal",
            {"notnull": True},
        ),
        (
            "id_mandato",
            "str",
            "Código identificador do mandato",
            "Mandate identifier code",
            "Código identificador del mandato",
            {"notnull": True},
        ),
        (
            "sigla_uf",
            "str",
            "Sigla da unidade da federação de mandato",
            "Federative unit abbreviation of the mandate",
            "Sigla de la unidad federativa del mandato",
            {"dir": DIR_UF},
        ),
        (
            "participacao",
            "str",
            "Condição de participação no mandato (Titular ou Suplente)",
            "Participation status in the mandate (Titular or Substitute)",
            "Condición de participación en el mandato (Titular o Suplente)",
            {"dict": True},
        ),
        (
            "numero_legislatura_1",
            "str",
            "Número da primeira legislatura do mandato",
            "Number of the first legislature of the mandate",
            "Número de la primera legislatura del mandato",
        ),
        (
            "data_inicio_legislatura_1",
            "date",
            "Data de início da primeira legislatura do mandato",
            "Start date of the first legislature of the mandate",
            "Fecha de inicio de la primera legislatura del mandato",
        ),
        (
            "data_fim_legislatura_1",
            "date",
            "Data de término da primeira legislatura do mandato",
            "End date of the first legislature of the mandate",
            "Fecha de término de la primera legislatura del mandato",
        ),
        (
            "numero_legislatura_2",
            "str",
            "Número da segunda legislatura do mandato, quando houver",
            "Number of the second legislature of the mandate, when applicable",
            "Número de la segunda legislatura del mandato, cuando corresponda",
        ),
        (
            "data_inicio_legislatura_2",
            "date",
            "Data de início da segunda legislatura do mandato, quando houver",
            "Start date of the second legislature of the mandate, when applicable",
            "Fecha de inicio de la segunda legislatura del mandato, cuando corresponda",
        ),
        (
            "data_fim_legislatura_2",
            "date",
            "Data de término da segunda legislatura do mandato, quando houver",
            "End date of the second legislature of the mandate, when applicable",
            "Fecha de término de la segunda legislatura del mandato, cuando corresponda",
        ),
    ],
    unique=["id_senador", "id_mandato"],
    ol=["id_senador"],
)

# ============================================================ senador_filiacao
_t(
    "senador_filiacao",
    "Filiações Partidárias dos Senadores",
    "Senators' Party Affiliations",
    "Filiaciones Partidarias de los Senadores",
    "Histórico de filiações partidárias de cada senador, com o partido e as datas de filiação e desfiliação, com uma linha por filiação.",
    "History of party affiliations of each senator, with the party and the affiliation and disaffiliation dates, one row per affiliation.",
    "Historial de filiaciones partidarias de cada senador, con el partido y las fechas de filiación y desafiliación, con una fila por filiación.",
    [
        (
            "id_senador",
            "str",
            "Código identificador do parlamentar no Senado Federal",
            "Senator identifier code in the Federal Senate",
            "Código identificador del parlamentario en el Senado Federal",
            {"notnull": True},
        ),
        (
            "id_partido",
            "str",
            "Código identificador do partido de filiação",
            "Identifier code of the affiliation party",
            "Código identificador del partido de filiación",
        ),
        (
            "sigla_partido",
            "str",
            "Sigla do partido de filiação na data da filiação",
            "Abbreviation of the affiliation party at the affiliation date",
            "Sigla del partido de filiación en la fecha de la filiación",
        ),
        (
            "data_filiacao",
            "date",
            "Data de filiação ao partido",
            "Date of affiliation to the party",
            "Fecha de filiación al partido",
        ),
        (
            "data_desfiliacao",
            "date",
            "Data de desfiliação do partido, quando houver",
            "Date of disaffiliation from the party, when applicable",
            "Fecha de desafiliación del partido, cuando corresponda",
        ),
    ],
    unique=["id_senador", "id_partido", "data_filiacao"],
    ol=["id_senador"],
)

# ============================================================ senador_comissao
_t(
    "senador_comissao",
    "Comissões dos Senadores",
    "Senators' Committee Memberships",
    "Comisiones de los Senadores",
    "Participações de cada senador em comissões, conselhos, frentes e demais colegiados, com a condição de titular ou suplente e o período de participação, com uma linha por participação.",
    "Memberships of each senator in committees, councils, fronts and other collegiate bodies, with the titular or substitute status and the participation period, one row per membership.",
    "Participaciones de cada senador en comisiones, consejos, frentes y demás colegiados, con la condición de titular o suplente y el período de participación, con una fila por participación.",
    [
        (
            "id_senador",
            "str",
            "Código identificador do parlamentar no Senado Federal",
            "Senator identifier code in the Federal Senate",
            "Código identificador del parlamentario en el Senado Federal",
            {"notnull": True},
        ),
        (
            "id_comissao",
            "str",
            "Código identificador do colegiado",
            "Collegiate body identifier code",
            "Código identificador del colegiado",
        ),
        (
            "sigla_comissao",
            "str",
            "Sigla do colegiado",
            "Collegiate body abbreviation",
            "Sigla del colegiado",
        ),
        (
            "sigla_casa",
            "str",
            "Sigla da casa legislativa do colegiado",
            "Legislative house abbreviation of the body",
            "Sigla de la cámara legislativa del colegiado",
        ),
        (
            "participacao",
            "str",
            "Condição de participação no colegiado (Titular ou Suplente)",
            "Participation status in the body (Titular or Substitute)",
            "Condición de participación en el colegiado (Titular o Suplente)",
            {"dict": True},
        ),
        (
            "data_inicio",
            "date",
            "Data de início da participação no colegiado",
            "Start date of the membership in the body",
            "Fecha de inicio de la participación en el colegiado",
        ),
        (
            "data_fim",
            "date",
            "Data de término da participação no colegiado, quando houver",
            "End date of the membership in the body, when applicable",
            "Fecha de término de la participación en el colegiado, cuando corresponda",
        ),
    ],
    unique=["id_senador", "id_comissao", "data_inicio"],
    ol=["id_senador"],
)

# ============================================================ senador_cargo
_t(
    "senador_cargo",
    "Cargos dos Senadores",
    "Senators' Positions",
    "Cargos de los Senadores",
    "Cargos exercidos por cada senador em comissões, conselhos, frentes e demais colegiados, com a descrição do cargo e o período de exercício, com uma linha por cargo.",
    "Positions held by each senator in committees, councils, fronts and other collegiate bodies, with the position description and the term of office, one row per position.",
    "Cargos ejercidos por cada senador en comisiones, consejos, frentes y demás colegiados, con la descripción del cargo y el período de ejercicio, con una fila por cargo.",
    [
        (
            "id_senador",
            "str",
            "Código identificador do parlamentar no Senado Federal",
            "Senator identifier code in the Federal Senate",
            "Código identificador del parlamentario en el Senado Federal",
            {"notnull": True},
        ),
        (
            "id_comissao",
            "str",
            "Código identificador do colegiado do cargo",
            "Identifier code of the position's collegiate body",
            "Código identificador del colegiado del cargo",
        ),
        (
            "sigla_comissao",
            "str",
            "Sigla do colegiado do cargo",
            "Abbreviation of the position's collegiate body",
            "Sigla del colegiado del cargo",
        ),
        (
            "id_cargo",
            "str",
            "Código identificador do cargo",
            "Position identifier code",
            "Código identificador del cargo",
        ),
        (
            "descricao_cargo",
            "str",
            "Descrição do cargo exercido",
            "Description of the position held",
            "Descripción del cargo ejercido",
        ),
        (
            "data_inicio",
            "date",
            "Data de início do exercício do cargo",
            "Start date of the position's term",
            "Fecha de inicio del ejercicio del cargo",
        ),
        (
            "data_fim",
            "date",
            "Data de término do exercício do cargo, quando houver",
            "End date of the position's term, when applicable",
            "Fecha de término del ejercicio del cargo, cuando corresponda",
        ),
    ],
    unique=["id_senador", "id_comissao", "id_cargo", "data_inicio"],
    ol=["id_senador"],
)

# ============================================================ relatoria
_t(
    "relatoria",
    "Relatorias",
    "Rapporteurships",
    "Relatorías",
    "Designações de relatoria de processos legislativos em colegiados do Senado Federal e do Congresso Nacional, ligando cada processo ao senador relator, com uma linha por designação.",
    "Rapporteurship designations of legislative processes in collegiate bodies of the Federal Senate and National Congress, linking each process to the rapporteur senator, one row per designation.",
    "Designaciones de relatoría de procesos legislativos en colegiados del Senado Federal y del Congreso Nacional, vinculando cada proceso al senador relator, con una fila por designación.",
    [
        (
            "ano",
            "int",
            "Ano de apresentação do processo relatado",
            "Presentation year of the reported process",
            "Año de presentación del proceso relatado",
            {"part": True, "notnull": True, "dir": DIR_ANO},
        ),
        (
            "id_relatoria",
            "str",
            "Código identificador da relatoria",
            "Rapporteurship identifier code",
            "Código identificador de la relatoría",
            {"notnull": True},
        ),
        (
            "id_processo",
            "str",
            "Código identificador do processo legislativo relatado",
            "Identifier code of the reported legislative process",
            "Código identificador del proceso legislativo relatado",
            {"notnull": True},
        ),
        (
            "codigo_materia",
            "str",
            "Código legado da matéria no sistema MATE",
            "Legacy code of the matter in the MATE system",
            "Código heredado de la materia en el sistema MATE",
        ),
        (
            "identificacao_processo",
            "str",
            "Identificação do processo relatado (sigla, número e ano)",
            "Identification of the reported process (abbreviation, number and year)",
            "Identificación del proceso relatado (sigla, número y año)",
        ),
        (
            "id_senador",
            "str",
            "Código identificador do parlamentar relator",
            "Identifier code of the rapporteur senator",
            "Código identificador del parlamentario relator",
            {"notnull": True},
        ),
        (
            "sigla_casa_relator",
            "str",
            "Sigla da casa legislativa do relator",
            "Legislative house abbreviation of the rapporteur",
            "Sigla de la cámara legislativa del relator",
        ),
        (
            "id_colegiado",
            "str",
            "Código identificador do colegiado da relatoria",
            "Identifier code of the rapporteurship's collegiate body",
            "Código identificador del colegiado de la relatoría",
        ),
        (
            "sigla_colegiado",
            "str",
            "Sigla do colegiado da relatoria",
            "Abbreviation of the rapporteurship's collegiate body",
            "Sigla del colegiado de la relatoría",
        ),
        (
            "nome_colegiado",
            "str",
            "Nome do colegiado da relatoria",
            "Name of the rapporteurship's collegiate body",
            "Nombre del colegiado de la relatoría",
        ),
        (
            "id_tipo_colegiado",
            "str",
            "Código do tipo de colegiado da relatoria",
            "Code of the rapporteurship's collegiate body type",
            "Código del tipo de colegiado de la relatoría",
        ),
        (
            "tipo_relator",
            "str",
            "Descrição do tipo de relator (Relator, Relator-Revisor)",
            "Description of the rapporteur type (Rapporteur, Revising Rapporteur)",
            "Descripción del tipo de relator (Relator, Relator-Revisor)",
            {"dict": True},
        ),
        (
            "id_tipo_relator",
            "str",
            "Código do tipo de relator",
            "Code of the rapporteur type",
            "Código del tipo de relator",
        ),
        (
            "numero_autuacao",
            "str",
            "Número de autuação do processo no colegiado",
            "Filing number of the process in the collegiate body",
            "Número de autuación del proceso en el colegiado",
        ),
        (
            "tipo_encerramento",
            "str",
            "Descrição do tipo de encerramento da relatoria, quando houver",
            "Description of the rapporteurship closure type, when applicable",
            "Descripción del tipo de cierre de la relatoría, cuando corresponda",
        ),
        (
            "data_designacao",
            "date",
            "Data de designação da relatoria",
            "Date of the rapporteurship designation",
            "Fecha de designación de la relatoría",
        ),
        (
            "data_destituicao",
            "date",
            "Data de destituição da relatoria, quando houver",
            "Date of the rapporteurship dismissal, when applicable",
            "Fecha de destitución de la relatoría, cuando corresponda",
        ),
        (
            "tramitando",
            "str",
            "Indica se o processo relatado está tramitando (S/N)",
            "Indicates whether the reported process is under way (S/N)",
            "Indica si el proceso relatado está en trámite (S/N)",
            {"dict": True},
        ),
    ],
    unique=["id_relatoria"],
    partition="ano",
    ol=["ano", "id_processo", "id_senador"],
)

# ============================================================ votacao_comissao
_t(
    "votacao_comissao",
    "Votações em Comissões",
    "Committee Votes",
    "Votaciones en Comisiones",
    "Votações realizadas em comissões e demais colegiados do Senado Federal e do Congresso Nacional, com uma linha por votação e os totais de votos apurados.",
    "Votes held in committees and other collegiate bodies of the Federal Senate and National Congress, one row per vote with the tallied vote totals.",
    "Votaciones realizadas en comisiones y demás colegiados del Senado Federal y del Congreso Nacional, con una fila por votación y los totales de votos computados.",
    [
        (
            "ano",
            "int",
            "Ano da reunião em que ocorreu a votação",
            "Year of the meeting in which the vote took place",
            "Año de la reunión en que ocurrió la votación",
            {"part": True, "notnull": True, "dir": DIR_ANO},
        ),
        (
            "id_votacao",
            "str",
            "Código identificador da votação em comissão",
            "Committee vote identifier code",
            "Código identificador de la votación en comisión",
            {"notnull": True},
        ),
        (
            "id_comissao",
            "str",
            "Código identificador do colegiado",
            "Collegiate body identifier code",
            "Código identificador del colegiado",
        ),
        (
            "sigla_colegiado",
            "str",
            "Sigla do colegiado em que ocorreu a votação",
            "Abbreviation of the collegiate body where the vote took place",
            "Sigla del colegiado en que ocurrió la votación",
        ),
        (
            "nome_colegiado",
            "str",
            "Nome do colegiado em que ocorreu a votação",
            "Name of the collegiate body where the vote took place",
            "Nombre del colegiado en que ocurrió la votación",
        ),
        (
            "sigla_casa_colegiado",
            "str",
            "Sigla da casa legislativa do colegiado",
            "Legislative house abbreviation of the body",
            "Sigla de la cámara legislativa del colegiado",
        ),
        (
            "id_reuniao",
            "str",
            "Código identificador da reunião",
            "Meeting identifier code",
            "Código identificador de la reunión",
        ),
        (
            "numero_reuniao",
            "str",
            "Número da reunião do colegiado",
            "Meeting number of the collegiate body",
            "Número de la reunión del colegiado",
        ),
        (
            "tipo_reuniao",
            "str",
            "Tipo da reunião (Ordinária, Extraordinária)",
            "Meeting type (Ordinary, Extraordinary)",
            "Tipo de la reunión (Ordinaria, Extraordinaria)",
        ),
        (
            "data_reuniao",
            "date",
            "Data da reunião em que ocorreu a votação",
            "Date of the meeting in which the vote took place",
            "Fecha de la reunión en que ocurrió la votación",
        ),
        (
            "identificacao_materia",
            "str",
            "Identificação da matéria votada (sigla, número e ano)",
            "Identification of the voted matter (abbreviation, number and year)",
            "Identificación de la materia votada (sigla, número y año)",
        ),
        (
            "sigla_materia",
            "str",
            "Sigla do tipo da matéria votada",
            "Abbreviation of the voted matter type",
            "Sigla del tipo de la materia votada",
        ),
        (
            "numero_materia",
            "str",
            "Número da matéria votada",
            "Number of the voted matter",
            "Número de la materia votada",
        ),
        (
            "ano_materia",
            "int",
            "Ano da matéria votada",
            "Year of the voted matter",
            "Año de la materia votada",
        ),
        (
            "descricao",
            "str",
            "Descrição do objeto da votação",
            "Description of the vote's subject",
            "Descripción del objeto de la votación",
        ),
        (
            "id_senador_presidente",
            "str",
            "Código identificador do parlamentar que presidiu a votação",
            "Identifier code of the senator who chaired the vote",
            "Código identificador del parlamentario que presidió la votación",
        ),
        (
            "voto_sim",
            "int",
            "Quantidade de votos Sim",
            "Number of Yes votes",
            "Cantidad de votos Sí",
            {"unit": "voto"},
        ),
        (
            "voto_nao",
            "int",
            "Quantidade de votos Não",
            "Number of No votes",
            "Cantidad de votos No",
            {"unit": "voto"},
        ),
        (
            "voto_abstencao",
            "int",
            "Quantidade de abstenções",
            "Number of abstentions",
            "Cantidad de abstenciones",
            {"unit": "voto"},
        ),
    ],
    unique=["id_votacao"],
    partition="ano",
    ol=["ano", "id_votacao"],
)

# ============================================================ votacao_comissao_parlamentar
_t(
    "votacao_comissao_parlamentar",
    "Votos dos Parlamentares em Comissões",
    "Senators' Committee Votes",
    "Votos de los Parlamentarios en Comisiones",
    "Voto individual de cada parlamentar em cada votação de comissão, com uma linha por par votação-parlamentar.",
    "Individual vote of each senator in each committee vote, one row per vote-senator pair.",
    "Voto individual de cada parlamentario en cada votación de comisión, con una fila por par votación-parlamentario.",
    [
        (
            "ano",
            "int",
            "Ano da reunião em que ocorreu a votação",
            "Year of the meeting in which the vote took place",
            "Año de la reunión en que ocurrió la votación",
            {"part": True, "notnull": True, "dir": DIR_ANO},
        ),
        (
            "id_votacao",
            "str",
            "Código identificador da votação em comissão",
            "Committee vote identifier code",
            "Código identificador de la votación en comisión",
            {"notnull": True},
        ),
        (
            "data_reuniao",
            "date",
            "Data da reunião em que ocorreu a votação",
            "Date of the meeting in which the vote took place",
            "Fecha de la reunión en que ocurrió la votación",
        ),
        (
            "id_senador",
            "str",
            "Código identificador do parlamentar votante",
            "Identifier code of the voting senator",
            "Código identificador del parlamentario votante",
            {"notnull": True},
        ),
        (
            "sigla_partido",
            "str",
            "Sigla do partido do parlamentar na votação",
            "Party abbreviation of the senator at the vote",
            "Sigla del partido del parlamentario en la votación",
        ),
        (
            "sigla_casa",
            "str",
            "Sigla da casa legislativa do parlamentar",
            "Legislative house abbreviation of the senator",
            "Sigla de la cámara legislativa del parlamentario",
        ),
        (
            "voto",
            "str",
            "Qualidade do voto do parlamentar (S, N, A)",
            "Quality of the senator's vote (S, N, A)",
            "Calidad del voto del parlamentario (S, N, A)",
            {"dict": True},
        ),
        (
            "voto_presidente",
            "str",
            "Indica se o parlamentar votou como presidente (true/false)",
            "Indicates whether the senator voted as chair (true/false)",
            "Indica si el parlamentario votó como presidente (true/false)",
            {"dict": True},
        ),
    ],
    unique=["id_votacao", "id_senador"],
    partition="ano",
    ol=["ano", "id_votacao", "id_senador"],
)

# ============================================================ discurso
_t(
    "discurso",
    "Discursos",
    "Speeches",
    "Discursos",
    "Pronunciamentos de parlamentares nas sessões plenárias do Senado Federal e do Congresso Nacional, com o autor, o resumo e a indexação temática, com uma linha por pronunciamento.",
    "Speeches by parliamentarians in plenary sessions of the Federal Senate and National Congress, with the author, the summary and the thematic indexing, one row per speech.",
    "Pronunciamientos de parlamentarios en las sesiones plenarias del Senado Federal y del Congreso Nacional, con el autor, el resumen y la indexación temática, con una fila por pronunciamiento.",
    [
        (
            "ano",
            "int",
            "Ano da sessão em que ocorreu o pronunciamento",
            "Year of the session in which the speech took place",
            "Año de la sesión en que ocurrió el pronunciamiento",
            {"part": True, "notnull": True, "dir": DIR_ANO},
        ),
        (
            "id_pronunciamento",
            "str",
            "Código identificador do pronunciamento",
            "Speech identifier code",
            "Código identificador del pronunciamiento",
            {"notnull": True},
        ),
        (
            "id_sessao",
            "str",
            "Código identificador da sessão",
            "Session identifier code",
            "Código identificador de la sesión",
        ),
        (
            "data_sessao",
            "date",
            "Data da sessão em que ocorreu o pronunciamento",
            "Date of the session in which the speech took place",
            "Fecha de la sesión en que ocurrió el pronunciamiento",
        ),
        (
            "sigla_casa",
            "str",
            "Sigla da casa legislativa da sessão (SF, CN)",
            "Legislative house abbreviation of the session (SF, CN)",
            "Sigla de la cámara legislativa de la sesión (SF, CN)",
        ),
        (
            "sigla_tipo_sessao",
            "str",
            "Sigla do tipo de sessão",
            "Session type abbreviation",
            "Sigla del tipo de sesión",
        ),
        (
            "numero_sessao",
            "str",
            "Número da sessão",
            "Session number",
            "Número de la sesión",
        ),
        (
            "id_senador",
            "str",
            "Código identificador do parlamentar autor do pronunciamento",
            "Identifier code of the senator who authored the speech",
            "Código identificador del parlamentario autor del pronunciamiento",
        ),
        (
            "tipo_autor",
            "str",
            "Tipo do autor do pronunciamento",
            "Type of the speech author",
            "Tipo del autor del pronunciamiento",
        ),
        (
            "sigla_partido",
            "str",
            "Sigla do partido do autor no pronunciamento",
            "Party abbreviation of the author at the speech",
            "Sigla del partido del autor en el pronunciamiento",
        ),
        (
            "sigla_uf",
            "str",
            "Sigla da unidade da federação do autor",
            "Federative unit abbreviation of the author",
            "Sigla de la unidad federativa del autor",
        ),
        (
            "sigla_tipo_uso_palavra",
            "str",
            "Sigla do tipo de uso da palavra (DIS, APA)",
            "Abbreviation of the type of use of the floor (DIS, APA)",
            "Sigla del tipo de uso de la palabra (DIS, APA)",
            {"dict": True},
        ),
        (
            "descricao_tipo_uso_palavra",
            "str",
            "Descrição do tipo de uso da palavra",
            "Description of the type of use of the floor",
            "Descripción del tipo de uso de la palabra",
        ),
        (
            "resumo",
            "str",
            "Resumo do pronunciamento",
            "Summary of the speech",
            "Resumen del pronunciamiento",
        ),
        (
            "indexacao",
            "str",
            "Indexação temática do pronunciamento",
            "Thematic indexing of the speech",
            "Indexación temática del pronunciamiento",
        ),
        (
            "url_texto",
            "str",
            "URL do texto integral do pronunciamento",
            "URL of the full text of the speech",
            "URL del texto íntegro del pronunciamiento",
        ),
    ],
    unique=["id_pronunciamento"],
    partition="ano",
    ol=["ano", "id_pronunciamento", "id_senador"],
)
