{{
    config(
        alias="teacher_context_grade_4",
        schema="world_iea_timss",
        materialized="table",
    )
}}
select
    safe_cast(year as int64) year,
    safe_cast(country_id as string) country_id,
    safe_cast(country_m49 as string) country_m49,
    safe_cast(grade_id as string) grade_id,
    safe_cast(school_id as string) school_id,
    safe_cast(teacher_id as string) teacher_id,
    safe_cast(link_id as string) link_id,
    safe_cast(tealin_id as string) tealin_id,
    safe_cast(course as string) course,
    safe_cast(subject_id as string) subject_id,
    safe_cast(language_school_questionnaire as string) language_school_questionnaire,
    safe_cast(locale_school_questionnaire as string) locale_school_questionnaire,
    safe_cast(atbg01 as int64) atbg01,
    safe_cast(atbg02 as string) atbg02,
    safe_cast(atbg03 as string) atbg03,
    safe_cast(atbg04 as string) atbg04,
    safe_cast(atbg05ba as string) atbg05ba,
    safe_cast(atbg05bb as string) atbg05bb,
    safe_cast(atbg05bd as string) atbg05bd,
    safe_cast(atbg06a as string) atbg06a,
    safe_cast(atbg06b as string) atbg06b,
    safe_cast(atbg06c as string) atbg06c,
    safe_cast(atbg06d as string) atbg06d,
    safe_cast(atbg06e as string) atbg06e,
    safe_cast(atbg06f as string) atbg06f,
    safe_cast(atbg06g as string) atbg06g,
    safe_cast(atbg06h as string) atbg06h,
    safe_cast(atbg06i as string) atbg06i,
    safe_cast(atbg06j as string) atbg06j,
    safe_cast(atbg06k as string) atbg06k,
    safe_cast(atbg07a as string) atbg07a,
    safe_cast(atbg07b as string) atbg07b,
    safe_cast(atbg07c as string) atbg07c,
    safe_cast(atbg07d as string) atbg07d,
    safe_cast(atbg07e as string) atbg07e,
    safe_cast(atbg07f as string) atbg07f,
    safe_cast(atbg07g as string) atbg07g,
    safe_cast(atbg08a as string) atbg08a,
    safe_cast(atbg08b as string) atbg08b,
    safe_cast(atbg08c as string) atbg08c,
    safe_cast(atbg08d as string) atbg08d,
    safe_cast(atbg08e as string) atbg08e,
    safe_cast(atbg08f as string) atbg08f,
    safe_cast(atbg08g as string) atbg08g,
    safe_cast(atbg09a as string) atbg09a,
    safe_cast(atbg09b as string) atbg09b,
    safe_cast(atbg09c as string) atbg09c,
    safe_cast(atbg09d as string) atbg09d,
    safe_cast(atbg09e as string) atbg09e,
    safe_cast(atbg09f as string) atbg09f,
    safe_cast(atbg09g as string) atbg09g,
    safe_cast(atbg09h as string) atbg09h,
    safe_cast(atbg10a as int64) atbg10a,
    safe_cast(atbg10b as int64) atbg10b,
    safe_cast(atbg11 as int64) atbg11,
    safe_cast(atbg12a as string) atbg12a,
    safe_cast(atbg12b as string) atbg12b,
    safe_cast(atbg12c as string) atbg12c,
    safe_cast(atbg12d as string) atbg12d,
    safe_cast(atbg12e as string) atbg12e,
    safe_cast(atbg12f as string) atbg12f,
    safe_cast(atbg12g as string) atbg12g,
    safe_cast(atbg13a as string) atbg13a,
    safe_cast(atbg13b as string) atbg13b,
    safe_cast(atbg13c as string) atbg13c,
    safe_cast(atbg13d as string) atbg13d,
    safe_cast(atbg13e as string) atbg13e,
    safe_cast(atbg13f as string) atbg13f,
    safe_cast(atbg13g as string) atbg13g,
    safe_cast(atbg13h as string) atbg13h,
    safe_cast(atbg13i as string) atbg13i,
    safe_cast(atdgeas as string) atdgeas,
    safe_cast(atdgsos as string) atdgsos,
    safe_cast(atdgtjs as string) atdgtjs,
    safe_cast(atdglsn as string) atdglsn,
    safe_cast(atdmmem as string) atdmmem,
    safe_cast(atdsmes as string) atdsmes,
    safe_cast(atdmnum as float64) atdmnum,
    safe_cast(atdmgeo as float64) atdmgeo,
    safe_cast(atdmdat as float64) atdmdat,
    safe_cast(atdslif as float64) atdslif,
    safe_cast(atdsphy as float64) atdsphy,
    safe_cast(atdsear as float64) atdsear,
    safe_cast(atdmhw as float64) atdmhw,
    safe_cast(atdshw as float64) atdshw,
    safe_cast(version as int64) version,
    safe_cast(scope as string) scope,
from {{ set_datalake_project("world_iea_timss_staging.teacher_context_grade_4") }} as t
