{{
    config(
        alias="execucao",
        schema="br_cgu_despesas_publicas",
        materialized="table",
        partition_by={
            "field": "ano",
            "data_type": "int64",
            "range": {"start": 2014, "end": 2031, "interval": 1},
        },
        cluster_by=["mes", "id_orgao_superior"],
    )
}}

select
    safe_cast(ano as int64) ano,
    safe_cast(mes as int64) mes,
    safe_cast(id_orgao_superior as string) id_orgao_superior,
    safe_cast(nome_orgao_superior as string) nome_orgao_superior,
    safe_cast(id_orgao_subordinado as string) id_orgao_subordinado,
    safe_cast(nome_orgao_subordinado as string) nome_orgao_subordinado,
    safe_cast(id_unidade_gestora as string) id_unidade_gestora,
    safe_cast(nome_unidade_gestora as string) nome_unidade_gestora,
    safe_cast(id_gestao as string) id_gestao,
    safe_cast(nome_gestao as string) nome_gestao,
    safe_cast(id_unidade_orcamentaria as string) id_unidade_orcamentaria,
    safe_cast(nome_unidade_orcamentaria as string) nome_unidade_orcamentaria,
    safe_cast(id_funcao as string) id_funcao,
    safe_cast(nome_funcao as string) nome_funcao,
    safe_cast(id_subfuncao as string) id_subfuncao,
    safe_cast(nome_subfuncao as string) nome_subfuncao,
    safe_cast(id_programa_orcamentario as string) id_programa_orcamentario,
    safe_cast(nome_programa_orcamentario as string) nome_programa_orcamentario,
    safe_cast(id_acao as string) id_acao,
    safe_cast(nome_acao as string) nome_acao,
    safe_cast(id_plano_orcamentario as string) id_plano_orcamentario,
    safe_cast(nome_plano_orcamentario as string) nome_plano_orcamentario,
    safe_cast(id_programa_governo as string) id_programa_governo,
    safe_cast(nome_programa_governo as string) nome_programa_governo,
    safe_cast(sigla_uf as string) sigla_uf,
    safe_cast(nome_municipio as string) nome_municipio,
    safe_cast(id_subtitulo as string) id_subtitulo,
    safe_cast(nome_subtitulo as string) nome_subtitulo,
    safe_cast(id_localizador as string) id_localizador,
    safe_cast(nome_localizador as string) nome_localizador,
    safe_cast(sigla_localizador as string) sigla_localizador,
    safe_cast(descricao_complementar_localizador as string) descricao_complementar_localizador,
    safe_cast(id_autor_emenda as string) id_autor_emenda,
    safe_cast(nome_autor_emenda as string) nome_autor_emenda,
    safe_cast(id_categoria_economica as string) id_categoria_economica,
    safe_cast(nome_categoria_economica as string) nome_categoria_economica,
    safe_cast(id_grupo_despesa as string) id_grupo_despesa,
    safe_cast(nome_grupo_despesa as string) nome_grupo_despesa,
    safe_cast(id_elemento_despesa as string) id_elemento_despesa,
    safe_cast(nome_elemento_despesa as string) nome_elemento_despesa,
    safe_cast(id_modalidade_despesa as string) id_modalidade_despesa,
    safe_cast(nome_modalidade_despesa as string) nome_modalidade_despesa,
    safe_cast(valor_empenhado as float64) valor_empenhado,
    safe_cast(valor_liquidado as float64) valor_liquidado,
    safe_cast(valor_pago as float64) valor_pago,
    safe_cast(valor_restos_pagar_inscritos as float64) valor_restos_pagar_inscritos,
    safe_cast(valor_restos_pagar_cancelados as float64) valor_restos_pagar_cancelados,
    safe_cast(valor_restos_pagar_pagos as float64) valor_restos_pagar_pagos,
from {{ set_datalake_project("br_cgu_despesas_publicas_staging.execucao") }} as t
