#!/usr/bin/env python3
"""Generate the cl_ine_ene dbt models from the architecture CSV and the codebook.

Two models:

  cl_ine_ene__microdato    safe_casts every column of the staging table, in
                           architecture order
  cl_ine_ene__dicionario   the value->label map

The dicionario is emitted as a LITERAL select, not built from a staging table.
The ENE microdata carries codes only -- the labels exist nowhere but the INE
codebook PDFs -- so there is no label column to derive it from, and harvesting it
from whatever periods a run happened to clean would let it shrink silently. As a
literal it is a function of the codebook, which is the property that matters.
"""

from __future__ import annotations

import argparse
import csv
import json
import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent
OVERRIDES = json.loads((HERE / "overrides.json").read_text())

DATASET = "cl_ine_ene"
TABLE = "microdato"
START_YEAR, END_YEAR = 2010, 2031

MODEL_HEADER = """{{{{
    config(
        schema="{dataset}",
        alias="{table}",
        materialized="table",
        partition_by={{
            "field": "ano",
            "data_type": "int64",
            "range": {{"start": {start}, "end": {end}, "interval": 1}},
        }},
    )
}}}}


select
"""


def sql_literal(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def cast(name: str, bq_type: str) -> str:
    return f"    safe_cast({name} as {bq_type.lower()}) {name},"


def write_microdato(rows, out_dir):
    body = MODEL_HEADER.format(
        dataset=DATASET, table=TABLE, start=START_YEAR, end=END_YEAR
    )
    lines = [cast(r["name"], r["bigquery_type"]) for r in rows]
    lines[-1] = lines[-1].rstrip(",")
    body += "\n".join(lines)
    body += f'\nfrom {{{{ set_datalake_project("{DATASET}_staging.{TABLE}") }}}} as t\n'
    path = out_dir / f"{DATASET}__{TABLE}.sql"
    path.write_text(body)
    return path


CODE_SPLIT = re.compile(r"^(\d{1,5}):\s*(.+)$")


def dicionario_rows(arch_rows, codebook):
    """(id_tabela, nome_coluna, chave, cobertura_temporal, valor), deduplicated."""
    out, seen = [], set()
    for row in arch_rows:
        if row["covered_by_dictionary"] != "yes":
            continue
        name = row["name"]
        source = row["original_name"] or name
        cats = (
            OVERRIDES["categories"].get(name)
            or codebook.get(source, {}).get("cats")
            or []
        )
        for raw in cats:
            match = CODE_SPLIT.match(raw.strip())
            if not match:
                continue
            key, label = (
                match.group(1),
                " ".join(match.group(2).split()).rstrip("."),
            )
            if (name, key) in seen:
                continue
            seen.add((name, key))
            out.append((TABLE, name, key, "", label))
    return out


def write_dicionario(rows, out_dir):
    body = [
        f'{{{{ config(alias="dicionario", schema="{DATASET}", materialized="table") }}}}',
        "",
        "-- Value labels for every dictionary-covered column of cl_ine_ene.microdato.",
        "-- Transcribed from the two INE codebooks (codigos-ene-2019.pdf for the schema",
        "-- in force until NDE 2019, codigos-ene-2020.pdf for the current one); the",
        "-- microdata itself carries codes only, so there is nothing to derive this from.",
        "-- Generated by code/gen_dbt.py -- edit the codebook artefacts, not this file.",
        "",
        "select",
        "    id_tabela,",
        "    nome_coluna,",
        "    chave,",
        "    cobertura_temporal,",
        "    valor",
        "from unnest([",
    ]
    literals = []
    for table, column, key, coverage, label in rows:
        literals.append(
            "    struct("
            f"{sql_literal(table)} as id_tabela, "
            f"{sql_literal(column)} as nome_coluna, "
            f"{sql_literal(key)} as chave, "
            f"{sql_literal(coverage)} as cobertura_temporal, "
            f"{sql_literal(label)} as valor)"
        )
    body.append(",\n".join(literals))
    body.append("])")
    body.append("")
    path = out_dir / f"{DATASET}__dicionario.sql"
    path.write_text("\n".join(body))
    return path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--architecture", default=str(HERE / "architecture" / "microdato.csv")
    )
    parser.add_argument("--out", default=str(HERE.parent))
    args = parser.parse_args()

    with open(args.architecture, encoding="utf-8") as handle:
        arch_rows = list(csv.DictReader(handle))
    codebook = json.loads((HERE / "codebook_parsed.json").read_text())
    out_dir = pathlib.Path(args.out)

    model = write_microdato(arch_rows, out_dir)
    print(f"wrote {model} ({len(arch_rows)} columns)")

    rows = dicionario_rows(arch_rows, codebook)
    dic = write_dicionario(rows, out_dir)
    columns = len({r[1] for r in rows})
    print(f"wrote {dic} ({len(rows)} labels across {columns} columns)")


if __name__ == "__main__":
    main()
