"""Measure which LODES8 state-year-jobtype files actually exist.

LODES does not publish OD and WAC files for every state-year: a state joins the
LED partnership at a different date, and a few withdraw. LODESTechDoc8.4 has a
coverage table, but this script measures the published directory listings
instead, so the reported gaps are observed rather than quoted.

    uv run python models/us_census_lodes/code/availability.py

Writes ``availability.md`` next to this file. That report is the source for the
"coverage gaps" section of the dataset and table descriptions.
"""

from __future__ import annotations

import collections
import concurrent.futures as cf
import re
import sys
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from pipelines.datasets.us_census_lodes.constants import (
    BASE_URL,
    JOB_TYPES,
    SEGMENT,
    STATES,
    YEARS,
)
from pipelines.datasets.us_census_lodes.utils import USER_AGENT

OUT = Path(__file__).resolve().parent / "availability.md"


def listing(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=180) as resp:
        return resp.read().decode("utf-8", "replace")


def state_files(state: str) -> tuple[str, dict[str, set[tuple[str, int]]]]:
    """Return {family: {(job_type, year)}} for the S000 segment."""
    found: dict[str, set[tuple[str, int]]] = {}
    for family in ("rac", "wac"):
        try:
            html = listing(f"{BASE_URL}/{state}/{family}/")
        except Exception:
            found[family] = set()
            continue
        pat = rf"{state}_{family}_{SEGMENT}_(JT0\d)_(\d{{4}})\.csv\.gz"
        found[family] = {(jt, int(yr)) for jt, yr in re.findall(pat, html)}
    return state, found


def main() -> None:
    inv: dict[str, dict[str, set[tuple[str, int]]]] = {}
    with cf.ThreadPoolExecutor(8) as ex:
        for state, found in ex.map(state_files, STATES):
            inv[state] = found
            print(
                f"{state}: rac={len(found['rac'])} wac={len(found['wac'])}",
                flush=True,
            )

    lines = [
        "# us_census_lodes - measured file availability",
        "",
        "Generated by `code/availability.py` from the LODES8 directory listings.",
        f"Segment `{SEGMENT}`, job types {', '.join(JOB_TYPES)}, "
        f"years {YEARS[0]}-{YEARS[-1]}.",
        "",
        "A missing file is a real coverage gap in the source, not a download failure:",
        "LODES publishes nothing for a state-year-jobtype with no data.",
        "",
    ]

    # Per-year state counts, and which states are missing WAC entirely.
    lines += [
        "## States with no workplace (WAC) file, by year",
        "",
        "| Year | States with RAC but no WAC |",
        "|---|---|",
    ]
    for year in YEARS:
        missing = sorted(
            s
            for s in STATES
            if any(jt for jt, y in inv[s]["rac"] if y == year)
            and not any(jt for jt, y in inv[s]["wac"] if y == year)
        )
        lines.append(
            f"| {year} | {', '.join(m.upper() for m in missing) or '-'} |"
        )

    lines += [
        "",
        "## Job types present, by year (count of states)",
        "",
        "| Year | " + " | ".join(JOB_TYPES) + " |",
        "|" + "---|" * (len(JOB_TYPES) + 1),
    ]
    for year in YEARS:
        cells = []
        for jt in JOB_TYPES:
            n = sum(1 for s in STATES if (jt, year) in inv[s]["rac"])
            cells.append(str(n))
        lines.append(f"| {year} | " + " | ".join(cells) + " |")

    lines += ["", "## States never publishing a workplace file", ""]
    never = sorted(s for s in STATES if not inv[s]["wac"])
    lines.append(", ".join(s.upper() for s in never) or "none")

    lines += ["", "## Totals", ""]
    tot = collections.Counter()
    for state in STATES:
        for family in ("rac", "wac"):
            tot[family] += len(inv[state][family])
    for family in ("rac", "wac"):
        possible = len(STATES) * len(YEARS) * len(JOB_TYPES)
        lines.append(
            f"- `{family}` segment {SEGMENT}: {tot[family]:,} files published "
            f"of {possible:,} state x year x job-type combinations "
            f"({100 * tot[family] / possible:.1f}%)"
        )

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nwrote {OUT}")


if __name__ == "__main__":
    main()
