"""Validate the cleaned us_census_lodes parquet and write the real coverage report.

    uv run python models/us_census_lodes/code/validate.py

Two jobs:

1. **Consistency.** For every state-year sampled, the age bands, the earnings
   bands and the twenty NAICS sectors must each sum exactly to `jobs_total`.
   That is the strongest available check that the source-to-destination column
   mapping is right, and it costs one pass.

2. **The coverage report.** `availability.py` measures which *files* LODES
   publishes, but the tech doc warns that a published file may contain only its
   header. Row counts from the cleaned output are the ground truth, so the
   report written here — `coverage.md` — supersedes the file listing for any
   statement about which state-years actually carry data.
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

import pyarrow.parquet as pq

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from pipelines.datasets.us_census_lodes.constants import (
    OUTPUT,
    STATES,
    YEARS,
)

OUT = Path(__file__).resolve().parent / "coverage.md"
FACTS = ["residence_jobs", "workplace_jobs"]

BANDS = {
    "age": [
        "jobs_age_29_or_younger",
        "jobs_age_30_to_54",
        "jobs_age_55_or_older",
    ],
    "earnings": [
        "jobs_earnings_1250_or_less",
        "jobs_earnings_1251_to_3333",
        "jobs_earnings_above_3333",
    ],
}


def counts() -> dict[str, dict[tuple[str, int], int]]:
    """rows per (state, year) per fact table, from the parquet metadata alone."""
    out: dict[str, dict[tuple[str, int], int]] = {t: {} for t in FACTS}
    for table in FACTS:
        for path in sorted((OUTPUT / table).glob("year=*/*.parquet")):
            m = re.search(r"year=(\d{4})", str(path))
            if m is None:
                raise ValueError(f"unexpected parquet path, no year=: {path}")
            year = int(m.group(1))
            state = path.stem
            out[table][(state, year)] = pq.ParquetFile(path).metadata.num_rows
    return out


def check_consistency(
    sample_years: list[int], sample_states: list[str]
) -> list[str]:
    problems = []
    for table in FACTS:
        naics = None
        for state in sample_states:
            for year in sample_years:
                path = OUTPUT / table / f"year={year}" / f"{state}.parquet"
                if not path.exists():
                    continue
                df = pq.ParquetFile(path).read().to_pandas()
                if naics is None:
                    naics = [
                        c for c in df.columns if c.startswith("jobs_naics_")
                    ]
                total = df["jobs_total"].astype("int64")
                for label, cols in {**BANDS, "naics": naics}.items():
                    got = df[cols].astype("int64").sum(axis=1)
                    bad = int((got != total).sum())
                    if bad:
                        problems.append(
                            f"{table} {state} {year}: {label} bands do not sum to "
                            f"jobs_total on {bad:,} of {len(df):,} rows"
                        )
                if (total < 0).any():
                    problems.append(
                        f"{table} {state} {year}: negative jobs_total"
                    )
                if df["block_id"].str.len().nunique() != 1:
                    problems.append(
                        f"{table} {state} {year}: block_id is not fixed-width"
                    )
    return problems


def main() -> None:
    rows = counts()

    print("=== consistency ===")
    problems = check_consistency([2005, 2012, 2023], ["ca", "vt", "tx", "ny"])
    for p in problems:
        print(f"  FAIL {p}")
    if not problems:
        print(
            "  OK: age, earnings and NAICS bands each sum to jobs_total; "
            "block_id fixed-width; no negative totals"
        )

    totals = {t: sum(v.values()) for t, v in rows.items()}
    for table in FACTS:
        print(
            f"\n{table}: {totals[table]:,} rows across {len(rows[table])} state-years"
        )
    for table in ("geography_crosswalk", "dicionario"):
        files = list((OUTPUT / table).glob("**/*.parquet"))
        n = sum(pq.ParquetFile(f).metadata.num_rows for f in files)
        print(f"{table}: {n:,} rows across {len(files)} file(s)")

    # Report
    missing = defaultdict(list)
    for table in FACTS:
        for state in STATES:
            for year in YEARS:
                if rows[table].get((state, year), 0) == 0:
                    missing[table].append((state, year))

    lines = [
        "# us_census_lodes - measured coverage",
        "",
        "Generated by `code/validate.py` from row counts in the cleaned parquet.",
        "",
        "This is the authoritative gap report. `availability.md` measures which",
        "*files* LODES publishes; LODESTechDoc8.4 warns that a published file may",
        "contain only its header, so file existence overstates coverage. A",
        "state-year listed here has **no rows**, either because LODES publishes no",
        "file for it or because the file it publishes is empty.",
        "",
        "## Row counts",
        "",
        "| Table | Rows | State-years with data |",
        "|---|---|---|",
    ]
    for table in FACTS:
        lines.append(
            f"| `{table}` | {totals[table]:,} | "
            f"{len(rows[table])} of {len(STATES) * len(YEARS)} |"
        )
    for table in ("geography_crosswalk", "dicionario"):
        files = list((OUTPUT / table).glob("**/*.parquet"))
        n = sum(pq.ParquetFile(f).metadata.num_rows for f in files)
        lines.append(f"| `{table}` | {n:,} | n/a |")

    for table in FACTS:
        lines += ["", f"## State-years with no `{table}` data", ""]
        by_state = defaultdict(list)
        for state, year in missing[table]:
            by_state[state].append(year)
        if not by_state:
            lines.append("none")
            continue
        lines += ["| State | Years |", "|---|---|"]
        for state in sorted(by_state):
            ys = sorted(by_state[state])
            span = (
                f"{ys[0]}-{ys[-1]} (all)"
                if ys == list(range(ys[0], ys[-1] + 1)) and len(ys) > 2
                else ", ".join(str(y) for y in ys)
            )
            lines.append(f"| {state.upper()} | {span} |")

    lines += [
        "",
        "## Columns published only for part of the range",
        "",
        "These are NULL outside their window, not zero -- see `_null_unavailable`",
        "in `pipelines/datasets/us_census_lodes/utils.py`.",
        "",
        "| Columns | Published for |",
        "|---|---|",
        "| `jobs_race_*`, `jobs_ethnicity_*`, `jobs_education_*`, `jobs_sex_*` | data year >= 2009 |",
        "| `jobs_education_*`, additionally | workers aged 30 and over |",
        "| `jobs_firm_age_*`, `jobs_firm_size_*` | data year >= 2011 and job type JT02 only |",
        "| job types `JT04`, `JT05` (federal) | data year >= 2010 |",
        "",
    ]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nwrote {OUT}")
    if problems:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
