{{
    config(
        schema="us_eia_electricity",
        alias="generator",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 2001, "end": 2031, "interval": 1},
        },
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(plant_id as string) plant_id,
    safe_cast(generator_id as string) generator_id,
    safe_cast(plant_name as string) plant_name,
    safe_cast(utility_id as string) utility_id,
    safe_cast(utility_name as string) utility_name,
    safe_cast(state_abbreviation as string) state_abbreviation,
    safe_cast(state_id as string) state_id,
    safe_cast(county_name as string) county_name,
    safe_cast(county_id as string) county_id,
    safe_cast(generator_status_group as string) generator_status_group,
    safe_cast(operational_status_code as string) operational_status_code,
    safe_cast(unit_id as string) unit_id,
    safe_cast(ownership_code as string) ownership_code,
    safe_cast(sector_id as string) sector_id,
    safe_cast(sector_name as string) sector_name,
    safe_cast(prime_mover_code as string) prime_mover_code,
    safe_cast(technology_description as string) technology_description,
    safe_cast(capacity_mw as float64) capacity_mw,
    safe_cast(summer_capacity_mw as float64) summer_capacity_mw,
    safe_cast(winter_capacity_mw as float64) winter_capacity_mw,
    safe_cast(minimum_load_mw as float64) minimum_load_mw,
    safe_cast(planned_new_capacity_mw as float64) planned_new_capacity_mw,
    safe_cast(turbines_num as int64) turbines_num,
    safe_cast(
        turbines_inverters_hydrokinetics as int64
    ) turbines_inverters_hydrokinetics,
    safe_cast(energy_source_code_1 as string) energy_source_code_1,
    safe_cast(energy_source_code_2 as string) energy_source_code_2,
    safe_cast(energy_source_code_3 as string) energy_source_code_3,
    safe_cast(energy_source_code_4 as string) energy_source_code_4,
    safe_cast(energy_source_code_5 as string) energy_source_code_5,
    safe_cast(energy_source_code_6 as string) energy_source_code_6,
    safe_cast(can_burn_multiple_fuels as string) can_burn_multiple_fuels,
    safe_cast(can_cofire_fuels as string) can_cofire_fuels,
    safe_cast(switch_oil_gas as string) switch_oil_gas,
    safe_cast(operating_date as date) operating_date,
    safe_cast(retirement_date as date) retirement_date,
    safe_cast(planned_retirement_date as date) planned_retirement_date,
    safe_cast(planned_operating_date as date) planned_operating_date,
    safe_cast(carbon_capture as string) carbon_capture,
    safe_cast(solid_fuel_gasification as string) solid_fuel_gasification,
    safe_cast(pulverized_coal_tech as string) pulverized_coal_tech,
    safe_cast(fluidized_bed_tech as string) fluidized_bed_tech,
    safe_cast(stoker_tech as string) stoker_tech,
    safe_cast(other_combustion_tech as string) other_combustion_tech,
    safe_cast(subcritical_tech as string) subcritical_tech,
    safe_cast(supercritical_tech as string) supercritical_tech,
    safe_cast(ultrasupercritical_tech as string) ultrasupercritical_tech,
    safe_cast(duct_burners as string) duct_burners,
    safe_cast(bypass_heat_recovery as string) bypass_heat_recovery,
    safe_cast(associated_combined_heat_power as string) associated_combined_heat_power,
    safe_cast(topping_bottoming_code as string) topping_bottoming_code,
    safe_cast(synchronized_transmission_grid as string) synchronized_transmission_grid,
    safe_cast(rto_iso_lmp_node_id as string) rto_iso_lmp_node_id,
    safe_cast(data_maturity as string) data_maturity
from {{ set_datalake_project("us_eia_electricity_staging.generator") }} as t
