"""Portuguese descriptions for the MG-only staging columns.

WHY THIS IS A FILE AND NOT PROSE IN `schema.yml`
------------------------------------------------
The 43 MG-only tables publish 629 column slots over 334 distinct names, all of
them derived from SICOM's own `dsc_`/`vlr_`/`dat_`/`num_`/`cod_`/`seq_` prefixes.
TCE-MG publishes no column dictionary for these streams, so every description
here is written from the column name plus the stream it sits in -- it is NOT a
transcription of an official layout document.

Keeping the mapping in one auditable file, rather than scattered across a
generated `schema.yml`, makes that provenance checkable: a reader can see the
whole vocabulary at once and correct it in one place.

TERMS is keyed on the PUBLISHED column name (the dbt alias), not the source
name. `build_description` falls back to the prefix rules for anything absent,
and `unresolved()` lists what fell through so nothing is silently generic.
"""

from __future__ import annotations

# Full descriptions, keyed on the published column name. Anything not here is
# assembled by the prefix rules below.
TERMS: dict[str, str] = {
    # -- partition / geography ------------------------------------------------
    "ano": "Número do ano de referência da informação",
    "mes": "Número do mês de referência da informação",
    "sigla_uf": "Sigla da Unidade da Federação",
    "id_municipio": "ID Município - IBGE 7 Dígitos",
    # -- administrative spine -------------------------------------------------
    "orgao": "Código do órgão atribuído pelo município (cod_orgao na fonte)",
    "id_unidade_gestora": "Código da unidade gestora",
    "codigo_unidade": "Código da unidade orçamentária",
    "codigo_subunidade": "Código da subunidade orçamentária",
    "numero_versao_arq": "Número da versão do arquivo remetido ao SICOM",
    # -- orçamento ------------------------------------------------------------
    "acao": "Descrição da ação orçamentária",
    "subacao": "Descrição da subação orçamentária",
    "funcao": "Descrição da função orçamentária",
    "subfuncao": "Descrição da subfunção orçamentária",
    "programa": "Descrição do programa orçamentário",
    "dotacao": "Descrição da dotação orçamentária",
    "dotacao_ori": "Descrição da dotação orçamentária de origem",
    "nat_despesa": "Descrição da natureza da despesa",
    "naturezadespesa": "Descrição da natureza da despesa",
    "cod_orcamentario": "Código orçamentário da despesa",
    "fonte_recurso": "Descrição da fonte de recursos",
    "fonterecurso": "Descrição da fonte de recursos",
    # -- objeto / processo ----------------------------------------------------
    "objeto": "Descrição do objeto",
    "objetocontrato": "Descrição do objeto do contrato",
    "objeto_adesao": "Descrição do objeto da adesão à ata de registro de preços",
    "naturezaobjeto": "Descrição da natureza do objeto",
    "nat_objeto": "Descrição da natureza do objeto",
    "nat_processo": "Descrição da natureza do processo",
    "tipo_processo": "Descrição do tipo de processo",
    "tipo_cadastro": "Descrição do tipo de cadastro",
    "modalidade": "Descrição da modalidade da licitação",
    "justificativa": "Justificativa registrada pelo órgão",
    "motivo": "Descrição do motivo",
    "razao": "Razão registrada pelo órgão",
    "finalidade_conta": "Descrição da finalidade da conta bancária",
    "alteracao": "Descrição da alteração",
    "documento": "Descrição do documento",
    "tabela": "Identificação da tabela de referência de preços",
    "item": "Descrição do item",
    "lote": "Identificação do lote",
    "unid_medida": "Descrição da unidade de medida do item",
    "unid_med_prazo": "Descrição da unidade de medida do prazo",
    "prazoexecucao": "Prazo de execução previsto",
    "fornecimento": "Descrição da forma de fornecimento",
    "formapagamento": "Descrição da forma de pagamento",
    "garantia": "Descrição da garantia contratual",
    "multarecisoria": "Descrição da multa rescisória",
    "multa_inadimplencia": "Descrição da multa por inadimplência",
    "veiculopublicacao": "Descrição do veículo de publicação",
    "veiculo_pub": "Descrição do veículo de publicação",
    "tipo_instrumento": "Descrição do tipo de instrumento contratual",
    "decorrentelicitacao": "Indica se o contrato decorre de licitação",
    "org_gerenciador": "Órgão gerenciador da ata de registro de preços",
    "inst_financeira": "Instituição financeira",
    "agencia": "Número da agência bancária",
    "conta_bancaria": "Número da conta bancária",
    "cargo": "Descrição do cargo",
    "ato_nomeacao": "Descrição do ato de nomeação",
    "mun_emitente": "Município do emitente do documento fiscal",
    "sigla_uf_credenciado": "Sigla da Unidade da Federação de registro do credenciado",
    "sigla_uf_fornecedor": "Sigla da Unidade da Federação de registro do fornecedor",
    # -- indicadores ----------------------------------------------------------
    "ind_processo_lote": "Indica se o processo é julgado por lote",
    "ind_desonera_folha": "Indica desoneração da folha de pagamento",
    "ind_desc_tab_preco": "Indica desconto sobre tabela de preços",
}

# `<prefix>` -> (template, strips the prefix from the remainder)
PREFIXES: list[tuple[str, str]] = [
    ("id_", "Sequencial identificador {}"),
    ("codigo_", "Código {}"),
    ("numero_", "Número {}"),
    ("nome_", "Nome {}"),
    ("nom_", "Nome {}"),
    ("data_", "Data {}"),
    ("valor_", "Valor {}"),
    ("tipo_", "Descrição do tipo {}"),
    ("ind_", "Indicador {}"),
    ("nat_", "Descrição da natureza {}"),
]

# Expansions for the abbreviated remainders SICOM uses.
PARTS: dict[str, str] = {
    "abertura": "de abertura",
    "credor": "do credor",
    "contrato_apostilamento": "do apostilamento do contrato",
    "contrato_contabilizacao": "da contabilização do contrato",
    "contrato_credito": "do crédito orçamentário do contrato",
    "contrato_item": "do item do contrato",
    "contrato_rescisao": "da rescisão do contrato",
    "contrato_termo_aditivo": "do termo aditivo do contrato",
    "contrato_termo_aditivo_item": "do item do termo aditivo do contrato",
    "dispensa_cotacao": "da cotação da dispensa",
    "dispensa_credenciado": "do credenciado da dispensa",
    "dispensa_dotacao": "da dotação orçamentária da dispensa",
    "dispensa_fornecedor": "do fornecedor da dispensa",
    "dispensa_item": "do item da dispensa",
    "dispensa_responsavel": "do responsável pela dispensa",
    "lei_decreto": "da lei que autoriza o decreto",
    "licitacao_comissao": "do membro da comissão de licitação",
    "licitacao_cotacao": "da cotação do item da licitação",
    "licitacao_dotacao": "da dotação orçamentária da licitação",
    "licitacao_homologacao": "da homologação do item da licitação",
    "licitacao_item": "do item da licitação",
    "licitacao_julgamento": "do julgamento do item da licitação",
    "licitacao_parecer": "do parecer da licitação",
    "licitacao_participante": "do participante da licitação",
    "licitacao_quadro_societario": "do sócio do participante da licitação",
    "licitacao_responsavel": "do responsável pela licitação",
    "liquidacao_fonte": "da fonte de recursos da liquidação",
    "liquidacao_nota_fiscal": "da nota fiscal da liquidação",
    "nota_fiscal_item": "do item da nota fiscal",
    "registro_preco_adesao_cotacao": "da cotação da adesão a registro de preços",
    "registro_preco_adesao_item": "do item da adesão a registro de preços",
    "registro_preco_adesao_vencedor": "do vencedor da adesão a registro de preços",
    "restos_pagar_credor": "do credor dos restos a pagar",
    "restos_pagar_movimentacao": "da movimentação de restos a pagar",
    "restos_pagar_movimentacao_credor": "do credor da movimentação de restos a pagar",
    "restos_pagar_movimentacao_fonte": "da fonte da movimentação de restos a pagar",
    "alteracao_orcamentaria": "da alteração orçamentária",
    "acres_red": "de acréscimo ou redução",
    "acrescimo": "do acréscimo",
    "alien_bens": "de alienação de bens",
    "alt": "de alteração",
    "alteracao": "da alteração",
    "anu_liq_fonte": "de anulação da liquidação por fonte",
    "anu_liquidacao": "de anulação da liquidação",
    "anu_outras_baixas": "de anulação de outras baixas",
    "anu_pagamento": "de anulação do pagamento",
    "anulacao_emp": "de anulação do empenho",
    "ano_contrato": "do ano do contrato",
    "ano_emp_origem": "do ano do empenho de origem",
    "ano_processo": "do ano do processo",
    "ano_referencia": "do ano de referência",
    "aplicacao": "da aplicação",
    "apost": "de apostilamento",
    "apostilamento": "do apostilamento",
    "ass_decreto": "de assinatura do decreto",
    "ass_termo": "de assinatura do termo",
    "assinatura": "de assinatura",
    "ata_reg_preco": "da ata de registro de preços",
    "ato_nomeacao": "do ato de nomeação",
    "atrib": "de atribuição",
    "aut_impressao": "da autorização de impressão",
    "aberto": "em aberto",
    "aberto_lei": "aberto por lei",
    "bruto": "bruto",
    "cep_mun_emitente": "do CEP do município do emitente",
    "cert_fgts": "da certidão do FGTS",
    "cert_negativa": "da certidão negativa",
    "certidao_inss": "da certidão do INSS",
    "cgc_habilitado": "do CNPJ do habilitado",
    "chave_mun_nota_fis": "da chave municipal da nota fiscal",
    "chave_nota_fis": "da chave da nota fiscal",
    "cndt": "da Certidão Negativa de Débitos Trabalhistas",
    "com_licitacao": "da comissão de licitação",
    "comissao": "de comissão",
    "contrato": "do contrato",
    "contratado": "do contratado",
    "cot_dispensa": "da cotação da dispensa",
    "cot_licitacao": "da cotação da licitação",
    "cot_preco_unit": "do preço unitário cotado",
    "cot_reg_adesao": "da cotação da adesão a registro de preços",
    "cotacao": "da cotação",
    "cred_dispensa": "do credenciado da dispensa",
    "cred_mov_rsp": "do credor da movimentação de restos a pagar",
    "credenciado": "do credenciado",
    "credenciamento": "de credenciamento",
    "credito_contrato": "do crédito do contrato",
    "credor_rsp": "do credor de restos a pagar",
    "decreto": "do decreto",
    "decreto_alt": "do decreto de alteração",
    "deducao": "de dedução",
    "desconto": "de desconto",
    "despesa_dotacao": "da dotação de despesa",
    "dispensa": "da dispensa",
    "doc": "do documento",
    "doc_credenciado": "do documento do credenciado",
    "doc_credor": "do documento do credor",
    "doc_emitente": "do documento do emitente",
    "doc_fornecedor": "do documento do fornecedor",
    "doc_licitante": "do documento do licitante",
    "doc_livre": "do documento livre",
    "doc_representante": "do documento do representante",
    "doc_resp": "do documento do responsável",
    "doc_resp_parecer": "do documento do responsável pelo parecer",
    "doc_responsavel": "do documento do responsável",
    "doc_signatario": "do documento do signatário",
    "doc_vencedor": "do documento do vencedor",
    "documento": "do documento",
    "emi_cert_fgts": "de emissão da certidão do FGTS",
    "emi_cert_inss": "de emissão da certidão do INSS",
    "emi_cert_negativa": "de emissão da certidão negativa",
    "emi_cndt": "de emissão da CNDT",
    "emissao": "de emissão",
    "emitente": "do emitente",
    "emp_credor": "do credor do empenho",
    "empenhado": "empenhado",
    "empenho": "do empenho",
    "empenho_credor": "do credor do empenho",
    "empenho_fonte": "da fonte do empenho",
    "empenho_origem": "do empenho de origem",
    "est_credor": "do estado do credor",
    "fim_vigencia": "de fim da vigência",
    "fimvigencia": "de fim da vigência",
    "fornecedor": "do fornecedor",
    "forn_dispensa": "do fornecedor da dispensa",
    "global": "global",
    "hab_licitacao": "do habilitado da licitação",
    "hom_licitacao": "da homologação da licitação",
    "ini_vigencia": "de início da vigência",
    "iniciovigencia": "de início da vigência",
    "inscr_est_emitente": "da inscrição estadual do emitente",
    "inscr_estadual": "da inscrição estadual",
    "inscr_mun_emitente": "da inscrição municipal do emitente",
    "item": "do item",
    "item_contrato": "do item do contrato",
    "item_dispensa": "do item da dispensa",
    "item_licitacao": "do item da licitação",
    "item_nota": "do item da nota fiscal",
    "item_planilha": "do item na planilha",
    "item_reg_adesao": "do item da adesão a registro de preços",
    "item_sicro": "do item na tabela SICRO",
    "item_sinapi": "do item na tabela SINAPI",
    "item_termo": "do item do termo aditivo",
    "julgamento": "do julgamento",
    "lei": "da lei",
    "lei_alt": "da lei de alteração",
    "lei_alteracao": "da lei de alteração",
    "licitacao": "da licitação",
    "licitante": "do licitante",
    "liq_fonte": "da liquidação por fonte",
    "liq_nota_fiscal": "da nota fiscal da liquidação",
    "liquidacao": "da liquidação",
    "liquidado": "liquidado",
    "liquido": "líquido",
    "lote": "do lote",
    "mat_serv": "de material ou serviço",
    "material_serv": "de material ou serviço",
    "mes_referencia": "do mês de referência",
    "min_alien_bens": "mínimo de alienação de bens",
    "modalidade": "da modalidade",
    "mov_fonte": "da movimentação por fonte",
    "mov_pagamento": "da movimentação do pagamento",
    "mov_rsp": "da movimentação de restos a pagar",
    "mov_rsp_fonte": "da fonte da movimentação de restos a pagar",
    "movimentacao": "da movimentação",
    "nao_processado": "não processado",
    "nat_cargo": "da natureza do cargo",
    "nota": "da nota fiscal",
    "nota_fiscal": "da nota fiscal",
    "nomeacao": "de nomeação",
    "novo_termino": "do novo término",
    "origem": "de origem",
    "original": "original",
    "outras_baixas": "de outras baixas",
    "pagamento": "do pagamento",
    "pagamento_movimento": "da movimentação do pagamento",
    "pago": "pago",
    "parecer": "do parecer",
    "parecer_licit": "do parecer da licitação",
    "participacao": "de participação",
    "pct_desconto": "percentual de desconto",
    "pct_tax_adm": "percentual da taxa de administração",
    "perc_desconto": "percentual de desconto",
    "perc_taxa_adm": "percentual da taxa de administração",
    "percentual": "percentual",
    "pessoa": "da pessoa",
    "pessoa_resp": "da pessoa responsável",
    "preco_unit": "unitário",
    "preco_unitario": "unitário",
    "previsto": "previsto",
    "processado": "processado",
    "processo": "do processo",
    "pub_aviso_inst": "de publicação do aviso do instrumento",
    "pub_lei": "de publicação da lei",
    "pub_lei_alt": "de publicação da lei de alteração",
    "pub_termo": "de publicação do termo",
    "publicacao": "de publicação",
    "quadro_soc": "do quadro societário",
    "quant_acres_decres": "da quantidade acrescida ou reduzida",
    "quant_aderido": "da quantidade aderida",
    "quant_item": "da quantidade do item",
    "quant_item_cotado": "da quantidade do item cotado",
    "quant_licitado": "da quantidade licitada",
    "rec_dispensa": "do recurso orçamentário da dispensa",
    "rec_licitacao": "do recurso orçamentário da licitação",
    "recurso": "do recurso orçamentário",
    "reforco_emp": "de reforço do empenho",
    "reg_adesao": "da adesão a registro de preços",
    "registro_preco_adesao": "da adesão a registro de preços",
    "representante": "do representante",
    "rescicao": "de rescisão",
    "rescisao": "da rescisão",
    "rescisao_contrato": "da rescisão do contrato",
    "resp": "do responsável",
    "resp_dispensa": "do responsável pela dispensa",
    "resp_licitacao": "do responsável pela licitação",
    "resp_parecer": "do responsável pelo parecer",
    "responsavel": "do responsável",
    "restos_pagar": "de restos a pagar",
    "rsp": "de restos a pagar",
    "rsp_nao_proc": "de restos a pagar não processados",
    "rsp_nao_processado": "de restos a pagar não processados",
    "rsp_proc": "de restos a pagar processados",
    "rsp_processado": "de restos a pagar processados",
    "rspnprocessado": "de restos a pagar não processados",
    "rspprocessado": "de restos a pagar processados",
    "serie_nota_fiscal": "da série da nota fiscal",
    "signatario": "do signatário",
    "termo": "do termo aditivo",
    "termo_aditivo": "do termo aditivo",
    "unidade_gestora": "da unidade gestora",
    "unitario": "unitário",
    "val_cert_fgts": "de validade da certidão do FGTS",
    "val_cert_inss": "de validade da certidão do INSS",
    "val_cert_negativa": "de validade da certidão negativa",
    "val_cndt": "de validade da CNDT",
    "validade": "de validade",
    "vencedor": "do vencedor",
    "vencimento": "de vencimento",
    "venc_reg_adesao": "do vencedor da adesão a registro de preços",
}

_MISSES: set[str] = set()


def build_description(column: str, table: str) -> str:
    """Return the Portuguese description for one published column."""
    if column in TERMS:
        return TERMS[column]
    if column.endswith("_bd"):
        entity = column[len("id_") : -len("_bd")]
        part = PARTS.get(entity)
        if part is None:
            _MISSES.add(column)
            part = entity.replace("_", " ")
        return (
            f"Código único de identificação {part}, construído por Data Basis"
        )
    for prefix, template in PREFIXES:
        if column.startswith(prefix):
            rest = column[len(prefix) :]
            part = PARTS.get(rest)
            if part is None:
                _MISSES.add(column)
                part = rest.replace("_", " ")
            return template.format(part)
    _MISSES.add(column)
    return column.replace("_", " ").capitalize()


def unresolved() -> list[str]:
    """Columns that fell through to the mechanical fallback."""
    return sorted(_MISSES)
