"""Generate the dbt models for world_noaa_ghcn from the architecture CSVs."""

import csv
from pathlib import Path

DATASET = "world_noaa_ghcn"
ROOT = Path(__file__).resolve().parents[1]
ARCH = Path(__file__).parent / "architecture"

CAST = {
    "STRING": "safe_cast({c} as string) {c}",
    "INT64": "safe_cast({c} as int64) {c}",
    "FLOAT64": "safe_cast({c} as float64) {c}",
    "DATE": "safe_cast({c} as date) {c}",
}

CONFIG = {
    "observation": (
        "        partition_by={\n"
        '            "field": "year",\n'
        '            "data_type": "int64",\n'
        '            "range": {"start": 1950, "end": 2031, "interval": 1},\n'
        "        },\n"
        '        cluster_by=["station_id", "element"],\n'
    ),
}


def main() -> None:
    for path in sorted(ARCH.glob("*.csv")):
        table = path.stem
        with open(path, encoding="utf-8") as fh:
            cols = list(csv.DictReader(fh))
        selects = ",\n".join(
            "    " + CAST[c["bigquery_type"]].format(c=c["name"]) for c in cols
        )
        extra = CONFIG.get(table, "")
        sql = (
            f"-- Generated by models/{DATASET}/code/gen_dbt.py from\n"
            f"-- code/architecture/{table}.csv. Edit the generator, not this file.\n"
            "{{\n"
            "    config(\n"
            f'        schema="{DATASET}",\n'
            f'        alias="{table}",\n'
            '        materialized="table",\n'
            f"{extra}"
            "    )\n"
            "}}\n\n\n"
            "select\n"
            f"{selects}\n"
            f'from {{{{ set_datalake_project("{DATASET}_staging.{table}") }}}} as t\n'
        )
        out = ROOT / f"{DATASET}__{table}.sql"
        out.write_text(sql, encoding="utf-8")
        print(
            f"wrote {out.relative_to(ROOT.parents[1])}  ({len(cols)} columns)"
        )


if __name__ == "__main__":
    main()
