{{
    config(
        schema="us_cms_open_payments",
        alias="research_legacy",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 2013, "end": 2020, "interval": 1},
        },
        cluster_by=["physician_profile_id", "reporting_entity_id"],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(record_id as string) record_id,
    safe_cast(physician_profile_id as string) physician_profile_id,
    safe_cast(physician_npi as string) physician_npi,
    safe_cast(teaching_hospital_ccn as string) teaching_hospital_ccn,
    safe_cast(teaching_hospital_id as string) teaching_hospital_id,
    safe_cast(reporting_entity_id as string) reporting_entity_id,
    safe_cast(change_type as string) change_type,
    safe_cast(covered_recipient_type as string) covered_recipient_type,
    safe_cast(noncovered_recipient_entity_name as string) noncovered_recipient_entity_name,
    safe_cast(teaching_hospital_name as string) teaching_hospital_name,
    safe_cast(physician_first_name as string) physician_first_name,
    safe_cast(physician_middle_name as string) physician_middle_name,
    safe_cast(physician_last_name as string) physician_last_name,
    safe_cast(physician_name_suffix as string) physician_name_suffix,
    safe_cast(recipient_address_line_1 as string) recipient_address_line_1,
    safe_cast(recipient_address_line_2 as string) recipient_address_line_2,
    safe_cast(recipient_city as string) recipient_city,
    safe_cast(recipient_state as string) recipient_state,
    safe_cast(recipient_zip_code as string) recipient_zip_code,
    safe_cast(recipient_country as string) recipient_country,
    safe_cast(recipient_province as string) recipient_province,
    safe_cast(recipient_postal_code as string) recipient_postal_code,
    safe_cast(physician_primary_type as string) physician_primary_type,
    safe_cast(physician_specialty as string) physician_specialty,
    safe_cast(physician_license_state_1 as string) physician_license_state_1,
    safe_cast(physician_license_state_2 as string) physician_license_state_2,
    safe_cast(physician_license_state_3 as string) physician_license_state_3,
    safe_cast(physician_license_state_4 as string) physician_license_state_4,
    safe_cast(physician_license_state_5 as string) physician_license_state_5,
    safe_cast(submitting_entity_name as string) submitting_entity_name,
    safe_cast(reporting_entity_name as string) reporting_entity_name,
    safe_cast(reporting_entity_state as string) reporting_entity_state,
    safe_cast(reporting_entity_country as string) reporting_entity_country,
    safe_cast(related_product_indicator as string) related_product_indicator,
    safe_cast(drug_name_1 as string) drug_name_1,
    safe_cast(drug_name_2 as string) drug_name_2,
    safe_cast(drug_name_3 as string) drug_name_3,
    safe_cast(drug_name_4 as string) drug_name_4,
    safe_cast(drug_name_5 as string) drug_name_5,
    safe_cast(drug_ndc_1 as string) drug_ndc_1,
    safe_cast(drug_ndc_2 as string) drug_ndc_2,
    safe_cast(drug_ndc_3 as string) drug_ndc_3,
    safe_cast(drug_ndc_4 as string) drug_ndc_4,
    safe_cast(drug_ndc_5 as string) drug_ndc_5,
    safe_cast(device_name_1 as string) device_name_1,
    safe_cast(device_name_2 as string) device_name_2,
    safe_cast(device_name_3 as string) device_name_3,
    safe_cast(device_name_4 as string) device_name_4,
    safe_cast(device_name_5 as string) device_name_5,
    safe_cast(payment_amount_total as float64) payment_amount_total,
    safe_cast(payment_date as date) payment_date,
    safe_cast(payment_form as string) payment_form,
    safe_cast(expenditure_category_1 as string) expenditure_category_1,
    safe_cast(expenditure_category_2 as string) expenditure_category_2,
    safe_cast(expenditure_category_3 as string) expenditure_category_3,
    safe_cast(expenditure_category_4 as string) expenditure_category_4,
    safe_cast(expenditure_category_5 as string) expenditure_category_5,
    safe_cast(expenditure_category_6 as string) expenditure_category_6,
    safe_cast(preclinical_research_indicator as string) preclinical_research_indicator,
    safe_cast(delay_in_publication_indicator as string) delay_in_publication_indicator,
    safe_cast(study_name as string) study_name,
    safe_cast(dispute_status as string) dispute_status,
    safe_cast(publication_date as date) publication_date,
    safe_cast(clinicaltrials_gov_id as string) clinicaltrials_gov_id,
    safe_cast(research_information_link as string) research_information_link,
    safe_cast(research_context as string) research_context
from {{ set_datalake_project("us_cms_open_payments_staging.research_legacy") }} as t
