#!/usr/bin/env python3
"""Clean the 15 ABS Labour Force Detailed data cubes into 12 partitioned tables.

Phase 2 of `au_abs_labour_force` (ABS cat. 6291.0.55.001, ceased March 2026).
One-shot onboarding ETL: the release has ceased, so there is no recurring
pipeline and nothing to share with `pipelines/datasets/au_abs_labour_force/`.

Reads the cubes from ``<data-root>/input/<CUBE>.xlsx`` and writes all-STRING
Snappy parquet, hive-partitioned by ``year``, to ``<data-root>/output/<table>/``.
``<data-root>`` defaults to ``~/Downloads/au_abs_labour_force_data`` and is
overridable with ``AU_ABS_LF_DATA``. Data never lands in the repo or in Dropbox.

Column order and types come from ``code/architecture_detailed/*.csv``, the
schema source of truth, generated by ``architecture_detailed.py``.

Every cube's raw row count is asserted against the published shape and every
classification-code map is asserted to cover the observed labels, so a silent
change in the source fails the run instead of producing NULLs.

Usage:
    uv run python models/au_abs_labour_force/code/clean_detailed.py [table ...]
"""

import csv
import json
import logging
import os
import sys
from pathlib import Path

import openpyxl
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

sys.path.insert(0, str(Path(__file__).resolve().parent))
from architecture_detailed import GRAIN, SOURCE_CUBES, TABLES

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("au_abs_labour_force_detailed")

ROOT = Path(__file__).resolve().parents[1]
ARCH = ROOT / "code" / "architecture_detailed"
DATA_ROOT = Path(
    os.environ.get(
        "AU_ABS_LF_DATA",
        Path.home() / "Downloads" / "au_abs_labour_force_data",
    )
).expanduser()
INPUT = DATA_ROOT / "input"
OUTPUT = DATA_ROOT / "output"

PA = {"STRING": pa.string(), "INT64": pa.int64(), "FLOAT64": pa.float64()}

# ── source shape, asserted ───────────────────────────────────────────────────
# Rows on each cube's `Data 1` sheet, header row excluded.
EXPECTED_CUBE_ROWS = {
    "EQ02": 9_408,
    "EQ03": 87_786,
    "EQ04": 19_251,
    "EQ05": 16_625,
    "EQ06": 514_879,
    "EQ07a": 86_762,
    "EQ07b": 7_136,
    "EQ09": 47_795,
    "EQ10": 20_738,
    "EQ11": 20_898,
    "EQ12": 34_667,
    "EQ13": 13_992,
    "EQ14": 9_801,
    "UM2": 20_229,
    "UM3": 14_753,
}

EXPECTED_TABLE_ROWS = {
    t: sum(EXPECTED_CUBE_ROWS[c] for c in cubes)
    for t, cubes in SOURCE_CUBES.items()
}

# ── source header names ──────────────────────────────────────────────────────
H_TIME_Q = "Mid-quarter month"
H_TIME_M = "Month"
H_SEX = "Sex"
H_AGE = "Age"
H_STT = "State and territory (STT): ASGS (2011)"
H_GCCSA = "Greater capital city and rest of state (GCCSA): ASGS (2011)"
H_DIVISION = "Industry division of main job: ANZSIC (2006) Rev.2.0"
H_GROUP = "Industry group of main job: ANZSIC (2006) Rev.2.0"
H_OCC_MAJOR = "Occupation major group of main job: ANZSCO (2013) v1.2"
H_OCC_SUB = "Occupation sub-major group of main job: ANZSCO (2013) v1.2"
H_STATUS = "Status in employment of main job"
H_TENURE = "Number of months or years with current employer or business"
H_DURATION = "Duration of job search"

M_EFT = "Employed full-time ('000)"
M_EPT = "Employed part-time ('000)"
M_UNEMP = "Unemployed total ('000)"
M_WEEKS = "Number of weeks searching for job ('000 Weeks)"
M_ULFT = "Unemployed looked for full-time work ('000)"
M_ULPT = "Unemployed looked for only part-time work ('000)"

THOUSANDS = 1_000

ANZSCO_CLASSIFICATION = "ANZSCO (2013) v1.2"

# ── classification code maps (asserted to cover the observed labels) ─────────
ANZSIC_DIVISION_CODE = {
    "Agriculture, Forestry and Fishing": "A",
    "Mining": "B",
    "Manufacturing": "C",
    "Electricity, Gas, Water and Waste Services": "D",
    "Construction": "E",
    "Wholesale Trade": "F",
    "Retail Trade": "G",
    "Accommodation and Food Services": "H",
    "Transport, Postal and Warehousing": "I",
    "Information Media and Telecommunications": "J",
    "Financial and Insurance Services": "K",
    "Rental, Hiring and Real Estate Services": "L",
    "Professional, Scientific and Technical Services": "M",
    "Administrative and Support Services": "N",
    "Public Administration and Safety": "O",
    "Education and Training": "P",
    "Health Care and Social Assistance": "Q",
    "Arts and Recreation Services": "R",
    "Other Services": "S",
}

# ANZSIC 2006 division -> inclusive subdivision range (the first two digits of a
# group code). Used to roll EQ06's group-level codes up to a division. Verified
# against the cube: all 272 three-digit group codes fall inside these ranges,
# with no orphans.
ANZSIC_DIVISION_SUBDIVISIONS = {
    "A": (1, 5),
    "B": (6, 10),
    "C": (11, 25),
    "D": (26, 29),
    "E": (30, 32),
    "F": (33, 38),
    "G": (39, 43),
    "H": (44, 45),
    "I": (46, 53),
    "J": (54, 60),
    "K": (62, 64),
    "L": (66, 67),
    "M": (69, 70),
    "N": (72, 73),
    "O": (75, 77),
    "P": (80, 82),
    "Q": (84, 87),
    "R": (89, 92),
    "S": (94, 96),
}

ANZSCO_MAJOR_CODE = {
    "Managers": "1",
    "Professionals": "2",
    "Technicians and Trades Workers": "3",
    "Community and Personal Service Workers": "4",
    "Clerical and Administrative Workers": "5",
    "Sales Workers": "6",
    "Machinery Operators and Drivers": "7",
    "Labourers": "8",
}

# The three EQ10/EQ11/EQ14 hours concepts, and their cube-specific zero labels.
HOURS_CUBES = {
    "EQ10": (
        "hours usually worked in all jobs",
        "Hours usually worked in all jobs",
    ),
    "EQ11": (
        "hours actually worked in main job",
        "Hours actually worked in main job",
    ),
    "EQ14": (
        "hours usually worked in main job",
        "Hours usually worked in main job",
    ),
}
ZERO_LABEL = "Did not work (0 hours)"
ZERO_LABEL_VARIANTS = {
    "Did not work (0 hours)",
    "Usually doesn't work (0 hours)",
    "Did not work in main job (0 hours)",
    "Usually doesn't work in main job (0 hours)",
}


def read_arch(table: str) -> list[dict[str, str]]:
    """Architecture rows for one table, in column order."""
    with (ARCH / f"{table}.csv").open() as fh:
        return list(csv.DictReader(fh))


def load_cube(cube: str) -> pd.DataFrame:
    """Read a cube's ``Data 1`` fact sheet into a DataFrame.

    The header is not row 0: three ABS banner rows sit above it. It is located
    by scanning the first eight rows for the one whose first cell is the time
    column, then everything below it whose first cell is a real period is data.
    Trailing all-empty columns and the copyright cell are dropped.
    """
    path = INPUT / f"{cube}.xlsx"
    if not path.exists():
        raise FileNotFoundError(path)
    wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
    if "Data 1" not in wb.sheetnames:
        raise ValueError(f"{cube}: no 'Data 1' sheet (has {wb.sheetnames})")
    ws = wb["Data 1"]
    it = ws.iter_rows(values_only=True)

    header: list[str] | None = None
    for i, row in enumerate(it):
        first = row[0]
        if isinstance(first, str) and first.strip() in (H_TIME_Q, H_TIME_M):
            header = [str(c).strip() for c in row if c is not None]
            break
        if i >= 7:
            break
    if header is None:
        raise ValueError(f"{cube}: header row not found in the first 8 rows")

    ncol = len(header)
    data = [row[:ncol] for row in it if row and _is_period(row[0])]
    wb.close()

    df = pd.DataFrame(data, columns=header)
    n = len(df)
    want = EXPECTED_CUBE_ROWS[cube]
    if n != want:
        raise ValueError(
            f"{cube}: {n:,} data rows on 'Data 1', expected {want:,}"
        )
    log.info(f"{cube}: {n:,} rows, {ncol} columns")
    return df


def _is_period(value: object) -> bool:
    """True for a real reference period cell (drops the copyright footer)."""
    return hasattr(value, "year") and hasattr(value, "month")


def add_time(df: pd.DataFrame, quarterly: bool) -> pd.DataFrame:
    """Split the ABS period column into year, quarter (quarterly only), month."""
    col = H_TIME_Q if quarterly else H_TIME_M
    ts = pd.to_datetime(df[col])
    df = df.drop(columns=[col])
    df.insert(0, "month", ts.dt.month.astype("int64"))
    if quarterly:
        months = set(df["month"].unique())
        if not months <= {2, 5, 8, 11}:
            raise ValueError(
                f"unexpected mid-quarter months: {sorted(months)}"
            )
        df.insert(0, "quarter", ((df["month"] - 1) // 3 + 1).astype("int64"))
    df.insert(0, "year", ts.dt.year.astype("int64"))
    return df


def scale(df: pd.DataFrame, mapping: dict[str, str]) -> pd.DataFrame:
    """Rename the ABS measure columns and convert thousands to absolute units."""
    for src, dst in mapping.items():
        if src not in df.columns:
            raise KeyError(f"measure column missing: {src!r}")
        df[dst] = pd.to_numeric(df[src], errors="coerce") * THOUSANDS
        if dst != src:
            df = df.drop(columns=[src])
    return df


EMP_MEASURE_MAP = {
    M_EFT: "employed_full_time",
    M_EPT: "employed_part_time",
}


def emp_hours_map(df: pd.DataFrame) -> dict[str, str]:
    """Locate the two hours measures, whose names vary by cube."""
    ft = [
        c
        for c in df.columns
        if c.startswith("Number of hours") and "(employed full-time)" in c
    ]
    pt = [
        c
        for c in df.columns
        if c.startswith("Number of hours") and "(employed part-time)" in c
    ]
    if len(ft) != 1 or len(pt) != 1:
        raise ValueError(f"expected one hours column per FT/PT, got {ft} {pt}")
    return {ft[0]: "hours_worked_full_time", pt[0]: "hours_worked_part_time"}


def emp_measures(df: pd.DataFrame) -> pd.DataFrame:
    return scale(df, {**EMP_MEASURE_MAP, **emp_hours_map(df)})


def map_strict(
    series: pd.Series, mapping: dict[str, str], what: str
) -> pd.Series:
    """Map labels to codes, raising on any label the map does not cover."""
    observed = set(series.dropna().unique())
    unmapped = observed - set(mapping)
    if unmapped:
        raise ValueError(
            f"{what}: {len(unmapped)} unmapped label(s): {sorted(unmapped)[:5]}"
        )
    unused = set(mapping) - observed
    if unused:
        log.warning(
            f"{what}: {len(unused)} map entries unused: {sorted(unused)}"
        )
    return series.map(mapping)


def split_group_code(series: pd.Series) -> tuple[pd.Series, pd.Series]:
    """Split ABS's code-prefixed industry group label into code and label.

    Two prefix forms occur, both three characters wide. 272 labels carry a real
    ANZSIC three-digit group code ("011 Nursery and Floriculture Production").
    The other 19 are division-level not-further-defined residuals, which ABS
    codes as the division letter followed by 00 ("A00 Agriculture, Forestry and
    Fishing nfd") — one per ANZSIC division, asserted below.
    """
    m = series.str.extract(r"^(\d{3}|[A-Z]00)\s+(.+)$")
    bad = series[m[0].isna()].unique()
    if len(bad):
        raise ValueError(
            f"industry group labels without a recognised code prefix: "
            f"{sorted(bad)[:5]}"
        )
    letters = {c[0] for c in m[0].dropna().unique() if c[0].isalpha()}
    expected = set(ANZSIC_DIVISION_CODE.values())
    if letters != expected:
        raise ValueError(
            f"nfd residual division letters {sorted(letters)} do not match the "
            f"19 ANZSIC divisions {sorted(expected)}"
        )
    return m[0], m[1]


# ── per-table builders ───────────────────────────────────────────────────────
def division_from_group_code(codes: pd.Series) -> pd.Series:
    """Roll EQ06's group-level codes up to their ANZSIC division letter.

    EQ06 is the only cube that publishes industry at group level, so it is the
    only one without a division column of its own. Every other industry table
    carries ``industry_division_code``/``industry_division``; deriving them here
    keeps the largest table joinable to its siblings and aggregatable to the 19
    divisions.

    The 19 division-level ``nfd`` residuals already carry their letter (``A00``);
    the 272 real group codes are mapped by their subdivision, the first two
    digits. Raises if any code lands outside every range.
    """
    letters = codes.str[0].where(codes.str[0].str.isalpha())
    subdivision = pd.to_numeric(codes.str[:2], errors="coerce")
    for letter, (lo, hi) in ANZSIC_DIVISION_SUBDIVISIONS.items():
        letters = letters.mask(subdivision.between(lo, hi), letter)
    if letters.isna().any():
        orphans = sorted(codes[letters.isna()].unique())[:5]
        raise ValueError(
            f"industry group codes outside every ANZSIC subdivision range: "
            f"{orphans}"
        )
    return letters


def build_employment_industry() -> pd.DataFrame:
    df = add_time(load_cube("EQ06"), quarterly=True)
    df = df.rename(columns={H_STT: "geography"})
    code, label = split_group_code(df[H_GROUP])
    df["industry_group_code"] = code
    df["industry_group"] = label
    df["industry_division_code"] = division_from_group_code(code)
    division_label = {v: k for k, v in ANZSIC_DIVISION_CODE.items()}
    df["industry_division"] = df["industry_division_code"].map(division_label)
    df = df.drop(columns=[H_GROUP])
    df["sex"] = df[H_SEX].str.lower()
    return emp_measures(df.drop(columns=[H_SEX]))


def build_employment_industry_region() -> pd.DataFrame:
    df = add_time(load_cube("EQ03"), quarterly=True)
    df = df.rename(columns={H_GCCSA: "gccsa", H_DIVISION: "industry_division"})
    df["industry_division_code"] = map_strict(
        df["industry_division"], ANZSIC_DIVISION_CODE, "ANZSIC division"
    )
    df["sex"] = df[H_SEX].str.lower()
    return emp_measures(df.drop(columns=[H_SEX]))


def build_employment_industry_age() -> pd.DataFrame:
    df = add_time(load_cube("EQ12"), quarterly=True)
    df = df.rename(
        columns={H_AGE: "age_group", H_DIVISION: "industry_division"}
    )
    df["industry_division_code"] = map_strict(
        df["industry_division"], ANZSIC_DIVISION_CODE, "ANZSIC division"
    )
    return emp_measures(df)


def build_employment_industry_hours() -> pd.DataFrame:
    parts = []
    for cube, (measure, band_header) in HOURS_CUBES.items():
        df = add_time(load_cube(cube), quarterly=True)
        df = df.rename(
            columns={
                band_header: "hours_band",
                H_DIVISION: "industry_division",
            }
        )
        bad = set(df["hours_band"].dropna().unique()) & ZERO_LABEL_VARIANTS
        if not bad:
            raise ValueError(
                f"{cube}: no zero-hours label found among the bands"
            )
        df["hours_band"] = df["hours_band"].replace(
            {v: ZERO_LABEL for v in ZERO_LABEL_VARIANTS}
        )
        df["hours_measure"] = measure
        df["industry_division_code"] = map_strict(
            df["industry_division"],
            ANZSIC_DIVISION_CODE,
            f"{cube} ANZSIC division",
        )
        parts.append(emp_measures(df))
    return pd.concat(parts, ignore_index=True)


def build_employment_industry_status() -> pd.DataFrame:
    df = add_time(load_cube("EQ05"), quarterly=True)
    df = df.rename(columns={H_DIVISION: "industry_division"})
    df["industry_division_code"] = map_strict(
        df["industry_division"], ANZSIC_DIVISION_CODE, "ANZSIC division"
    )
    df["status_in_employment"] = df[H_STATUS].str.lower()
    return emp_measures(df.drop(columns=[H_STATUS]))


def build_employment_industry_occupation() -> pd.DataFrame:
    df = add_time(load_cube("EQ09"), quarterly=True)
    df = df.rename(
        columns={
            H_DIVISION: "industry_division",
            H_OCC_MAJOR: "occupation_major",
        }
    )
    df["industry_division_code"] = map_strict(
        df["industry_division"], ANZSIC_DIVISION_CODE, "ANZSIC division"
    )
    df["occupation_major_code"] = map_strict(
        df["occupation_major"], ANZSCO_MAJOR_CODE, "ANZSCO major group"
    )
    df["occupation_classification"] = ANZSCO_CLASSIFICATION
    df["sex"] = df[H_SEX].str.lower()
    return emp_measures(df.drop(columns=[H_SEX]))


def build_employment_occupation() -> pd.DataFrame:
    df = add_time(load_cube("EQ07a"), quarterly=True)
    df = df.rename(
        columns={H_OCC_SUB: "occupation_sub_major", H_AGE: "age_group"}
    )
    df["occupation_classification"] = ANZSCO_CLASSIFICATION
    df["sex"] = df[H_SEX].str.lower()
    return emp_measures(df.drop(columns=[H_SEX]))


def build_employment_occupation_age() -> pd.DataFrame:
    df = add_time(load_cube("EQ13"), quarterly=True)
    df = df.rename(
        columns={H_OCC_MAJOR: "occupation_major", H_AGE: "age_group"}
    )
    df["occupation_major_code"] = map_strict(
        df["occupation_major"], ANZSCO_MAJOR_CODE, "ANZSCO major group"
    )
    df["occupation_classification"] = ANZSCO_CLASSIFICATION
    return emp_measures(df)


def build_employment_occupation_status() -> pd.DataFrame:
    df = add_time(load_cube("EQ07b"), quarterly=True)
    df = df.rename(columns={H_OCC_MAJOR: "occupation_major"})
    df["occupation_major_code"] = map_strict(
        df["occupation_major"], ANZSCO_MAJOR_CODE, "ANZSCO major group"
    )
    df["occupation_classification"] = ANZSCO_CLASSIFICATION
    df["status_in_employment"] = df[H_STATUS].str.lower()
    return emp_measures(df.drop(columns=[H_STATUS]))


def build_employment_status_hours() -> pd.DataFrame:
    df = add_time(load_cube("EQ04"), quarterly=True)
    df = df.rename(columns={"Hours actually worked in all jobs": "hours_band"})
    df["status_in_employment"] = df[H_STATUS].str.lower()
    df["sex"] = df[H_SEX].str.lower()
    return emp_measures(df.drop(columns=[H_STATUS, H_SEX]))


def build_employment_job_tenure() -> pd.DataFrame:
    df = add_time(load_cube("EQ02"), quarterly=True)
    df = df.rename(columns={H_STT: "geography", H_TENURE: "tenure_band"})
    df["sex"] = df[H_SEX].str.lower()
    return emp_measures(df.drop(columns=[H_SEX]))


def build_unemployment_duration() -> pd.DataFrame:
    """UM2 (state, no age) + UM3 (national, by age), merged on a total sentinel.

    The house pattern already used by the sibling `labour_force_status`, which
    merges the state cube with the by-age national cube the same way.
    """
    measures = {
        M_UNEMP: "unemployed_total",
        M_ULFT: "unemployed_looked_for_full_time",
        M_ULPT: "unemployed_looked_for_part_time",
        M_WEEKS: "weeks_searching",
    }

    um2 = add_time(load_cube("UM2"), quarterly=False)
    um2 = um2.rename(columns={H_STT: "geography", H_DURATION: "duration_band"})
    um2["age_group"] = "total"
    um2 = scale(um2, measures)

    um3 = add_time(load_cube("UM3"), quarterly=False)
    um3 = um3.rename(columns={H_AGE: "age_group", H_DURATION: "duration_band"})
    um3["geography"] = "Australia"
    um3 = scale(um3, measures)

    return pd.concat([um2, um3], ignore_index=True)


BUILDERS = {
    "employment_industry": build_employment_industry,
    "employment_industry_region": build_employment_industry_region,
    "employment_industry_age": build_employment_industry_age,
    "employment_industry_hours": build_employment_industry_hours,
    "employment_industry_status": build_employment_industry_status,
    "employment_industry_occupation": build_employment_industry_occupation,
    "employment_occupation": build_employment_occupation,
    "employment_occupation_age": build_employment_occupation_age,
    "employment_occupation_status": build_employment_occupation_status,
    "employment_status_hours": build_employment_status_hours,
    "employment_job_tenure": build_employment_job_tenure,
    "unemployment_duration": build_unemployment_duration,
}


def validate(table: str, df: pd.DataFrame) -> dict[str, float]:
    """Check shape, grain uniqueness and key nullability; measure sparsity."""
    arch = read_arch(table)
    order = [a["name"] for a in arch]
    missing = [c for c in order if c not in df.columns]
    extra = [c for c in df.columns if c not in order]
    if missing or extra:
        raise ValueError(f"{table}: missing={missing} extra={extra}")

    want = EXPECTED_TABLE_ROWS[table]
    if len(df) != want:
        raise ValueError(f"{table}: {len(df):,} rows, expected {want:,}")

    dup = df.duplicated(subset=GRAIN[table]).sum()
    if dup:
        raise ValueError(
            f"{table}: {dup:,} duplicate rows on grain {GRAIN[table]}"
        )

    for col in GRAIN[table]:
        n_null = int(df[col].isna().sum())
        if n_null:
            raise ValueError(
                f"{table}.{col}: {n_null:,} NULLs in a grain column"
            )

    frac = {c: round(float(df[c].notna().mean()), 4) for c in order}
    sparse = {c: v for c, v in frac.items() if v < 0.10}
    log.info(
        f"{table}: {len(df):,} rows OK; "
        f"sparse columns (<10% non-null): {sparse or 'none'}"
    )
    return frac


def write_partitioned(df: pd.DataFrame, table: str, output_dir: Path) -> Path:
    """Write a table as all-STRING Snappy parquet, hive-partitioned by year.

    Staging is all-STRING by Data Basis convention (`gcs.py::dump_header`
    stringifies the header BigQuery infers the staging schema from). Values pass
    through the architecture's real types first — so year serialises as "1984"
    not "1984.0" — then cast to string via arrow, never astype(str), which
    renders NULL as the literal "nan" and defeats the dbt safe_cast.
    """
    arch = read_arch(table)
    order = [a["name"] for a in arch]
    typed = pa.schema(
        [pa.field(a["name"], PA[a["bigquery_type"]]) for a in arch]
    )
    string_schema = pa.schema([pa.field(a["name"], pa.string()) for a in arch])
    out = df[order].copy()
    tdir = output_dir / table
    total = 0
    for year, g in out.groupby("year", sort=True):
        pdir = tdir / f"year={int(year)}"
        pdir.mkdir(parents=True, exist_ok=True)
        at = pa.Table.from_pandas(g, schema=typed, preserve_index=False)
        at = at.cast(string_schema)
        pq.write_table(at, pdir / "data.parquet", compression="snappy")
        total += len(g)
    log.info(f"{table}: {total:,} rows -> {tdir}")
    return tdir


def main() -> None:
    want = [t for t in TABLES if not sys.argv[1:] or t in set(sys.argv[1:])]
    unknown = set(sys.argv[1:]) - set(TABLES)
    if unknown:
        raise SystemExit(f"unknown table(s): {sorted(unknown)}")

    measured_path = ROOT / "code" / "detailed_measured.json"
    measured = (
        json.loads(measured_path.read_text()) if measured_path.exists() else {}
    )
    totals = {}
    for table in want:
        log.info(f"=== {table} ===")
        df = BUILDERS[table]()
        measured[table] = validate(table, df)
        write_partitioned(df, table, OUTPUT)
        totals[table] = len(df)
        del df

    measured_path.write_text(
        json.dumps(measured, indent=2, sort_keys=True) + "\n"
    )
    log.info(f"wrote {measured_path}")
    log.info(
        f"TOTAL {sum(totals.values()):,} rows across {len(totals)} table(s)"
    )


if __name__ == "__main__":
    main()
