"""Column spec (source of truth) for us_irs_form990 -> architecture CSVs + JSON.

One spec, two outputs:
  * ``code/architecture/<table>.csv`` — the BD architecture table (column
    order, BigQuery type, PT description, dictionary/directory flags, unit,
    original name). The cleaning transform and the dbt generator read column
    ORDER and TYPE from these files.
  * ``code/columns_json/<table>.json`` — trilingual column definitions used at
    metadata registration (``bulk_upsert_columns``).

Every column is written as ``(name, type, en, pt, es, opts)`` where ``opts``
may carry ``dict`` (covered_by_dictionary), ``dir`` (directory FK), ``unit``
(measurement unit), ``obs`` (English observation, translated below) and
``orig`` (source field / concordance variable).
"""

import csv
import json
from pathlib import Path

HERE = Path(__file__).parent
ARCH_DIR = HERE / "architecture"
JSON_DIR = HERE / "columns_json"

ARCH_HEADER = [
    "name",
    "bigquery_type",
    "description",
    "temporal_coverage",
    "covered_by_dictionary",
    "directory_column",
    "measurement_unit",
    "has_sensitive_data",
    "observations",
    "original_name",
]

# The backend's dataset slug for the US directory is `diretorios_us`, not the
# GCP dataset id `br_bd_diretorios_us`; with the latter the FK silently
# resolves to null (three `state` directory tables exist: us, au, de).
# State columns carry USPS abbreviations ("CA"). The US state directory's
# primary key is `id_state`, the FIPS code ("06"), and the backend accepts a
# directory link only to a column flagged as that table's primary key — so an
# abbreviation-keyed link cannot be expressed there and these columns carry no
# `directory_column`. The referential check lives in dbt instead, against the
# directory's `abbreviation` column (see build_dbt.STATE_COLUMNS).
DIR_YEAR = "diretorios_data_tempo.ano:ano"
USD = "USD"

# Observations: written once in English, translated here so every column
# ships notes in all three languages.
OBS = {
    "Partition column; the return's tax year (TaxYr in the return header)": (
        "Coluna de partição; ano fiscal da declaração (TaxYr no cabeçalho)",
        "Columna de partición; año fiscal de la declaración (TaxYr en el encabezado)",
    ),
    "Partition column; posting date of the monthly extract, read from the file's Last-Modified header": (
        "Coluna de partição; data de publicação do extrato mensal, lida do cabeçalho Last-Modified do arquivo",
        "Columna de partición; fecha de publicación del extracto mensual, leída del encabezado Last-Modified del archivo",
    ),
    "Only 990 and 990-EZ are loaded; 990-PF and 990-T are outside the concordance": (
        "Apenas 990 e 990-EZ são carregados; 990-PF e 990-T estão fora da concordância",
        "Solo se cargan 990 y 990-EZ; 990-PF y 990-T están fuera de la concordancia",
    ),
    "18-digit IRS object id, also the XML file name; unique per filing": (
        "Identificador de objeto do IRS com 18 dígitos, também o nome do arquivo XML; único por declaração",
        "Identificador de objeto del IRS de 18 dígitos, también el nombre del archivo XML; único por declaración",
    ),
    "IRS e-file schema version (e.g. 2024v5.2); element names change between versions and are reconciled by the concordance": (
        "Versão do esquema e-file do IRS (ex.: 2024v5.2); os nomes dos elementos mudam entre versões e são conciliados pela concordância",
        "Versión del esquema e-file del IRS (p. ej. 2024v5.2); los nombres de los elementos cambian entre versiones y se concilian mediante la concordancia",
    ),
    "Name of the IRS ZIP the return was released in; matches XML_BATCH_ID in the IRS index files": (
        "Nome do ZIP do IRS em que a declaração foi divulgada; corresponde a XML_BATCH_ID nos índices do IRS",
        "Nombre del ZIP del IRS en que se publicó la declaración; coincide con XML_BATCH_ID en los índices del IRS",
    ),
    "Checkbox; false when the box is absent from the XML": (
        "Caixa de seleção; false quando a caixa não consta do XML",
        "Casilla; false cuando la casilla no aparece en el XML",
    ),
    "Business name lines 1 and 2 of the filer, joined with a space": (
        "Linhas 1 e 2 do nome do declarante, unidas por espaço",
        "Líneas 1 y 2 del nombre del declarante, unidas por un espacio",
    ),
    "Form 990 only": (
        "Apenas Form 990",
        "Solo Form 990",
    ),
    "US state or, for foreign addresses, the province/state name": (
        "Estado dos EUA ou, para endereços no exterior, o nome da província/estado",
        "Estado de EE. UU. o, para direcciones en el extranjero, el nombre de la provincia/estado",
    ),
    "Filled only for foreign addresses": (
        "Preenchido apenas para endereços no exterior",
        "Solo se completa para direcciones en el extranjero",
    ),
    "Derived from the four type-of-organization checkboxes: corporation, trust, association, other": (
        "Derivado das quatro caixas de tipo de organização: corporation, trust, association, other",
        "Derivado de las cuatro casillas de tipo de organización: corporation, trust, association, other",
    ),
    "Derived from the exempt-status checkboxes: 501(c)(3), 501(c), 4947(a)(1), 527": (
        "Derivado das caixas de status de isenção: 501(c)(3), 501(c), 4947(a)(1), 527",
        "Derivado de las casillas de estado de exención: 501(c)(3), 501(c), 4947(a)(1), 527",
    ),
    "Part I line 1 (Form 990) or the primary exempt purpose (990-EZ)": (
        "Parte I linha 1 (Form 990) ou a finalidade isenta principal (990-EZ)",
        "Parte I línea 1 (Form 990) o el propósito exento principal (990-EZ)",
    ),
    "Form 990 Part I line 8 or 990-EZ Part I line 1": (
        "Form 990 Parte I linha 8 ou 990-EZ Parte I linha 1",
        "Form 990 Parte I línea 8 o 990-EZ Parte I línea 1",
    ),
    "Form 990 Part I; on 990-EZ the Part II balance-sheet total": (
        "Form 990 Parte I; no 990-EZ o total do balanço da Parte II",
        "Form 990 Parte I; en el 990-EZ el total del balance de la Parte II",
    ),
    "Prior-year column of Form 990 Part I; null on 990-EZ, which reports the current year only": (
        "Coluna do ano anterior da Parte I do Form 990; nulo no 990-EZ, que informa apenas o ano corrente",
        "Columna del año anterior de la Parte I del Form 990; nulo en el 990-EZ, que solo informa el año corriente",
    ),
    "Sequence of the person within the return's listing, starting at 1": (
        "Sequência da pessoa na listagem da declaração, a partir de 1",
        "Secuencia de la persona en el listado de la declaración, a partir de 1",
    ),
    "Position checkboxes exist on Form 990 Part VII only; null on 990-EZ": (
        "As caixas de cargo existem apenas na Parte VII do Form 990; nulo no 990-EZ",
        "Las casillas de cargo existen solo en la Parte VII del Form 990; nulo en el 990-EZ",
    ),
    "Form 990 column D; 990-EZ Part IV column (c)": (
        "Form 990 coluna D; 990-EZ Parte IV coluna (c)",
        "Form 990 columna D; 990-EZ Parte IV columna (c)",
    ),
    "Form 990 column F; on 990-EZ the expense account and other allowances column (e)": (
        "Form 990 coluna F; no 990-EZ a coluna (e) de conta de despesas e outros abonos",
        "Form 990 columna F; en el 990-EZ la columna (e) de cuenta de gastos y otras asignaciones",
    ),
    "990-EZ Part IV column (d) only": (
        "Apenas 990-EZ Parte IV coluna (d)",
        "Solo 990-EZ Parte IV columna (d)",
    ),
    "Trade name, chapter name or local number (SORT_NAME)": (
        "Nome fantasia, nome do capítulo ou número local (SORT_NAME)",
        "Nombre comercial, nombre del capítulo o número local (SORT_NAME)",
    ),
    "Filing-address state; outside the US state directory for international records (eo_xx)": (
        "Estado do endereço de declaração; fora do diretório de estados dos EUA para registros internacionais (eo_xx)",
        "Estado de la dirección de declaración; fuera del directorio de estados de EE. UU. para registros internacionales (eo_xx)",
    ),
    "Four-digit group exemption number; 0000 when none": (
        "Número de isenção de grupo com quatro dígitos; 0000 quando não há",
        "Número de exención de grupo de cuatro dígitos; 0000 cuando no hay",
    ),
    "Subsection of IRC 501(c) (or 40=501(d), 50=501(e), 60=501(f), 70=501(k), 71, 81, 92=4947(a)(1)); see the dictionary": (
        "Subseção do IRC 501(c) (ou 40=501(d), 50=501(e), 60=501(f), 70=501(k), 71, 81, 92=4947(a)(1)); ver dicionário",
        "Subsección del IRC 501(c) (o 40=501(d), 50=501(e), 60=501(f), 70=501(k), 71, 81, 92=4947(a)(1)); ver diccionario",
    ),
    "Up to four one-digit classification codes concatenated; meaning depends on the subsection (dictionary key is subsection+classification)": (
        "Até quatro códigos de classificação de um dígito concatenados; o significado depende da subseção (chave do dicionário é subseção+classificação)",
        "Hasta cuatro códigos de clasificación de un dígito concatenados; el significado depende de la subsección (la clave del diccionario es subsección+clasificación)",
    ),
    "Month and year of the determination letter, stored as the first day of that month; null when the source has 000000": (
        "Mês e ano da carta de determinação, armazenados como o primeiro dia do mês; nulo quando a fonte traz 000000",
        "Mes y año de la carta de determinación, almacenados como el primer día del mes; nulo cuando la fuente trae 000000",
    ),
    "Up to three obsolete three-digit activity codes concatenated (pre-1995 determinations); 000000000 when none": (
        "Até três códigos de atividade obsoletos de três dígitos concatenados (determinações anteriores a 1995); 000000000 quando não há",
        "Hasta tres códigos de actividad obsoletos de tres dígitos concatenados (determinaciones anteriores a 1995); 000000000 cuando no hay",
    ),
    "NTEE-CC code assigned by the IRS; the dictionary covers the three-character code, a fourth character (when present) is an IRS suffix": (
        "Código NTEE-CC atribuído pelo IRS; o dicionário cobre o código de três caracteres, o quarto caractere (quando presente) é um sufixo do IRS",
        "Código NTEE-CC asignado por el IRS; el diccionario cubre el código de tres caracteres, el cuarto carácter (cuando existe) es un sufijo del IRS",
    ),
    "Tax period of the latest return filed, as YYYYMM": (
        "Período fiscal da última declaração apresentada, no formato YYYYMM",
        "Período fiscal de la última declaración presentada, en formato YYYYMM",
    ),
    "Fiscal year-end month (MM)": (
        "Mês de encerramento do exercício (MM)",
        "Mes de cierre del ejercicio (MM)",
    ),
    "From the most recent Form 990-series return; null when the organization has not filed": (
        "Da declaração mais recente da série 990; nulo quando a organização não apresentou declaração",
        "De la declaración más reciente de la serie 990; nulo cuando la organización no ha presentado declaración",
    ),
    "Computer-generated by the IRS from the latest return; adds back expense items netted in total revenue": (
        "Gerado pelo IRS a partir da última declaração; soma de volta itens de despesa líquidos na receita total",
        "Generado por el IRS a partir de la última declaración; suma de vuelta partidas de gasto netas en el ingreso total",
    ),
    "IRC subsection under which the organization was exempt (same code list as the BMF subsection_code)": (
        "Subseção do IRC sob a qual a organização era isenta (mesma lista de códigos de subsection_code do BMF)",
        "Subsección del IRC bajo la cual la organización estaba exenta (misma lista de códigos que subsection_code del BMF)",
    ),
    "Effective date of the automatic revocation": (
        "Data de vigência da revogação automática",
        "Fecha de vigencia de la revocación automática",
    ),
    "Date the revocation was posted on irs.gov": (
        "Data em que a revogação foi publicada em irs.gov",
        "Fecha en que la revocación se publicó en irs.gov",
    ),
    "Null unless exemption was later reinstated": (
        "Nulo a menos que a isenção tenha sido restabelecida posteriormente",
        "Nulo salvo que la exención haya sido restablecida posteriormente",
    ),
    "Reported hours; the IRS schema stores them as a decimal string": (
        "Horas informadas; o esquema do IRS as armazena como texto decimal",
        "Horas informadas; el esquema del IRS las almacena como texto decimal",
    ),
}

# --------------------------------------------------------------------------
# tables
# --------------------------------------------------------------------------

_B = "BOOLEAN"
_S = "STRING"
_F = "FLOAT64"
_I = "INT64"
_D = "DATE"


def c(name, typ, en, pt, es, **opts):
    return {"name": name, "type": typ, "en": en, "pt": pt, "es": es, **opts}


RETURN_FINANCIAL = [
    c(
        "year",
        _I,
        "Tax year of the return",
        "Ano fiscal da declaração",
        "Año fiscal de la declaración",
        dir=DIR_YEAR,
        obs="Partition column; the return's tax year (TaxYr in the return header)",
        orig="F9_00_TAX_YEAR",
    ),
    c(
        "ein",
        _S,
        "Employer Identification Number of the filing organization (nine digits)",
        "Número de Identificação de Empregador (EIN) da organização declarante (nove dígitos)",
        "Número de Identificación de Empleador (EIN) de la organización declarante (nueve dígitos)",
        orig="F9_00_ORG_EIN",
    ),
    c(
        "form_type",
        _S,
        "Return form filed: 990 or 990EZ",
        "Formulário apresentado: 990 ou 990EZ",
        "Formulario presentado: 990 o 990EZ",
        dict=True,
        obs="Only 990 and 990-EZ are loaded; 990-PF and 990-T are outside the concordance",
        orig="F9_00_RETURN_TYPE",
    ),
    c(
        "object_id",
        _S,
        "IRS object identifier of the filing",
        "Identificador de objeto da declaração no IRS",
        "Identificador de objeto de la declaración en el IRS",
        obs="18-digit IRS object id, also the XML file name; unique per filing",
        orig="(file name)",
    ),
    c(
        "return_version",
        _S,
        "IRS e-file XML schema version of the return",
        "Versão do esquema XML e-file do IRS da declaração",
        "Versión del esquema XML e-file del IRS de la declaración",
        obs="IRS e-file schema version (e.g. 2024v5.2); element names change between versions and are reconciled by the concordance",
        orig="@returnVersion",
    ),
    c(
        "xml_batch_id",
        _S,
        "IRS release batch (ZIP file) the return was published in",
        "Lote de divulgação do IRS (arquivo ZIP) em que a declaração foi publicada",
        "Lote de publicación del IRS (archivo ZIP) en que se publicó la declaración",
        obs="Name of the IRS ZIP the return was released in; matches XML_BATCH_ID in the IRS index files",
        orig="(ZIP name)",
    ),
    c(
        "return_timestamp",
        "TIMESTAMP",
        "Timestamp the return was electronically filed",
        "Data e hora do envio eletrônico da declaração",
        "Fecha y hora del envío electrónico de la declaración",
        orig="F9_00_RETURN_TIME_STAMP",
    ),
    c(
        "tax_period_begin",
        _D,
        "First day of the tax period covered",
        "Primeiro dia do período fiscal coberto",
        "Primer día del período fiscal cubierto",
        orig="F9_00_TAX_PERIOD_BEGIN_DATE",
    ),
    c(
        "tax_period_end",
        _D,
        "Last day of the tax period covered",
        "Último dia do período fiscal coberto",
        "Último día del período fiscal cubierto",
        orig="F9_00_TAX_PERIOD_END_DATE",
    ),
    c(
        "is_amended",
        _B,
        "Whether the return is an amended return",
        "Se a declaração é retificadora",
        "Si la declaración es rectificativa",
        obs="Checkbox; false when the box is absent from the XML",
        orig="F9_00_RETURN_AMENDED_X",
    ),
    c(
        "is_initial",
        _B,
        "Whether this is the organization's initial return",
        "Se é a primeira declaração da organização",
        "Si es la primera declaración de la organización",
        obs="Checkbox; false when the box is absent from the XML",
        orig="F9_00_RETURN_INITIAL_X",
    ),
    c(
        "is_final",
        _B,
        "Whether this is a final return (organization terminated)",
        "Se é a declaração final (organização encerrada)",
        "Si es la declaración final (organización cerrada)",
        obs="Checkbox; false when the box is absent from the XML",
        orig="F9_00_RETURN_FINAL_X",
    ),
    c(
        "is_group_return",
        _B,
        "Whether the return is a group return for affiliates",
        "Se a declaração é um retorno de grupo para afiliadas",
        "Si la declaración es un retorno de grupo para afiliadas",
        obs="Checkbox; false when the box is absent from the XML",
        orig="F9_00_RETURN_GROUP_X",
    ),
    c(
        "organization_name",
        _S,
        "Name of the filing organization",
        "Nome da organização declarante",
        "Nombre de la organización declarante",
        obs="Business name lines 1 and 2 of the filer, joined with a space",
        orig="F9_00_ORG_NAME_L1 + F9_00_ORG_NAME_L2",
    ),
    c(
        "doing_business_as_name",
        _S,
        "Name the organization does business as",
        "Nome fantasia da organização",
        "Nombre comercial de la organización",
        obs="Form 990 only",
        orig="F9_00_ORG_NAME_DBA_L1",
    ),
    c(
        "principal_officer_name",
        _S,
        "Name of the principal officer",
        "Nome do dirigente principal",
        "Nombre del directivo principal",
        obs="Form 990 only",
        orig="F9_00_PRIN_OFF_NAME_PERS",
    ),
    c(
        "address_line_1",
        _S,
        "Street address of the organization",
        "Logradouro do endereço da organização",
        "Dirección de la organización",
        orig="F9_00_ORG_ADDR_L1",
    ),
    c(
        "city",
        _S,
        "City of the organization's address",
        "Cidade do endereço da organização",
        "Ciudad de la dirección de la organización",
        orig="F9_00_ORG_ADDR_CITY",
    ),
    c(
        "state",
        _S,
        "State of the organization's address (USPS abbreviation)",
        "Estado do endereço da organização (sigla USPS)",
        "Estado de la dirección de la organización (sigla USPS)",
        obs="US state or, for foreign addresses, the province/state name",
        orig="F9_00_ORG_ADDR_STATE",
    ),
    c(
        "zip_code",
        _S,
        "ZIP or foreign postal code",
        "CEP (ZIP) ou código postal estrangeiro",
        "Código postal (ZIP) o extranjero",
        orig="F9_00_ORG_ADDR_ZIP",
    ),
    c(
        "country",
        _S,
        "Country code of a foreign address",
        "Código do país de um endereço no exterior",
        "Código del país de una dirección en el extranjero",
        obs="Filled only for foreign addresses",
        orig="F9_00_ORG_ADDR_CNTR",
    ),
    c(
        "website",
        _S,
        "Website of the organization",
        "Site da organização",
        "Sitio web de la organización",
        orig="F9_00_ORG_WEBSITE",
    ),
    c(
        "formation_year",
        _I,
        "Year the organization was formed",
        "Ano de constituição da organização",
        "Año de constitución de la organización",
        unit="year",
        obs="Form 990 only",
        orig="F9_00_YEAR_FORMATION",
    ),
    c(
        "legal_domicile_state",
        _S,
        "State of legal domicile",
        "Estado de domicílio legal",
        "Estado de domicilio legal",
        obs="Form 990 only",
        orig="F9_00_LEGAL_DMCL_STATE",
    ),
    c(
        "organization_type",
        _S,
        "Legal form: corporation, trust, association or other",
        "Forma jurídica: corporation, trust, association ou other",
        "Forma jurídica: corporation, trust, association u other",
        obs="Derived from the four type-of-organization checkboxes: corporation, trust, association, other",
        orig="F9_00_TYPE_ORG_*_X",
    ),
    c(
        "exempt_status",
        _S,
        "Exempt status claimed: 501(c)(3), 501(c), 4947(a)(1) or 527",
        "Status de isenção declarado: 501(c)(3), 501(c), 4947(a)(1) ou 527",
        "Estado de exención declarado: 501(c)(3), 501(c), 4947(a)(1) o 527",
        obs="Derived from the exempt-status checkboxes: 501(c)(3), 501(c), 4947(a)(1), 527",
        orig="F9_00_EXEMPT_STAT_*_X",
    ),
    c(
        "group_exemption_number",
        _S,
        "Group exemption number",
        "Número de isenção de grupo",
        "Número de exención de grupo",
        orig="F9_00_GROUP_EXEMPT_NUM",
    ),
    c(
        "mission_description",
        _S,
        "Mission or most significant activities",
        "Missão ou atividades mais significativas",
        "Misión o actividades más significativas",
        obs="Part I line 1 (Form 990) or the primary exempt purpose (990-EZ)",
        orig="F9_01_ACT_GVRN_ACT_MISSION / F9_03_ORG_MISSION_PURPOSE",
    ),
    c(
        "gross_receipts",
        _F,
        "Gross receipts",
        "Receitas brutas",
        "Ingresos brutos",
        unit=USD,
        orig="F9_00_GRO_RCPT",
    ),
    c(
        "voting_members_count",
        _I,
        "Number of voting members of the governing body",
        "Número de membros votantes do órgão de governança",
        "Número de miembros votantes del órgano de gobierno",
        unit="person",
        obs="Form 990 only",
        orig="F9_01_ACT_GVRN_NUM_VOTE_MEMB",
    ),
    c(
        "independent_voting_members_count",
        _I,
        "Number of independent voting members of the governing body",
        "Número de membros votantes independentes do órgão de governança",
        "Número de miembros votantes independientes del órgano de gobierno",
        unit="person",
        obs="Form 990 only",
        orig="F9_01_ACT_GVRN_NUM_VOTE_MEMB_IND",
    ),
    c(
        "employees_count",
        _I,
        "Total number of employees",
        "Número total de empregados",
        "Número total de empleados",
        unit="person",
        obs="Form 990 only",
        orig="F9_01_ACT_GVRN_EMPL_TOT",
    ),
    c(
        "volunteers_count",
        _I,
        "Total number of volunteers (estimate)",
        "Número total de voluntários (estimativa)",
        "Número total de voluntarios (estimación)",
        unit="person",
        obs="Form 990 only",
        orig="F9_01_ACT_GVRN_VOL_TOT",
    ),
    c(
        "unrelated_business_revenue",
        _F,
        "Total unrelated business revenue",
        "Receita total de negócios não relacionados",
        "Ingreso total por negocios no relacionados",
        unit=USD,
        obs="Form 990 only",
        orig="F9_01_ACT_GVRN_UBIZ_REV_TOT",
    ),
    c(
        "unrelated_business_taxable_income",
        _F,
        "Net unrelated business taxable income",
        "Renda tributável líquida de negócios não relacionados",
        "Renta imponible neta por negocios no relacionados",
        unit=USD,
        obs="Form 990 only",
        orig="F9_01_ACT_GVRN_UBIZ_TAXABLE_NET",
    ),
    c(
        "contributions_grants",
        _F,
        "Contributions, gifts and grants received",
        "Contribuições, doações e subvenções recebidas",
        "Contribuciones, donaciones y subvenciones recibidas",
        unit=USD,
        obs="Form 990 Part I line 8 or 990-EZ Part I line 1",
        orig="F9_01_REV_CONTR_TOT_CY / _V2",
    ),
    c(
        "contributions_grants_prior_year",
        _F,
        "Contributions, gifts and grants received, prior year",
        "Contribuições, doações e subvenções recebidas, ano anterior",
        "Contribuciones, donaciones y subvenciones recibidas, año anterior",
        unit=USD,
        obs="Prior-year column of Form 990 Part I; null on 990-EZ, which reports the current year only",
        orig="F9_01_REV_CONTR_TOT_PY",
    ),
    c(
        "program_service_revenue",
        _F,
        "Program service revenue",
        "Receita de serviços de programa",
        "Ingresos por servicios de programa",
        unit=USD,
        orig="F9_01_REV_PROG_TOT_CY",
    ),
    c(
        "program_service_revenue_prior_year",
        _F,
        "Program service revenue, prior year",
        "Receita de serviços de programa, ano anterior",
        "Ingresos por servicios de programa, año anterior",
        unit=USD,
        obs="Prior-year column of Form 990 Part I; null on 990-EZ, which reports the current year only",
        orig="F9_01_REV_PROG_TOT_PY",
    ),
    c(
        "investment_income",
        _F,
        "Investment income",
        "Receita de investimentos",
        "Ingresos por inversiones",
        unit=USD,
        obs="Form 990 only",
        orig="F9_01_REV_INVEST_TOT_CY",
    ),
    c(
        "investment_income_prior_year",
        _F,
        "Investment income, prior year",
        "Receita de investimentos, ano anterior",
        "Ingresos por inversiones, año anterior",
        unit=USD,
        obs="Prior-year column of Form 990 Part I; null on 990-EZ, which reports the current year only",
        orig="F9_01_REV_INVEST_TOT_PY",
    ),
    c(
        "other_revenue",
        _F,
        "Other revenue",
        "Outras receitas",
        "Otros ingresos",
        unit=USD,
        obs="Form 990 only",
        orig="F9_01_REV_OTH_CY",
    ),
    c(
        "other_revenue_prior_year",
        _F,
        "Other revenue, prior year",
        "Outras receitas, ano anterior",
        "Otros ingresos, año anterior",
        unit=USD,
        obs="Prior-year column of Form 990 Part I; null on 990-EZ, which reports the current year only",
        orig="F9_01_REV_OTH_PY",
    ),
    c(
        "total_revenue",
        _F,
        "Total revenue",
        "Receita total",
        "Ingreso total",
        unit=USD,
        orig="F9_01_REV_TOT_CY",
    ),
    c(
        "total_revenue_prior_year",
        _F,
        "Total revenue, prior year",
        "Receita total, ano anterior",
        "Ingreso total, año anterior",
        unit=USD,
        obs="Prior-year column of Form 990 Part I; null on 990-EZ, which reports the current year only",
        orig="F9_01_REV_TOT_PY",
    ),
    c(
        "grants_paid",
        _F,
        "Grants and similar amounts paid",
        "Subvenções e valores similares pagos",
        "Subvenciones y montos similares pagados",
        unit=USD,
        orig="F9_01_EXP_GRANT_SIMILAR_CY",
    ),
    c(
        "grants_paid_prior_year",
        _F,
        "Grants and similar amounts paid, prior year",
        "Subvenções e valores similares pagos, ano anterior",
        "Subvenciones y montos similares pagados, año anterior",
        unit=USD,
        obs="Prior-year column of Form 990 Part I; null on 990-EZ, which reports the current year only",
        orig="F9_01_EXP_GRANT_SIMILAR_PY",
    ),
    c(
        "benefits_paid_to_members",
        _F,
        "Benefits paid to or for members",
        "Benefícios pagos a membros ou em seu favor",
        "Beneficios pagados a miembros o en su favor",
        unit=USD,
        orig="F9_01_EXP_BEN_PAID_MEMB_CY",
    ),
    c(
        "benefits_paid_to_members_prior_year",
        _F,
        "Benefits paid to or for members, prior year",
        "Benefícios pagos a membros ou em seu favor, ano anterior",
        "Beneficios pagados a miembros o en su favor, año anterior",
        unit=USD,
        obs="Prior-year column of Form 990 Part I; null on 990-EZ, which reports the current year only",
        orig="F9_01_EXP_BEN_PAID_MEMB_PY",
    ),
    c(
        "salaries_compensation",
        _F,
        "Salaries, other compensation and employee benefits",
        "Salários, outras remunerações e benefícios a empregados",
        "Salarios, otras remuneraciones y beneficios a empleados",
        unit=USD,
        orig="F9_01_EXP_SAL_ETC_CY",
    ),
    c(
        "salaries_compensation_prior_year",
        _F,
        "Salaries, other compensation and employee benefits, prior year",
        "Salários, outras remunerações e benefícios a empregados, ano anterior",
        "Salarios, otras remuneraciones y beneficios a empleados, año anterior",
        unit=USD,
        obs="Prior-year column of Form 990 Part I; null on 990-EZ, which reports the current year only",
        orig="F9_01_EXP_SAL_ETC_PY",
    ),
    c(
        "professional_fundraising_fees",
        _F,
        "Professional fundraising fees",
        "Honorários de captação de recursos profissional",
        "Honorarios de recaudación de fondos profesional",
        unit=USD,
        obs="Form 990 only",
        orig="F9_01_EXP_PROF_FUNDR_TOT_CY",
    ),
    c(
        "professional_fundraising_fees_prior_year",
        _F,
        "Professional fundraising fees, prior year",
        "Honorários de captação de recursos profissional, ano anterior",
        "Honorarios de recaudación de fondos profesional, año anterior",
        unit=USD,
        obs="Prior-year column of Form 990 Part I; null on 990-EZ, which reports the current year only",
        orig="F9_01_EXP_PROF_FUNDR_TOT_PY",
    ),
    c(
        "total_fundraising_expenses",
        _F,
        "Total fundraising expenses",
        "Despesas totais de captação de recursos",
        "Gastos totales de recaudación de fondos",
        unit=USD,
        obs="Form 990 only",
        orig="F9_01_EXP_FUNDR_TOT_CY",
    ),
    c(
        "other_expenses",
        _F,
        "Other expenses",
        "Outras despesas",
        "Otros gastos",
        unit=USD,
        orig="F9_01_EXP_OTH_CY / _V2",
    ),
    c(
        "other_expenses_prior_year",
        _F,
        "Other expenses, prior year",
        "Outras despesas, ano anterior",
        "Otros gastos, año anterior",
        unit=USD,
        obs="Prior-year column of Form 990 Part I; null on 990-EZ, which reports the current year only",
        orig="F9_01_EXP_OTH_PY",
    ),
    c(
        "total_expenses",
        _F,
        "Total expenses",
        "Despesas totais",
        "Gastos totales",
        unit=USD,
        orig="F9_01_EXP_TOT_CY",
    ),
    c(
        "total_expenses_prior_year",
        _F,
        "Total expenses, prior year",
        "Despesas totais, ano anterior",
        "Gastos totales, año anterior",
        unit=USD,
        obs="Prior-year column of Form 990 Part I; null on 990-EZ, which reports the current year only",
        orig="F9_01_EXP_TOT_PY",
    ),
    c(
        "revenue_less_expenses",
        _F,
        "Revenue less expenses (excess or deficit)",
        "Receita menos despesas (superávit ou déficit)",
        "Ingresos menos gastos (superávit o déficit)",
        unit=USD,
        orig="F9_01_EXP_REV_LESS_EXP_CY",
    ),
    c(
        "revenue_less_expenses_prior_year",
        _F,
        "Revenue less expenses, prior year",
        "Receita menos despesas, ano anterior",
        "Ingresos menos gastos, año anterior",
        unit=USD,
        obs="Prior-year column of Form 990 Part I; null on 990-EZ, which reports the current year only",
        orig="F9_01_EXP_REV_LESS_EXP_PY",
    ),
    c(
        "total_assets_boy",
        _F,
        "Total assets at the beginning of the year",
        "Ativo total no início do ano",
        "Activo total al inicio del año",
        unit=USD,
        obs="Form 990 Part I; on 990-EZ the Part II balance-sheet total",
        orig="F9_01_NAFB_ASSET_TOT_BOY / F9_10_ASSET_TOT_BOY",
    ),
    c(
        "total_assets_eoy",
        _F,
        "Total assets at the end of the year",
        "Ativo total no fim do ano",
        "Activo total al final del año",
        unit=USD,
        obs="Form 990 Part I; on 990-EZ the Part II balance-sheet total",
        orig="F9_01_NAFB_ASSET_TOT_EOY / F9_10_ASSET_TOT_EOY",
    ),
    c(
        "total_liabilities_boy",
        _F,
        "Total liabilities at the beginning of the year",
        "Passivo total no início do ano",
        "Pasivo total al inicio del año",
        unit=USD,
        obs="Form 990 Part I; on 990-EZ the Part II balance-sheet total",
        orig="F9_01_NAFB_LIAB_TOT_BOY / F9_10_LIAB_TOT_BOY",
    ),
    c(
        "total_liabilities_eoy",
        _F,
        "Total liabilities at the end of the year",
        "Passivo total no fim do ano",
        "Pasivo total al final del año",
        unit=USD,
        obs="Form 990 Part I; on 990-EZ the Part II balance-sheet total",
        orig="F9_01_NAFB_LIAB_TOT_EOY / F9_10_LIAB_TOT_EOY",
    ),
    c(
        "net_assets_boy",
        _F,
        "Net assets or fund balances at the beginning of the year",
        "Patrimônio líquido ou saldo de fundos no início do ano",
        "Activos netos o saldo de fondos al inicio del año",
        unit=USD,
        orig="F9_01_NAFB_TOT_BOY",
    ),
    c(
        "net_assets_eoy",
        _F,
        "Net assets or fund balances at the end of the year",
        "Patrimônio líquido ou saldo de fundos no fim do ano",
        "Activos netos o saldo de fondos al final del año",
        unit=USD,
        orig="F9_01_NAFB_TOT_EOY",
    ),
]

COMPENSATION = [
    c(
        "year",
        _I,
        "Tax year of the return",
        "Ano fiscal da declaração",
        "Año fiscal de la declaración",
        dir=DIR_YEAR,
        obs="Partition column; the return's tax year (TaxYr in the return header)",
        orig="F9_00_TAX_YEAR",
    ),
    c(
        "ein",
        _S,
        "Employer Identification Number of the filing organization (nine digits)",
        "Número de Identificação de Empregador (EIN) da organização declarante (nove dígitos)",
        "Número de Identificación de Empleador (EIN) de la organización declarante (nueve dígitos)",
        orig="F9_00_ORG_EIN",
    ),
    c(
        "form_type",
        _S,
        "Return form filed: 990 or 990EZ",
        "Formulário apresentado: 990 ou 990EZ",
        "Formulario presentado: 990 o 990EZ",
        dict=True,
        orig="F9_00_RETURN_TYPE",
    ),
    c(
        "object_id",
        _S,
        "IRS object identifier of the filing",
        "Identificador de objeto da declaração no IRS",
        "Identificador de objeto de la declaración en el IRS",
        obs="18-digit IRS object id, also the XML file name; unique per filing",
        orig="(file name)",
    ),
    c(
        "line_number",
        _S,
        "Position of the person in the return's listing",
        "Posição da pessoa na listagem da declaração",
        "Posición de la persona en el listado de la declaración",
        obs="Sequence of the person within the return's listing, starting at 1",
        orig="(group order)",
    ),
    c(
        "person_name",
        _S,
        "Name of the officer, director, trustee, key employee or highest-compensated employee",
        "Nome do dirigente, diretor, curador, empregado-chave ou empregado mais bem remunerado",
        "Nombre del directivo, director, fiduciario, empleado clave o empleado mejor remunerado",
        orig="F9_07_COMP_DTK_NAME_PERS",
    ),
    c(
        "business_name",
        _S,
        "Name of the entity, when the position is held by an organization",
        "Nome da entidade, quando o cargo é ocupado por uma organização",
        "Nombre de la entidad, cuando el cargo lo ocupa una organización",
        orig="F9_07_COMP_DTK_NAME_ORG_L1",
    ),
    c(
        "title",
        _S,
        "Title or position",
        "Cargo ou título",
        "Cargo o título",
        orig="F9_07_COMP_DTK_TITLE",
    ),
    c(
        "average_hours_per_week",
        _F,
        "Average hours per week devoted to the position",
        "Média de horas semanais dedicadas ao cargo",
        "Promedio de horas semanales dedicadas al cargo",
        unit="hour",
        obs="Reported hours; the IRS schema stores them as a decimal string",
        orig="F9_07_COMP_DTK_AVE_HOUR_WEEK",
    ),
    c(
        "average_hours_per_week_related",
        _F,
        "Average hours per week for related organizations",
        "Média de horas semanais em organizações relacionadas",
        "Promedio de horas semanales en organizaciones relacionadas",
        unit="hour",
        obs="Form 990 only",
        orig="F9_07_COMP_DTK_AVE_HOUR_WEEK_RL",
    ),
    c(
        "is_individual_trustee_or_director",
        _B,
        "Position: individual trustee or director",
        "Cargo: curador individual ou diretor",
        "Cargo: fiduciario individual o director",
        obs="Position checkboxes exist on Form 990 Part VII only; null on 990-EZ",
        orig="F9_07_COMP_DTK_POS_INDIV_TRUST_X",
    ),
    c(
        "is_institutional_trustee",
        _B,
        "Position: institutional trustee",
        "Cargo: curador institucional",
        "Cargo: fiduciario institucional",
        obs="Position checkboxes exist on Form 990 Part VII only; null on 990-EZ",
        orig="F9_07_COMP_DTK_POS_INST_TRUST_X",
    ),
    c(
        "is_officer",
        _B,
        "Position: officer",
        "Cargo: dirigente",
        "Cargo: directivo",
        obs="Position checkboxes exist on Form 990 Part VII only; null on 990-EZ",
        orig="F9_07_COMP_DTK_POS_OFF_X",
    ),
    c(
        "is_key_employee",
        _B,
        "Position: key employee",
        "Cargo: empregado-chave",
        "Cargo: empleado clave",
        obs="Position checkboxes exist on Form 990 Part VII only; null on 990-EZ",
        orig="F9_07_COMP_DTK_POS_KEY_EMPL_X",
    ),
    c(
        "is_highest_compensated_employee",
        _B,
        "Position: highest compensated employee",
        "Cargo: empregado mais bem remunerado",
        "Cargo: empleado mejor remunerado",
        obs="Position checkboxes exist on Form 990 Part VII only; null on 990-EZ",
        orig="F9_07_COMP_DTK_POS_HIGH_COMP_X",
    ),
    c(
        "is_former",
        _B,
        "Position: former officer, director, trustee or employee",
        "Cargo: ex-dirigente, ex-diretor, ex-curador ou ex-empregado",
        "Cargo: exdirectivo, exdirector, exfiduciario o exempleado",
        obs="Position checkboxes exist on Form 990 Part VII only; null on 990-EZ",
        orig="F9_07_COMP_DTK_POS_FORMER_X",
    ),
    c(
        "reportable_compensation_from_organization",
        _F,
        "Reportable compensation from the organization (W-2/1099)",
        "Remuneração declarável paga pela organização (W-2/1099)",
        "Remuneración declarable pagada por la organización (W-2/1099)",
        unit=USD,
        obs="Form 990 column D; 990-EZ Part IV column (c)",
        orig="F9_07_COMP_DTK_COMP_ORG",
    ),
    c(
        "reportable_compensation_from_related",
        _F,
        "Reportable compensation from related organizations",
        "Remuneração declarável paga por organizações relacionadas",
        "Remuneración declarable pagada por organizaciones relacionadas",
        unit=USD,
        obs="Form 990 only",
        orig="F9_07_COMP_DTK_COMP_RLTD",
    ),
    c(
        "other_compensation",
        _F,
        "Estimated other compensation from the organization and related organizations",
        "Outra remuneração estimada da organização e de organizações relacionadas",
        "Otra remuneración estimada de la organización y de organizaciones relacionadas",
        unit=USD,
        obs="Form 990 column F; on 990-EZ the expense account and other allowances column (e)",
        orig="F9_07_COMP_DTK_COMP_OTH",
    ),
    c(
        "employee_benefit_contributions",
        _F,
        "Contributions to employee benefit plans and deferred compensation",
        "Contribuições a planos de benefícios e remuneração diferida",
        "Contribuciones a planes de beneficios y remuneración diferida",
        unit=USD,
        obs="990-EZ Part IV column (d) only",
        orig="F9_07_COMP_DTK_EMPL_BEN",
    ),
]

ORGANIZATION = [
    c(
        "extraction_date",
        _D,
        "Posting date of the monthly Business Master File extract",
        "Data de publicação do extrato mensal do Business Master File",
        "Fecha de publicación del extracto mensual del Business Master File",
        obs="Partition column; posting date of the monthly extract, read from the file's Last-Modified header",
        orig="(Last-Modified)",
    ),
    c(
        "ein",
        _S,
        "Employer Identification Number (nine digits)",
        "Número de Identificação de Empregador (EIN, nove dígitos)",
        "Número de Identificación de Empleador (EIN, nueve dígitos)",
        orig="EIN",
    ),
    c(
        "name",
        _S,
        "Primary name of the organization",
        "Nome principal da organização",
        "Nombre principal de la organización",
        orig="NAME",
    ),
    c(
        "sort_name",
        _S,
        "Secondary name line",
        "Linha de nome secundária",
        "Línea de nombre secundaria",
        obs="Trade name, chapter name or local number (SORT_NAME)",
        orig="SORT_NAME",
    ),
    c(
        "in_care_of_name",
        _S,
        "In-care-of name for correspondence",
        "Nome aos cuidados de quem a correspondência é dirigida",
        "Nombre a cuya atención se dirige la correspondencia",
        orig="ICO",
    ),
    c(
        "street",
        _S,
        "Street address",
        "Logradouro",
        "Dirección",
        orig="STREET",
    ),
    c("city", _S, "City", "Cidade", "Ciudad", orig="CITY"),
    c(
        "state",
        _S,
        "State of the filing address (USPS abbreviation)",
        "Estado do endereço (sigla USPS)",
        "Estado de la dirección (sigla USPS)",
        obs="Filing-address state; outside the US state directory for international records (eo_xx)",
        orig="STATE",
    ),
    c(
        "zip_code",
        _S,
        "ZIP code",
        "CEP (ZIP)",
        "Código postal (ZIP)",
        orig="ZIP",
    ),
    c(
        "group_exemption_number",
        _S,
        "Group exemption number",
        "Número de isenção de grupo",
        "Número de exención de grupo",
        obs="Four-digit group exemption number; 0000 when none",
        orig="GROUP",
    ),
    c(
        "subsection_code",
        _S,
        "Internal Revenue Code subsection under which the organization is exempt",
        "Subseção do Internal Revenue Code sob a qual a organização é isenta",
        "Subsección del Internal Revenue Code bajo la cual la organización está exenta",
        dict=True,
        obs="Subsection of IRC 501(c) (or 40=501(d), 50=501(e), 60=501(f), 70=501(k), 71, 81, 92=4947(a)(1)); see the dictionary",
        orig="SUBSECTION",
    ),
    c(
        "classification_code",
        _S,
        "Classification code(s) within the subsection",
        "Código(s) de classificação dentro da subseção",
        "Código(s) de clasificación dentro de la subsección",
        obs="Up to four one-digit classification codes concatenated; meaning depends on the subsection (dictionary key is subsection+classification)",
        orig="CLASSIFICATION",
    ),
    c(
        "affiliation_code",
        _S,
        "Affiliation code (central, intermediate, independent, subordinate)",
        "Código de afiliação (central, intermediária, independente, subordinada)",
        "Código de afiliación (central, intermedia, independiente, subordinada)",
        dict=True,
        orig="AFFILIATION",
    ),
    c(
        "ruling_date",
        _D,
        "Month of the ruling or determination letter recognizing exempt status",
        "Mês da carta de decisão ou determinação que reconhece a isenção",
        "Mes de la carta de resolución o determinación que reconoce la exención",
        obs="Month and year of the determination letter, stored as the first day of that month; null when the source has 000000",
        orig="RULING",
    ),
    c(
        "deductibility_code",
        _S,
        "Whether contributions are tax deductible",
        "Se as contribuições são dedutíveis",
        "Si las contribuciones son deducibles",
        dict=True,
        orig="DEDUCTIBILITY",
    ),
    c(
        "foundation_code",
        _S,
        "Foundation code (public charity or private foundation type)",
        "Código de fundação (tipo de instituição de caridade pública ou fundação privada)",
        "Código de fundación (tipo de organización benéfica pública o fundación privada)",
        dict=True,
        orig="FOUNDATION",
    ),
    c(
        "activity_code",
        _S,
        "Activity codes (obsolete since 1995)",
        "Códigos de atividade (obsoletos desde 1995)",
        "Códigos de actividad (obsoletos desde 1995)",
        obs="Up to three obsolete three-digit activity codes concatenated (pre-1995 determinations); 000000000 when none",
        orig="ACTIVITY",
    ),
    c(
        "organization_code",
        _S,
        "Type of organization (corporation, trust, cooperative, partnership, association)",
        "Tipo de organização (sociedade, trust, cooperativa, parceria, associação)",
        "Tipo de organización (sociedad, fideicomiso, cooperativa, asociación en participación, asociación)",
        dict=True,
        orig="ORGANIZATION",
    ),
    c(
        "status_code",
        _S,
        "Exempt organization status code",
        "Código de status da organização isenta",
        "Código de estado de la organización exenta",
        dict=True,
        orig="STATUS",
    ),
    c(
        "ntee_code",
        _S,
        "National Taxonomy of Exempt Entities (NTEE) code",
        "Código NTEE (National Taxonomy of Exempt Entities)",
        "Código NTEE (National Taxonomy of Exempt Entities)",
        dict=True,
        obs="NTEE-CC code assigned by the IRS; the dictionary covers the three-character code, a fourth character (when present) is an IRS suffix",
        orig="NTEE_CD",
    ),
    c(
        "tax_period",
        _S,
        "Tax period of the latest return filed (YYYYMM)",
        "Período fiscal da última declaração apresentada (YYYYMM)",
        "Período fiscal de la última declaración presentada (YYYYMM)",
        obs="Tax period of the latest return filed, as YYYYMM",
        orig="TAX_PERIOD",
    ),
    c(
        "accounting_period_month",
        _S,
        "Fiscal year-end month",
        "Mês de encerramento do exercício",
        "Mes de cierre del ejercicio",
        obs="Fiscal year-end month (MM)",
        orig="ACCT_PD",
    ),
    c(
        "filing_requirement_code",
        _S,
        "Form 990 filing requirement code",
        "Código de obrigatoriedade de apresentação do Form 990",
        "Código de obligación de presentación del Form 990",
        dict=True,
        orig="FILING_REQ_CD",
    ),
    c(
        "pf_filing_requirement_code",
        _S,
        "Form 990-PF filing requirement code",
        "Código de obrigatoriedade de apresentação do Form 990-PF",
        "Código de obligación de presentación del Form 990-PF",
        dict=True,
        orig="PF_FILING_REQ_CD",
    ),
    c(
        "asset_code",
        _S,
        "Asset size class of the latest return",
        "Faixa de ativos da última declaração",
        "Tramo de activos de la última declaración",
        dict=True,
        orig="ASSET_CD",
    ),
    c(
        "income_code",
        _S,
        "Income size class of the latest return",
        "Faixa de renda da última declaração",
        "Tramo de ingresos de la última declaración",
        dict=True,
        orig="INCOME_CD",
    ),
    c(
        "asset_amount",
        _F,
        "Book value of total assets at the end of the year on the latest return",
        "Valor contábil do ativo total no fim do ano na última declaração",
        "Valor contable del activo total al final del año en la última declaración",
        unit=USD,
        obs="From the most recent Form 990-series return; null when the organization has not filed",
        orig="ASSET_AMT",
    ),
    c(
        "income_amount",
        _F,
        "Income amount computed by the IRS from the latest return",
        "Valor de renda calculado pelo IRS a partir da última declaração",
        "Monto de ingresos calculado por el IRS a partir de la última declaración",
        unit=USD,
        obs="Computer-generated by the IRS from the latest return; adds back expense items netted in total revenue",
        orig="INCOME_AMT",
    ),
    c(
        "revenue_amount",
        _F,
        "Total revenue on the latest Form 990 or 990-EZ",
        "Receita total na última declaração Form 990 ou 990-EZ",
        "Ingreso total en la última declaración Form 990 o 990-EZ",
        unit=USD,
        obs="From the most recent Form 990-series return; null when the organization has not filed",
        orig="REVENUE_AMT",
    ),
]

REVOCATION = [
    c(
        "ein",
        _S,
        "Employer Identification Number (nine digits)",
        "Número de Identificação de Empregador (EIN, nove dígitos)",
        "Número de Identificación de Empleador (EIN, nueve dígitos)",
        orig="EIN",
    ),
    c(
        "legal_name",
        _S,
        "Legal name of the organization",
        "Nome legal da organização",
        "Nombre legal de la organización",
        orig="Legal Name",
    ),
    c(
        "doing_business_as_name",
        _S,
        "Name the organization does business as",
        "Nome fantasia da organização",
        "Nombre comercial de la organización",
        orig="Doing Business As Name",
    ),
    c(
        "address",
        _S,
        "Street address",
        "Logradouro",
        "Dirección",
        orig="Organization Address",
    ),
    c("city", _S, "City", "Cidade", "Ciudad", orig="City"),
    c(
        "state",
        _S,
        "State (USPS abbreviation)",
        "Estado (sigla USPS)",
        "Estado (sigla USPS)",
        orig="State",
    ),
    c(
        "zip_code",
        _S,
        "ZIP code",
        "CEP (ZIP)",
        "Código postal (ZIP)",
        orig="ZIP Code",
    ),
    c(
        "country",
        _S,
        "Country code",
        "Código do país",
        "Código del país",
        orig="Country",
    ),
    c(
        "exemption_type",
        _S,
        "Internal Revenue Code subsection the organization was exempt under",
        "Subseção do Internal Revenue Code sob a qual a organização era isenta",
        "Subsección del Internal Revenue Code bajo la cual la organización estaba exenta",
        dict=True,
        obs="IRC subsection under which the organization was exempt (same code list as the BMF subsection_code)",
        orig="Exemption Type",
    ),
    c(
        "revocation_date",
        _D,
        "Effective date of the automatic revocation",
        "Data de vigência da revogação automática",
        "Fecha de vigencia de la revocación automática",
        obs="Effective date of the automatic revocation",
        orig="Revocation Date",
    ),
    c(
        "revocation_posting_date",
        _D,
        "Date the revocation was posted",
        "Data de publicação da revogação",
        "Fecha de publicación de la revocación",
        obs="Date the revocation was posted on irs.gov",
        orig="Revocation Posting Date",
    ),
    c(
        "exemption_reinstatement_date",
        _D,
        "Date exempt status was reinstated, if any",
        "Data de restabelecimento da isenção, se houver",
        "Fecha de restablecimiento de la exención, si la hay",
        obs="Null unless exemption was later reinstated",
        orig="Exemption Reinstatement Date",
    ),
]

DICIONARIO = [
    c(
        "id_tabela",
        _S,
        "Table identifier",
        "Identificador da tabela",
        "Identificador de la tabla",
    ),
    c(
        "nome_coluna",
        _S,
        "Column name",
        "Nome da coluna",
        "Nombre de la columna",
    ),
    c("chave", _S, "Code value", "Chave (código)", "Clave (código)"),
    c(
        "cobertura_temporal",
        _S,
        "Temporal coverage of the code",
        "Cobertura temporal do código",
        "Cobertura temporal del código",
    ),
    c(
        "valor",
        _S,
        "Label of the code",
        "Valor (rótulo) do código",
        "Valor (etiqueta) del código",
    ),
]

TABLES = {
    "organization": ORGANIZATION,
    "return_financial": RETURN_FINANCIAL,
    "compensation": COMPENSATION,
    "revocation": REVOCATION,
    "dicionario": DICIONARIO,
}


def column_names(table: str) -> list[str]:
    return [col["name"] for col in TABLES[table]]


def write_architecture() -> None:
    ARCH_DIR.mkdir(exist_ok=True)
    JSON_DIR.mkdir(exist_ok=True)
    for table, cols in TABLES.items():
        rows, jrows = [], []
        for col in cols:
            obs_en = col.get("obs", "")
            if obs_en and obs_en not in OBS:
                raise SystemExit(f"untranslated observation: {obs_en}")
            obs_pt, obs_es = OBS[obs_en] if obs_en else ("", "")
            rows.append(
                {
                    "name": col["name"],
                    "bigquery_type": col["type"],
                    "description": col["pt"],
                    "temporal_coverage": "",
                    "covered_by_dictionary": "yes"
                    if col.get("dict")
                    else "no",
                    "directory_column": col.get("dir", ""),
                    "measurement_unit": col.get("unit", ""),
                    "has_sensitive_data": "no",
                    "observations": obs_pt,
                    "original_name": col.get("orig", ""),
                }
            )
            jrows.append(
                {
                    "name": col["name"],
                    "bigquery_type": col["type"],
                    "description_pt": col["pt"],
                    "description_en": col["en"],
                    "description_es": col["es"],
                    "covered_by_dictionary": bool(col.get("dict")),
                    "directory_column": col.get("dir", ""),
                    "measurement_unit": col.get("unit", ""),
                    "observations_pt": obs_pt,
                    "observations_en": obs_en,
                    "observations_es": obs_es,
                    "original_name": col.get("orig", ""),
                }
            )
        with open(
            ARCH_DIR / f"{table}.csv", "w", newline="", encoding="utf-8"
        ) as fh:
            w = csv.DictWriter(fh, fieldnames=ARCH_HEADER)
            w.writeheader()
            w.writerows(rows)
        (JSON_DIR / f"{table}.json").write_text(
            json.dumps(jrows, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        print(f"{table}: {len(cols)} columns")


if __name__ == "__main__":
    write_architecture()
