"""Regenerate the legacy (2007-2017) architecture TSV from the real 45-column header.

The `_codes.zip` all-records file header (verified from 2017) is the source of truth.
Tract-level fields are renamed to match the modern table where the concept matches
(tract_population, tract_minority_population_percent, tract_to_msa_income_percentage,
tract_owner_occupied_units, tract_one_to_four_family_homes); everything else keeps a
faithful name. `original_name` always holds the raw header token.

Amounts reported "in thousands" (loan_amount_000s, applicant_income_000s) are multiplied
by 1000 at clean time so measurement_unit=USD is truthful; noted in observations.

Emits models/us_cfpb_hmda/code/sheet_loan_application_register_legacy.tsv
"""

from pathlib import Path

HEADER = [
    "name",
    "bigquery_type",
    "description",
    "temporal_coverage",
    "covered_by_dictionary",
    "directory_column",
    "measurement_unit",
    "has_sensitive_data",
    "observations",
    "original_name",
]

# name, type, dict(yes/no), unit, directory_column, observations, original_name, description_pt
# order below is the FINAL column order (partition -> geography -> institution ->
# loan/financial -> demographics -> census tract fields -> filing artifacts).
ROWS = [
    (
        "year",
        "INT64",
        "no",
        "year",
        "br_bd_diretorios_data_tempo.ano:ano",
        "",
        "as_of_year",
        "Ano de referência do registro de empréstimo/solicitação",
    ),
    (
        "state_code",
        "STRING",
        "no",
        "",
        "",
        "Código FIPS numérico de estado; FK para br_bd_diretorios_us resolvida no discover",
        "state_code",
        "Código FIPS de duas posições do estado dos EUA",
    ),
    (
        "county_code",
        "STRING",
        "no",
        "",
        "",
        "Código FIPS de condado; FK para br_bd_diretorios_us resolvida no discover",
        "county_code",
        "Código FIPS de cinco posições do condado",
    ),
    (
        "census_tract",
        "STRING",
        "no",
        "",
        "",
        "Setor censitário; FK para br_bd_diretorios_us resolvida no discover",
        "census_tract_number",
        "Código do setor censitário do Census Bureau",
    ),
    (
        "msa_md",
        "STRING",
        "no",
        "",
        "",
        "Código MSA/MD reportado pela instituição",
        "msamd",
        "Código da área metropolitana ou divisão metropolitana (MSA/MD)",
    ),
    (
        "respondent_id",
        "STRING",
        "no",
        "",
        "",
        "Identificador da instituição declarante; combinar com agency_code para unicidade",
        "respondent_id",
        "Identificador da instituição declarante no ano de referência",
    ),
    (
        "agency_code",
        "STRING",
        "yes",
        "",
        "",
        "",
        "agency_code",
        "Código da agência federal supervisora que recebeu o registro",
    ),
    (
        "loan_type",
        "STRING",
        "yes",
        "",
        "",
        "",
        "loan_type",
        "Tipo de empréstimo (convencional, FHA, VA, FSA/RHS)",
    ),
    (
        "property_type",
        "STRING",
        "yes",
        "",
        "",
        "",
        "property_type",
        "Tipo de imóvel (1-4 famílias, multifamiliar, casa pré-fabricada)",
    ),
    (
        "loan_purpose",
        "STRING",
        "yes",
        "",
        "",
        "",
        "loan_purpose",
        "Finalidade do empréstimo (compra, melhoria, refinanciamento)",
    ),
    (
        "owner_occupancy",
        "STRING",
        "yes",
        "",
        "",
        "",
        "owner_occupancy",
        "Ocupação do imóvel pelo proprietário como residência principal",
    ),
    (
        "preapproval",
        "STRING",
        "yes",
        "",
        "",
        "",
        "preapproval",
        "Indicador de solicitação de pré-aprovação",
    ),
    (
        "action_taken",
        "STRING",
        "yes",
        "",
        "",
        "",
        "action_taken",
        "Ação tomada sobre a solicitação (originado, negado, retirado, etc.)",
    ),
    (
        "loan_amount",
        "FLOAT64",
        "no",
        "USD",
        "",
        "Valor reportado na fonte em milhares de dólares e multiplicado por 1000",
        "loan_amount_000s",
        "Valor do empréstimo em dólares",
    ),
    (
        "income",
        "FLOAT64",
        "no",
        "USD",
        "",
        "Renda reportada na fonte em milhares de dólares e multiplicada por 1000",
        "applicant_income_000s",
        "Renda bruta anual considerada na decisão, em dólares",
    ),
    (
        "rate_spread",
        "FLOAT64",
        "no",
        "percent",
        "",
        "Regra de cálculo do spread mudou no 4o trimestre de 2009",
        "rate_spread",
        "Diferença entre a APR do empréstimo e a taxa de referência (spread)",
    ),
    (
        "hoepa_status",
        "STRING",
        "yes",
        "",
        "",
        "",
        "hoepa_status",
        "Indicador de empréstimo de alto custo sob o HOEPA",
    ),
    (
        "lien_status",
        "STRING",
        "yes",
        "",
        "",
        "",
        "lien_status",
        "Posição da garantia (primeira, subordinada)",
    ),
    (
        "purchaser_type",
        "STRING",
        "yes",
        "",
        "",
        "",
        "purchaser_type",
        "Tipo de comprador do empréstimo no mercado secundário",
    ),
    (
        "applicant_ethnicity",
        "STRING",
        "yes",
        "",
        "",
        "",
        "applicant_ethnicity",
        "Etnia do solicitante (código único, esquema pré-2018)",
    ),
    (
        "co_applicant_ethnicity",
        "STRING",
        "yes",
        "",
        "",
        "",
        "co_applicant_ethnicity",
        "Etnia do cossolicitante (código único, esquema pré-2018)",
    ),
    (
        "applicant_race_1",
        "STRING",
        "yes",
        "",
        "",
        "",
        "applicant_race_1",
        "Primeira raça informada pelo solicitante",
    ),
    (
        "applicant_race_2",
        "STRING",
        "yes",
        "",
        "",
        "",
        "applicant_race_2",
        "Segunda raça informada pelo solicitante",
    ),
    (
        "applicant_race_3",
        "STRING",
        "yes",
        "",
        "",
        "",
        "applicant_race_3",
        "Terceira raça informada pelo solicitante",
    ),
    (
        "applicant_race_4",
        "STRING",
        "yes",
        "",
        "",
        "",
        "applicant_race_4",
        "Quarta raça informada pelo solicitante",
    ),
    (
        "applicant_race_5",
        "STRING",
        "yes",
        "",
        "",
        "",
        "applicant_race_5",
        "Quinta raça informada pelo solicitante",
    ),
    (
        "co_applicant_race_1",
        "STRING",
        "yes",
        "",
        "",
        "",
        "co_applicant_race_1",
        "Primeira raça informada pelo cossolicitante",
    ),
    (
        "co_applicant_race_2",
        "STRING",
        "yes",
        "",
        "",
        "",
        "co_applicant_race_2",
        "Segunda raça informada pelo cossolicitante",
    ),
    (
        "co_applicant_race_3",
        "STRING",
        "yes",
        "",
        "",
        "",
        "co_applicant_race_3",
        "Terceira raça informada pelo cossolicitante",
    ),
    (
        "co_applicant_race_4",
        "STRING",
        "yes",
        "",
        "",
        "",
        "co_applicant_race_4",
        "Quarta raça informada pelo cossolicitante",
    ),
    (
        "co_applicant_race_5",
        "STRING",
        "yes",
        "",
        "",
        "",
        "co_applicant_race_5",
        "Quinta raça informada pelo cossolicitante",
    ),
    (
        "applicant_sex",
        "STRING",
        "yes",
        "",
        "",
        "",
        "applicant_sex",
        "Sexo do solicitante",
    ),
    (
        "co_applicant_sex",
        "STRING",
        "yes",
        "",
        "",
        "",
        "co_applicant_sex",
        "Sexo do cossolicitante",
    ),
    (
        "denial_reason_1",
        "STRING",
        "yes",
        "",
        "",
        "",
        "denial_reason_1",
        "Primeiro motivo de negação da solicitação",
    ),
    (
        "denial_reason_2",
        "STRING",
        "yes",
        "",
        "",
        "",
        "denial_reason_2",
        "Segundo motivo de negação da solicitação",
    ),
    (
        "denial_reason_3",
        "STRING",
        "yes",
        "",
        "",
        "",
        "denial_reason_3",
        "Terceiro motivo de negação da solicitação",
    ),
    (
        "tract_population",
        "INT64",
        "no",
        "unit",
        "",
        "",
        "population",
        "População total do setor censitário",
    ),
    (
        "tract_minority_population_percent",
        "FLOAT64",
        "no",
        "percent",
        "",
        "",
        "minority_population",
        "Percentual de população de minorias no setor censitário",
    ),
    (
        "hud_median_family_income",
        "INT64",
        "no",
        "USD",
        "",
        "Renda mediana definida pelo HUD para a MSA/MD (analog pré-2018 do campo FFIEC)",
        "hud_median_family_income",
        "Renda familiar mediana da MSA/MD definida pelo HUD, em dólares",
    ),
    (
        "tract_to_msa_income_percentage",
        "FLOAT64",
        "no",
        "percent",
        "",
        "",
        "tract_to_msamd_income",
        "Razão entre a renda mediana do setor e a da MSA/MD, em percentual",
    ),
    (
        "tract_owner_occupied_units",
        "INT64",
        "no",
        "unit",
        "",
        "",
        "number_of_owner_occupied_units",
        "Número de domicílios ocupados pelo proprietário no setor censitário",
    ),
    (
        "tract_one_to_four_family_homes",
        "INT64",
        "no",
        "unit",
        "",
        "",
        "number_of_1_to_4_family_units",
        "Número de domicílios de 1 a 4 famílias no setor censitário",
    ),
    # NOTE: edit_status, sequence_number, application_date_indicator are present in the raw
    # header but 100% empty in the public all-records file (verified 2017) -> dropped.
]


def main() -> None:
    out = (
        Path(__file__).resolve().parent
        / "sheet_loan_application_register_legacy.tsv"
    )
    lines = ["\t".join(HEADER)]
    for name, typ, dic, unit, dircol, obs, orig, desc in ROWS:
        lines.append(
            "\t".join(
                [
                    name,
                    typ,
                    desc,
                    "",
                    dic,
                    dircol,
                    unit,
                    "no",
                    obs,
                    orig,
                ]
            )
        )
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out} with {len(ROWS)} columns")


if __name__ == "__main__":
    main()
