-- Generated by models/us_census_lodes/code/gen_dbt.py from
-- code/architecture/<table>.csv. Edit the generator, not this file.
{{
    config(
        schema="us_census_lodes",
        alias="residence_jobs",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 2002, "end": 2028, "interval": 1},
        },
        cluster_by=["state_id", "county_id"],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(state_id as string) state_id,
    safe_cast(county_id as string) county_id,
    safe_cast(census_tract_id as string) census_tract_id,
    safe_cast(block_id as string) block_id,
    safe_cast(job_type as string) job_type,
    safe_cast(jobs_total as int64) jobs_total,
    safe_cast(jobs_age_29_or_younger as int64) jobs_age_29_or_younger,
    safe_cast(jobs_age_30_to_54 as int64) jobs_age_30_to_54,
    safe_cast(jobs_age_55_or_older as int64) jobs_age_55_or_older,
    safe_cast(jobs_earnings_1250_or_less as int64) jobs_earnings_1250_or_less,
    safe_cast(jobs_earnings_1251_to_3333 as int64) jobs_earnings_1251_to_3333,
    safe_cast(jobs_earnings_above_3333 as int64) jobs_earnings_above_3333,
    safe_cast(jobs_naics_11 as int64) jobs_naics_11,
    safe_cast(jobs_naics_21 as int64) jobs_naics_21,
    safe_cast(jobs_naics_22 as int64) jobs_naics_22,
    safe_cast(jobs_naics_23 as int64) jobs_naics_23,
    safe_cast(jobs_naics_31_33 as int64) jobs_naics_31_33,
    safe_cast(jobs_naics_42 as int64) jobs_naics_42,
    safe_cast(jobs_naics_44_45 as int64) jobs_naics_44_45,
    safe_cast(jobs_naics_48_49 as int64) jobs_naics_48_49,
    safe_cast(jobs_naics_51 as int64) jobs_naics_51,
    safe_cast(jobs_naics_52 as int64) jobs_naics_52,
    safe_cast(jobs_naics_53 as int64) jobs_naics_53,
    safe_cast(jobs_naics_54 as int64) jobs_naics_54,
    safe_cast(jobs_naics_55 as int64) jobs_naics_55,
    safe_cast(jobs_naics_56 as int64) jobs_naics_56,
    safe_cast(jobs_naics_61 as int64) jobs_naics_61,
    safe_cast(jobs_naics_62 as int64) jobs_naics_62,
    safe_cast(jobs_naics_71 as int64) jobs_naics_71,
    safe_cast(jobs_naics_72 as int64) jobs_naics_72,
    safe_cast(jobs_naics_81 as int64) jobs_naics_81,
    safe_cast(jobs_naics_92 as int64) jobs_naics_92,
    safe_cast(jobs_race_white as int64) jobs_race_white,
    safe_cast(jobs_race_black as int64) jobs_race_black,
    safe_cast(
        jobs_race_american_indian_alaska_native as int64
    ) jobs_race_american_indian_alaska_native,
    safe_cast(jobs_race_asian as int64) jobs_race_asian,
    safe_cast(
        jobs_race_native_hawaiian_pacific_islander as int64
    ) jobs_race_native_hawaiian_pacific_islander,
    safe_cast(jobs_race_two_or_more as int64) jobs_race_two_or_more,
    safe_cast(jobs_ethnicity_not_hispanic as int64) jobs_ethnicity_not_hispanic,
    safe_cast(jobs_ethnicity_hispanic as int64) jobs_ethnicity_hispanic,
    safe_cast(
        jobs_education_less_than_high_school as int64
    ) jobs_education_less_than_high_school,
    safe_cast(jobs_education_high_school as int64) jobs_education_high_school,
    safe_cast(jobs_education_some_college as int64) jobs_education_some_college,
    safe_cast(
        jobs_education_bachelors_or_higher as int64
    ) jobs_education_bachelors_or_higher,
    safe_cast(jobs_sex_male as int64) jobs_sex_male,
    safe_cast(jobs_sex_female as int64) jobs_sex_female,
    safe_cast(date_created as date) date_created
from {{ set_datalake_project("us_census_lodes_staging.residence_jobs") }} as t
