-- Generated by models/us_census_lodes/code/gen_dbt.py from
-- code/architecture/<table>.csv. Edit the generator, not this file.
{{
    config(
        schema="us_census_lodes",
        alias="geography_crosswalk",
        materialized="table",
    )
}}


select
    safe_cast(block_id as string) block_id,
    safe_cast(state_id as string) state_id,
    safe_cast(state_abbreviation as string) state_abbreviation,
    safe_cast(state_name as string) state_name,
    safe_cast(county_id as string) county_id,
    safe_cast(county_name as string) county_name,
    safe_cast(census_tract_id as string) census_tract_id,
    safe_cast(census_tract_name as string) census_tract_name,
    safe_cast(block_group_id as string) block_group_id,
    safe_cast(block_group_name as string) block_group_name,
    safe_cast(cbsa_id as string) cbsa_id,
    safe_cast(cbsa_name as string) cbsa_name,
    safe_cast(zcta_id as string) zcta_id,
    safe_cast(zcta_name as string) zcta_name,
    safe_cast(place_id as string) place_id,
    safe_cast(place_name as string) place_name,
    safe_cast(county_subdivision_id as string) county_subdivision_id,
    safe_cast(county_subdivision_name as string) county_subdivision_name,
    safe_cast(congressional_district_id as string) congressional_district_id,
    safe_cast(congressional_district_name as string) congressional_district_name,
    safe_cast(
        state_legislative_district_lower_id as string
    ) state_legislative_district_lower_id,
    safe_cast(
        state_legislative_district_lower_name as string
    ) state_legislative_district_lower_name,
    safe_cast(
        state_legislative_district_upper_id as string
    ) state_legislative_district_upper_id,
    safe_cast(
        state_legislative_district_upper_name as string
    ) state_legislative_district_upper_name,
    safe_cast(school_district_id as string) school_district_id,
    safe_cast(school_district_name as string) school_district_name,
    safe_cast(secondary_school_district_id as string) secondary_school_district_id,
    safe_cast(secondary_school_district_name as string) secondary_school_district_name,
    safe_cast(tribal_area_id as string) tribal_area_id,
    safe_cast(tribal_area_name as string) tribal_area_name,
    safe_cast(tribal_subdivision_id as string) tribal_subdivision_id,
    safe_cast(tribal_subdivision_name as string) tribal_subdivision_name,
    safe_cast(alaska_native_corporation_id as string) alaska_native_corporation_id,
    safe_cast(alaska_native_corporation_name as string) alaska_native_corporation_name,
    safe_cast(military_installation_id as string) military_installation_id,
    safe_cast(military_installation_name as string) military_installation_name,
    safe_cast(workforce_board_id as string) workforce_board_id,
    safe_cast(workforce_board_name as string) workforce_board_name,
    safe_cast(latitude as float64) latitude,
    safe_cast(longitude as float64) longitude,
    safe_cast(date_created as date) date_created
from {{ set_datalake_project("us_census_lodes_staging.geography_crosswalk") }} as t
