{{
    config(
        schema="us_cfpb_hmda",
        alias="loan_application_register",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 2018, "end": 2029, "interval": 1},
        },
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(state_abbreviation as string) state_abbreviation,
    safe_cast(county_id as string) county_id,
    safe_cast(census_tract_id as string) census_tract_id,
    safe_cast(msa_md_id as string) msa_md_id,
    safe_cast(lei as string) lei,
    safe_cast(conforming_loan_limit as string) conforming_loan_limit,
    safe_cast(derived_loan_product_type as string) derived_loan_product_type,
    safe_cast(derived_dwelling_category as string) derived_dwelling_category,
    safe_cast(derived_ethnicity as string) derived_ethnicity,
    safe_cast(derived_race as string) derived_race,
    safe_cast(derived_sex as string) derived_sex,
    safe_cast(action_taken as string) action_taken,
    safe_cast(purchaser_type as string) purchaser_type,
    safe_cast(preapproval as string) preapproval,
    safe_cast(loan_type as string) loan_type,
    safe_cast(loan_purpose as string) loan_purpose,
    safe_cast(lien_status as string) lien_status,
    safe_cast(reverse_mortgage as string) reverse_mortgage,
    safe_cast(open_end_line_of_credit as string) open_end_line_of_credit,
    safe_cast(business_or_commercial_purpose as string) business_or_commercial_purpose,
    safe_cast(loan_amount as float64) loan_amount,
    safe_cast(loan_to_value_ratio as float64) loan_to_value_ratio,
    safe_cast(interest_rate as float64) interest_rate,
    safe_cast(rate_spread as float64) rate_spread,
    safe_cast(hoepa_status as string) hoepa_status,
    safe_cast(total_loan_costs as float64) total_loan_costs,
    safe_cast(total_points_and_fees as float64) total_points_and_fees,
    safe_cast(origination_charges as float64) origination_charges,
    safe_cast(discount_points as float64) discount_points,
    safe_cast(lender_credits as float64) lender_credits,
    safe_cast(loan_term as int64) loan_term,
    safe_cast(prepayment_penalty_term as int64) prepayment_penalty_term,
    safe_cast(intro_rate_period as int64) intro_rate_period,
    safe_cast(negative_amortization as string) negative_amortization,
    safe_cast(interest_only_payment as string) interest_only_payment,
    safe_cast(balloon_payment as string) balloon_payment,
    safe_cast(other_nonamortizing_features as string) other_nonamortizing_features,
    safe_cast(property_value as float64) property_value,
    safe_cast(construction_method as string) construction_method,
    safe_cast(occupancy_type as string) occupancy_type,
    safe_cast(
        manufactured_home_secured_property_type as string
    ) manufactured_home_secured_property_type,
    safe_cast(
        manufactured_home_land_property_interest as string
    ) manufactured_home_land_property_interest,
    safe_cast(total_units as string) total_units,
    safe_cast(multifamily_affordable_units as int64) multifamily_affordable_units,
    safe_cast(income as float64) income,
    safe_cast(debt_to_income_ratio as string) debt_to_income_ratio,
    safe_cast(applicant_credit_score_type as string) applicant_credit_score_type,
    safe_cast(co_applicant_credit_score_type as string) co_applicant_credit_score_type,
    safe_cast(applicant_ethnicity_1 as string) applicant_ethnicity_1,
    safe_cast(applicant_ethnicity_2 as string) applicant_ethnicity_2,
    safe_cast(applicant_ethnicity_3 as string) applicant_ethnicity_3,
    safe_cast(applicant_ethnicity_4 as string) applicant_ethnicity_4,
    safe_cast(applicant_ethnicity_5 as string) applicant_ethnicity_5,
    safe_cast(co_applicant_ethnicity_1 as string) co_applicant_ethnicity_1,
    safe_cast(co_applicant_ethnicity_2 as string) co_applicant_ethnicity_2,
    safe_cast(co_applicant_ethnicity_3 as string) co_applicant_ethnicity_3,
    safe_cast(co_applicant_ethnicity_4 as string) co_applicant_ethnicity_4,
    safe_cast(co_applicant_ethnicity_5 as string) co_applicant_ethnicity_5,
    safe_cast(applicant_ethnicity_observed as string) applicant_ethnicity_observed,
    safe_cast(
        co_applicant_ethnicity_observed as string
    ) co_applicant_ethnicity_observed,
    safe_cast(applicant_race_1 as string) applicant_race_1,
    safe_cast(applicant_race_2 as string) applicant_race_2,
    safe_cast(applicant_race_3 as string) applicant_race_3,
    safe_cast(applicant_race_4 as string) applicant_race_4,
    safe_cast(applicant_race_5 as string) applicant_race_5,
    safe_cast(co_applicant_race_1 as string) co_applicant_race_1,
    safe_cast(co_applicant_race_2 as string) co_applicant_race_2,
    safe_cast(co_applicant_race_3 as string) co_applicant_race_3,
    safe_cast(co_applicant_race_4 as string) co_applicant_race_4,
    safe_cast(co_applicant_race_5 as string) co_applicant_race_5,
    safe_cast(applicant_race_observed as string) applicant_race_observed,
    safe_cast(co_applicant_race_observed as string) co_applicant_race_observed,
    safe_cast(applicant_sex as string) applicant_sex,
    safe_cast(co_applicant_sex as string) co_applicant_sex,
    safe_cast(applicant_sex_observed as string) applicant_sex_observed,
    safe_cast(co_applicant_sex_observed as string) co_applicant_sex_observed,
    safe_cast(applicant_age as string) applicant_age,
    safe_cast(co_applicant_age as string) co_applicant_age,
    safe_cast(applicant_age_above_62 as string) applicant_age_above_62,
    safe_cast(co_applicant_age_above_62 as string) co_applicant_age_above_62,
    safe_cast(submission_of_application as string) submission_of_application,
    safe_cast(
        initially_payable_to_institution as string
    ) initially_payable_to_institution,
    safe_cast(aus_1 as string) aus_1,
    safe_cast(aus_2 as string) aus_2,
    safe_cast(aus_3 as string) aus_3,
    safe_cast(aus_4 as string) aus_4,
    safe_cast(aus_5 as string) aus_5,
    safe_cast(denial_reason_1 as string) denial_reason_1,
    safe_cast(denial_reason_2 as string) denial_reason_2,
    safe_cast(denial_reason_3 as string) denial_reason_3,
    safe_cast(denial_reason_4 as string) denial_reason_4,
    safe_cast(tract_population as int64) tract_population,
    safe_cast(
        tract_minority_population_percent as float64
    ) tract_minority_population_percent,
    safe_cast(
        ffiec_msa_md_median_family_income as int64
    ) ffiec_msa_md_median_family_income,
    safe_cast(tract_to_msa_income_percentage as float64) tract_to_msa_income_percentage,
    safe_cast(tract_owner_occupied_units as int64) tract_owner_occupied_units,
    safe_cast(tract_one_to_four_family_homes as int64) tract_one_to_four_family_homes,
    safe_cast(
        tract_median_age_of_housing_units as int64
    ) tract_median_age_of_housing_units
from {{ set_datalake_project("us_cfpb_hmda_staging.loan_application_register") }} as t
