---
version: 2
models:
  - name: br_bd_diretorios_mx__estado
    description: >
      Tabla estado del conjunto br_bd_diretorios_mx.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [id_estado]
      - not_null_proportion_multiple_columns:
          at_least: 0.05
    columns:
      - name: id_estado
        description: >
          Clave geoestadística de la entidad federativa según INEGI, de dos dígitos
        tests: [not_null]
      - name: nombre
        description: >
          Nombre de la entidad federativa
      - name: abreviatura
        description: >
          Abreviatura oficial de la entidad federativa
  - name: br_bd_diretorios_mx__municipio
    description: >
      Tabla municipio del conjunto br_bd_diretorios_mx.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [id_municipio]
      - not_null_proportion_multiple_columns:
          at_least: 0.05
    columns:
      - name: id_municipio
        description: >
          Clave geoestadística del municipio según INEGI, de cinco dígitos
        tests: [not_null]
      - name: id_estado
        description: >
          Clave de la entidad federativa a la que pertenece el municipio
        tests:
          - relationships:
              to: ref('br_bd_diretorios_mx__estado')
              field: id_estado
      - name: nombre
        description: >-
          Nombre del municipio
