---
version: 2
models:
  - name: br_bd_diretorios_comercio_internacional__sistema_harmonizado
    description: O "Sistema Harmonizado de Designação e de Codificação de Mercadorias",
      ou simplesmente "Sistema Harmonizado", tem o objetivo maior foi a criação de
      um sistema único mundial de designação e de codificação de mercadorias.
    tests:
      - dbt_utils.unique_combination_of_columns:
          tags: [comercio_internacional]
          combination_of_columns: [id_sh6]
      - not_null_proportion_multiple_columns:
          at_least: 0.97
    columns:
      - name: id_sh6
        description: Identificador de 6 dígitos do Sistema Harmonizado (SH6)
        tests:
          - custom_relationships:
              to: ref('br_bd_diretorios_mundo__nomenclatura_comum_mercosul')
              field: id_sh6
              ignore_values: ['401099', '701920', '848499']
      - name: id_sh4
        description: Identificador de 4 dígitos do Sistema Harmonizado (SH6)
      - name: id_sh2
        description: Identificador de 2 dígitos do Sistema Harmonizado (SH6)
      - name: id_ncm_secrom
        description: Não informado
      - name: nome_sh6_portugues
        description: Descrição do id_sh6 em português
      - name: nome_sh4_portugues
        description: Descrição do id_sh4 em português
      - name: nome_sh2_portugues
        description: Descrição do id_sh2 em português
      - name: nome_sec_portugues
        description: Descrição do em português
      - name: nome_sh6_espanhol
        description: Descrição do id_sh6 em espanhol
      - name: nome_sh4_espanhol
        description: Descrição do id_sh4 em espanhol
      - name: nome_sh2_espanhol
        description: Descrição do id_sh2 em espanhol
      - name: nome_sec_espanhol
        description: Descrição do em espanhol
      - name: nome_sh6_ingles
        description: Descrição do id_sh6 em inglês
      - name: nome_sh4_ingles
        description: Descrição do id_sh4 em inglês
      - name: nome_sh2_ingles
        description: Descrição do id_sh2 em inglês
      - name: nome_sec_ingles
        description: Descrição do em inglês
