select
    safe_cast(id_pesquisa as string) id_pesquisa,
    safe_cast(ano as int64) ano,
    safe_cast(sigla_uf as string) sigla_uf,
    safe_cast(nome_municipio as string) nome_municipio,
    safe_cast(cargo as string) cargo,
    safe_cast(data as date) data,
    safe_cast(data_referencia as string) data_referencia,
    safe_cast(instituto as string) instituto,
    safe_cast(contratante as string) contratante,
    safe_cast(orgao_registro as string) orgao_registro,
    safe_cast(numero_registro as string) numero_registro,
    safe_cast(quantidade_entrevistas as float64) quantidade_entrevistas,
    safe_cast(margem_mais as float64) margem_mais,
    safe_cast(margem_menos as float64) margem_menos,
    safe_cast(tipo as string) tipo,
    safe_cast(turno as int64) turno,
    safe_cast(tipo_voto as string) tipo_voto,
    safe_cast(id_cenario as string) id_cenario,
    safe_cast(descricao_cenario as string) descricao_cenario,
    safe_cast(id_candidato_poder360 as string) id_candidato_poder360,
    safe_cast(nome_candidato as string) nome_candidato,
    safe_cast(sigla_partido as string) sigla_partido,
    safe_cast(condicao as int64) condicao,
    safe_cast(percentual as float64) percentual
from {{ set_datalake_project("br_poder360_pesquisas_staging.microdados") }} as t
