---
version: 2
models:
  - name: br_ibge_ipca15__mes_brasil
    description: Inflação - Índice Nacional de Preços ao Consumidor Amplo 15 - IPCA15
      - Índice Geral para Brasil (a partir de maio/2000)
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [ano, mes]
      - not_null_proportion_multiple_columns:
          at_least: 0.50
    columns:
      - name: ano
        description: Ano
      - name: mes
        description: Mês
      - name: indice
        description: Número índice (dez 1993 = 100)
      - name: variacao_mensal
        description: Variação percentual mensal
      - name: variacao_trimestral
        description: Variação percentual trimestral
      - name: variacao_semestral
        description: Variação percentual semestral
      - name: variacao_anual
        description: Variação percentual anual
      - name: variacao_doze_meses
        description: Variação percentual doze meses
  - name: br_ibge_ipca15__mes_categoria_brasil
    description: Tabela com as variações da inflação (IPCA15) e peso dos produtos
      e serviços na cesta de inflação do IBGE (a partir de fevereiro/2020)
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [ano, mes, id_categoria]
      - not_null_proportion_multiple_columns:
          at_least: 0.50
    columns:
      - name: ano
        description: Ano
      - name: mes
        description: Mes
      - name: id_categoria
        description: Código identificador grupo para criação de estrutura hierárquica
      - name: categoria
        description: Descrição da categoria
      - name: peso_mensal
        description: Peso percentual mensal do item
      - name: variacao_mensal
        description: Variação percentual mensal
      - name: variacao_anual
        description: Variação percentual acumulada no ano
      - name: variacao_doze_meses
        description: Variação percentual acumulada em doze meses
  - name: br_ibge_ipca15__mes_categoria_municipio
    description: Tabela com as variações da inflação (IPCA15) e peso dos produtos
      e serviços na cesta de inflação do IBGE para municípios selecionados onde a
      pesquisa é realizada (a partir de fevereiro/2020)
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [ano, mes, id_categoria, id_municipio]
      - not_null_proportion_multiple_columns:
          at_least: 0.50
    columns:
      - name: ano
        description: Ano
      - name: mes
        description: Mes
      - name: id_municipio
        description: ID do Município IBGE - 7 Dígitos
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__municipio')
              field: id_municipio
      - name: sigla_uf
        description: Sigla da Unidade da Federação
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__uf')
              field: sigla
      - name: id_categoria
        description: Código identificador grupo para criação de estrutura hierárquica
      - name: categoria
        description: Descrição da categoria
      - name: peso_mensal
        description: Peso percentual mensal do item
      - name: variacao_mensal
        description: Variação percentual mensal
      - name: variacao_anual
        description: Variação percentual acumulada no ano
      - name: variacao_doze_meses
        description: Variação percentual acumulada em doze meses
  - name: br_ibge_ipca15__mes_categoria_rm
    description: Tabela com as variações da inflação (IPCA15) e peso dos produtos
      e serviços na cesta de inflação do IBGE para regiões metropolitanas selecionados
      onde a pesquisa é realizada (a partir de fevereiro/2020)
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - ano
            - mes
            - regiao_metropolitana
            - id_categoria
      - not_null_proportion_multiple_columns:
          at_least: 0.50
    columns:
      - name: ano
        description: Ano
      - name: mes
        description: Mes
      - name: regiao_metropolitana
        description: Região Metropolitana
      - name: sigla_uf
        description: Sigla da Unidade da Federação
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__uf')
              field: sigla
      - name: id_categoria
        description: Código identificador grupo para criação de estrutura hierárquica
      - name: categoria
        description: Descrição da categoria
      - name: peso_mensal
        description: Peso percentual mensal do item
      - name: variacao_mensal
        description: Variação percentual mensal
      - name: variacao_anual
        description: Variação percentual acumulada no ano
      - name: variacao_doze_meses
        description: Variação percentual acumulada em doze meses
