---
version: 2
models:
  - name: world_oceanos_mapeamento__historico_jurados
    description: A tabela contém informações sobre a participação dos jurados ano
      a ano, incluindo dados demográficos, o tipo de obra avaliada e se participaram
      da seleção dos livros finalistas.
    columns:
      - name: ano
        description: Ano
      - name: nome
        description: Nome
      - name: nome_pais
        description: Nome do País
      - name: sigla_uf
        description: Sigla da UF
      - name: nome_municipio_origem
        description: Nome do Município de Origem do Inscrito
      - name: genero
        description: Gênero
      - name: ocupacao
        description: Ocupação
      - name: instituicao
        description: Instituição
      - name: categoria
        description: Categoria avalidada pelo jurado
      - name: indicador_juri_intermediario
        description: Indica se o jurado fez parte do Júri Intermediário
      - name: indicador_juri_final
        description: Indica se o jurado fez parte do Júri Final
  - name: world_oceanos_mapeamento__historico_inscritos
    description: A tabela apresenta informações sobre os livros inscritos a cada ano
      no prêmio, incluindo detalhes sobre autores e editoras.
    columns:
      - name: ano
        description: Ano
      - name: id_inscrito
        description: Código de identificação da inscrição
      - name: responsavel
        description: Tipo de responsável pela inscrição
      - name: nome_responsavel
        description: Nome do responsável pela inscrição
      - name: titulo_livro
        description: Título da Obra
      - name: isbn
        description: International Standard Book Number
      - name: genero_livro
        description: Categoria/Gênero Literário
      - name: nome_pais_primeira_edicao
        description: País da primeira edição
      - name: tipo_publicacao
        description: Tipo da Publicação
      - name: autor_nome
        description: Nome
      - name: autor_genero
        description: Gênero
      - name: autor_idade
        description: Idade
      - name: autor_nome_pais
        description: País
      - name: autor_nacionalidade
        description: Nacionalidade
      - name: autor_indicador_atividade_economica_principal
        description: Indica se a escrita literária é a ativade econômica principal
          do autor
      - name: autor_educacao_formal
        description: Grau de educação formal do autor
      - name: autor_indicador_publicacao_outras_obras
        description: Indica se o autor já publicou outras obras
      - name: autor_quantidade_obras_publicadas
        description: Quantidade de obras publicadas pelo autor
      - name: editora_nome
        description: Nome da Editora
      - name: editora_pais_origem
        description: País de origem da Editora
      - name: editora_local_sede
        description: Local/Locais de Sede da Editora
      - name: editora_ano_criacao
        description: Ano de criação da Editora
      - name: editora_linha_predominante
        description: Linha/Linhas predomianantes
      - name: editora_canal_distribuicao
        description: Canal/Canais de distribuição e comercialização
      - name: editora_tiragem_edicao
        description: Tiragem da Edição
      - name: editora_financiamento_edicao
        description: Modo de Financiamento da Edição
      - name: editora_site
        description: Site da Editora
      - name: indicador_outras_edicoes
        description: Indica se a obra possui outra edições
      - name: outras_edicoes_nome_editora
        description: Nome da Editora, no caso da existência de outras edições
      - name: outras_edicoes_ano_publicacao
        description: Ano da publicação, no caso da existência de outras publicações
      - name: outras_edicoes_nome_pais
        description: País da edição, no caso da existência de outras edições
      - name: indicador_semifinalista
        description: Indica se a Obra foi semifinalista do prêmio
      - name: indicador_finalista
        description: Indica se a Obra foi finalsita do prêmio
      - name: indicador_vencedor
        description: Indica se a Obra foi vencedora do prêmio
  - name: world_oceanos_mapeamento__mapeamento
    description: Mapeamento Oceanos
    columns:
      - name: id
        description: Id
        tests:
          - relationships:
              to: ref('world_oceanos_mapeamento__historico_inscritos')
              field: id_inscrito
      - name: titulo
        description: Título do livro.
      - name: genero_literario
        description: Gênero literário.
      - name: outros_generos_literarios
        description: Outros gêneros literários.
      - name: registro_linguistico
        description: Registro linguístico.
      - name: tematica
        description: Temática.
      - name: espaco_representacao
        description: Espaço de representação.
      - name: ambiente_predominante
        description: Ambiente predominante.
      - name: temporalidade
        description: Temporalidade.
      - name: foco_narrativo
        description: Foco narrativo.
      - name: tipo_narrador
        description: Tipo de narrador.
      - name: procedimento_expressivo
        description: Procedimento expressivo.
      - name: genero_dramaturgico
        description: Gênero dramatúrgico.
      - name: interprete
        description: Intérprete.
      - name: narrador
        description: Narrador.
      - name: formato_cena
        description: Formato de cena.
      - name: estetica_cenografica
        description: Estética cenográfica.
      - name: tipo_localizacao
        description: Tipo de localização
      - name: localizacao_geografica
        description: Localização geográfica
