-- Reads staging rows built by models/world_dasanaike_sage/code/ (download.py ->
-- clean.py -> upload.py).
{{
    config(
        schema="world_dasanaike_sage",
        alias="election_returns",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 1948, "end": 2031, "interval": 1},
        },
        cluster_by=["country_iso3_code"],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(country_iso3_code as string) country_iso3_code,
    safe_cast(country as string) country,
    safe_cast(name_1 as string) name_1,
    safe_cast(name_1_b as string) name_1_b,
    safe_cast(name_1_c as string) name_1_c,
    safe_cast(name_1_d as string) name_1_d,
    safe_cast(name_1_imp as string) name_1_imp,
    safe_cast(name_1_raw as string) name_1_raw,
    safe_cast(name_2 as string) name_2,
    safe_cast(name_2_b as string) name_2_b,
    safe_cast(name_2_c as string) name_2_c,
    safe_cast(name_2_d as string) name_2_d,
    safe_cast(name_2_imp as string) name_2_imp,
    safe_cast(name_3 as string) name_3,
    safe_cast(name_3_b as string) name_3_b,
    safe_cast(name_3_c as string) name_3_c,
    safe_cast(name_3_imp as string) name_3_imp,
    safe_cast(name_4 as string) name_4,
    safe_cast(name_4_b as string) name_4_b,
    safe_cast(name_5 as string) name_5,
    safe_cast(name_5_b as string) name_5_b,
    safe_cast(name_5_c as string) name_5_c,
    safe_cast(name_6 as string) name_6,
    safe_cast(name_6_b as string) name_6_b,
    safe_cast(name_7 as string) name_7,
    safe_cast(name_7_b as string) name_7_b,
    safe_cast(latitude as float64) latitude,
    safe_cast(longitude as float64) longitude,
    safe_cast(election_type as string) election_type,
    safe_cast(round as string) round,
    safe_cast(month as string) month,
    safe_cast(special_type as string) special_type,
    safe_cast(special_type_b as string) special_type_b,
    safe_cast(special_type_c as string) special_type_c,
    safe_cast(party as string) party,
    safe_cast(party_b as string) party_b,
    safe_cast(party_c as string) party_c,
    safe_cast(party_d as string) party_d,
    safe_cast(candidate as string) candidate,
    safe_cast(candidate_b as string) candidate_b,
    safe_cast(candidate_c as string) candidate_c,
    safe_cast(coalition as string) coalition,
    safe_cast(partyfacts_id as string) partyfacts_id,
    safe_cast(partyfacts_name as string) partyfacts_name,
    safe_cast(match_confidence as string) match_confidence,
    safe_cast(votes as float64) votes,
    safe_cast(total_votes as float64) total_votes,
    safe_cast(registered_voters as float64) registered_voters,
    safe_cast(eligible_voters as float64) eligible_voters,
    safe_cast(turnout_registered as float64) turnout_registered,
    safe_cast(turnout_eligible as float64) turnout_eligible,
    safe_cast(geometry_type as string) geometry_type,
    safe_cast(geometry_type_b as string) geometry_type_b,
    safe_cast(geometry_level as string) geometry_level,
    safe_cast(geocode_duplicates as int64) geocode_duplicates
from {{ set_datalake_project("world_dasanaike_sage_staging.election_returns") }} as t
