{{
    config(
        schema="us_dot_bts_ontime",
        alias="flight",
        materialized="table",
        partition_by={
            "field": "year",
            "data_type": "int64",
            "range": {"start": 1987, "end": 2031, "interval": 1},
        },
        cluster_by=["reporting_carrier", "origin", "destination"],
    )
}}


select
    safe_cast(year as int64) year,
    safe_cast(quarter as int64) quarter,
    safe_cast(month as int64) month,
    safe_cast(day_of_month as int64) day_of_month,
    safe_cast(day_of_week as string) day_of_week,
    safe_cast(flight_date as date) flight_date,
    safe_cast(reporting_carrier as string) reporting_carrier,
    safe_cast(reporting_carrier_airline_id as string) reporting_carrier_airline_id,
    safe_cast(reporting_carrier_iata_code as string) reporting_carrier_iata_code,
    safe_cast(tail_number as string) tail_number,
    safe_cast(flight_number as string) flight_number,
    safe_cast(origin_airport_id as string) origin_airport_id,
    safe_cast(origin_airport_seq_id as string) origin_airport_seq_id,
    safe_cast(origin_city_market_id as string) origin_city_market_id,
    safe_cast(origin as string) origin,
    safe_cast(origin_city_name as string) origin_city_name,
    safe_cast(origin_state_abbreviation as string) origin_state_abbreviation,
    safe_cast(origin_state_fips as string) origin_state_fips,
    safe_cast(origin_state_name as string) origin_state_name,
    safe_cast(origin_world_area_code as string) origin_world_area_code,
    safe_cast(destination_airport_id as string) destination_airport_id,
    safe_cast(destination_airport_seq_id as string) destination_airport_seq_id,
    safe_cast(destination_city_market_id as string) destination_city_market_id,
    safe_cast(destination as string) destination,
    safe_cast(destination_city_name as string) destination_city_name,
    safe_cast(destination_state_abbreviation as string) destination_state_abbreviation,
    safe_cast(destination_state_fips as string) destination_state_fips,
    safe_cast(destination_state_name as string) destination_state_name,
    safe_cast(destination_world_area_code as string) destination_world_area_code,
    safe_cast(scheduled_departure_time as string) scheduled_departure_time,
    safe_cast(scheduled_departure_time_local as time) scheduled_departure_time_local,
    safe_cast(
        scheduled_departure_datetime_local as datetime
    ) scheduled_departure_datetime_local,
    safe_cast(departure_time as string) departure_time,
    safe_cast(departure_time_local as time) departure_time_local,
    safe_cast(departure_delay as float64) departure_delay,
    safe_cast(departure_delay_minutes as float64) departure_delay_minutes,
    safe_cast(departure_delay_15min as string) departure_delay_15min,
    safe_cast(departure_delay_group as string) departure_delay_group,
    safe_cast(scheduled_departure_time_block as string) scheduled_departure_time_block,
    safe_cast(taxi_out as float64) taxi_out,
    safe_cast(wheels_off_time as string) wheels_off_time,
    safe_cast(wheels_on_time as string) wheels_on_time,
    safe_cast(taxi_in as float64) taxi_in,
    safe_cast(scheduled_arrival_time as string) scheduled_arrival_time,
    safe_cast(scheduled_arrival_time_local as time) scheduled_arrival_time_local,
    safe_cast(arrival_time as string) arrival_time,
    safe_cast(arrival_time_local as time) arrival_time_local,
    safe_cast(arrival_delay as float64) arrival_delay,
    safe_cast(arrival_delay_minutes as float64) arrival_delay_minutes,
    safe_cast(arrival_delay_15min as string) arrival_delay_15min,
    safe_cast(arrival_delay_group as string) arrival_delay_group,
    safe_cast(scheduled_arrival_time_block as string) scheduled_arrival_time_block,
    safe_cast(cancelled as string) cancelled,
    safe_cast(cancellation_code as string) cancellation_code,
    safe_cast(diverted as string) diverted,
    safe_cast(scheduled_elapsed_time as float64) scheduled_elapsed_time,
    safe_cast(actual_elapsed_time as float64) actual_elapsed_time,
    safe_cast(air_time as float64) air_time,
    safe_cast(flights as int64) flights,
    safe_cast(distance as float64) distance,
    safe_cast(distance_group as string) distance_group,
    safe_cast(carrier_delay as float64) carrier_delay,
    safe_cast(weather_delay as float64) weather_delay,
    safe_cast(national_air_system_delay as float64) national_air_system_delay,
    safe_cast(security_delay as float64) security_delay,
    safe_cast(late_aircraft_delay as float64) late_aircraft_delay,
    safe_cast(first_departure_time as string) first_departure_time,
    safe_cast(total_additional_gate_time as float64) total_additional_gate_time,
    safe_cast(longest_additional_gate_time as float64) longest_additional_gate_time,
    safe_cast(diverted_airport_landings as int64) diverted_airport_landings,
    safe_cast(diverted_reached_destination as string) diverted_reached_destination,
    safe_cast(diverted_actual_elapsed_time as float64) diverted_actual_elapsed_time,
    safe_cast(diverted_arrival_delay as float64) diverted_arrival_delay,
    safe_cast(diverted_distance as float64) diverted_distance,
    safe_cast(diversion_1_airport as string) diversion_1_airport,
    safe_cast(diversion_1_airport_id as string) diversion_1_airport_id,
    safe_cast(diversion_1_airport_seq_id as string) diversion_1_airport_seq_id,
    safe_cast(diversion_1_wheels_on_time as string) diversion_1_wheels_on_time,
    safe_cast(diversion_1_total_gate_time as float64) diversion_1_total_gate_time,
    safe_cast(diversion_1_longest_gate_time as float64) diversion_1_longest_gate_time,
    safe_cast(diversion_1_wheels_off_time as string) diversion_1_wheels_off_time,
    safe_cast(diversion_1_tail_number as string) diversion_1_tail_number,
    safe_cast(diversion_2_airport as string) diversion_2_airport,
    safe_cast(diversion_2_airport_id as string) diversion_2_airport_id,
    safe_cast(diversion_2_airport_seq_id as string) diversion_2_airport_seq_id,
    safe_cast(diversion_2_wheels_on_time as string) diversion_2_wheels_on_time,
    safe_cast(diversion_2_total_gate_time as float64) diversion_2_total_gate_time,
    safe_cast(diversion_2_longest_gate_time as float64) diversion_2_longest_gate_time,
    safe_cast(diversion_2_wheels_off_time as string) diversion_2_wheels_off_time,
    safe_cast(diversion_2_tail_number as string) diversion_2_tail_number,
    safe_cast(diversion_3_airport as string) diversion_3_airport,
    safe_cast(diversion_3_airport_id as string) diversion_3_airport_id,
    safe_cast(diversion_3_airport_seq_id as string) diversion_3_airport_seq_id,
    safe_cast(diversion_3_wheels_on_time as string) diversion_3_wheels_on_time,
    safe_cast(diversion_3_total_gate_time as float64) diversion_3_total_gate_time,
    safe_cast(diversion_3_longest_gate_time as float64) diversion_3_longest_gate_time,
    safe_cast(diversion_3_wheels_off_time as string) diversion_3_wheels_off_time,
    safe_cast(diversion_3_tail_number as string) diversion_3_tail_number,
    safe_cast(diversion_4_airport as string) diversion_4_airport,
    safe_cast(diversion_4_airport_id as string) diversion_4_airport_id,
    safe_cast(diversion_4_airport_seq_id as string) diversion_4_airport_seq_id,
    safe_cast(diversion_4_wheels_on_time as string) diversion_4_wheels_on_time,
    safe_cast(diversion_4_total_gate_time as float64) diversion_4_total_gate_time,
    safe_cast(diversion_4_longest_gate_time as float64) diversion_4_longest_gate_time,
    safe_cast(diversion_4_wheels_off_time as string) diversion_4_wheels_off_time,
    safe_cast(diversion_4_tail_number as string) diversion_4_tail_number,
    safe_cast(diversion_5_airport as string) diversion_5_airport,
    safe_cast(diversion_5_airport_id as string) diversion_5_airport_id,
    safe_cast(diversion_5_airport_seq_id as string) diversion_5_airport_seq_id,
    safe_cast(diversion_5_wheels_on_time as string) diversion_5_wheels_on_time,
    safe_cast(diversion_5_total_gate_time as float64) diversion_5_total_gate_time,
    safe_cast(diversion_5_longest_gate_time as float64) diversion_5_longest_gate_time,
    safe_cast(diversion_5_wheels_off_time as string) diversion_5_wheels_off_time,
    safe_cast(diversion_5_tail_number as string) diversion_5_tail_number
from {{ set_datalake_project("us_dot_bts_ontime_staging.flight") }} as t
