---
version: 2
models:
  - name: br_ibge_ppm__producao_pecuaria
    description: Dados de pecuária contendo o número de vacas ordenhadas e ovinos
      tosquiados.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - [ano, sigla_uf, id_municipio, produto]
      - not_null_proportion_multiple_columns:
          at_least: 0.05
    columns:
      - name: ano
        description: Ano
        tests:
          - relationships:
              to: ref('br_bd_diretorios_data_tempo__ano')
              field: ano.ano
      - name: sigla_uf
        description: Sigla da Unidade da Federação
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__uf')
              field: sigla
      - name: id_municipio
        description: ID Município IBGE 7 dígitos
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__municipio')
              field: id_municipio
      - name: ovinos_tosquiados
        description: Número de ovinos tosquiados
      - name: vacas_ordenhadas
        description: Número de vacas ordenhadas
  - name: br_ibge_ppm__efetivo_rebanhos
    description: Efetivo dos rebanhos (cabeça), por tipo de rebanho.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [insert unique keys here]
      - not_null_proportion_multiple_columns:
          at_least: 0.05
    columns:
      - name: ano
        description: Ano
        tests:
          - relationships:
              to: ref('br_bd_diretorios_data_tempo__ano')
              field: ano.ano
      - name: sigla_uf
        description: Sigla da Unidade da Federação
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__uf')
              field: sigla
      - name: id_municipio
        description: ID Município IBGE 7 dígitos
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__municipio')
              field: id_municipio
      - name: tipo_rebanho
        description: Tipo de rebanho
      - name: quantidade
        description: Quantidade de animais
  - name: br_ibge_ppm__producao_origem_animal
    description: Produção de origem animal, por tipo de produto e valor da produção.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [insert unique keys here]
      - not_null_proportion_multiple_columns:
          at_least: 0.05
    columns:
      - name: ano
        description: Ano
        tests:
          - relationships:
              to: ref('br_bd_diretorios_data_tempo__ano')
              field: ano.ano
      - name: sigla_uf
        description: Sigla da Unidade da Federação
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__uf')
              field: sigla
      - name: id_municipio
        description: ID Município IBGE 7 dígitos
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__municipio')
              field: id_municipio
      - name: produto
        description: Produto
      - name: unidade
        description: Unidade de medida do produto
      - name: quantidade
        description: Quantidade da produção
      - name: valor
        description: Valor da produção
  - name: br_ibge_ppm__producao_aquicultura
    description: Produção da aquicultura, de acordo com a quantidade produzida em
      quilogramas e valor da produção em mil reais.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [insert unique keys here]
      - not_null_proportion_multiple_columns:
          at_least: 0.05
    columns:
      - name: ano
        description: Ano
        tests:
          - relationships:
              to: ref('br_bd_diretorios_data_tempo__ano')
              field: ano.ano
      - name: sigla_uf
        description: Sigla da Unidade da Federação
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__uf')
              field: sigla
      - name: id_municipio
        description: ID Município IBGE 7 dígitos
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__municipio')
              field: id_municipio
      - name: produto
        description: Produto
      - name: quantidade
        description: Quantidade da produção
      - name: valor
        description: Valor da produção
