"""Column spec for br_cgu_despesas_publicas.favorecido — single source of truth.

Tuple: (bd_name, type, source_header, pt, en, es, unit, directory_column,
        has_sensitive_data, observations_pt)

`source_header` is None for the two columns derived by splitting the period
column, which in THIS product is "MM/AAAA" — the reverse of the "AAAA/MM" used
by despesas-execucao. Copying the execucao parser here would silently swap the
year and the month.
"""

SPEC = [
    (
        "ano",
        "INT64",
        None,
        "Ano do lançamento do recebimento",
        "Year the receipt was recorded",
        "Año del registro del cobro",
        "year",
        "br_bd_diretorios_data_tempo.ano:ano",
        "no",
        "Coluna de partição, derivada de 'Ano e mês do lançamento' (formato MM/AAAA)",
    ),
    (
        "mes",
        "INT64",
        None,
        "Mês do lançamento do recebimento",
        "Month the receipt was recorded",
        "Mes del registro del cobro",
        "month",
        "br_bd_diretorios_data_tempo.mes:mes",
        "no",
        "Coluna de partição, derivada de 'Ano e mês do lançamento' (formato MM/AAAA)",
    ),
    (
        "id_favorecido",
        "STRING",
        "Código Favorecido",
        "Código do favorecido: CNPJ para pessoa jurídica, CPF parcialmente mascarado para pessoa física",
        "Recipient code: CNPJ for legal entities, partially masked CPF for individuals",
        "Código del beneficiario: CNPJ para persona jurídica, CPF parcialmente enmascarado para persona física",
        "",
        "",
        "yes",
        "A fonte publica o CPF de pessoas físicas mascarado no formato ***.123.456-**, expondo apenas os seis dígitos centrais. Códigos de favorecidos no exterior e de unidades gestoras seguem outros formatos e não têm 14 caracteres",
    ),
    (
        "nome_favorecido",
        "STRING",
        "Nome Favorecido",
        "Nome ou razão social do favorecido do pagamento",
        "Name or corporate name of the payment recipient",
        "Nombre o razón social del beneficiario del pago",
        "",
        "",
        "yes",
        "Publicado por extenso pela fonte, inclusive para pessoas físicas",
    ),
    (
        "sigla_uf",
        "STRING",
        "Sigla UF",
        "Sigla da unidade da federação do favorecido",
        "Abbreviation of the recipient's federative unit",
        "Sigla de la unidad federativa del beneficiario",
        "",
        "br_bd_diretorios_brasil.uf:sigla",
        "no",
        "Assume os sentinelas 'EX' para favorecidos no exterior e '-1' quando a UF não é informada, que juntos somam cerca de 0,6% das linhas e não constam do diretório de UFs",
    ),
    (
        "nome_municipio",
        "STRING",
        "Nome Município",
        "Nome do município do favorecido",
        "Name of the recipient's municipality",
        "Nombre del municipio del beneficiario",
        "",
        "",
        "no",
        "A fonte publica o nome, não o código IBGE, então a coluna não é ligada ao diretório de municípios. Assume 'Exterior' quando a UF é 'EX' e 'Sem informação' quando a UF é '-1'",
    ),
    (
        "id_orgao_superior",
        "STRING",
        "Código Órgão Superior",
        "Código do órgão superior pagador, em geral um ministério",
        "Code of the paying superior agency, usually a ministry",
        "Código del órgano superior pagador, generalmente un ministerio",
        "",
        "",
        "no",
        "",
    ),
    (
        "nome_orgao_superior",
        "STRING",
        "Nome Órgão Superior",
        "Nome do órgão superior pagador",
        "Name of the paying superior agency",
        "Nombre del órgano superior pagador",
        "",
        "",
        "no",
        "",
    ),
    (
        "id_orgao",
        "STRING",
        "Código Órgão",
        "Código do órgão pagador",
        "Code of the paying agency",
        "Código del órgano pagador",
        "",
        "",
        "no",
        "",
    ),
    (
        "nome_orgao",
        "STRING",
        "Nome Órgão",
        "Nome do órgão pagador",
        "Name of the paying agency",
        "Nombre del órgano pagador",
        "",
        "",
        "no",
        "",
    ),
    (
        "id_unidade_gestora",
        "STRING",
        "Código Unidade Gestora",
        "Código da unidade gestora que efetuou o pagamento",
        "Code of the managing unit that made the payment",
        "Código de la unidad gestora que efectuó el pago",
        "",
        "",
        "no",
        "",
    ),
    (
        "nome_unidade_gestora",
        "STRING",
        "Nome Unidade Gestora",
        "Nome da unidade gestora que efetuou o pagamento",
        "Name of the managing unit that made the payment",
        "Nombre de la unidad gestora que efectuó el pago",
        "",
        "",
        "no",
        "",
    ),
    (
        "valor_recebido",
        "FLOAT64",
        "Valor Recebido",
        "Valor recebido pelo favorecido no mês, em reais correntes",
        "Amount received by the recipient in the month, in current Brazilian reais",
        "Valor recibido por el beneficiario en el mes, en reales corrientes",
        "brl",
        "",
        "no",
        "A fonte publica quatro casas decimais e admite valores negativos, que correspondem a estornos e devoluções",
    ),
]
