"""Column spec for br_cgu_despesas_publicas.execucao — single source of truth.

Tuple: (bd_name, type, source_header, pt, en, es, unit, directory_column, observations_pt)
`source_header` is None for the two columns derived by splitting "Ano e mês do lançamento".
"""

SPEC = [
    (
        "ano",
        "INT64",
        None,
        "Ano do lançamento da despesa",
        "Year the expenditure was recorded",
        "Año del registro del gasto",
        "year",
        "br_bd_diretorios_data_tempo.ano:ano",
        "Coluna de partição, derivada de 'Ano e mês do lançamento' (formato AAAA/MM)",
    ),
    (
        "mes",
        "INT64",
        None,
        "Mês do lançamento da despesa",
        "Month the expenditure was recorded",
        "Mes del registro del gasto",
        "month",
        "br_bd_diretorios_data_tempo.mes:mes",
        "Coluna de partição, derivada de 'Ano e mês do lançamento' (formato AAAA/MM)",
    ),
    (
        "id_orgao_superior",
        "STRING",
        "Código Órgão Superior",
        "Código do órgão superior responsável pela despesa, em geral um ministério",
        "Code of the superior agency responsible for the expenditure, usually a ministry",
        "Código del órgano superior responsable del gasto, generalmente un ministerio",
        "",
        "",
        "",
    ),
    (
        "nome_orgao_superior",
        "STRING",
        "Nome Órgão Superior",
        "Nome do órgão superior responsável pela despesa",
        "Name of the superior agency responsible for the expenditure",
        "Nombre del órgano superior responsable del gasto",
        "",
        "",
        "",
    ),
    (
        "id_orgao_subordinado",
        "STRING",
        "Código Órgão Subordinado",
        "Código do órgão subordinado responsável pela despesa",
        "Code of the subordinate agency responsible for the expenditure",
        "Código del órgano subordinado responsable del gasto",
        "",
        "",
        "",
    ),
    (
        "nome_orgao_subordinado",
        "STRING",
        "Nome Órgão Subordinado",
        "Nome do órgão subordinado responsável pela despesa",
        "Name of the subordinate agency responsible for the expenditure",
        "Nombre del órgano subordinado responsable del gasto",
        "",
        "",
        "",
    ),
    (
        "id_unidade_gestora",
        "STRING",
        "Código Unidade Gestora",
        "Código da unidade gestora, a unidade administrativa que executa o gasto no SIAFI",
        "Code of the managing unit, the administrative unit that executes the spending in SIAFI",
        "Código de la unidad gestora, la unidad administrativa que ejecuta el gasto en SIAFI",
        "",
        "",
        "Assume o sentinela '-3' quando a unidade gestora não é identificada; o nome correspondente é 'Inválido'",
    ),
    (
        "nome_unidade_gestora",
        "STRING",
        "Nome Unidade Gestora",
        "Nome da unidade gestora",
        "Name of the managing unit",
        "Nombre de la unidad gestora",
        "",
        "",
        "Assume 'Inválido' quando a unidade gestora não é identificada",
    ),
    (
        "id_gestao",
        "STRING",
        "Código Gestão",
        "Código da gestão, que identifica o conjunto orçamentário-financeiro a que a unidade gestora pertence",
        "Code of the management unit, identifying the budgetary-financial set the managing unit belongs to",
        "Código de la gestión, que identifica el conjunto presupuestario-financiero de la unidad gestora",
        "",
        "",
        "",
    ),
    (
        "nome_gestao",
        "STRING",
        "Nome Gestão",
        "Nome da gestão",
        "Name of the management unit",
        "Nombre de la gestión",
        "",
        "",
        "",
    ),
    (
        "id_unidade_orcamentaria",
        "STRING",
        "Código Unidade Orçamentária",
        "Código da unidade orçamentária, menor nível da estrutura administrativa a que se aloca a dotação",
        "Code of the budget unit, the lowest administrative level to which the appropriation is allocated",
        "Código de la unidad presupuestaria, el nivel administrativo más bajo al que se asigna la dotación",
        "",
        "",
        "",
    ),
    (
        "nome_unidade_orcamentaria",
        "STRING",
        "Nome Unidade Orçamentária",
        "Nome da unidade orçamentária",
        "Name of the budget unit",
        "Nombre de la unidad presupuestaria",
        "",
        "",
        "",
    ),
    (
        "id_funcao",
        "STRING",
        "Código Função",
        "Código da função de governo em que a despesa foi classificada",
        "Code of the government function under which the expenditure was classified",
        "Código de la función de gobierno en que se clasificó el gasto",
        "",
        "",
        "",
    ),
    (
        "nome_funcao",
        "STRING",
        "Nome Função",
        "Nome da função de governo em que a despesa foi classificada",
        "Name of the government function under which the expenditure was classified",
        "Nombre de la función de gobierno en que se clasificó el gasto",
        "",
        "",
        "",
    ),
    (
        "id_subfuncao",
        "STRING",
        "Código Subfução",
        "Código da subfunção, que detalha a função em áreas de atuação mais específicas",
        "Code of the subfunction, which breaks the function into more specific areas of action",
        "Código de la subfunción, que detalla la función en áreas más específicas",
        "",
        "",
        "O cabeçalho da fonte traz a grafia incorreta 'Código Subfução'",
    ),
    (
        "nome_subfuncao",
        "STRING",
        "Nome Subfunção",
        "Nome da subfunção",
        "Name of the subfunction",
        "Nombre de la subfunción",
        "",
        "",
        "",
    ),
    (
        "id_programa_orcamentario",
        "STRING",
        "Código Programa Orçamentário",
        "Código do programa orçamentário, instrumento do plano plurianual que articula ações para um objetivo",
        "Code of the budget programme, the multi-year plan instrument grouping actions towards an objective",
        "Código del programa presupuestario, instrumento del plan plurianual",
        "",
        "",
        "",
    ),
    (
        "nome_programa_orcamentario",
        "STRING",
        "Nome Programa Orçamentário",
        "Nome do programa orçamentário",
        "Name of the budget programme",
        "Nombre del programa presupuestario",
        "",
        "",
        "",
    ),
    (
        "id_acao",
        "STRING",
        "Código Ação",
        "Código da ação orçamentária, menor unidade de programação que gera bem ou serviço",
        "Code of the budget action, the smallest programming unit delivering a good or service",
        "Código de la acción presupuestaria",
        "",
        "",
        "Alfanumérico: assume valores como '20RL' além de códigos puramente numéricos",
    ),
    (
        "nome_acao",
        "STRING",
        "Nome Ação",
        "Nome da ação orçamentária",
        "Name of the budget action",
        "Nombre de la acción presupuestaria",
        "",
        "",
        "",
    ),
    (
        "id_plano_orcamentario",
        "STRING",
        "Código Plano Orçamentário",
        "Código do plano orçamentário, subdivisão da ação usada no detalhamento gerencial da despesa",
        "Code of the budget plan, a subdivision of the action used in the managerial breakdown of the expenditure",
        "Código del plan presupuestario, subdivisión de la acción",
        "",
        "",
        "",
    ),
    (
        "nome_plano_orcamentario",
        "STRING",
        "Plano Orçamentário",
        "Nome do plano orçamentário",
        "Name of the budget plan",
        "Nombre del plan presupuestario",
        "",
        "",
        "",
    ),
    (
        "id_programa_governo",
        "STRING",
        "Código Programa Governo",
        "Código do programa de governo associado à despesa",
        "Code of the government programme associated with the expenditure",
        "Código del programa de gobierno asociado al gasto",
        "",
        "",
        "Assume o sentinela '-1' quando não há programa de governo associado; '00' predomina",
    ),
    (
        "nome_programa_governo",
        "STRING",
        "Nome Programa Governo",
        "Nome do programa de governo associado à despesa",
        "Name of the government programme associated with the expenditure",
        "Nombre del programa de gobierno asociado al gasto",
        "",
        "",
        "Quase sempre 'Sem informação'; valores reais são raros",
    ),
    (
        "sigla_uf",
        "STRING",
        "UF",
        "Sigla da unidade da federação do localizador da despesa",
        "Abbreviation of the federative unit in the expenditure localiser",
        "Sigla de la unidad federativa del localizador del gasto",
        "",
        "br_bd_diretorios_brasil.uf:sigla",
        "Vazia em cerca de dois terços das linhas: só é preenchida quando o localizador da ação tem recorte estadual",
    ),
    (
        "nome_municipio",
        "STRING",
        "Município",
        "Nome do município do localizador da despesa",
        "Name of the municipality in the expenditure localiser",
        "Nombre del municipio del localizador del gasto",
        "",
        "",
        "Vazia em cerca de 99% das linhas. A fonte publica o nome, não o código IBGE, então a coluna não é ligada ao diretório de municípios",
    ),
    (
        "id_subtitulo",
        "STRING",
        "Código Subtítulo",
        "Código do subtítulo, que identifica a localização física ou o recorte da ação orçamentária",
        "Code of the subtitle, identifying the physical location or scope of the budget action",
        "Código del subtítulo, que identifica la localización física o el alcance de la acción",
        "",
        "",
        "",
    ),
    (
        "nome_subtitulo",
        "STRING",
        "Nome Subtítulo",
        "Nome do subtítulo",
        "Name of the subtitle",
        "Nombre del subtítulo",
        "",
        "",
        "",
    ),
    (
        "id_localizador",
        "STRING",
        "Código Localizador",
        "Código do localizador do gasto dentro da ação orçamentária",
        "Code of the spending localiser within the budget action",
        "Código del localizador del gasto dentro de la acción",
        "",
        "",
        "",
    ),
    (
        "nome_localizador",
        "STRING",
        "Nome Localizador",
        "Nome do localizador do gasto",
        "Name of the spending localiser",
        "Nombre del localizador del gasto",
        "",
        "",
        "",
    ),
    (
        "sigla_localizador",
        "STRING",
        "Sigla Localizador",
        "Sigla do localizador do gasto",
        "Abbreviation of the spending localiser",
        "Sigla del localizador del gasto",
        "",
        "",
        "Assume o sentinela '-1' em cerca de 99% das linhas",
    ),
    (
        "descricao_complementar_localizador",
        "STRING",
        "Descrição Complementar Localizador",
        "Descrição complementar do localizador do gasto",
        "Supplementary description of the spending localiser",
        "Descripción complementaria del localizador del gasto",
        "",
        "",
        "Assume 'Sem informação' em cerca de 99% das linhas",
    ),
    (
        "id_autor_emenda",
        "STRING",
        "Código Autor Emenda",
        "Código do autor da emenda parlamentar que originou a despesa",
        "Code of the author of the parliamentary amendment that originated the expenditure",
        "Código del autor de la enmienda parlamentaria que originó el gasto",
        "",
        "",
        "Vazia em cerca de 97% das linhas: só é preenchida quando a despesa decorre de emenda parlamentar",
    ),
    (
        "nome_autor_emenda",
        "STRING",
        "Nome Autor Emenda",
        "Nome do autor da emenda parlamentar que originou a despesa",
        "Name of the author of the parliamentary amendment that originated the expenditure",
        "Nombre del autor de la enmienda parlamentaria que originó el gasto",
        "",
        "",
        "Assume 'SEM EMENDA' quando não há emenda e 'Informação do autor não disponível' quando o autor não foi informado",
    ),
    (
        "id_categoria_economica",
        "STRING",
        "Código Categoria Econômica",
        "Código da categoria econômica da despesa, que separa despesas correntes de despesas de capital",
        "Code of the economic category, separating current from capital expenditure",
        "Código de la categoría económica del gasto",
        "",
        "",
        "",
    ),
    (
        "nome_categoria_economica",
        "STRING",
        "Nome Categoria Econômica",
        "Nome da categoria econômica da despesa",
        "Name of the economic category of the expenditure",
        "Nombre de la categoría económica del gasto",
        "",
        "",
        "",
    ),
    (
        "id_grupo_despesa",
        "STRING",
        "Código Grupo de Despesa",
        "Código do grupo de natureza da despesa, por exemplo pessoal e encargos sociais, juros da dívida, investimentos",
        "Code of the expenditure nature group, such as personnel, debt interest or investment",
        "Código del grupo de naturaleza del gasto",
        "",
        "",
        "",
    ),
    (
        "nome_grupo_despesa",
        "STRING",
        "Nome Grupo de Despesa",
        "Nome do grupo de natureza da despesa",
        "Name of the expenditure nature group",
        "Nombre del grupo de naturaleza del gasto",
        "",
        "",
        "",
    ),
    (
        "id_elemento_despesa",
        "STRING",
        "Código Elemento de Despesa",
        "Código do elemento de despesa, que identifica o objeto do gasto",
        "Code of the expenditure element, identifying the object of the spending",
        "Código del elemento de gasto, que identifica el objeto del gasto",
        "",
        "",
        "",
    ),
    (
        "nome_elemento_despesa",
        "STRING",
        "Nome Elemento de Despesa",
        "Nome do elemento de despesa",
        "Name of the expenditure element",
        "Nombre del elemento de gasto",
        "",
        "",
        "",
    ),
    (
        "id_modalidade_despesa",
        "STRING",
        "Código Modalidade da Despesa",
        "Código da modalidade de aplicação, que indica se o gasto é direto ou por transferência a outro ente",
        "Code of the application modality, indicating whether spending is direct or transferred to another entity",
        "Código de la modalidad de aplicación del gasto",
        "",
        "",
        "",
    ),
    (
        "nome_modalidade_despesa",
        "STRING",
        "Modalidade da Despesa",
        "Nome da modalidade de aplicação",
        "Name of the application modality",
        "Nombre de la modalidad de aplicación",
        "",
        "",
        "",
    ),
    (
        "valor_empenhado",
        "FLOAT64",
        "Valor Empenhado (R$)",
        "Valor empenhado no mês, em reais correntes",
        "Amount committed in the month, in current Brazilian reais",
        "Valor comprometido en el mes, en reales corrientes",
        "brl",
        "",
        "",
    ),
    (
        "valor_liquidado",
        "FLOAT64",
        "Valor Liquidado (R$)",
        "Valor liquidado no mês, isto é, reconhecido como devido após a verificação da entrega, em reais correntes",
        "Amount verified as due in the month after delivery is confirmed, in current Brazilian reais",
        "Valor liquidado en el mes, reconocido como debido tras verificar la entrega, en reales corrientes",
        "brl",
        "",
        "",
    ),
    (
        "valor_pago",
        "FLOAT64",
        "Valor Pago (R$)",
        "Valor efetivamente pago no mês, em reais correntes",
        "Amount actually paid in the month, in current Brazilian reais",
        "Valor efectivamente pagado en el mes, en reales corrientes",
        "brl",
        "",
        "",
    ),
    (
        "valor_restos_pagar_inscritos",
        "FLOAT64",
        "Valor Restos a Pagar Inscritos (R$)",
        "Valor inscrito em restos a pagar, isto é, empenhado em exercício anterior e não pago até o seu encerramento, em reais correntes",
        "Amount carried over as unpaid commitments from a previous fiscal year, in current Brazilian reais",
        "Valor inscrito como residuos por pagar de un ejercicio anterior, en reales corrientes",
        "brl",
        "",
        "",
    ),
    (
        "valor_restos_pagar_cancelados",
        "FLOAT64",
        "Valor Restos a Pagar Cancelado (R$)",
        "Valor de restos a pagar cancelado no mês, em reais correntes",
        "Amount of carried-over commitments cancelled in the month, in current Brazilian reais",
        "Valor de residuos por pagar cancelado en el mes, en reales corrientes",
        "brl",
        "",
        "",
    ),
    (
        "valor_restos_pagar_pagos",
        "FLOAT64",
        "Valor Restos a Pagar Pagos (R$)",
        "Valor de restos a pagar efetivamente pago no mês, em reais correntes",
        "Amount of carried-over commitments actually paid in the month, in current Brazilian reais",
        "Valor de residuos por pagar efectivamente pagado en el mes, en reales corrientes",
        "brl",
        "",
        "",
    ),
]
