def renames_afd() -> dict[str, str]:
    return {
        "NU_ANO_CENSO": "ano",
        "NO_CATEGORIA": "localizacao",
        "NO_DEPENDENCIA": "rede",
        "ED_INF_CAT_1": "afd_ei_grupo_1",
        "ED_INF_CAT_2": "afd_ei_grupo_2",
        "ED_INF_CAT_3": "afd_ei_grupo_3",
        "ED_INF_CAT_4": "afd_ei_grupo_4",
        "ED_INF_CAT_5": "afd_ei_grupo_5",
        "FUN_CAT_1": "afd_ef_grupo_1",
        "FUN_CAT_2": "afd_ef_grupo_2",
        "FUN_CAT_3": "afd_ef_grupo_3",
        "FUN_CAT_4": "afd_ef_grupo_4",
        "FUN_CAT_5": "afd_ef_grupo_5",
        "FUN_AI_CAT_1": "afd_ef_anos_iniciais_grupo_1",
        "FUN_AI_CAT_2": "afd_ef_anos_iniciais_grupo_2",
        "FUN_AI_CAT_3": "afd_ef_anos_iniciais_grupo_3",
        "FUN_AI_CAT_4": "afd_ef_anos_iniciais_grupo_4",
        "FUN_AI_CAT_5": "afd_ef_anos_iniciais_grupo_5",
        "FUN_AF_CAT_1": "afd_ef_anos_finais_grupo_1",
        "FUN_AF_CAT_2": "afd_ef_anos_finais_grupo_2",
        "FUN_AF_CAT_3": "afd_ef_anos_finais_grupo_3",
        "FUN_AF_CAT_4": "afd_ef_anos_finais_grupo_4",
        "FUN_AF_CAT_5": "afd_ef_anos_finais_grupo_5",
        "MED_CAT_1": "afd_em_grupo_1",
        "MED_CAT_2": "afd_em_grupo_2",
        "MED_CAT_3": "afd_em_grupo_3",
        "MED_CAT_4": "afd_em_grupo_4",
        "MED_CAT_5": "afd_em_grupo_5",
        "EJA_FUN_CAT_1": "afd_eja_fundamental_grupo_1",
        "EJA_FUN_CAT_2": "afd_eja_fundamental_grupo_2",
        "EJA_FUN_CAT_3": "afd_eja_fundamental_grupo_3",
        "EJA_FUN_CAT_4": "afd_eja_fundamental_grupo_4",
        "EJA_FUN_CAT_5": "afd_eja_fundamental_grupo_5",
        "EJA_MED_CAT_1": "afd_eja_medio_grupo_1",
        "EJA_MED_CAT_2": "afd_eja_medio_grupo_2",
        "EJA_MED_CAT_3": "afd_eja_medio_grupo_3",
        "EJA_MED_CAT_4": "afd_eja_medio_grupo_4",
        "EJA_MED_CAT_5": "afd_eja_medio_grupo_5",
    }


def renames_atu() -> dict[str, str]:
    return {
        "NU_ANO_CENSO": "ano",
        "NO_CATEGORIA": "localizacao",
        "NO_DEPENDENCIA": "rede",
        "ED_INF_CAT_0": "atu_ei",
        "CRE_CAT_0": "atu_ei_creche",
        "PRE_CAT_0": "atu_ei_pre_escola",
        "FUN_CAT_0": "atu_ef",
        "FUN_AI_CAT_0": "atu_ef_anos_iniciais",
        "FUN_AF_CAT_0": "atu_ef_anos_finais",
        "FUN_01_CAT_0": "atu_ef_1_ano",
        "FUN_02_CAT_0": "atu_ef_2_ano",
        "FUN_03_CAT_0": "atu_ef_3_ano",
        "FUN_04_CAT_0": "atu_ef_4_ano",
        "FUN_05_CAT_0": "atu_ef_5_ano",
        "FUN_06_CAT_0": "atu_ef_6_ano",
        "FUN_07_CAT_0": "atu_ef_7_ano",
        "FUN_08_CAT_0": "atu_ef_8_ano",
        "FUN_09_CAT_0": "atu_ef_9_ano",
        "MULT_ETA_CAT_0": "atu_ef_turmas_unif_multi_fluxo",
        "MED_CAT_0": "atu_em",
        "MED_01_CAT_0": "atu_em_1_ano",
        "MED_02_CAT_0": "atu_em_2_ano",
        "MED_03_CAT_0": "atu_em_3_ano",
        "MED_04_CAT_0": "atu_em_4_ano",
        "MED_NS_CAT_0": "atu_em_nao_seriado",
    }


def renames_dsu(year: int) -> dict[str, str]:
    if year in [2019, 2020, 2021, 2022, 2023, 2024]:
        return {
            "NU_ANO_CENSO": "ano",
            "NO_CATEGORIA": "localizacao",
            "NO_DEPENDENCIA": "rede",
            "ED_INF_CAT_0": "dsu_ei",
            "CRE_CAT_0": "dsu_ei_creche",
            "PRE_CAT_0": "dsu_ei_pre_escola",
            "FUN_CAT_0": "dsu_ef",
            "FUN_AI_CAT_0": "dsu_ef_anos_iniciais",
            "FUN_AF_CAT_0": "dsu_ef_anos_finais",
            "MED_CAT_0": "dsu_em",
            "PROF_CAT_0": "dsu_ep",
            "EJA_CAT_0": "dsu_eja",
            "EDU_BAS_CAT_0": "dsu_ee",
        }
    elif year == 2025:
        return {
            "NU_ANO_CENSO": "ano",
            "NO_CATEGORIA": "localizacao",
            "NO_DEPENDENCIA": "rede",
            "ED_INF_CAT_0": "dsu_ei",
            "CRE_CAT_0": "dsu_ei_creche",
            "PRE_CAT_0": "dsu_ei_pre_escola",
            "FUN_CAT_0": "dsu_ef",
            "FUN_AI_CAT_0": "dsu_ef_anos_iniciais",
            "FUN_AF_CAT_0": "dsu_ef_anos_finais",
            "MED_CAT_0": "dsu_em",
            "EJA_CAT_0": "dsu_eja",
            # "EJA_FUN_CAT_0": "dsu_eja_ef",
            # "EJA_MED_CAT_0": "dsu_eja_em",
        }
    else:
        raise AssertionError


def renames_had(year: int) -> dict[str, str]:
    if year == 2019:
        return {
            "NU_ANO_CENSO": "ano",
            "NO_CATEGORIA": "localizacao",
            "NO_DEPENDENCIA": "rede",
            "ED_INF_CAT_0": "had_ei",
            "CRE_CAT_0": "had_ei_creche",
            "PRE_CAT_0": "had_ei_pre_escola",
            "FUN_CAT_0": "had_ef",
            "FUN_AI_CAT_0": "had_ef_anos_iniciais",
            "FUN_AF_CAT_0": "had_ef_anos_finais",
            "FUN_01_CAT_0": "had_ef_1_ano",
            "FUN_02_CAT_0": "had_ef_2_ano",
            "FUN_03_CAT_0": "had_ef_3_ano",
            "FUN_04_CAT_0": "had_ef_4_ano",
            "FUN_05_CAT_0": "had_ef_5_ano",
            "FUN_06_CAT_0": "had_ef_6_ano",
            "FUN_07_CAT_0": "had_ef_7_ano",
            "FUN_08_CAT_0": "had_ef_8_ano",
            "FUN_09_CAT_0": "had_ef_9_ano",
            "MED_CAT_0": "had_em",
            "MED_01_CAT_0": "had_em_1_ano",
            "MED_03_CAT_0": "had_em_3_ano",
            "MED_04_CAT_0": "had_em_4_ano",
            "MED_02_CAT_0": "had_em_2_ano",
            "MED_NS_CAT_0": "had_em_nao_seriado",
        }
    else:
        return {
            "NU_ANO_CENSO": "ano",
            "NO_CATEGORIA": "localizacao",
            "NO_DEPENDENCIA": "rede",
            "ED_INF_CAT_0": "had_ei",
            "CRE_CAT_0": "had_ei_creche",
            "PRE_CAT_0": "had_ei_pre_escola",
            "FUN_CAT_0": "had_ef",
            "FUN_AI_CAT_0": "had_ef_anos_iniciais",
            "FUN_AF_CAT_0": "had_ef_anos_finais",
            "FUN_01_CAT_0": "had_ef_1_ano",
            "FUN_02_CAT_0": "had_ef_2_ano",
            "FUN_03_CAT_0": "had_ef_3_ano",
            "FUN_04_CAT_0": "had_ef_4_ano",
            "FUN_05_CAT_0": "had_ef_5_ano",
            "FUN_06_CAT_0": "had_ef_6_ano",
            "FUN_07_CAT_0": "had_ef_7_ano",
            "FUN_08_CAT_0": "had_ef_8_ano",
            "FUN_09_CAT_0": "had_ef_9_ano",
            "MED_CAT_0": "had_em",
            "MED_01_CAT_0": "had_em_1_ano",
            "MED_03_CAT_0": "had_em_3_ano",
            "MED_04_CAT_0": "had_em_4_ano",
            "MED_02_CAT_0": "had_em_2_ano",
            "MED_NS_CAT_0": "had_em_nao_seriado",
        }


def renames_icg() -> dict[str, str]:
    return {
        "NU_ANO_CENSO": "ano",
        "NO_CATEGORIA": "localizacao",
        "NO_DEPENDENCIA": "rede",
        "EDU_BAS_CAT_1": "icg_nivel_1",
        "EDU_BAS_CAT_2": "icg_nivel_2",
        "EDU_BAS_CAT_3": "icg_nivel_3",
        "EDU_BAS_CAT_4": "icg_nivel_4",
        "EDU_BAS_CAT_5": "icg_nivel_5",
        "EDU_BAS_CAT_6": "icg_nivel_6",
    }


def renames_ied() -> dict[str, str]:
    return {
        "NU_ANO_CENSO": "ano",
        "NO_CATEGORIA": "localizacao",
        "NO_DEPENDENCIA": "rede",
        "FUN_CAT_1": "ied_ef_nivel_1",
        "FUN_CAT_2": "ied_ef_nivel_2",
        "FUN_CAT_3": "ied_ef_nivel_3",
        "FUN_CAT_4": "ied_ef_nivel_4",
        "FUN_CAT_5": "ied_ef_nivel_5",
        "FUN_CAT_6": "ied_ef_nivel_6",
        "FUN_AI_CAT_1": "ied_ef_anos_iniciais_nivel_1",
        "FUN_AI_CAT_2": "ied_ef_anos_iniciais_nivel_2",
        "FUN_AI_CAT_3": "ied_ef_anos_iniciais_nivel_3",
        "FUN_AI_CAT_4": "ied_ef_anos_iniciais_nivel_4",
        "FUN_AI_CAT_5": "ied_ef_anos_iniciais_nivel_5",
        "FUN_AI_CAT_6": "ied_ef_anos_iniciais_nivel_6",
        "FUN_AF_CAT_1": "ied_ef_anos_finais_nivel_1",
        "FUN_AF_CAT_2": "ied_ef_anos_finais_nivel_2",
        "FUN_AF_CAT_3": "ied_ef_anos_finais_nivel_3",
        "FUN_AF_CAT_4": "ied_ef_anos_finais_nivel_4",
        "FUN_AF_CAT_5": "ied_ef_anos_finais_nivel_5",
        "FUN_AF_CAT_6": "ied_ef_anos_finais_nivel_6",
        "MED_CAT_1": "ied_em_nivel_1",
        "MED_CAT_2": "ied_em_nivel_2",
        "MED_CAT_3": "ied_em_nivel_3",
        "MED_CAT_4": "ied_em_nivel_4",
        "MED_CAT_5": "ied_em_nivel_5",
        "MED_CAT_6": "ied_em_nivel_6",
    }


def renames_ird() -> dict[str, str]:
    return {
        "NU_ANO_CENSO": "ano",
        "NO_CATEGORIA": "localizacao",
        "NO_DEPENDENCIA": "rede",
        "EDU_BAS_CAT_1": "ird_baixa_regularidade",
        "EDU_BAS_CAT_2": "ird_media_baixa",
        "EDU_BAS_CAT_3": "ird_media_alta",
        "EDU_BAS_CAT_4": "ird_alta",
    }


def renames_tdi() -> dict[str, str]:
    return {
        "NU_ANO_CENSO": "ano",
        "NO_CATEGORIA": "localizacao",
        "NO_DEPENDENCIA": "rede",
        "FUN_CAT_0": "tdi_ef",
        "FUN_AI_CAT_0": "tdi_ef_anos_iniciais",
        "FUN_AF_CAT_0": "tdi_ef_anos_finais",
        "FUN_01_CAT_0": "tdi_ef_1_ano",
        "FUN_02_CAT_0": "tdi_ef_2_ano",
        "FUN_03_CAT_0": "tdi_ef_3_ano",
        "FUN_04_CAT_0": "tdi_ef_4_ano",
        "FUN_05_CAT_0": "tdi_ef_5_ano",
        "FUN_06_CAT_0": "tdi_ef_6_ano",
        "FUN_07_CAT_0": "tdi_ef_7_ano",
        "FUN_08_CAT_0": "tdi_ef_8_ano",
        "FUN_09_CAT_0": "tdi_ef_9_ano",
        "MED_CAT_0": "tdi_em",
        "MED_01_CAT_0": "tdi_em_1_ano",
        "MED_02_CAT_0": "tdi_em_2_ano",
        "MED_03_CAT_0": "tdi_em_3_ano",
        "MED_04_CAT_0": "tdi_em_4_ano",
    }


def renames_tnr(year: int) -> dict[str, str]:
    if year == 2019 or year == 2020:
        return {
            "ano": "ano",
            "TIPOLOCA": "localizacao",
            "DEPENDAD": "rede",
            "TNR_FUN": "tnr_ef",
            "TNR_F14": "tnr_ef_anos_iniciais",
            "TNR_F04": "tnr_ef_anos_finais",
            "TNR_F58": "tnr_ef_1_ano",
            "TNR_F00": "tnr_ef_2_ano",
            "TNR_F01": "tnr_ef_3_ano",
            "TNR_F02": "tnr_ef_4_ano",
            "TNR_F03": "tnr_ef_5_ano",
            "TNR_F05": "tnr_ef_6_ano",
            "TNR_F06": "tnr_ef_7_ano",
            "TNR_F07": "tnr_ef_8_ano",
            "TNR_F08": "tnr_ef_9_ano",
            "TNR_MED": "tnr_em",
            "TNR_M01": "tnr_em_1_ano",
            "TNR_M02": "tnr_em_2_ano",
            "TNR_M03": "tnr_em_3_ano",
            "TNR_M04": "tnr_em_4_ano",
            "TNR_MNS": "tnr_em_nao_seriado",
        }
    else:
        return {
            "NU_ANO_CENSO": "ano",
            "NO_CATEGORIA": "localizacao",
            "NO_DEPENDENCIA": "rede",
            "4_CAT_FUN": "tnr_ef",
            "4_CAT_FUN_AI": "tnr_ef_anos_iniciais",
            "4_CAT_FUN_AF": "tnr_ef_anos_finais",
            "4_CAT_FUN_01": "tnr_ef_1_ano",
            "4_CAT_FUN_02": "tnr_ef_2_ano",
            "4_CAT_FUN_03": "tnr_ef_3_ano",
            "4_CAT_FUN_04": "tnr_ef_4_ano",
            "4_CAT_FUN_05": "tnr_ef_5_ano",
            "4_CAT_FUN_06": "tnr_ef_6_ano",
            "4_CAT_FUN_07": "tnr_ef_7_ano",
            "4_CAT_FUN_08": "tnr_ef_8_ano",
            "4_CAT_FUN_09": "tnr_ef_9_ano",
            "4_CAT_MED": "tnr_em",
            "4_CAT_MED_01": "tnr_em_1_ano",
            "4_CAT_MED_02": "tnr_em_2_ano",
            "4_CAT_MED_03": "tnr_em_3_ano",
            "4_CAT_MED_04": "tnr_em_4_ano",
            "4_CAT_MED_NS": "tnr_em_nao_seriado",
        }


def renames_tx(year: int) -> dict[str, str]:
    if year == 2019:
        return {
            "Unnamed: 0": "ano",
            "Unnamed: 3": "id_municipio",
            "Unnamed: 5": "localizacao",
            "Unnamed: 6": "rede",
            "Unnamed: 7": "taxa_aprovacao_ef",
            "Unnamed: 8": "taxa_aprovacao_ef_anos_iniciais",
            "Unnamed: 9": "taxa_aprovacao_ef_anos_finais",
            "Unnamed: 10": "taxa_aprovacao_ef_1_ano",
            "Unnamed: 11": "taxa_aprovacao_ef_2_ano",
            "Unnamed: 12": "taxa_aprovacao_ef_3_ano",
            "Unnamed: 13": "taxa_aprovacao_ef_4_ano",
            "Unnamed: 14": "taxa_aprovacao_ef_5_ano",
            "Unnamed: 15": "taxa_aprovacao_ef_6_ano",
            "Unnamed: 16": "taxa_aprovacao_ef_7_ano",
            "Unnamed: 17": "taxa_aprovacao_ef_8_ano",
            "Unnamed: 18": "taxa_aprovacao_ef_9_ano",
            "Unnamed: 19": "taxa_aprovacao_em",
            "Unnamed: 20": "taxa_aprovacao_em_1_ano",
            "Unnamed: 21": "taxa_aprovacao_em_2_ano",
            "Unnamed: 22": "taxa_aprovacao_em_3_ano",
            "Unnamed: 23": "taxa_aprovacao_em_4_ano",
            "Unnamed: 24": "taxa_aprovacao_em_nao_seriado",
            "Unnamed: 25": "taxa_reprovacao_ef",
            "Unnamed: 26": "taxa_reprovacao_ef_anos_iniciais",
            "Unnamed: 27": "taxa_reprovacao_ef_anos_finais",
            "Unnamed: 28": "taxa_reprovacao_ef_1_ano",
            "Unnamed: 29": "taxa_reprovacao_ef_2_ano",
            "Unnamed: 30": "taxa_reprovacao_ef_3_ano",
            "Unnamed: 31": "taxa_reprovacao_ef_4_ano",
            "Unnamed: 32": "taxa_reprovacao_ef_5_ano",
            "Unnamed: 33": "taxa_reprovacao_ef_6_ano",
            "Unnamed: 34": "taxa_reprovacao_ef_7_ano",
            "Unnamed: 35": "taxa_reprovacao_ef_8_ano",
            "Unnamed: 36": "taxa_reprovacao_ef_9_ano",
            "Unnamed: 37": "taxa_reprovacao_em",
            "Unnamed: 38": "taxa_reprovacao_em_1_ano",
            "Unnamed: 39": "taxa_reprovacao_em_2_ano",
            "Unnamed: 40": "taxa_reprovacao_em_3_ano",
            "Unnamed: 41": "taxa_reprovacao_em_4_ano",
            "Unnamed: 42": "taxa_reprovacao_em_nao_seriado",
            "Unnamed: 43": "taxa_abandono_ef",
            "Unnamed: 44": "taxa_abandono_ef_anos_iniciais",
            "Unnamed: 45": "taxa_abandono_ef_anos_finais",
            "Unnamed: 46": "taxa_abandono_ef_1_ano",
            "Unnamed: 47": "taxa_abandono_ef_2_ano",
            "Unnamed: 48": "taxa_abandono_ef_3_ano",
            "Unnamed: 49": "taxa_abandono_ef_4_ano",
            "Unnamed: 50": "taxa_abandono_ef_5_ano",
            "Unnamed: 51": "taxa_abandono_ef_6_ano",
            "Unnamed: 52": "taxa_abandono_ef_7_ano",
            "Unnamed: 53": "taxa_abandono_ef_8_ano",
            "Unnamed: 54": "taxa_abandono_ef_9_ano",
            "Unnamed: 55": "taxa_abandono_em",
            "Unnamed: 56": "taxa_abandono_em_1_ano",
            "Unnamed: 57": "taxa_abandono_em_2_ano",
            "Unnamed: 58": "taxa_abandono_em_3_ano",
            "Unnamed: 59": "taxa_abandono_em_4_ano",
            "Unnamed: 60": "taxa_abandono_em_nao_seriado",
        }
    else:
        return {
            "NU_ANO_CENSO": "ano",
            "NO_CATEGORIA": "localizacao",
            "NO_DEPENDENCIA": "rede",
            "1_CAT_FUN": "taxa_aprovacao_ef",
            "1_CAT_FUN_AI": "taxa_aprovacao_ef_anos_iniciais",
            "1_CAT_FUN_AF": "taxa_aprovacao_ef_anos_finais",
            "1_CAT_FUN_01": "taxa_aprovacao_ef_1_ano",
            "1_CAT_FUN_02": "taxa_aprovacao_ef_2_ano",
            "1_CAT_FUN_03": "taxa_aprovacao_ef_3_ano",
            "1_CAT_FUN_04": "taxa_aprovacao_ef_4_ano",
            "1_CAT_FUN_05": "taxa_aprovacao_ef_5_ano",
            "1_CAT_FUN_06": "taxa_aprovacao_ef_6_ano",
            "1_CAT_FUN_07": "taxa_aprovacao_ef_7_ano",
            "1_CAT_FUN_08": "taxa_aprovacao_ef_8_ano",
            "1_CAT_FUN_09": "taxa_aprovacao_ef_9_ano",
            "1_CAT_MED": "taxa_aprovacao_em",
            "1_CAT_MED_01": "taxa_aprovacao_em_1_ano",
            "1_CAT_MED_02": "taxa_aprovacao_em_2_ano",
            "1_CAT_MED_03": "taxa_aprovacao_em_3_ano",
            "1_CAT_MED_04": "taxa_aprovacao_em_4_ano",
            "1_CAT_MED_NS": "taxa_aprovacao_em_nao_seriado",
            "2_CAT_FUN": "taxa_reprovacao_ef",
            "2_CAT_FUN_AI": "taxa_reprovacao_ef_anos_iniciais",
            "2_CAT_FUN_AF": "taxa_reprovacao_ef_anos_finais",
            "2_CAT_FUN_01": "taxa_reprovacao_ef_1_ano",
            "2_CAT_FUN_02": "taxa_reprovacao_ef_2_ano",
            "2_CAT_FUN_03": "taxa_reprovacao_ef_3_ano",
            "2_CAT_FUN_04": "taxa_reprovacao_ef_4_ano",
            "2_CAT_FUN_05": "taxa_reprovacao_ef_5_ano",
            "2_CAT_FUN_06": "taxa_reprovacao_ef_6_ano",
            "2_CAT_FUN_07": "taxa_reprovacao_ef_7_ano",
            "2_CAT_FUN_08": "taxa_reprovacao_ef_8_ano",
            "2_CAT_FUN_09": "taxa_reprovacao_ef_9_ano",
            "2_CAT_MED": "taxa_reprovacao_em",
            "2_CAT_MED_01": "taxa_reprovacao_em_1_ano",
            "2_CAT_MED_02": "taxa_reprovacao_em_2_ano",
            "2_CAT_MED_03": "taxa_reprovacao_em_3_ano",
            "2_CAT_MED_04": "taxa_reprovacao_em_4_ano",
            "2_CAT_MED_NS": "taxa_reprovacao_em_nao_seriado",
            "3_CAT_FUN": "taxa_abandono_ef",
            "3_CAT_FUN_AI": "taxa_abandono_ef_anos_iniciais",
            "3_CAT_FUN_AF": "taxa_abandono_ef_anos_finais",
            "3_CAT_FUN_01": "taxa_abandono_ef_1_ano",
            "3_CAT_FUN_02": "taxa_abandono_ef_2_ano",
            "3_CAT_FUN_03": "taxa_abandono_ef_3_ano",
            "3_CAT_FUN_04": "taxa_abandono_ef_4_ano",
            "3_CAT_FUN_05": "taxa_abandono_ef_5_ano",
            "3_CAT_FUN_06": "taxa_abandono_ef_6_ano",
            "3_CAT_FUN_07": "taxa_abandono_ef_7_ano",
            "3_CAT_FUN_08": "taxa_abandono_ef_8_ano",
            "3_CAT_FUN_09": "taxa_abandono_ef_9_ano",
            "3_CAT_MED": "taxa_abandono_em",
            "3_CAT_MED_01": "taxa_abandono_em_1_ano",
            "3_CAT_MED_02": "taxa_abandono_em_2_ano",
            "3_CAT_MED_03": "taxa_abandono_em_3_ano",
            "3_CAT_MED_04": "taxa_abandono_em_4_ano",
            "3_CAT_MED_NS": "taxa_abandono_em_nao_seriado",
        }
