---
version: 2
models:
  - name: br_ans_beneficiario__informacao_consolidada
    description: O conjunto contém Informações consolidadas de beneficiários por competência.
      Este será alterado para inclusão de dados acima de 5 anos e melhorias na qualidade
      dos dados.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - ano
            - mes
            - sigla_uf
            - id_municipio
            - codigo_operadora
            - razao_social
            - cnpj
            - modalidade_operadora
            - sexo
            - faixa_etaria
            - faixa_etaria_reajuste
            - codigo_plano
            - tipo_vigencia_plano
            - contratacao_beneficiario
            - segmentacao_beneficiario
            - abrangencia_beneficiario
            - cobertura_assistencia_beneficiario
            - tipo_vinculo
          config:
            where: __most_recent_year_month__
    columns:
      - name: ano
        description: Competência dos dados (AAAA)
      - name: mes
        description: Competência dos dados (MM)
      - name: sigla_uf
        description: Sigla da Unidade da Federação
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__uf')
              field: sigla
              config:
                where: __most_recent_year_month__
      - name: id_municipio
        description: ID do Município IBGE - 7 Dígitos
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__municipio')
              field: id_municipio
              config:
                where: __most_recent_year_month__
      - name: sexo
        description: Sexo (M, F)
        tests:
          - accepted_values:
              values: [M, F]
              config:
                where: __most_recent_year_month__
      - name: faixa_etaria
        description: Faixa etária do beneficiário
      - name: faixa_etaria_reajuste
        description: Faixa etária do beneficiária utilizada para o reajuste do plano
          definida pela Lei 9.656
      - name: codigo_operadora
        description: Código de registro da operadora de plano de saúde na ANS
      - name: razao_social
        description: Razão Social da Operadora
      - name: cnpj
        description: CNPJ da Operadora
      - name: modalidade_operadora
        description: Classificação das operadoras de planos privados de assistência
          à saúde de acordo com seu estatuto jurídico
        tests:
          - accepted_values:
              values:
                - Filantropia
                - Autogestao
                - Medicina De Grupo
                - Odontologia De Grupo
                - Cooperativa Odontologica
                - Seguradora Especializada Em Saude
                - Cooperativa Medica
              config:
                where: __most_recent_year_month__
      - name: codigo_plano
        description: Código do plano registrado ou cadastrado na ANS no qual o beneficiário
          possui vínculo
      - name: tipo_vigencia_plano
        description: Início da vigência do plano para comercialização
      - name: contratacao_beneficiario
        description: Tipo de contratação do plano do beneficiário
      - name: segmentacao_beneficiario
        description: Tipo de segmentação assistencial do plano do beneficiário
      - name: abrangencia_beneficiario
        description: Tipo de abrangência do plano do beneficiário
      - name: cobertura_assistencia_beneficiario
        description: Tipo de cobertura de plano do beneficiário
        tests:
          - accepted_values:
              values: [Medico-Hospitalar, Odontologico]
              config:
                where: __most_recent_year_month__
      - name: tipo_vinculo
        description: Tipo de vinculo do beneficiário
        tests:
          - accepted_values:
              values: [Titular, Dependente, Nao Identificado]
              config:
                where: __most_recent_year_month__
      - name: quantidade_beneficiario_ativo
        description: Quantidade de beneficiários ativos na competência
      - name: quantidade_beneficiario_aderido
        description: Quantidade de beneficiários aderidos na competência
      - name: quantidade_beneficiario_cancelado
        description: Quantidade de beneficiários cancelados na competência
      - name: data_carga
        description: Data de Carga dos dados.
  - name: br_ans_beneficiario__dicionario
    description: Dicionario
    columns:
      - name: id_tabela
        description: ID da Tabela
      - name: nome_coluna
        description: Nome da coluna
      - name: chave
        description: Chave
      - name: cobertura_temporal
        description: Cobertura temporal
      - name: valor
        description: Valor
