{{
    config(
        alias="microdatos_hogar",
        schema="ar_indec_eph",
        materialized="table",
        partition_by={
            "field": "ano",
            "data_type": "int64",
            "range": {
                "start": 2003,
                "end": 2031,
                "interval": 1,
            },
        },
        cluster_by=["trimestre", "id_aglomerado"],
    )
}}


select
    safe_cast(ano as int64) ano,
    safe_cast(trimestre as int64) trimestre,
    safe_cast(id_vivienda as string) id_vivienda,
    safe_cast(nro_hogar as string) nro_hogar,
    safe_cast(id_region as string) id_region,
    safe_cast(id_aglomerado as string) id_aglomerado,
    safe_cast(mas_500 as string) mas_500,
    safe_cast(pondera as int64) pondera,
    safe_cast(pondih as int64) pondih,
    safe_cast(realizada as string) realizada,
    safe_cast(iv1 as string) iv1,
    safe_cast(iv1_esp as string) iv1_esp,
    safe_cast(iv2 as int64) iv2,
    safe_cast(iv3 as string) iv3,
    safe_cast(iv3_esp as string) iv3_esp,
    safe_cast(iv4 as string) iv4,
    safe_cast(iv5 as string) iv5,
    safe_cast(iv6 as string) iv6,
    safe_cast(iv7 as string) iv7,
    safe_cast(iv7_esp as string) iv7_esp,
    safe_cast(iv8 as string) iv8,
    safe_cast(iv9 as string) iv9,
    safe_cast(iv10 as string) iv10,
    safe_cast(iv11 as string) iv11,
    safe_cast(iv12_1 as string) iv12_1,
    safe_cast(iv12_2 as string) iv12_2,
    safe_cast(iv12_3 as string) iv12_3,
    safe_cast(ii1 as int64) ii1,
    safe_cast(ii2 as int64) ii2,
    safe_cast(ii3 as string) ii3,
    safe_cast(ii3_1 as int64) ii3_1,
    safe_cast(ii4_1 as string) ii4_1,
    safe_cast(ii4_2 as string) ii4_2,
    safe_cast(ii4_3 as string) ii4_3,
    safe_cast(ii5 as string) ii5,
    safe_cast(ii5_1 as int64) ii5_1,
    safe_cast(ii6 as string) ii6,
    safe_cast(ii6_1 as int64) ii6_1,
    safe_cast(ii7 as string) ii7,
    safe_cast(ii7_esp as string) ii7_esp,
    safe_cast(ii8 as string) ii8,
    safe_cast(ii8_esp as string) ii8_esp,
    safe_cast(ii9 as string) ii9,
    safe_cast(v1 as string) v1,
    safe_cast(v2 as string) v2,
    safe_cast(v21 as string) v21,
    safe_cast(v22 as string) v22,
    safe_cast(v3 as string) v3,
    safe_cast(v4 as string) v4,
    safe_cast(v5 as string) v5,
    safe_cast(v6 as string) v6,
    safe_cast(v7 as string) v7,
    safe_cast(v8 as string) v8,
    safe_cast(v9 as string) v9,
    safe_cast(v10 as string) v10,
    safe_cast(v11 as string) v11,
    safe_cast(v12 as string) v12,
    safe_cast(v13 as string) v13,
    safe_cast(v14 as string) v14,
    safe_cast(v15 as string) v15,
    safe_cast(v16 as string) v16,
    safe_cast(v17 as string) v17,
    safe_cast(v18 as string) v18,
    safe_cast(v19_a as string) v19_a,
    safe_cast(v19_b as string) v19_b,
    safe_cast(ix_tot as int64) ix_tot,
    safe_cast(ix_men10 as int64) ix_men10,
    safe_cast(ix_mayeq10 as int64) ix_mayeq10,
    safe_cast(itf as float64) itf,
    safe_cast(decifr as string) decifr,
    safe_cast(idecifr as string) idecifr,
    safe_cast(rdecifr as string) rdecifr,
    safe_cast(gdecifr as string) gdecifr,
    safe_cast(pdecifr as string) pdecifr,
    safe_cast(adecifr as string) adecifr,
    safe_cast(ipcf as float64) ipcf,
    safe_cast(deccfr as string) deccfr,
    safe_cast(ideccfr as string) ideccfr,
    safe_cast(rdeccfr as string) rdeccfr,
    safe_cast(gdeccfr as string) gdeccfr,
    safe_cast(pdeccfr as string) pdeccfr,
    safe_cast(adeccfr as string) adeccfr,
    safe_cast(vii1_1 as string) vii1_1,
    safe_cast(vii1_2 as string) vii1_2,
    safe_cast(vii2_1 as string) vii2_1,
    safe_cast(vii2_2 as string) vii2_2,
    safe_cast(vii2_3 as string) vii2_3,
    safe_cast(vii2_4 as string) vii2_4,
    safe_cast(idimph as string) idimph,
    safe_cast(v2_02 as string) v2_02,
    safe_cast(v2_03 as string) v2_03,
    safe_cast(v21_01 as string) v21_01,
    safe_cast(v22_01 as string) v22_01,
    safe_cast(v5_02 as string) v5_02,
    safe_cast(v5_03 as string) v5_03,
    safe_cast(v11_01 as string) v11_01,
    safe_cast(v11_02 as string) v11_02,
    safe_cast(v5_01 as string) v5_01,
    safe_cast(v21_02 as string) v21_02,
    safe_cast(v21_03 as string) v21_03,
    safe_cast(v22_02 as string) v22_02,
    safe_cast(v22_03 as string) v22_03,
    safe_cast(v2_01 as string) v2_01
from {{ set_datalake_project("ar_indec_eph_staging.microdatos_hogar") }} as t
