"""
Constant values for the datasets projects
"""

from enum import Enum
from pathlib import Path


class constants(Enum):
    """
    Constant values for the br_cvm_fii project
    """

    TMP_DIR = Path("tmp")
    DATASET_DIR = TMP_DIR / "br_cvm_fi"
    TMP_DIR.mkdir(exist_ok=True)
    DATASET_DIR.mkdir(exist_ok=True, parents=True)

    # URLs
    URL_CDA = "https://dados.cvm.gov.br/dados/FI/DOC/CDA/DADOS/"
    URL_INFORME_DIARIO = (
        "https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/"
    )
    URL_EXTRATO = "https://dados.cvm.gov.br/dados/FI/DOC/EXTRATO/DADOS/"
    URL_PERFIL_MENSAL = (
        "https://dados.cvm.gov.br/dados/FI/DOC/PERFIL_MENSAL/DADOS/"
    )
    URL_INFO_CADASTRAL = "https://dados.cvm.gov.br/dados/FI/CAD/DADOS/"
    URL_BALANCETE = "https://dados.cvm.gov.br/dados/FI/DOC/BALANCETE/DADOS/"

    # Architectures
    URL_ARCH_CDA = "https://docs.google.com/spreadsheets/d/1V2XHBXBB_biC0cLoMZ3FxtbC7CPLxQXZhIY7iJDtsSw/edit#gid=0"
    URL_ARCH_INFORME = "https://docs.google.com/spreadsheets/d/1W739_mLZNBPYhBqGyjsuuWFBOqCrhrDl/edit#gid=1045172528"
    URL_ARCH_INFO_CAD = "https://docs.google.com/spreadsheets/d/1OdPdDRnZ9sh3tEdSUo64wsSxVuf5atHP/edit#gid=1045172528"
    URL_ARCH_BALANCETE = "https://docs.google.com/spreadsheets/d/1eIMo_hYHy89oh6kHRN9Kh0NytUZzr8__/edit#gid=1045172528"
    URL_ARCH_EXTRATO = "https://docs.google.com/spreadsheets/d/1b94RdASfwXMgJuVMhFeY6Xbph4n4_MVt/edit#gid=1045172528"
    URL_ARCH_PERFIL_MENSAL = "https://docs.google.com/spreadsheets/d/1IN7enHe6K-StD_sDfCaqhJ7XfUNXe-W8/edit#gid=1045172528"

    # Tables supposed to be found in CSV files
    CSV_LIST = [
        "https://dados.cvm.gov.br/dados/FI/DOC/EXTRATO/DADOS/",
        "https://dados.cvm.gov.br/dados/FI/DOC/PERFIL_MENSAL/DADOS/",
        "https://dados.cvm.gov.br/dados/FI/CAD/DADOS/",
    ]

    CAD_FILE = "cad_fi.csv"
    FILE_EXT = "extrato_fi.csv"

    MAPEAMENTO = {"S": "1", "N": "0"}

    RENAME_MAPPING_CDA = {
        "TP_FUNDO_CLASSE": "id_fundo",
        "CNPJ_FUNDO_CLASSE": "cnpj",
        "TP_FUNDO": "id_fundo",
        "CNPJ_FUNDO": "cnpj",
        "DENOM_SOCIAL": "denominacao_social",
        "DT_COMPTC": "data_competencia",
        "TP_APLIC": "tipo_aplicacao",
        "TP_ATIVO": "tipo_ativo",
        "EMISSOR_LIGADO": "indicador_emissor_ligado",
        "TP_NEGOC": "tipo_negociacao",
        "QT_VENDA_NEGOC": "quantidade_vendas_negocios_mes",
        "VL_VENDA_NEGOC": "valor_vendas_negocios_mes",
        "QT_AQUIS_NEGOC": "quantidade_aquisicoes_negocios_mes",
        "VL_AQUIS_NEGOC": "valor_aquisicoes_negocios_mes",
        "QT_POS_FINAL": "quantidade_posicao_final",
        "VL_MERC_POS_FINAL": "valor_mercado_posicao_final",
        "VL_CUSTO_POS_FINAL": "valor_custo_posicao_final",
        "DT_CONFID_APLIC": "prazo_confidencialidae_aplicacao",
        "TP_TITPUB": "tipo_titulo_publico",
        "CD_ISIN": "codigo_isin",
        "CD_SELIC": "codigo_selic",
        "DT_EMISSAO": "data_emissao",
        "DT_VENC": "data_vencimento",
        "CNPJ_FUNDO_COTA": "cnpj_fundo_investido",
        "NM_FUNDO_COTA": "denominacao_social_fundo_investido",
        "CNPJ_FUNDO_CLASSE_COTA": "cnpj_fundo_investido",
        "NM_FUNDO_CLASSE_COTA": "denominacao_social_fundo_investido",
        "CD_SWAP": "codigo_swap",
        "DS_SWAP": "descricao_tipo_ativo_swap",
        "CD_ATIVO": "codigo_ativo",
        "DS_ATIVO": "descricao_ativo",
        "DT_INI_VIGENCIA": "data_inicio_vigencia",
        "DT_FIM_VIGENCIA": "data_fim_vigencia",
        "CNPJ_EMISSOR": "cnpj_emissor",
        "EMISSOR": "nome_emissor",
        "TITULO_POSFX": "indicador_titulo_pos_fixado",
        "CD_INDEXADOR_POSFX": "codigo_indexador_pos_fixados",
        "DS_INDEXADOR_POSFX": "descricao_indexador_pos_fixados",
        "PR_INDEXADOR_POSFX": "porcentagem_indexador_pos_fixados",
        "PR_CUPOM_POSFX": "porcentagem_cupom_pos_fixados",
        "PR_TAXA_PREFX": "porcentagem_taxa_concentrada_pre_fixados",
        "RISCO_EMISSOR": "indicador_emissor_possui_classificacao_risco",
        "AG_RISCO": "nome_agencia_classificacao_risco",
        "DT_RISCO": "data_classificacao_risco",
        "GRAU_RISCO": "grau_risco_atribuido",
        "PF_PJ_EMISSOR": "indicador_emissor_pessoa_fisica_juridica",
        "CPF_CNPJ_EMISSOR": "indicador_codigo_identificacao_emissor_pessoa_fisica_juridica",
        "TITULO_CETIP": "indicador_titulo_registrado_cetip",
        "TITULO_GARANTIA": "indicador_titulo_possui_garantia_seguro",
        "CNPJ_INSTITUICAO_FINANC_COOBR": "cnpj_instituicao_financeira_coobrigacao",
        "INVEST_COLETIVO": "indicador_investimento_coletivo",
        "INVEST_COLETIVO_GESTOR": "indicador_gestao_carteira_influencia_gestor",
        "CD_PAIS": "codigo_pais",
        "PAIS": "nome_pais",
        "CD_BV_MERC": "codigo_bolsa_mercado_balcao",
        "BV_MERC": "tipo_bolsa_mercado_balcao",
        "CD_ATIVO_BV_MERC": "codigo_ativo_bolsa_mercado_balcao_local_aquisicao",
        "DS_ATIVO_EXTERIOR": "descricao_ativo_exterior",
        "QT_ATIVO_EXTERIOR": "quantidade_ativos_exterior",
        "VL_ATIVO_EXTERIOR": "valor_ativo_exterior",
    }
    FINAL_COLS_CDA = [
        "id_fundo",
        "cnpj",
        "denominacao_social",
        "data_competencia",
        "tipo_aplicacao",
        "tipo_ativo",
        "indicador_emissor_ligado",
        "tipo_negociacao",
        "quantidade_vendas_negocios_mes",
        "valor_vendas_negocios_mes",
        "quantidade_aquisicoes_negocios_mes",
        "valor_aquisicoes_negocios_mes",
        "quantidade_posicao_final",
        "valor_mercado_posicao_final",
        "valor_custo_posicao_final",
        "prazo_confidencialidae_aplicacao",
        "codigo_ativo",
        "descricao_ativo",
        "codigo_isin",
        "data_inicio_vigencia",
        "data_fim_vigencia",
        "bloco",
        "tipo_titulo_publico",
        "codigo_selic",
        "data_emissao",
        "data_vencimento",
        "indicador_emissor_pessoa_fisica_juridica",
        "indicador_codigo_identificacao_emissor_pessoa_fisica_juridica",
        "nome_emissor",
        "indicador_titulo_pos_fixado",
        "codigo_indexador_pos_fixados",
        "descricao_indexador_pos_fixados",
        "porcentagem_indexador_pos_fixados",
        "porcentagem_cupom_pos_fixados",
        "porcentagem_taxa_concentrada_pre_fixados",
        "indicador_titulo_registrado_cetip",
        "indicador_titulo_possui_garantia_seguro",
        "cnpj_instituicao_financeira_coobrigacao",
        "codigo_swap",
        "descricao_tipo_ativo_swap",
        "cnpj_emissor",
        "indicador_emissor_possui_classificacao_risco",
        "nome_agencia_classificacao_risco",
        "data_classificacao_risco",
        "grau_risco_atribuido",
        "cnpj_fundo_investido",
        "denominacao_social_fundo_investido",
        "indicador_investimento_coletivo",
        "indicador_gestao_carteira_influencia_gestor",
        "codigo_pais",
        "nome_pais",
        "codigo_bolsa_mercado_balcao",
        "tipo_bolsa_mercado_balcao",
        "codigo_ativo_bolsa_mercado_balcao_local_aquisicao",
        "descricao_ativo_exterior",
        "quantidade_ativos_exterior",
        "valor_ativo_exterior",
        "ano",
        "mes",
    ]
    TO_MAP_COLS_CDA = [
        "indicador_emissor_ligado",
        "indicador_titulo_pos_fixado",
        "indicador_emissor_possui_classificacao_risco",
        "indicador_emissor_pessoa_fisica_juridica",
        "indicador_codigo_identificacao_emissor_pessoa_fisica_juridica",
        "indicador_titulo_registrado_cetip",
        "indicador_titulo_possui_garantia_seguro",
        "indicador_investimento_coletivo",
        "indicador_gestao_carteira_influencia_gestor",
    ]
    ASCII_COLS_CDA = [
        "denominacao_social",
        "tipo_aplicacao",
        "tipo_ativo",
        "descricao_ativo",
        "tipo_negociacao",
        "tipo_titulo_publico",
        "nome_emissor",
        "descricao_indexador_pos_fixados",
        "nome_agencia_classificacao_risco",
        "grau_risco_atribuido",
        "nome_pais",
        "tipo_bolsa_mercado_balcao",
        "codigo_ativo_bolsa_mercado_balcao_local_aquisicao",
    ]

    RENAME_MAPPING_INFORME = {
        "TP_FUNDO_CLASSE": "id_fundo",
        "CNPJ_FUNDO_CLASSE": "cnpj",
        "DT_COMPTC": "data_competencia",
        "VL_TOTAL": "valor_total",
        "VL_QUOTA": "valor_cota",
        "VL_PATRIM_LIQ": "valor_patrimonio_liquido",
        "CAPTC_DIA": "captacao_dia",
        "RESG_DIA": "regate_dia",
        "NR_COTST": "quantidade_cotistas",
    }
    FINAL_COLS_INFORME = [
        "id_fundo",
        "cnpj",
        "data_competencia",
        "valor_total",
        "valor_cota",
        "valor_patrimonio_liquido",
        "captacao_dia",
        "regate_dia",
        "quantidade_cotistas",
        "ano",
        "mes",
    ]

    RENAME_MAPPING_EXTRATO = {
        "CNPJ_FUNDO_CLASSE": "cnpj",
        "CNPJ_FUNDO": "cnpj",
        "DENOM_SOCIAL": "denominacao_social",
        "DT_COMPTC": "data_competencia",
        "CONDOM": "condominio",
        "NEGOC_MERC": "indicador_negociacao_mercado",
        "MERCADO": "nome_mercado",
        "TP_PRAZO": "tipo_prazo",
        "PRAZO": "prazo",
        "PUBLICO_ALVO": "publico_alvo",
        "REG_ANBIMA": "indicador_registro_anbima",
        "CLASSE_ANBIMA": "classificacao_anbima",
        "DISTRIB": "forma_distribuicao",
        "POLIT_INVEST": "politica_investimento",
        "APLIC_MAX_FUNDO_LIGADO": "porcentagem_aplicacao_maximo_fundo_ligado",
        "RESULT_CART_INCORP_PL": "indicador_resultados_carteira_incorporado_patrimonio_liquido",
        "FUNDO_COTAS": "indicador_fundo_cotas",
        "FUNDO_ESPELHO": "indicador_fundo_espelho",
        "APLIC_MIN": "aplicacao_minima",
        "ATUALIZ_DIARIA_COTA": "indicador_atualizacao_diaria_cota",
        "PRAZO_ATUALIZ_COTA": "prazo_atualizacao_valor_cota",
        "COTA_EMISSAO": "cota_emissao",
        "COTA_PL": "patrimonio_liquido_cota",
        "QT_DIA_CONVERSAO_COTA": "quantidade_dias_conversao_cota",
        "QT_DIA_PAGTO_COTA": "quantidade_dias_pagamento_cota",
        "QT_DIA_RESGATE_COTAS": "quantidade_dias_carencia_resgate_cotas",
        "QT_DIA_PAGTO_RESGATE": "quantidade_dias_pagamento_resgates",
        "TP_DIA_PAGTO_RESGATE": "tipo_prazo_pagamento_resgates",
        "TAXA_SAIDA_PAGTO_RESGATE": "indicador_cobranca_taxa_saida_resgates",
        "TAXA_ADM": "taxa_administracao",
        "TAXA_CUSTODIA_MAX": "taxa_maxima_custodia",
        "EXISTE_TAXA_PERFM": "indicador_taxa_performance",
        "TAXA_PERFM": "taxa_performance",
        "PARAM_TAXA_PERFM": "parametro_taxa_performance",
        "PR_INDICE_REFER_TAXA_PERFM": "porcentagem_indice_referencia_taxa_performance",
        "VL_CUPOM": "valor_cumpom",
        "CALC_TAXA_PERFM": "metodo_calculo_taxa_performance",
        "INF_TAXA_PERFM": "informacoes_adicionais_taxa_performance",
        "EXISTE_TAXA_INGRESSO": "indicador_taxa_ingresso",
        "TAXA_INGRESSO_REAL": "taxa_ingresso_real",
        "TAXA_INGRESSO_PR": "porcentagem_taxa_ingresso",
        "EXISTE_TAXA_SAIDA": "indicador_cobranca_taxa_saida",
        "TAXA_SAIDA_REAL": "taxa_saida_real",
        "TAXA_SAIDA_PR": "porcentagem_taxa_saida",
        "OPER_DERIV": "indicador_operacoes_derivativos",
        "FINALIDADE_OPER_DERIV": "finalidade_operacoes_derivativos",
        "OPER_VL_SUPERIOR_PL": "indicador_operacoes_valor_superior_patrimonio_liquido",
        "FATOR_OPER_VL_SUPERIOR_PL": "fator_limite_total_operacoes_patrimonio_liquido",
        "CONTRAP_LIGADO": "indicador_contraparte_ligado",
        "INVEST_EXTERIOR": "indicador_investimentos_exterior",
        "APLIC_MAX_ATIVO_EXTERIOR": "aplicacao_maxima_ativo_exterior",
        "ATIVO_CRED_PRIV": "indicador_ativo_credito_privado",
        "APLIC_MAX_ATIVO_CRED_PRIV": "aplicacao_maxima_ativo_credito_privado",
        "PR_INSTITUICAO_FINANC_MIN": "porcentagem_exposicao_minima_emissor_instituicao_financeira",
        "PR_INSTITUICAO_FINANC_MAX": "porcentagem_exposicao_maxima_emissor_instituicao_financeira",
        "PR_CIA_MIN": "porcentagem_exposicao_minima_emissor_companhias_abertas",
        "PR_CIA_MAX": "porcentagem_exposicao_maxima_emissor_companhias_abertas",
        "PR_FI_MIN": "porcentagem_exposicao_minima_emissor_fundos_investimento",
        "PR_FI_MAX": "porcentagem_exposicao_maxima_emissor_fundos_investimento",
        "PR_UNIAO_MIN": "porcentagem_exposicao_minima_emissor_uniao_federal",
        "PR_UNIAO_MAX": "porcentagem_exposicao_maxima_emissor_uniao_federal",
        "PR_ADMIN_GESTOR_MIN": "porcentagem_exposicao_minima_emissor_adm_gestor_pessoas_ligadas",
        "PR_ADMIN_GESTOR_MAX": "porcentagem_exposicao_maxima_emissor_adm_gestor_pessoas_ligadas",
        "PR_EMISSOR_OUTRO_MIN": "porcentagem_exposicao_minima_emissor_outros",
        "PR_EMISSOR_OUTRO_MAX": "porcentagem_exposicao_maxima_emissor_outros",
        "PR_COTA_FI_MIN": "porcentagem_exposicao_minima_cotas_fi",
        "PR_COTA_FI_MAX": "porcentagem_exposicao_maxima_cotas_fi",
        "PR_COTA_FIC_MIN": "porcentagem_exposicao_minima_cotas_fic",
        "PR_COTA_FIC_MAX": "porcentagem_exposicao_maxima_cotas_fic",
        "PR_COTA_FI_QUALIF_MIN": "porcentagem_exposicao_minima_cotas_fi_qualificados",
        "PR_COTA_FI_QUALIF_MAX": "porcentagem_exposicao_maxima_cotas_fi_qualificados",
        "PR_COTA_FIC_QUALIF_MIN": "porcentagem_exposicao_minima_cotas_fic_qualificados",
        "PR_COTA_FIC_QUALIF_MAX": "porcentagem_exposicao_maxima_cotas_fic_qualificados",
        "PR_COTA_FI_PROF_MIN": "porcentagem_exposicao_minima_cotas_fi_profissionais",
        "PR_COTA_FI_PROF_MAX": "porcentagem_exposicao_maxima_cotas_fi_profissionais",
        "PR_COTA_FIC_PROF_MIN": "porcentagem_exposicao_minima_cotas_fic_profissionais",
        "PR_COTA_FIC_PROF_MAX": "porcentagem_exposicao_maxima_cotas_fic_profissionais",
        "PR_COTA_FII_MIN": "porcentagem_exposicao_minima_cotas_fii",
        "PR_COTA_FII_MAX": "porcentagem_exposicao_maxima_cotas_fii",
        "PR_COTA_FIDC_MIN": "porcentagem_exposicao_minima_cotas_fidc",
        "PR_COTA_FIDC_MAX": "porcentagem_exposicao_maxima_cotas_fidc",
        "PR_COTA_FICFIDC_MIN": "porcentagem_exposicao_minima_cotas_ficfidc",
        "PR_COTA_FICFIDC_MAX": "porcentagem_exposicao_maxima_cotas_ficfidc",
        "PR_COTA_FIDC_NP_MIN": "porcentagem_exposicao_minima_cotas_fidic_np",
        "PR_COTA_FIDC_NP_MAX": "porcentagem_exposicao_maxima_cotas_fidic_np",
        "PR_COTA_FICFIDC_NP_MIN": "porcentagem_exposicao_minima_cotas_ficfidic_np",
        "PR_COTA_FICFIDC_NP_MAX": "porcentagem_exposicao_maxima_cotas_ficfidc_np",
        "PR_COTA_ETF_MIN": "porcentagem_exposicao_minima_cotas_etf",
        "PR_COTA_ETF_MAX": "porcentagem_exposicao_maxima_cotas_etf",
        "PR_CRI_MIN": "porcentagem_exposicao_minima_cota_cri",
        "PR_CRI_MAX": "porcentagem_exposicao_maxima_cota_cri",
        "PR_TITPUB_MIN": "porcentagem_exposicao_minima_titulos_publicos_operacoes_comprimessadas",
        "PR_TITPUB_MAX": "porcentagem_exposicao_maxima_titulos_publicos_operacoes_comprimessadas",
        "PR_OURO_MIN": "porcentagem_exposicao_minima_ouro",
        "PR_OURO_MAX": "porcentagem_exposicao_maxima_ouro",
        "PR_TIT_INSTITUICAO_FINANC_BACEN_MIN": "porcentagem_exposicao_minima_titulos_instituicao_financeira_bacen",
        "PR_TIT_INSTITUICAO_FINANC_BACEN_MAX": "porcentagem_exposicao_maxima_titulos_instituicao_financeira_bacen",
        "PR_VLMOB_MIN": "porcentagem_exposicao_minima_valores_mobiliarios",
        "PR_VLMOB_MAX": "porcentagem_exposicao_maxima_valores_mobiliarios",
        "PR_ACAO_MIN": "porcentagem_exposicao_minima_acoes",
        "PR_ACAO_MAX": "porcentagem_exposicao_maxima_acoes",
        "PR_DEBENTURE_MIN": "porcentagem_exposicao_minima_debenture",
        "PR_DEBENTURE_MAX": "porcentagem_exposicao_maxima_debenture",
        "PR_NP_MIN": "porcentagem_exposicao_minima_notas_promissorias",
        "PR_NP_MAX": "porcentagem_exposicao_maxima_notas_promissorias",
        "PR_COMPROM_MIN": "porcentagem_exposicao_minima_operacoes_compromissadas_titulos_credito_privado",
        "PR_COMPROM_MAX": "porcentagem_exposicao_maxima_operacoes_compromissadas_titulos_credito_privado",
        "PR_DERIV_MIN": "porcentagem_exposicao_minima_derivativos",
        "PR_DERIV_MAX": "porcentagem_exposicao_maxima_derivativos",
        "PR_ATIVO_OUTRO_MIN": "porcentagem_exposicao_minima_outros",
        "PR_ATIVO_OUTRO_MAX": "porcentagem_exposicao_maxima_outros",
        "PR_COTA_FMIEE_MIN": "porcentagem_exposicao_minima_cotas_fmiee",
        "PR_COTA_FMIEE_MAX": "porcentagem_exposicao_maxima_cotas_fmiee",
        "PR_COTA_FIP_MIN": "porcentagem_exposicao_minima_cotas_fip",
        "PR_COTA_FIP_MAX": "porcentagem_exposicao_maxima_cotas_fip",
        "PR_COTA_FICFIP_MIN": "porcentagem_exposicao_minima_cotas_ficfip",
        "PR_COTA_FICFIP_MAX": "porcentagem_exposicao_maxima_cotas_ficfip",
    }
    FINAL_COLS_EXTRATO = [
        "cnpj",
        "denominacao_social",
        "data_competencia",
        "condominio",
        "indicador_negociacao_mercado",
        "nome_mercado",
        "tipo_prazo",
        "prazo",
        "publico_alvo",
        "indicador_registro_anbima",
        "classificacao_anbima",
        "forma_distribuicao",
        "politica_investimento",
        "porcentagem_aplicacao_maximo_fundo_ligado",
        "indicador_resultados_carteira_incorporado_patrimonio_liquido",
        "indicador_fundo_cotas",
        "indicador_fundo_espelho",
        "aplicacao_minima",
        "indicador_atualizacao_diaria_cota",
        "prazo_atualizacao_valor_cota",
        "cota_emissao",
        "patrimonio_liquido_cota",
        "quantidade_dias_conversao_cota",
        "quantidade_dias_pagamento_cota",
        "quantidade_dias_carencia_resgate_cotas",
        "quantidade_dias_pagamento_resgates",
        "tipo_prazo_pagamento_resgates",
        "indicador_cobranca_taxa_saida_resgates",
        "taxa_administracao",
        "taxa_maxima_custodia",
        "indicador_taxa_performance",
        "taxa_performance",
        "parametro_taxa_performance",
        "porcentagem_indice_referencia_taxa_performance",
        "valor_cumpom",
        "metodo_calculo_taxa_performance",
        "informacoes_adicionais_taxa_performance",
        "indicador_taxa_ingresso",
        "taxa_ingresso_real",
        "porcentagem_taxa_ingresso",
        "indicador_cobranca_taxa_saida",
        "taxa_saida_real",
        "porcentagem_taxa_saida",
        "indicador_operacoes_derivativos",
        "finalidade_operacoes_derivativos",
        "indicador_operacoes_valor_superior_patrimonio_liquido",
        "fator_limite_total_operacoes_patrimonio_liquido",
        "indicador_contraparte_ligado",
        "indicador_investimentos_exterior",
        "aplicacao_maxima_ativo_exterior",
        "indicador_ativo_credito_privado",
        "aplicacao_maxima_ativo_credito_privado",
        "porcentagem_exposicao_minima_emissor_instituicao_financeira",
        "porcentagem_exposicao_maxima_emissor_instituicao_financeira",
        "porcentagem_exposicao_minima_emissor_companhias_abertas",
        "porcentagem_exposicao_maxima_emissor_companhias_abertas",
        "porcentagem_exposicao_minima_emissor_fundos_investimento",
        "porcentagem_exposicao_maxima_emissor_fundos_investimento",
        "porcentagem_exposicao_minima_emissor_uniao_federal",
        "porcentagem_exposicao_maxima_emissor_uniao_federal",
        "porcentagem_exposicao_minima_emissor_adm_gestor_pessoas_ligadas",
        "porcentagem_exposicao_maxima_emissor_adm_gestor_pessoas_ligadas",
        "porcentagem_exposicao_minima_emissor_outros",
        "porcentagem_exposicao_maxima_emissor_outros",
        "porcentagem_exposicao_minima_cotas_fi",
        "porcentagem_exposicao_maxima_cotas_fi",
        "porcentagem_exposicao_minima_cotas_fic",
        "porcentagem_exposicao_maxima_cotas_fic",
        "porcentagem_exposicao_minima_cotas_fi_qualificados",
        "porcentagem_exposicao_maxima_cotas_fi_qualificados",
        "porcentagem_exposicao_minima_cotas_fic_qualificados",
        "porcentagem_exposicao_maxima_cotas_fic_qualificados",
        "porcentagem_exposicao_minima_cotas_fi_profissionais",
        "porcentagem_exposicao_maxima_cotas_fi_profissionais",
        "porcentagem_exposicao_minima_cotas_fic_profissionais",
        "porcentagem_exposicao_maxima_cotas_fic_profissionais",
        "porcentagem_exposicao_minima_cotas_fii",
        "porcentagem_exposicao_maxima_cotas_fii",
        "porcentagem_exposicao_minima_cotas_fidc",
        "porcentagem_exposicao_maxima_cotas_fidc",
        "porcentagem_exposicao_minima_cotas_ficfidc",
        "porcentagem_exposicao_maxima_cotas_ficfidc",
        "porcentagem_exposicao_minima_cotas_fidic_np",
        "porcentagem_exposicao_maxima_cotas_fidic_np",
        "porcentagem_exposicao_minima_cotas_ficfidic_np",
        "porcentagem_exposicao_maxima_cotas_ficfidc_np",
        "porcentagem_exposicao_minima_cotas_etf",
        "porcentagem_exposicao_maxima_cotas_etf",
        "porcentagem_exposicao_minima_cota_cri",
        "porcentagem_exposicao_maxima_cota_cri",
        "porcentagem_exposicao_minima_titulos_publicos_operacoes_comprimessadas",
        "porcentagem_exposicao_maxima_titulos_publicos_operacoes_comprimessadas",
        "porcentagem_exposicao_minima_ouro",
        "porcentagem_exposicao_maxima_ouro",
        "porcentagem_exposicao_minima_titulos_instituicao_financeira_bacen",
        "porcentagem_exposicao_maxima_titulos_instituicao_financeira_bacen",
        "porcentagem_exposicao_minima_valores_mobiliarios",
        "porcentagem_exposicao_maxima_valores_mobiliarios",
        "porcentagem_exposicao_minima_acoes",
        "porcentagem_exposicao_maxima_acoes",
        "porcentagem_exposicao_minima_debenture",
        "porcentagem_exposicao_maxima_debenture",
        "porcentagem_exposicao_minima_notas_promissorias",
        "porcentagem_exposicao_maxima_notas_promissorias",
        "porcentagem_exposicao_minima_operacoes_compromissadas_titulos_credito_privado",
        "porcentagem_exposicao_maxima_operacoes_compromissadas_titulos_credito_privado",
        "porcentagem_exposicao_minima_derivativos",
        "porcentagem_exposicao_maxima_derivativos",
        "porcentagem_exposicao_minima_outros",
        "porcentagem_exposicao_maxima_outros",
        "porcentagem_exposicao_minima_cotas_fmiee",
        "porcentagem_exposicao_maxima_cotas_fmiee",
        "porcentagem_exposicao_minima_cotas_fip",
        "porcentagem_exposicao_maxima_cotas_fip",
        "porcentagem_exposicao_minima_cotas_ficfip",
        "porcentagem_exposicao_maxima_cotas_ficfip",
        "ano",
        "mes",
    ]
    TO_MAP_COLS_EXTRATO = [
        "indicador_negociacao_mercado",
        "indicador_registro_anbima",
        "indicador_resultados_carteira_incorporado_patrimonio_liquido",
        "indicador_fundo_cotas",
        "indicador_fundo_espelho",
        "indicador_atualizacao_diaria_cota",
        "indicador_cobranca_taxa_saida_resgates",
        "indicador_taxa_performance",
        "indicador_taxa_ingresso",
        "indicador_cobranca_taxa_saida",
        "indicador_operacoes_derivativos",
        "indicador_operacoes_valor_superior_patrimonio_liquido",
        "indicador_contraparte_ligado",
        "indicador_investimentos_exterior",
        "indicador_ativo_credito_privado",
    ]
    ASCII_COLS_EXTRATO = [
        "denominacao_social",
        "condominio",
        "nome_mercado",
        "tipo_prazo",
        "prazo",
        "publico_alvo",
        "classificacao_anbima",
        "forma_distribuicao",
        "politica_investimento",
        "prazo_atualizacao_valor_cota",
        "cota_emissao",
        "patrimonio_liquido_cota",
        "tipo_prazo_pagamento_resgates",
        "parametro_taxa_performance",
        "metodo_calculo_taxa_performance",
        "informacoes_adicionais_taxa_performance",
        "finalidade_operacoes_derivativos",
    ]

    ASCII_COLS_PERFIL_MENSAL = [
        "cnpj",
        "denominacao_social",
        "versao",
        "resumo_voto_adminstrador_assembleia",
        "justificativa_voto_administrador_assembleia",
        "tipo_modelos_valor_em_risco",
        "resumo_deliberacoes_aprovadas_assembleia",
        "fator_primitivo_risco",
        "cenario_fator_primitivo_risco_ibovespa",
        "cenario_fator_primitivo_risco_juros",
        "cenario_fator_primitivo_cupom_cambial",
        "cenario_fator_primitivo_dolar",
        "cenario_fator_primitivo_outros",
        "fator_risco_outros",
        "fator_risco_nocional",
        "tipo_pessoa_comitente_1",
        "cpf_cnpj_comitente_1",
        "tipo_pessoa_comitente_2",
        "cpf_cnpj_comitente_2",
        "tipo_pessoa_comitente_3",
        "cpf_cnpj_comitente_3",
        "tipo_pessoa_emissor_1",
        "cpf_cnpj_emissor_1",
        "tipo_pessoa_emissor_2",
        "cpf_cnpj_emissor_2",
        "tipo_pessoa_emissor_3",
        "cpf_cnpj_emissor_3",
    ]
    RENAME_MAPPING_PERFIL = {
        "CNPJ_FUNDO_CLASSE": "cnpj",
        "DENOM_SOCIAL": "denominacao_social",
        "DT_COMPTC": "data_competencia",
        "VERSAO": "versao",
        "NR_COTST_PF_PB": "quantidade_clientes_cotitstas_pessoa_fisica_private_banking",
        "NR_COTST_PF_VAREJO": "quantidade_clientes_cotitstas_pessoa_fisica_varejo",
        "NR_COTST_PJ_NAO_FINANC_PB": "quantidade_clientes_cotistas_pessoa_juridica_nao_financeira_private_banking",
        "NR_COTST_PJ_NAO_FINANC_VAREJO": "quantidade_clientes_cotistas_pessoa_juridica_nao_financeira_varejo",
        "NR_COTST_BANCO": "quantidade_clientes_cotitstas_banco_comercial",
        "NR_COTST_CORRETORA_DISTRIB": "quantidade_clientes_cotistas_corretora_distribuidora",
        "NR_COTST_PJ_FINANC": "quantidade_clientes_cotistas_outras_pessoas_juridicas_financeiras",
        "NR_COTST_INVNR": "quantidade_clientes_cotistas_investidores_nao_residentes",
        "NR_COTST_EAPC": "quantidade_clientes_cotistas_entidade_aberta_previdencia_complementar",
        "NR_COTST_EFPC": "quantidade_clientes_cotistas_entidade_fechada_previdencia_complementar",
        "NR_COTST_RPPS": "quantidade_clientes_cotistas_regime_proprio_previdencia_servidores_publicos",
        "NR_COTST_SEGUR": "quantidade_clientes_cotistas_sociedade_seguradora_resseguradora",
        "NR_COTST_CAPITALIZ": "quantidade_clientes_cotistas_sociedade_capitalizacao_arrendamento_mercantil",
        "NR_COTST_FI_CLUBE": "quantidade_clientes_cotistas_fundos_clubes_investimento",
        "NR_COTST_DISTRIB": "quantidade_clientes_cotistas_distribuidores_fundo",
        "NR_COTST_OUTRO": "quantidade_clientes_cotistas_outros_tipos",
        "PR_PL_COTST_PF_PB": "porcentagem_patrimonio_liquido_detido_cotitstas_pessoa_fisica_private_banking",
        "PR_PL_COTST_PF_VAREJO": "porcentagem_patrimonio_liquido_detido_cotitstas_pessoa_fisica_varejo",
        "PR_PL_COTST_PJ_NAO_FINANC_PB": "porcentagem_patrimonio_liquido_detido_cotistas_pessoa_juridica_nao_financeira_private_banking",
        "PR_PL_COTST_PJ_NAO_FINANC_VAREJO": "porcentagem_patrimonio_liquido_detido_cotistas_pessoa_juridica_nao_financeira_varejo",
        "PR_PL_COTST_BANCO": "porcentagem_patrimonio_liquido_detido_cotitstas_banco_comercial",
        "PR_PL_COTST_CORRETORA_DISTRIB": "porcentagem_patrimonio_liquido_detido_cotistas_corretora_distribuidora",
        "PR_PL_COTST_PJ_FINANC": "porcentagem_patrimonio_liquido_detido_cotistas_outras_pessoas_juridicas_financeiras",
        "PR_PL_COTST_INVNR": "porcentagem_patrimonio_liquido_detido_cotistas_investidores_nao_residentes",
        "PR_PL_COTST_EAPC": "porcentagem_patrimonio_liquido_detido_cotistas_entidade_aberta_previdencia_complementar",
        "PR_PL_COTST_EFPC": "porcentagem_patrimonio_liquido_detido_cotistas_entidade_fechada_previdencia_complementar",
        "PR_PL_COTST_RPPS": "porcentagem_patrimonio_liquido_detido_cotistas_regime_proprio_previdencia_servidores_publicos",
        "PR_PL_COTST_SEGUR": "porcentagem_patrimonio_liquido_detido_cotistas_sociedade_seguradora_resseguradora",
        "PR_PL_COTST_CAPITALIZ": "porcentagem_patrimonio_liquido_detido_cotistas_sociedade_capitalizacao_arrendamento_mercantil",
        "PR_PL_COTST_FI_CLUBE": "porcentagem_patrimonio_liquido_cotistas_fundos_clubes_investimento",
        "PR_PL_COTST_DISTRIB": "porcentagem_patrimonio_liquido_cotistas_distribuidores_fundo",
        "PR_PL_COTST_OUTRO": "porcentagem_patrimonio_liquido_cotistas_outros_tipos",
        "VOTO_ADMIN_ASSEMB": "resumo_voto_adminstrador_assembleia",
        "JUSTIF_VOTO_ADMIN_ASSEMB": "justificativa_voto_administrador_assembleia",
        "PR_VAR_CARTEIRA": "porcentagem_valor_em_risco_carteria",
        "MOD_VAR": "tipo_modelos_valor_em_risco",
        "PRAZO_CARTEIRA_TITULO": "prazo_carteira_titulos",
        "DELIB_ASSEMB": "resumo_deliberacoes_aprovadas_assembleia",
        "VL_CONTRATO_COMPRA_DOLAR": "valor_total_contrato_compra_dolar",
        "VL_CONTRATO_VENDA_DOLAR": "valor_total_contrato_venda_dolar",
        "PR_VARIACAO_DIARIA_COTA": "porcentagem_variacao_diaria_valor_cota",
        "FPR": "fator_primitivo_risco",
        "CENARIO_FPR_IBOVESPA": "cenario_fator_primitivo_risco_ibovespa",
        "CENARIO_FPR_JUROS": "cenario_fator_primitivo_risco_juros",
        "CENARIO_FPR_CUPOM": "cenario_fator_primitivo_cupom_cambial",
        "CENARIO_FPR_DOLAR": "cenario_fator_primitivo_dolar",
        "CENARIO_FPR_OUTRO": "cenario_fator_primitivo_outros",
        "PR_VARIACAO_DIARIA_COTA_ESTRESSE": "porcentagem_variacao_diaria_cota_estresse",
        "PR_VARIACAO_DIARIA_PL_TAXA_ANUAL": "porcentagem_variacao_diaria_patrimonio_liquido_taxa_anual_juros",
        "PR_VARIACAO_DIARIA_PL_TAXA_CAMBIO": "porcentagem_variacao_diaria_patrimonio_liquido_taxa_cambio",
        "PR_VARIACAO_DIARIA_PL_IBOVESPA": "porcentagem_variacao_diaria_patrimonio_liquido_ibovespa",
        "FATOR_RISCO_OUTRO": "fator_risco_outros",
        "PR_VARIACAO_DIARIA_OUTRO": "porcentagem_variacao_diaria_patrimonio_liquido_outros",
        "PR_COLATERAL_DERIV": "porcentagem_valor_colateral_garantia_derivativos",
        "FATOR_RISCO_NOCIONAL": "fator_risco_nocional",
        "VL_FATOR_RISCO_NOCIONAL_LONG_IBOVESPA": "valor_fator_risco_nocional_long_ibovespa",
        "VL_FATOR_RISCO_NOCIONAL_LONG_JUROS": "valor_fator_risco_nocional_long_juros",
        "VL_FATOR_RISCO_NOCIONAL_LONG_CUPOM": "valor_fator_risco_nocional_long_cupom",
        "VL_FATOR_RISCO_NOCIONAL_LONG_DOLAR": "valor_fator_risco_nocional_long_dolar",
        "VL_FATOR_RISCO_NOCIONAL_LONG_OUTRO": "valor_fator_risco_nocional_long_outro",
        "VL_FATOR_RISCO_NOCIONAL_SHORT_IBOVESPA": "valor_fator_risco_nocional_short_ibovespa",
        "VL_FATOR_RISCO_NOCIONAL_SHORT_JUROS": "valor_fator_risco_nocional_short_juros",
        "VL_FATOR_RISCO_NOCIONAL_SHORT_CUPOM": "valor_fator_risco_nocional_short_cupom",
        "VL_FATOR_RISCO_NOCIONAL_SHORT_DOLAR": "valor_fator_risco_nocional_short_dolar",
        "VL_FATOR_RISCO_NOCIONAL_SHORT_OUTRO": "valor_fator_risco_nocional_short_outro",
        "PF_PJ_COMITENTE_1": "tipo_pessoa_comitente_1",
        "CPF_CNPJ_COMITENTE_1": "cpf_cnpj_comitente_1",
        "COMITENTE_LIGADO_1": "indicador_comitente_relacionada_administrador_gestor_1",
        "PR_COMITENTE_1": "porcentagem_valor_parte_comitente_1",
        "PF_PJ_COMITENTE_2": "tipo_pessoa_comitente_2",
        "CPF_CNPJ_COMITENTE_2": "cpf_cnpj_comitente_2",
        "COMITENTE_LIGADO_2": "indicador_comitente_relacionada_administrador_gestor_2",
        "PR_COMITENTE_2": "porcentagem_valor_parte_comitente_2",
        "PF_PJ_COMITENTE_3": "tipo_pessoa_comitente_3",
        "CPF_CNPJ_COMITENTE_3": "cpf_cnpj_comitente_3",
        "COMITENTE_LIGADO_3": "indicador_comitente_relacionada_administrador_gestor_3",
        "PR_COMITENTE_3": "porcentagem_valor_parte_comitente_3",
        "PR_ATIVO_EMISSOR_LIGADO": "porcentagem_valor_total_ativos_emissao_partes_relacionadas",
        "PF_PJ_EMISSOR_1": "tipo_pessoa_emissor_1",
        "CPF_CNPJ_EMISSOR_1": "cpf_cnpj_emissor_1",
        "EMISSOR_LIGADO_1": "indicador_emissor_relacionada_administrador_gestor_1",
        "PR_EMISSOR_1": "porcentagem_valor_parte_emissor_1",
        "PF_PJ_EMISSOR_2": "tipo_pessoa_emissor_2",
        "CPF_CNPJ_EMISSOR_2": "cpf_cnpj_emissor_2",
        "EMISSOR_LIGADO_2": "indicador_emissor_relacionada_administrador_gestor_2",
        "PR_EMISSOR_2": "porcentagem_valor_parte_emissor_2",
        "PF_PJ_EMISSOR_3": "tipo_pessoa_emissor_3",
        "CPF_CNPJ_EMISSOR_3": "cpf_cnpj_emissor_3",
        "EMISSOR_LIGADO_3": "indicador_emissor_relacionada_administrador_gestor_3",
        "PR_EMISSOR_3": "porcentagem_valor_parte_emissor_3",
        "PR_ATIVO_CRED_PRIV": "porcentagem_valor_total_ativos_credito_privado",
        "VEDAC_TAXA_PERFM": "indicador_vedada_cobranca_taxa_performance",
        "DT_COTA_TAXA_PERFM": "data_cota_fundo_ultima_cobranca_taxa_performance",
        "VL_COTA_TAXA_PERFM": "valor_cota_fundo_ultima_cobranca_taxa_performance",
        "VL_DIREITO_DISTRIB": "valor_distribuido_direito_dividendos_juros_capital_proprio_outros",
        "NR_COTST_ENTID_PREVID_COMPL": "quantidade_cotistas_entidade_previdencia_complementar",
        "PR_COTST_ENTID_PREVID_COMPL": "porcentagem_cotistas_entidade_previdencia_complementar",
        "PR_PATRIM_LIQ_MAIOR_COTST": "porcentagem_patrimonio_liquido_maior_cotista",
        "NR_DIA_CINQU_PERC": "quantidade_dias_cinquenta_percentual",
        "NR_DIA_CEM_PERC": "quantidade_dias_cem_percentual",
        "ST_LIQDEZ": "indicador_liquidez",
        "PR_PATRIM_LIQ_CONVTD_CAIXA": "porcentagem_patrimonio_liquido_convertido_caixa",
    }
    FINAL_COLS_PERFIL = [
        "cnpj",
        "denominacao_social",
        "data_competencia",
        "versao",
        "quantidade_clientes_cotitstas_pessoa_fisica_private_banking",
        "quantidade_clientes_cotitstas_pessoa_fisica_varejo",
        "quantidade_clientes_cotistas_pessoa_juridica_nao_financeira_private_banking",
        "quantidade_clientes_cotistas_pessoa_juridica_nao_financeira_varejo",
        "quantidade_clientes_cotitstas_banco_comercial",
        "quantidade_clientes_cotistas_corretora_distribuidora",
        "quantidade_clientes_cotistas_outras_pessoas_juridicas_financeiras",
        "quantidade_clientes_cotistas_investidores_nao_residentes",
        "quantidade_clientes_cotistas_entidade_aberta_previdencia_complementar",
        "quantidade_clientes_cotistas_entidade_fechada_previdencia_complementar",
        "quantidade_clientes_cotistas_regime_proprio_previdencia_servidores_publicos",
        "quantidade_clientes_cotistas_sociedade_seguradora_resseguradora",
        "quantidade_clientes_cotistas_sociedade_capitalizacao_arrendamento_mercantil",
        "quantidade_clientes_cotistas_fundos_clubes_investimento",
        "quantidade_clientes_cotistas_distribuidores_fundo",
        "quantidade_clientes_cotistas_outros_tipos",
        "porcentagem_patrimonio_liquido_detido_cotitstas_pessoa_fisica_private_banking",
        "porcentagem_patrimonio_liquido_detido_cotitstas_pessoa_fisica_varejo",
        "porcentagem_patrimonio_liquido_detido_cotistas_pessoa_juridica_nao_financeira_private_banking",
        "porcentagem_patrimonio_liquido_detido_cotistas_pessoa_juridica_nao_financeira_varejo",
        "porcentagem_patrimonio_liquido_detido_cotitstas_banco_comercial",
        "porcentagem_patrimonio_liquido_detido_cotistas_corretora_distribuidora",
        "porcentagem_patrimonio_liquido_detido_cotistas_outras_pessoas_juridicas_financeiras",
        "porcentagem_patrimonio_liquido_detido_cotistas_investidores_nao_residentes",
        "porcentagem_patrimonio_liquido_detido_cotistas_entidade_aberta_previdencia_complementar",
        "porcentagem_patrimonio_liquido_detido_cotistas_entidade_fechada_previdencia_complementar",
        "porcentagem_patrimonio_liquido_detido_cotistas_regime_proprio_previdencia_servidores_publicos",
        "porcentagem_patrimonio_liquido_detido_cotistas_sociedade_seguradora_resseguradora",
        "porcentagem_patrimonio_liquido_detido_cotistas_sociedade_capitalizacao_arrendamento_mercantil",
        "porcentagem_patrimonio_liquido_cotistas_fundos_clubes_investimento",
        "porcentagem_patrimonio_liquido_cotistas_distribuidores_fundo",
        "porcentagem_patrimonio_liquido_cotistas_outros_tipos",
        "resumo_voto_adminstrador_assembleia",
        "justificativa_voto_administrador_assembleia",
        "porcentagem_valor_em_risco_carteria",
        "tipo_modelos_valor_em_risco",
        "prazo_carteira_titulos",
        "resumo_deliberacoes_aprovadas_assembleia",
        "valor_total_contrato_compra_dolar",
        "valor_total_contrato_venda_dolar",
        "porcentagem_variacao_diaria_valor_cota",
        "fator_primitivo_risco",
        "cenario_fator_primitivo_risco_ibovespa",
        "cenario_fator_primitivo_risco_juros",
        "cenario_fator_primitivo_cupom_cambial",
        "cenario_fator_primitivo_dolar",
        "cenario_fator_primitivo_outros",
        "porcentagem_variacao_diaria_cota_estresse",
        "porcentagem_variacao_diaria_patrimonio_liquido_taxa_anual_juros",
        "porcentagem_variacao_diaria_patrimonio_liquido_taxa_cambio",
        "porcentagem_variacao_diaria_patrimonio_liquido_ibovespa",
        "fator_risco_outros",
        "porcentagem_variacao_diaria_patrimonio_liquido_outros",
        "porcentagem_valor_colateral_garantia_derivativos",
        "fator_risco_nocional",
        "valor_fator_risco_nocional_long_ibovespa",
        "valor_fator_risco_nocional_long_juros",
        "valor_fator_risco_nocional_long_cupom",
        "valor_fator_risco_nocional_long_dolar",
        "valor_fator_risco_nocional_long_outro",
        "valor_fator_risco_nocional_short_ibovespa",
        "valor_fator_risco_nocional_short_juros",
        "valor_fator_risco_nocional_short_cupom",
        "valor_fator_risco_nocional_short_dolar",
        "valor_fator_risco_nocional_short_outro",
        "tipo_pessoa_comitente_1",
        "cpf_cnpj_comitente_1",
        "indicador_comitente_relacionada_administrador_gestor_1",
        "porcentagem_valor_parte_comitente_1",
        "tipo_pessoa_comitente_2",
        "cpf_cnpj_comitente_2",
        "indicador_comitente_relacionada_administrador_gestor_2",
        "porcentagem_valor_parte_comitente_2",
        "tipo_pessoa_comitente_3",
        "cpf_cnpj_comitente_3",
        "indicador_comitente_relacionada_administrador_gestor_3",
        "porcentagem_valor_parte_comitente_3",
        "porcentagem_valor_total_ativos_emissao_partes_relacionadas",
        "tipo_pessoa_emissor_1",
        "cpf_cnpj_emissor_1",
        "indicador_emissor_relacionada_administrador_gestor_1",
        "porcentagem_valor_parte_emissor_1",
        "tipo_pessoa_emissor_2",
        "cpf_cnpj_emissor_2",
        "indicador_emissor_relacionada_administrador_gestor_2",
        "porcentagem_valor_parte_emissor_2",
        "tipo_pessoa_emissor_3",
        "cpf_cnpj_emissor_3",
        "indicador_emissor_relacionada_administrador_gestor_3",
        "porcentagem_valor_parte_emissor_3",
        "porcentagem_valor_total_ativos_credito_privado",
        "indicador_vedada_cobranca_taxa_performance",
        "data_cota_fundo_ultima_cobranca_taxa_performance",
        "valor_cota_fundo_ultima_cobranca_taxa_performance",
        "valor_distribuido_direito_dividendos_juros_capital_proprio_outros",
        "quantidade_cotistas_entidade_previdencia_complementar",
        "porcentagem_cotistas_entidade_previdencia_complementar",
        "porcentagem_patrimonio_liquido_maior_cotista",
        "quantidade_dias_cinquenta_percentual",
        "quantidade_dias_cem_percentual",
        "indicador_liquidez",
        "porcentagem_patrimonio_liquido_convertido_caixa",
        "ano",
        "mes",
    ]
    TO_MAP_COLS_PERFIL = [
        "indicador_comitente_relacionada_administrador_gestor_1",
        "indicador_comitente_relacionada_administrador_gestor_2",
        "indicador_comitente_relacionada_administrador_gestor_3",
        "indicador_emissor_relacionada_administrador_gestor_1",
        "indicador_emissor_relacionada_administrador_gestor_2",
        "indicador_emissor_relacionada_administrador_gestor_3",
        "indicador_vedada_cobranca_taxa_performance",
        "indicador_liquidez",
    ]

    RENAME_MAPPING_CAD = {
        "TP_FUNDO": "id_fundo",
        "CNPJ_FUNDO": "cnpj",
        "DENOM_SOCIAL": "denominacao_social",
        "DT_REG": "data_registro",
        "DT_CONST": "data_constituicao",
        "CD_CVM": "codigo_cvm",
        "DT_CANCEL": "data_cancelamento",
        "SIT": "situacao",
        "DT_INI_SIT": "data_inicio_situacao",
        "DT_INI_ATIV": "data_inicio_atividade",
        "DT_INI_EXERC": "data_inicio_exercicio",
        "DT_FIM_EXERC": "data_fim_exercicio",
        "CLASSE": "classe",
        "DT_INI_CLASSE": "data_inicio_classe",
        "RENTAB_FUNDO": "tipo_rentabilidade",
        "CONDOM": "tipo_condominio",
        "FUNDO_COTAS": "indicador_fundo_cotas",
        "FUNDO_EXCLUSIVO": "indicador_fundo_exclusivo",
        "TRIB_LPRAZO": "indicador_tributacao_longo_prazo",
        "PUBLICO_ALVO": "publico_alvo",
        "ENTID_INVEST": "indicador_entidade_investimento",
        "TAXA_PERFM": "taxa_perfomarnce",
        "INF_TAXA_PERFM": "informacoes_adicionais_taxa_performance",
        "TAXA_ADM": "taxa_administracao",
        "INF_TAXA_ADM": "informacoes_adicionais_taxa_administracao",
        "VL_PATRIM_LIQ": "valor_patrimonio_liquido",
        "DT_PATRIM_LIQ": "data_patrimonio_liquido",
        "DIRETOR": "nome_diretor",
        "CNPJ_ADMIN": "cnpj_administrador",
        "ADMIN": "nome_administrador",
        "PF_PJ_GESTOR": "indicador_pessoa_fisica_ou_juridica",
        "CPF_CNPJ_GESTOR": "cpf_cnpj_gestor",
        "GESTOR": "nome_gestor",
        "CNPJ_AUDITOR": "cnpj_auditor",
        "AUDITOR": "nome_auditor",
        "CNPJ_CUSTODIANTE": "cnpj_custodiante",
        "CUSTODIANTE": "nome_custodiante",
        "CNPJ_CONTROLADOR": "cnpj_controlador",
        "CONTROLADOR": "nome_controlador",
        "INVEST_CEMPR_EXTER": "indicador_aplicacao_total_recursos_exterior",
    }
    FINAL_COLS_CAD = [
        "id_fundo",
        "cnpj",
        "denominacao_social",
        "data_registro",
        "data_constituicao",
        "codigo_cvm",
        "data_cancelamento",
        "situacao",
        "data_inicio_situacao",
        "data_inicio_atividade",
        "data_inicio_exercicio",
        "data_fim_exercicio",
        "classe",
        "data_inicio_classe",
        "tipo_rentabilidade",
        "tipo_condominio",
        "indicador_fundo_cotas",
        "indicador_fundo_exclusivo",
        "indicador_tributacao_longo_prazo",
        "publico_alvo",
        "indicador_entidade_investimento",
        "taxa_perfomarnce",
        "informacoes_adicionais_taxa_performance",
        "taxa_administracao",
        "informacoes_adicionais_taxa_administracao",
        "valor_patrimonio_liquido",
        "data_patrimonio_liquido",
        "nome_diretor",
        "cnpj_administrador",
        "nome_administrador",
        "indicador_pessoa_fisica_ou_juridica",
        "cpf_cnpj_gestor",
        "nome_gestor",
        "cnpj_auditor",
        "nome_auditor",
        "cnpj_custodiante",
        "nome_custodiante",
        "cnpj_controlador",
        "nome_controlador",
        "indicador_aplicacao_total_recursos_exterior",
    ]
    TO_MAP_COLS_CAD = []
    ASCII_COLS_CAD = [
        "id_fundo",
        "cnpj",
        "denominacao_social",
        "codigo_cvm",
        "situacao",
        "classe",
        "tipo_rentabilidade",
        "tipo_condominio",
        "informacoes_adicionais_taxa_performance",
        "informacoes_adicionais_taxa_administracao",
        "nome_diretor",
        "cnpj_administrador",
        "nome_administrador",
        "indicador_pessoa_fisica_ou_juridica",
        "cpf_cnpj_gestor",
        "nome_gestor",
        "cnpj_auditor",
        "nome_auditor",
        "cnpj_custodiante",
        "nome_custodiante",
        "cnpj_controlador",
        "nome_controlador",
    ]

    RENAME_MAPPING_BALANCETE = {
        "CNPJ_FUNDO": "cnpj",
        "CNPJ_FUNDO_CLASSE": "cnpj",
        "DT_COMPTC": "data_competencia",
        "PLANO_CONTA_BALCTE": "plano_contabil_balancete",
        "TP_FUNDO_CLASSE": "tipo_fundo",
        "CD_CONTA_BALCTE": "codigo_conta",
        "VL_SALDO_BALCTE": "valor_saldo",
    }
    FINAL_COLS_BALANCETE = [
        "cnpj",
        "data_competencia",
        "plano_contabil_balancete",
        "tipo_fundo",
        "codigo_conta",
        "valor_saldo",
        "ano",
        "mes",
    ]
