"""Architecture for the legado tables (Lei 8.666/1993 and earlier, 1997-2025)."""

from arch_common import BRL, DIR_ANO, c


def ano(
    source: str, en_src: str, es_src: str, coverage: str, obs: str = ""
) -> dict:
    return c(
        "ano",
        "INT64",
        f"Ano de {source}",
        en=f"Year of {en_src}",
        es=f"Año de {es_src}",
        directory=DIR_ANO,
        unit="year",
        coverage=coverage,
        obs=obs
        or "Coluna de particionamento, derivada da data correspondente",
    )


LICITACAO = [
    ano(
        "publicação do aviso de licitação",
        "publication of the tender notice",
        "publicación del aviso de licitación",
        "1997(1)2025",
    ),
    c(
        "id_compra",
        "STRING",
        "Identificador da licitação no SIASG",
        en="Identifier of the tender in SIASG",
        es="Identificador de la licitación en el SIASG",
        obs="Concatena código da UASG, modalidade, número do aviso e ano. Chave primária da tabela",
        original="id_compra",
    ),
    c(
        "identificador",
        "STRING",
        "Identificador alternativo da licitação publicado pela fonte",
        en="Alternative tender identifier published by the source",
        es="Identificador alternativo de la licitación publicado por la fuente",
        original="identificador",
    ),
    c(
        "codigo_uasg",
        "STRING",
        "Código da UASG responsável pela licitação",
        en="Code of the UASG running the tender",
        es="Código de la UASG responsable de la licitación",
        original="uasg",
    ),
    c(
        "numero_aviso",
        "STRING",
        "Número do aviso de licitação",
        en="Number of the tender notice",
        es="Número del aviso de licitación",
        original="numero_aviso",
    ),
    c(
        "numero_processo",
        "STRING",
        "Número do processo administrativo da licitação",
        en="Administrative case number of the tender",
        es="Número del proceso administrativo de la licitación",
        original="numero_processo",
    ),
    c(
        "codigo_modalidade",
        "STRING",
        "Código da modalidade de licitação no SIASG",
        en="SIASG code of the tender modality",
        es="Código de la modalidad de licitación en el SIASG",
        dic=True,
        obs="Codificação do regime da Lei 8.666, distinta da usada nas tabelas de contratação "
        "sob a Lei 14.133",
        original="modalidade",
    ),
    c(
        "modalidade",
        "STRING",
        "Modalidade de licitação, como pregão, concorrência, tomada de preços ou convite",
        en="Tender modality, such as reverse auction, competitive bidding or invitation",
        es="Modalidad de licitación, como pregón, concurrencia, toma de precios o invitación",
        original="nome_modalidade",
    ),
    c(
        "tipo_pregao",
        "STRING",
        "Forma de realização do pregão, eletrônico ou presencial",
        en="How the reverse auction was run, electronic or in person",
        es="Forma de realización del pregón, electrónico o presencial",
        original="tipo_pregao",
    ),
    c(
        "tipo_recurso",
        "STRING",
        "Origem dos recursos da licitação, nacional ou internacional",
        en="Origin of the tender's funds, domestic or international",
        es="Origen de los recursos de la licitación, nacional o internacional",
        original="tipo_recurso",
    ),
    c(
        "situacao_aviso",
        "STRING",
        "Situação do aviso, como publicado, revogado ou anulado",
        en="Notice status, such as published, revoked or annulled",
        es="Situación del aviso, como publicado, revocado o anulado",
        original="situacao_aviso",
    ),
    c(
        "codigo_municipio_uasg",
        "STRING",
        "Código do município da UASG no SIASG",
        en="SIASG municipality code of the UASG",
        es="Código del municipio de la UASG en el SIASG",
        obs="Codificação interna do SIASG, sem equivalência direta com o código IBGE. "
        "A UF pode ser obtida juntando com a tabela unidade_administrativa",
        original="codigo_municipio_uasg",
    ),
    c(
        "objeto",
        "STRING",
        "Descrição do objeto da licitação",
        en="Description of the tender's subject matter",
        es="Descripción del objeto de la licitación",
        original="objeto",
    ),
    c(
        "informacoes_gerais",
        "STRING",
        "Informações gerais publicadas com o aviso",
        en="General information published with the notice",
        es="Información general publicada con el aviso",
        original="informacoes_gerais",
    ),
    c(
        "endereco_entrega_edital",
        "STRING",
        "Endereço de entrega ou retirada do edital",
        en="Address for collecting the tender documents",
        es="Dirección de entrega o retiro del pliego",
        original="endereco_entrega_edital",
    ),
    c(
        "nome_responsavel",
        "STRING",
        "Nome do responsável pela licitação",
        en="Name of the official responsible for the tender",
        es="Nombre del responsable de la licitación",
        original="nome_responsavel",
    ),
    c(
        "funcao_responsavel",
        "STRING",
        "Função do responsável pela licitação",
        en="Role of the official responsible for the tender",
        es="Función del responsable de la licitación",
        original="funcao_responsavel",
    ),
    c(
        "numero_itens",
        "INT64",
        "Quantidade de itens da licitação",
        en="Number of items in the tender",
        es="Cantidad de ítems de la licitación",
        unit="unit",
        original="numero_itens",
    ),
    c(
        "valor_estimado_total",
        "FLOAT64",
        "Valor total estimado da licitação",
        en="Total estimated value of the tender",
        es="Valor total estimado de la licitación",
        unit=BRL,
        original="valor_estimado_total",
    ),
    c(
        "valor_homologado_total",
        "FLOAT64",
        "Valor total homologado da licitação",
        en="Total awarded value of the tender",
        es="Valor total homologado de la licitación",
        unit=BRL,
        original="valor_homologado_total",
    ),
    c(
        "indicador_pertence_14133",
        "BOOLEAN",
        "Indica se a licitação foi realizada sob a Lei 14.133/2021",
        en="Whether the tender was run under Law 14.133/2021",
        es="Indica si la licitación se realizó bajo la Ley 14.133/2021",
        obs="Durante a transição entre regimes algumas licitações da Lei 14.133 também "
        "aparecem no módulo legado",
        original="pertence14133",
    ),
    c(
        "data_publicacao",
        "DATE",
        "Data de publicação do aviso de licitação",
        en="Date the tender notice was published",
        es="Fecha de publicación del aviso de licitación",
        original="data_publicacao",
    ),
    c(
        "data_entrega_edital",
        "DATE",
        "Data de disponibilização do edital",
        en="Date the tender documents became available",
        es="Fecha de disponibilización del pliego",
        original="data_entrega_edital",
    ),
    c(
        "data_entrega_proposta",
        "DATE",
        "Data limite para entrega das propostas",
        en="Deadline for submitting proposals",
        es="Fecha límite para la entrega de propuestas",
        original="data_entrega_proposta",
    ),
    c(
        "data_abertura_proposta",
        "DATE",
        "Data de abertura das propostas",
        en="Date the proposals were opened",
        es="Fecha de apertura de las propuestas",
        original="data_abertura_proposta",
    ),
    c(
        "data_alteracao",
        "DATETIME",
        "Data e hora da última alteração do registro",
        en="Timestamp of the last change to the record",
        es="Fecha y hora de la última modificación del registro",
        original="dt_alteracao",
    ),
]

LICITACAO_PREGAO = [
    ano(
        "publicação do edital do pregão",
        "publication of the reverse auction notice",
        "publicación del pliego del pregón",
        "2000(1)2023",
    ),
    c(
        "id_compra",
        "STRING",
        "Identificador do pregão no SIASG",
        en="Identifier of the reverse auction in SIASG",
        es="Identificador del pregón en el SIASG",
        obs="Chave primária da tabela. Junta com a tabela licitacao, embora pregões sem "
        "data de publicação não apareçam lá",
        original="id_compra",
    ),
    c(
        "numero",
        "STRING",
        "Número do pregão",
        en="Number of the reverse auction",
        es="Número del pregón",
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="numero",
    ),
    c(
        "codigo_uasg",
        "STRING",
        "Código da UASG responsável pelo pregão",
        en="Code of the UASG running the reverse auction",
        es="Código de la UASG responsable del pregón",
        obs="Integralmente vazia nas amostras verificadas em 2026-08. O nome da unidade "
        "está em nome_uasg",
        original="co_uasg",
    ),
    c(
        "nome_uasg",
        "STRING",
        "Nome da UASG responsável pelo pregão",
        en="Name of the UASG running the reverse auction",
        es="Nombre de la UASG responsable del pregón",
        original="no_ausg",
    ),
    c(
        "codigo_orgao",
        "STRING",
        "Código do órgão responsável pelo pregão",
        en="Code of the body running the reverse auction",
        es="Código del órgano responsable del pregón",
        original="co_orgao",
    ),
    c(
        "nome_orgao",
        "STRING",
        "Nome do órgão responsável pelo pregão",
        en="Name of the body running the reverse auction",
        es="Nombre del órgano responsable del pregón",
        original="no_orgao",
    ),
    c(
        "numero_processo",
        "STRING",
        "Número do processo administrativo do pregão",
        en="Administrative case number of the reverse auction",
        es="Número del proceso administrativo del pregón",
        original="co_processo",
    ),
    c(
        "numero_portaria",
        "STRING",
        "Número da portaria que designou o pregoeiro",
        en="Number of the order appointing the auctioneer",
        es="Número de la resolución que designó al pregonero",
        original="co_portaria",
    ),
    c(
        "situacao_pregao",
        "STRING",
        "Situação do pregão, como aberto, homologado, revogado ou anulado",
        en="Status of the reverse auction, such as open, awarded, revoked or annulled",
        es="Situación del pregón, como abierto, homologado, revocado o anulado",
        original="ds_situacao_pregao",
    ),
    c(
        "tipo_pregao",
        "STRING",
        "Forma de realização do pregão, eletrônico ou presencial",
        en="How the reverse auction was run, electronic or in person",
        es="Forma de realización del pregón, electrónico o presencial",
        original="ds_tipo_pregao",
    ),
    c(
        "tipo_pregao_compra",
        "STRING",
        "Sistema de compra do pregão",
        en="Purchasing system of the reverse auction",
        es="Sistema de compra del pregón",
        dic=True,
        obs="SISPP preço praticado, SISRP registro de preços",
        original="ds_tipo_pregao_compra",
    ),
    c(
        "objeto",
        "STRING",
        "Descrição do objeto do pregão",
        en="Description of the reverse auction's subject matter",
        es="Descripción del objeto del pregón",
        original="tx_objeto",
    ),
    c(
        "valor_estimado_total",
        "FLOAT64",
        "Valor total estimado do pregão",
        en="Total estimated value of the reverse auction",
        es="Valor total estimado del pregón",
        unit=BRL,
        original="valor_estimado_total",
    ),
    c(
        "valor_homologado_total",
        "FLOAT64",
        "Valor total homologado do pregão",
        en="Total awarded value of the reverse auction",
        es="Valor total homologado del pregón",
        unit=BRL,
        original="valor_homologado_total",
    ),
    c(
        "indicador_pertence_14133",
        "BOOLEAN",
        "Indica se o pregão foi realizado sob a Lei 14.133/2021",
        en="Whether the reverse auction was run under Law 14.133/2021",
        es="Indica si el pregón se realizó bajo la Ley 14.133/2021",
        original="pertence14133",
    ),
    c(
        "data_portaria",
        "DATE",
        "Data da portaria que designou o pregoeiro",
        en="Date of the order appointing the auctioneer",
        es="Fecha de la resolución que designó al pregonero",
        original="dt_portaria",
    ),
    c(
        "data_edital",
        "DATE",
        "Data de publicação do edital do pregão",
        en="Date the reverse auction notice was published",
        es="Fecha de publicación del pliego del pregón",
        original="dt_data_edital",
    ),
    c(
        "data_inicio_proposta",
        "DATETIME",
        "Data e hora de abertura do prazo de propostas",
        en="Timestamp when the proposal window opened",
        es="Fecha y hora de apertura del plazo de propuestas",
        original="dt_inicio_proposta",
    ),
    c(
        "data_fim_proposta",
        "DATETIME",
        "Data e hora de encerramento do prazo de propostas",
        en="Timestamp when the proposal window closed",
        es="Fecha y hora de cierre del plazo de propuestas",
        original="dt_fim_proposta",
    ),
    c(
        "data_encerramento",
        "DATETIME",
        "Data e hora de encerramento do pregão",
        en="Timestamp when the reverse auction closed",
        es="Fecha y hora de cierre del pregón",
        original="dt_encerramento",
    ),
    c(
        "data_resultado",
        "DATETIME",
        "Data e hora do resultado do pregão",
        en="Timestamp of the reverse auction's result",
        es="Fecha y hora del resultado del pregón",
        original="dt_resultado",
    ),
    c(
        "data_alteracao",
        "DATETIME",
        "Data e hora da última alteração do registro",
        en="Timestamp of the last change to the record",
        es="Fecha y hora de la última modificación del registro",
        original="dt_alteracao",
    ),
]

LICITACAO_ITEM = [
    ano(
        "realização da licitação",
        "the tender",
        "la licitación",
        "1997(1)2025",
        obs="Coluna de particionamento. A fonte não publica data para o item, portanto o ano "
        "é extraído dos quatro últimos dígitos de id_compra",
    ),
    c(
        "id_compra",
        "STRING",
        "Identificador da licitação no SIASG",
        en="Identifier of the tender in SIASG",
        es="Identificador de la licitación en el SIASG",
        obs="Junta com a tabela licitacao",
        original="id_compra",
    ),
    c(
        "id_compra_item",
        "STRING",
        "Identificador do item da licitação no SIASG",
        en="Identifier of the tender item in SIASG",
        es="Identificador del ítem de la licitación en el SIASG",
        obs="Chave primária da tabela",
        original="id_compra_item",
    ),
    c(
        "numero_licitacao",
        "STRING",
        "Número da licitação publicado pela fonte",
        en="Tender number published by the source",
        es="Número de la licitación publicado por la fuente",
        original="numero_licitacao",
    ),
    c(
        "numero_item_licitacao",
        "STRING",
        "Número do item dentro da licitação",
        en="Item number within the tender",
        es="Número del ítem dentro de la licitación",
        original="numero_item_licitacao",
    ),
    c(
        "codigo_uasg",
        "STRING",
        "Código da UASG responsável pela licitação",
        en="Code of the UASG running the tender",
        es="Código de la UASG responsable de la licitación",
        original="uasg",
    ),
    c(
        "nome_uasg",
        "STRING",
        "Nome da UASG responsável pela licitação",
        en="Name of the UASG running the tender",
        es="Nombre de la UASG responsable de la licitación",
        original="nome_uasg",
    ),
    c(
        "numero_aviso",
        "STRING",
        "Número do aviso de licitação",
        en="Number of the tender notice",
        es="Número del aviso de licitación",
        original="numero_aviso",
    ),
    c(
        "codigo_modalidade",
        "STRING",
        "Código da modalidade de licitação no SIASG",
        en="SIASG code of the tender modality",
        es="Código de la modalidad de licitación en el SIASG",
        dic=True,
        original="modalidade",
    ),
    c(
        "modalidade",
        "STRING",
        "Modalidade de licitação",
        en="Tender modality",
        es="Modalidad de licitación",
        original="nome_modalidade",
    ),
    c(
        "codigo_item_material",
        "STRING",
        "Código do item no catálogo de materiais CATMAT",
        en="Code of the item in the CATMAT material catalogue",
        es="Código del ítem en el catálogo de materiales CATMAT",
        obs="Preenchido apenas quando o item é material",
        original="codigo_item_material",
    ),
    c(
        "nome_material",
        "STRING",
        "Nome do material licitado",
        en="Name of the tendered material",
        es="Nombre del material licitado",
        original="nome_material",
    ),
    c(
        "codigo_item_servico",
        "STRING",
        "Código do item no catálogo de serviços CATSER",
        en="Code of the item in the CATSER service catalogue",
        es="Código del ítem en el catálogo de servicios CATSER",
        obs="Preenchido apenas quando o item é serviço",
        original="codigo_item_servico",
    ),
    c(
        "nome_servico",
        "STRING",
        "Nome do serviço licitado",
        en="Name of the tendered service",
        es="Nombre del servicio licitado",
        original="nome_servico",
    ),
    c(
        "descricao_item",
        "STRING",
        "Descrição detalhada do item licitado",
        en="Detailed description of the tendered item",
        es="Descripción detallada del ítem licitado",
        original="descricao_item",
    ),
    c(
        "unidade",
        "STRING",
        "Unidade de fornecimento do item",
        en="Supply unit of the item",
        es="Unidad de suministro del ítem",
        original="unidade",
    ),
    c(
        "quantidade",
        "FLOAT64",
        "Quantidade licitada do item",
        en="Quantity of the item put out to tender",
        es="Cantidad licitada del ítem",
        unit="unit",
        original="quantidade",
    ),
    c(
        "valor_estimado",
        "FLOAT64",
        "Valor estimado do item",
        en="Estimated value of the item",
        es="Valor estimado del ítem",
        unit=BRL,
        original="valor_estimado",
    ),
    c(
        "criterio_julgamento",
        "STRING",
        "Critério de julgamento do item, como menor valor ou maior desconto",
        en="Award criterion for the item, such as lowest value or largest discount",
        es="Criterio de adjudicación del ítem, como menor valor o mayor descuento",
        original="criterio_julgamento",
    ),
    c(
        "beneficio",
        "STRING",
        "Tratamento diferenciado concedido a microempresas, empresas de pequeno porte e cooperativas",
        en="Preferential treatment granted to micro, small enterprises and cooperatives",
        es="Trato diferenciado concedido a microempresas, pequeñas empresas y cooperativas",
        original="beneficio",
    ),
    c(
        "cnpj_fornecedor",
        "STRING",
        "CNPJ do fornecedor vencedor do item",
        en="Taxpayer number of the supplier awarded the item",
        es="CNPJ del proveedor adjudicatario del ítem",
        original="cnpj_fornecedor",
    ),
    c(
        "nome_fornecedor",
        "STRING",
        "Razão social do fornecedor vencedor do item",
        en="Corporate name of the supplier awarded the item",
        es="Razón social del proveedor adjudicatario del ítem",
        original="nome_fornecedor",
    ),
    c(
        "cpf_vencedor",
        "STRING",
        "CPF mascarado do vencedor pessoa física",
        en="Masked taxpayer number of the individual winner",
        es="CPF enmascarado del ganador persona física",
        sensitive=True,
        obs="A fonte publica o CPF parcialmente mascarado. O valor ESTRANGEIRO indica "
        "vencedor sem CPF brasileiro",
        original="cpf_vencedor",
    ),
    c(
        "nome_vencedor_pessoa_fisica",
        "STRING",
        "Nome do vencedor pessoa física",
        en="Name of the individual winner",
        es="Nombre del ganador persona física",
        sensitive=True,
        original="nome_vencedor_pf",
    ),
    c(
        "indicador_decreto_7174",
        "STRING",
        "Indica se o item está sujeito às preferências do Decreto 7.174/2010",
        en="Whether the item is subject to the preferences of Decree 7,174/2010",
        es="Indica si el ítem está sujeto a las preferencias del Decreto 7.174/2010",
        dic=True,
        obs="O Decreto 7.174/2010 regula a preferência para bens e serviços de informática. "
        "A fonte publica o valor como texto true ou false, não como booleano",
        original="decreto_7174",
    ),
    c(
        "indicador_sustentavel",
        "STRING",
        "Indica se o item é classificado como sustentável",
        en="Whether the item is classified as sustainable",
        es="Indica si el ítem está clasificado como sostenible",
        dic=True,
        obs="A fonte publica o valor como 0 ou 1, não como booleano",
        original="sustentavel",
    ),
    c(
        "data_alteracao",
        "DATETIME",
        "Data e hora da última alteração do registro",
        en="Timestamp of the last change to the record",
        es="Fecha y hora de la última modificación del registro",
        original="dt_alteracao",
    ),
]

LICITACAO_ITEM_PREGAO = [
    ano(
        "homologação do item",
        "the item's award",
        "la homologación del ítem",
        "2000(1)2025",
    ),
    c(
        "id_compra",
        "STRING",
        "Identificador do pregão no SIASG",
        en="Identifier of the reverse auction in SIASG",
        es="Identificador del pregón en el SIASG",
        obs="Junta com as tabelas licitacao e licitacao_pregao",
        original="id_compra",
    ),
    c(
        "id_compra_item",
        "STRING",
        "Identificador do item do pregão no SIASG",
        en="Identifier of the reverse auction item in SIASG",
        es="Identificador del ítem del pregón en el SIASG",
        obs="Chave primária da tabela. Junta com licitacao_item",
        original="id_compra_item",
    ),
    c(
        "situacao_item",
        "STRING",
        "Situação do item, como homologado, cancelado no julgamento, deserto ou fracassado",
        en="Item status, such as awarded, cancelled at judgement, deserted or failed",
        es="Situación del ítem, como homologado, cancelado en el juicio, desierto o fracasado",
        original="situacao_item",
    ),
    c(
        "descricao_item",
        "STRING",
        "Descrição do item",
        en="Description of the item",
        es="Descripción del ítem",
        original="descricao_item",
    ),
    c(
        "descricao_detalhada_item",
        "STRING",
        "Descrição detalhada do item",
        en="Detailed description of the item",
        es="Descripción detallada del ítem",
        original="descricao_detalhada_item",
    ),
    c(
        "unidade_fornecimento",
        "STRING",
        "Unidade de fornecimento do item",
        en="Supply unit of the item",
        es="Unidad de suministro del ítem",
        original="unidade_fornecimento",
    ),
    c(
        "quantidade_item",
        "FLOAT64",
        "Quantidade licitada do item",
        en="Quantity of the item put out to tender",
        es="Cantidad licitada del ítem",
        unit="unit",
        original="quantidade_item",
    ),
    c(
        "valor_estimado_item",
        "FLOAT64",
        "Valor estimado do item",
        en="Estimated value of the item",
        es="Valor estimado del ítem",
        unit=BRL,
        original="valor_estimado_item",
    ),
    c(
        "menor_lance",
        "FLOAT64",
        "Menor lance ofertado para o item",
        en="Lowest bid offered for the item",
        es="Menor oferta presentada para el ítem",
        unit=BRL,
        original="menor_lance",
    ),
    c(
        "valor_negociado",
        "FLOAT64",
        "Valor obtido após negociação com o fornecedor",
        en="Value reached after negotiation with the supplier",
        es="Valor obtenido tras la negociación con el proveedor",
        unit=BRL,
        original="valor_negociado",
    ),
    c(
        "valor_homologado_item",
        "FLOAT64",
        "Valor homologado do item",
        en="Awarded value of the item",
        es="Valor homologado del ítem",
        unit=BRL,
        original="valor_homologado_item",
    ),
    c(
        "fornecedor_vencedor",
        "STRING",
        "Fornecedor vencedor do item",
        en="Supplier awarded the item",
        es="Proveedor adjudicatario del ítem",
        obs="Integralmente vazia nas amostras verificadas em 2026-08. O vencedor está "
        "disponível na tabela licitacao_item",
        original="fornecedor_vencedor",
    ),
    c(
        "nome_responsavel_adjudicacao",
        "STRING",
        "Nome do responsável pela adjudicação do item",
        en="Name of the official who adjudicated the item",
        es="Nombre del responsable de la adjudicación del ítem",
        original="no_adjudic",
    ),
    c(
        "nome_responsavel_homologacao",
        "STRING",
        "Nome do responsável pela homologação do item",
        en="Name of the official who awarded the item",
        es="Nombre del responsable de la homologación del ítem",
        original="no_hom",
    ),
    c(
        "indicador_decreto_7174",
        "STRING",
        "Indica se o item está sujeito às preferências do Decreto 7.174/2010",
        en="Whether the item is subject to the preferences of Decree 7,174/2010",
        es="Indica si el ítem está sujeto a las preferencias del Decreto 7.174/2010",
        dic=True,
        obs="A fonte publica o valor como texto TRUE ou FALSE, não como booleano",
        original="decreto_7174",
    ),
    c(
        "indicador_margem_preferencial",
        "STRING",
        "Indica se foi aplicada margem de preferência ao item",
        en="Whether a preference margin was applied to the item",
        es="Indica si se aplicó margen de preferencia al ítem",
        dic=True,
        obs="A fonte publica o valor como texto TRUE ou FALSE, não como booleano",
        original="margem_preferencial",
    ),
    c(
        "tratamento_diferenciado",
        "STRING",
        "Tratamento diferenciado concedido a microempresas e empresas de pequeno porte",
        en="Preferential treatment granted to micro and small enterprises",
        es="Trato diferenciado concedido a microempresas y pequeñas empresas",
        dic=True,
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="tratamento_diferenciado",
    ),
    c(
        "data_encerramento",
        "DATE",
        "Data de encerramento da disputa do item",
        en="Date the bidding for the item closed",
        es="Fecha de cierre de la disputa del ítem",
        original="dt_encerramento",
    ),
    c(
        "data_adjudicacao",
        "DATE",
        "Data de adjudicação do item",
        en="Date the item was adjudicated",
        es="Fecha de adjudicación del ítem",
        original="dt_adjudic",
    ),
    c(
        "data_homologacao",
        "DATE",
        "Data de homologação do item",
        en="Date the item was awarded",
        es="Fecha de homologación del ítem",
        original="dt_hom",
    ),
    c(
        "data_alteracao",
        "DATETIME",
        "Data e hora da última alteração do registro",
        en="Timestamp of the last change to the record",
        es="Fecha y hora de la última modificación del registro",
        original="dt_alteracao",
    ),
]

_SEM_LIC_COMUM = [
    c(
        "codigo_uasg",
        "STRING",
        "Código da UASG responsável pela contratação",
        en="Code of the UASG running the procurement",
        es="Código de la UASG responsable de la contratación",
        original="co_uasg",
    ),
    c(
        "codigo_orgao",
        "STRING",
        "Código do órgão responsável pela contratação",
        en="Code of the body running the procurement",
        es="Código del órgano responsable de la contratación",
        original="co_orgao",
    ),
    c(
        "numero_aviso",
        "STRING",
        "Número do aviso da contratação direta",
        en="Notice number of the direct contracting",
        es="Número del aviso de la contratación directa",
        original="nu_aviso_licitacao",
    ),
    c(
        "numero_processo",
        "STRING",
        "Número do processo administrativo",
        en="Administrative case number",
        es="Número del proceso administrativo",
        original="nu_processo",
    ),
    c(
        "codigo_modalidade",
        "STRING",
        "Código da modalidade da contratação direta",
        en="Code of the direct contracting modality",
        es="Código de la modalidad de la contratación directa",
        dic=True,
        obs="6 dispensa de licitação, 7 inexigibilidade de licitação",
        original="co_modalidade_licitacao",
    ),
    c(
        "quantidade_total_item",
        "INT64",
        "Quantidade total de itens da contratação",
        en="Total number of items in the procurement",
        es="Cantidad total de ítems de la contratación",
        unit="unit",
        original="qt_total_item",
    ),
    c(
        "objeto_licitacao",
        "STRING",
        "Descrição do objeto da contratação",
        en="Description of the procurement's subject matter",
        es="Descripción del objeto de la contratación",
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="ds_objeto_licitacao",
    ),
    c(
        "fundamento_legal",
        "STRING",
        "Dispositivo legal que fundamenta a contratação direta",
        en="Legal provision underpinning the direct contracting",
        es="Disposición legal que fundamenta la contratación directa",
        original="ds_fundamento_legal",
    ),
    c(
        "justificativa",
        "STRING",
        "Justificativa apresentada para a contratação direta",
        en="Justification given for the direct contracting",
        es="Justificación presentada para la contratación directa",
        original="ds_justificativa",
    ),
    c(
        "nome_responsavel_declaracao_dispensa",
        "STRING",
        "Nome do responsável pela declaração de dispensa ou inexigibilidade",
        en="Name of the official who declared the waiver",
        es="Nombre del responsable de la declaración de dispensa o inexigibilidad",
        original="no_responsavel_decl_disp",
    ),
    c(
        "cargo_responsavel_declaracao_dispensa",
        "STRING",
        "Cargo do responsável pela declaração de dispensa ou inexigibilidade",
        en="Role of the official who declared the waiver",
        es="Cargo del responsable de la declaración de dispensa o inexigibilidad",
        original="no_cargo_resp_decl_disp",
    ),
    c(
        "nome_responsavel_ratificacao",
        "STRING",
        "Nome do responsável pela ratificação",
        en="Name of the official who ratified the waiver",
        es="Nombre del responsable de la ratificación",
        original="no_responsavel_ratificacao",
    ),
    c(
        "cargo_responsavel_ratificacao",
        "STRING",
        "Cargo do responsável pela ratificação",
        en="Role of the official who ratified the waiver",
        es="Cargo del responsable de la ratificación",
        original="no_cargo_resp_ratificacao",
    ),
]

COMPRA_SEM_LICITACAO = [
    ano(
        "publicação do aviso de contratação direta",
        "publication of the direct contracting notice",
        "publicación del aviso de contratación directa",
        "1997(1)2024",
        obs="Coluna de particionamento, correspondente ao campo dt_ano_aviso da fonte",
    ),
    c(
        "id_compra",
        "STRING",
        "Identificador da contratação direta no SIASG",
        en="Identifier of the direct contracting in SIASG",
        es="Identificador de la contratación directa en el SIASG",
        obs="Chave primária da tabela",
        original="id_compra",
    ),
    *_SEM_LIC_COMUM,
    c(
        "nome_uasg",
        "STRING",
        "Nome da UASG responsável pela contratação",
        en="Name of the UASG running the procurement",
        es="Nombre de la UASG responsable de la contratación",
        original="no_ausg",
    ),
    c(
        "codigo_orgao_superior",
        "STRING",
        "Código do órgão superior na hierarquia administrativa",
        en="Code of the superior body in the administrative hierarchy",
        es="Código del órgano superior en la jerarquía administrativa",
        original="co_orgao_superior",
    ),
    c(
        "lei",
        "STRING",
        "Lei que rege a contratação direta",
        en="Law governing the direct contracting",
        es="Ley que rige la contratación directa",
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="ds_lei",
    ),
    c(
        "valor_estimado",
        "FLOAT64",
        "Valor total estimado da contratação direta",
        en="Total estimated value of the direct contracting",
        es="Valor total estimado de la contratación directa",
        unit=BRL,
        original="vr_estimado",
    ),
    c(
        "indicador_pertence_14133",
        "BOOLEAN",
        "Indica se a contratação foi realizada sob a Lei 14.133/2021",
        en="Whether the procurement was run under Law 14.133/2021",
        es="Indica si la contratación se realizó bajo la Ley 14.133/2021",
        original="pertence14133",
    ),
    c(
        "data_declaracao_dispensa",
        "DATE",
        "Data da declaração de dispensa ou inexigibilidade",
        en="Date the waiver was declared",
        es="Fecha de la declaración de dispensa o inexigibilidad",
        original="dt_declaracao_dispensa",
    ),
    c(
        "data_ratificacao",
        "DATE",
        "Data da ratificação da contratação direta",
        en="Date the direct contracting was ratified",
        es="Fecha de la ratificación de la contratación directa",
        original="dt_ratificacao",
    ),
    c(
        "data_publicacao",
        "DATE",
        "Data de publicação do aviso",
        en="Date the notice was published",
        es="Fecha de publicación del aviso",
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="dt_publicacao",
    ),
    c(
        "data_alteracao",
        "DATETIME",
        "Data e hora da última alteração do registro",
        en="Timestamp of the last change to the record",
        es="Fecha y hora de la última modificación del registro",
        original="dt_alteracao",
    ),
]

COMPRA_SEM_LICITACAO_ITEM = [
    ano(
        "publicação do aviso de contratação direta",
        "publication of the direct contracting notice",
        "publicación del aviso de contratación directa",
        "1997(1)2024",
        obs="Coluna de particionamento, correspondente ao campo dt_ano_aviso_licitacao da fonte",
    ),
    c(
        "id_compra",
        "STRING",
        "Identificador da contratação direta no SIASG",
        en="Identifier of the direct contracting in SIASG",
        es="Identificador de la contratación directa en el SIASG",
        obs="Junta com a tabela compra_sem_licitacao",
        original="id_compra",
    ),
    c(
        "id_compra_item",
        "STRING",
        "Identificador do item da contratação direta no SIASG",
        en="Identifier of the direct contracting item in SIASG",
        es="Identificador del ítem de la contratación directa en el SIASG",
        obs="Chave primária da tabela",
        original="id_compra_item",
    ),
    c(
        "numero_item_material",
        "STRING",
        "Número do item dentro da contratação",
        en="Item number within the procurement",
        es="Número del ítem dentro de la contratación",
        original="nu_item_material",
    ),
    *_SEM_LIC_COMUM,
    c(
        "modalidade",
        "STRING",
        "Modalidade da contratação direta, dispensa ou inexigibilidade",
        en="Direct contracting modality, waiver or non-enforceability",
        es="Modalidad de la contratación directa, dispensa o inexigibilidad",
        original="no_modalidade_licitacao",
    ),
    c(
        "numero_inciso",
        "STRING",
        "Inciso do dispositivo legal que fundamenta a contratação",
        en="Subsection of the legal provision underpinning the procurement",
        es="Inciso de la disposición legal que fundamenta la contratación",
        original="nu_inciso",
    ),
    c(
        "tipo_item",
        "STRING",
        "Indica se o item é material ou serviço",
        en="Whether the item is a material or a service",
        es="Indica si el ítem es material o servicio",
        dic=True,
        original="in_material_servico",
    ),
    c(
        "codigo_conjunto_materiais",
        "STRING",
        "Código do conjunto de materiais no CATMAT",
        en="Code of the material set in CATMAT",
        es="Código del conjunto de materiales en el CATMAT",
        obs="O valor 0 indica item que não é material",
        original="co_conjunto_materiais",
    ),
    c(
        "nome_conjunto_materiais",
        "STRING",
        "Nome do conjunto de materiais",
        en="Name of the material set",
        es="Nombre del conjunto de materiales",
        original="no_conjunto_materiais",
    ),
    c(
        "codigo_servico",
        "STRING",
        "Código do serviço no CATSER",
        en="Code of the service in CATSER",
        es="Código del servicio en el CATSER",
        original="co_servico",
    ),
    c(
        "nome_servico",
        "STRING",
        "Nome do serviço contratado",
        en="Name of the contracted service",
        es="Nombre del servicio contratado",
        original="no_servico",
    ),
    c(
        "descricao_detalhada",
        "STRING",
        "Descrição detalhada do item",
        en="Detailed description of the item",
        es="Descripción detallada del ítem",
        original="ds_detalhada",
    ),
    c(
        "marca_material",
        "STRING",
        "Marca do material adquirido",
        en="Brand of the purchased material",
        es="Marca del material adquirido",
        original="no_marca_material",
    ),
    c(
        "fabricante",
        "STRING",
        "Fabricante do material adquirido",
        en="Manufacturer of the purchased material",
        es="Fabricante del material adquirido",
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="ds_fabricante",
    ),
    c(
        "unidade_medida",
        "STRING",
        "Unidade de medida do item",
        en="Unit of measurement of the item",
        es="Unidad de medida del ítem",
        original="no_unidade_medida",
    ),
    c(
        "quantidade_material",
        "FLOAT64",
        "Quantidade contratada do item",
        en="Contracted quantity of the item",
        es="Cantidad contratada del ítem",
        unit="unit",
        original="qt_material_alt",
    ),
    c(
        "valor_estimado",
        "FLOAT64",
        "Valor total estimado da contratação direta",
        en="Total estimated value of the direct contracting",
        es="Valor total estimado de la contratación directa",
        unit=BRL,
        original="vr_estimado",
    ),
    c(
        "valor_estimado_item",
        "FLOAT64",
        "Valor estimado do item",
        en="Estimated value of the item",
        es="Valor estimado del ítem",
        unit=BRL,
        original="vr_estimado_item",
    ),
    c(
        "tipo_fornecedor_vencedor",
        "STRING",
        "Indica se o fornecedor vencedor é pessoa física ou jurídica",
        en="Whether the winning supplier is an individual or a legal entity",
        es="Indica si el proveedor adjudicatario es persona física o jurídica",
        dic=True,
        original="in_tipo_fornecedor_vencedor",
    ),
    c(
        "nome_fornecedor_vencedor",
        "STRING",
        "Nome ou razão social do fornecedor vencedor",
        en="Name of the winning supplier",
        es="Nombre o razón social del proveedor adjudicatario",
        original="no_fornecedor_vencedor",
    ),
    c(
        "cnpj_vencedor",
        "STRING",
        "CNPJ do fornecedor vencedor",
        en="Taxpayer number of the winning supplier",
        es="CNPJ del proveedor adjudicatario",
        original="nu_cnpj_vencedor",
    ),
    c(
        "cpf_vencedor",
        "STRING",
        "CPF mascarado do vencedor pessoa física",
        en="Masked taxpayer number of the individual winner",
        es="CPF enmascarado del ganador persona física",
        sensitive=True,
        obs="A fonte publica o CPF parcialmente mascarado, no formato ***308103**",
        original="nu_cpf_vencedor",
    ),
    c(
        "cpf_responsavel_declaracao_dispensa",
        "STRING",
        "CPF do responsável pela declaração de dispensa",
        en="Taxpayer number of the official who declared the waiver",
        es="CPF del responsable de la declaración de dispensa",
        sensitive=True,
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="nu_cpf_resp_decl_disp",
    ),
    c(
        "cpf_responsavel_ratificacao",
        "STRING",
        "CPF do responsável pela ratificação",
        en="Taxpayer number of the official who ratified the waiver",
        es="CPF del responsable de la ratificación",
        sensitive=True,
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="nu_cpf_resp_ratificacao",
    ),
    c(
        "cpf_responsavel_publicacao",
        "STRING",
        "CPF do responsável pela publicação",
        en="Taxpayer number of the official who published the notice",
        es="CPF del responsable de la publicación",
        sensitive=True,
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="nu_cpf_resp_publicacao",
    ),
    c(
        "data_publicacao",
        "DATE",
        "Data de publicação do aviso",
        en="Date the notice was published",
        es="Fecha de publicación del aviso",
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="dt_publicacao",
    ),
    c(
        "data_alteracao",
        "DATETIME",
        "Data e hora da última alteração do registro",
        en="Timestamp of the last change to the record",
        es="Fecha y hora de la última modificación del registro",
        original="dt_alteracao",
    ),
]

TABLES = {
    "licitacao": LICITACAO,
    "licitacao_pregao": LICITACAO_PREGAO,
    "licitacao_item": LICITACAO_ITEM,
    "licitacao_item_pregao": LICITACAO_ITEM_PREGAO,
    "compra_sem_licitacao": COMPRA_SEM_LICITACAO,
    "compra_sem_licitacao_item": COMPRA_SEM_LICITACAO_ITEM,
}
