"""Architecture for the contratação result and ata de registro de preço tables."""

from arch_common import BRL, DIR_ANO, DIR_UF, c

COB_RES = "2021(1)2026"
COB_ARP = "2023(1)2027"


def ano(source: str, en_src: str, es_src: str, coverage: str) -> dict:
    return c(
        "ano",
        "INT64",
        f"Ano de {source}",
        en=f"Year of {en_src}",
        es=f"Año de {es_src}",
        directory=DIR_ANO,
        unit="year",
        coverage=coverage,
        obs="Coluna de particionamento, derivada da data correspondente",
    )


CONTRATACAO_ITEM_RESULTADO = [
    ano(
        "divulgação do resultado no PNCP",
        "the result's publication on PNCP",
        "la divulgación del resultado en el PNCP",
        COB_RES,
    ),
    c(
        "sigla_uf",
        "STRING",
        "Sigla da unidade da federação da unidade compradora",
        en="Abbreviation of the purchasing unit's federative unit",
        es="Sigla de la unidad federativa de la unidad compradora",
        obs="O valor EX identifica unidades sediadas no exterior",
        directory=DIR_UF,
        original="unidadeOrgaoUfSigla",
    ),
    c(
        "id_compra",
        "STRING",
        "Identificador da contratação no SIASG",
        en="Identifier of the procurement in SIASG",
        es="Identificador de la contratación en el SIASG",
        original="idCompra",
    ),
    c(
        "id_compra_item",
        "STRING",
        "Identificador do item da contratação no SIASG",
        en="Identifier of the procurement item in SIASG",
        es="Identificador del ítem de la contratación en el SIASG",
        obs="Junta com a tabela contratacao_item",
        original="idCompraItem",
    ),
    c(
        "sequencial_resultado",
        "STRING",
        "Número sequencial do resultado dentro do item",
        en="Sequential number of the result within the item",
        es="Número secuencial del resultado dentro del ítem",
        obs="Um item pode ter mais de um resultado, por exemplo em registro de preços com "
        "vários fornecedores classificados. Com id_compra_item forma a chave primária",
        original="sequencialResultado",
    ),
    c(
        "numero_controle_pncp",
        "STRING",
        "Número de controle da contratação no PNCP",
        en="PNCP control number of the procurement",
        es="Número de control de la contratación en el PNCP",
        original="numeroControlePNCPCompra",
    ),
    c(
        "id_contratacao_pncp",
        "STRING",
        "Número de controle da contratação no PNCP repetido pela fonte",
        en="PNCP control number of the procurement, repeated by the source",
        es="Número de control de la contratación en el PNCP, repetido por la fuente",
        original="idContratacaoPNCP",
    ),
    c(
        "numero_item_pncp",
        "STRING",
        "Número do item na contratação segundo o PNCP",
        en="Item number within the procurement according to PNCP",
        es="Número del ítem en la contratación según el PNCP",
        original="numeroItemPncp",
    ),
    c(
        "cnpj_orgao",
        "STRING",
        "CNPJ do órgão comprador",
        en="Taxpayer number of the purchasing body",
        es="CNPJ del órgano comprador",
        original="orgaoEntidadeCnpj",
    ),
    c(
        "codigo_unidade",
        "STRING",
        "Código da UASG compradora",
        en="Code of the purchasing UASG",
        es="Código de la UASG compradora",
        original="unidadeOrgaoCodigoUnidade",
    ),
    c(
        "id_fornecedor",
        "STRING",
        "CNPJ ou CPF do fornecedor",
        en="Taxpayer number of the supplier",
        es="CNPJ o CPF del proveedor",
        original="niFornecedor",
    ),
    c(
        "nome_fornecedor",
        "STRING",
        "Nome ou razão social do fornecedor",
        en="Name of the supplier",
        es="Nombre o razón social del proveedor",
        original="nomeRazaoSocialFornecedor",
    ),
    c(
        "tipo_pessoa",
        "STRING",
        "Indica se o fornecedor é pessoa física ou jurídica",
        en="Whether the supplier is an individual or a legal entity",
        es="Indica si el proveedor es persona física o jurídica",
        dic=True,
        obs="PF pessoa física, PJ pessoa jurídica, PE pessoa estrangeira",
        original="tipoPessoa",
    ),
    c(
        "codigo_pais",
        "STRING",
        "Código ISO de três letras do país do fornecedor",
        en="Three-letter ISO code of the supplier's country",
        es="Código ISO de tres letras del país del proveedor",
        original="codigoPais",
    ),
    c(
        "id_porte_fornecedor",
        "STRING",
        "Código do porte do fornecedor",
        en="Code of the supplier's size band",
        es="Código del tamaño del proveedor",
        dic=True,
        original="porteFornecedorId",
    ),
    c(
        "porte_fornecedor",
        "STRING",
        "Porte do fornecedor",
        en="Size band of the supplier",
        es="Tamaño del proveedor",
        original="porteFornecedorNome",
    ),
    c(
        "id_natureza_juridica",
        "STRING",
        "Código da natureza jurídica do fornecedor",
        en="Code of the supplier's legal nature",
        es="Código de la naturaleza jurídica del proveedor",
        dic=True,
        original="naturezaJuridicaId",
    ),
    c(
        "natureza_juridica",
        "STRING",
        "Natureza jurídica do fornecedor",
        en="Legal nature of the supplier",
        es="Naturaleza jurídica del proveedor",
        original="naturezaJuridicaNome",
    ),
    c(
        "ordem_classificacao_srp",
        "STRING",
        "Posição do fornecedor na classificação do sistema de registro de preços",
        en="Rank of the supplier in the price registration system classification",
        es="Posición del proveedor en la clasificación del sistema de registro de precios",
        original="ordemClassificacaoSrp",
    ),
    c(
        "id_situacao_resultado",
        "STRING",
        "Código da situação do resultado",
        en="Code of the result status",
        es="Código de la situación del resultado",
        dic=True,
        original="situacaoCompraItemResultadoId",
    ),
    c(
        "situacao_resultado",
        "STRING",
        "Situação do resultado, como informado ou cancelado",
        en="Result status, such as reported or cancelled",
        es="Situación del resultado, como informado o cancelado",
        original="situacaoCompraItemResultadoNome",
    ),
    c(
        "motivo_cancelamento",
        "STRING",
        "Motivo do cancelamento do resultado",
        en="Reason the result was cancelled",
        es="Motivo de la cancelación del resultado",
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="motivoCancelamento",
    ),
    c(
        "quantidade_homologada",
        "FLOAT64",
        "Quantidade homologada para o fornecedor",
        en="Quantity awarded to the supplier",
        es="Cantidad homologada para el proveedor",
        unit="unit",
        original="quantidadeHomologada",
    ),
    c(
        "valor_unitario_homologado",
        "FLOAT64",
        "Valor unitário homologado",
        en="Awarded unit value",
        es="Valor unitario homologado",
        unit=BRL,
        original="valorUnitarioHomologado",
    ),
    c(
        "valor_total_homologado",
        "FLOAT64",
        "Valor total homologado",
        en="Total awarded value",
        es="Valor total homologado",
        unit=BRL,
        original="valorTotalHomologado",
    ),
    c(
        "percentual_desconto",
        "FLOAT64",
        "Percentual de desconto ofertado pelo fornecedor",
        en="Discount percentage offered by the supplier",
        es="Porcentaje de descuento ofrecido por el proveedor",
        unit="percent",
        original="percentualDesconto",
    ),
    c(
        "id_amparo_legal_margem_preferencia",
        "STRING",
        "Código do amparo legal da margem de preferência aplicada",
        en="Code of the legal basis for the applied preference margin",
        es="Código del amparo legal del margen de preferencia aplicado",
        dic=True,
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="amparoLegalMargemPreferenciaId",
    ),
    c(
        "amparo_legal_margem_preferencia",
        "STRING",
        "Dispositivo legal que ampara a margem de preferência aplicada",
        en="Legal provision supporting the applied preference margin",
        es="Disposición legal que ampara el margen de preferencia aplicado",
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="amparoLegalMargemPreferenciaNome",
    ),
    c(
        "id_amparo_legal_criterio_desempate",
        "STRING",
        "Código do amparo legal do critério de desempate aplicado",
        en="Code of the legal basis for the applied tie-break criterion",
        es="Código del amparo legal del criterio de desempate aplicado",
        dic=True,
        original="amparoLegalCriterioDesempateId",
    ),
    c(
        "amparo_legal_criterio_desempate",
        "STRING",
        "Dispositivo legal que ampara o critério de desempate aplicado",
        en="Legal provision supporting the applied tie-break criterion",
        es="Disposición legal que ampara el criterio de desempate aplicado",
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="amparoLegalCriterioDesempateNome",
    ),
    c(
        "id_moeda_estrangeira",
        "STRING",
        "Código da moeda estrangeira da proposta",
        en="Code of the proposal's foreign currency",
        es="Código de la moneda extranjera de la propuesta",
        dic=True,
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="moedaEstrangeiraId",
    ),
    c(
        "valor_nominal_moeda_estrangeira",
        "FLOAT64",
        "Valor nominal da proposta em moeda estrangeira",
        en="Nominal value of the proposal in foreign currency",
        es="Valor nominal de la propuesta en moneda extranjera",
        unit="foreign_currency_unit",
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="valorNominalMoedaEstrangeira",
    ),
    c(
        "data_cotacao_moeda_estrangeira",
        "DATETIME",
        "Data e hora da cotação da moeda estrangeira",
        en="Timestamp of the foreign currency quotation",
        es="Fecha y hora de la cotización de la moneda extranjera",
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="dataCotacaoMoedaEstrangeira",
    ),
    c(
        "timezone_cotacao_moeda_estrangeira",
        "STRING",
        "Fuso horário da cotação da moeda estrangeira",
        en="Time zone of the foreign currency quotation",
        es="Zona horaria de la cotización de la moneda extranjera",
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="timezoneCotacaoMoedaEstrangeira",
    ),
    c(
        "id_pais_origem_produto_servico",
        "STRING",
        "Código do país de origem do produto ou serviço",
        en="Code of the product or service country of origin",
        es="Código del país de origen del producto o servicio",
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="paisOrigemProdutoServicoId",
    ),
    c(
        "indicador_subcontratacao",
        "BOOLEAN",
        "Indica se há subcontratação no resultado",
        en="Whether the result involves subcontracting",
        es="Indica si hay subcontratación en el resultado",
        original="indicadorSubcontratacao",
    ),
    c(
        "indicador_aplicacao_margem_preferencia",
        "BOOLEAN",
        "Indica se foi aplicada margem de preferência",
        en="Whether a preference margin was applied",
        es="Indica si se aplicó margen de preferencia",
        original="aplicacaoMargemPreferencia",
    ),
    c(
        "indicador_aplicacao_beneficio_meepp",
        "BOOLEAN",
        "Indica se foi aplicado benefício para microempresas e empresas de pequeno porte",
        en="Whether the micro and small enterprise benefit was applied",
        es="Indica si se aplicó el beneficio para microempresas y pequeñas empresas",
        original="aplicacaoBeneficioMeepp",
    ),
    c(
        "indicador_aplicacao_criterio_desempate",
        "BOOLEAN",
        "Indica se foi aplicado critério de desempate",
        en="Whether a tie-break criterion was applied",
        es="Indica si se aplicó criterio de desempate",
        original="aplicacaoCriterioDesempate",
    ),
    c(
        "data_resultado_pncp",
        "DATETIME",
        "Data e hora do resultado no PNCP",
        en="Timestamp of the result on PNCP",
        es="Fecha y hora del resultado en el PNCP",
        original="dataResultadoPncp",
    ),
    c(
        "data_inclusao_pncp",
        "DATETIME",
        "Data e hora de inclusão do resultado no PNCP",
        en="Timestamp when the result was added to PNCP",
        es="Fecha y hora de inclusión del resultado en el PNCP",
        original="dataInclusaoPncp",
    ),
    c(
        "data_atualizacao_pncp",
        "DATETIME",
        "Data e hora da última atualização do resultado no PNCP",
        en="Timestamp of the last update to the result on PNCP",
        es="Fecha y hora de la última actualización del resultado en el PNCP",
        original="dataAtualizacaoPncp",
    ),
    c(
        "data_cancelamento_pncp",
        "DATETIME",
        "Data e hora do cancelamento do resultado no PNCP",
        en="Timestamp when the result was cancelled on PNCP",
        es="Fecha y hora de la cancelación del resultado en el PNCP",
        original="dataCancelamentoPncp",
    ),
]

ATA_REGISTRO_PRECO = [
    ano(
        "início da vigência da ata",
        "the start of the price record's validity",
        "el inicio de la vigencia del acta",
        COB_ARP,
    ),
    c(
        "numero_controle_pncp_ata",
        "STRING",
        "Número de controle da ata no PNCP",
        en="PNCP control number of the price record",
        es="Número de control del acta en el PNCP",
        obs="Chave primária da tabela",
        original="numeroControlePncpAta",
    ),
    c(
        "numero_ata_registro_preco",
        "STRING",
        "Número da ata de registro de preços",
        en="Number of the price record",
        es="Número del acta de registro de precios",
        original="numeroAtaRegistroPreco",
    ),
    c(
        "numero_controle_pncp_compra",
        "STRING",
        "Número de controle da contratação de origem no PNCP",
        en="PNCP control number of the originating procurement",
        es="Número de control de la contratación de origen en el PNCP",
        original="numeroControlePncpCompra",
    ),
    c(
        "id_compra",
        "STRING",
        "Identificador da contratação de origem no SIASG",
        en="Identifier of the originating procurement in SIASG",
        es="Identificador de la contratación de origen en el SIASG",
        obs="Junta com a tabela contratacao",
        original="idCompra",
    ),
    c(
        "numero_compra",
        "STRING",
        "Número da contratação de origem",
        en="Number of the originating procurement",
        es="Número de la contratación de origen",
        original="numeroCompra",
    ),
    c(
        "ano_compra",
        "INT64",
        "Ano da contratação de origem",
        en="Year of the originating procurement",
        es="Año de la contratación de origen",
        unit="year",
        original="anoCompra",
    ),
    c(
        "codigo_unidade_gerenciadora",
        "STRING",
        "Código da UASG gerenciadora da ata",
        en="Code of the UASG managing the price record",
        es="Código de la UASG gestora del acta",
        original="codigoUnidadeGerenciadora",
    ),
    c(
        "nome_unidade_gerenciadora",
        "STRING",
        "Nome da UASG gerenciadora da ata",
        en="Name of the UASG managing the price record",
        es="Nombre de la UASG gestora del acta",
        original="nomeUnidadeGerenciadora",
    ),
    c(
        "codigo_orgao",
        "STRING",
        "Código do órgão gerenciador no SIASG",
        en="SIASG code of the managing body",
        es="Código del órgano gestor en el SIASG",
        original="codigoOrgao",
    ),
    c(
        "nome_orgao",
        "STRING",
        "Nome do órgão gerenciador",
        en="Name of the managing body",
        es="Nombre del órgano gestor",
        original="nomeOrgao",
    ),
    c(
        "codigo_modalidade_compra",
        "STRING",
        "Código da modalidade da contratação de origem",
        en="Code of the originating procurement's modality",
        es="Código de la modalidad de la contratación de origen",
        dic=True,
        original="codigoModalidadeCompra",
    ),
    c(
        "modalidade_compra",
        "STRING",
        "Modalidade da contratação de origem",
        en="Modality of the originating procurement",
        es="Modalidad de la contratación de origen",
        original="nomeModalidadeCompra",
    ),
    c(
        "status_ata",
        "STRING",
        "Situação da ata, como vigente ou cancelada",
        en="Status of the price record, such as in force or cancelled",
        es="Situación del acta, como vigente o cancelada",
        original="statusAta",
    ),
    c(
        "objeto",
        "STRING",
        "Descrição do objeto da ata de registro de preços",
        en="Description of the price record's subject matter",
        es="Descripción del objeto del acta de registro de precios",
        original="objeto",
    ),
    c(
        "quantidade_itens",
        "INT64",
        "Quantidade de itens registrados na ata",
        en="Number of items recorded in the price record",
        es="Cantidad de ítems registrados en el acta",
        unit="unit",
        original="quantidadeItens",
    ),
    c(
        "valor_total",
        "FLOAT64",
        "Valor total registrado na ata",
        en="Total value recorded in the price record",
        es="Valor total registrado en el acta",
        unit=BRL,
        original="valorTotal",
    ),
    c(
        "link_ata_pncp",
        "STRING",
        "Endereço da ata no portal do PNCP",
        en="URL of the price record on the PNCP portal",
        es="Dirección del acta en el portal del PNCP",
        original="linkAtaPNCP",
    ),
    c(
        "link_compra_pncp",
        "STRING",
        "Endereço da contratação de origem no portal do PNCP",
        en="URL of the originating procurement on the PNCP portal",
        es="Dirección de la contratación de origen en el portal del PNCP",
        original="linkCompraPNCP",
    ),
    c(
        "indicador_ata_excluida",
        "BOOLEAN",
        "Indica se a ata foi excluída do PNCP",
        en="Whether the price record was deleted from PNCP",
        es="Indica si el acta fue excluida del PNCP",
        original="ataExcluido",
    ),
    c(
        "data_assinatura",
        "DATE",
        "Data de assinatura da ata",
        en="Date the price record was signed",
        es="Fecha de firma del acta",
        original="dataAssinatura",
    ),
    c(
        "data_vigencia_inicial",
        "DATE",
        "Data de início da vigência da ata",
        en="Start date of the price record's validity",
        es="Fecha de inicio de la vigencia del acta",
        original="dataVigenciaInicial",
    ),
    c(
        "data_vigencia_final",
        "DATE",
        "Data de término da vigência da ata",
        en="End date of the price record's validity",
        es="Fecha de término de la vigencia del acta",
        original="dataVigenciaFinal",
    ),
    c(
        "data_hora_inclusao",
        "DATETIME",
        "Data e hora de inclusão da ata no PNCP",
        en="Timestamp when the price record was added to PNCP",
        es="Fecha y hora de inclusión del acta en el PNCP",
        original="dataHoraInclusao",
    ),
    c(
        "data_hora_atualizacao",
        "DATETIME",
        "Data e hora da última atualização da ata no PNCP",
        en="Timestamp of the last update to the price record on PNCP",
        es="Fecha y hora de la última actualización del acta en el PNCP",
        original="dataHoraAtualizacao",
    ),
    c(
        "data_hora_exclusao",
        "DATETIME",
        "Data e hora da exclusão da ata do PNCP",
        en="Timestamp when the price record was deleted from PNCP",
        es="Fecha y hora de la exclusión del acta del PNCP",
        obs="Preenchida apenas nos registros excluídos, menos de 2% do total",
        original="dataHoraExclusao",
    ),
]

ATA_REGISTRO_PRECO_ITEM = [
    ano(
        "início da vigência da ata",
        "the start of the price record's validity",
        "el inicio de la vigencia del acta",
        COB_ARP,
    ),
    c(
        "numero_controle_pncp_ata",
        "STRING",
        "Número de controle da ata no PNCP",
        en="PNCP control number of the price record",
        es="Número de control del acta en el PNCP",
        obs="Junta com a tabela ata_registro_preco",
        original="numeroControlePncpAta",
    ),
    c(
        "numero_item",
        "STRING",
        "Número do item dentro da ata",
        en="Item number within the price record",
        es="Número del ítem dentro del acta",
        obs="Com numero_controle_pncp_ata e classificacao_fornecedor forma a chave primária",
        original="numeroItem",
    ),
    c(
        "classificacao_fornecedor",
        "STRING",
        "Posição do fornecedor na classificação do item",
        en="Rank of the supplier for the item",
        es="Posición del proveedor en la clasificación del ítem",
        obs="Um item pode registrar vários fornecedores classificados",
        original="classificacaoFornecedor",
    ),
    c(
        "numero_ata_registro_preco",
        "STRING",
        "Número da ata de registro de preços",
        en="Number of the price record",
        es="Número del acta de registro de precios",
        original="numeroAtaRegistroPreco",
    ),
    c(
        "numero_controle_pncp_compra",
        "STRING",
        "Número de controle da contratação de origem no PNCP",
        en="PNCP control number of the originating procurement",
        es="Número de control de la contratación de origen en el PNCP",
        original="numeroControlePncpCompra",
    ),
    c(
        "id_compra",
        "STRING",
        "Identificador da contratação de origem no SIASG",
        en="Identifier of the originating procurement in SIASG",
        es="Identificador de la contratación de origen en el SIASG",
        original="idCompra",
    ),
    c(
        "numero_compra",
        "STRING",
        "Número da contratação de origem",
        en="Number of the originating procurement",
        es="Número de la contratación de origen",
        original="numeroCompra",
    ),
    c(
        "ano_compra",
        "INT64",
        "Ano da contratação de origem",
        en="Year of the originating procurement",
        es="Año de la contratación de origen",
        unit="year",
        original="anoCompra",
    ),
    c(
        "codigo_unidade_gerenciadora",
        "STRING",
        "Código da UASG gerenciadora da ata",
        en="Code of the UASG managing the price record",
        es="Código de la UASG gestora del acta",
        original="codigoUnidadeGerenciadora",
    ),
    c(
        "nome_unidade_gerenciadora",
        "STRING",
        "Nome da UASG gerenciadora da ata",
        en="Name of the UASG managing the price record",
        es="Nombre de la UASG gestora del acta",
        original="nomeUnidadeGerenciadora",
    ),
    c(
        "codigo_modalidade_compra",
        "STRING",
        "Código da modalidade da contratação de origem",
        en="Code of the originating procurement's modality",
        es="Código de la modalidad de la contratación de origen",
        dic=True,
        original="codigoModalidadeCompra",
    ),
    c(
        "modalidade_compra",
        "STRING",
        "Modalidade da contratação de origem",
        en="Modality of the originating procurement",
        es="Modalidad de la contratación de origen",
        original="nomeModalidadeCompra",
    ),
    c(
        "codigo_item",
        "STRING",
        "Código do item nos catálogos CATMAT ou CATSER",
        en="Code of the item in the CATMAT or CATSER catalogues",
        es="Código del ítem en los catálogos CATMAT o CATSER",
        original="codigoItem",
    ),
    c(
        "descricao_item",
        "STRING",
        "Descrição do item registrado",
        en="Description of the recorded item",
        es="Descripción del ítem registrado",
        original="descricaoItem",
    ),
    c(
        "tipo_item",
        "STRING",
        "Indica se o item é material ou serviço",
        en="Whether the item is a material or a service",
        es="Indica si el ítem es material o servicio",
        original="tipoItem",
    ),
    c(
        "codigo_pdm",
        "STRING",
        "Código do Padrão Descritivo de Material do item",
        en="Code of the item's material descriptive standard",
        es="Código del Patrón Descriptivo de Material del ítem",
        original="codigoPdm",
    ),
    c(
        "nome_pdm",
        "STRING",
        "Nome do Padrão Descritivo de Material do item",
        en="Name of the item's material descriptive standard",
        es="Nombre del Patrón Descriptivo de Material del ítem",
        original="nomePdm",
    ),
    c(
        "id_fornecedor",
        "STRING",
        "CNPJ ou CPF do fornecedor registrado",
        en="Taxpayer number of the recorded supplier",
        es="CNPJ o CPF del proveedor registrado",
        original="niFornecedor",
    ),
    c(
        "nome_fornecedor",
        "STRING",
        "Nome ou razão social do fornecedor registrado",
        en="Name of the recorded supplier",
        es="Nombre o razón social del proveedor registrado",
        original="nomeRazaoSocialFornecedor",
    ),
    c(
        "situacao_sicaf",
        "STRING",
        "Código da situação do fornecedor no SICAF",
        en="Code of the supplier's status in SICAF",
        es="Código de la situación del proveedor en el SICAF",
        dic=True,
        original="situacaoSicaf",
    ),
    c(
        "quantidade_homologada_item",
        "FLOAT64",
        "Quantidade total homologada para o item",
        en="Total quantity awarded for the item",
        es="Cantidad total homologada para el ítem",
        unit="unit",
        original="quantidadeHomologadaItem",
    ),
    c(
        "quantidade_homologada_vencedor",
        "FLOAT64",
        "Quantidade homologada para este fornecedor",
        en="Quantity awarded to this supplier",
        es="Cantidad homologada para este proveedor",
        unit="unit",
        original="quantidadeHomologadaVencedor",
    ),
    c(
        "quantidade_empenhada",
        "FLOAT64",
        "Quantidade já empenhada do item",
        en="Quantity of the item already committed",
        es="Cantidad ya comprometida del ítem",
        unit="unit",
        original="quantidadeEmpenhada",
    ),
    c(
        "maximo_adesao",
        "FLOAT64",
        "Quantidade máxima permitida para adesões de outras unidades",
        en="Maximum quantity allowed for other units to piggyback on the record",
        es="Cantidad máxima permitida para adhesiones de otras unidades",
        unit="unit",
        original="maximoAdesao",
    ),
    c(
        "valor_unitario",
        "FLOAT64",
        "Valor unitário registrado",
        en="Recorded unit value",
        es="Valor unitario registrado",
        unit=BRL,
        original="valorUnitario",
    ),
    c(
        "valor_total",
        "FLOAT64",
        "Valor total registrado para o item",
        en="Total recorded value for the item",
        es="Valor total registrado para el ítem",
        unit=BRL,
        original="valorTotal",
    ),
    c(
        "percentual_maior_desconto",
        "FLOAT64",
        "Maior percentual de desconto registrado para o item",
        en="Largest discount percentage recorded for the item",
        es="Mayor porcentaje de descuento registrado para el ítem",
        unit="percent",
        original="percentualMaiorDesconto",
    ),
    c(
        "indicador_item_excluido",
        "BOOLEAN",
        "Indica se o item foi excluído do PNCP",
        en="Whether the item was deleted from PNCP",
        es="Indica si el ítem fue excluido del PNCP",
        original="itemExcluido",
    ),
    c(
        "data_assinatura",
        "DATE",
        "Data de assinatura da ata",
        en="Date the price record was signed",
        es="Fecha de firma del acta",
        original="dataAssinatura",
    ),
    c(
        "data_vigencia_inicial",
        "DATE",
        "Data de início da vigência da ata",
        en="Start date of the price record's validity",
        es="Fecha de inicio de la vigencia del acta",
        original="dataVigenciaInicial",
    ),
    c(
        "data_vigencia_final",
        "DATE",
        "Data de término da vigência da ata",
        en="End date of the price record's validity",
        es="Fecha de término de la vigencia del acta",
        original="dataVigenciaFinal",
    ),
    c(
        "data_hora_inclusao",
        "DATETIME",
        "Data e hora de inclusão do item no PNCP",
        en="Timestamp when the item was added to PNCP",
        es="Fecha y hora de inclusión del ítem en el PNCP",
        original="dataHoraInclusao",
    ),
    c(
        "data_hora_atualizacao",
        "DATETIME",
        "Data e hora da última atualização do item no PNCP",
        en="Timestamp of the last update to the item on PNCP",
        es="Fecha y hora de la última actualización del ítem en el PNCP",
        original="dataHoraAtualizacao",
    ),
    c(
        "data_hora_exclusao",
        "DATETIME",
        "Data e hora da exclusão do item do PNCP",
        en="Timestamp when the item was deleted from PNCP",
        es="Fecha y hora de la exclusión del ítem del PNCP",
        obs="Preenchida apenas nos registros excluídos, menos de 2% do total",
        original="dataHoraExclusao",
    ),
]

TABLES = {
    "contratacao_item_resultado": CONTRATACAO_ITEM_RESULTADO,
    "ata_registro_preco": ATA_REGISTRO_PRECO,
    "ata_registro_preco_item": ATA_REGISTRO_PRECO_ITEM,
}
