"""Architecture for the registry and catalogue tables (snapshot, partitioned by data_extracao)."""

from arch_common import DIR_MUNICIPIO, DIR_UF, c

DATA_EXTRACAO = c(
    "data_extracao",
    "DATE",
    "Data em que o registro foi extraído da API Compras.gov.br",
    en="Date on which the record was extracted from the Compras.gov.br API",
    es="Fecha en que el registro fue extraído de la API Compras.gov.br",
    obs="Coluna de particionamento. A fonte publica apenas o estado corrente do cadastro, "
    "sem histórico, portanto cada extração é uma fotografia",
)

ORGAO = [
    DATA_EXTRACAO,
    c(
        "codigo_orgao",
        "STRING",
        "Código do órgão no SIASG",
        en="Code of the government body in SIASG",
        es="Código del órgano en el SIASG",
        original="codigoOrgao",
    ),
    c(
        "cnpj_orgao",
        "STRING",
        "CNPJ ou CPF do órgão",
        en="Taxpayer number (CNPJ or CPF) of the government body",
        es="CNPJ o CPF del órgano",
        obs="O valor 0 indica órgão sem CNPJ próprio, como as agregações regionais",
        original="cnpjCpfOrgao",
    ),
    c(
        "nome_orgao",
        "STRING",
        "Nome do órgão",
        en="Name of the government body",
        es="Nombre del órgano",
        original="nomeOrgao",
    ),
    c(
        "nome_mnemonico_orgao",
        "STRING",
        "Nome abreviado do órgão usado no SIASG",
        en="Short name of the government body used in SIASG",
        es="Nombre abreviado del órgano usado en el SIASG",
        original="nomeMnemonicoOrgao",
    ),
    c(
        "codigo_orgao_vinculado",
        "STRING",
        "Código do órgão ao qual este é vinculado",
        en="Code of the body this one is attached to",
        es="Código del órgano al que este está vinculado",
        original="codigoOrgaoVinculado",
    ),
    c(
        "cnpj_orgao_vinculado",
        "STRING",
        "CNPJ ou CPF do órgão vinculado",
        en="Taxpayer number of the attached-to body",
        es="CNPJ o CPF del órgano vinculado",
        original="cnpjCpfOrgaoVinculado",
    ),
    c(
        "nome_orgao_vinculado",
        "STRING",
        "Nome do órgão vinculado",
        en="Name of the attached-to body",
        es="Nombre del órgano vinculado",
        original="nomeOrgaoVinculado",
    ),
    c(
        "codigo_orgao_superior",
        "STRING",
        "Código do órgão superior na hierarquia administrativa",
        en="Code of the superior body in the administrative hierarchy",
        es="Código del órgano superior en la jerarquía administrativa",
        original="codigoOrgaoSuperior",
    ),
    c(
        "cnpj_orgao_superior",
        "STRING",
        "CNPJ ou CPF do órgão superior",
        en="Taxpayer number of the superior body",
        es="CNPJ o CPF del órgano superior",
        original="cnpjCpfOrgaoSuperior",
    ),
    c(
        "nome_orgao_superior",
        "STRING",
        "Nome do órgão superior",
        en="Name of the superior body",
        es="Nombre del órgano superior",
        original="nomeOrgaoSuperior",
    ),
    c(
        "codigo_tipo_administracao",
        "STRING",
        "Código do tipo de administração do órgão",
        en="Code of the body's administration type",
        es="Código del tipo de administración del órgano",
        dic=True,
        original="codigoTipoAdministracao",
    ),
    c(
        "nome_tipo_administracao",
        "STRING",
        "Tipo de administração do órgão, como administração direta federal, autarquia ou fundo",
        en="Administration type of the body, such as federal direct administration, autarchy or fund",
        es="Tipo de administración del órgano, como administración directa federal, autarquía o fondo",
        original="nomeTipoAdministracao",
    ),
    c(
        "poder",
        "STRING",
        "Poder ao qual o órgão pertence",
        en="Branch of government the body belongs to",
        es="Poder al que pertenece el órgano",
        dic=True,
        obs="E Executivo, L Legislativo, J Judiciário, N não classificado",
        original="poder",
    ),
    c(
        "esfera",
        "STRING",
        "Esfera federativa do órgão",
        en="Federative sphere of the body",
        es="Esfera federativa del órgano",
        dic=True,
        obs="F federal, E estadual, M municipal, D distrital, N não classificado",
        original="esfera",
    ),
    c(
        "indicador_uso_sisg",
        "BOOLEAN",
        "Indica se o órgão integra o SISG",
        en="Whether the body is part of SISG",
        es="Indica si el órgano integra el SISG",
        obs="SISG é o Sistema de Serviços Gerais, que reúne os órgãos da administração federal direta, "
        "autárquica e fundacional",
        original="usoSisg",
    ),
    c(
        "indicador_orgao_ativo",
        "BOOLEAN",
        "Indica se o órgão está ativo no cadastro",
        en="Whether the body is active in the registry",
        es="Indica si el órgano está activo en el registro",
        original="statusOrgao",
    ),
    c(
        "data_hora_movimento",
        "DATETIME",
        "Data e hora da última movimentação do cadastro do órgão",
        en="Timestamp of the last change to the body's registry entry",
        es="Fecha y hora del último movimiento del registro del órgano",
        original="dataHoraMovimento",
    ),
]

UNIDADE_ADMINISTRATIVA = [
    DATA_EXTRACAO,
    c(
        "sigla_uf",
        "STRING",
        "Sigla da unidade da federação onde a UASG está sediada",
        en="Abbreviation of the federative unit where the UASG is based",
        es="Sigla de la unidad federativa donde la UASG está ubicada",
        directory=DIR_UF,
        original="siglaUf",
    ),
    c(
        "id_municipio",
        "STRING",
        "Código IBGE de 7 dígitos do município onde a UASG está sediada",
        en="Seven-digit IBGE code of the municipality where the UASG is based",
        es="Código IBGE de siete dígitos del municipio donde la UASG está ubicada",
        directory=DIR_MUNICIPIO,
        original="codigoMunicipioIbge",
    ),
    c(
        "codigo_uasg",
        "STRING",
        "Código da Unidade Administrativa de Serviços Gerais",
        en="Code of the administrative purchasing unit (UASG)",
        es="Código de la Unidad Administrativa de Servicios Generales",
        original="codigoUasg",
    ),
    c(
        "codigo_orgao",
        "STRING",
        "Código do órgão ao qual a UASG pertence",
        en="Code of the body the UASG belongs to",
        es="Código del órgano al que pertenece la UASG",
        original="codigoOrgao",
    ),
    c(
        "cnpj_orgao",
        "STRING",
        "CNPJ ou CPF do órgão ao qual a UASG pertence",
        en="Taxpayer number of the body the UASG belongs to",
        es="CNPJ o CPF del órgano al que pertenece la UASG",
        original="cnpjCpfOrgao",
    ),
    c(
        "cnpj_orgao_vinculado",
        "STRING",
        "CNPJ ou CPF do órgão vinculado",
        en="Taxpayer number of the attached-to body",
        es="CNPJ o CPF del órgano vinculado",
        original="cnpjCpfOrgaoVinculado",
    ),
    c(
        "cnpj_orgao_superior",
        "STRING",
        "CNPJ ou CPF do órgão superior",
        en="Taxpayer number of the superior body",
        es="CNPJ o CPF del órgano superior",
        original="cnpjCpfOrgaoSuperior",
    ),
    c(
        "cnpj_uasg",
        "STRING",
        "CNPJ ou CPF próprio da UASG, quando possui",
        en="Own taxpayer number of the UASG, where it has one",
        es="CNPJ o CPF propio de la UASG, cuando lo tiene",
        original="cnpjCpfUasg",
    ),
    c(
        "nome_uasg",
        "STRING",
        "Nome da UASG",
        en="Name of the UASG",
        es="Nombre de la UASG",
        original="nomeUasg",
    ),
    c(
        "codigo_municipio_siasg",
        "STRING",
        "Código do município no SIASG",
        en="Municipality code in SIASG",
        es="Código del municipio en el SIASG",
        obs="Codificação interna do SIASG, distinta do código IBGE em id_municipio",
        original="codigoMunicipio",
    ),
    c(
        "nome_municipio",
        "STRING",
        "Nome do município onde a UASG está sediada",
        en="Name of the municipality where the UASG is based",
        es="Nombre del municipio donde la UASG está ubicada",
        original="nomeMunicipioIbge",
    ),
    c(
        "codigo_unidade_polo",
        "STRING",
        "Código da unidade polo à qual a UASG se subordina",
        en="Code of the hub unit the UASG reports to",
        es="Código de la unidad polo a la que la UASG se subordina",
        original="codigoUnidadePolo",
    ),
    c(
        "nome_unidade_polo",
        "STRING",
        "Nome da unidade polo",
        en="Name of the hub unit",
        es="Nombre de la unidad polo",
        original="nomeUnidadePolo",
    ),
    c(
        "codigo_unidade_espelho",
        "STRING",
        "Código da unidade espelho, quando a UASG replica outra unidade",
        en="Code of the mirror unit, when the UASG replicates another unit",
        es="Código de la unidad espejo, cuando la UASG replica otra unidad",
        obs="O valor 0 indica ausência de unidade espelho",
        original="codigoUnidadeEspelho",
    ),
    c(
        "nome_unidade_espelho",
        "STRING",
        "Nome da unidade espelho",
        en="Name of the mirror unit",
        es="Nombre de la unidad espejo",
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="nomeUnidadeEspelho",
    ),
    c(
        "codigo_siorg",
        "STRING",
        "Código da unidade no SIORG",
        en="Unit code in SIORG",
        es="Código de la unidad en el SIORG",
        obs="SIORG é o Sistema de Informações Organizacionais do Governo Federal",
        original="codigoSiorg",
    ),
    c(
        "indicador_uso_sisg",
        "BOOLEAN",
        "Indica se a UASG integra o SISG",
        en="Whether the UASG is part of SISG",
        es="Indica si la UASG integra el SISG",
        original="usoSisg",
    ),
    c(
        "indicador_adesao_siasg",
        "BOOLEAN",
        "Indica se a UASG aderiu ao SIASG",
        en="Whether the UASG has joined SIASG",
        es="Indica si la UASG se adhirió al SIASG",
        obs="Unidades estaduais e municipais aparecem no cadastro por adesão voluntária ao sistema federal",
        original="adesaoSiasg",
    ),
    c(
        "indicador_uasg_cadastradora",
        "BOOLEAN",
        "Indica se a UASG pode cadastrar fornecedores no SICAF",
        en="Whether the UASG may register suppliers in SICAF",
        es="Indica si la UASG puede registrar proveedores en el SICAF",
        original="uasgCadastradora",
    ),
    c(
        "indicador_uasg_ativa",
        "BOOLEAN",
        "Indica se a UASG está ativa no cadastro",
        en="Whether the UASG is active in the registry",
        es="Indica si la UASG está activa en el registro",
        original="statusUasg",
    ),
    c(
        "data_implantacao_sidec",
        "DATETIME",
        "Data e hora de implantação da UASG no SIDEC",
        en="Timestamp when the UASG was set up in SIDEC",
        es="Fecha y hora de implantación de la UASG en el SIDEC",
        original="dataImplantacaoSidec",
    ),
    c(
        "data_hora_movimento",
        "DATETIME",
        "Data e hora da última movimentação do cadastro da UASG",
        en="Timestamp of the last change to the UASG's registry entry",
        es="Fecha y hora del último movimiento del registro de la UASG",
        original="dataHoraMovimento",
    ),
]

FORNECEDOR = [
    DATA_EXTRACAO,
    c(
        "sigla_uf",
        "STRING",
        "Sigla da unidade da federação do fornecedor",
        en="Abbreviation of the supplier's federative unit",
        es="Sigla de la unidad federativa del proveedor",
        directory=DIR_UF,
        original="ufSigla",
    ),
    c(
        "cnpj",
        "STRING",
        "CNPJ do fornecedor pessoa jurídica",
        en="Taxpayer number (CNPJ) of the corporate supplier",
        es="CNPJ del proveedor persona jurídica",
        obs="Vazio para fornecedores pessoa física, que são identificados em cpf",
        original="cnpj",
    ),
    c(
        "cpf",
        "STRING",
        "CPF mascarado do fornecedor pessoa física",
        en="Masked taxpayer number (CPF) of the individual supplier",
        es="CPF enmascarado del proveedor persona física",
        sensitive=True,
        obs="A fonte publica o CPF parcialmente mascarado, no formato ***007562**",
        original="cpf",
    ),
    c(
        "nome_razao_social",
        "STRING",
        "Razão social ou nome do fornecedor",
        en="Corporate or personal name of the supplier",
        es="Razón social o nombre del proveedor",
        original="nomeRazaoSocialFornecedor",
    ),
    c(
        "codigo_cnae",
        "STRING",
        "Código CNAE da atividade econômica principal do fornecedor",
        en="CNAE code of the supplier's main economic activity",
        es="Código CNAE de la actividad económica principal del proveedor",
        original="codigoCnae",
    ),
    c(
        "nome_cnae",
        "STRING",
        "Descrição da atividade econômica principal do fornecedor",
        en="Description of the supplier's main economic activity",
        es="Descripción de la actividad económica principal del proveedor",
        original="nomeCnae",
    ),
    c(
        "id_natureza_juridica",
        "STRING",
        "Código da natureza jurídica do fornecedor",
        en="Code of the supplier's legal nature",
        es="Código de la naturaleza jurídica del proveedor",
        dic=True,
        original="naturezaJuridicaId",
    ),
    c(
        "natureza_juridica",
        "STRING",
        "Natureza jurídica do fornecedor",
        en="Legal nature of the supplier",
        es="Naturaleza jurídica del proveedor",
        original="naturezaJuridicaNome",
    ),
    c(
        "id_porte_empresa",
        "STRING",
        "Código do porte da empresa",
        en="Code of the company size band",
        es="Código del tamaño de la empresa",
        dic=True,
        original="porteEmpresaId",
    ),
    c(
        "porte_empresa",
        "STRING",
        "Porte da empresa, como microempresa, empresa de pequeno porte ou demais",
        en="Company size band, such as micro-enterprise, small business or other",
        es="Tamaño de la empresa, como microempresa, pequeña empresa u otras",
        obs="O porte determina a elegibilidade aos benefícios da Lei Complementar 123/2006",
        original="porteEmpresaNome",
    ),
    c(
        "nome_municipio",
        "STRING",
        "Nome do município do fornecedor",
        en="Name of the supplier's municipality",
        es="Nombre del municipio del proveedor",
        obs="A fonte não publica o código IBGE do município, apenas o nome, com grafia inconsistente",
        original="nomeMunicipio",
    ),
    c(
        "indicador_habilitado_licitar",
        "BOOLEAN",
        "Indica se o fornecedor está habilitado a licitar no SICAF",
        en="Whether the supplier is cleared to bid in SICAF",
        es="Indica si el proveedor está habilitado para licitar en el SICAF",
        original="habilitadoLicitar",
    ),
    c(
        "indicador_fornecedor_ativo",
        "BOOLEAN",
        "Indica se o fornecedor está ativo no cadastro",
        en="Whether the supplier is active in the registry",
        es="Indica si el proveedor está activo en el registro",
        original="ativo",
    ),
]

CATALOGO_MATERIAL = [
    DATA_EXTRACAO,
    c(
        "codigo_item",
        "STRING",
        "Código do item de material no CATMAT",
        en="Code of the material item in CATMAT",
        es="Código del artículo de material en el CATMAT",
        original="codigoItem",
    ),
    c(
        "codigo_grupo",
        "STRING",
        "Código do grupo de material",
        en="Code of the material group",
        es="Código del grupo de material",
        original="codigoGrupo",
    ),
    c(
        "nome_grupo",
        "STRING",
        "Nome do grupo de material",
        en="Name of the material group",
        es="Nombre del grupo de material",
        original="nomeGrupo",
    ),
    c(
        "codigo_classe",
        "STRING",
        "Código da classe de material",
        en="Code of the material class",
        es="Código de la clase de material",
        original="codigoClasse",
    ),
    c(
        "nome_classe",
        "STRING",
        "Nome da classe de material",
        en="Name of the material class",
        es="Nombre de la clase de material",
        original="nomeClasse",
    ),
    c(
        "codigo_pdm",
        "STRING",
        "Código do Padrão Descritivo de Material",
        en="Code of the material descriptive standard (PDM)",
        es="Código del Patrón Descriptivo de Material",
        original="codigoPdm",
    ),
    c(
        "nome_pdm",
        "STRING",
        "Nome do Padrão Descritivo de Material",
        en="Name of the material descriptive standard (PDM)",
        es="Nombre del Patrón Descriptivo de Material",
        original="nomePdm",
    ),
    c(
        "codigo_ncm",
        "STRING",
        "Código NCM da Nomenclatura Comum do Mercosul",
        en="NCM code under the Mercosur Common Nomenclature",
        es="Código NCM de la Nomenclatura Común del Mercosur",
        original="codigo_ncm",
    ),
    c(
        "descricao_ncm",
        "STRING",
        "Descrição da classificação NCM",
        en="Description of the NCM classification",
        es="Descripción de la clasificación NCM",
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="descricao_ncm",
    ),
    c(
        "descricao_item",
        "STRING",
        "Descrição estruturada do item de material",
        en="Structured description of the material item",
        es="Descripción estructurada del artículo de material",
        obs="Concatena o PDM e os valores de cada característica do padrão descritivo",
        original="descricaoItem",
    ),
    c(
        "indicador_item_sustentavel",
        "BOOLEAN",
        "Indica se o item é classificado como sustentável",
        en="Whether the item is classified as sustainable",
        es="Indica si el artículo está clasificado como sostenible",
        original="itemSustentavel",
    ),
    c(
        "indicador_aplica_margem_preferencia",
        "BOOLEAN",
        "Indica se o item admite margem de preferência para produtos nacionais",
        en="Whether the item allows a preference margin for domestic products",
        es="Indica si el artículo admite margen de preferencia para productos nacionales",
        original="aplica_margem_preferencia",
    ),
    c(
        "indicador_item_ativo",
        "BOOLEAN",
        "Indica se o item está ativo no catálogo",
        en="Whether the item is active in the catalogue",
        es="Indica si el artículo está activo en el catálogo",
        original="statusItem",
    ),
    c(
        "data_hora_atualizacao",
        "DATETIME",
        "Data e hora da última atualização do item no catálogo",
        en="Timestamp of the last update to the catalogue item",
        es="Fecha y hora de la última actualización del artículo en el catálogo",
        original="dataHoraAtualizacao",
    ),
]

CATALOGO_SERVICO = [
    DATA_EXTRACAO,
    c(
        "codigo_servico",
        "STRING",
        "Código do item de serviço no CATSER",
        en="Code of the service item in CATSER",
        es="Código del artículo de servicio en el CATSER",
        original="codigoServico",
    ),
    c(
        "codigo_secao",
        "STRING",
        "Código da seção de serviço",
        en="Code of the service section",
        es="Código de la sección de servicio",
        original="codigoSecao",
    ),
    c(
        "nome_secao",
        "STRING",
        "Nome da seção de serviço",
        en="Name of the service section",
        es="Nombre de la sección de servicio",
        original="nomeSecao",
    ),
    c(
        "codigo_divisao",
        "STRING",
        "Código da divisão de serviço",
        en="Code of the service division",
        es="Código de la división de servicio",
        original="codigoDivisao",
    ),
    c(
        "nome_divisao",
        "STRING",
        "Nome da divisão de serviço",
        en="Name of the service division",
        es="Nombre de la división de servicio",
        original="nomeDivisao",
    ),
    c(
        "codigo_grupo",
        "STRING",
        "Código do grupo de serviço",
        en="Code of the service group",
        es="Código del grupo de servicio",
        original="codigoGrupo",
    ),
    c(
        "nome_grupo",
        "STRING",
        "Nome do grupo de serviço",
        en="Name of the service group",
        es="Nombre del grupo de servicio",
        original="nomeGrupo",
    ),
    c(
        "codigo_classe",
        "STRING",
        "Código da classe de serviço",
        en="Code of the service class",
        es="Código de la clase de servicio",
        original="codigoClasse",
    ),
    c(
        "nome_classe",
        "STRING",
        "Nome da classe de serviço",
        en="Name of the service class",
        es="Nombre de la clase de servicio",
        original="nomeClasse",
    ),
    c(
        "codigo_subclasse",
        "STRING",
        "Código da subclasse de serviço",
        en="Code of the service subclass",
        es="Código de la subclase de servicio",
        obs="Preenchido para menos de 1% dos itens",
        original="codigoSubclasse",
    ),
    c(
        "nome_subclasse",
        "STRING",
        "Nome da subclasse de serviço",
        en="Name of the service subclass",
        es="Nombre de la subclase de servicio",
        original="nomeSubclasse",
    ),
    c(
        "nome_servico",
        "STRING",
        "Nome do item de serviço",
        en="Name of the service item",
        es="Nombre del artículo de servicio",
        original="nomeServico",
    ),
    c(
        "codigo_cpc",
        "STRING",
        "Código da Central Product Classification correspondente ao serviço",
        en="Central Product Classification code matching the service",
        es="Código de la Central Product Classification correspondiente al servicio",
        original="codigoCpc",
    ),
    c(
        "indicador_exclusivo_central_compras",
        "BOOLEAN",
        "Indica se o serviço é de contratação exclusiva pela Central de Compras",
        en="Whether the service may be contracted only by the Central Purchasing Office",
        es="Indica si el servicio es de contratación exclusiva por la Central de Compras",
        original="exclusivoCentralCompras",
    ),
    c(
        "indicador_servico_ativo",
        "BOOLEAN",
        "Indica se o serviço está ativo no catálogo",
        en="Whether the service is active in the catalogue",
        es="Indica si el servicio está activo en el catálogo",
        original="statusServico",
    ),
    c(
        "data_hora_atualizacao",
        "DATETIME",
        "Data e hora da última atualização do serviço no catálogo",
        en="Timestamp of the last update to the catalogue service",
        es="Fecha y hora de la última actualización del servicio en el catálogo",
        original="dataHoraAtualizacao",
    ),
]

TABLES = {
    "orgao": ORGAO,
    "unidade_administrativa": UNIDADE_ADMINISTRATIVA,
    "fornecedor": FORNECEDOR,
    "catalogo_material": CATALOGO_MATERIAL,
    "catalogo_servico": CATALOGO_SERVICO,
}
