"""Architecture for the Lei 14.133/2021 contratação tables (2021-)."""

from arch_common import BRL, DIR_ANO, DIR_MUNICIPIO, DIR_UF, c

COBERTURA = "2021(1)2026"


def ano(source: str, en_src: str, es_src: str) -> dict:
    return c(
        "ano",
        "INT64",
        f"Ano de {source}",
        en=f"Year of {en_src}",
        es=f"Año de {es_src}",
        directory=DIR_ANO,
        unit="year",
        coverage=COBERTURA,
        obs="Coluna de particionamento, derivada da data correspondente",
    )


CONTRATACAO = [
    ano(
        "publicação da contratação no PNCP",
        "publication of the procurement on PNCP",
        "publicación de la contratación en el PNCP",
    ),
    c(
        "sigla_uf",
        "STRING",
        "Sigla da unidade da federação da unidade compradora",
        en="Abbreviation of the purchasing unit's federative unit",
        es="Sigla de la unidad federativa de la unidad compradora",
        obs="O valor EX identifica unidades sediadas no exterior",
        directory=DIR_UF,
        original="unidadeOrgaoUfSigla",
    ),
    c(
        "id_municipio",
        "STRING",
        "Código IBGE de 7 dígitos do município da unidade compradora",
        en="Seven-digit IBGE code of the purchasing unit's municipality",
        es="Código IBGE de siete dígitos del municipio de la unidad compradora",
        directory=DIR_MUNICIPIO,
        original="unidadeOrgaoCodigoIbge",
    ),
    c(
        "id_compra",
        "STRING",
        "Identificador da contratação no SIASG",
        en="Identifier of the procurement in SIASG",
        es="Identificador de la contratación en el SIASG",
        obs="Concatena código da UASG, modalidade e número da compra. NÃO é único: uma "
        "mesma chave do SIASG pode corresponder a dezenas de contratações distintas no "
        "PNCP, cada uma com seu número de controle e data de publicação. A chave primária "
        "da tabela é numero_controle_pncp",
        original="idCompra",
    ),
    c(
        "numero_controle_pncp",
        "STRING",
        "Número de controle da contratação no PNCP",
        en="PNCP control number of the procurement",
        es="Número de control de la contratación en el PNCP",
        obs="Formato CNPJ-1-sequencial/ano. Chave primária da tabela e chave de junção "
        "com o conjunto br_pncp",
        original="numeroControlePNCP",
    ),
    c(
        "ano_compra_pncp",
        "INT64",
        "Ano da contratação no numerador do PNCP",
        en="Procurement year in the PNCP numbering",
        es="Año de la contratación en la numeración del PNCP",
        unit="year",
        original="anoCompraPncp",
    ),
    c(
        "sequencial_compra_pncp",
        "STRING",
        "Número sequencial da contratação no PNCP dentro do ano e do órgão",
        en="Sequential number of the procurement within the year and body in PNCP",
        es="Número secuencial de la contratación dentro del año y del órgano en el PNCP",
        original="sequencialCompraPncp",
    ),
    c(
        "numero_compra",
        "STRING",
        "Número da compra atribuído pela unidade compradora",
        en="Purchase number assigned by the purchasing unit",
        es="Número de la compra asignado por la unidad compradora",
        original="numeroCompra",
    ),
    c(
        "processo",
        "STRING",
        "Número do processo administrativo da contratação",
        en="Administrative case number of the procurement",
        es="Número del proceso administrativo de la contratación",
        original="processo",
    ),
    c(
        "codigo_orgao",
        "STRING",
        "Código do órgão comprador no SIASG",
        en="SIASG code of the purchasing body",
        es="Código del órgano comprador en el SIASG",
        original="codigoOrgao",
    ),
    c(
        "cnpj_orgao",
        "STRING",
        "CNPJ do órgão comprador",
        en="Taxpayer number of the purchasing body",
        es="CNPJ del órgano comprador",
        original="orgaoEntidadeCnpj",
    ),
    c(
        "nome_orgao",
        "STRING",
        "Razão social do órgão comprador",
        en="Corporate name of the purchasing body",
        es="Razón social del órgano comprador",
        original="orgaoEntidadeRazaoSocial",
    ),
    c(
        "esfera",
        "STRING",
        "Esfera federativa do órgão comprador",
        en="Federative sphere of the purchasing body",
        es="Esfera federativa del órgano comprador",
        dic=True,
        obs="F federal, E estadual, M municipal, D distrital, N não classificado",
        original="orgaoEntidadeEsferaId",
    ),
    c(
        "poder",
        "STRING",
        "Poder ao qual o órgão comprador pertence",
        en="Branch of government of the purchasing body",
        es="Poder al que pertenece el órgano comprador",
        dic=True,
        obs="E Executivo, L Legislativo, J Judiciário, N não classificado",
        original="orgaoEntidadePoderId",
    ),
    c(
        "codigo_unidade",
        "STRING",
        "Código da UASG compradora",
        en="Code of the purchasing UASG",
        es="Código de la UASG compradora",
        original="unidadeOrgaoCodigoUnidade",
    ),
    c(
        "nome_unidade",
        "STRING",
        "Nome da UASG compradora",
        en="Name of the purchasing UASG",
        es="Nombre de la UASG compradora",
        original="unidadeOrgaoNomeUnidade",
    ),
    c(
        "nome_municipio",
        "STRING",
        "Nome do município da unidade compradora",
        en="Name of the purchasing unit's municipality",
        es="Nombre del municipio de la unidad compradora",
        original="unidadeOrgaoMunicipioNome",
    ),
    c(
        "cnpj_orgao_subrogado",
        "STRING",
        "CNPJ do órgão sub-rogado, quando a contratação foi transferida",
        en="Taxpayer number of the subrogated body, when the procurement was transferred",
        es="CNPJ del órgano subrogado, cuando la contratación fue transferida",
        obs="Sub-rogação ocorre em cerca de 0,1% das contratações",
        original="orgaoSubrogadoCnpj",
    ),
    c(
        "nome_orgao_subrogado",
        "STRING",
        "Razão social do órgão sub-rogado",
        en="Corporate name of the subrogated body",
        es="Razón social del órgano subrogado",
        obs="Preenchido apenas nas contratações sub-rogadas, cerca de 0,3% do total",
        original="orgaoSubrogadoRazaoSocial",
    ),
    c(
        "esfera_subrogado",
        "STRING",
        "Esfera federativa do órgão sub-rogado",
        en="Federative sphere of the subrogated body",
        es="Esfera federativa del órgano subrogado",
        dic=True,
        obs="Preenchido apenas nas contratações sub-rogadas, cerca de 0,3% do total",
        original="orgaoSubrogadoEsferaId",
    ),
    c(
        "poder_subrogado",
        "STRING",
        "Poder do órgão sub-rogado",
        en="Branch of government of the subrogated body",
        es="Poder del órgano subrogado",
        dic=True,
        obs="Preenchido apenas nas contratações sub-rogadas, cerca de 0,3% do total",
        original="orgaoSubrogadoPoderId",
    ),
    c(
        "codigo_unidade_subrogada",
        "STRING",
        "Código da UASG sub-rogada",
        en="Code of the subrogated UASG",
        es="Código de la UASG subrogada",
        obs="Preenchido apenas nas contratações sub-rogadas, cerca de 0,3% do total",
        original="unidadeSubrogadaCodigoUnidade",
    ),
    c(
        "nome_unidade_subrogada",
        "STRING",
        "Nome da UASG sub-rogada",
        en="Name of the subrogated UASG",
        es="Nombre de la UASG subrogada",
        obs="Preenchido apenas nas contratações sub-rogadas, cerca de 0,3% do total",
        original="unidadeSubrogadaNomeUnidade",
    ),
    c(
        "sigla_uf_subrogada",
        "STRING",
        "Sigla da unidade da federação da UASG sub-rogada",
        en="Federative unit abbreviation of the subrogated UASG",
        es="Sigla de la unidad federativa de la UASG subrogada",
        obs="Preenchido apenas nas contratações sub-rogadas, cerca de 0,3% do total",
        original="unidadeSubrogadaUfSigla",
    ),
    c(
        "id_municipio_subrogada",
        "STRING",
        "Código IBGE do município da UASG sub-rogada",
        en="IBGE municipality code of the subrogated UASG",
        es="Código IBGE del municipio de la UASG subrogada",
        obs="Preenchido apenas nas contratações sub-rogadas, cerca de 0,3% do total",
        original="unidadeSubrogadaCodigoIbge",
    ),
    c(
        "nome_municipio_subrogada",
        "STRING",
        "Nome do município da UASG sub-rogada",
        en="Municipality name of the subrogated UASG",
        es="Nombre del municipio de la UASG subrogada",
        obs="Preenchido apenas nas contratações sub-rogadas, cerca de 0,3% do total",
        original="unidadeSubrogadaMunicipioNome",
    ),
    c(
        "codigo_modalidade",
        "STRING",
        "Código da modalidade de contratação no SIASG",
        en="SIASG code of the procurement modality",
        es="Código de la modalidad de contratación en el SIASG",
        dic=True,
        obs="Codificação do SIASG, distinta da do PNCP. Apenas 3, 5, 6 e 7 possuem registros",
        original="codigoModalidade",
    ),
    c(
        "id_modalidade_pncp",
        "STRING",
        "Código da modalidade de contratação no PNCP",
        en="PNCP code of the procurement modality",
        es="Código de la modalidad de contratación en el PNCP",
        dic=True,
        obs="Codificação do PNCP. O código 6 do SIASG corresponde ao 8 do PNCP, Dispensa",
        original="modalidadeIdPncp",
    ),
    c(
        "modalidade",
        "STRING",
        "Nome da modalidade de contratação",
        en="Name of the procurement modality",
        es="Nombre de la modalidad de contratación",
        original="modalidadeNome",
    ),
    c(
        "id_modo_disputa_pncp",
        "STRING",
        "Código do modo de disputa no PNCP",
        en="PNCP code of the dispute mode",
        es="Código del modo de disputa en el PNCP",
        dic=True,
        original="modoDisputaIdPncp",
    ),
    c(
        "codigo_modo_disputa",
        "STRING",
        "Código do modo de disputa no SIASG",
        en="SIASG code of the dispute mode",
        es="Código del modo de disputa en el SIASG",
        dic=True,
        original="codigoModoDisputa",
    ),
    c(
        "modo_disputa",
        "STRING",
        "Modo de disputa, como aberto, fechado ou aberto-fechado",
        en="Dispute mode, such as open, closed or open-closed",
        es="Modo de disputa, como abierto, cerrado o abierto-cerrado",
        original="modoDisputaNomePncp",
    ),
    c(
        "codigo_amparo_legal",
        "STRING",
        "Código do amparo legal da contratação no PNCP",
        en="PNCP code of the legal basis for the procurement",
        es="Código del amparo legal de la contratación en el PNCP",
        dic=True,
        original="amparoLegalCodigoPncp",
    ),
    c(
        "amparo_legal",
        "STRING",
        "Dispositivo legal que ampara a contratação",
        en="Legal provision the procurement relies on",
        es="Disposición legal que ampara la contratación",
        original="amparoLegalNome",
    ),
    c(
        "descricao_amparo_legal",
        "STRING",
        "Descrição do dispositivo legal que ampara a contratação",
        en="Description of the legal provision the procurement relies on",
        es="Descripción de la disposición legal que ampara la contratación",
        original="amparoLegalDescricao",
    ),
    c(
        "codigo_tipo_instrumento_convocatorio",
        "STRING",
        "Código do tipo de instrumento convocatório no PNCP",
        en="PNCP code of the type of calling instrument",
        es="Código del tipo de instrumento convocatorio en el PNCP",
        dic=True,
        original="tipoInstrumentoConvocatorioCodigoPncp",
    ),
    c(
        "tipo_instrumento_convocatorio",
        "STRING",
        "Tipo de instrumento convocatório, como edital ou aviso de contratação direta",
        en="Type of calling instrument, such as a public notice or a direct contracting notice",
        es="Tipo de instrumento convocatorio, como pliego o aviso de contratación directa",
        original="tipoInstrumentoConvocatorioNome",
    ),
    c(
        "id_situacao_compra",
        "STRING",
        "Código da situação da contratação no PNCP",
        en="PNCP code of the procurement status",
        es="Código de la situación de la contratación en el PNCP",
        dic=True,
        original="situacaoCompraIdPncp",
    ),
    c(
        "situacao_compra",
        "STRING",
        "Situação da contratação, como divulgada no PNCP, suspensa, revogada ou anulada",
        en="Procurement status, such as published on PNCP, suspended, revoked or annulled",
        es="Situación de la contratación, como divulgada en el PNCP, suspendida, revocada o anulada",
        original="situacaoCompraNomePncp",
    ),
    c(
        "codigo_orcamento_sigiloso",
        "STRING",
        "Código do regime de sigilo do orçamento estimado",
        en="Code of the confidentiality regime of the estimated budget",
        es="Código del régimen de secreto del presupuesto estimado",
        dic=True,
        original="orcamentoSigilosoCodigo",
    ),
    c(
        "orcamento_sigiloso",
        "STRING",
        "Regime de sigilo do orçamento estimado da contratação",
        en="Confidentiality regime of the procurement's estimated budget",
        es="Régimen de secreto del presupuesto estimado de la contratación",
        original="orcamentoSigilosoDescricao",
    ),
    c(
        "objeto_compra",
        "STRING",
        "Descrição do objeto da contratação",
        en="Description of the procurement's subject matter",
        es="Descripción del objeto de la contratación",
        original="objetoCompra",
    ),
    c(
        "informacao_complementar",
        "STRING",
        "Informações complementares publicadas com a contratação",
        en="Supplementary information published with the procurement",
        es="Información complementaria publicada con la contratación",
        original="informacaoComplementar",
    ),
    c(
        "valor_total_estimado",
        "FLOAT64",
        "Valor total estimado da contratação",
        en="Total estimated value of the procurement",
        es="Valor total estimado de la contratación",
        unit=BRL,
        original="valorTotalEstimado",
    ),
    c(
        "valor_total_homologado",
        "FLOAT64",
        "Valor total homologado da contratação",
        en="Total awarded value of the procurement",
        es="Valor total homologado de la contratación",
        unit=BRL,
        obs="Vazio enquanto a contratação não tem resultado homologado",
        original="valorTotalHomologado",
    ),
    c(
        "indicador_srp",
        "BOOLEAN",
        "Indica se a contratação usa Sistema de Registro de Preços",
        en="Whether the procurement uses the price registration system (SRP)",
        es="Indica si la contratación usa el Sistema de Registro de Precios",
        obs="Contratações SRP geram atas de registro de preço, na tabela ata_registro_preco",
        original="srp",
    ),
    c(
        "indicador_existe_resultado",
        "BOOLEAN",
        "Indica se a contratação possui resultado registrado",
        en="Whether the procurement has a recorded result",
        es="Indica si la contratación tiene resultado registrado",
        original="existeResultado",
    ),
    c(
        "indicador_contratacao_excluida",
        "BOOLEAN",
        "Indica se a contratação foi excluída do PNCP",
        en="Whether the procurement was deleted from PNCP",
        es="Indica si la contratación fue excluida del PNCP",
        original="contratacaoExcluida",
    ),
    c(
        "data_publicacao_pncp",
        "DATETIME",
        "Data e hora de publicação da contratação no PNCP",
        en="Timestamp when the procurement was published on PNCP",
        es="Fecha y hora de publicación de la contratación en el PNCP",
        original="dataPublicacaoPncp",
    ),
    c(
        "data_inclusao_pncp",
        "DATETIME",
        "Data e hora de inclusão da contratação no PNCP",
        en="Timestamp when the procurement was added to PNCP",
        es="Fecha y hora de inclusión de la contratación en el PNCP",
        original="dataInclusaoPncp",
    ),
    c(
        "data_atualizacao_pncp",
        "DATETIME",
        "Data e hora da última atualização da contratação no PNCP",
        en="Timestamp of the last update to the procurement on PNCP",
        es="Fecha y hora de la última actualización de la contratación en el PNCP",
        obs="97,4% das contratações nunca são alteradas após a publicação",
        original="dataAtualizacaoPncp",
    ),
    c(
        "data_abertura_proposta",
        "DATETIME",
        "Data e hora de abertura do prazo de propostas",
        en="Timestamp when the proposal window opens",
        es="Fecha y hora de apertura del plazo de propuestas",
        original="dataAberturaPropostaPncp",
    ),
    c(
        "data_encerramento_proposta",
        "DATETIME",
        "Data e hora de encerramento do prazo de propostas",
        en="Timestamp when the proposal window closes",
        es="Fecha y hora de cierre del plazo de propuestas",
        original="dataEncerramentoPropostaPncp",
    ),
]

CONTRATACAO_ITEM = [
    ano(
        "inclusão do item no PNCP",
        "the item's inclusion on PNCP",
        "la inclusión del ítem en el PNCP",
    ),
    c(
        "id_compra",
        "STRING",
        "Identificador da contratação no SIASG",
        en="Identifier of the procurement in SIASG",
        es="Identificador de la contratación en el SIASG",
        obs="Junta com a tabela contratacao",
        original="idCompra",
    ),
    c(
        "id_compra_item",
        "STRING",
        "Identificador do item da contratação no SIASG",
        en="Identifier of the procurement item in SIASG",
        es="Identificador del ítem de la contratación en el SIASG",
        obs="Chave primária da tabela",
        original="idCompraItem",
    ),
    c(
        "numero_controle_pncp",
        "STRING",
        "Número de controle da contratação no PNCP",
        en="PNCP control number of the procurement",
        es="Número de control de la contratación en el PNCP",
        original="numeroControlePNCPCompra",
    ),
    c(
        "id_contratacao_pncp",
        "STRING",
        "Número de controle da contratação no PNCP repetido pela fonte",
        en="PNCP control number of the procurement, repeated by the source",
        es="Número de control de la contratación en el PNCP, repetido por la fuente",
        obs="Idêntico a numero_controle_pncp em todas as amostras verificadas",
        original="idContratacaoPNCP",
    ),
    c(
        "cnpj_orgao",
        "STRING",
        "CNPJ do órgão comprador",
        en="Taxpayer number of the purchasing body",
        es="CNPJ del órgano comprador",
        original="orgaoEntidadeCnpj",
    ),
    c(
        "codigo_unidade",
        "STRING",
        "Código da UASG compradora",
        en="Code of the purchasing UASG",
        es="Código de la UASG compradora",
        original="unidadeOrgaoCodigoUnidade",
    ),
    c(
        "numero_item_pncp",
        "STRING",
        "Número do item na contratação segundo o PNCP",
        en="Item number within the procurement according to PNCP",
        es="Número del ítem en la contratación según el PNCP",
        original="numeroItemPncp",
    ),
    c(
        "numero_item_compra",
        "STRING",
        "Número do item na contratação segundo o SIASG",
        en="Item number within the procurement according to SIASG",
        es="Número del ítem en la contratación según el SIASG",
        original="numeroItemCompra",
    ),
    c(
        "numero_grupo",
        "STRING",
        "Número do grupo de itens ao qual o item pertence",
        en="Number of the item group the item belongs to",
        es="Número del grupo de ítems al que pertenece el ítem",
        obs="O valor 0 indica item que não integra grupo",
        original="numeroGrupo",
    ),
    c(
        "tipo_item",
        "STRING",
        "Indica se o item é material ou serviço",
        en="Whether the item is a material or a service",
        es="Indica si el ítem es material o servicio",
        dic=True,
        obs="M material, S serviço",
        original="materialOuServico",
    ),
    c(
        "nome_tipo_item",
        "STRING",
        "Nome do tipo do item",
        en="Name of the item type",
        es="Nombre del tipo de ítem",
        original="materialOuServicoNome",
    ),
    c(
        "codigo_item_catalogo",
        "STRING",
        "Código do item nos catálogos CATMAT ou CATSER",
        en="Code of the item in the CATMAT or CATSER catalogues",
        es="Código del ítem en los catálogos CATMAT o CATSER",
        obs="Junta com catalogo_material quando tipo_item é M e com catalogo_servico quando é S",
        original="codItemCatalogo",
    ),
    c(
        "codigo_grupo",
        "STRING",
        "Código do grupo do item no catálogo",
        en="Code of the item's catalogue group",
        es="Código del grupo del ítem en el catálogo",
        original="codigoGrupo",
    ),
    c(
        "codigo_classe",
        "STRING",
        "Código da classe do item no catálogo",
        en="Code of the item's catalogue class",
        es="Código de la clase del ítem en el catálogo",
        original="codigoClasse",
    ),
    c(
        "codigo_pdm",
        "STRING",
        "Código do Padrão Descritivo de Material do item",
        en="Code of the item's material descriptive standard",
        es="Código del Patrón Descriptivo de Material del ítem",
        original="codigoPdm",
    ),
    c(
        "nome_pdm",
        "STRING",
        "Nome do Padrão Descritivo de Material do item",
        en="Name of the item's material descriptive standard",
        es="Nombre del Patrón Descriptivo de Material del ítem",
        original="nomePdm",
    ),
    c(
        "codigo_ncm",
        "STRING",
        "Código NCM da Nomenclatura Comum do Mercosul do item",
        en="Mercosur Common Nomenclature code of the item",
        es="Código NCM de la Nomenclatura Común del Mercosur del ítem",
        original="codigoNCM",
    ),
    c(
        "descricao_ncm",
        "STRING",
        "Descrição da classificação NCM do item",
        en="Description of the item's NCM classification",
        es="Descripción de la clasificación NCM del ítem",
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="descricaoNCM",
    ),
    c(
        "descricao_resumida",
        "STRING",
        "Descrição resumida do item",
        en="Short description of the item",
        es="Descripción resumida del ítem",
        original="descricaoResumida",
    ),
    c(
        "descricao_detalhada",
        "STRING",
        "Descrição detalhada do item",
        en="Detailed description of the item",
        es="Descripción detallada del ítem",
        original="descricaodetalhada",
    ),
    c(
        "unidade_medida",
        "STRING",
        "Unidade de medida do item",
        en="Unit of measurement of the item",
        es="Unidad de medida del ítem",
        original="unidadeMedida",
    ),
    c(
        "id_item_categoria",
        "STRING",
        "Código da categoria do item no PNCP",
        en="PNCP code of the item category",
        es="Código de la categoría del ítem en el PNCP",
        dic=True,
        original="itemCategoriaIdPncp",
    ),
    c(
        "item_categoria",
        "STRING",
        "Categoria do item, como informática, obras ou serviços de engenharia",
        en="Item category, such as IT, works or engineering services",
        es="Categoría del ítem, como informática, obras o servicios de ingeniería",
        original="itemCategoriaNome",
    ),
    c(
        "id_criterio_julgamento",
        "STRING",
        "Código do critério de julgamento do item no PNCP",
        en="PNCP code of the item's award criterion",
        es="Código del criterio de adjudicación del ítem en el PNCP",
        dic=True,
        original="criterioJulgamentoIdPncp",
    ),
    c(
        "criterio_julgamento",
        "STRING",
        "Critério de julgamento do item, como menor preço ou maior desconto",
        en="Award criterion for the item, such as lowest price or largest discount",
        es="Criterio de adjudicación del ítem, como menor precio o mayor descuento",
        original="criterioJulgamentoNome",
    ),
    c(
        "id_situacao_item",
        "STRING",
        "Código da situação do item",
        en="Code of the item status",
        es="Código de la situación del ítem",
        dic=True,
        original="situacaoCompraItem",
    ),
    c(
        "situacao_item",
        "STRING",
        "Situação do item, como homologado, deserto, fracassado ou cancelado",
        en="Item status, such as awarded, deserted, failed or cancelled",
        es="Situación del ítem, como homologado, desierto, fracasado o cancelado",
        original="situacaoCompraItemNome",
    ),
    c(
        "id_tipo_beneficio",
        "STRING",
        "Código do tipo de benefício aplicado ao item",
        en="Code of the benefit type applied to the item",
        es="Código del tipo de beneficio aplicado al ítem",
        dic=True,
        original="tipoBeneficio",
    ),
    c(
        "tipo_beneficio",
        "STRING",
        "Tipo de benefício, como participação exclusiva para microempresas e empresas de pequeno porte",
        en="Benefit type, such as participation reserved for micro and small enterprises",
        es="Tipo de beneficio, como participación exclusiva para microempresas y pequeñas empresas",
        original="tipoBeneficioNome",
    ),
    c(
        "quantidade",
        "FLOAT64",
        "Quantidade licitada do item",
        en="Quantity of the item put out to tender",
        es="Cantidad licitada del ítem",
        unit="unit",
        original="quantidade",
    ),
    c(
        "valor_unitario_estimado",
        "FLOAT64",
        "Valor unitário estimado do item",
        en="Estimated unit value of the item",
        es="Valor unitario estimado del ítem",
        unit=BRL,
        original="valorUnitarioEstimado",
    ),
    c(
        "valor_total",
        "FLOAT64",
        "Valor total estimado do item",
        en="Total estimated value of the item",
        es="Valor total estimado del ítem",
        unit=BRL,
        original="valorTotal",
    ),
    c(
        "quantidade_resultado",
        "FLOAT64",
        "Quantidade homologada do item",
        en="Quantity awarded for the item",
        es="Cantidad homologada del ítem",
        unit="unit",
        original="quantidadeResultado",
    ),
    c(
        "valor_unitario_resultado",
        "FLOAT64",
        "Valor unitário homologado do item",
        en="Awarded unit value of the item",
        es="Valor unitario homologado del ítem",
        unit=BRL,
        original="valorUnitarioResultado",
    ),
    c(
        "valor_total_resultado",
        "FLOAT64",
        "Valor total homologado do item",
        en="Total awarded value of the item",
        es="Valor total homologado del ítem",
        unit=BRL,
        original="valorTotalResultado",
    ),
    c(
        "id_fornecedor",
        "STRING",
        "CNPJ ou CPF do fornecedor vencedor do item",
        en="Taxpayer number of the supplier awarded the item",
        es="CNPJ o CPF del proveedor adjudicatario del ítem",
        obs="Traz apenas o vencedor principal. A tabela contratacao_item_resultado lista "
        "todos os classificados",
        original="codFornecedor",
    ),
    c(
        "nome_fornecedor",
        "STRING",
        "Nome ou razão social do fornecedor vencedor do item",
        en="Name of the supplier awarded the item",
        es="Nombre o razón social del proveedor adjudicatario del ítem",
        original="nomeFornecedor",
    ),
    c(
        "percentual_margem_preferencia_normal",
        "FLOAT64",
        "Percentual da margem de preferência normal aplicada ao item",
        en="Percentage of the standard preference margin applied to the item",
        es="Porcentaje del margen de preferencia normal aplicado al ítem",
        unit="percent",
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="percentualMargemPreferenciaNormal",
    ),
    c(
        "percentual_margem_preferencia_adicional",
        "FLOAT64",
        "Percentual da margem de preferência adicional aplicada ao item",
        en="Percentage of the additional preference margin applied to the item",
        es="Porcentaje del margen de preferencia adicional aplicado al ítem",
        unit="percent",
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="percentualMargemPreferenciaAdicional",
    ),
    c(
        "indicador_orcamento_sigiloso",
        "BOOLEAN",
        "Indica se o orçamento estimado do item é sigiloso",
        en="Whether the item's estimated budget is confidential",
        es="Indica si el presupuesto estimado del ítem es reservado",
        original="orcamentoSigiloso",
    ),
    c(
        "indicador_incentivo_produtivo_basico",
        "BOOLEAN",
        "Indica se o item recebe incentivo do Processo Produtivo Básico",
        en="Whether the item receives the basic productive process incentive",
        es="Indica si el ítem recibe el incentivo del Proceso Productivo Básico",
        original="incentivoProdutivoBasico",
    ),
    c(
        "indicador_margem_preferencia_normal",
        "BOOLEAN",
        "Indica se foi aplicada margem de preferência normal ao item",
        en="Whether the standard preference margin was applied to the item",
        es="Indica si se aplicó margen de preferencia normal al ítem",
        original="margemPreferenciaNormal",
    ),
    c(
        "indicador_margem_preferencia_adicional",
        "BOOLEAN",
        "Indica se foi aplicada margem de preferência adicional ao item",
        en="Whether the additional preference margin was applied to the item",
        es="Indica si se aplicó margen de preferencia adicional al ítem",
        original="margemPreferenciaAdicional",
    ),
    c(
        "indicador_tem_resultado",
        "BOOLEAN",
        "Indica se o item possui resultado registrado",
        en="Whether the item has a recorded result",
        es="Indica si el ítem tiene resultado registrado",
        original="temResultado",
    ),
    c(
        "data_inclusao_pncp",
        "DATETIME",
        "Data e hora de inclusão do item no PNCP",
        en="Timestamp when the item was added to PNCP",
        es="Fecha y hora de inclusión del ítem en el PNCP",
        original="dataInclusaoPncp",
    ),
    c(
        "data_atualizacao_pncp",
        "DATETIME",
        "Data e hora da última atualização do item no PNCP",
        en="Timestamp of the last update to the item on PNCP",
        es="Fecha y hora de la última actualización del ítem en el PNCP",
        obs="Os itens são preenchidos progressivamente: a mediana da defasagem entre inclusão e "
        "última atualização é de 78 dias",
        original="dataAtualizacaoPncp",
    ),
    c(
        "data_resultado",
        "DATETIME",
        "Data e hora do resultado do item",
        en="Timestamp of the item's result",
        es="Fecha y hora del resultado del ítem",
        original="dataResultado",
    ),
]

TABLES = {
    "contratacao": CONTRATACAO,
    "contratacao_item": CONTRATACAO_ITEM,
}
