"""Architecture for the contrato tables (Lei 14.133 execution stage)."""

from arch_common import BRL, DIR_ANO, c

COB = "2021(1)2026"


def ano() -> dict:
    return c(
        "ano",
        "INT64",
        "Ano de início da vigência do contrato",
        en="Year the contract's validity starts",
        es="Año de inicio de la vigencia del contrato",
        directory=DIR_ANO,
        unit="year",
        coverage=COB,
        obs="Coluna de particionamento, derivada de data_vigencia_inicial",
    )


_ORG = [
    c(
        "codigo_orgao",
        "STRING",
        "Código do órgão contratante no SIASG",
        en="SIASG code of the contracting body",
        es="Código del órgano contratante en el SIASG",
        original="codigoOrgao",
    ),
    c(
        "nome_orgao",
        "STRING",
        "Nome do órgão contratante",
        en="Name of the contracting body",
        es="Nombre del órgano contratante",
        original="nomeOrgao",
    ),
    c(
        "codigo_unidade_gestora",
        "STRING",
        "Código da unidade gestora do contrato",
        en="Code of the unit managing the contract",
        es="Código de la unidad gestora del contrato",
        original="codigoUnidadeGestora",
    ),
    c(
        "nome_unidade_gestora",
        "STRING",
        "Nome da unidade gestora do contrato",
        en="Name of the unit managing the contract",
        es="Nombre de la unidad gestora del contrato",
        original="nomeUnidadeGestora",
    ),
    c(
        "codigo_unidade_gestora_origem",
        "STRING",
        "Código da unidade gestora de origem do contrato",
        en="Code of the unit the contract originated in",
        es="Código de la unidad gestora de origen del contrato",
        original="codigoUnidadeGestoraOrigemContrato",
    ),
    c(
        "nome_unidade_gestora_origem",
        "STRING",
        "Nome da unidade gestora de origem do contrato",
        en="Name of the unit the contract originated in",
        es="Nombre de la unidad gestora de origen del contrato",
        original="nomeUnidadeGestoraOrigemContrato",
    ),
    c(
        "codigo_unidade_realizadora_compra",
        "STRING",
        "Código da unidade que realizou a contratação",
        en="Code of the unit that ran the procurement",
        es="Código de la unidad que realizó la contratación",
        original="codigoUnidadeRealizadoraCompra",
    ),
    c(
        "nome_unidade_realizadora_compra",
        "STRING",
        "Nome da unidade que realizou a contratação",
        en="Name of the unit that ran the procurement",
        es="Nombre de la unidad que realizó la contratación",
        original="nomeUnidadeRealizadoraCompra",
    ),
]

_COMPRA = [
    c(
        "numero_compra",
        "STRING",
        "Número da contratação de origem",
        en="Number of the originating procurement",
        es="Número de la contratación de origen",
        original="numeroCompra",
    ),
    c(
        "codigo_modalidade_compra",
        "STRING",
        "Código da modalidade da contratação de origem",
        en="Code of the originating procurement's modality",
        es="Código de la modalidad de la contratación de origen",
        dic=True,
        original="codigoModalidadeCompra",
    ),
    c(
        "modalidade_compra",
        "STRING",
        "Modalidade da contratação de origem",
        en="Modality of the originating procurement",
        es="Modalidad de la contratación de origen",
        original="nomeModalidadeCompra",
    ),
]

_FORN = [
    c(
        "id_fornecedor",
        "STRING",
        "CNPJ ou CPF do fornecedor contratado",
        en="Taxpayer number of the contracted supplier",
        es="CNPJ o CPF del proveedor contratado",
        original="niFornecedor",
    ),
    c(
        "nome_fornecedor",
        "STRING",
        "Nome ou razão social do fornecedor contratado",
        en="Name of the contracted supplier",
        es="Nombre o razón social del proveedor contratado",
        original="nomeRazaoSocialFornecedor",
    ),
]

CONTRATO = [
    ano(),
    c(
        "numero_controle_pncp_contrato",
        "STRING",
        "Número de controle do contrato no PNCP",
        en="PNCP control number of the contract",
        es="Número de control del contrato en el PNCP",
        obs="Vazio para cerca de 80% dos contratos, que antecedem a obrigatoriedade de "
        "publicação no PNCP ou não foram enviados",
        original="numeroControlePncpContrato",
    ),
    c(
        "numero_contrato",
        "STRING",
        "Número do contrato na unidade gestora",
        en="Contract number within the managing unit",
        es="Número del contrato en la unidad gestora",
        obs="Com codigo_orgao e codigo_unidade_gestora forma a chave primária",
        original="numeroContrato",
    ),
    *_ORG,
    c(
        "id_compra",
        "STRING",
        "Identificador da contratação de origem no SIASG",
        en="Identifier of the originating procurement in SIASG",
        es="Identificador de la contratación de origen en el SIASG",
        obs="Junta com a tabela contratacao",
        original="idCompra",
    ),
    c(
        "numero_controle_pncp_compra",
        "STRING",
        "Número de controle da contratação de origem no PNCP",
        en="PNCP control number of the originating procurement",
        es="Número de control de la contratación de origen en el PNCP",
        original="numeroControlePncpCompra",
    ),
    *_COMPRA,
    *_FORN,
    c(
        "processo",
        "STRING",
        "Número do processo administrativo do contrato",
        en="Administrative case number of the contract",
        es="Número del proceso administrativo del contrato",
        original="processo",
    ),
    c(
        "receita_despesa",
        "STRING",
        "Indica se o contrato gera receita ou despesa",
        en="Whether the contract generates revenue or expenditure",
        es="Indica si el contrato genera ingreso o gasto",
        dic=True,
        obs="D despesa, R receita, S sem ônus",
        original="receitaDespesa",
    ),
    c(
        "codigo_tipo",
        "STRING",
        "Código do tipo de contrato",
        en="Code of the contract type",
        es="Código del tipo de contrato",
        dic=True,
        original="codigoTipo",
    ),
    c(
        "tipo",
        "STRING",
        "Tipo de contrato, como contrato, credenciamento ou termo aditivo",
        en="Contract type, such as contract, accreditation or amendment",
        es="Tipo de contrato, como contrato, acreditación o adenda",
        original="nomeTipo",
    ),
    c(
        "codigo_categoria",
        "STRING",
        "Código da categoria do contrato",
        en="Code of the contract category",
        es="Código de la categoría del contrato",
        dic=True,
        original="codigoCategoria",
    ),
    c(
        "categoria",
        "STRING",
        "Categoria do contrato, como compras, serviços ou obras",
        en="Contract category, such as purchases, services or works",
        es="Categoría del contrato, como compras, servicios u obras",
        original="nomeCategoria",
    ),
    c(
        "codigo_subcategoria",
        "STRING",
        "Código da subcategoria do contrato",
        en="Code of the contract subcategory",
        es="Código de la subcategoría del contrato",
        dic=True,
        original="codigoSubcategoria",
    ),
    c(
        "subcategoria",
        "STRING",
        "Subcategoria do contrato",
        en="Contract subcategory",
        es="Subcategoría del contrato",
        original="nomeSubcategoria",
    ),
    c(
        "objeto",
        "STRING",
        "Descrição do objeto do contrato",
        en="Description of the contract's subject matter",
        es="Descripción del objeto del contrato",
        original="objeto",
    ),
    c(
        "informacoes_complementares",
        "STRING",
        "Informações complementares do contrato",
        en="Supplementary information about the contract",
        es="Información complementaria del contrato",
        original="informacoesComplementares",
    ),
    c(
        "unidades_requisitantes",
        "STRING",
        "Códigos das unidades requisitantes do contrato",
        en="Codes of the units that requested the contract",
        es="Códigos de las unidades solicitantes del contrato",
        obs="Lista separada por vírgula quando há mais de uma unidade",
        original="unidadesRequisitantes",
    ),
    c(
        "valor_global",
        "FLOAT64",
        "Valor global do contrato",
        en="Global value of the contract",
        es="Valor global del contrato",
        unit=BRL,
        original="valorGlobal",
    ),
    c(
        "numero_parcelas",
        "INT64",
        "Número de parcelas do contrato",
        en="Number of instalments in the contract",
        es="Número de cuotas del contrato",
        unit="unit",
        original="numeroParcelas",
    ),
    c(
        "valor_parcela",
        "FLOAT64",
        "Valor de cada parcela do contrato",
        en="Value of each contract instalment",
        es="Valor de cada cuota del contrato",
        unit=BRL,
        original="valorParcela",
    ),
    c(
        "valor_acumulado",
        "FLOAT64",
        "Valor acumulado do contrato, incluindo aditivos",
        en="Accumulated value of the contract, including amendments",
        es="Valor acumulado del contrato, incluyendo adendas",
        unit=BRL,
        original="valorAcumulado",
    ),
    c(
        "total_despesas_acessorias",
        "FLOAT64",
        "Total de despesas acessórias do contrato",
        en="Total ancillary expenses of the contract",
        es="Total de gastos accesorios del contrato",
        unit=BRL,
        obs="Integralmente vazia nas amostras verificadas em 2026-08",
        original="totalDespesasAcessorias",
    ),
    c(
        "indicador_contrato_excluido",
        "BOOLEAN",
        "Indica se o contrato foi excluído",
        en="Whether the contract was deleted",
        es="Indica si el contrato fue excluido",
        original="contratoExcluido",
    ),
    c(
        "data_vigencia_inicial",
        "DATE",
        "Data de início da vigência do contrato",
        en="Start date of the contract's validity",
        es="Fecha de inicio de la vigencia del contrato",
        original="dataVigenciaInicial",
    ),
    c(
        "data_vigencia_final",
        "DATE",
        "Data de término da vigência do contrato",
        en="End date of the contract's validity",
        es="Fecha de término de la vigencia del contrato",
        original="dataVigenciaFinal",
    ),
    c(
        "data_hora_inclusao",
        "DATETIME",
        "Data e hora de inclusão do contrato no sistema",
        en="Timestamp when the contract was added to the system",
        es="Fecha y hora de inclusión del contrato en el sistema",
        original="dataHoraInclusao",
    ),
    c(
        "data_hora_exclusao",
        "DATETIME",
        "Data e hora da exclusão do contrato",
        en="Timestamp when the contract was deleted",
        es="Fecha y hora de la exclusión del contrato",
        original="dataHoraExclusao",
    ),
]

CONTRATO_ITEM = [
    ano(),
    c(
        "numero_controle_pncp_contrato",
        "STRING",
        "Número de controle do contrato no PNCP",
        en="PNCP control number of the contract",
        es="Número de control del contrato en el PNCP",
        original="numeroControlePncpContrato",
    ),
    c(
        "numero_contrato",
        "STRING",
        "Número do contrato na unidade gestora",
        en="Contract number within the managing unit",
        es="Número del contrato en la unidad gestora",
        original="numeroContrato",
    ),
    c(
        "numero_item",
        "STRING",
        "Número do item dentro do contrato",
        en="Item number within the contract",
        es="Número del ítem dentro del contrato",
        obs="Com codigo_orgao, codigo_unidade_gestora e numero_contrato forma a chave primária",
        original="numeroItem",
    ),
    *_ORG,
    c(
        "id_compra",
        "STRING",
        "Identificador da contratação de origem no SIASG",
        en="Identifier of the originating procurement in SIASG",
        es="Identificador de la contratación de origen en el SIASG",
        original="idCompra",
    ),
    c(
        "numero_controle_pncp_compra",
        "STRING",
        "Número de controle da contratação de origem no PNCP",
        en="PNCP control number of the originating procurement",
        es="Número de control de la contratación de origen en el PNCP",
        original="numeroControlePncpCompra",
    ),
    *_COMPRA,
    *_FORN,
    c(
        "processo",
        "STRING",
        "Número do processo administrativo do contrato",
        en="Administrative case number of the contract",
        es="Número del proceso administrativo del contrato",
        original="processo",
    ),
    c(
        "esfera",
        "STRING",
        "Esfera federativa do órgão contratante",
        en="Federative sphere of the contracting body",
        es="Esfera federativa del órgano contratante",
        obs="Publicada por extenso nesta tabela, ao contrário da coluna esfera de contratacao, "
        "que traz a sigla",
        original="esfera",
    ),
    c(
        "poder",
        "STRING",
        "Poder ao qual o órgão contratante pertence",
        en="Branch of government of the contracting body",
        es="Poder al que pertenece el órgano contratante",
        obs="Publicado por extenso nesta tabela",
        original="poder",
    ),
    c(
        "tipo_item",
        "STRING",
        "Indica se o item é material ou serviço",
        en="Whether the item is a material or a service",
        es="Indica si el ítem es material o servicio",
        original="tipoItem",
    ),
    c(
        "codigo_item",
        "STRING",
        "Código do item nos catálogos CATMAT ou CATSER",
        en="Code of the item in the CATMAT or CATSER catalogues",
        es="Código del ítem en los catálogos CATMAT o CATSER",
        original="codigoItem",
    ),
    c(
        "descricao_item",
        "STRING",
        "Descrição do item contratado",
        en="Description of the contracted item",
        es="Descripción del ítem contratado",
        original="descricaoIitem",
    ),
    c(
        "quantidade_item",
        "FLOAT64",
        "Quantidade contratada do item",
        en="Contracted quantity of the item",
        es="Cantidad contratada del ítem",
        unit="unit",
        original="quantidadeItem",
    ),
    c(
        "valor_unitario_item",
        "FLOAT64",
        "Valor unitário do item contratado",
        en="Unit value of the contracted item",
        es="Valor unitario del ítem contratado",
        unit=BRL,
        original="valorUnitarioItem",
    ),
    c(
        "valor_total_item",
        "FLOAT64",
        "Valor total do item contratado",
        en="Total value of the contracted item",
        es="Valor total del ítem contratado",
        unit=BRL,
        original="valorTotalItem",
    ),
    c(
        "valor_global",
        "FLOAT64",
        "Valor global do contrato ao qual o item pertence",
        en="Global value of the contract the item belongs to",
        es="Valor global del contrato al que pertenece el ítem",
        unit=BRL,
        original="valorGlobal",
    ),
    c(
        "indicador_contrato_excluido",
        "BOOLEAN",
        "Indica se o contrato foi excluído",
        en="Whether the contract was deleted",
        es="Indica si el contrato fue excluido",
        original="contratoExcluido",
    ),
    c(
        "indicador_item_excluido",
        "BOOLEAN",
        "Indica se o item do contrato foi excluído",
        en="Whether the contract item was deleted",
        es="Indica si el ítem del contrato fue excluido",
        original="contratoItemExcluido",
    ),
    c(
        "data_vigencia_inicial",
        "DATE",
        "Data de início da vigência do contrato",
        en="Start date of the contract's validity",
        es="Fecha de inicio de la vigencia del contrato",
        original="dataVigenciaInicial",
    ),
    c(
        "data_vigencia_final",
        "DATE",
        "Data de término da vigência do contrato",
        en="End date of the contract's validity",
        es="Fecha de término de la vigencia del contrato",
        original="dataVigenciaFinal",
    ),
    c(
        "data_hora_inclusao",
        "DATETIME",
        "Data e hora de inclusão do item no sistema",
        en="Timestamp when the item was added to the system",
        es="Fecha y hora de inclusión del ítem en el sistema",
        original="dataHoraInclusao",
    ),
    c(
        "data_hora_exclusao_item",
        "DATETIME",
        "Data e hora da exclusão do item do contrato",
        en="Timestamp when the contract item was deleted",
        es="Fecha y hora de la exclusión del ítem del contrato",
        original="dataHoraExclusaoItem",
    ),
    c(
        "data_hora_exclusao_contrato",
        "DATETIME",
        "Data e hora da exclusão do contrato",
        en="Timestamp when the contract was deleted",
        es="Fecha y hora de la exclusión del contrato",
        original="dataHoraExclusaoContrato",
    ),
]

TABLES = {"contrato": CONTRATO, "contrato_item": CONTRATO_ITEM}
