"""Constantes da Sinopse Estatística da Educação Básica.

O porquê de cada escolha está no README do conjunto.
"""

import os
import re
from pathlib import Path

REDES_PUBLICAS = ("Federal", "Estadual", "Municipal")

TOTAL = "Total"

NIVEIS_PUBLICA = ("Rede Pública", "Pública")

NIVEIS_PRIVADA = ("Rede Privada", "Privada")

NIVEIS_AGREGADOS = (
    "Ano e Dependência Administrativa",
    "Etapa de Ensino e Dependência Administrativa",
)

FOOTNOTE = re.compile(r"(\D)\d+$")

N_COLS_HEADER = 200

DATA_DIR = Path(
    os.environ.get(
        "SINOPSE_DATA_DIR",
        Path.home()
        / "Downloads"
        / "br_inep_sinopse_estatistica_educacao_basica_data",
    )
)

INPUT = DATA_DIR / "input"

OUTPUT = DATA_DIR / "output"

URL = "https://download.inep.gov.br/dados_abertos/sinopses_estatisticas/sinopse_estatistica_censo_escolar_2025.zip"

ZIP_PATH = INPUT / "2025.zip"

sheets_etapa_ensino_serie = {
    "educacao_infantil": ("Educação Infantil 1.8", 11),
    "anos_iniciais": ("Anos Iniciais 1.22", 10),  # Ensino Fundamental
    "anos_finais": ("Anos Finais 1.28", 10),  # Ensino Fundamental
    "ensino_medio": ("1.35", 10),
    "ensino_profissional": ("Educação Profissional 1.42", 12),
    "eja": ("EJA 1.49", 11),
}

ETAPAS_PROFISSIONAL: dict[str, tuple[str, str]] = {
    "Ensino Médio Normal/Magistério": (
        "ep_2",
        "Educação Profissional - Ensino Médio Normal/Magistério",
    ),
    "Curso Técnico - Concomitante": (
        "ep_8",
        "Educação Profissional - Curso Técnico Concomitante",
    ),
    "Curso Técnico - Subsequente": (
        "ep_9",
        "Educação Profissional - Curso Técnico Subsequente",
    ),
    "Curso FIC Concomitante": (
        "ep_10",
        "Educação Profissional - Curso FIC Concomitante",
    ),
    "Curso Técnico Integrado à EJA de Nível Médio": (
        "ep_13",
        "Educação Profissional - Curso Técnico Integrado à EJA de Nível Médio",
    ),
    "Curso FIC Integrado na Modalidade EJA de Nível Fundamental": (
        "ep_14",
        "Educação Profissional - Curso FIC Integrado na Modalidade EJA de"
        " Nível Fundamental",
    ),
    "Curso FIC Integrado na Modalidade EJA de Nível Médio": (
        "ep_15",
        "Educação Profissional - Curso FIC Integrado na Modalidade EJA de"
        " Nível Médio",
    ),
    "Ensino Médio articulado ao Itinerário Formativo Técnico Profissional -"
    " Curso Técnico": (
        "ep_1",
        "Educação Profissional - Ensino Médio articulado ao Itinerário"
        " Formativo Técnico Profissional - Curso Técnico",
    ),
    "Ensino Médio articulado ao Itinerário Formativo Técnico Profissional -"
    " Qualificação Profissional": (
        "ep_16",
        "Educação Profissional - Ensino Médio articulado ao Itinerário"
        " Formativo Técnico Profissional - Qualificação Profissional",
    ),
    "Itinerário Formativo Técnico Profissional Exclusivo - Curso Técnico (não"
    " articulado ao ensino médio regular)": (
        "ep_12",
        "Educação Profissional - Itinerário Formativo Técnico Profissional"
        " Exclusivo - Curso Técnico (não articulado ao ensino médio regular)",
    ),
    "Itinerário Formativo Técnico Profissional Exclusivo - Qualificação"
    " Profissional (não articulado ao ensino médio regular)": (
        "ep_17",
        "Educação Profissional - Itinerário Formativo Técnico Profissional"
        " Exclusivo - Qualificação Profissional (não articulado ao ensino"
        " médio regular)",
    ),
}

ETAPAS_POR_PREFIXO: dict[str, str] = {
    prefixo: etapa for prefixo, etapa in ETAPAS_PROFISSIONAL.values()
}

BLOCOS_ETAPA_ENSINO_SERIE: dict[str, dict[str, str]] = {
    "educacao_infantil": {
        "Creche": "creche",
        "Pré-Escola": "pre_escola",
    },
    "anos_iniciais": {f"{n}º ano": str(n) for n in range(1, 6)},
    "anos_finais": {f"{n}º ano": str(n) for n in range(6, 10)},
    "ensino_medio": {
        **{f"{n}º ano": f"em_{n}" for n in range(1, 5)},
        "Não Seriada": "em_ns",
    },
    "ensino_profissional": {
        bloco: prefixo for bloco, (prefixo, _) in ETAPAS_PROFISSIONAL.items()
    },
    "eja": {
        "Ensino Fundamental": "eja_ef",
        "Ensino Médio": "eja_em",
    },
}

sheets_faixa_etaria = {
    "creche": "1.13",
    "pre_escola": "1.18",
    "anos_iniciais": "1.26",
    "anos_finais": "1.32",
    "ensino_medio": "1.40",
    "ensino_profissional": "1.46",
    "eja": "1.53",
}

RENAMES_FAIXA_ETARIA = {
    "creche": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Unnamed: 5": "ate_3_anos",
        "Unnamed: 6": "4_a_5_anos",
        "Unnamed: 7": "6_anos_ou_mais",
    },
    "pre_escola": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Unnamed: 5": "ate_3_anos",
        "Unnamed: 6": "4_a_5_anos",
        "Unnamed: 7": "6_anos_ou_mais",
    },
    "anos_iniciais": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Unnamed: 5": "ate_5_anos",
        "Unnamed: 6": "6_a_10_anos",
        "Unnamed: 7": "11_a_14_anos",
        "Unnamed: 8": "15_a_17_anos",
        "Unnamed: 9": "18_a_19_anos",
        "Unnamed: 10": "20_anos_ou_mais",
    },
    "anos_finais": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Unnamed: 5": "ate_10_anos",
        "Unnamed: 6": "11_a_14_anos",
        "Unnamed: 7": "15_a_17_anos",
        "Unnamed: 8": "18_a_19_anos",
        "Unnamed: 9": "20_a_24_anos",
        "Unnamed: 10": "25_anos_ou_mais",
    },
    "ensino_medio": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Unnamed: 5": "ate_14_anos",
        "Unnamed: 6": "15_a_17_anos",
        "Unnamed: 7": "18_a_19_anos",
        "Unnamed: 8": "20_a_24_anos",
        "Unnamed: 9": "25_anos_ou_mais",
    },
    "ensino_profissional": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Unnamed: 5": "ate_14_anos",
        "Unnamed: 6": "15_a_17_anos",
        "Unnamed: 7": "18_a_19_anos",
        "Unnamed: 8": "20_a_24_anos",
        "Unnamed: 9": "25_anos_ou_mais",
    },
    "eja": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Unnamed: 5": "ate_14_anos",
        "Unnamed: 6": "15_a_17_anos",
        "Unnamed: 7": "18_a_19_anos",
        "Unnamed: 8": "20_a_24_anos",
        "Unnamed: 9": "25_a_29_anos",
        "Unnamed: 10": "30_a_34_anos",
        "Unnamed: 11": "35_a_39_anos",
        "Unnamed: 12": "40_anos_ou_mais",
    },
}

sheets_localizacao = {
    "creche": "Creche 1.10",
    "pre_escola": "Pré-Escola 1.15",
    "anos_iniciais": "1.23",
    "anos_finais": "1.29",
    "ensino_medio": "1.37",
    "ensino_profissional": "1.43",
    "eja": "1.50",
    "classes_comuns": "1.61",
    "classes_exclusivas": "1.68",
}

#: Nível do cabeçalho que agrupa os blocos de localização. Antes dele a aba
#: repete o total por rede da etapa inteira, em colunas de mesma forma.
NIVEL_LOCALIZACAO = "Localização e Dependência Administrativa"

BLOCOS_LOCALIZACAO = {
    "Urbana": "urbana",
    "Rural": "rural",
}

sheets_tempo_ensino = {
    "creche": "1.14",
    "pre_escola": "1.19",
    "anos_iniciais": "1.27",
    "anos_finais": "1.33",
    "ensino_medio": "1.41",
    "classes_comuns": "1.66",
    "classes_exclusivas": "1.73",
}

#: Equivalente de `NIVEL_LOCALIZACAO` nas abas de tempo de ensino.
NIVEL_TEMPO_ENSINO = "Tempo Integral e Parcial e Dependência Administrativa"

BLOCOS_TEMPO_ENSINO = {
    "Tempo Integral": "integral",
    "Tempo Parcial": "parcial",
}

renames_sexo_raca_cor = {
    "Unnamed: 1": "uf",
    "Unnamed: 3": "id_municipio",
    "Unnamed: 6": "feminino_nao-declarada",
    "Unnamed: 7": "feminino_branca",
    "Unnamed: 8": "feminino_preta",
    "Unnamed: 9": "feminino_parda",
    "Unnamed: 10": "feminino_amarela",
    "Unnamed: 11": "feminino_indigena",
    "Unnamed: 13": "masculino_nao-declarada",
    "Unnamed: 14": "masculino_branca",
    "Unnamed: 15": "masculino_preta",
    "Unnamed: 16": "masculino_parda",
    "Unnamed: 17": "masculino_amarela",
    "Unnamed: 18": "masculino_indigena",
}

sheets_sexo_raca_cor = {
    "creche": "1.12",
    "pre_escola": "1.17",
    "anos_iniciais": "1.25",
    "anos_finais": "1.31",
    "ensino_medio": "1.39",
    "ensino_profissional": "1.45",
    "eja": "1.52",
    "classes_comuns": "1.63",
    "classes_exclusivas": "1.70",
}

sheets_docente_etapa_ensino = {
    "Educacao Basica": ("Educação Básica 2.1", 9),
    "Educacao Infantil": ("Educação Infantil 2.7", 11),
    "Ensino Fundamental": ("Ensino Fundamental 2.20", 11),
    "Educacao Profissional": ("Educação Profissional 2.43", 12),
    "EJA": ("EJA 2.49", 11),
    "Educacao Especial": ("Educação Especial 2.55", 11),
    "Educacao Especial - Classes Comuns": ("Classes Comuns 2.62", 11),
    "Educacao Especial - Classes Exclusivas": ("Classes Exclusivas 2.69", 11),
    "Educacao Indigena": ("Educação Indígena 2.77", 11),
}

RENAMES_DOCENTE_ETAPA_ENSINO = {
    "Educacao Basica": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Creche": "Educação Infantil - Creche",
        "Pré-Escola9": "Educação Infantil - Pré Escola",
        "Anos Iniciais11": "Ensino Fundamental - Anos Iniciais",
        "Anos Finais12": "Ensino Fundamental - Anos Finais",
        "Ensino Médio Propedêutico ": "Ensino Médio - Propedêutico",
        "Ensino Médio Normal/Magistério": "Ensino Médio - Normal/Magistério",
        "Articulado ao Itinerário Formativo Técnico Profissional (IFTP)": "Ensino Médio - Articulado ao Itinerário Formativo Técnico Profissional (IFTP) - Curso Técnico",
        "Unnamed: 15": "Ensino Médio - Articulado ao Itinerário Formativo Técnico Profissional (IFTP) - Qualificação Profissional",
        " Itinerário Formativo Exclusivo": "Ensino Médio - Itinerário Formativo Exclusivo",
        "Ensino Médio Articulado ao Itinerário Formativo Técnico Profissional  - Curso Técnico": "Educação Profissional - Ensino Médio Articulado ao Itinerário Formativo Técnico Profissional - Curso Técnico",
        "Ensino Médio Normal/Magistério.1": "Educação Profissional - Ensino Médio Normal/Magistério",
        "Curso Técnico Concomitante": "Educação Profissional - Curso Técnico Concomitante",
        "Curso Técnico Subsequente": "Educação Profissional - Curso Técnico Subsequente",
        "Itinerário Formativo Técnico Profissional Exclusivo - Curso Técnico\n(não articulado ao ensino médio regular)": "Educação Profissional - Itinerário Formativo Técnico Profissional Exclusivo - Curso Técnico (não articulado ao ensino médio regular)",
        "Curso Técnico Misto (Concomitante e Subsequente)": "Educação Profissional - Curso Técnico Misto (Concomitante e Subsequente)",
        "Curso Técnico Integrado à EJA de Nível Médio": "Educação Profissional - Curso Técnico Integrado à EJA de Nível Médio",
        "Curso FIC Concomitante": "Educação Profissional - Curso FIC Concomitante",
        "Curso FIC Integrado na Modalidade EJA17": "Educação Profissional - Curso FIC Integrado na Modalidade EJA",
        "Ensino Médio articulado ao Itinerário Formativo Técnico Profissional - Qualificação Profissional": "Educação Profissional - Ensino Médio articulado ao Itinerário Formativo Técnico Profissional - Qualificação Profissional",
        "Itinerário Formativo Técnico Profissional Exclusivo - Qualificação Profissional \n(não articulado ao ensino médio regular)": "Educação Profissional - Itinerário Formativo Técnico Profissional Exclusivo - Qualificação Profissional (não articulado ao ensino médio regular)",
        "Ensino Fundamental19": "EJA - Ensino Fundamental",
        "Ensino Médio20": "EJA - Ensino Médio",
        "Classes Comuns22": "Educação Especial - Classes Comuns",
        "Classes Exclusivas23": "Educação Especial - Classes Exclusivas",
    },
    "Educacao Infantil": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Unnamed: 15": "Creche - Pública",
        "Unnamed: 16": "Creche - Federal",
        "Unnamed: 17": "Creche - Estadual",
        "Unnamed: 18": "Creche - Municipal",
        "Unnamed: 19": "Creche - Privada",
        "Unnamed: 25": "Pré-Escola - Pública",
        "Unnamed: 26": "Pré-Escola - Federal",
        "Unnamed: 27": "Pré-Escola - Estadual",
        "Unnamed: 28": "Pré-Escola - Municipal",
        "Unnamed: 29": "Pré-Escola - Privada",
    },
    "Ensino Fundamental": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Unnamed: 15": "Anos Iniciais - Pública",
        "Unnamed: 16": "Anos Iniciais - Federal",
        "Unnamed: 17": "Anos Iniciais - Estadual",
        "Unnamed: 18": "Anos Iniciais - Municipal",
        "Unnamed: 19": "Anos Iniciais - Privada",
        "Unnamed: 25": "Anos Finais - Pública",
        "Unnamed: 26": "Anos Finais - Federal",
        "Unnamed: 27": "Anos Finais - Estadual",
        "Unnamed: 28": "Anos Finais - Municipal",
        "Unnamed: 29": "Anos Finais - Privada",
        "Unnamed: 35": "Turmas Multi - Pública",
        "Unnamed: 36": "Turmas Multi - Federal",
        "Unnamed: 37": "Turmas Multi - Estadual",
        "Unnamed: 38": "Turmas Multi - Municipal",
        "Unnamed: 39": "Turmas Multi - Privada",
    },
    "Educacao Profissional": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Unnamed: 16": "Ensino Médio articulado ao Itinerário Formativo Técnico Profissional - Curso Técnico - Pública",
        "Unnamed: 17": "Ensino Médio articulado ao Itinerário Formativo Técnico Profissional - Curso Técnico - Federal",
        "Unnamed: 18": "Ensino Médio articulado ao Itinerário Formativo Técnico Profissional - Curso Técnico - Estadual",
        "Unnamed: 19": "Ensino Médio articulado ao Itinerário Formativo Técnico Profissional - Curso Técnico - Municipal",
        "Unnamed: 20": "Ensino Médio articulado ao Itinerário Formativo Técnico Profissional - Curso Técnico - Privada",
        "Unnamed: 26": "Ensino Médio Normal/Magistério - Pública",
        "Unnamed: 27": "Ensino Médio Normal/Magistério - Federal",
        "Unnamed: 28": "Ensino Médio Normal/Magistério - Estadual",
        "Unnamed: 29": "Ensino Médio Normal/Magistério - Municipal",
        "Unnamed: 30": "Ensino Médio Normal/Magistério - Privada",
        "Unnamed: 36": "Curso Técnico Concomitante - Pública",
        "Unnamed: 37": "Curso Técnico Concomitante - Federal",
        "Unnamed: 38": "Curso Técnico Concomitante - Estadual",
        "Unnamed: 39": "Curso Técnico Concomitante - Municipal",
        "Unnamed: 40": "Curso Técnico Concomitante - Privada",
        "Unnamed: 46": "Curso Técnico Subsequente - Pública",
        "Unnamed: 47": "Curso Técnico Subsequente - Federal",
        "Unnamed: 48": "Curso Técnico Subsequente - Estadual",
        "Unnamed: 49": "Curso Técnico Subsequente - Municipal",
        "Unnamed: 50": "Curso Técnico Subsequente - Privada",
        "Unnamed: 56": "Itinerário Formativo Técnico Profissional Exclusivo - Curso Técnico (não articulado ao ensino médio regular) - Pública",
        "Unnamed: 57": "Itinerário Formativo Técnico Profissional Exclusivo - Curso Técnico (não articulado ao ensino médio regular) - Federal",
        "Unnamed: 58": "Itinerário Formativo Técnico Profissional Exclusivo - Curso Técnico (não articulado ao ensino médio regular) - Estadual",
        "Unnamed: 59": "Itinerário Formativo Técnico Profissional Exclusivo - Curso Técnico (não articulado ao ensino médio regular) - Municipal",
        "Unnamed: 60": "Itinerário Formativo Técnico Profissional Exclusivo - Curso Técnico (não articulado ao ensino médio regular) - Privada",
        "Unnamed: 76": "Curso Técnico Integrado à EJA de Nível Médio - Pública",
        "Unnamed: 77": "Curso Técnico Integrado à EJA de Nível Médio - Federal",
        "Unnamed: 78": "Curso Técnico Integrado à EJA de Nível Médio - Estadual",
        "Unnamed: 79": "Curso Técnico Integrado à EJA de Nível Médio - Municipal",
        "Unnamed: 80": "Curso Técnico Integrado à EJA de Nível Médio - Privada",
        "Unnamed: 87": "Curso FIC Concomitante - Pública",
        "Unnamed: 88": "Curso FIC Concomitante - Federal",
        "Unnamed: 89": "Curso FIC Concomitante - Estadual",
        "Unnamed: 90": "Curso FIC Concomitante - Municipal",
        "Unnamed: 91": "Curso FIC Concomitante - Privada",
        "Unnamed: 97": "Curso FIC Integrado na Modalidade EJA de Nível Fundamental - Pública",
        "Unnamed: 98": "Curso FIC Integrado na Modalidade EJA de Nível Fundamental - Federal",
        "Unnamed: 99": "Curso FIC Integrado na Modalidade EJA de Nível Fundamental - Estadual",
        "Unnamed: 100": "Curso FIC Integrado na Modalidade EJA de Nível Fundamental - Municipal",
        "Unnamed: 101": "Curso FIC Integrado na Modalidade EJA de Nível Fundamental - Privada",
        "Unnamed: 107": "Curso FIC Integrado na Modalidade EJA de Nível Médio - Pública",
        "Unnamed: 108": "Curso FIC Integrado na Modalidade EJA de Nível Médio - Federal",
        "Unnamed: 109": "Curso FIC Integrado na Modalidade EJA de Nível Médio - Estadual",
        "Unnamed: 110": "Curso FIC Integrado na Modalidade EJA de Nível Médio - Municipal",
        "Unnamed: 111": "Curso FIC Integrado na Modalidade EJA de Nível Médio - Privada",
        "Unnamed: 117": "Ensino Médio articulado ao Itinerário Formativo Técnico Profissional - Qualificação Profissional - Pública",
        "Unnamed: 118": "Ensino Médio articulado ao Itinerário Formativo Técnico Profissional - Qualificação Profissional - Federal",
        "Unnamed: 119": "Ensino Médio articulado ao Itinerário Formativo Técnico Profissional - Qualificação Profissional - Estadual",
        "Unnamed: 120": "Ensino Médio articulado ao Itinerário Formativo Técnico Profissional - Qualificação Profissional - Municipal",
        "Unnamed: 121": "Ensino Médio articulado ao Itinerário Formativo Técnico Profissional - Qualificação Profissional - Privada",
        "Unnamed: 127": "Itinerário Formativo Técnico Profissional Exclusivo - Qualificação Profissional (não articulado ao ensino médio regular) - Pública",
        "Unnamed: 128": "Itinerário Formativo Técnico Profissional Exclusivo - Qualificação Profissional (não articulado ao ensino médio regular) - Federal",
        "Unnamed: 129": "Itinerário Formativo Técnico Profissional Exclusivo - Qualificação Profissional (não articulado ao ensino médio regular) - Estadual",
        "Unnamed: 130": "Itinerário Formativo Técnico Profissional Exclusivo - Qualificação Profissional (não articulado ao ensino médio regular) - Municipal",
        "Unnamed: 131": "Itinerário Formativo Técnico Profissional Exclusivo - Qualificação Profissional (não articulado ao ensino médio regular) - Privada",
    },
    "EJA": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Unnamed: 6": "Ensino Fundamental - Pública",
        "Unnamed: 7": "Ensino Fundamental - Federal",
        "Unnamed: 8": "Ensino Fundamental - Estadual",
        "Unnamed: 9": "Ensino Fundamental - Municipal",
        "Unnamed: 10": "Ensino Fundamental - Privada",
        "Unnamed: 16": "Ensino Médio - Pública",
        "Unnamed: 17": "Ensino Médio - Federal",
        "Unnamed: 18": "Ensino Médio - Estadual",
        "Unnamed: 19": "Ensino Médio - Municipal",
        "Unnamed: 20": "Ensino Médio - Privada",
    },
    "Educacao Especial": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Unnamed: 8": "Educação Infantil - Creche",
        "Unnamed: 9": "Educação Infantil - Pré Escola",
        "Unnamed: 11": "Ensino Fundamental - Anos Iniciais",
        "Unnamed: 12": "Ensino Fundamental - Anos Finais",
        "Unnamed: 14": "Ensino Médio - Propedêutico",
        "Unnamed: 15": "Ensino Médio - Normal/Magistério",
        "Unnamed: 16": "Ensino Médio - Articulado ao Itinerário Formativo Técnico Profissional (IFTP) - Curso Técnico",
        "Unnamed: 17": "Ensino Médio - Articulado ao Itinerário Formativo Técnico Profissional (IFTP) - Qualificação Profissional",
        "Unnamed: 18": "Ensino Médio - Itinerário Formativo Exclusivo - Turma de Itinerário Formativo de Aprofundamento (IFA) ou Itinerário Formativo Técnico Profissional (IFTP), que possui algum aluno do Ensino Médio Regular",
        "Unnamed: 21": "Educação Profissional - Educação Profissional Técnica - Ensino Médio Articulado ao Itinerário Formativo Técnico Profissional - Curso Técnico",
        "Unnamed: 22": "Educação Profissional - Educação Profissional Técnica - Ensino Médio Normal/Magistério",
        "Unnamed: 23": "Educação Profissional - Educação Profissional Técnica - Curso Técnico Concomitante",
        "Unnamed: 24": "Educação Profissional - Educação Profissional Técnica - Curso Técnico Subsequente",
        "Unnamed: 25": "Educação Profissional - Educação Profissional Técnica - Itinerário Formativo Técnico Profissional Exclusivo - Curso Técnico (não articulado ao ensino médio regular)",
        "Unnamed: 26": "Educação Profissional - Educação Profissional Técnica - Curso Técnico Misto (Concomitante e Subsequente)",
        "Unnamed: 27": "Educação Profissional - Educação Profissional Técnica - Curso Técnico Integrado à EJA de Nível Médio",
        "Unnamed: 29": "Educação Profissional - Formação Inicial Continuada (FIC) ou Qualificação Profissional - Curso FIC Concomitante",
        "Unnamed: 30": "Educação Profissional - Formação Inicial Continuada (FIC) ou Qualificação Profissional - Curso FIC Integrado na Modalidade EJA",
        "Unnamed: 31": "Educação Profissional - Formação Inicial Continuada (FIC) ou Qualificação Profissional - Ensino Médio articulado ao Itinerário Formativo Técnico Profissional - Qualificação Profissional",
        "Unnamed: 32": "Educação Profissional - Formação Inicial Continuada (FIC) ou Qualificação Profissional - Itinerário Formativo Técnico Profissional Exclusivo - Qualificação Profissional (não articulado ao ensino médio regular)",
        "Unnamed: 34": "EJA - Ensino Fundamental",
        "Unnamed: 35": "EJA - Ensino Médio",
    },
    "Educacao Especial - Classes Comuns": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Unnamed: 6": "Educação Infantil - Creche",
        "Unnamed: 7": "Educação Infantil - Pré Escola",
        "Unnamed: 9": "Ensino Fundamental - Anos Iniciais",
        "Unnamed: 10": "Ensino Fundamental - Anos Finais",
        "Unnamed: 12": "Ensino Médio - Propedêutico",
        "Unnamed: 13": "Ensino Médio - Normal/Magistério",
        "Unnamed: 14": "Ensino Médio - Articulado ao Itinerário Formativo Técnico Profissional (IFTP) - Curso Técnico",
        "Unnamed: 15": "Ensino Médio - Articulado ao Itinerário Formativo Técnico Profissional (IFTP) - Qualificação Profissional",
        "Unnamed: 16": "Ensino Médio - Itinerário Formativo Exclusivo - Turma de Itinerário Formativo de Aprofundamento (IFA) ou Itinerário Formativo Técnico Profissional (IFTP), que possui algum aluno do Ensino Médio Regular",
        "Unnamed: 19": "Educação Profissional - Educação Profissional Técnica - Ensino Médio Articulado ao Itinerário Formativo Técnico Profissional - Curso Técnico",
        "Unnamed: 20": "Educação Profissional - Educação Profissional Técnica - Ensino Médio Normal/Magistério",
        "Unnamed: 21": "Educação Profissional - Educação Profissional Técnica - Curso Técnico Concomitante",
        "Unnamed: 22": "Educação Profissional - Educação Profissional Técnica - Curso Técnico Subsequente",
        "Unnamed: 23": "Educação Profissional - Educação Profissional Técnica - Itinerário Formativo Técnico Profissional Exclusivo - Curso Técnico (não articulado ao ensino médio regular)",
        "Unnamed: 24": "Educação Profissional - Educação Profissional Técnica - Curso Técnico Misto (Concomitante e Subsequente)",
        "Unnamed: 25": "Educação Profissional - Educação Profissional Técnica - Curso Técnico Integrado à EJA de Nível Médio",
        "Unnamed: 27": "Educação Profissional - Formação Inicial Continuada (FIC) ou Qualificação Profissional - Curso FIC Concomitante",
        "Unnamed: 28": "Educação Profissional - Formação Inicial Continuada (FIC) ou Qualificação Profissional - Curso FIC Integrado na Modalidade EJA",
        "Unnamed: 29": "Educação Profissional - Formação Inicial Continuada (FIC) ou Qualificação Profissional - Ensino Médio articulado ao Itinerário Formativo Técnico Profissional - Qualificação Profissional",
        "Unnamed: 30": "Educação Profissional - Formação Inicial Continuada (FIC) ou Qualificação Profissional - Itinerário Formativo Técnico Profissional Exclusivo - Qualificação Profissional (não articulado ao ensino médio regular)",
        "Unnamed: 32": "EJA - Ensino Fundamental",
        "Unnamed: 33": "EJA - Ensino Médio",
    },
    "Educacao Especial - Classes Exclusivas": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Unnamed: 6": "Educação Infantil - Creche",
        "Unnamed: 7": "Educação Infantil - Pré Escola",
        "Unnamed: 9": "Ensino Fundamental - Anos Iniciais",
        "Unnamed: 10": "Ensino Fundamental - Anos Finais",
        "Unnamed: 12": "Ensino Médio - Propedêutico",
        "Unnamed: 13": "Ensino Médio - Normal/Magistério",
        "Unnamed: 14": "Ensino Médio - Articulado ao Itinerário Formativo Técnico Profissional (IFTP) - Curso Técnico",
        "Unnamed: 15": "Ensino Médio - Articulado ao Itinerário Formativo Técnico Profissional (IFTP) - Qualificação Profissional",
        "Unnamed: 16": "Ensino Médio - Itinerário Formativo Exclusivo - Turma de Itinerário Formativo de Aprofundamento (IFA) ou Itinerário Formativo Técnico Profissional (IFTP), que possui algum aluno do Ensino Médio Regular",
        "Unnamed: 19": "Educação Profissional - Educação Profissional Técnica - Ensino Médio Articulado ao Itinerário Formativo Técnico Profissional - Curso Técnico",
        "Unnamed: 20": "Educação Profissional - Educação Profissional Técnica - Ensino Médio Normal/Magistério",
        "Unnamed: 21": "Educação Profissional - Educação Profissional Técnica - Curso Técnico Concomitante",
        "Unnamed: 22": "Educação Profissional - Educação Profissional Técnica - Curso Técnico Subsequente",
        "Unnamed: 23": "Educação Profissional - Educação Profissional Técnica - Itinerário Formativo Técnico Profissional Exclusivo - Curso Técnico (não articulado ao ensino médio regular)",
        "Unnamed: 24": "Educação Profissional - Educação Profissional Técnica - Curso Técnico Misto (Concomitante e Subsequente)",
        "Unnamed: 25": "Educação Profissional - Educação Profissional Técnica - Curso Técnico Integrado à EJA de Nível Médio",
        "Unnamed: 27": "Educação Profissional - Formação Inicial Continuada (FIC) ou Qualificação Profissional - Curso FIC Concomitante",
        "Unnamed: 28": "Educação Profissional - Formação Inicial Continuada (FIC) ou Qualificação Profissional - Curso FIC Integrado na Modalidade EJA",
        "Unnamed: 29": "Educação Profissional - Formação Inicial Continuada (FIC) ou Qualificação Profissional - Ensino Médio articulado ao Itinerário Formativo Técnico Profissional - Qualificação Profissional",
        "Unnamed: 30": "Educação Profissional - Formação Inicial Continuada (FIC) ou Qualificação Profissional - Itinerário Formativo Técnico Profissional Exclusivo - Qualificação Profissional (não articulado ao ensino médio regular)",
        "Unnamed: 32": "EJA - Ensino Fundamental",
        "Unnamed: 33": "EJA - Ensino Médio",
    },
    "Educacao Indigena": {
        "  ": "uf",
        " ": "id_municipio",
        "Unnamed: 6": "Educação Infantil - Creche",
        "Unnamed: 7": "Educação Infantil - Pré Escola",
        "Unnamed: 9": "Ensino Fundamental - Anos Iniciais",
        "Unnamed: 10": "Ensino Fundamental - Anos Finais",
        "Unnamed: 12": "Ensino Médio - Propedêutico",
        "Unnamed: 13": "Ensino Médio - Normal/Magistério",
        "Unnamed: 14": "Ensino Médio - Articulado ao Itinerário Formativo Técnico Profissional (IFTP) - Curso Técnico",
        "Unnamed: 15": "Ensino Médio - Articulado ao Itinerário Formativo Técnico Profissional (IFTP) - Qualificação Profissional",
        "Unnamed: 16": "Ensino Médio - Itinerário Formativo Exclusivo - Turma de Itinerário Formativo de Aprofundamento (IFA) ou Itinerário Formativo Técnico Profissional (IFTP), que possui algum aluno do Ensino Médio Regular",
        "Unnamed: 19": "Educação Profissional - Educação Profissional Técnica - Ensino Médio Articulado ao Itinerário Formativo Técnico Profissional - Curso Técnico",
        "Unnamed: 20": "Educação Profissional - Educação Profissional Técnica - Ensino Médio Normal/Magistério",
        "Unnamed: 21": "Educação Profissional - Educação Profissional Técnica - Curso Técnico Concomitante",
        "Unnamed: 22": "Educação Profissional - Educação Profissional Técnica - Curso Técnico Subsequente",
        "Unnamed: 23": "Educação Profissional - Educação Profissional Técnica - Itinerário Formativo Técnico Profissional Exclusivo - Curso Técnico (não articulado ao ensino médio regular)",
        "Unnamed: 24": "Educação Profissional - Educação Profissional Técnica - Curso Técnico Misto (Concomitante e Subsequente)",
        "Unnamed: 25": "Educação Profissional - Educação Profissional Técnica - Curso Técnico Integrado à EJA de Nível Médio",
        "Unnamed: 27": "Educação Profissional - Formação Inicial Continuada (FIC) ou Qualificação Profissional - Curso FIC Concomitante",
        "Unnamed: 28": "Educação Profissional - Formação Inicial Continuada (FIC) ou Qualificação Profissional - Curso FIC Integrado na Modalidade EJA",
        "Unnamed: 29": "Educação Profissional - Formação Inicial Continuada (FIC) ou Qualificação Profissional - Ensino Médio articulado ao Itinerário Formativo Técnico Profissional - Qualificação Profissional",
        "Unnamed: 30": "Educação Profissional - Formação Inicial Continuada (FIC) ou Qualificação Profissional - Itinerário Formativo Técnico Profissional Exclusivo - Qualificação Profissional (não articulado ao ensino médio regular)",
        "Unnamed: 32": "EJA - Ensino Fundamental",
        "Unnamed: 33": "EJA - Ensino Médio",
        "Unnamed: 35": "Educação Especial - Classes Comuns",
        "Unnamed: 36": "Educação Especial - Classes Exclusivas",
    },
}

sheets_docente_localizacao = {
    "Educação Básica": "2.2",
    "Educação Infantil": "2.9",
    "Educação Infantil - Creche": "Creche 2.10",
    "Educação Infantil - Pré-Escola": "Pré-Escola 2.15",
    "Ensino Fundamental": "2.21",
    "Ensino Fundamental - Anos Iniciais": "Anos Iniciais 2.26",
    "Ensino Fundamental - Anos Finais": "Anos Finais 2.31",
    "Ensino Médio": "2.38",
    "Educação Profissional": "2.44",
    "EJA": "2.50",
    "Educação Especial - Classes Comuns": "2.63",
    "Educação Especial - Classes Exclusivas": "2.70",
}

sheets_docente_escolaridade = {
    "Educacao Basica": "2.5",
    "Educacao Infantil - Creche": "2.13",
    "Educacao Infantil - Pré-Escola": "2.18",
    "Ensino Fundamental": "2.24",
    "Ensino Fundamental - Anos Iniciais": "2.29",
    "Ensino Fundamental - Anos Finais": "2.34",
    "Ensino Médio": "2.41",
    "Educacao Profissional": "2.47",
    "EJA": "2.53",
    "Educacao Especial - Classes Comuns": "2.66",
    "Educacao Especial - Classes Exclusivas": "2.73",
}


sheets_docente_deficiencia = {
    "Educacao Especial - Classes Comuns": "2.67",
    "Educacao Especial - Classes Exclusivas": "2.74",
}

RENAMES_DOCENTE_DEFICIENCIA = {
    "Educacao Especial - Classes Comuns": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Cegueira": "Cegueira",
        "Baixa Visão": "Baixa Visão",
        "Surdez": "Surdez",
        "Deficiência Auditiva": "Deficiência Auditiva",
        "Surdocegueira": "Surdocegueira",
        "Deficiência Física": "Deficiência Física",
        "Deficiência Intelectual": "Deficiência Intelectual",
        "Deficiência Múltipla": "Deficiência Múltipla",
        "Transtorno do Espectro Autista": "Transtorno do Espectro Autista",
        "Altas Habilidades / Superdotação": "Altas Habilidades / Superdotação",
    },
    "Educacao Especial - Classes Exclusivas": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Cegueira": "Cegueira",
        "Baixa Visão": "Baixa Visão",
        "Surdez": "Surdez",
        "Deficiência Auditiva": "Deficiência Auditiva",
        "Surdocegueira": "Surdocegueira",
        "Deficiência Física": "Deficiência Física",
        "Deficiência Intelectual": "Deficiência Intelectual",
        "Deficiência Múltipla": "Deficiência Múltipla",
        "Transtorno do Espectro Autista": "Transtorno do Espectro Autista",
        "Altas Habilidades / Superdotação": "Altas Habilidades / Superdotação",
    },
}

sheets_docente_faixa_etaria_sexo = {
    "Educação Básica": "2.4",
    "Educação Infantil - Creche": "2.12",
    "Educação Infantil - Pré-Escola": "2.17",
    "Ensino Fundamental": "2.23",
    "Ensino Fundamental - Anos Iniciais": "2.28",
    "Ensino Fundamental - Anos Finais": "2.33",
    "Ensino Médio": "2.40",
    "Educação Profissional": "2.46",
    "EJA": "2.52",
    "Educação Especial - Classes Comuns": "2.65",
    "Educação Especial - Classes Exclusivas": "2.72",
}

RENAMES_DOCENTE_FAIXA_ETARIA_SEXO = {
    "Educação Básica": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Até 24 anos": "Feminino_Até 24 anos",
        "De 25 a 29 anos": "Feminino_25 a 29 anos",
        "De 30 a 39 anos": "Feminino_30 a 39 anos",
        "De 40 a 49 anos": "Feminino_40 a 49 anos",
        "De 50 a 54 anos": "Feminino_50 a 54 anos",
        "De 55 a 59 anos": "Feminino_55 a 59 anos",
        "60 anos ou mais": "Feminino_60 anos ou mais",
        "Até 24 anos.1": "Masculino_Até 24 anos",
        "De 25 a 29 anos.1": "Masculino_25 a 29 anos",
        "De 30 a 39 anos.1": "Masculino_30 a 39 anos",
        "De 40 a 49 anos.1": "Masculino_40 a 49 anos",
        "De 50 a 54 anos.1": "Masculino_50 a 54 anos",
        "De 55 a 59 anos.1": "Masculino_55 a 59 anos",
        "60 anos ou mais.1": "Masculino_60 anos ou mais",
    },
    "Educação Infantil - Creche": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Até 24 anos": "Feminino_Até 24 anos",
        "De 25 a 29 anos": "Feminino_25 a 29 anos",
        "De 30 a 39 anos": "Feminino_30 a 39 anos",
        "De 40 a 49 anos": "Feminino_40 a 49 anos",
        "De 50 a 54 anos": "Feminino_50 a 54 anos",
        "De 55 a 59 anos": "Feminino_55 a 59 anos",
        "60 anos ou mais": "Feminino_60 anos ou mais",
        "Até 24 anos.1": "Masculino_Até 24 anos",
        "De 25 a 29 anos.1": "Masculino_25 a 29 anos",
        "De 30 a 39 anos.1": "Masculino_30 a 39 anos",
        "De 40 a 49 anos.1": "Masculino_40 a 49 anos",
        "De 50 a 54 anos.1": "Masculino_50 a 54 anos",
        "De 55 a 59 anos.1": "Masculino_55 a 59 anos",
        "60 anos ou mais.1": "Masculino_60 anos ou mais",
    },
    "Educação Infantil - Pré-Escola": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Até 24 anos": "Feminino_Até 24 anos",
        "De 25 a 29 anos": "Feminino_25 a 29 anos",
        "De 30 a 39 anos": "Feminino_30 a 39 anos",
        "De 40 a 49 anos": "Feminino_40 a 49 anos",
        "De 50 a 54 anos": "Feminino_50 a 54 anos",
        "De 55 a 59 anos": "Feminino_55 a 59 anos",
        "60 anos ou mais": "Feminino_60 anos ou mais",
        "Até 24 anos.1": "Masculino_Até 24 anos",
        "De 25 a 29 anos.1": "Masculino_25 a 29 anos",
        "De 30 a 39 anos.1": "Masculino_30 a 39 anos",
        "De 40 a 49 anos.1": "Masculino_40 a 49 anos",
        "De 50 a 54 anos.1": "Masculino_50 a 54 anos",
        "De 55 a 59 anos.1": "Masculino_55 a 59 anos",
        "60 anos ou mais.1": "Masculino_60 anos ou mais",
    },
    "Ensino Fundamental": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Até 24 anos": "Feminino_Até 24 anos",
        "De 25 a 29 anos": "Feminino_25 a 29 anos",
        "De 30 a 39 anos": "Feminino_30 a 39 anos",
        "De 40 a 49 anos": "Feminino_40 a 49 anos",
        "De 50 a 54 anos": "Feminino_50 a 54 anos",
        "De 55 a 59 anos": "Feminino_55 a 59 anos",
        "60 anos ou mais": "Feminino_60 anos ou mais",
        "Até 24 anos.1": "Masculino_Até 24 anos",
        "De 25 a 29 anos.1": "Masculino_25 a 29 anos",
        "De 30 a 39 anos.1": "Masculino_30 a 39 anos",
        "De 40 a 49 anos.1": "Masculino_40 a 49 anos",
        "De 50 a 54 anos.1": "Masculino_50 a 54 anos",
        "De 55 a 59 anos.1": "Masculino_55 a 59 anos",
        "60 anos ou mais.1": "Masculino_60 anos ou mais",
    },
    "Ensino Fundamental - Anos Iniciais": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Até 24 anos": "Feminino_Até 24 anos",
        "De 25 a 29 anos": "Feminino_25 a 29 anos",
        "De 30 a 39 anos": "Feminino_30 a 39 anos",
        "De 40 a 49 anos": "Feminino_40 a 49 anos",
        "De 50 a 54 anos": "Feminino_50 a 54 anos",
        "De 55 a 59 anos": "Feminino_55 a 59 anos",
        "60 anos ou mais": "Feminino_60 anos ou mais",
        "Até 24 anos.1": "Masculino_Até 24 anos",
        "De 25 a 29 anos.1": "Masculino_25 a 29 anos",
        "De 30 a 39 anos.1": "Masculino_30 a 39 anos",
        "De 40 a 49 anos.1": "Masculino_40 a 49 anos",
        "De 50 a 54 anos.1": "Masculino_50 a 54 anos",
        "De 55 a 59 anos.1": "Masculino_55 a 59 anos",
        "60 anos ou mais.1": "Masculino_60 anos ou mais",
    },
    "Ensino Fundamental - Anos Finais": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Até 24 anos": "Feminino_Até 24 anos",
        "De 25 a 29 anos": "Feminino_25 a 29 anos",
        "De 30 a 39 anos": "Feminino_30 a 39 anos",
        "De 40 a 49 anos": "Feminino_40 a 49 anos",
        "De 50 a 54 anos": "Feminino_50 a 54 anos",
        "De 55 a 59 anos": "Feminino_55 a 59 anos",
        "60 anos ou mais": "Feminino_60 anos ou mais",
        "Até 24 anos.1": "Masculino_Até 24 anos",
        "De 25 a 29 anos.1": "Masculino_25 a 29 anos",
        "De 30 a 39 anos.1": "Masculino_30 a 39 anos",
        "De 40 a 49 anos.1": "Masculino_40 a 49 anos",
        "De 50 a 54 anos.1": "Masculino_50 a 54 anos",
        "De 55 a 59 anos.1": "Masculino_55 a 59 anos",
        "60 anos ou mais.1": "Masculino_60 anos ou mais",
    },
    "Ensino Médio": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Até 24 anos": "Feminino_Até 24 anos",
        "De 25 a 29 anos": "Feminino_25 a 29 anos",
        "De 30 a 39 anos": "Feminino_30 a 39 anos",
        "De 40 a 49 anos": "Feminino_40 a 49 anos",
        "De 50 a 54 anos": "Feminino_50 a 54 anos",
        "De 55 a 59 anos": "Feminino_55 a 59 anos",
        "60 anos ou mais": "Feminino_60 anos ou mais",
        "Até 24 anos.1": "Masculino_Até 24 anos",
        "De 25 a 29 anos.1": "Masculino_25 a 29 anos",
        "De 30 a 39 anos.1": "Masculino_30 a 39 anos",
        "De 40 a 49 anos.1": "Masculino_40 a 49 anos",
        "De 50 a 54 anos.1": "Masculino_50 a 54 anos",
        "De 55 a 59 anos.1": "Masculino_55 a 59 anos",
        "60 anos ou mais.1": "Masculino_60 anos ou mais",
    },
    "Educação Profissional": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Até 24 anos": "Feminino_Até 24 anos",
        "De 25 a 29 anos": "Feminino_25 a 29 anos",
        "De 30 a 39 anos": "Feminino_30 a 39 anos",
        "De 40 a 49 anos": "Feminino_40 a 49 anos",
        "De 50 a 54 anos": "Feminino_50 a 54 anos",
        "De 55 a 59 anos": "Feminino_55 a 59 anos",
        "60 anos ou mais": "Feminino_60 anos ou mais",
        "Até 24 anos.1": "Masculino_Até 24 anos",
        "De 25 a 29 anos.1": "Masculino_25 a 29 anos",
        "De 30 a 39 anos.1": "Masculino_30 a 39 anos",
        "De 40 a 49 anos.1": "Masculino_40 a 49 anos",
        "De 50 a 54 anos.1": "Masculino_50 a 54 anos",
        "De 55 a 59 anos.1": "Masculino_55 a 59 anos",
        "60 anos ou mais.1": "Masculino_60 anos ou mais",
    },
    "EJA": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Até 24 anos": "Feminino_Até 24 anos",
        "De 25 a 29 anos": "Feminino_25 a 29 anos",
        "De 30 a 39 anos": "Feminino_30 a 39 anos",
        "De 40 a 49 anos": "Feminino_40 a 49 anos",
        "De 50 a 54 anos": "Feminino_50 a 54 anos",
        "De 55 a 59 anos": "Feminino_55 a 59 anos",
        "60 anos ou mais": "Feminino_60 anos ou mais",
        "Até 24 anos.1": "Masculino_Até 24 anos",
        "De 25 a 29 anos.1": "Masculino_25 a 29 anos",
        "De 30 a 39 anos.1": "Masculino_30 a 39 anos",
        "De 40 a 49 anos.1": "Masculino_40 a 49 anos",
        "De 50 a 54 anos.1": "Masculino_50 a 54 anos",
        "De 55 a 59 anos.1": "Masculino_55 a 59 anos",
        "60 anos ou mais.1": "Masculino_60 anos ou mais",
    },
    "Educação Especial - Classes Comuns": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Até 24 anos": "Feminino_Até 24 anos",
        "De 25 a 29 anos": "Feminino_25 a 29 anos",
        "De 30 a 39 anos": "Feminino_30 a 39 anos",
        "De 40 a 49 anos": "Feminino_40 a 49 anos",
        "De 50 a 54 anos": "Feminino_50 a 54 anos",
        "De 55 a 59 anos": "Feminino_55 a 59 anos",
        "60 anos ou mais": "Feminino_60 anos ou mais",
        "Até 24 anos.1": "Masculino_Até 24 anos",
        "De 25 a 29 anos.1": "Masculino_25 a 29 anos",
        "De 30 a 39 anos.1": "Masculino_30 a 39 anos",
        "De 40 a 49 anos.1": "Masculino_40 a 49 anos",
        "De 50 a 54 anos.1": "Masculino_50 a 54 anos",
        "De 55 a 59 anos.1": "Masculino_55 a 59 anos",
        "60 anos ou mais.1": "Masculino_60 anos ou mais",
    },
    "Educação Especial - Classes Exclusivas": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Até 24 anos": "Feminino_Até 24 anos",
        "De 25 a 29 anos": "Feminino_25 a 29 anos",
        "De 30 a 39 anos": "Feminino_30 a 39 anos",
        "De 40 a 49 anos": "Feminino_40 a 49 anos",
        "De 50 a 54 anos": "Feminino_50 a 54 anos",
        "De 55 a 59 anos": "Feminino_55 a 59 anos",
        "60 anos ou mais": "Feminino_60 anos ou mais",
        "Até 24 anos.1": "Masculino_Até 24 anos",
        "De 25 a 29 anos.1": "Masculino_25 a 29 anos",
        "De 30 a 39 anos.1": "Masculino_30 a 39 anos",
        "De 40 a 49 anos.1": "Masculino_40 a 49 anos",
        "De 50 a 54 anos.1": "Masculino_50 a 54 anos",
        "De 55 a 59 anos.1": "Masculino_55 a 59 anos",
        "60 anos ou mais.1": "Masculino_60 anos ou mais",
    },
}

sheets_docente_regime_contrato = {
    "Educação Basica": "2.6",
    "Educação Infantil - Creche": "2.14",
    "Educação Infantil - Pré-Escola": "2.19",
    "Ensino Fundamental - Anos Iniciais": "2.30",
    "Ensino Fundamental - Anos Finais": "2.35",
    "Ensino Médio": "2.42",
    "Educação Profissional": "2.48",
    "EJA": "2.54",
    "Educação Especial - Classes Comuns": "2.68",
    "Educação Especial - Classes Exclusivas": "2.75",
}

RENAMES_DOCENTE_REGIME_CONTRATO = {
    "Educação Basica": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Federal": "Concursado_Federal",
        "Estadual": "Concursado_Estadual",
        "Municipal": "Concursado_Municipal",
        "Federal.1": "Contrato Temporário_Federal",
        "Estadual.1": "Contrato Temporário_Estadual",
        "Municipal.1": "Contrato Temporário_Municipal",
        "Federal.2": "Contrato Terceirizado_Federal",
        "Estadual.2": "Contrato Terceirizado_Estadual",
        "Municipal.2": "Contrato Terceirizado_Municipal",
        "Federal.3": "Contrato CLT_Federal",
        "Estadual.3": "Contrato CLT_Estadual",
        "Municipal.3": "Contrato CLT_Municipal",
    },
    "Educação Infantil - Creche": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Federal": "Concursado_Federal",
        "Estadual": "Concursado_Estadual",
        "Municipal": "Concursado_Municipal",
        "Federal.1": "Contrato Temporário_Federal",
        "Estadual.1": "Contrato Temporário_Estadual",
        "Municipal.1": "Contrato Temporário_Municipal",
        "Federal.2": "Contrato Terceirizado_Federal",
        "Estadual.2": "Contrato Terceirizado_Estadual",
        "Municipal.2": "Contrato Terceirizado_Municipal",
        "Federal.3": "Contrato CLT_Federal",
        "Estadual.3": "Contrato CLT_Estadual",
        "Municipal.3": "Contrato CLT_Municipal",
    },
    "Educação Infantil - Pré-Escola": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Federal": "Concursado_Federal",
        "Estadual": "Concursado_Estadual",
        "Municipal": "Concursado_Municipal",
        "Federal.1": "Contrato Temporário_Federal",
        "Estadual.1": "Contrato Temporário_Estadual",
        "Municipal.1": "Contrato Temporário_Municipal",
        "Federal.2": "Contrato Terceirizado_Federal",
        "Estadual.2": "Contrato Terceirizado_Estadual",
        "Municipal.2": "Contrato Terceirizado_Municipal",
        "Federal.3": "Contrato CLT_Federal",
        "Estadual.3": "Contrato CLT_Estadual",
        "Municipal.3": "Contrato CLT_Municipal",
    },
    "Ensino Fundamental": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Federal": "Concursado_Federal",
        "Estadual": "Concursado_Estadual",
        "Municipal": "Concursado_Municipal",
        "Federal.1": "Contrato Temporário_Federal",
        "Estadual.1": "Contrato Temporário_Estadual",
        "Municipal.1": "Contrato Temporário_Municipal",
        "Federal.2": "Contrato Terceirizado_Federal",
        "Estadual.2": "Contrato Terceirizado_Estadual",
        "Municipal.2": "Contrato Terceirizado_Municipal",
        "Federal.3": "Contrato CLT_Federal",
        "Estadual.3": "Contrato CLT_Estadual",
        "Municipal.3": "Contrato CLT_Municipal",
    },
    "Ensino Fundamental - Anos Iniciais": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Federal": "Concursado_Federal",
        "Estadual": "Concursado_Estadual",
        "Municipal": "Concursado_Municipal",
        "Federal.1": "Contrato Temporário_Federal",
        "Estadual.1": "Contrato Temporário_Estadual",
        "Municipal.1": "Contrato Temporário_Municipal",
        "Federal.2": "Contrato Terceirizado_Federal",
        "Estadual.2": "Contrato Terceirizado_Estadual",
        "Municipal.2": "Contrato Terceirizado_Municipal",
        "Federal.3": "Contrato CLT_Federal",
        "Estadual.3": "Contrato CLT_Estadual",
        "Municipal.3": "Contrato CLT_Municipal",
    },
    "Ensino Fundamental - Anos Finais": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Federal": "Concursado_Federal",
        "Estadual": "Concursado_Estadual",
        "Municipal": "Concursado_Municipal",
        "Federal.1": "Contrato Temporário_Federal",
        "Estadual.1": "Contrato Temporário_Estadual",
        "Municipal.1": "Contrato Temporário_Municipal",
        "Federal.2": "Contrato Terceirizado_Federal",
        "Estadual.2": "Contrato Terceirizado_Estadual",
        "Municipal.2": "Contrato Terceirizado_Municipal",
        "Federal.3": "Contrato CLT_Federal",
        "Estadual.3": "Contrato CLT_Estadual",
        "Municipal.3": "Contrato CLT_Municipal",
    },
    "Ensino Médio": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Federal": "Concursado_Federal",
        "Estadual": "Concursado_Estadual",
        "Municipal": "Concursado_Municipal",
        "Federal.1": "Contrato Temporário_Federal",
        "Estadual.1": "Contrato Temporário_Estadual",
        "Municipal.1": "Contrato Temporário_Municipal",
        "Federal.2": "Contrato Terceirizado_Federal",
        "Estadual.2": "Contrato Terceirizado_Estadual",
        "Municipal.2": "Contrato Terceirizado_Municipal",
        "Federal.3": "Contrato CLT_Federal",
        "Estadual.3": "Contrato CLT_Estadual",
        "Municipal.3": "Contrato CLT_Municipal",
    },
    "Educação Profissional": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Federal": "Concursado_Federal",
        "Estadual": "Concursado_Estadual",
        "Municipal": "Concursado_Municipal",
        "Federal.1": "Contrato Temporário_Federal",
        "Estadual.1": "Contrato Temporário_Estadual",
        "Municipal.1": "Contrato Temporário_Municipal",
        "Federal.2": "Contrato Terceirizado_Federal",
        "Estadual.2": "Contrato Terceirizado_Estadual",
        "Municipal.2": "Contrato Terceirizado_Municipal",
        "Federal.3": "Contrato CLT_Federal",
        "Estadual.3": "Contrato CLT_Estadual",
        "Municipal.3": "Contrato CLT_Municipal",
    },
    "EJA": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Federal": "Concursado_Federal",
        "Estadual": "Concursado_Estadual",
        "Municipal": "Concursado_Municipal",
        "Federal.1": "Contrato Temporário_Federal",
        "Estadual.1": "Contrato Temporário_Estadual",
        "Municipal.1": "Contrato Temporário_Municipal",
        "Federal.2": "Contrato Terceirizado_Federal",
        "Estadual.2": "Contrato Terceirizado_Estadual",
        "Municipal.2": "Contrato Terceirizado_Municipal",
        "Federal.3": "Contrato CLT_Federal",
        "Estadual.3": "Contrato CLT_Estadual",
        "Municipal.3": "Contrato CLT_Municipal",
    },
    "Educação Especial - Classes Comuns": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Federal": "Concursado_Federal",
        "Estadual": "Concursado_Estadual",
        "Municipal": "Concursado_Municipal",
        "Federal.1": "Contrato Temporário_Federal",
        "Estadual.1": "Contrato Temporário_Estadual",
        "Municipal.1": "Contrato Temporário_Municipal",
        "Federal.2": "Contrato Terceirizado_Federal",
        "Estadual.2": "Contrato Terceirizado_Estadual",
        "Municipal.2": "Contrato Terceirizado_Municipal",
        "Federal.3": "Contrato CLT_Federal",
        "Estadual.3": "Contrato CLT_Estadual",
        "Municipal.3": "Contrato CLT_Municipal",
    },
    "Educação Especial - Classes Exclusivas": {
        "Unnamed: 1": "uf",
        "Unnamed: 3": "id_municipio",
        "Federal": "Concursado_Federal",
        "Estadual": "Concursado_Estadual",
        "Municipal": "Concursado_Municipal",
        "Federal.1": "Contrato Temporário_Federal",
        "Estadual.1": "Contrato Temporário_Estadual",
        "Municipal.1": "Contrato Temporário_Municipal",
        "Federal.2": "Contrato Terceirizado_Federal",
        "Estadual.2": "Contrato Terceirizado_Estadual",
        "Municipal.2": "Contrato Terceirizado_Municipal",
        "Federal.3": "Contrato CLT_Federal",
        "Estadual.3": "Contrato CLT_Estadual",
        "Municipal.3": "Contrato CLT_Municipal",
    },
}

RENAMES_DOCENTE_LOCALIZACAO = {
    "Unnamed: 1": "uf",
    "Unnamed: 3": "id_municipio",
    "Unnamed: 16": "urbana_federal",
    "Unnamed: 17": "urbana_estadual",
    "Unnamed: 18": "urbana_municipal",
    "Unnamed: 19": "urbana_privada",
    "Unnamed: 26": "rural_federal",
    "Unnamed: 27": "rural_estadual",
    "Unnamed: 28": "rural_municipal",
    "Unnamed: 29": "rural_privada",
}

RENAMES_DOCENTE_ESCOLARIDADE = {
    "Unnamed: 1": "uf",
    "Unnamed: 3": "id_municipio",
    "Unnamed: 5": "Ensino Fundamental",
    "Unnamed: 6": "Ensino Médio",
    "Unnamed: 8": "Graduação - Com Licenciatura",
    "Unnamed: 9": "Graduação - Sem Licenciatura",
    "Unnamed: 11": "Pós Graduação - Especialização",
    "Unnamed: 12": "Pós Graduação - Mestrado",
    "Unnamed: 13": "Pós Graduação - Doutorado",
}

ETAPAS_FAIXA_ETARIA = {
    "creche": "Educação Infantil - Creche",
    "pre_escola": "Educação Infantil - Pré-Escola",
    "anos_iniciais": "Ensino Fundamental - Anos Iniciais",
    "anos_finais": "Ensino Fundamental - Anos Finais",
    "ensino_medio": "Ensino Médio Regular",
    "ensino_profissional": "Educação Profissional",
    "eja": "Educação de Jovens e Adultos (EJA)",
}

FAIXAS_ETARIAS = {
    "ate_3_anos": "Até 3 anos",
    "4_a_5_anos": "4 a 5 anos",
    "6_anos_ou_mais": "6 anos ou mais",
    "ate_5_anos": "Até 5 anos",
    "6_a_10_anos": "6 a 10 anos",
    "11_a_14_anos": "11 a 14 anos",
    "15_a_17_anos": "15 a 17 anos",
    "18_a_19_anos": "18 a 19 anos",
    "20_anos_ou_mais": "20 anos ou mais",
    "ate_10_anos": "Até 10 anos",
    "20_a_24_anos": "20 a 24 anos",
    "25_anos_ou_mais": "25 anos ou mais",
    "ate_14_anos": "Até 14 anos",
    "25_a_29_anos": "25 a 29 anos",
    "30_a_34_anos": "30 a 34 anos",
    "35_a_39_anos": "35 a 39 anos",
    "40_anos_ou_mais": "40 anos ou mais",
}

ETAPAS_LOCALIZACAO = {
    "creche": "Educação Infantil - Creche",
    "pre_escola": "Educação Infantil - Pré-Escola",
    "anos_iniciais": "Ensino Fundamental - Anos Iniciais",
    "anos_finais": "Ensino Fundamental - Anos Finais",
    "ensino_medio": "Ensino Médio Regular",
    "ensino_profissional": "Educação Profissional",
    "eja": "Educação de Jovens e Adultos (EJA)",
    "classes_comuns": "Educação Especial - Classes Comuns",
    "classes_exclusivas": "Educação Especial - Classes Exclusivas",
}

ETAPAS_TEMPO_ENSINO = {
    "creche": "Educação Infantil - Creche",
    "pre_escola": "Educação Infantil - Pré-Escola",
    "anos_iniciais": "Ensino Fundamental - Anos Iniciais",
    "anos_finais": "Ensino Fundamental - Anos Finais",
    "ensino_medio": "Ensino Médio Regular",
    "classes_comuns": "Educação Especial - Classes Comuns",
    "classes_exclusivas": "Educação Especial - Classes Exclusivas",
}

ETAPAS_SEXO_RACA_COR = ETAPAS_LOCALIZACAO

RACA_COR = {
    "nao-declarada": "Não declarada",
    "branca": "Branca",
    "preta": "Preta",
    "parda": "Parda",
    "amarela": "Amarela",
    "indigena": "Indígena",
}

DATASET_ID = "br_inep_sinopse_estatistica_educacao_basica"

YEAR = 2025

BILLING_PROJECT_ID = "basedosdados-dev"

UF_NOME_SIGLA = {
    "Acre": "AC",
    "Alagoas": "AL",
    "Amazonas": "AM",
    "Amapá": "AP",
    "Bahia": "BA",
    "Ceará": "CE",
    "Distrito Federal": "DF",
    "Espírito Santo": "ES",
    "Goiás": "GO",
    "Maranhão": "MA",
    "Minas Gerais": "MG",
    "Mato Grosso do Sul": "MS",
    "Mato Grosso": "MT",
    "Pará": "PA",
    "Paraíba": "PB",
    "Pernambuco": "PE",
    "Piauí": "PI",
    "Paraná": "PR",
    "Rio de Janeiro": "RJ",
    "Rio Grande do Norte": "RN",
    "Rondônia": "RO",
    "Roraima": "RR",
    "Rio Grande do Sul": "RS",
    "Santa Catarina": "SC",
    "Sergipe": "SE",
    "São Paulo": "SP",
    "Tocantins": "TO",
}
