---
name: Build Docker image
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/cd.yaml
      - pipelines/**/*
      - models/**/*
      - macros/**/*
      - tests-dbt/**/*
      - pyproject.toml
      - Dockerfile
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/cd_staging.yaml
      - .github/workflows/build-docker.yaml
      - pipelines/**/*
      - models/**/*
      - macros/**/*
      - tests-dbt/**/*
      - pyproject.toml
      - Dockerfile
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GH_PAT: ${{ secrets.GH_PAT }}
  IMAGE_NAME: ghcr.io/basedosdados/prefect-flows
jobs:
  build-container:
    name: Build Docker image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: gabriel-milan
          password: ${{ secrets.GH_PAT }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long,prefix=
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and publish Prefect Agent image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }},${{ env.IMAGE_NAME }}:latest
          # build-args: BD_DBT_SERVICE_ACCOUNT=${{secrets.GCP_SA_KEY}}

      # - name: Build and publish Prefect Agent image
      #   run: |-
      #     docker build --build-arg BD_DBT_SERVICE_ACCOUNT="$GCP_SA_KEY" -t $IMAGE_NAME:$GITHUB_SHA .
      #     docker build --build-arg BD_DBT_SERVICE_ACCOUNT=$GCP_SA_KEY -t $IMAGE_NAME:latest .
      #     echo $GH_PAT | docker login ghcr.io -u gabriel-milan --password-stdin
      #     docker push $IMAGE_NAME:$GITHUB_SHA
      #     docker push $IMAGE_NAME:latest
