---
name: Build Docker image
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/cd.yaml
      - pipelines/**/*
      - models/**/*
      - macros/**/*
      - tests-dbt/**/*
      - pyproject.toml
      - poetry.lock
      - Dockerfile
      # DBT config files
      - dbt_project.yml
      - packages.yml
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/cd-staging.yaml
      - .github/workflows/build-docker.yaml
      - pipelines/**/*
      - models/**/*
      - macros/**/*
      - tests-dbt/**/*
      - pyproject.toml
      - poetry.lock
      - Dockerfile
      # DBT config files
      - dbt_project.yml
      - packages.yml
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: basedosdados/prefect-flows
jobs:
  build-container:
    name: Build Docker image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: gabriel-milan
          password: ${{ secrets.GH_PAT }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long,prefix=
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and publish Prefect Agent image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # ,${{ env.IMAGE_NAME }}:latest
