---
name: DBT Test
on:
  pull_request:
    types: [labeled, opened]
    branches: [main]
jobs:
  test_dbt_model:
    if: contains(github.event.pull_request.labels.*.name, 'test-dev-model')
    name: Test DBT dev model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Get all changed files using a comma separator
        id: changed-files
        uses: tj-actions/changed-files@6cb76d07bee4c9772c6882c06c37837bf82a04d3  # v46
        with:
          separator: ','
      - name: Set up poetry
        run: pipx install poetry==1.8.5
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          cache: poetry
          python-version: '3.10'
      - name: Install requirements
        run: poetry install --no-root
      - name: Run script to test DBT model
        run: |-
          poetry run python .github/workflows/scripts/dbt_run.py \
            --target dev \
            --dbt-command test \
            --modified-files ${{ steps.changed-files.outputs.all_modified_files }} \
            --graphql-url ${{ secrets.BACKEND_GRAPHQL_URL }} \
            --source-bucket-name ${{ secrets.SOURCE_BUCKET_NAME }} \
            --destination-bucket-name ${{ secrets.DESTINATION_BUCKET_NAME }} \
            --backup-bucket-name ${{ secrets.BACKUP_BUCKET_NAME }}
