---
name: table-approve
on:
  pull_request:
    types: [closed]
    branches: [main]
jobs:
  table-approve:
    name: table approve
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'table-approve')
    steps:
      - name: Get changed files in PR
        id: changed_files
        uses: actions/github-script@v8
        with:
          script: |
            const files = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const fileNames = files.data
              .filter(file => file.status !== 'removed')
              .map(f => f.filename)
              .join(',');
            console.log("Changed files:", fileNames);
            core.setOutput("files", fileNames);
      - name: Checkout
        if: steps.changed_files.outputs.files != ''
        uses: actions/checkout@v6
      - name: Install uv
        if: steps.changed_files.outputs.files != ''
        uses: astral-sh/setup-uv@v7
      - name: Set up python
        if: steps.changed_files.outputs.files != ''
        run: uv python install
      - name: Install requirements
        if: steps.changed_files.outputs.files != ''
        run: uv sync --locked --no-dev
      - name: Run prefect flow to execute dbt model in prod
        if: steps.changed_files.outputs.files != ''
        run: |-
          uv run .github/workflows/scripts/prefect_run_dbt.py \
            --dbt-command run \
            --sync-bucket \
            --modified-files "${{ steps.changed_files.outputs.files }}"
        env:
          PREFECT_API_URL: https://prefect3.basedosdados.org/api
          PREFECT_API_KEY: ${{ secrets.PREFECT3_AUTH_TOKEN }}
          BASEDOSDADOS_CONFIG: ${{ secrets.BASEDOSDADOS_CONFIG }}
          BASEDOSDADOS_CREDENTIALS_PROD: ${{ secrets.BASEDOSDADOS_CREDENTIALS_PROD }}
          BASEDOSDADOS_CREDENTIALS_STAGING: ${{ secrets.BASEDOSDADOS_CREDENTIALS_STAGING }}
